### ISSUE TITLE
Allow element position edition by GPS coordinates

### ISSUE THREAD

**Issue by brunetton** [umap-project/umap#1001]
I'm trying to manually place elements on a map with a good precision (not importing from geojson, but using UI)

I'm copying GPS coordinates (example `50.92350,2.11022`) from another online tool (https://www.geoportail.gouv.fr) and I'd like to be able to quickly paste them to a marker on map.

For now I've to separate longitude from latitude, and copy/paste them separately on the properties of my newly created marker:
![image](https://user-images.githubusercontent.com/86322/171655263-97146b69-7bfb-4489-8b6b-c079b0300786.png)

I'd like to have another field titled "GPS coordinates" that is the representation of the coordinates as GPS format (lat and log separated by a comma) that could be used to:
- quickly copy coordinates to standard format
- quickly paste coordinates from standard format to set the new marker position (from https://www.openstreetmap.org for example)

This is somehow related to #1000

**Comment by yohanboniface** [comment]
This is possible by typing the coordinates in the search box and clicking on the pen:

![Image](https://github.com/user-attachments/assets/412840f8-8d4c-49f1-8655-8d34a3b6aaf3)

**Comment by brunetton** [comment]
Thank you :)
