### ISSUE TITLE
Documentation - basic: explain howto start hacking on the project

### ISSUE THREAD

**Issue by brunetton** [umap-project/umap#1002]
@yohanboniface I'm absolutely not a Django dev but after opening #1001 I had the feeling that I probably could implement it by myself. So I cloned the project, read the documentation(s) that I could find, but I didn't find howto achieve the super-basic change of modifying a template:
- I start the server using `umap runserver 0.0.0.0:8000`
- to test the edition, I started to edit `umap/templates/umap/home.html` as it's a simple case (I don't think to be wrong by thinking it corresponds to the homepage)
- I remove a part from the template (for example trying to remove the search bar `{% include "umap/search_bar.html" %}`)
- I stop the server
- I start the server again

=> the homepage is not updated

Did I miss something ?

Thanks

I'd be happy to contribute to documentation to help future devs that could have this same problem.

**Comment by yohanboniface** [comment]
hi @brunetton sorry to hear that and sorry that I've missed the notification and that I'm answering so late!

If I try to reproduce your use case, I see that the search bar is not shown any more, as I would expect. So I'm a bit disappointed :/

One thing that comes to my mind is that you may be running umap with `DEBUG=False` and you have run already `umap collectstatic`, that will collect all statics files and put them in a cache folder inside `STATIC_PATH`. Could you check that ?

Sorry again for my late answer!

**Comment by brunetton** [comment]
Thanks for your answer @yohanboniface 
Since I opened this issue, I think I moved forward and found out that the cause of my problem was the installation of umap. It looks like I installed it onto a venv previousely, and the `umap` command was actually calling this packaged version...
For now the program doesn't starts, but at least I'm now sure umap command actually run the local code in current folder ! I'll run the installation process again when I'll find time fir this to be sure everything is as it should be.

Thanks for your time
