### ISSUE TITLE
Problem in the response

### ISSUE THREAD

**Issue by crk067** [umap-project/umap#1003]
Hi!
I've got an error message "Problem in the response" after trying to open my map containig several layers. All layers are not visible
Could you help me please?
![Screenshot_3](https://user-images.githubusercontent.com/106806287/171823656-28809780-3c3b-4b64-91a8-6249ad17b29e.jpg)

**Comment by MigraMundo** [comment]
Same problem with me! I have several maps in UMap, and only in one of them I have this issue. 

Thanks a lot for helping!

**Comment by davidbgk** [comment]
@crk067 @MigraMundo do you still have that issue?

**Comment by MigraMundo** [comment]
Yeah, still same problem and no solution.

**Comment by yohanboniface** [comment]
Could you share the URL of the map please ?

**Comment by MigraMundo** [comment]
https://umap.openstreetmap.fr/en/map/cartografia-complejidad-transfronteriza_391000#7/18.318/-91.758

This one?

**Comment by yohanboniface** [comment]
Ok, seems that all the layers of this map are missing from the server (this map has no datalayer at all in the file system). That's a mystery.

It's before the February outage  (cf https://github.com/umap-project/umap/issues/1045), so it's something else.

@cquest do you remember by chance if the old versions cleaning script was still running last year and if yes if there is a log somewhere ?

**Comment by MigraMundo** [comment]
Uauuuu.

So everything is missing? Empty? Can't believe it. Is there a solution?

I downloaded this from UMap, but I think may have been after starting
having this issue, so it may not be of help... attached.

Thanks for your help!

**Comment by MigraMundo** [comment]
I tried via GitHub but get a "we don't support that file type" (its a .umap file)

**Comment by yohanboniface** [comment]
can you zip it before ?

**Comment by MigraMundo** [comment]
[Cartografía Complejidad UMap.zip](https://github.com/umap-project/umap/files/11384836/Cartografia.Complejidad.UMap.zip)


Hope it works! (seems so)

**Comment by yohanboniface** [comment]
It is empty, sadly :/

**Comment by MigraMundo** [comment]
So theres no solution and also no explanation? :-(

**Comment by yohanboniface** [comment]
A script to clean some old files has been run at this period, so I suspect this script to have deleted those data. Really sorry about that, but I don't a way to get them back.

**Comment by MigraMundo** [comment]
HS!! What a pity. So bad they didn't warn or make security backup for those
data that was compromised. Mine was neither old or not used, I was working
on it one day, and the other, deleted. OMG.

Not a good publicity for the platform! (in fact, I'm working now with
others, so far, so good, and better).

Thanks for your support!
