### ISSUE TITLE
Location does not work on macOS/Firefox

### ISSUE THREAD

**Issue by fxcoudert** [umap-project/umap#1006]
With latest Firefox (101.0) on latest macOS (12.4):

- I open a map, let's say https://umap.openstreetmap.fr/fr/map/fete-du-phare-du-cordouan_737137#14/45.6190/-1.0278
- I ask the to center on my position
- I get asked for permission, and I say yes:
![Capture d’écran 2022-06-08 à 16 07 37](https://user-images.githubusercontent.com/1980544/172637653-08aa6f35-4816-4730-b63b-1efb872695ea.png)

-  But nothing happens… the button stays "pressed":
![Capture d’écran 2022-06-08 à 16 08 08](https://user-images.githubusercontent.com/1980544/172637771-f6ac7763-642b-4b7b-b589-4611a9dcd03b.png)

**Comment by davidbgk** [comment]
@fxcoudert is it still the case with your current setup?

**Comment by fxcoudert** [comment]
With Firefox 112.0.2 on macOS 13.3.1, it works.

**Comment by davidbgk** [comment]
Great, I'm closing the issue, thanks for your reactivity!

**Comment by fxcoudert** [comment]
I've opened an issue on Safari, where the same bug is present (and still there)
