### ISSUE TITLE
Version restoration for layer does not work

### ISSUE THREAD

**Issue by Ianunaut** [umap-project/umap#1007]
(For a more detailed description of my issue, see my request over at the help forum: https://help.openstreetmap.org/questions/84421/umap-version-restoration-does-not-work )

I have recently added several dozens of objects to a layer of a new map and saved my progress. After revisiting the map some time later, the objects had disappeared. According to the version restoration function, the data is still saved:
![Versions available](https://i.imgur.com/uZRqB2R.png)

However, the restoration of those previous versions does not work; the objects still neither show on the map nor in the object list.

Is there a way to make the restoration work or at least salvage the data? The map in question can be found [here](https://umap.openstreetmap.de/de/map/bauforum-ulm_24498), "Projekte" being the problematic layer.

**Comment by davidbgk** [comment]
Is it still the case? Can it be related to #1008 ?

**Comment by Ianunaut** [comment]
Firstly, apologies for not coming back to you earlier - I was not notified there was a reply to my old issue.

I just checked the map in question and yes, unfortunately, the problem still persists and was not fixed by some update of sorts. The problematic layer seems to have data stored in previous versions (as shown in the screenshot above: some 30 kilobytes), but said previous versions cannot be restored. I would still be happy to get some hints on how to fix or maybe work around this issue. Maybe the data from previous verisons can be exported in some way and then imported into a new layer?

**Comment by Ianunaut** [comment]
> Is it still the case? Can it be related to [#1008](https://github.com/umap-project/umap/issues/1008) ?

Hello, 

I revisited this project after a while and would like to kindly inquire if you could reopen this issue. The issue still remains, and I don't see it being related to #1008. I would gladly accept a complete data dump which I could use to import into a new fresh map too, as long as it contains the data in the previous versions of the afflicted layer. Thanks!

**Comment by yohanboniface** [comment]
Do you have any message/error in the console when trying to restore ?

**Comment by Ianunaut** [comment]
When I open the map and try to restore a previous version, I get no message/error. As far as I can tell, the map acts like it completed the action but there are no changes to the layers. When I then try to restore another version, I get an error message (red box with an exclamation mark) saying "Fehler in der Antwort" which roughly translates to "Error in the reply".
