### ISSUE TITLE
Error 502 Bad gateway

### ISSUE THREAD

**Issue by rononoa** [umap-project/umap#1008]
hello every one !!
I have a randon 502 Bad Gateway erreur. When trying to log into umap via my osm account.  create a new map or consult an existing map. 
and if I manage to access at the creation of map, adding a layer with Remote Data option does not work

ps: sorry for my bad English ^^'.

**Comment by SaintJimbo** [comment]
Me too - bad gateway from osm login

**Comment by compasseur** [comment]
Me too, same problem for the last 24 hours.

**Comment by daviddelon** [comment]
Same
