### ISSUE TITLE
Problem in the response when enter in a map

### ISSUE THREAD

**Issue by Pierreiozzo** [umap-project/umap#1010]
Hello,

I created a map recently but now, when I enter it, a red banner appears with the message "Problem in the response". No more data appears on the map now.
How can I get through it ? Is there any solution to retrieve the data?
The map link : http://u.osmfr.org/m/750000/

Thanks a lot,

Pierre

**Comment by Pierreiozzo** [comment]
Hello,
I didn't... I just recreate a new map. But now I make a local save every
weeks to be sure to not loose any data.


Regards

**Comment by philstephenrichards** [comment]
This seems to be the case when your map is too large. The first time I experienced this the map was just under 500MB (file size after downloading it). However I have got the same issue with one just under 100MB.  

So I am not sure what the limit is as obviously with the first map it was allowed to grow in stages up to 500MB. 

> Hello
> 
> I created a map recently but now, when I enter it, a red banner appears with the message "Problem in the response". No more data appears on the map now. How can I get through it ? Is there any solution to retrieve the data? The map link : http://u.osmfr.org/m/750000/
> 
> Thanks a lot,
> 
> Pierre

**Comment by tanquist** [comment]
I have a map which I updated successfully this morning. I changed the color and description of three polygons.
I just tried to make another change to the description and got the red "Problem in the response" message.
I do not understand why this is happening. I have maintained this map without issue for several years.
link: https://umap.openstreetmap.fr/en/map/minnesota-restricted-routes_571411

**Comment by tech62** [comment]
Same thing for me, with this error in the console log from browser

` SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Comment by tech62** [comment]
Problem disappear when remove ` UMAP_XSENDFILE_HEADER = 'X-Accel-Redirect' ` from /etc/umap/umap.conf

**Comment by davidbgk** [comment]
I'll close that one as a solution has been provided in #1070

**Comment by tech62** [comment]
If you add this line when following the installation docs, you can remove it in the Umap configuration file : /etc/umap/umap.conf

**Comment by yohanboniface** [comment]
I think there is a confusion here: the initial bug report was not on a custom uMap install, AFAIK. So I think it's unrelated to the XSENDFILE thing.

@Filou70 do you still have the issue, and if yes can you provide the link to the map ?

It can be either a map "too big", or that the server was under load at this very moment.

**Comment by tech62** [comment]
Sorry for the confusion, but with the XSENDFILE directive in umap configuration, i'm encountered the same error message :/
