### ISSUE TITLE
import relations with remote data

### ISSUE THREAD

**Issue by pbalyx** [umap-project/umap#1011]
Hello
I'm trying to use uMap to display relations belonging to a node network.
  -   When I make an Overpass query, exported in json then reread in uMap everything goes well : I have the path of the relations on the map and the table of the tags of the relation in which I can choose what I want to display (name, length, elevation ...).
  -   When I try to do the same thing (with the same request compacted by overpass) using remote data to have an automatic real time import , I get the path of the relations on the map but no tag in the table, not even the name, they are all called with the name of the layer.
Am I missing something or is it just not possible?

 My overpass query  : 
[out:json][timeout:50];
( relation  [ "network:type"="node_network" ] (44.7333816459144,4.368524551391602,44.755144990108455,4.406290054321289););
out geom;

Thanks

**Comment by pbalyx** [comment]
No comments for two years but now I can answer this question myself.

After developing a small Leaflet application to do almost the same thing, I realized what the problem was.
When you tell overpass-turbo to export the result in geojson format, you get a real geojson object, correctly processed by uMap.
But when you make a direct call to the Overpass API, the result is also a Json object but in OSM format. The data content is the same but the keys are different and in the case of a relation, uMap does not decode the properties. (In the case of simple nodes this seems to work. Why?)
However, there is an osmtogeojson library to do the job. It is used by overpass-turbo. Why not in uMap?
With a simple line of code
geojsonobject = osmtogeojson(osm_data);
the result could be sent to the pipe which processes geojson imports which does the job very well.

So I'm going to turn my question into a suggestion for improvement. Could this be done in uMap in the near future or am I still missing something?


A simple example of a uMap to illustrate
https://umap.openstreetmap.fr/fr/map/import-relation_1070763

**Comment by pbalyx** [comment]
Concerning the query, I insist, in the umap example shown the query is exactly the same.
The geojson layer (in blue) is made by loading a file exported from overpass-turbo. The table shows all the keys.
The import layer is made with the same query in remote data. The table is empty and the relation is split in ways.

**Comment by pbalyx** [comment]
Here is a very simple example of what I would expect to get with uMap when the query returns a relation.
https://pbalyx.github.io/tests/overpass_test/overpass_test.html
Always with exactly the same query than in the uMap example I gave above. When I click on the route, I can get the name and the tags content, not only the name of the uMap layer.
Source code is in https://github.com/pbalyx/tests/overpass_test.

**Comment by pbalyx** [comment]
Still no hope of solving this problem? It would be nice though, in conjunction with the current development of a simple Overpass importer for uMap.
A very simple query with this importer, "route=hiking" gives all the hiking trails in the map area. Unfortunately when we click on a route, we only have the name of the layer and not the name of the route and we cannot access the details of the relation.

I took a look at the code (umap.layers) to understand differences with my simple code above but I'm not very comfortable with modern Javascript. It seems to me that the output of osmtogeojson is processed afterwards in a recursive procedure geojsonToFeatures which decomposes each element into sub-elements. So the route relation is decomposed in ways and the name and tags of the relation are lost.
Would it be possible to remove this step or at least to leave it optional if it is useful for other type of relation ?

**Comment by pbalyx** [comment]
This issue has been closed as fixed however, one day after, I don't see any change. 
In the example already shown https://umap.openstreetmap.fr/fr/map/import-relation_1070763 the red route, imported through remote data, has no name and is split in ways, the blue one, imported from a geojson file has the correct behaviour with name, tags and a single line geometry.

**Comment by davidbgk** [comment]
You have to wait for the next [release](https://github.com/umap-project/umap/releases) and deployment.
