### ISSUE TITLE
Typo in Map

### ISSUE THREAD

**Issue by je1977** [umap-project/umap#1012]
Hi,

ich have found a Type in the map in Germany > Dresden. There is missing an n

![grafik](https://user-images.githubusercontent.com/39240528/179451753-1ddbfd9d-013f-4637-acca-44ebea8bc724.png)

**Comment by E3Lmo** [comment]
Why you think it is missing?
In french the name of the city is `Dresde`. So if you use
So if you use https://umap.openstreetmap.de/de/ instead of https://umap.openstreetmap.fr/en/ you will see the name in German language ;)

**Comment by Marc-marc-marc** [comment]
you may also use https://umap.openstreetmap.fr with the standard background layer
