### ISSUE TITLE
Keep logging into wrong account

### ISSUE THREAD

**Issue by AnnaYeung9797** [umap-project/umap#1015]
I got two openstreetmap accounts, signing up with two different gmail. When I tried to log into umap via the second openstreetmap account, the redirected page keeps logging into the first account and loading the map owned by the first account. Even if I use another computer with incognito window and different browser, the same issue happens.

Attached files show the issue, HKMarineLife is the second account that I want to log in to Umap via openstreetmap, Anna9797 is the first account that the page automatically redirected to. 

Any idea on how to fix it? Many thanks!

<img width="1440" alt="log in page" src="https://user-images.githubusercontent.com/90446353/184599416-a4cb72d1-9030-4b2f-92fd-88a944316ade.png">

<img width="1440" alt="logged in" src="https://user-images.githubusercontent.com/90446353/184599311-a05a122e-78ff-4ad6-b757-7696ba0d0089.png">

**Comment by yohanboniface** [comment]
Hi @AnnaYeung9797 did you try recently ? This should have been fixed since version 1.3.0.
