### ISSUE TITLE
Cities are displayed in French

### ISSUE THREAD

**Issue by alexlist** [umap-project/umap#1016]
When trying to create a new map on

https://umap.openstreetmap.fr/en/map/new/#6/51.000/2.000

city names are displayed in French, even though the rest of the UI is in English.

Let's have the city names follow the locale selected / suggested by the browser. My browser only has English and German as languages configured.

**Comment by E3Lmo** [comment]
So as you mentioned German as browser language I can tell that the website is also deployed on the `.de` domain. So the names are no longer french but mostly german. May it helps you out.

**Comment by Marc-marc-marc** [comment]
the osm-fr background layer display name in fr in name:fr exist
switch to the standard openstreetmap layer and you'll have name in the local language

**Comment by davidbgk** [comment]
A solution has been provided, feel free to reopen if you think there is a related bug.
