### ISSUE TITLE
Feature Request: Map Layer for railways

### ISSUE THREAD

**Issue by bickelmeister** [umap-project/umap#1017]
I a mostly interested in railway maps. For this I often create some maps for presentation purposes. I would kindly ask if it is possible to add a new overlay map design like [OpenRailwayMap](https://www.openrailwaymap.org).

**Comment by govvin** [comment]
There's also an option to set a customer background layer for a umap project. 

According to the ORM's API page, the [tile layer](https://wiki.openstreetmap.org/wiki/OpenRailwayMap/API#Tiles) end-point is "http://{s}.tiles.openrailwaymap.org/{style}/{z}/{x}/{y}.png", and don't forget to set a value for {style}.

Seems to work from my end:
![image](https://user-images.githubusercontent.com/5821688/189555185-9b60bea2-5d53-48cf-95ae-c573a587970c.png)

**Comment by yohanboniface** [comment]
You can now add a custom overlay above the background:

![overlay](https://github.com/umap-project/umap/assets/146023/cdb22a9a-f004-4635-b34a-5b7aa59aba01)

Please  reopen if this does not answer your need!
