### ISSUE TITLE
Prevent breaking out of a kiosk browser that uses umap in an iframe

### ISSUE THREAD

**Issue by Michael1337** [umap-project/umap#1018]
Hey there,

is it possible to configure a umap so that users can not break out of a site that uses the umap in an iframe?
I use a umap created on https://umap.openstreetmap.de/ in an iframe as part of a website that I use in a kiosk mode, meaning visitors who walk past the computer screen can only interact with it using touch, but can not open new tabs, jump back in the browser history, or stuff like that. The screen is left unattended 24/7 for the most part.
If I simply include the map with no query parameters, users can click on the link on the bottom right, which will be opened in a new tab. Also, tapping the touch screen with two fingers opens a popup which again can lead to links that open in new tabs. Is there a way to disable certain touch gestures or to remove anything that leads users to a new website?

Kind regards,
Michael

**Comment by yohanboniface** [comment]
Sorry, there currently no such option, and at this time this is not planned.
