### ISSUE TITLE
UMAP_ALLOW_ANONYMOUS = False seems to be ignored

### ISSUE THREAD

**Issue by gribodyr** [umap-project/umap#1019]
Hello, 

When I set `UMAP_ALLOW_ANONYMOUS = False` in my umap.conf file, the expected behavior is that when an unauthenticated user clicks the "Create New Map" button, they are redirected to the login page,

In my case the user is still allowed to create a new map.

Please advise.

**Comment by yohanboniface** [comment]
This should not be the case.
Maybe, this is because there is still the button "Create a Map" ? But then when saving, use will be prompted to login.
Maybe we should hide this button to make this clearer.
