### ISSUE TITLE
Popup content template and remote data properties: can they be combined?

### ISSUE THREAD

**Issue by febeling** [umap-project/umap#1020]
Is it possible to reference properties from the remote data markers in a popup content template?

There is the curly braces syntax for marker attributes, but I can't access properties that's served with the geojson marker objects. 

What I've tried to use as template:
```
Name {name}
Name {properties.name}
Website {website}
Website {properties.website}
```
This is the remote data.
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [12.9873455, 51.987345],
        "properties": {
          "name": "ACME",
          "website": "https://www.example.com"
        }
      }
    }
  ]
}
```
The marker popup does show correctly, but the placeholders remain empty.

**Comment by seppesantens** [comment]
Yes, it's possible. Not sure what is going wrong at your side. Here is an example that works:

Geojson:
![image](https://user-images.githubusercontent.com/17066627/196743650-874556b1-4355-402f-bee4-04e9ac5a59e7.png)

popup template:
![image](https://user-images.githubusercontent.com/17066627/196743772-bd1aa00c-d662-4e98-bc46-859350c0b879.png)

Result:
![image](https://user-images.githubusercontent.com/17066627/196743831-33ab9111-5e10-46ae-93ee-71f72b56ab47.png)

**Comment by febeling** [comment]
@seppesantens Thanks for confirming this, and the full example! I see my bug now, too. The `properties` is a child to `geometry` in my case, not a sibling as it should.
