### ISSUE TITLE
Lien dynamique UMAP - EXCEL

### ISSUE THREAD

**Issue by fgu35** [umap-project/umap#1023]
Je souhaite savoir s'il existe un moyen de lier un calque UMAP avec un fichier de type excel ou cvs de façon dynamique.
L'idée est de modifier la couleur des repères en fonction d'un tableau excel de type:
lat - lon - forme - couleur
ça fonctionne très bien quand on fait l'importation manuellement.
Peut-on l'automatiser? Utiliser une URL pour le fichier excel (le fichier est sur une dropbox)?

**Comment by Al-Hun** [comment]
Bonjour,
Je le fais avec des feuilles de calcul en ligne du grand méchant Gogol. Il faut passer par le partage et publier la page en csv (pas en tsv).
J'avais vu un exemple similaire avec une feuille Libre Office publiée sur un serveur NextCloud, donc modifiable via Libre Office online (cf association La Mouette). Si je retrouve le lien je l'indiquerai ici.

Des infos utiles [ici](https://github.com/umap-project/umap/issues/448)
Cherche "cors url" sur Wikipedia.

**Comment by davidbgk** [comment]
Je ferme car une piste/solution a été proposée, n'hésitez pas à documenter vos usages pour que l'on puisse faire des liens !
