### ISSUE TITLE
[UMAP] unable to edit anymore

### ISSUE THREAD

**Issue by hunaism** [umap-project/umap#1024]
Hi !

So I have very drama-situation :( - have created umap, and now I can't edit it anymore.
(no sharing option was turned on)

Here is the links:
[http://umap.openstreetmap.fr/pl/map/wilczypaluch_804583#19/52.15700/20.96240](http://umap.openstreetmap.fr/pl/map/wilczypaluch_804583#19/52.15700/20.96240)
Thanks for your help !

**Comment by Marc-marc-marc** [comment]
Send an email to umap@openstreetmap.org so I can send you the editing url

**Comment by Marc-marc-marc** [comment]
it's sended
