### ISSUE TITLE
How do I view more than 100 of my own maps?

### ISSUE THREAD

**Issue by brunellop** [umap-project/umap#1025]
Hello there !

On umap I created more than 100 maps, but the "My maps" page only allows me to view the last 100 maps I've created. Can't the limit be eliminated?
Also, why was it never considered to include the 'Search maps' button also on proprietary maps and not only on public maps?

Thank you.

**Comment by Al-Hun** [comment]
Hello !
I'm not yet concerned with the 100 limit (but it's coming...). On the other part I frequently regret the lack for search in my maps, or others. Something like an option 'user:user_name' ?
Thanks.
