### ISSUE TITLE
CSV import from a URL fails without any error

### ISSUE THREAD

**Issue by richlv** [umap-project/umap#1026]
Attempting import from a URL https://data.lvceli.lv/maps/CSV/CSV_SIC_MPPOINT.csv , setting type to CSV.
After clicking "Import" nothing happens - points are not imported, no error message appears.

**Comment by yohanboniface** [comment]
It's a CORS issue: the server hosting the file does not let web pages call it from another domain.

@davidbgk last time I've checked I didn't find a way to identifie a proper CORS error (no specific code or such), but maybe you have an idea ?

**Comment by davidbgk** [comment]
There is no specific CORS error, but as far as I understand it there should still be a network error that we can deal with and display an error message accordingly?

**Comment by richlv** [comment]
Thank you so much for improving this aspect :)

**Comment by davidbgk** [comment]
@richlv you're welcome :)
