### ISSUE TITLE
Item "Leaflet. Storage"“ https://github.com/umap-project/Leaflet.Storage ”Readme Demo address in md“ http://umap.fluv.io/ ”, will jump to other addresses instead of demo, including porn and fraud

### ISSUE THREAD

**Issue by onemue** [umap-project/umap#1027]
Item "Leaflet. Storage"“ https://github.com/umap-project/Leaflet.Storage ”Readme Demo address in md“ http://umap.fluv.io/ ”, will jump to other addresses instead of demo, including porn and fraud

**Comment by yohanboniface** [comment]
Thanks, fixed!
