### ISSUE TITLE
Escaping Special characters in Field Names

### ISSUE THREAD

**Issue by SK53** [umap-project/umap#1028]
I am trying to use an Overpass-turbo produced Geojson file in umap and want to create a link to an OSM object in an interaction pop-up by concatenating the string "https://openstreetmap.org/" with the value of the geojson "@id" field. This works if I do a search & replace on "@id" and replace it with "id", but trying to use fairly standard escape sequences such as backslash or double quotes or single quotes does not work.

The search & replace or export as a .csv are my current workarounds.

If I am missing an escape sequence then this is a request for clearer documentation.

If there is no escape sequence, this is a request for adding it as an enhancement.

http://umap.openstreetmap.fr/en/map/aged-pub-stock_835228 is current umap instance.

**Comment by davidbgk** [comment]
@SK53 can you share the geojson from Overpass-turbo that you try to import?

**Comment by davidbgk** [comment]
It might be the same issue as #676
