### ISSUE TITLE
To set minZoom and maxZoom for a map

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#103]
Originally reported by: **Andrea Borruso (BitBucket: [aborruso](http://bitbucket.org/aborruso), GitHub: [aborruso](http://github.com/aborruso))**

---

It would be very usefule to have the possibiloty set minZoom and maxZoom for a map.
It's would be "a perfect match" with bounding box settings.

Thank you

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/103

**Comment by tordans** [comment]
This feature is available today, right? I think this can be closed.
<img width="370" alt="image" src="https://user-images.githubusercontent.com/111561/154677603-f1ea511e-8228-4f2c-a62b-6d4eada7580d.png">
