### ISSUE TITLE
No contact information at https://umap.openstreetmap.fr/en/about/

### ISSUE THREAD

**Issue by SomeoneElseOSM** [umap-project/umap#1030]
Hello,

Andy from OSM's Data Working Group here.  Someone's got in touch with us, and would like to get in touch with you, and they don't know how to.  The only relevant link on https://umap.openstreetmap.fr/en/about/ is https://wiki.openstreetmap.org/wiki/UMap#Feedback_and_help and that is not appropriate in this case.

Could you add something to e..g the "about" page saying what people should do?

Best Regards,

Andy

**Comment by Marc-marc-marc** [comment]
for general/public help : umap mailing umap@openstreetmap.org
for private/sensitive : admin mailing admin@listes.openstreetmap.fr
for technical/public help (but it's doesn't seems to be the case I suppose) : tech mailing tech@listes.openstreetmap.fr

**Comment by SomeoneElseOSM** [comment]
https://umap.openstreetmap.fr/en/about/ is still a bit light on information.  Users need to click "Feedback" and only there will they see the "for private/sensitive stuff".

On English language websites, "Feedback" usually means "type something into a box which we will then ignore".

Perhaps rename it in English to "Feedback and Contact" or even just "Contact"?

**Comment by yohanboniface** [comment]
Let's make a simple contact link/form in the about page, that should be configurable through the settings.
