### ISSUE TITLE
cannot find my map on https://umap.openstreetmap.co/it/map/visitaltavaltidoneit_2733

### ISSUE THREAD

**Issue by matteomacoratti22** [umap-project/umap#1033]
Hi 
since some time we cannot see the map
https://umap.openstreetmap.co/it/map/visitaltavaltidoneit_2733

The domain itself seems to not be available,

can you help me please?
Thanks

**Comment by davidbgk** [comment]
Hello, that domain does not seem to be existing (anymore?), the main instance is at umap.openstreemap.fr are you sure you typed the correct URL?

I'm closing the issue, please provide more informations about where you found that link and reopen the issue if that is still a problem for you.
