### ISSUE TITLE
Feature request : Printing drawings & plans (A0, A1, A2...)

### ISSUE THREAD

**Issue by ptaluy** [umap-project/umap#1035]
Hi there,

Unfortunately, there is no easy way to produce full paper (A0, A1, A2... format) drawings & plans from umap.

The french land register service offer a print fonction with several size, scale, rotation, orientation and a frame like any professional software.

Is it possible to include such fonction in umap ?

Best regards
![Land_register_tool](https://user-images.githubusercontent.com/1395148/205918412-33c11a1d-2274-4e79-bc5e-69ba068a297a.jpg)
[print_result.pdf](https://github.com/umap-project/umap/files/10166636/print_result.pdf)

**Comment by yohanboniface** [comment]
That would indeed be useful, and there is a start here #1075, but it's a long way to get it work will all features in the map and to have a A4/A3 whatever cut/split.

I'm closing this issue, as we already have one to track this need: #88
