### ISSUE TITLE
part of POIs are not within the map

### ISSUE THREAD

**Issue by Spielmops** [umap-project/umap#1039]
My map: https://umap.openstreetmap.de/de/map/reiseziele-und-campingplaetze_6953#7/51.843/3.367
I am just working in UK and on both data-types: Reiseziele and Campingplaetze. But only the Campingplaetze of UK appear in the map. 1. Each time I login the continue my work, the Reiseziele in UK are not present any more, I have to restore them. Next time I login [goto 1]. The Campsites stay ...

Spielmops

**Comment by davidbgk** [comment]
Alright, I'll close it as a duplicate then 👍
