### ISSUE TITLE
some of my .fr maps deleted and i have no idea why who to ask ?

### ISSUE THREAD

**Issue by sinanisler** [umap-project/umap#1046]
some of my .fr maps deleted and i have no idea why who to ask ?
what to do ?

didn't get any mailr o message as well I use my osm login there.

https://umap.openstreetmap.fr/en

**Comment by Shohreh** [comment]
Same here

**Comment by deuzeffe** [comment]
See https://github.com/umap-project/umap/issues/1045#issuecomment-1436107673

**Comment by sinanisler** [comment]
looks like an update
![image](https://user-images.githubusercontent.com/1686324/220014400-fda8fcb8-f9da-4830-93a3-24bfe7c4bd3f.png)

![image](https://user-images.githubusercontent.com/1686324/220014491-f4703f7f-a4e6-44e6-839a-bad9925982c4.png)


lets wait a bit

**Comment by sinanisler** [comment]
continue on same topic.     #1045
