### ISSUE TITLE
I can't see my UMAP in github

### ISSUE THREAD

**Issue by SaltimbanquiAmarillo** [umap-project/umap#1047]
I don't know why it doesn't work with the ones in the files I uploaded... in google colab it does show perfectly. Someone knows why?

**Comment by marcoXbresciani** [comment]
Same as #1045

**Comment by sinanisler** [comment]
should be fixed now.
you can close the issue.

**Comment by binndr** [comment]
#1045 was fixed for me but now data lost again (only the layers that i saved yesterday).
Offline bakcup I made only shows a few layers not all. Issue not closed, I will make a new one
