### ISSUE TITLE
add info/link about wiki/mailing list on the frontage

### ISSUE THREAD

**Issue by Marc-marc-marc** [umap-project/umap#1049]
user of osm-fr ask help on admin ml
it would be convenient to have the url of the wiki and the umap mailinglist on the main page so that they go to the right place for help

**Comment by yohanboniface** [comment]
There is already a "help" link in the header pointing to the wiki, what would expect instead ? Thanks!

**Comment by Marc-marc-marc** [comment]
I don't know if the interface has changed since February or if it's an ergonomic problem, but we regularly get messages from people who obviously haven't see it... maybe change Help to Help&Contact
