### ISSUE TITLE
Data from map gone since 23 feb. 

### ISSUE THREAD

**Issue by binndr** [umap-project/umap#1050]
I had the same isse as #1045 (all data lost). That was fixed few days ago, but nowi have the same issue again

http://umap.openstreetmap.fr/nl/map/binndr_809360#4/40.61/20.57

**Comment by yohanboniface** [comment]
Hey, as far as I know, there have a been a few hours of data lost. All the edits between the serve issue and the restore have a been lost. Sorry about that! :(
