### ISSUE TITLE
Issues al cargar cualquier capa geoJson, kml,  gpx u otro

### ISSUE THREAD

**Issue by fdcorrea12** [umap-project/umap#1051]
Cuando realizo la carga de una capa me genera este error. 
![image](https://user-images.githubusercontent.com/87347469/222919654-2b379024-aed0-462c-8f66-60f3ba4ec555.png)

El api de generar error 502

![image](https://user-images.githubusercontent.com/87347469/222919734-b40f147f-91fe-46fc-8041-25d9d8e8a9f9.png)

**Comment by yohanboniface** [comment]
Sounds like a server overload. There is a planned upgrade that should fix that, but I'm not sure yet it will be. Should be in a few days.

**Comment by davidbgk** [comment]
@fdcorrea12 I let you reopen the issue if it's still relevant now that the server should have been upgraded(?).
