### ISSUE TITLE
Unable to save new maps

### ISSUE THREAD

**Issue by parlconst** [umap-project/umap#1052]
When I create a new map and try saving it, I get an error message "Problem in the response".
Help please - after the back-up problems a couple of weeks ago, another period of being unable to create maps is not welcome.

**Comment by gymate-1** [comment]
I got the same error message for the last ~9 hours also when I tried saving the updates I made to an old map of mine.

I tried isolating the issue: created a new map, uploaded data with different kinds of extensions to different number of layers. It seems to me that the bug only persists when I try to **save the map with more than 50 KB of data**.

**Comment by parlconst** [comment]
50kb is quite small for a map - I think all of mine are bigger than this.  Very frustrating.

**Comment by tanquist** [comment]
I just got the same error.
I have a map which I updated successfully this morning. I changed the color and description of three polygons.
I just tried to make another change to the description and got the red "Problem in the response" message.
I do not understand why this is happening. I have maintained this map without issue for several years.
link: https://umap.openstreetmap.fr/en/map/minnesota-restricted-routes_571411

**Comment by gymate-1** [comment]
It seems to be working now.

**Comment by tanquist** [comment]
Thank you. Mine is working now.

**Comment by DIPALOT** [comment]
I have the same problem

**Comment by parlconst** [comment]
After working for a while during today, the problem has returned.

**Comment by yohanboniface** [comment]
@osm-fr team is on it!

**Comment by yohanboniface** [comment]
Should be good now! Disk space on the proxy was preventing nginx from creating tmp files.

**Comment by tanquist** [comment]
Thank you @osm-ft team! It is working for me now.

**Comment by DIPALOT** [comment]
yup it works !! thanks !

**Comment by davidbgk** [comment]
Glad it works!
