### ISSUE TITLE
exported iframe code does not work

### ISSUE THREAD

**Issue by cyricium** [umap-project/umap#1053]
When I save my map on Umap and copy the URL in an iframe that I write myself, it's ok.

However, if I export my map from Umap and paste the iframe or the shortened URL :

Firefox answers that the file cannot be found

**Comment by yohanboniface** [comment]
Ah, thanks, interesting! May it be a https vs http issue ? cc @Jocelyn in case you have an idea

**Comment by yohanboniface** [comment]
I meant cc @jocelynj sorry

**Comment by jocelynj** [comment]
No idea - @cyricium : could you give an example?

**Comment by SansPseudoFix** [comment]
Hello,
you can try with: https://framacarte.org/fr/map/issue-1053_154734

The iframe url is: ``<iframe width="100%" height="300px" frameborder="0" allowfullscreen src="//framacarte.org/fr/map/issue-1053_154734?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false"></iframe><p><a href="//framacarte.org/fr/map/issue-1053_154734">Voir en plein écran</a></p>``

``https:`` is missing :)

**Comment by yohanboniface** [comment]
Well, it's a "feature": the `//` means that the browser should decide by itself if going with http or https depending on the parent.

Can you share a page where this iframe is embedded and it can't be loaded ?

**Comment by SansPseudoFix** [comment]
No I haven't. I tried with a local html page.

**Comment by yohanboniface** [comment]
How are you testing ? If you load your html page a file, then the browser will try to load `//xxx` as another file, but if you use an HTTP server for serving the file (eg. `python -m http.server 8080`), then it should load it as an HTTP request.

**Comment by yohanboniface** [comment]
Thanks for your confirmation! :)

I close the issue, please reopen if there is a way to reproduce the issue.
