### ISSUE TITLE
Can't Edit My Umap

### ISSUE THREAD

**Issue by fabest1** [umap-project/umap#1055]
Hi all,
@Marc-marc-marc the edit link  of this [MAP](https://framacarte.org/fr/map/ma-bibliotheque-dobjets-toulouse_117083) which I used 10 days ago today leads me to a blank page. I can provide the edit link it for troubleshooting if usefull.

Would it be possible to link it this map to my account fabestivals@hotmail.com please? 

Thanks and best regards.
Fabien

**Comment by SansPseudoFix** [comment]
Hi,
Please send us a ticket [here](https://contact.framasoft.org/) with [theses informations](https://contact.framasoft.org/fr/faq/#carte-lost-edit) (in french - or [in english](https://contact.framasoft.org/en/faq/#carte-lost-edit)).
Framacarte is using umap but this project hasn't Framacarte's access (to sum up: you're not at the right place to ask help about Framacarte :slightly_smiling_face:  ).
Regards.
