### ISSUE TITLE
Embedded uMap won't load on my webpage?

### ISSUE THREAD

**Issue by collegemapproject** [umap-project/umap#1057]
I've been trying to make a webpage with an embedded uMap - it works fine when I display the html page using my localhost port or directly from the file on my laptop, but when I try to load the webpage on my college www server, the page loads minus the embedded map - which gives the message "u.osmfr.org refused to connect."

I'm not a technical guy, so I don't have any JS or coding in the html page really, just using iframe to embed. Here's the relevant HTML code:

          <iframe width="80%" height="580px" frameborder="5px" allowfullscreen src="http://u.osmfr.org/m/884191/"></iframe>
          <p><a href="http://umap.openstreetmap.fr/en/map/idm-project-trinity-college_884191#16/53.3441/-6.2547">See full screen</a></p>

The only relevant error displayed in the console is "DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND" - which disappears when I disable JS and CSS source maps in the devtools settings - though the map still doesn't load. The map area only says "u.osmfr.org refused to connect." - I've changed all links to https per the advice on similar problems I've seen people have.

The only other clue I can glean from the console is the link to the embedded map shows as status - failed in the network tab, not 404

**Comment by yohanboniface** [comment]
Could you try with https:// instead of http:// ?

**Comment by sfkeller** [comment]
Related to #983 .

**Comment by yohanboniface** [comment]
@collegemapproject do you still need assistance ?
