### ISSUE TITLE
Permissions edition no longer working

### ISSUE THREAD

**Issue by arzhed** [umap-project/umap#1059]
They simply dont appear where they should anymore : there is no "Who can edit" select box in the menu (Step 3 of this guide https://wiki.openstreetmap.org/wiki/UMap/Guide/Define_who_can_edit_my_uMap)

**Comment by yohanboniface** [comment]
Can you be more informative ? Eg. describe what you see or paste a screenshot.

It may be that this is an anonymous map, so the permission management is different.

**Comment by arzhed** [comment]
![screenshot-umap openstreetmap fr-2023 03 29-11_52_20](https://user-images.githubusercontent.com/3858479/228505028-44e6a923-2d49-4ed1-9afb-af2bf9a7e42e.png)

**Comment by arzhed** [comment]
Je suppose que tu es français ? Quand je suis connecté : 

![screenshot-umap openstreetmap fr-2023 03 29-12_24_36](https://user-images.githubusercontent.com/3858479/228505270-d26fbba8-f595-4560-b794-9ee295212b14.png)

Il s'agit de la carte https://umap.openstreetmap.fr/en/map/le-rheu-a-velo-2023_846383 , ce n'est donc pas une "anonymous map" je pense...

**Comment by yohanboniface** [comment]
Bizarre. La carte n'a pas de propriétaire, et possiblement tu n'as plus le cookie qui permet à uMap de te donner les droits. C'est quoi ton compte uMap/OSM ? Je vais l'ajouter à la carte.

**Comment by arzhed** [comment]
L'adresse mail de mon compte OSM est arthursymon@gmail.com, pseudo "arzhed". Merci beaucoup :)

**Comment by yohanboniface** [comment]
C'est fait, dis-moi si c'est mieux

**Comment by arzhed** [comment]
OK effectivement je peux assigner des éditeurs c'est bon. J'aurais bien aimé créer un lien secret par contre, mais quand je ne suis pas loggé je n'ai pas non plus l'option. Enfin si c'est pas possible je vais me débrouiller autrement :) Peut-être en important les données dans une nouvelle carte sinon ?

**Comment by davidbgk** [comment]
@arzhed je vais fermer cette issue car le problème initial est résolu, n'hésite pas à en ouvrir une autre pour le lien secret en anonyme si c'est bloquant 👍
