### ISSUE TITLE
Getting list of one's own maps?

### ISSUE THREAD

**Issue by Shohreh** [umap-project/umap#1062]
Hello,

Unless I missed it, Umap doesn't seem to provide a way to list someone's maps.

Is there a reliable way, besides this type of (Windows) script?

```@ECHO OFF
REM Know of no other way than trial and error to find how many times to loop
FOR /L %%i IN (1,1,15) DO (
  wget -qcO - http://umap.openstreetmap.fr/en/user/joe/?p=%%i | grep -Poha "/en/map/.+?_\d+" | sed -r "s@^(.+)$@http://umap.openstreetmap.fr/\1@"
)
```

Thank  you.

--

Edit: The script above seems to work. I get the same list when scrolling manually in a browser.

--

Edit: Scrolling seems to only show the last fifty maps: Some of my maps aren't in the list :-/

**Comment by vinber** [comment]
this is not what you want http://umap.openstreetmap.fr/fr/user/Shohreh/

**Comment by yohanboniface** [comment]
> Edit: Scrolling seems to only show the last fifty maps: Some of my maps aren't in the list :-/

See also this issue https://github.com/umap-project/umap/issues/1025

**Comment by andrew-black512** [comment]
I think this would be really useful. I have sometimes created more than one map with similar purposes.

Can you unpack what the /?p=%%i is doing. I would like to do something similar on linux.

**Comment by Shohreh** [comment]
It's just the counter in the loop

I had to resort to looping with wget since Umap uses JavaScript to scroll down the list of maps

```
FOR /L %%i IN (1,1,15) DO (
  Current: %%i
)
```

**Comment by davidbgk** [comment]
The limit of 50 maps has been removed.

**Comment by Shohreh** [comment]
Good news.

It'd be even easier to add that basic feature in the UI:

![image](https://github.com/umap-project/umap/assets/1541861/d7737eeb-4149-441e-bd46-ddb15cc8bfe4)

**Comment by yohanboniface** [comment]
What do you mean by "easier" ?

**Comment by Shohreh** [comment]
It's a lot easier to change the UI to and let the user click on "List my maps" than having to write a script to download the list.

`SELECT title FROM * WHERE id=`

**Comment by yohanboniface** [comment]
Why would you run a script ? Why not just going in this page http://umap.openstreetmap.fr/fr/user/Shohreh/ ?

**Comment by Shohreh** [comment]
Because
1. The user had to scroll down manually severals times to see his maps (by groups of five? ten? Awkward)
2. Until very recently, only the last fifty maps were shown. There was no way to see the rest
