### ISSUE TITLE
Ziplines visibility on the default map view

### ISSUE THREAD

**Issue by CharliePlett** [umap-project/umap#1064]
Hi, I would like to request a map update to include ziplines on the default Umap map view.

Below is an example of the standard osm map view and an image of Umap not including the ziplines.

![image](https://user-images.githubusercontent.com/35817820/232269748-fb47cd50-2a46-44ae-939b-824b9b00fdad.png)
![image](https://user-images.githubusercontent.com/35817820/232269773-e704df6b-1c58-42bd-8121-18aa3b1940dd.png)

**Comment by yohanboniface** [comment]
You can change the background of your map to use the OSM one instead of the OSM France one (which is the default for this uMap instance).

And if you want OSM France style to render ziplines, you can open issue there: https://github.com/cquest/osmfr-cartocss
