### ISSUE TITLE
improvement : allow JSON/add fields in descripion + custom stored icons (SVG?)

### ISSUE THREAD

**Issue by jlmxyz** [umap-project/umap#1065]
I would like to add in the name some extra infos
for example I made a map for tourism, and have some extra fields like "interest" "historic interest" "cost" "nature".... each with a icon, and a rate from 0 to 10
I would like to have it displayed below the name of the place 
![image](https://user-images.githubusercontent.com/40383940/232320808-9921e8ec-7448-4ecc-bed7-b97ff549d15f.png)

- so my need is to be able to add extra field in the node properties
- the extra fields could be described in a JSON schema or maybe a "add extra" button and interface to enter arbitrary information
- in description or title be able to reference for example ${D}{key} 

the idea is to have in a single view the information "name of the place + interests" in a graphical way, and maybe later beeing able to filter them (if you're interested in archeological and cities, but not about nature place... or on the opposite if you only like natural place but have no interest in city life....) and also create "area interest" (for example if you want to have a sporty weekend in nature but you don't know where to go, you can choose an area by a single pin displayed and attached to the area but summarizing the number of spots and the average interest of the spots)
thanks and regards

**Comment by yohanboniface** [comment]
> so my need is to be able to add extra field in the node properties

You can add new fields using the "table" view:

![image](https://github.com/umap-project/umap/assets/146023/5ffe58e3-e21b-46f1-8272-dd89e67c9d8d)


> in description or title be able to reference for example ${D}{key}

You can chose which field is used as "label", but at this time no way to use references. I think this is something that could be added, something like a template where one could do very simple things like "{field} + {otherfield}".

cc @davidbgk 

> maybe later beeing able to filter them 

In the next release, there will be an experimental more advanced filter based on a property, cf #1041

![image](https://github.com/umap-project/umap/assets/146023/9bb1384c-bfa3-4fb9-943f-decb89fca7b7)

![image](https://github.com/umap-project/umap/assets/146023/b015e44c-7506-47a8-b1e3-6c4578226c1c)

See an example here, in the demo instance: 

https://umap.yohanboniface.me/en/map/example-of-filter_6457#9/44.5983/4.4742

**Comment by yohanboniface** [comment]
>  in description or title be able to reference for example ${D}{key}

This is actually possible. Say we have a `rating` property in our features, with stars as values:

![image](https://github.com/umap-project/umap/assets/146023/7b5ba7c9-26d6-4c82-bfd0-35c2dda0692c)

Then one can reference it has `labelKey`:

![image](https://github.com/umap-project/umap/assets/146023/f7234d56-743f-45bd-9e11-92aa32fa634a)

And then it will be used when computing the feature label, for example in the tooltip:

![image](https://github.com/umap-project/umap/assets/146023/2c2f4f2d-78c5-4656-add4-b8d0d233a63f)

@jlmxyz would that work for you ?

**Comment by yohanboniface** [comment]
Variable in labels an filters are now live.
