### ISSUE TITLE
Jawg Watermark in .html

### ISSUE THREAD

**Issue by brutez** [umap-project/umap#1066]
Hi,
If i save my map as .HTML i get this jawg watermark displayed:
[tile.jawg.io/light/10/538/328.png?api-key=community](https://tile.jawg.io/light/10/538/328.png?api-key=community)

This also happens when i change the background image to openstreetmap tiles. Shouldnt the watermark go away when not using jawg Files?

**Comment by davidbgk** [comment]
Hello,

Can you provide an image of the watermark being applied? I can't see it from the linked image.
