### ISSUE TITLE
Problem in the response format - Fresh Install

### ISSUE THREAD

**Issue by tech62** [umap-project/umap#1070]
Hi,

After following the docs (https://github.com/umap-project/umap/blob/master/docs/ubuntu.md), i get "Problem with the server response".

I've found simillary cases opened and i've try to answer it (https://github.com/umap-project/umap/issues/1010)

https://github.com/umap-project/umap/issues/827
https://github.com/umap-project/umap/issues/879
https://github.com/umap-project/umap/issues/1003

The only solution i found is to remove `UMAP_XSENDFILE_HEADER = 'X-Accel-Redirect'` from umap configuration to get a functionnal Umap.
Anybody have an idea how to get this work with this header ?

Thanks !

**Comment by yohanboniface** [comment]
Sorry, I just noticed that the documentation was not building since a while, so it was not up to date.

I fixed that. Can you have a look at this https://umap-project.readthedocs.io/en/latest/ubuntu/#configure-x-accel-redirect ?

**Comment by tech62** [comment]
Hi ! 
Can you precise where add the conf or variable ? (/etc/nginx/nginx.conf or /srv/umap/nginx.conf) 

In the "Create a virtualenv and activate it" , you can update the doc with that
` virtualenv venv --python=/usr/bin/python3.9`
`. /srv/umap/venv/bin/activate`

In the /srv/umap/nginx.conf, comment the lines about 443 and SSL or set a certifcate file, if not, Nginx will return an error and will not start.
```
upstream umap {
    server unix:///srv/umap/uwsgi.sock;
}

# configuration of the server
server {
    # the port your site will be served on
    listen 80;
    listen [::]:80;
    #listen      443 ssl;
    #listen   [::]:443 ssl;
    # the domain name it will serve for
    server_name carto.testserver.lan;
    charset utf-8;

    # max upload size
    client_max_body_size 5M; # adjust to taste

    location /ajax-proxy/ {
        valid_referers server_names;
        if ($invalid_referer) {
            return 400;
        }
    }

    # Finally, send all non-media requests to the Django server.
    location / {
        uwsgi_pass umap;
        include /srv/umap/uwsgi_params;
    }

    location /static {
        autoindex off;
        access_log off;
        log_not_found off;
        sendfile on;
        gzip on;
        gzip_vary on;
        alias /srv/umap/var/static/;
    }

    location /uploads {
        autoindex off;
        sendfile on;
        gzip on;
        gzip_vary on;
        alias /srv/umap/var/data/;
        # Exclude direct acces to geojson, as permissions must be
        # checked py django.
        location /uploads/datalayer/ {
            return 404;
        }
    }

    location /internal/ {
        internal;
        gzip_vary on;
        gzip_static on;
        alias /srv/umap/var/data/;
    }
}
```
I had this in the http section of /etc/nginx/nginx.conf
```
proxy_cache_path /tmp/nginx_ajax_proxy_cache levels=1:2 keys_zone=ajax_proxy:10m inactive=60m;
proxy_cache_key "$args";
```

If i add `UMAP_XSENDFILE_HEADER = 'X-Accel-Redirect'` in /etc/umap/umap.conf, restarting uwsgi and nginx, i got "problem in the server response"

**Comment by tech62** [comment]
Hi ! 
Can you precise where add the conf or variable ? (/etc/nginx/nginx.conf or /srv/umap/nginx.conf) 

In the "Create a virtualenv and activate it"  section, you can update the doc with that
` virtualenv venv --python=/usr/bin/python3.9`
`. /srv/umap/venv/bin/activate`

In the /srv/umap/nginx.conf, comment the lines about 443 and SSL or set a certifcate file, if not, Nginx will return an error and will not start.
```
upstream umap {
    server unix:///srv/umap/uwsgi.sock;
}

# configuration of the server
server {
    # the port your site will be served on
    listen 80;
    listen [::]:80;
    #listen      443 ssl;
    #listen   [::]:443 ssl;
    # the domain name it will serve for
    server_name carto.testserver.lan
    charset utf-8;

    # max upload size
    client_max_body_size 5M; # adjust to taste

    location /ajax-proxy/ {
        valid_referers server_names;
        if ($invalid_referer) {
            return 400;
        }

        add_header X-Proxy-Cache $upstream_cache_status always;
        proxy_cache ajax_proxy;
        proxy_cache_valid 1m; # Default. Umap will override using X-Accel-Expires
        gzip on;
        gzip_proxied any;
        gzip_types
        application/vnd.google-earth.kml+xml
        application/geo+json
        application/json
        application/javascript
        text/xml
        application/xml;
        uwsgi_pass umap;
        include /srv/umap/uwsgi_params;
    }

    # Finally, send all non-media requests to the Django server.
    location / {
        uwsgi_pass umap;
        include /srv/umap/uwsgi_params;
    }

    location /static {
        autoindex off;
        access_log off;
        log_not_found off;
        sendfile on;
        gzip on;
        gzip_vary on;
        alias /srv/umap/var/static/;
    }

    location /uploads {
        autoindex off;
        sendfile on;
        gzip on;
        gzip_vary on;
        alias /srv/umap/var/data/;
        # Exclude direct acces to geojson, as permissions must be
        # checked py django.
        location /uploads/datalayer/ {
            return 404;
        }
    }

    location /internal/ {
        internal;
        gzip_vary on;
        gzip_static on;
        alias /srv/umap/var/data/;
    }
}
```

If i add `UMAP_XSENDFILE_HEADER = 'X-Accel-Redirect'` in /etc/umap/umap.conf, restarting uwsgi and nginx, i got "problem in the server response"

**Comment by yohanboniface** [comment]
The nginx conf part should be added in the nginx VHost, which can depend on the OS, but under Debian/Ubuntu, should be in /etc/nginx/sites-enabled/umap.

You can also totally disable the xsendfile feature (so do not set the `UMAP_XSENDFILE_HEADER` setting, and remove the `location /internal` part from the nginx conf) and let python serve the geojson, if you are not expecting a huge load on the server

**Comment by tech62** [comment]
I'm under debian and expecting 100 / 250 potentials users, so this optimization interesting me ^^

**Comment by yohanboniface** [comment]
Can you check nginx error.log ? Should be in /var/log/nginx/error.log

Also uwsgi logs, in /var/log/uwsgi/app/umap.log

**Comment by tech62** [comment]
After setup log in configuration files and restart services, logs are ... empty, i've stopped the services and trying to access to ensure the logs are correctly set, and got error 502 (normal).

But nothing are log about Umap :/

**Comment by yohanboniface** [comment]
Can you share the output of `sudo systemctl status uwsgi` ?

**Comment by tech62** [comment]
`pid: 68570|app: 0|req: 1/1] 192.168.8.119 () {44 vars in 750 bytes} [Wed May  3 12:23:53 2023] GET /fr/ => generated 11469 bytes in 161 msecs (HTTP/1.1 200) 5 headers in 254 bytes (1 switches on core 0)
[pid: 68569|app: 0|req: 1/2] 192.168.8.119 () {44 vars in 750 bytes} [Wed May  3 12:23:55 2023] GET /fr/ => generated 11469 bytes in 163 msecs (HTTP/1.1 200) 5 headers in 254 bytes (1 switches on core 0)`

```uwsgi.service - LSB: Start/stop uWSGI server instance(s)
     Loaded: loaded (/etc/init.d/uwsgi; generated)
     Active: active (running) since Wed 2023-05-03 14:23:36 CEST; 56s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 68461 ExecStart=/etc/init.d/uwsgi start (code=exited, status=0/SUCCESS)
      Tasks: 5 (limit: 4645)
     Memory: 76.3M
        CPU: 1.164s
     CGroup: /system.slice/uwsgi.service
             ├─68560 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/umap.ini --daemonize /var/log/uwsgi/app/umap.log
             ├─68567 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/umap.ini --daemonize /var/log/uwsgi/app/umap.log
             ├─68568 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/umap.ini --daemonize /var/log/uwsgi/app/umap.log
             ├─68569 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/umap.ini --daemonize /var/log/uwsgi/app/umap.log
             └─68570 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/umap.ini --daemonize /var/log/uwsgi/app/umap.log

mai 03 14:23:36 umaplab systemd[1]: uwsgi.service: Succeeded.
mai 03 14:23:36 umaplab systemd[1]: Stopped LSB: Start/stop uWSGI server instance(s).
mai 03 14:23:36 umaplab systemd[1]: uwsgi.service: Consumed 1.547s CPU time.
mai 03 14:23:36 umaplab systemd[1]: Starting LSB: Start/stop uWSGI server instance(s)...
mai 03 14:23:36 umaplab uwsgi[68461]: Starting app server(s): uwsgi -> . done.
mai 03 14:23:36 umaplab systemd[1]: Started LSB: Start/stop uWSGI server instance(s).

**Comment by yohanboniface** [comment]
uWSGI sounds good.
Can you share the full Nginx error.log ?

**Comment by tech62** [comment]
Code Http 200 for all, and the xhr response : `Idÿ4_1682511999634.geojsoneAKÄ0ÿÌ9´uíâÚë'A/dYfÛ±Ì8IRòßMW½èõ½÷ñ½Ò"<¦¬tdçhLxÿÎ"oë]mEYHÝúÎÙ£Y6ôØÃ«º´Yã[±câYÑ·ÖãL±0C)fbOIûñ¼° ©ZFflÀt½±kºÃ}ßíÌ¾kîöýáTÊÉüO6Ãå9`

**Comment by yohanboniface** [comment]
Ah! I thought those was 502, not 200, sorry.

This sounds like body gzip encoded without the correct header. Can you share the headers of a response ?

**Comment by tech62** [comment]
` HTTP/1.1 200 OK
Server: nginx
Date: Wed, 03 May 2023 14:06:17 GMT
Content-Type: text/html; charset=utf-8
Last-Modified: Wed, 26 Apr 2023 12:26:39 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Cache-Control: must-revalidate
ETag: W/"6449187f-eb"
Content-Encoding: gzip`

**Comment by yohanboniface** [comment]
OK, header is there, so that may be a double gzip encoding.

Are you running uMap mater ?

**Comment by tech62** [comment]
Umap master ?

**Comment by yohanboniface** [comment]
How did you install umap ?

**Comment by tech62** [comment]
It's umap Version 1.2.4, installed from repo (pip install umap-project)

**Comment by yohanboniface** [comment]
Ok. Doc is up to date with master, but master is unreleased yet. It should be this Friday.

Would you try to install from git (`pip install git+https://github.com/umap-project/umap`) or could you wait until Friday for an official release ?

**Comment by tech62** [comment]
Thanks for your help, it seems working with 1.3.0a0 version, the XHR request is "human readable".
I can't re-editing the old map and new maps i've created  (The config normally allowing that UMAP_ALLOW_ANONYMOUS = True)

**Comment by yohanboniface** [comment]
> I can't re-editing the old map and new maps i've created (The config normally allowing that UMAP_ALLOW_ANONYMOUS = True)

Inside your virtualenv:

    umap anonymous_edit_url {map_id}

This will give you the edit link to restore the cookie.

**Comment by tech62** [comment]
Is there a var i've to set allowing anonymous contribution without running cli command ?

**Comment by yohanboniface** [comment]
I thought just lost the ability to edit your old anonymous map. But you cannot create new anonymous maps ?

**Comment by tech62** [comment]
I can create new maps, i close the tab, back to the same map and can't editing

```
$ . /srv/umap/venv/bin/activate
(venv) $ umap anonymous_edit_url 4
Loaded local config from /etc/umap/umap.conf
Map is not anonymous (owner: umap)
```

**Comment by tech62** [comment]
It's fine, the permission by default is set to only allow creator to modify the map, when creating a map, don't forget to set this option to "allow all to edit"
![image](https://user-images.githubusercontent.com/16237642/235957595-1de65e06-33cf-4ffe-bd58-6f4d62d85f92.png)

**Comment by tech62** [comment]
If needed, my installation procedure

## Dependency Installation
```
apt install sudo build-essential autoconf python3.9 python3.9-dev python3-virtualenv wget nginx uwsgi uwsgi-plugin-python3 postgresql-13 postgresql-server-dev-13 postgresql-13-postgis-3 git libxml2-dev libxslt1-dev zlib1g-dev
```
## Create folders
```
mkdir -p /srv/umap && mkdir -p /etc/umap
```

## Creating user and give permission
```
/usr/sbin/useradd -d /srv/umap -N umap && chown -R umap /srv/umap
```

## Downloading umap configuration file and variables adjustments 
```
wget https://raw.githubusercontent.com/umap-project/umap/master/umap/settings/local.py.sample -O /etc/umap/umap.conf
```

## Generate/copy new secret
```
python3
import secrets
secrets.token_hex(16)
quit()
```
## Edit Umap Configuration /etc/umap/umap.conf
```
nano /etc/umap/umap.conf
```
```
DEBUG = False
SECRET_KEY = Your_Secret_Generated
COMPRESS_ENABLED = False
COMPRESS_OFFLINE = True
LANGUAGE_CODE = 'fr'
STATIC_ROOT = '/srv/umap/var/static'
MEDIA_ROOT = '/srv/umap/var/data'
COMPRESS_STORAGE = "compressor.storage.GzipCompressorFileStorage"
UMAP_XSENDFILE_HEADER = 'X-Accel-Redirect'
SITE_URL = "http://carto.myserver.lan"
SHORT_SITE_URL = "http://carto.myserver.lan"
```
## Creating user Umap to use with postgres                          
```
sudo -u postgres createuser umap
sudo -u postgres createdb umap -O umap
sudo -u postgres psql umap -c "CREATE EXTENSION postgis"
```

## Creating virtualenv
```
sudo -u umap -i
virtualenv venv --python=/usr/bin/python3.9
. /srv/umap/venv/bin/activate
```
## Umap Installation (DB / Static / UserAdmin)
```
pip install umap-project
umap migrate
umap collectstatic
umap createsuperuser
umap compress
exit
```
## Create /srv/umap/uwsgi_params file with this content
```
nano /srv/umap/uwsgi_params
```

```
uwsgi_param  QUERY_STRING       $query_string;
uwsgi_param  REQUEST_METHOD     $request_method;
uwsgi_param  CONTENT_TYPE       $content_type;
uwsgi_param  CONTENT_LENGTH     $content_length;

uwsgi_param  REQUEST_URI        $request_uri;
uwsgi_param  PATH_INFO          $document_uri;
uwsgi_param  DOCUMENT_ROOT      $document_root;
uwsgi_param  SERVER_PROTOCOL    $server_protocol;
uwsgi_param  REQUEST_SCHEME     $scheme;
uwsgi_param  HTTPS              $https if_not_empty;

uwsgi_param  REMOTE_ADDR        $remote_addr;
uwsgi_param  REMOTE_PORT        $remote_port;
uwsgi_param  SERVER_PORT        $server_port;
uwsgi_param  SERVER_NAME        $server_name;
```

### Create /srv/umap/uwsgi.ini file with this content
```
nano /srv/umap/uwsgi.ini
```

```
[uwsgi]
uid = umap
gid = users
chdir           = /srv/umap/
module          = umap.wsgi
home            = /srv/umap/venv
master          = true
processes       = 4
socket          = /srv/umap/uwsgi.sock
chmod-socket    = 666
stats           = /srv/umap/stats.sock
vacuum          = true
plugins         = python3, logfile
```
### Add proxy directive in /etc/nginx.conf - http section
```
nano /etc/nginx/nginx.conf
```

```
proxy_cache_path /tmp/nginx_ajax_proxy_cache levels=1:2 keys_zone=ajax_proxy:10m inactive=60m;
proxy_cache_key "$args";
```

### Create Nginx Vhost Configuration
```
nano /srv/umap/umapvhost.conf
```

```
upstream umap {
    server unix:///srv/umap/uwsgi.sock;
}

server {
    #the port your site will be served on
    listen 80;
    listen [::]:80;
    #listen      443 ssl;
    #listen   [::]:443 ssl;
    #the domain name it will serve for
    server_name carto.myserver.lan;
    charset utf-8;
    #max upload size
    client_max_body_size 5M; #adjust to taste

    location /ajax-proxy/ {
        valid_referers server_names;
        if ($invalid_referer) {
            return 400;
        }

        add_header X-Proxy-Cache $upstream_cache_status always;
        proxy_cache ajax_proxy;
        proxy_cache_valid 1m; # Default. Umap will override using X-Accel-Expires
        gzip on;
        gzip_proxied any;
        gzip_types
        application/vnd.google-earth.kml+xml
        application/geo+json
        application/json
        application/javascript
        text/xml
        application/xml;
        uwsgi_pass umap;
        include /srv/umap/uwsgi_params;
    }

    location /internal/ {
        internal;
        gzip_vary on;
        gzip_static on;
        alias /srv/umap/var/data/;
    }

    location / {
        uwsgi_pass umap;
        include /srv/umap/uwsgi_params;
    }

    location /static {
        autoindex off;
        access_log off;
        log_not_found off;
        sendfile on;
        gzip on;
        gzip_vary on;
        alias /srv/umap/var/static/;
    }

    location /uploads {
        autoindex off;
        sendfile on;
        gzip on;
        gzip_vary on;
        alias /srv/umap/var/data/;
        # Exclude direct acces to geojson, as permissions must be
        # checked py django.
        location /uploads/datalayer/ {
            return 404;
        }
    }
}
```
## Create symlink of the new configuration in nginx and uwsgi sites/apps enabled folders
```
ln -s /srv/umap/umapvhost.conf /etc/nginx/sites-enabled/umap
ln -s /srv/umap/uwsgi.ini /etc/uwsgi/apps-enabled/umap.ini
```
### Removing nginx default site
```
rm /etc/nginx/sites-enabled/default
```

### Checking nginx conf before enable and restart
```
/usr/sbin/nginx -t
```
### Umap at startup
```
systemctl enable uwsgi nginx
```

### Restarting services to apply vhost configuration
```
systemctl restart uwsgi nginx
```

**Comment by tech62** [comment]
With ```pip install git+https://github.com/umap-project/umap``` i got :
```
CommandError: An error occurred during rendering umap/password_change.html: 'umap/vendors/leaflet/leaflet.css' could not be found in the COMPRESS_ROOT '/srv/umap/var/static' or with staticfiles.
Compressing... (venv) $ 
```

**Comment by yohanboniface** [comment]
1.3.x has been released since then, so I think we can close
