### ISSUE TITLE
Twitter auth broken

### ISSUE THREAD

**Issue by lessormore4** [umap-project/umap#1071]
I'm unable to login to http://umap.openstreetmap.fr. When I click on the Twitter login button, I get "Oops, Server error…".

**Comment by yohanboniface** [comment]
Hi, thanks for reporting this. Seems that the Twitter API has changed, and even the terms for using it. I'll have a look on how to upgrade, but I'm not sure I'll make it quickly :(
Do you have another provider to use in the meantime ?

**Comment by lessormore4** [comment]
Unfortunately, no.

**Comment by yohanboniface** [comment]
Can you try again ?

**Comment by lessormore4** [comment]
It works! Thank you so much!

**Comment by yohanboniface** [comment]
Great! I was easier than I thought :)

**Comment by yohanboniface** [comment]
In case someone is interested: Twitter has changed its ToS, and:
- one must subscribe a plan to use their API (even only for Oauth, it seems), either Basic (100 $/month) or Free
- when using Free plan, only one app is allowed (so I removed all my TestFoo apps)
