### ISSUE TITLE
Firefox embed remembers earlier center and zoom

### ISSUE THREAD

**Issue by tuukka** [umap-project/umap#1105]
When I open in Firefox a page with an embed and I have visited it before, uMap does not obey the center and zoom as set in the map properties or in the embed URL. Instead, it remembers where I left the center and zoom last time I visited the page.

On Chrome, I don't see the same behaviour.

**To Reproduce**
1. Go to https://umap.openstreetmap.fr
2. Share a map embed and put it on a web page.
3. Visit the page in Firefox, pan and zoom.
4. Visit the page again, Firefox somehow remembers where you left last time.

**Expected behavior**
I would expect the embed to open at the configured center and zoom, not where I left off.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser and version: Firefox 113.0.1

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android
 - Browser and version: Firefox 114.0b4

**Additional context**

I checked in the cookies and localstorage, but couldn't find anything. I also viewed the source to make sure there was no center and zoom in the URL of the iframe. Actually, it doesn't matter whether there's a center and zoom or not, it's not obeyed.

Something that would alleviate this issue greatly: if there was an embed option and/or a control to "fit to data", the user could get back to a view where the data is visible. In my use case, I don't really care what the starting center and zoom are as long as the data is visible.

**Comment by yohanboniface** [comment]
Can you share a link to a page where you see this behaviour ?
