### ISSUE TITLE
Pb de connexion avec mon compte OSM

### ISSUE THREAD

**Issue by phjarry** [umap-project/umap#1106]
Quand je veux me connecter avec mon compte OSM, le comportement est normal jusqu'à l'écran "Autoriser l’accès à votre compte"
Quand, je clique sur le bouton "Accorder l'accès"
Il m'envoie sur la page suivante :
https://umap.openstreetmap.fr/complete/openstreetmap/?oauth_token=qvqEAXBKwhpnU8yY82jZ8PY14kqbNiywJ6GWvDGr&oauth_verifier=yXYZPzZtEGQTrQ6C38RU
Et je reçois le message d'erreur : Oops, Server error…

Je dois préciser que j'ai aussi un accès avec mon compte Twitter dont l'identifiant est également phjarry
Et là l'accès est accordé. Mais en me connectant avec Twitter je n'ai qu'une seule carte. Alors qu'avec mon compte OSM, j'en ai plusieurs dizaines
Id OSM : phjarry
Adresse mail : ph.jarry@gmail.com

Merci de ce que vous pourrez faire
Bon courage
Philippe Jarry

**Comment by yohanboniface** [comment]
Hello Philippe, il y a effectivement un conflit entre les noms de tes comptes OSM/Twitter.
À court terme, est-ce que tu peux transférer la carte qui est sur ton compte Twitter vers ton compte OSM ? Comme ça je supprime ensuite ton compte Twitter, et le pseudo sera libre de nouveau.

On essaiera de mieux gérer ce cas à l'avenir, mais c'est histoire que tu puisses retrouver un compte opérationnel :)

**Comment by phjarry** [comment]
Bonjour yohan
Tu peux supprimer le compte twitter avec la carte qui est dessus. C'était
un essai qui n'a pas d'intérêt
Merci

Le ven. 26 mai 2023, 17:20, Yohan Boniface ***@***.***> a
écrit :

**Comment by yohanboniface** [comment]
> Tu peux supprimer le compte twitter avec la carte qui est dessus.

C'est fait :)

**Comment by phjarry** [comment]
J'ai récupéré l'accès à toutes mes cartes
Merci

Le sam. 27 mai 2023, 14:05, Yohan Boniface ***@***.***> a
écrit :
