### ISSUE TITLE
Error 403 nginx/1.18.0 (Ubuntu

### ISSUE THREAD

**Issue by grid56126** [umap-project/umap#1116]
https://umap.openstreetmap.fr/en/map/richard-howe-uk-marked-map_852450#10/51.3821/0.1744 has error 403 and huge swaithes of my infilling have vanished

This map and all others are fine
https://umap.openstreetmap.fr/en/map/germany_775812#10/52.5417/13.7178

I am a huge computer novice and it's taken me forever to work out how to get here! Treat me like a novice please

Huge Smiles

Richard (grid56126)

**Comment by yohanboniface** [comment]
Hi Richard!

Sorry this inconvenience! This should be fixed.

**Comment by grid56126** [comment]
All sorted MANY THANKS

**Comment by grid56126** [comment]
Magic

All sorted

Thankyou so much x x 

⁣Get BlueMail for Android ​

**Comment by AhmedoSemsuri** [comment]
I'm having the same issue with my map. https://umap.openstreetmap.fr/da/map/anatolia-kurdistan-mesopotamia_878806#6/36.022/42.792

**Comment by der-binni** [comment]
The same here with my map as well: https://umap.openstreetmap.fr/de/map/radreise-escape-now_649781#5/45.228/30.586

**Comment by alehaa** [comment]
Unfortunately mine is broken as well.

**Comment by yohanboniface** [comment]
Should be fixed for all maps now. Sorry for the inconvenience!

Please reopen if it's not the case.
