### ISSUE TITLE
Ease OSM objects integration through Overpass with a dedicated simple UI

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#112]
Originally reported by: **BitBucket: [clkao](http://bitbucket.org/clkao), GitHub: [clkao](http://github.com/clkao)**

---

It'd be great if we can simply add way/node/relation from osm as data entries in a layer, and apply styles like current layer nodes.

This allows reusing POI/objects, tracking changes from OSM, and encourages people to edit things on OSM first and simply reference them in umap.

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/112

**Comment by datendelphin** [comment]
I started with a prototype of integrating overpass: https://github.com/sosm/Leaflet.Storage/commit/ec280b45dd0b8a7a534b866d617bc706ce6a60a8
For now it adds a separate category overpass next to remote data. How would that look with the radio button you proposed? I can't find a radio button example in the UI of umap.

**Comment by yohanboniface** [comment]
@datendelphin cool!
Can you share some screenshots of your work so far? And maybe open a pull request so it's easier to review/discuss?

**Comment by datendelphin** [comment]
Here is a screenshot:

![screenshot from 2017-11-01 09-30-33](https://user-images.githubusercontent.com/1568661/32266519-04f7c9d6-bee8-11e7-8a8b-8400137191b5.png)

There are open issues:
- as soon as the settings screen is left, the overpass query disappears
- the turbo usual {{bbox}} is not yet supported

**Comment by davidbgk** [comment]
We might want to use https://geodatamine.fr/ through the [dedicated API](https://geodatamine.fr/doc/) either as a remote layer or as a local copy.
