### ISSUE TITLE
I Can't edit my umap

### ISSUE THREAD

**Issue by Nicolas13300** [umap-project/umap#1122]
Hi,

I've created a umap prior creating the OSM account and after few weeks of use it is now locked for edition.
I understand there is still a possibilty to link the map to my OSM account.
Can someone support on this?

Map link: http://umap.openstreetmap.fr/fr/map/nicolas-benoit-13300_902026#12/45.7106/4.8295
OSM account : nicolas.benoit.13300@gmail.com

I do thank you

**Comment by yohanboniface** [comment]
Hi @Nicolas13300 I need your OSM username, we don't store emails in uMap ;)

**Comment by Nicolas13300** [comment]
Sure Yohan,
And thank you for the follow up.

My username is: Nicolas13300.

Thanks

Nicolas

Le mer. 21 juin 2023 à 13:08, Yohan Boniface ***@***.***> a
écrit :

**Comment by Nicolas13300** [comment]
Well, maybe I'm misunderstanding.
My account name on https://www.openstreetmap.org is well nicolas13300:

[image: image.png]

Is there something I misunderstand?

Thanks again for the support by the way.

Nicolas

Le mer. 21 juin 2023 à 15:05, Yohan Boniface ***@***.***> a
écrit :

**Comment by yohanboniface** [comment]
Have you created an account on uMap itself ? I mean have you clicked on "log in/connexion" ?

**Comment by Nicolas13300** [comment]
Well I can’t remember the way I did.However, clicking on log in/ connexion in umap, I can log in umap via my OSM login.However when I open my map, the edit menu does not appear…Well if it is not possible anymore I will create a new oneThanks anyway for the time passed to support.NicolasEnvoyé de mon iPhoneLe 21 juin 2023 à 16:10, Yohan Boniface ***@***.***> a écrit :﻿
Have you created an account on uMap itself ? I mean have you clicked on "log in/connexion" ?

**Comment by yohanboniface** [comment]
Now you have an account, and I've linked that map to it. :)

**Comment by Oulma23** [comment]
Hello, I am in the same problem than Nicolas, I've created a card (named chantiers EST), and I didn't do it under my account, so now I can't edit t anymore.. Can u help me please ?

**Comment by Nicolas13300** [comment]
Hi Oulma,

Very sorry, but I'm not a developper at all, and then somone helped me.
I guess you should either wait someone read your message on this thread and
help you, or open a new thread which will be more visible.

Regards

Nicolas

**Comment by Oulma23** [comment]
Thanks for that
