### ISSUE TITLE
uMap Horizontal Scroll Bar

### ISSUE THREAD

**Issue by kwalshe62** [umap-project/umap#1131]
**Describe the bug**
Hi, thank you for addressing the issues reported in #1130.
The only remaining issue is around the black horizontal box which becomes fixed over text or photographs. Is it possible to move this to the bottom of the marker description box so as to allow the text to be read or the photograph to be seen in full? 

**To Reproduce**
1. Go to '...' (VERY IMPORTANT, we need to know which instance of uMap is concerned!)

**Expected behavior**

**Screenshots**
![image](https://github.com/umap-project/umap/assets/135322314/87e67b1b-5ca2-4731-954e-7c5640718eb3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Browser, iPhone, iPad.

**Additional context**

**Comment by davidbgk** [comment]
#1146 is more detailed (duplicate)
