### ISSUE TITLE
Basic Public API for stats

### ISSUE THREAD

**Issue by virgile-dev** [umap-project/umap#1137]
**Is your feature request related to a problem? Please describe.**
Was wondering if umap had some kind of public api that can expose some stats like number of maps, number of users etc.

**Describe the solution you'd like**
Here is an example of what we had with decidim, more advanced than what I'm describing but allowed a member of the community to make a dashboard with all known live instances and their basic stats : https://decidim-census.digidemlab.org/
<img width="951" alt="Capture d’écran 2023-06-14 à 09 37 16" src="https://github.com/umap-project/umap/assets/11473995/cb27a942-204e-4768-ba63-96564fe00bc7">

**Describe alternatives you've considered**
Every instances send regularly their data to be agregated by the mainteners.

**Additional context**
Would help measuring the impact of the project.

**Comment by yohanboniface** [comment]
Very lite, but it exists since recently!

https://umap.openstreetmap.fr/stats/

Could be improved if you have other needs :)

**Comment by virgile-dev** [comment]
I do have one, could you expose the version of umap that is deployed on the server. This is will give us an idea of how much up to date an instance is with the last version.
