### ISSUE TITLE
Ability to pin the properties panel in place to prevent auto-hide

### ISSUE THREAD

**Issue by pfbreton-perso** [umap-project/umap#1139]
**Is your feature request related to a problem? Please describe.**
When you want to modify several layers in a sequence (ex:  delete them) the UI panel keeps hiding away. 

**Describe the solution you'd like**
 I would like the ability to prevent the UI panel from fading in and out and pin it in place so it does not auto-hides itself - which forces me to re-enable it.  In some softwares, this is acheived with a little "pin" icon like this but there are other ways to convey the idea:
 
 
![image](https://github.com/umap-project/umap/assets/59520411/062b5684-34e4-403a-8674-e6efad315e40)

**Describe alternatives you've considered**
---.

**Additional context**
Here is an example of the UI panel that keeps hiding away, even if I don't intent it to :

![panel_hiding](https://github.com/umap-project/umap/assets/59520411/3db98f11-2c7b-4d51-97d6-68c914ee846e)

**Comment by yohanboniface** [comment]
Make sense!

The action you are doing in your screenplay is not clear to me, can you explain ? Thanks :)

**Comment by pfbreton-perso** [comment]
Yes sorry this wasn't obvious.

The attached video shows that the panel hides itself when I sav
![panel_hiding](https://github.com/umap-project/umap/assets/59520411/1d3e3c43-55ef-41a3-8617-65cabda6e43e)
e the map after editing or deleting a layer or a point on a map.

**Comment by yohanboniface** [comment]
OK, thanks, that's clearer, and I agree that it's annoying.

cf also those old issues #330 #190
