### ISSUE TITLE
[[geo:{lat},{lon}|Directions]] no longer works

### ISSUE THREAD

**Issue by naturistwiki** [umap-project/umap#1140]
**Describe the bug**
[[geo:{lat},{lon}|Directions]] when used in a Popup content template used to return a link to: `<a href="geo:<lat>,<lon>">Directions</a>`.
Now only `<a>Directions</a>` is returned.

**To Reproduce**
1. Create Popup content template
2. Add [[geo:{lat},{lon}|Directions]]
3. View item popup

**Expected behavior**
Link using html geo schema 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox/Chrome
 - Version: 113.0.2

**Comment by yohanboniface** [comment]
Thanks for the report.

@davidbgk may be related to dompurify ?

**Comment by davidbgk** [comment]
That's my guess too, I'll give it a look 👍

**Comment by davidbgk** [comment]
Indeed: https://github.com/cure53/DOMPurify/blob/main/src/regexp.js#L10

Is `geo:` a standard link scheme?

**Comment by davidbgk** [comment]
Alright, I found the RFC: https://www.rfc-editor.org/rfc/rfc5870.html

**Comment by davidbgk** [comment]
Thanks @naturistwiki for reporting!

**Comment by naturistwiki** [comment]
Working great! Thanks for the quick response!
