### ISSUE TITLE
uMap Popup Direction Bar Overwriting Text

### ISSUE THREAD

**Issue by kwalshe62** [umap-project/umap#1146]
**Describe the bug**
In the popup description box, the directional black bar is now fixed and overwrites the text underneath. This appeared at the bottom of the box previously.

**To Reproduce**
1. Go to '...' (VERY IMPORTANT, we need to know which instance of uMap is concerned!)

**Expected behavior**

**Screenshots**
![image](https://github.com/umap-project/umap/assets/135322314/5e2b59a8-acaf-4b12-8a91-e76ac10f47e0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidbgk** [comment]
Hi Katherine,

No problem, I'll close #1131 if that one is more accurate 👍 

Thanks for reporting!

**Comment by yohanboniface** [comment]
> Go to '...' (VERY IMPORTANT, we need to know which instance of uMap is concerned!)

@kwalshe62 sharing at least an URL to a map would help a lot, so we don't have to spend time recreating the issue with correct context/content, etc.

**Comment by yohanboniface** [comment]
I've been able to reproduce:

![image](https://github.com/umap-project/umap/assets/146023/cf399342-db2b-46d4-a0a1-9008ab4d3c29)

I'll have a look.

**Comment by kwalshe62** [comment]
Thanks very much.

The link is:

https://umap.openstreetmap.fr/en/map/sarah-and-the-priory_650247#5/45.089/1.406

Katherine.

**Comment by kwalshe62** [comment]
Yohan,

Thank you.

The link is:

https://umap.openstreetmap.fr/en/map/sarah-and-the-priory_650247#5/45.089/1.406

Katherine.

**Comment by kwalshe62** [comment]
Thank you Yohan.

Will it take a few days for the change to take effect?

Kind regards,
Katherine.

**Comment by yohanboniface** [comment]
Yes, should be release tomorrow or Sunday

**Comment by kwalshe62** [comment]
Thank you once again!
