### ISSUE TITLE
Permalink to a marker don't show the associated popup

### ISSUE THREAD

**Issue by clwacker** [umap-project/umap#1147]
**Is your feature request related to a problem? Please describe.**
It is possible to obtain a permalink by right-clicking on a marker, and this is a very useful function for providing direct access to a marker. However, if the marker is associated with a popup, the popup is not displayed using the permalink. 

**Describe alternatives you've considered**
On the other hand, if you're viewing Umap data and select a marker, the popup is displayed.

**Describe the solution you'd like**
So it should be possible to view the marker and its popup by entering the permalink directly?

**Comment by davidbgk** [comment]
Hi @clwacker,

You can do that with the advanced export options:
<img width="1884" alt="Capture d’écran, le 2023-06-16 à 11 09 58" src="https://github.com/umap-project/umap/assets/3556/1e0bc0f2-a69c-418c-9b69-f1469bcbc9af">

Let me know if it helps!

**Comment by clwacker** [comment]
Thanks, looks great but I don't see the Direct Link !
I see a short URL at the bottom under the Export options.
<img width="1670" alt="Umap no Direct Link" src="https://github.com/umap-project/umap/assets/97670456/51eed5e7-c0ba-4c7e-b482-d57aa9915f68">
part of my Umap: https://umap.osm.ch/fr/map/bornes-historiques-de-neuchatel_3405#17/46.87797/6.47969

**Comment by clwacker** [comment]
Thanks work great.
I have also seen that I can use the Permalink of the marker and then edit the URL and just add onLoadPanel=none& after the ? sign.
Great support, thanks David and la team

**Comment by davidbgk** [comment]
> I have also seen that I can use the Permalink of the marker and then edit the URL and just add onLoadPanel=none& after the ? sign.

Sure whatever works for you 👍 

Hopefully, the umap.osm.ch instance will be updated at some point :)
