### ISSUE TITLE
Unwanted (?) scroll bar with width and height intégration under Chromium and Google Chrome

### ISSUE THREAD

**Issue by AZWCI** [umap-project/umap#1152]
**Describe the bug**
Always see scroll bar height intégration (even grayed out)

**To Reproduce** **Expected behavior**
insert images, text, iframes...

**Screenshots**
https://i.imgur.com/F96bHWw.png
https://i.imgur.com/Wqcx2Me.png

**Desktop (please complete the following information):**
 - OS: [under MX Linux and Windows 10]
 - Browser [Chromium + Google Chrome]
 - Version Chromium/Chrome [Version 114.0.5735.133]

**Additional context**
Not this "bug" under Firefox.

**Comment by yohanboniface** [comment]
Thanks for your report! Should be fixed in next release/deploy.
