### ISSUE TITLE
Change the pictograms used : to manage layers / change the map background

### ISSUE THREAD

**Issue by Aurelie-Jallut** [umap-project/umap#1165]
The two current pictograms are incomprehensible and do not represent their function.

I propose 2 more understandable pictograms

![image](https://github.com/umap-project/umap/assets/131352601/b0c46fe5-3876-4e7d-8a12-114872e5d2f0)

We'll have to see if the picto library we're using includes these: 
![map-fill](https://github.com/umap-project/umap/assets/131352601/c10fd713-0985-4582-9512-00f4a1f99c4d)
![stack-fill](https://github.com/umap-project/umap/assets/131352601/05573d55-4cd4-4fd7-b599-370cff222093)

**Comment by Aurelie-Jallut** [comment]
![Uploading stack-fill(1).svg…]()

**Comment by yohanboniface** [comment]
We are not using any library for UI pictograms (OSM fr uses pictos from Maki/Nori/Osmic for user to add in markers, though).

So either you have the rights to use those suggested pictograms, either you/I should redraw something similar :)

Our pictograms are in this directory, in *.svg, in 24/16px and black/white:

https://github.com/umap-project/umap/blob/master/umap/static/umap/img/

Exemple for the black 24 px ones:

https://github.com/umap-project/umap/blob/master/umap/static/umap/img/24.svg

Would you update those files or should I ? :)

**Comment by Aurelie-Jallut** [comment]
We can use those from the https://remixicon.com/ and see if they don't clash too much with the others.

![image](https://github.com/umap-project/umap/assets/131352601/aa6106a5-01e5-4396-b27d-0a681c032ce5)

**Comment by Aurelie-Jallut** [comment]
> We are not using any library for UI pictograms (OSM fr uses pictos from Maki/Nori/Osmic for user to add in markers, though).
> 
> So either you have the rights to use those suggested pictograms, either you/I should redraw something similar :)
> 
> Our pictograms are in this directory, in *.svg, in 24/16px and black/white:
> 
> https://github.com/umap-project/umap/blob/master/umap/static/umap/img/
> 
> Exemple for the black 24 px ones:
> 
> https://github.com/umap-project/umap/blob/master/umap/static/umap/img/24.svg
> 
> Would you update those files or should I ? :)
> I can try :)

**Comment by yohanboniface** [comment]
### 1
![Screenshot from 2023-06-23 19-55-14](https://github.com/umap-project/umap/assets/146023/44e38b4d-98fd-4029-a062-e15fe2385e14)
### 2
![image](https://github.com/umap-project/umap/assets/146023/f38cf618-6401-421a-9f34-3c4912b78243)
### 3
![Screenshot from 2023-06-23 19-52-00](https://github.com/umap-project/umap/assets/146023/c7e9a9ef-becf-41cb-b819-eeee96a2bbc7)
### 4
![Screenshot from 2023-06-23 19-50-57](https://github.com/umap-project/umap/assets/146023/1ca4136f-52a0-4191-b388-d6b0826d900a)
### 5
![Screenshot from 2023-06-23 19-49-45](https://github.com/umap-project/umap/assets/146023/d2f6c7c5-3b6f-4fc8-8b2f-8341f0230f85)
### 6
![Screenshot from 2023-06-23 19-48-57](https://github.com/umap-project/umap/assets/146023/4aaf06f0-d9a9-4450-a6b8-5ae18158ef63)


@Aurelie-Jallut about the "background layer icon", pick a number, or I can run the dice again! :)

**Comment by davidbgk** [comment]
Icons can be pretty confusing, especially in uncommon contexts :)

What about buttons with readable labels: [Search], [Fullscreen], [Share], etc. 🙃

**Comment by yohanboniface** [comment]
For datalayers:

![image](https://github.com/umap-project/umap/assets/146023/f83c18c2-473a-454f-b3ea-8ef2585394bf)

(Retina icons needed…)

**Comment by yohanboniface** [comment]
> What about buttons with readable labels: [Search], [Fullscreen], [Share], etc. 

Labels can be confusing too: https://fr.wikipedia.org/wiki/Facile_%C3%A0_lire_et_%C3%A0_comprendre ;)

**Comment by davidbgk** [comment]
¿Por que no los dos? 🤷

**Comment by yohanboniface** [comment]
؟ Porque es un otro ticketto :)

**Comment by davidbgk** [comment]
More seriously, I can't see an icon representing “changing a map background” that would be explicit at first sight.

**Comment by yohanboniface** [comment]
Sure!

Plus here we need to distinguish between "background layer" and "data layer", so for new comers it's a real challenge. I guess here the cultural habits should help (doing the same as other applications), and I understand that's what @Aurelie-Jallut is pushing.
I'm definitely ok to have some sort of label, but I'd say this should be done in a separate move. And I'll let Aurélie push her views on this :)

**Comment by yohanboniface** [comment]
For the record, there is a label on hover, using the `title` attribute, but that indeed may not be enough :)

![image](https://github.com/umap-project/umap/assets/146023/ea525a08-1d0d-4d50-987d-168a9def5334)

**Comment by Aurelie-Jallut** [comment]
On the subject of the picto "**change the map background**"

After a tour of 4 online carto tools, each one does its own thing : 
- small map in a rounded rectangle
- text
- picto layer
- picto layer with arrow

I tried it out 

![image](https://github.com/umap-project/umap/assets/131352601/d678a9c5-ced8-4a9b-9fd8-1bc86c6162ea)

I like the last one, I could do a monochrome version

**Comment by yohanboniface** [comment]
:+1: 

Remember that we need it in SVG, and we need both a light and a dark version (if you need the grey tones, tell me, but I guess you don't :) ).

**Comment by davidbgk** [comment]
> I like the last one, I could do a monochrome version

Maybe the last one works because it has common layer colors?

**Comment by Aurelie-Jallut** [comment]
![image](https://github.com/umap-project/umap/assets/131352601/c4489685-c0a9-44dd-8758-d4e77a01b805)

**Comment by davidbgk** [comment]
The one with colors looks more explicit to me.

**Comment by yohanboniface** [comment]
Done in #1188

**Comment by virgile-dev** [comment]
> On the subject of the picto "**change the map background**"
> 
> After a tour of 4 online carto tools, each one does its own thing :
> 
>     * small map in a rounded rectangle
> 
>     * text
> 
>     * picto layer
> 
>     * picto layer with arrow
> 
> 
> I tried it out
> 
> ![image](https://user-images.githubusercontent.com/131352601/248853821-d678a9c5-ced8-4a9b-9fd8-1bc86c6162ea.png)
> 
> I like the last one, I could do a monochrome version

Hey @Aurelie-Jallut, thanks for pointing out the issue. 
It's awesome that icons are not pixelised anymore !
My preference goes to the one in the middle as the idea of switching map background is clearer. IMHO having a real map image in such a small icon is not really recognizable. I see the PR was already merged and live in production. I guess we'll see what users have to say ^^
