### ISSUE TITLE
Direct link to a filtered data layer

### ISSUE THREAD

**Issue by fusenuk** [umap-project/umap#1167]
I'd like to be able to have a link to my map which includes the name or ID of a data layer within the URL, and when my map loads the only data layer shown is what was named in the URL

To get to the same state currently I have to load the entire map, choose 'See data layers' then select 'Browse data' then I type the name of the data layer in the 'Filter' box on the right side, then I click the icon for 'Bring feature to center' and I'm now viewing an almost empty map except it has highlighted the data layer that I'm interested in and centers the map view around it.

So the functionality to filter out all data layers except the one I want is there and the ability to center the page around that data layer exists, but getting to that end point requires multiple steps. It'd be great to have that automatically happen via an anchor link or similar which specifies the data layer.

**Comment by yohanboniface** [comment]
Have you tried using the "Keep current layers" and "Open current feature on load" option in the export panel ?

![image](https://github.com/umap-project/umap/assets/146023/89f9747e-1887-4235-a82d-921c9c671453)

**Comment by yohanboniface** [comment]
Closing, please reopen if needed!
