### ISSUE TITLE
Allways show tag doesn't work in my map

### ISSUE THREAD

**Issue by hugomvlopes** [umap-project/umap#1172]
I have this map: https://umap.openstreetmap.fr/pt-pt/map/mapa-sem-nome_931913?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false&captionMenus=true

And the source of info is an API who feed's the map via CSV, in the description i have # strings to display the info.
When i click to always show tag, it doesn't work and only show the "icon" in the map.

How can i Solve it?

**Comment by yohanboniface** [comment]
hi @hugomvlopes it seems that the data you are consuming does not have a `name` property, which is the default expected by uMap. So in this case, you need to tell uMap which key to use, maybe it's `location` in your case (`chave de etiqueta`) ?

![image](https://github.com/umap-project/umap/assets/146023/3ce43164-ef7a-4e7a-be68-f970cc955fbe)

You could also use more than one field, for example:

![image](https://github.com/umap-project/umap/assets/146023/ec0fac2f-1912-4570-b752-05be17dbdc50)

**Comment by yohanboniface** [comment]
Hey @hugomvlopes do you still need help ? :)

**Comment by hugomvlopes** [comment]
No, fixed. Thank you
