### ISSUE TITLE
Issues with docker image

### ISSUE THREAD

**Issue by fabiosebastiano-vertical** [umap-project/umap#1178]
**Describe the bug**
Using image 1.3.5 (either from your Docker Hub or by building the source), we encounter the following error during the run:
```
288 static files copied to '/srv/umap/static'.
No valid UMAP_SETTINGS found
CommandError: An error occurred during rendering umap/js.html: 'umap/vendors/leaflet/leaflet-src.js' could not be found in the COMPRESS_ROOT '/srv/umap/static' or with staticfiles.
```

However, when using version 1.3.3, the container starts correctly, but the following issues arise:

1. How to configure the superuser/admin?
2. The login services window is empty. How to configure SSO access?
3. When using a reverse proxy (nginx) and setting up an SSL connection, the following error occurs when trying to save a map:

```
CSRF verification failed. Request aborted.
Reason given for failure:
    Origin checking failed - https://umap.map-hosting.it does not match any trusted origins.
     
In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django’s CSRF mechanism has not been used correctly. For POST forms, you need to ensure:
[...]

```

**To Reproduce**
As mentioned above, running the Docker image 1.3.5 will result in the first error, while using version 1.3.3 will cause the other issues.
Here the docker compose:
```
version: '3.3'

services:
  db:
    image: postgis/postgis:14-3.3-alpine
    container_name: umap-db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
    volumes:
      - /mnt/umap/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - umap-network
  app:
    image: umap/umap:1.3.3
    #build:
    #  context: ./code/umap
    #  dockerfile: Dockerfile
    container_name: umap-app
    ports:
      - 8001:8000
    environment:
      - DATABASE_URL=postgis://--------@--------postgres
      - SECRET_KEY=xyz
      - SITE_URL=https://umap.map-hosting.it
      - UMAP_ALLOW_ANONYMOUS=True
      - DEBUG=1
    volumes:
      - /mnt/umap/data:/srv/umap/uploads
    networks:
      - umap-network
  reverseproxy:
    image: nginx
    container_name: umap-nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /mnt/umap/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/umap/certbot/conf:/etc/letsencrypt
      - /mnt/umap/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - umap-network
  certbot:
    image: certbot/certbot
    container_name: umap-certbot
    volumes:
      - /mnt/umap/certbot/conf:/etc/letsencrypt
      - /mnt/umap/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  umap-network:
```

**Expected behavior**
With version 1.3.5, I expect the container to start without any issues. With version 1.3.3, I would like to understand how to generate the superuser and enable SSO login as on your homepage.

**Desktop :**
 - OS: Debian 5.10.179-1 + iOS 13.4
 - Browser Chrome
 - Version 1.3.5/1.3.3

**Comment by yohanboniface** [comment]
Hi @fabiosebastiano-vertical thanks for the report.

I'll have a look for the 1.3.5 image.

About your other questions:

> How to configure the superuser/admin?

It depends on how you run the image. I'd say with docker-compose, run `docker-compose run app /bin/bash` and then `/venv/bin/umap createsuperuser`

> The login services window is empty. How to configure SSO access?

If you use OpenStreetMap Account, you can add those env vars `SOCIAL_AUTH_OPENSTREETMAP_KEY` and `SOCIAL_AUTH_OPENSTREETMAP_SECRET`.

If you want something custom, you'll have to define a setting file in `/etc/umap/umap.conf` with valid `python-social-auth` config (see https://python-social-auth.readthedocs.io/en/latest/configuration/django.html).

> When using a reverse proxy (nginx) and setting up an SSL connection, the following error occurs when trying to save a map:

Make sure your reverse proxy is keeping all headers, specifically `X-CSRFToken`.

**Comment by yohanboniface** [comment]
> No valid UMAP_SETTINGS found

This is just a warning that no setting file has been found, but if you configured settings through env vars, you can ignore it.

> CommandError: An error occurred during rendering umap/js.html: 'umap/vendors/leaflet/leaflet-src.js' could not be found in the COMPRESS_ROOT '/srv/umap/static' or with staticfiles.

This seems to be this command missing: `umap collectstatic`, which is normally in the endpoint script. Can you detail how you run the image ?

Thanks!

**Comment by fabiosebastiano-vertical** [comment]
Thank you for the answers, I'm trying to integrate them to see if I can solve all the problems.

To run the image, I use two simple start and stop scripts that I use in all my projects. The start script executes:
`docker compose -f ./docker-compose-umap.yml up --build -d --force-recreate
`
The stop script executes:
`docker compose -f ./docker-compose-umap.yml down --remove-orphans
`
Is there a list of parameters that can be passed in the compose ENV?

**Comment by yohanboniface** [comment]
See https://github.com/umap-project/umap/pull/1179/files (not yet merged) for available settings, must of them can be set through en var.

**Comment by fabiosebastiano-vertical** [comment]
Thank you, i'm now trying to apply some basic customization (use of a different logo), but with the docker image it's not as easy as it seems in the [documentation](https://umap-project.readthedocs.io/en/latest/custom/#settings) and my theme.css it's never applied. i've added this line in my docker-compose.yml
`- /mnt/umap/conf/custom/static/umap:/srv/umap/static/umap`
and in that folder i've put the png and the theme.css with a single line:
```
.umap-nav h1 a {
    background-image: url('./img/logo_png.png');
}
```
But everytime I run the container, the app still using the old logo.

**Comment by yohanboniface** [comment]
@fabiosebastiano-vertical a new release 1.3.6 has been issued that should also fix the initial issue with statics. cf #1185 

How is your configuration working, btw ?

**Comment by fabiosebastiano-vertical** [comment]
The configuration is working great right now. I'll give a look to the 1.3.6 version and I'll check if the error is still present.
Thanks a lot.

**Comment by eMerzh** [comment]
Hey here :) 
i was trying to setup compose to have a dev env ... (i don't want to install postgis & all the suff on my main host)

but i sumble upon this using latest master's image and compose.

I replaced
` image: umap/umap:1.3.2` 

with 
```
    build:
      context: .
```
i think it should be, and after the start : 
```
map-app-1  |   Applying umap.0013_datalayer_edit_status... OK
umap-app-1  |   Applying umap.0014_map_created_at... OK
umap-app-1  |   Applying umap.0015_alter_pictogram_pictogram... OK
umap-app-1  |   Applying umap.0016_pictogram_category... OK
umap-app-1  | No valid UMAP_SETTINGS found
umap-app-1  |
umap-app-1  | 302 static files copied to '/srv/umap/static'.
umap-app-1  | No valid UMAP_SETTINGS found
umap-app-1  | CommandError: An error occurred during rendering umap/js.html: 'umap/vendors/leaflet/leaflet-src.js' could not be found in the COMPRESS_ROOT '/srv/umap/static' or with staticfiles.
umap-app-1  | Compressing...
umap-app-1 exited with code 1
```

**Comment by yohanboniface** [comment]
Sounds like it's building with your local sources ? In this case, I'd say you need to run `make install vendors`, so to have JS dependencies files

**Comment by eMerzh** [comment]
hum... but shouldn't it be somewhat in the docker file? 🤔  ...

**Comment by yohanboniface** [comment]
Certainly… I'm not a Docker expert ;)

Can you paste the image build log ?

**Comment by eMerzh** [comment]
ahah same here... i found it handy , but i'm no expert... trying to figuring it out :p
