### ISSUE TITLE
Webpage Freezes when editing coordinates in a placed waypoint. 

### ISSUE THREAD

**Issue by ThePieMonster** [umap-project/umap#1183]
**Describe the bug**
I encountered a bug similar to the below. After placing a point, I am editing the advanced settings - coordinates and the webpage freezes when editing the second coordinate number. 

https://github.com/umap-project/umap/issues/799

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 114

**Comment by yohanboniface** [comment]
Hi @ThePieMonster and thanks for reporting this.

As stated in the issue template, we need a way to reproduce the issue, and ideally a link to a map where the issue occurs.

Thanks!

**Comment by yohanboniface** [comment]
Also #799 has been been fixed with #1168 (which is not released yet).

**Comment by yohanboniface** [comment]
Released. Please reopen if you still have the issue.
