### ISSUE TITLE
`umap collectstatic` does not seem to generate `vendors` directory

### ISSUE THREAD

**Issue by satabin** [umap-project/umap#1185]
**Describe the bug**

I have a fresh install of umap on Debian, done following this guide: https://umap-project.readthedocs.io/en/master/ubuntu
I followed every step in order and checked them twice. Installed version is 1.3.5 (via pip, according to the guide).
The static `umap` directory is not containing any `vendors` directory.

```shell
$ ls /srv/umap/var/static/umap/
base.css       content.css  font.css    img  locale   nav.css            test       twitter.png
bitbucket.png  font         github.png  js   map.css  openstreetmap.png  theme.css
```

When I am trying to compress the files, I get this error:

```shell
$ umap compress
Loaded local config from /etc/umap/umap.conf
CommandError: An error occurred during rendering umap/map_detail.html: 'umap/vendors/leaflet/leaflet.css' could not be found in the COMPRESS_ROOT '/srv/umap/var/static' or with staticfiles.
```

I can also see this specific folder not being there when I load the main page

![Screenshot from 2023-07-01 16-28-45](https://github.com/umap-project/umap/assets/2537737/47b308b9-a8d6-4172-bda2-419bbb5c1e29)

For the configuration I took the [sample one](https://raw.githubusercontent.com/umap-project/umap/master/umap/settings/local.py.sample), which I tuned according to the guide.

Is it possible that the `collectstatic` command is not generating this folder in the current version?

Thanks in advance.

**Comment by davidbgk** [comment]
@satabin we need to document the `make vendors` command can you confirm that it fixes your issue with your setup?

**Comment by satabin** [comment]
From the pip installed version I do not have either a Makefile nor a `package.json` available at hand. Where should this command run from?

**Comment by davidbgk** [comment]
This is a regression introduced in https://github.com/umap-project/umap/pull/1133 we need to release a new version including the vendors folder in statics.

You can `pip install umap-project==1.3.3` for now before we fix it, sorry 😔

**Comment by satabin** [comment]
Ok, I was thinking this was something like that. Thank you for the quick reply. I cloned the source to generate the folder, which I uploaded and it fixed it, in the meantime. But for non source install, I didn't find any solution.

Thanks for this awesome project!

**Comment by davidbgk** [comment]
@satabin I just issued a new release if you want to test https://pypi.org/project/umap-project/
