### ISSUE TITLE
OSM-Fr background

### ISSUE THREAD

**Issue by Bulest** [umap-project/umap#1186]
**Describe the bug**
Hello, on uMap, the OSM-Fr background doesn't work properly. This morning, it showed part of OpenStreetMap background instead of the OSM-Fr background. Now, it displays the OpenStreetMap background. 

**To Reproduce**
1. Go anywhere on the map

**Expected behavior**
The map background is wrong; it displays the OpenStreetMap background instead of OSM-Fr

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 7

**Smartphone (please complete the following information):**
 

**Additional context**

**Comment by yohanboniface** [comment]
Thanks for the report, but this is not related to uMap itself. You may create an issue, but I know from IRC discussions that OSM France admin are working on it.
