### ISSUE TITLE
Locale "pt-pt" stoped working, need to use just "pt" for map to work

### ISSUE THREAD

**Issue by avataranedotas** [umap-project/umap#1187]
**Describe the bug**

Using URL's like https://umap.openstreetmap.fr/pt-pt/map/XXXXX stoped working correcty, to get the correct results the "pt-pt" needs to be replaced with just "pt"

**To Reproduce**
1. Go to https://umap.openstreetmap.fr/pt-pt/map/antenas-mobile-v21_724717
2. Only the pink layer will show data
3. Go to https://umap.openstreetmap.fr/pt/map/antenas-mobile-v21_724717
4. All layers will show data

**Expected behavior**
The URL with pt-pt should work as it always did

**Desktop:**
 - OS: Windows 10 or Ubuntu 20
 - Browser: Same issue with Firefox, Chrome or Brave
 - Version: any

**Smartphone (please complete the following information):**
 - Device: Any android device
 - OS: 12 or 13
 - Browser: stock or chrome
 - Version: any

**Additional context**

**Comment by yohanboniface** [comment]
Tanks for the report, fix is on its way!
