### ISSUE TITLE
Modernize Umap Icon Selection

### ISSUE THREAD

**Issue by ThePieMonster** [umap-project/umap#1194]
**Is your feature request related to a problem? Please describe.**
Modernize the Umap icon selection with the Google Material Icon list.

**Describe the solution you'd like**
Using the below icon list from Google, Umap should have a white and black version for each icon and search field to search the icon names.

In addition, once a icon is selected, a toggle should be used to determine if the white version is wanted instead of the default black version. This will reduce having double the amount of icons displayed in the list.

https://fonts.google.com/icons

<img width="271" alt="image" src="https://github.com/umap-project/umap/assets/11359134/7bda64b7-4f1b-48fc-838c-01776a9b5cdc">

**Comment by googie0815** [comment]
i help myself by "linking" my own icons. i have also found that there are different icon sets depending on which host you use.

http://umap.openstreetmap.fr
https://umap.openstreetmap.de
https://umap.osm.ch
https://umap.geonue.com

everyone uses different symbols

**Comment by yohanboniface** [comment]
New UI and new icons on the OSM Fr server.
