### ISSUE TITLE
Server error with certain OSM Login

### ISSUE THREAD

**Issue by Hedaja** [umap-project/umap#1202]
**Describe the bug**
Logging in with a certain OSM account results in umap replying with the 'Oops, Server error' page. This happens right after granting access to the account information. When I tried it with a different account, it worked without issues

**To Reproduce**
1. Go to umap.openstreetmap.fr
2. Click on Log in/Sign in
3. Click on OSM Login
4. Insert credentials
5. grant permission to access account information
6. umap page but shows Ooops, Server error

**Expected behavior**
Login to umap and see main page

**Screenshots**
![image](https://github.com/umap-project/umap/assets/693781/2205a2d5-c1e0-4c7a-8e58-5a47e308cf79)

**Desktop (please complete the following information):**
 happens on all kinds of platforms and browsers
tested with Linux (Chromium & Firefox) and Android Firefox

Let me know if the specific account name is needed for diagnosis

**Comment by yohanboniface** [comment]
> Let me know if the specific account name is needed for diagnosis

Yes, please, it's certainly #773 :/

**Comment by Hedaja** [comment]
> > Let me know if the specific account name is needed for diagnosis
> 
> Yes, please, it's certainly #773 :/

Thank you for the quick reply
OSM account name is MissionWolf

**Comment by yohanboniface** [comment]
Did you deleted your MissionWolf OSM account and created a new one recently with the same name ?

**Comment by yohanboniface** [comment]
(By recently, I mean around February last year)

**Comment by Hedaja** [comment]
I had created one with Mission:Wolf but that caused trouble with umap nit being able to find it and transfer ownership/editing rights for maps.
so I created the new one without :
I've been using that account with umap for a while it just recently started giving the error

**Comment by yohanboniface** [comment]
Can you try again ?

**Comment by Hedaja** [comment]
I tested it and it's working again
Thank your very much
really appreciate the quick help
