### ISSUE TITLE
More icons to manage line squares

### ISSUE THREAD

**Issue by sorgina** [umap-project/umap#1204]
**Describe the bug**

Hi

Not being English speaker I've translated with DeepL. I hope it's clear and it's also my first time posting here :)

When I put my cursor on a small square of a line (to delete it for example) no no icon appears (for markers and polygons it's OK). polygons):

**Screenshots**

![2023-07-13 15_23_57-Le contenu - uMap — Mozilla Firefox](https://github.com/umap-project/umap/assets/13588786/b7d7f702-4125-439c-9f84-4b39549fa646)

**Desktop (please complete the following information):**

 - OS: Windows 10

 - Browser Firefox

 - Version 115

**Comment by yohanboniface** [comment]
Thanks for the report!

I've pushed a fix, and it will be released soon.

**Comment by sorgina** [comment]
Thanks for the work. And I'd like to take this opportunity to thank you for this really great tool :)
