### ISSUE TITLE
Can't edit map (Woops! Someone else seems to have edited the data.)

### ISSUE THREAD

**Issue by CharliePlett** [umap-project/umap#1212]
**Describe the bug**
When I want to add a line to my map project and hit the save button then I get this error message _Woops! Someone else seems to have edited the data. You can save anyway, but this will erase the changes made by others._ Even after clicking Ok to saving over other data it just refuses to save it.

**To Reproduce**
It happens only when I edit this map [Places I've Been](http://umap.openstreetmap.fr/en/map/places-ive-been_259931).
I managed to save a few pins the first time that happened, but now I can't even save pins anymore.

**Desktop**
 - OS: Arch Linux & Windows 11
 - Browser: Firefox
 - Version: 115.0.2 on Arch

**Smartphone**
 - Device: Xiaomi Redmi Note 10 Pro
 - OS: Android 13
 - Browser: Firefox Nightly
 - Version: 117.0a1

**Additional context**
I have cleared cookies on the two PC's that I've used this map on already. And also my Smartphone.

**Comment by yohanboniface** [comment]
That's annoying, sorry about that :/

Can you open the developer tools of your browser (`ctrl-shift-I`), then make a change that will reproduce this behavior, and then individuate the URL that cannot be saved (I don't know how comfortable your are with this operation, in case you're not: the URL will be in red in the list).

**Comment by yohanboniface** [comment]
OK, I've been able to reproduce the issue thanks to https://forum.openstreetmap.fr/t/modification-dune-carte-umap-aie-quelquun-dautre-semble/16185/6

The issue arise with datalayers created before uMap `1.3.0`, in case the geojson file and the geojson.gz was not created on the same second.

If you can tell me which datalayer is impacted (the URL that creates the error), I can fix it by hand. Otherwise let's wait for a proper fix to be released, hopefully soon, today or tomorrow, next week-end at the latest.

**Comment by LaurentChm** [comment]
Hello Johan, I have the same issue. I was editing this map https://umap.openstreetmap.fr/en/map/published-studies-on-hot-spot-detection-co2-ch4_809410 this morning. All went fine. But I now suddenly have the same _Woops! Someone else seems to have edited the data. You can save anyway, but this will erase the changes made by others._ message as above. It seems that there is only one affected layer in the map  ("CH4 / General"). Any possible help?

**Comment by yohanboniface** [comment]
@LaurentChm can you try again ?

**Comment by LaurentChm** [comment]
Still the same :(

**Comment by yohanboniface** [comment]
Are you sure about the impacted datalayer ?

**Comment by LaurentChm** [comment]
Yes, "CH4 / General"

**Comment by LaurentChm** [comment]
It works :) Thanks a lot!

**Comment by CharliePlett** [comment]
Thanks for fixing it. It works now.
