### ISSUE TITLE
Dynamic property with a colon does not seem to work

### ISSUE THREAD

**Issue by richlv** [umap-project/umap#1213]
**Describe the bug**
When a [dynamic property](https://wiki.openstreetmap.org/wiki/UMap/Guide/Text_formatting) with a colon in the name, like "description:en", is used, it is not displayed.

**To Reproduce**
1. Go to http://umap.openstreetmap.fr
2. Create a map with dynamic remote source that includes objects with description:en
3. Include "{description:en}" in the layer properties, description.
4. Save the map, observe description:en not included.

This can also be observed in http://umap.openstreetmap.fr/en/map/piena-galdi_941935#15/56.2910/27.4384 , node in question is https://www.openstreetmap.org/node/10940304079 .

**Expected behavior**
"description:en" is displayed.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 115.0.2

**Additional context**
Tried doublequoting it and escaping the colon.

**Comment by yohanboniface** [comment]
> Include "{description:en}" in the layer properties, description.

Maybe that's where the issue is: if `descrition:en` is a property of the features, then using this in the **layer's** description would not do anything. Perhaps you want to change the popup content template in the "interaction options" of that layer ?
![image](https://github.com/umap-project/umap/assets/146023/f6d4d2f4-3b5e-44a8-b857-aed6c230fe68)

**Comment by richlv** [comment]
Thank you so much, I guess I got confused about the fact that "description" is shown by default - I had included both "description" and "description:en", and thought that only one showed up :)

Properly using the popup template makes it all work.

![dynamic popup](https://github.com/umap-project/umap/assets/112888/5b3a4615-e620-4373-9abc-55b438a70ac5)

Closing.
