### ISSUE TITLE
Login using third party application

### ISSUE THREAD

**Issue by CartierPierre** [umap-project/umap#1219]
I'm looking for a feature that allow account from other site (in my case, Wordpress self hosted) to authenticate with same account in uMap.  
It can be possible throught OAuth, SAML, OIDC or Shibboleth (IDP).  
Do you have any idea how to do that ?
Thanks a lot

**Comment by yohanboniface** [comment]
@CartierPierre did you need more info/help ? :)

**Comment by yohanboniface** [comment]
Closing, do not hesitate to reopen if needed. Also, I'm curious about what you've been able to do and what you're doing with uMap, if you have 5 minutes to share, that would be appreciated :)
