### ISSUE TITLE
wrong file extension on gpx export (firefox for android)

### ISSUE THREAD

**Issue by QJKX** [umap-project/umap#1225]
On f-droid fenec (roughly the same as firefox for android) and umap.openstreetmap.fr an exported gpx has a file extension .xml

This could be firefox using the mime type to set the file extension, and the server sending an xml mimetype instead of a the correct gpx mime type (application/gpx+xml).

**Comment by yohanboniface** [comment]
Thanks for the report, it will be fixed in next release!
