### ISSUE TITLE
"from zoom" and "to zoom" options for "Import data"

### ISSUE THREAD

**Issue by iriman** [umap-project/umap#1227]
Hi!
umap feature "Remote data" has nice options to hide content based on zoom levels, "from zoom" and "to zoom":
![remote data panel](https://github.com/umap-project/umap/assets/8467903/6e40de4b-5eb1-448d-880a-edae9791f28f)

but I couldn't find them for "Import data":
![import data panel](https://github.com/umap-project/umap/assets/8467903/fa16174a-5e62-471c-bdd5-15bb29e3d1a7)

As an example, with my first project [map_943303](https://umap.openstreetmap.fr/en/map/map_943303) I used some data in geojson format to display some boundaries. I want to hide them for zooms above 11. On the other hand, running a query for this nearly static data isn't needed so I prefer to use "import data" rather than "remote data".

**Comment by yohanboniface** [comment]
Thanks for the report.

I think this is similar to #473.
