### ISSUE TITLE
Export Options

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#123]
Originally reported by: **Badita Florin (BitBucket: [baditaflorin](http://bitbucket.org/baditaflorin), GitHub: [baditaflorin](http://github.com/baditaflorin))**

---

I am communicating now with one of the people from mapjam, and they would want to use umap for mapping and showing the results. 

One of their requirements is to ability to save back the map as a CSV or some other format. 
From what i know and tried to find out in the setting, this is not possible yet.

Tom Llewellyn
6:00 PM (1 hour ago)

to Yohan, Adrien, me 
The idea with the map Jam is that communities will map out their local resources and have a unique web address where others can find and contribute additional local resources. Groups will first compile their information in a spreadsheet and then upload it to a map either as a single or ideally multiple layers (5-10).

During the map jam multiple people may be adding to the map at the same time (especially if there is a decentralized event).  Once information is on the map is it easy to get it all back out as a CSV? We are also hoping to make community directories that will compliment the maps and also contain local "off the map" mobile or web based resources.

Last year some maps had 10-20 locations in smaller communities while others had as many as 200 in bigger more active cities and we anticipate the same thing this year.  

We will also have a lot of groups who will (hopefully) be able to transfer the information that they compiled last year on for their google maps (through spread sheets) to OSM.  I just tried uploading one of the layers of the map that I made for Asheville as a csv (in umap) and it won't seem to take.  I get  red bar across the top of the screen with no explanation.

I hope that helps to clarify what we are hoping to do.

Thanks for your help,
-Tom

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/123

**Comment by lupa18** [comment]
Here they manage the csv export option: http://geojson.io

**Comment by berteh** [comment]
Old issue, but as it is still open I wanted to make it clear last time I checked geojson.io only exports the "marker" type features in their CSV (dots, if you like). The more complex shapes are simply dropped from that format.

I think geojson is pretty good export format (also being json you nowadays have parsers in all web frameworks and languages)... and if you need to view it in tabular form there's always the easy but ugly option to turn it into a table with repeating columns, like https://konklone.io/json/ does.

**Comment by yohanboniface** [comment]
Closing in favor of #608
