### ISSUE TITLE
Please allow us to save the map up to 500MB

### ISSUE THREAD

**Issue by worldconflictmap** [umap-project/umap#1230]
**Describe the bug**
When I try to save a map on UMAP, the error message "Problem in the response" appears.
I found out that the map's size in KML is 48.5MB, and the full map data is 189MB.
Please allow us to save up to 500MB or more.

**Expected behavior**
I expected the map will be saved without any problem.

**Screenshots**
![스크린샷(4045)](https://github.com/umap-project/umap/assets/140384925/8cf9c81e-689b-4376-b258-7ec0d488b281)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser : Firefox
 - Version 115.0.2

**Additional context**

**Comment by worldconflictmap** [comment]
@yohanboniface Would you please advise me on this issue?

**Comment by yohanboniface** [comment]
> I found out that the map's size in KML is 48.5MB, and the full map data is 189MB.

That's already a lot of data!

Have you tried simplifying it ? For example using https://mapshaper.org/ (uMap may allow this at some point, but not yet).

You may also use more targeted layers, and I'd suggest not to display them all on load, letting people load what they want.

> Please allow us to save up to 500MB or more.

It's unlikely. This is too much data for uMap/Leaflet to handle at this time (cf #618 for example).

**Comment by worldconflictmap** [comment]
Thank you for the quick response. I'll try to simplify the data.
