### ISSUE TITLE
[suggestion] Simplify list of background maps

### ISSUE THREAD

**Issue by Shohreh** [umap-project/umap#1234]
Hello,

I have a suggestion for the Background section: Simplify the list by eg. listing just the five most used maps based on user data, while still making it possible to change that list for those needing other maps.

I counted 39 (!) of them, most being very similar maps.

Personally, I very rarely need more than OSM, OpenCycleMap/CyclOSM, OpenTopoMap, and OSM Transport.

Cheers,

**Comment by overflorian** [comment]
Hi, my suggestion would be to 
1. Define a list of very limited amount (3 ?) of maps, based on how often they are already chosen by the users and useful they are.
2. Display them by default
3. Allow the user to choose any map he/she like with a advanced button

This is the UX we use on https://gribrouillon.fr, feel free to use the already written code.

**Comment by Shohreh** [comment]
Thanks, but it's not for me: It was a general suggestion.

I find there are way too many available backgrounds available, and no easy way to only see and access the two-three I commonly use.

**Comment by overflorian** [comment]
100% agreed! My suggestions is for the development team ;)

**Comment by Shohreh** [comment]
Nice. Ideally, the user could choose what layers to include by default in all their maps since it's likely they commonly use the same — personally, regular OSM  + OpenCycleMap + Transport + Topo.
