### ISSUE TITLE
'Popup' and 'Popup (large)' the same width now?

### ISSUE THREAD

**Issue by Xonnext** [umap-project/umap#1236]
Are 'Popup' and 'Popup (large)' the same width now as a result of the not showing the horizontal scroll bar? Selecting the 'Popup' shows the same result as selecting the 'Popup (large)'.

_Originally posted by @Xonnext in https://github.com/umap-project/umap/issues/1199#issuecomment-1652304833_

**Comment by yohanboniface** [comment]
I'll have a look. But:

- please don't cross post (people have another life than just answering issues in Github, so please give them time)
- please include a link to a map where the problem appears, as stated in the issue template, because we need to know which instance is used and we need to have the full context, the issue may be related to another settings

**Comment by Xonnext** [comment]
Ok, but github is magic for me and I was unsure if a question added to a ‘closed’ issue would be read. No hurry at all. Sorry and excuses…Cees Op 28 jul. 2023 om 09:10 heeft Yohan Boniface ***@***.***> het volgende geschreven:﻿
I'll have a look. But:

please don't cross post (people have another life than just answering issues in Github, so please give them time)
please include a link to a map where the problem appears, as stated in the issue template, because we need to know which instance is used and we need to have the full context, the issue may be related to another settings

**Comment by yohanboniface** [comment]
No worry. Please add more context on where you see the issue, etc. That will make our life easier and we will debug/answer faster. :)

**Comment by Xonnext** [comment]
Please look at: https://umap.openstreetmap.fr/nl/map/nederland-routemaps-nl_795244#7/52.510/5.570

**Comment by yohanboniface** [comment]
Sorry to say that, but this is not helpful.
Please add more information on where/which feature to click, what you expect, what you see, etc.

I had a quick look and did no see a popup large defined. So I need more info.

**Comment by Xonnext** [comment]
In this map and other maps I can only create popups with the same width now. If I choose Popup in the maps I get the same width as when I choose Popup (large). So even if I have NOT defined Popup (large) in that map, I do get the size of the Popup (large). There is no Popup with the former width anymore.

**Comment by Xonnext** [comment]
This is the size I had before your latest update:
![image](https://github.com/umap-project/umap/assets/7556062/b2fc3737-951e-4994-9e48-189675393df3)
Now it lookes like this:
![image](https://github.com/umap-project/umap/assets/7556062/ec5ce9ff-f598-4f17-b44d-75f884336adb)
And I cannot get the smaller size anymore.

**Comment by Xonnext** [comment]
To illustrate:
![image](https://github.com/umap-project/umap/assets/7556062/721bc180-02ef-4cf8-909a-c88f69bd7405)

**Comment by Xonnext** [comment]
Update.

I had 2 problems:
- suddenly white space on the right site in the popup (right picture);
- popups in only one size.

The white space on the right seems to have no connection with the second problem. It is caused bij my own css-settings. Those settings were needed before the latest UMAP-update, but after the update things have changed in UMAP and the correction is not needed anymore. Just found that out and will correct that myself. Sorry

What remains  I think is the one-size popup,. 

And I love the latest update, in particular the new Dasboard and the Search in the Dashboard...! ;-)

**Comment by yohanboniface** [comment]
I don't think this is a recent change. At least, I tested with version 1.2.4, which has been released years ago, and I see the same behaviour apparently. I'll make bigger the iframe in a popup large, but you can still control the width for you iframe with something like: `{{{https://myiframe.html|400*500}}}`

**Comment by Xonnext** [comment]
Thanks Yohan for your support.
