### ISSUE TITLE
New configuration option: Default Map Visibility

### ISSUE THREAD

**Issue by eiclu** [umap-project/umap#1244]
**Is your feature request related to a problem? Please describe.**
I would like for all maps on my instance to be non public by default. Right now this is not possible.

**Describe the solution you'd like**
Configuration options for "Who can edit by default" and "Who can view by default"

**Comment by yohanboniface** [comment]
Sounds legit! :)

That would be new Django settings, like `DEFAULT_SHARE_STATUS` and `DEFAULT_EDIT_STATUS`, is that ok for you ?

**Comment by yohanboniface** [comment]
Do you think you can make a PR for that ? If not, I'll do it, it's an easy one, anyway :)

**Comment by eiclu** [comment]
Will do 👍

**Comment by eiclu** [comment]
OK I give up. It seems the defaults are set directly in the database. I tried setting the new defaults in the MapCreate class, but it didn't seem to work. How would you implement this? @yohanboniface

**Comment by yohanboniface** [comment]
I'll have a look :)

**Comment by yohanboniface** [comment]
@eiclu see #1245 :)

**Comment by eiclu** [comment]
Ah I see. Thanks :)
