### ISSUE TITLE
Layers disappear when I scroll down the mouse

### ISSUE THREAD

**Issue by worldconflictmap** [umap-project/umap#1257]
**Describe the bug**
When I scroll down the mouse, all layers suddenly disappear. 

**To Reproduce**
1. Go to any map, such as http://umap.openstreetmap.fr/ko/map/map-showing-languages-usually-used-for-communicati_568525#8/47.113/28.581
2. Scroll down the mouse
3. All layers disappear

**Expected behavior**
I of course expected the layers will not disappear.

**Screenshots**
![image](https://github.com/umap-project/umap/assets/140384925/2bcf6a59-bda0-48e2-a682-ca9ecae33e24)
(Before scroll down)
![image](https://github.com/umap-project/umap/assets/140384925/57fa0aef-8399-4a86-92cf-f3f5ef8c7e1f)
(After scroll down)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Safari
 - Version : Safari 116.0.2

**Additional context**
This error occurred since 11PM (UTC+9), 15th August 2023.

**Comment by yohanboniface** [comment]
Oops. Thanks for the report, I'll have a look!

**Comment by Xonnext** [comment]
Same problem here in all maps and different backgrounds. Thanks for helping...

**Comment by yohanboniface** [comment]
Should be fixed, sorry!
