### ISSUE TITLE
Is there a plan for payed version of Umap?

### ISSUE THREAD

**Issue by worldconflictmap** [umap-project/umap#1258]
**Is your feature request related to a problem? Please describe.**
Is there any plan for payed version of Umap which will allow us to save up to 1GB of data on a map?

**Describe the solution you'd like**
I wish a payed version of Umap like Arcgis Online will be launched. If it allows us to save up to 1GB of data and share it to others, I'm willing to pay for it.

**Describe alternatives you've considered**
In order to upload and save large size datas, I'm trying to use Arcgis Online, but it has more errors than Umap.

**Additional context**
I'd requested to allow us to save large size datas on here. https://github.com/umap-project/umap/issues/1230

**Comment by yohanboniface** [comment]
Sorry, there is no such plan, AFAIK.
But uMap is open source, so someone may host it for paid for you (but I don't know such service).
Also, 1Go is a lot of data, and will never be loaded by a browser. One option is to use services that better prepare the data server side, like felt.com or carto.com.
