### ISSUE TITLE
Map is slow and lagging

### ISSUE THREAD

**Issue by theraquet** [umap-project/umap#1259]
Is there any way to speed up the load time of my map and get it to run faster when I zoom and pan around. It is a 11mb map file when I save it. Is this too big and causing the slowness of the viewing?

Can I make it a smaller file somehow without deleting any of the map points? or can I limit zoom to make it run faster?

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser Chrome, Firefox

**Comment by yohanboniface** [comment]
Answer is certainly "yes, map is too big", but hard to say more without a link to the given map…
