### ISSUE TITLE
[suggestion] Show/hide all layrrs

### ISSUE THREAD

**Issue by Shohreh** [umap-project/umap#1262]
Hello,

Unless I missed it, the application doesn't allow the user to show/hide all layers in one go.

Cheers,

**Comment by yohanboniface** [comment]
cc @Aurelie-Jallut, to add in the new layers box ?

**Comment by Hedaja** [comment]
I support this enhancement.
I'm working on a birding project at the moment and I therefore have about 50 layers. A hide/show all button would be quite time saving when trying to look at a specific layer.

**Comment by yohanboniface** [comment]
This is now possible:

![Image](https://github.com/user-attachments/assets/ba7e3f52-b750-4b2a-9fbd-b51887273d70)
