### ISSUE TITLE
Limit location search results

### ISSUE THREAD

**Issue by entrider** [umap-project/umap#1264]
**Is your feature request related to a problem?**
Sometimes when a household is missing on the map of selected city (which is common in poorly mapped areas) or if you made a typo in your search request, the results from other places are provided. It seems logical, but if you create a map for specific city, why would you need results from others cities and even countries? In such cases, it'd be better to provide none in my opinion.

**Describe the solution you'd like.**
Since a user can set custom boundaries, they can be used to limit search results. Or the search results can be limited based on their "remoteness" (ideally an option should be added to specify the distance).

P.S. I am not sure if it is possible to implement.

**Comment by yohanboniface** [comment]
uMap uses Photon by default, and it seems doable: https://github.com/komoot/photon#filter-results-by-bounding-box
