### ISSUE TITLE
miniMap doesn't show anymore

### ISSUE THREAD

**Issue by Kikwaju** [umap-project/umap#1265]
Hi!

What: miniMap doesn't show anymore, in embed iframe AND on direct link. With this code: https://umap.openstreetmap.fr/fr/map/[my_personal_map_xxx]?miniMap=true

When:  since < 1 week (maybe 1 day, but idk when was the turning point). Before, it perfectly worked.

In map editor parameters > settings user interface > display mini map : ON.
When I set "off" and then back "on", the mini map appears. Saving parameters. Refreshing. Mini map disappearing. Even adding "?miniMap=true"

Same behavior on PC (W10) with Chrome 116, Firefox 116, even Edge 115 !
Same behavior on Smartphone (Android Firefox 116)

I found nothing in recent patch notes about this. Will we get the minimap back?
Many thanks, and cheer up to the devs!

**Comment by yohanboniface** [comment]
Thanks for the report, will be fixed in next release.

**Comment by Kikwaju** [comment]
many thanks, perfectly works now!
[SOLVED]
