### ISSUE TITLE
mouse interaction

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#127]
Originally reported by: **Anonymous**

---

Having many objects (e.g., buildings) is it possible to first disable mouse interaction for entire map/layer and then enable single object? For same reason (many objects), one could choose not to show data layers if not very useful. 

Many thanks, wonderful sw!
ualios

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/127

**Comment by davidbgk** [comment]
Please reopen if the problem persist.
