### ISSUE TITLE
[regression] All layers are loaded and displayed, even those "Display on load=OFF"

### ISSUE THREAD

**Issue by Shohreh** [umap-project/umap#1276]
Hello,

A new bug was introduced after fixing the issue with moving items in the list: Now, when viewing a map, _all the layers_ are fetched and displayed, even those configured to be hidden by default (Display on load=Off).

Cheers,

**Comment by yohanboniface** [comment]
Sorry, no link, I cannot do anything.

**Comment by Shohreh** [comment]
http://umap.openstreetmap.fr/en/map/tours-clermont-ferrand_948035

**Comment by yohanboniface** [comment]
Thanks but please explain better the issue, what you see, what you expect.

Here is what I see, which does not seem to be all layers loaded.

![image](https://github.com/umap-project/umap/assets/146023/b50da8d4-6212-4b84-8053-620ca8ab2b93)

**Comment by Shohreh** [comment]
While only _some layers_ are set to be displayed at load time, they are now _all displayed_ when I open a map.

Didn't occur before, which leads me to believe the bug was introduced recently while fixing the other bug.

![image](https://github.com/umap-project/umap/assets/1541861/a798fa1c-fa25-4da6-9761-23321764a360)

**Comment by yohanboniface** [comment]
This is not what I see when I open the map. So it is certainly related to some environnement difference: can you try on another browser ? can you try without being logged in ?

**Comment by Shohreh** [comment]
Same browser (Chrome) after logging out: Same issue.
Firefox without being logged on: Same issue.
Opera  without being logged on: Same issue.

**Comment by yohanboniface** [comment]
You "just" load the map, right ?

**Comment by davidbgk** [comment]
Whatever the browser (Firefox, Safari, Chromium), I cannot reproduce.

**Comment by yohanboniface** [comment]
This URL http://umap.openstreetmap.fr/en/map/tours-clermont-ferrand_948035 without any query string ?

**Comment by Shohreh** [comment]
Yes, the same URL.

I exported the whole map (.umap), and then re-imported it in a new map: Same problem.

[Here](https://gofile.io/d/SFgv6t)'s the file.

**Comment by adavaaix** [comment]
Bonjour, 
Même soucis (à priori?) ici depuis quelques jours, tous les calques s'affichent même ceux non visibles en théorie.
Tout comme sur la carte de Shohreh, ces calques cachés ne s'affichent pas immédiatement à l'ouverture de la carte mais seulement après avoir fait un zoom/dézoom.
Cela le fait chez plusieurs personnes même non propriétaire de la carte, sous linux/windows/android/chrome/firefox/... Bref partout.
lien carte : http://umap.openstreetmap.fr/fr/map/adava-pays-daix_192878

**Comment by adavaaix** [comment]
C'est tout bon de notre coté, merci pour mise à jour rapide !

**Comment by Shohreh** [comment]
👍
