### ISSUE TITLE
bug: redirect direct link

### ISSUE THREAD

**Issue by gefrenzel** [umap-project/umap#1277]
**Describe the bug**
since Update to V1.6.0 direct links to my umap are going to an redirect to another zoomlevel and new center of the map

**To Reproduce**
1. Go to 'http://umap.openstreetmap.fr/de/map/imnu_583376#19/51.05119/13.81963' in an new window
2. wait for loading
3. See error -> URL after redirect: 'http://umap.openstreetmap.fr/de/map/imnu_583376#12/51.0551/13.7988'

**Expected behavior**
I expect to load the map at the position from my URL like in the past versions and like overwrite the URL in the open UMap-window.

**testet with:**
 - OS: Windows/Linux/Android
 - Browser firefox, chromium (different Versions)

**Comment by yohanboniface** [comment]
Thanks for detailed report, I'll have a look!

**Comment by yohanboniface** [comment]
Sounds related to the miniMap, I'm investigating
