### ISSUE TITLE
umap.openstreetmap.fr: Username change at OSM not reflected; cannot change by myself; no contact of administrators findable.

### ISSUE THREAD

**Issue by dreirund** [umap-project/umap#1285]
Ahoj,

this I report as a bug here because [&nearr;&hairsp;I got this recommendation in the OpenStreetMap forum](https://community.openstreetmap.org/t/102943/2).

However, it applies to the instance at [umap.openstreetmap.fr](http://umap.openstreetmap.fr/), I am not sure if it applies to the uMap software.

The Problem is:

1. I have an account at [umap.openstreetmap.fr](http://umap.openstreetmap.fr/), using [OpenStreetMap.org](http://openstreetmap.org/) as login provider.
2. I changed my username at [OpenStreetMap.org](http://openstreetmap.org/) some time ago.
3. When I login at [umap.openstreetmap.fr](http://umap.openstreetmap.fr/), I still see my old username.
4. I cannot find an option at [umap.openstreetmap.fr](http://umap.openstreetmap.fr/) to change my username.
5. I do not find a contact to the administrators of [umap.openstreetmap.fr](http://umap.openstreetmap.fr/) at [umap.openstreetmap.fr](http://umap.openstreetmap.fr/)!

So the most prevalent issue I see is number 5, that the service at [umap.openstreetmap.fr](http://umap.openstreetmap.fr/) does not reveal a contact.  
The second prevalent issue is the combination of number 3 and 4, that a username change with the login provider is not reflected _and_ it is not possible to change the login locally.

I initially was asking about the issue [&nearr;&hairsp;here in the OpenStreetMap community](https://community.openstreetmap.org/t/102943/1), and [&nearr;&hairsp;in answers](https://community.openstreetmap.org/t/102943/2) was [&nearr;&hairsp;referred to this bug tracker](https://community.openstreetmap.org/t/102943/3).

Regards!

**Comment by yohanboniface** [comment]
Thanks for the detailed report!

Did you try this page ?

https://umap.openstreetmap.fr/fr/me/profile

**Comment by dreirund** [comment]
> *https://umap.openstreetmap.fr/fr/me/profile*

Yes, that enables me to change the username.

It was hidden "in plain sight", so sorry my fault (maybe encouraged by user interface design):

The text

> *My Dashboard | [My profile](https://umap.openstreetmap.fr/en/me/profile)*

after I clicked on "[My Dashboard (<username>)](https://umap.openstreetmap.fr/en/me)" on the main site [umap.openstreetmap.fr](http://umap.openstreetmap.fr/) did appear to me as just a headline for the whole page, it does not look for me like an link ("My profile" is not underlined as links usually are, and the whole typography is like a single headline), and other items where also in the top menu so I would have expeted it there.

I close it as resolved but leave the note that the user interface might need a redisign here, maybe place the "[My profile](https://umap.openstreetmap.fr/en/me/profile)" in the top menu!

Regards!

**Comment by yohanboniface** [comment]
> I close it as resolved but leave the note that the user interface might need a redisign here

Definitely!

Thanks for your useful criticism! :+1: 

cc @Aurelie-Jallut, about rethinking the navigation, soon :)
