### ISSUE TITLE
Facilitate the addition of pictograms by integrating a pictogram library, for example.

### ISSUE THREAD

**Issue by Aurelie-J** [umap-project/umap#1286]
**Is your feature request related to a problem? Please describe.**
adding pictograms is complex 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Aurelie-Jallut** [comment]
Scenario U: 
- As a webmaster in the communications department, I'm in charge of creating a map to inform residents about work in progress in the commune.
- There are several types of work, and I'd like residents to be able to identify and differentiate between them.
- Type of work: Electricity / Gas / Roads
- I create a layer for each type of work
- On the Electricity layer, I place pointers where the electrical work is located.
- I want to put a picto representing the Electricity type


**Problems** /// Ideas for solutions
**It's hard to see the shape of the icons with the small-square transparent background** /// use a plain background

**when I find the icon and click on it, the icon panel closes. I have to scroll up a bit to find where to click to make it appear again** /// leave the panel open / allow me to close it / have it close automatically if I do another action

**the link to change the pictogram is not very visible** /// revise the button's UI to make it more visible

**I need to find the icon I'm looking for again to test the white version** /// Search by keyword or display icons sorted by theme

 **the rendering isn't great (not very clean outline)** /// Use another icon library (remix)

**Add more icons that meet the main needs of communities** /// Allow users to add their own set of icons

**Comment by yohanboniface** [comment]
Fixed in #1387 #1395
