### ISSUE TITLE
Enable grouping/sub-grouping of data-layers

### ISSUE THREAD

**Issue by rprovilij** [umap-project/umap#1300]
Is it possible to create layer-groups that contain several data layers? This would allow users to create, for example, a group called "Public transport" under which fall the individual layers of bus-, train-, tram-, and metro-stops. Whereas currently, each of these layers would need to be hidden/revealed individually, the use of groups would facilitate users to hide/reveal all elements within this group simultaneously. 

In summary, the use of groups would give users added flexibility in organizing and showcasing their data layers. 

<img width="112" alt="Screenshot 2023-09-04 153442" src="https://github.com/umap-project/umap/assets/81406457/21a971e4-b8e5-4c50-9d6f-a71c5edde451">
<img width="140" alt="Screenshot 2023-09-04 153450" src="https://github.com/umap-project/umap/assets/81406457/cc53d189-7612-4824-9725-d7c757f22e97">
<img width="110" alt="Screenshot 2023-09-04 153505" src="https://github.com/umap-project/umap/assets/81406457/2ad6d87f-a232-4b7b-b4cc-cb12137dce70">
<img width="219" alt="Screenshot 2023-09-04 153939" src="https://github.com/umap-project/umap/assets/81406457/c5b8d4c8-740f-4e1e-b47b-ceb607a03523">

**Comment by yohanboniface** [comment]
Thanks for the suggestion!
There is already a discussion about this feature: #939 
So I'm closing here, and let's continue the discussion there.
