### ISSUE TITLE
Improve the legibility of pictograms and complete them.

### ISSUE THREAD

**Issue by Aurelie-Jallut** [umap-project/umap#1301]
**Is your feature request related to a problem? Please describe.**
The current pictograms are difficult to identify, with their transparent background and small squares, and I can't find any pictograms representing work, which is a frequent need for local authorities. The visual rendering is not very sharp

**Describe the solution you'd like**
- Use another set of icons: https://remixicon.com/ (possibility of making a selection of the most useful icons for communities).
- Make it possible to search or sort icons by theme.

**Comment by yohanboniface** [comment]
Done :)
