### ISSUE TITLE
Keep .gz only for latest version

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#1317]
It seems that we keep it for old version and sounds useless and consumes server space.

**Comment by davidbgk** [comment]
I guess it's because we remove the old name here:

https://github.com/umap-project/umap/blob/master/umap/models.py#L331

And then in `purge_old_versions` we do not have the reference anymore (hence still keep the `.gz`):

https://github.com/umap-project/umap/blob/master/umap/models.py#L399-L408

**Comment by yohanboniface** [comment]
Humm, I don't think this is the issue.

When removing the `oldname`, we do it because we want to have a name in the form `{id}_{modified_at}` and I did not find a way to alter this name before the first save.

`purge_old_versions` will delete the files (including .gz) older than the X (`settings.KEEP_VERSIONS`). What this issue is about is that for the version we keep, we also keep the `.gz` which I think will never be used again.

Given the `.gz` is created at first access to the file, maybe the fix is as simple as deleting all `.gz` on save, because at this time the `.gz` of the latest file version does not yet exist.

**Comment by yohanboniface** [comment]
> I did not find a way to alter this name before the first save

Now I remember why: we do not have the pk before the first save…
