### ISSUE TITLE
Same map listed many times in my catalog

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#1325]
**Describe the bug**
when viewing my map catalog (Mon Espace) I can see the same map several times. The number of times seems to relate to the number of editors of the map.
- account : cartocite
- map : http://umap.openstreetmap.fr/fr/map/gares-sncf-2022_702105

**To Reproduce**
1. Login with the account cartocite on the umap.openstreetmap.fr instance
2. Open the catalog (http://umap.openstreetmap.fr/fr/me)
3. The map "Gares SNCF 2022" appears 5 times – note only the first one shows some map content. I checked they all point to the same URL.

**Expected behavior**
Each map should be listed only once.

**Screenshots**
![image](https://github.com/umap-project/umap/assets/6516063/6e3aad7f-f8cc-41b8-933f-067dd8777783)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser : Firefox 117.0.1 (64 bits)

**Comment by yohanboniface** [comment]
Thanks for the report Antoine, I'll have a look :)
