### ISSUE TITLE
Links to map with/without visible layers

### ISSUE THREAD

**Issue by Philetjosie** [umap-project/umap#1327]
It is really useful to create maps with multiple layers. It is possible to activate / desactivate the layers to show different informations. For example, a map can show a long way, with each traveled days in a different layer.
It would be useful to be able to have differents links to show either the map with all layers activated, or with specific layers only. For the example above, that would allow to show the full way, or the same map with the way traveled day 1, then another link for day 2, etc.
That may be copied with the formalism of the html anchor, i.e. Link all activated: umap.blabla.fr/mymap#full, or with specific layers: umap.blabla.fr/mymap#layer1

**Comment by Philetjosie** [comment]
Ok, sorry, I have not seen this. Great ! I will test it immediatly.
Regards.

**Comment by yohanboniface** [comment]
Cool!
