### ISSUE TITLE
Data filtering based on points in map focus

### ISSUE THREAD

**Issue by IgnacioHeredia** [umap-project/umap#1338]
Hi all,  

I have yet another proposal for data filtering. 

I would like that when I select `See data layers` --> `Bronwse data`, the data displayed in the side panel would only be the data currently visible in the map.

For example, here I have only three points in the screen, but all the points of the map are shown in the side panel. So it becomes hard to know what are these three points. So ideally, the side panel would only display those three points.

![image](https://github.com/umap-project/umap/assets/16413205/3269419c-b48c-4d73-b787-5301e33afb9d)

I think this is different from other data filtering issues (https://github.com/umap-project/umap/issues/1242, https://github.com/umap-project/umap/issues/1120) because I would like this filtering to be dynamic, as I resize the map, and more points appear/dissapear from focus.

One could enable/disable this feature in a checkbox in case some wants the old behaviour (eg. `[x] On focus`)

**Comment by yohanboniface** [comment]
Thanks for the proposal @IgnacioHeredia !

This is something we already discussed in the past, so here is a proposal #1339 :)

**Comment by IgnacioHeredia** [comment]
WOW, that was quick 😄🚀  . Thanks so much @yohanboniface !
