### ISSUE TITLE
Making description field available in the properties table of layers

### ISSUE THREAD

**Issue by iriman** [umap-project/umap#1363]
**Is your feature request related to a problem? Please describe.**
For polygons that consist of many points (like borders) it usually takes long and it also slows down the browser while loading the feature to edit properties of it. "Table of Properties" for layer (right-most icon) ![image](https://github.com/umap-project/umap/assets/8467903/90dcee60-7206-4f21-8991-080fb44b043b) works great for this to avoid extra load on browser but it doesn't have description field.

**Describe the solution you'd like**
Making description field available in the properties table. thanks!

**Comment by yohanboniface** [comment]
I think going this way would mean replacing our home made table by a more powerful one, like:
- https://gridjs.io/
- https://www.datagridxl.com/
- https://sheetjs.com/
- https://www.ag-grid.com/
- https://tabulator.info/

It's on our radar, while not in the top priorities at the moment. But of course, PR are welcome! :)

**Comment by yohanboniface** [comment]
It's now possible to edit description in the table editor.
