### ISSUE TITLE
Short Link has no SSL certificate

### ISSUE THREAD

**Issue by kNsja5w** [umap-project/umap#1365]
When trying to share a public map, the short link has no SSL certificate installed.
The link only has http not https.

![Bildschirm­foto 2023-10-11 um 14 12 11](https://github.com/umap-project/umap/assets/16246095/5563a7f7-10e1-42a8-a9de-539e3552b3fb)

**Comment by yohanboniface** [comment]
Thanks for the report! That's an old known issue, sadly :(

See #594
