### ISSUE TITLE
Can't load and edit a map

### ISSUE THREAD

**Issue by altilunium** [umap-project/umap#1374]
**Describe the bug**
After configuring layer-specific editing permissions, the map can no longer be edited. Several errors are displayed in the console log.

**To Reproduce**
1. Configure a layer-specific editing permissions.
2. Save and exit
3. Edit that map back

**Screenshots**
Error log, while logged in : 
![image](https://github.com/umap-project/umap/assets/70379302/44822570-d4c8-48f3-b498-2f797618f2fc)

Error log, while logged out :
![image](https://github.com/umap-project/umap/assets/70379302/8a11b75b-c43d-40f4-8277-4f37211b6baa)

https://umap.openstreetmap.fr/en/map/poster-caleg_952507

**Comment by yohanboniface** [comment]
Sorry for that, and for the report, I'll have a look!

**Comment by yohanboniface** [comment]
I've reset the datalayers edit status permissions, but it seems the error is still there. So it may be related to another change. Can you remember changing something else before the bug appeared ? Maybe the default map view ?

**Comment by altilunium** [comment]
Other than edit status permissions, I changed the map tile layer.

**Comment by yohanboniface** [comment]
Sounds like that: I've reset the default view, and it seems the map is back alive.

**Comment by altilunium** [comment]
Thank you very much :)
