### ISSUE TITLE
Placeholder for fields with space

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#139]
Originally reported by: **Andrea Borruso (BitBucket: [aborruso](http://bitbucket.org/aborruso), GitHub: [aborruso](http://github.com/aborruso))**

---

Hi,
I have a field name with a space inside "My places". If I use this placeholder  {My places} for a popup, I have in the popup "{My places}" and not the value of that record.

What's the right syntax for a field name with a space inside?

Thank you very much

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/139

**Comment by cascafico** [comment]
Looks like a persistent issue: in[ this map ](http://umap.openstreetmap.fr/it/map/case-di-riposo-in-fvg_938933#) I have a field named "ragione sociale" that works perfectly as advanced filter key but is not set in popup template, appearing as "{ragione sociale}". 

Advanced filter key is showed in data pane, so it would be nice avoiding field names as ragione_sociale or the awful ragione%20sociale.
