### ISSUE TITLE
The iframe code to embed a map misses out https: in the URL 

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#1397]
**Describe the bug**
In the code that is produced to embed a map into a web page, the src value misses out "https:". This is also missing from the "See full screen" link. 

**To Reproduce**
1. Go to http://u.osmfr.org/m/587367/
2. Click on 'Share the map'
3. The iframe code under "Embed the map" shows "src="//umap.openstreetmap.fr/en/map/jardinage_587367..."
4. Embed the map in an HTML file
5. Open the HTML file
6. The browser (Firefox) displays "File not found" : Firefox ne peut trouver le fichier à l’adresse /en/map/jardinage_587367

**Expected behavior**
Adding "https:" in front of the URL fixes the problem, uMap used to do it for you.
Note that "https:" is also missing from the link to open the map in full screen.

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 22.04
 - Browser : Firefox
 - Version 119.01

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidbgk** [comment]
Do you have a place where it's embedded with that code and doesn't work?

**Comment by naomap** [comment]
Attached is an example HTML file. 
[index.html.txt](https://github.com/umap-project/umap/files/13305085/index.html.txt)

**Comment by yohanboniface** [comment]
@naomap the `//` is supposed to be a "neutral" schema, which will result in `https` if the main window is `https` and `http` otherwise. So I guess the question of @davidbgk is: do you have a web page where the iframe with such URL does not load as expected ? :)

**Comment by naomap** [comment]
I see. Indeed this works fine when integrating the iframe map into a proper web page, this just does not work when using a plain HTLM file. This means my training exercise no longer works, the solution implemented by uMap is good and working well.

**Comment by davidbgk** [comment]
One option for a training exercise might be to start a local server in the folder of the HTML, like `python -m http.server 8000`, it should make the `iframe` render but I understand that it's not a trivial extra step…
