### ISSUE TITLE
Add another type of data layer : proportional circles 

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#1399]
**Is your feature request related to a problem? Please describe.**
The addition of cloropleth data layers triggers another idea : showing point data as proportional circles, i.e. circles whose area is proportional to the value of a numerical field. 

**Describe the solution you'd like**
- Load point data in a layer, with a field that contains a numerical value e.g. population.
- Select "Proportional circles" as the type of layer
- Define the field used to calculate the area of each circle, and a factor to apply so that circle sizes can be adjusted
- Each point is displayed as a circle, and can be selected to show a popup.
- It may be necessary to adjust the size of circles to the zoom level, so that they do not hide each other at a low zoom level => need for another factor ?

**Describe alternatives you've considered**

**Additional context**
Example map : 
![image](https://github.com/umap-project/umap/assets/6516063/e39e70a1-7805-4528-9b38-317455ec1148)

**Comment by naomap** [comment]
Here is an example with Overpass Turbo : bicycle parkings where the surface is proportional to their capacity 
http://overpass-turbo.eu/s/1DS5

**Comment by yohanboniface** [comment]
May help https://github.com/balladaniel/leaflet-dataclassification
