### ISSUE TITLE
Overpass variables with dynamic

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#140]
Originally reported by: **Unknown Name (BitBucket: [robjn](http://bitbucket.org/robjn), GitHub: [robjn](http://github.com/robjn))**

----------------------------------------

Hi,

I had a user ask how to get a overpass url to directly load in uMap
[http://www.mappa-mercia.org/2014/09/creating-an-always-up-to-date-map.html#comment-320](http://www.mappa-mercia.org/2014/09/creating-an-always-up-to-date-map.html#comment-320)

He's got a couple of bits wrong, but I've tried following your instructions at [http://www.openstreetmap.org/user/ybon/diary/23611](http://www.openstreetmap.org/user/ybon/diary/23611) and still cannot get it to work.

The URL I'm testing with is:
[http://umap.openstreetmap.fr/map/new?dataUrl=http%3A%2F%2Foverpass-api.de%2Fapi%2Finterpreter%3Fdata%3Dway%5B%22historic%22%3D%22archaeological_site%22%5D(%7Bsouth%7D%2C%7Bwest%7D%2C%7Bnorth%7D%2C%7Beast%7D)%3Bout%20body%20center%20qt%3B&dataFormat=osm#16/49.4331/-2.3597](http://umap.openstreetmap.fr/map/new?dataUrl=http%3A%2F%2Foverpass-api.de%2Fapi%2Finterpreter%3Fdata%3Dway%5B%22historic%22%3D%22archaeological_site%22%5D(%7Bsouth%7D%2C%7Bwest%7D%2C%7Bnorth%7D%2C%7Beast%7D)%3Bout%20body%20center%20qt%3B&dataFormat=osm#16/49.4331/-2.3597)

Are we trying to do something that is not possible? Note that in the user interface I'd normally tick the Dynamic=yes checkbox. Do I need to add this to the URL?

----------------------------------------
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/140

**Comment by sfkeller** [comment]
Regarding https://github.com/tyrasd/overpass-turbo/issues/231 my use case is to make it much easier to integrate Overpass queries in uMap as remote data, with a compatible "({bbox})".
