### ISSUE TITLE
Change of behavior when clicking arrows in footer of side panel

### ISSUE THREAD

**Issue by el-srabo** [umap-project/umap#1400]
**Describe the bug**
I am using the Framasoft instance. Until a recent update (1 month ago maybe? I'm not sure sorry), when I would click on the arrows in the footer of a side panel, it would take me directly to the previous or next panel. Now, the map still moves to the next point, but it does not open the panel so I have to manually click on the dot, which is tiresome if I want to quickly go through many panels.

**To Reproduce**
1. Go to https://framacarte.org/m/148987/
2. Click on any marker
3. Click on the forward or backward arrow

**Expected behavior**
Open the next or previous panel (same way as it does for the popups)

 - Device: Fairphone 2
 - OS: LineageOS 18.1 (Android 11)
 - Browser: Firefox
 - Version: 116.3.0

**Comment by yohanboniface** [comment]
Thanks for your report! A fix is on its way!

**Comment by el-srabo** [comment]
Thanks for the quick fix! Any idea about when the Framacarte instance will be updated?
