### ISSUE TITLE
Les liens n'apparaissent plus en couleur.

### ISSUE THREAD

**Issue by AZWCI** [umap-project/umap#1418]
Bonjour.

L'usuelle couleur des liens (bleue) a "disparu". Cela vaut pour les "popups" comme les "crédits", en pied de carte.
Du coup, ils sont actuellement noirs comme le texte, leur visibilité est nulle et ne se devine plus qu'au survol de la souris.

https://umap.openstreetmap.fr/fr/map/carte-radars-cdg_1#11/48.6306/1.1779

Merci à celles et ceux qui corrigeront le css !

**Comment by Aurelie-Jallut** [comment]
Dans le pied de page : On pourra aussi exclure du lien les "-" :)
ne pas souligner "— À propos" au survol mais juste "À propos"
<img width="532" alt="image" src="https://github.com/umap-project/umap/assets/131352601/6708c47d-c265-4d36-b3de-1fffa7c40afd">
