### ISSUE TITLE
Escape key shouldn't cancel the actual polygon creation

### ISSUE THREAD

**Issue by brunetton** [umap-project/umap#1428]
I'm using a [pen tablet](https://en.wikipedia.org/wiki/Graphics_tablet) to trace some roads; and with this type of device the double clic is not easy to do. So I'm using escape key, as in Inkscape that I'm using a lot. But in uMap escape cancel all points I've already done :( It's quite frustrating as I lost sometimes a lot of time, working on complex polygons. 

IMHO escape shouldn't do anything, or just qui "add mode"; ie stop adding more points when I clic.

**Comment by yohanboniface** [comment]
Can you explain a bit more your use case or issue ?

If I try myself, when drawing a line and using Escape, it only quits the "drawing mode", but do not delete already existing points.

[Screencast from 2023-11-26 11-30-36.webm](https://github.com/umap-project/umap/assets/146023/4326a05d-83c5-4ee5-b949-86196cc3b0f1)

Thanks!

**Comment by brunetton** [comment]
Damn, I just checked and I've not the same behavior here: I clicked 3 times and pressed escape key

https://github.com/umap-project/umap/assets/86322/6c002081-062c-4849-973e-b8692966edd5

Tested with Google chrome 117.0.5938.149 and Firefox 118.0.1, with new profiles without any extensions

**Comment by brunetton** [comment]
I got it ! You where using polyline tool, I'm using polygon tool. This actually works well using polyline, but not for polygons
