### ISSUE TITLE
[suggestion] Way to contact map owner

### ISSUE THREAD

**Issue by Shohreh** [umap-project/umap#1431]
Hello,

I have a suggestion: Provide a way to contact a map's owner.

There's a map whose owner I need to contact for more infos, but there's no way for that unless the user provided an email in the map's About section.

Cheers,

**Comment by yohanboniface** [comment]
Agreed!

Closing in favor of this oooooold but still open issue #29 

The main problem being that we usually does not have the user email (when using osm.org as auth provider, we don't have the information). And we cannot find a way to retrieve the OSM account from it's id neither. But I agree that we should have a something, so let's not forget this issue.
