### ISSUE TITLE
Some users don’t have their maps in "my maps" page

### ISSUE THREAD

**Issue by ldidry** [umap-project/umap#1448]
**Describe the bug**
In "my maps" page, some users (not all of them) don’t see their maps. It can be no maps, or just some of them

**To Reproduce**
1. Go to "my maps" page
2. no maps, or not all of them

**Expected behavior**
Have all of your maps

**Additional context**
It’s a regression due to https://github.com/umap-project/umap/commit/9af5375dbf52afb0e53911a7b5a0772dd7d55406. I reverted the commit and it’s now working as before.

Problem: I didn’t experience the bug myself, so I can’t dig it deep. I just now that reverting the commit fixes it.

**Comment by yohanboniface** [comment]
See https://github.com/umap-project/umap/blob/master/umap/templates/umap/navigation.html#L12

**Comment by yohanboniface** [comment]
Here is a diff:

```diff
diff --git a/templates/umap/navigation.html b/templates/umap/navigation.html
index 1be9c0c..fdd8fb3 100644
--- a/templates/umap/navigation.html
+++ b/templates/umap/navigation.html
@@ -4,7 +4,7 @@
     <div class="container">
         <ul class="nav navbar-nav navbar-right">
           {% if user.is_authenticated %}
-          <li><a href="{% url 'user_maps' user.username %}">{% trans "My maps" %} ({{ user }})</a></li>
+          <li><a href="{% url 'user_dashboard' %}">{% trans "My maps" %} ({{ user }})</a></li>
           {% else %}
           <li><a href="{% url 'login' %}" class="login">{% trans "Log in" %} / {% trans "Sign in" %}</a></li>
           {% endif %}

```

Which then points to the dashboard, which looks like this:

![image](https://github.com/umap-project/umap/assets/146023/d800a5ba-0c84-4c5e-a99e-78336396c355)

@ldidry should I make a PR ?

**Comment by ldidry** [comment]
Anyway, thank you for the fix (I’m waiting for an impact user to say if it’s all right).

**Comment by almet** [comment]
Hey @ldidry 🤗

[On some other projects](https://github.com/Kinto/kinto/blob/master/CHANGELOG.rst), we were adding some more information in the changelogs, to make this more easy to spot.

We could then have different sections in the changelog, like:

- Breaking Changes
- New features
- Documentation
- Bug Fixes
- Internal changes

Would that make it easier to get the information?

**Comment by ldidry** [comment]
Add a link to the changelog in the releases and it should be enough :slightly_smiling_face:

**Comment by yohanboniface** [comment]
Should we close here ? :)

**Comment by ldidry** [comment]
Sure, sorry.
