### ISSUE TITLE
On mac, ommand+option+i is captured and prevents from opening the dev console.

### ISSUE THREAD

**Issue by almet** [umap-project/umap#1452]
**Describe the bug**

When using mac OS, doing command + option + i opens the import panel rather than opening the dev tools. I'm not sure that's intentional (?)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Firefox 
 - Version 120.0.1

**Comment by yohanboniface** [comment]
I think we are doing it the wrong way: we check that some key pressed AND we check if the modifier (ctrl/cmd) is pressed, but we do not check for other keys:

https://github.com/umap-project/umap/blob/master/umap/static/umap/js/umap.js#L509-L575
