### ISSUE TITLE
uMap loads/delivers extremely slowly

### ISSUE THREAD

**Issue by OttoRiehl** [umap-project/umap#1457]
I have been using umap.osm.fr for four years now  
Recently, I have noticed a striking difference in speed between the German and French instances.

German instance
https://umap.openstreetmap.de/de/map/herkunft-und-verbleib-der-bewohner-von-krasna-mit-_49937#6/49.831/18.281

https://umap.openstreetmap.de/de/map/origin-and-whereabouts-of-the-citizens-of-krasna-w_49938#6/49.831/18.281

French instance
https://umap.openstreetmap.fr/de/map/herkunft-und-verbleib-der-bewohner-von-krasna-mit-_266645#6/50.479/20.016

https://umap.openstreetmap.fr/de/map/origin-and-whereabouts-of-the-citizens-of-krasna-w_268737#6/49.767/18.347

The German instance is running version 1.2.3.
The French instance is running version 1.11.1

The French instance loads the data unusually slowly. 
Do I have to provide the data differently?

**Comment by yohanboniface** [comment]
Thanks for report!

I had a quick look, and this bug seems to be introduced with 51c19906818f5790410177748df2fc2bdb9a2236

I'll try to continue investigation asap!

**Comment by yohanboniface** [comment]
OK, got it: the data browser panel is being rebuilt at each feature added. So one workaround could be to remove the data browser.

I'll work on a fix, but I'm not sure I'll be able to release it before end of the week.

**Comment by OttoRiehl** [comment]
Thank you.
With version 1.12.0, the import of data is running smoothly again.

uMap is a great tool.
