### ISSUE TITLE
[suggestion] List maps as tile, with checkboxes to delete them all

### ISSUE THREAD

**Issue by Shohreh** [umap-project/umap#1459]
Hello,

Currently, listing and possibly deleting maps is slow, as the user must possibly scroll down several times to see them all.*

I suggest;
1. Display maps as a tile, each map with a checkbox next to it so as to delete several maps in one go
2. Only display Name and Last Save with option to sort each column. Fetching the maps takes too much time, and Title is good enough to know what it is — provide link to map in case the user wants to actually see it.

Cheers,

![image](https://github.com/umap-project/umap/assets/1541861/a851ffcc-d0fd-4733-9fd4-bc1b2039484d)

**Comment by davidbgk** [comment]
@Shohreh what about adding a Delete option on the My maps page in the last column of the table?

<img width="1216" alt="Capture d’écran, le 2023-12-11 à 10 07 26" src="https://github.com/umap-project/umap/assets/3556/8c3fbc0c-1ca6-4756-9535-00a13634798d">

**Comment by yohanboniface** [comment]
I see several points here:

- map miniature makes the page too slow => we'd like a preview image instead, but this is hard to do without adding a complex stack; Should we hide the miniature in the meantime ?
- Scrolling with a "more" button is not very friendly => should we have a normal paginator instead ? (prev 1 2 3 … next) ?
- 10 maps at a time may not be enough ?
- we'd like some mass action, with check boxes on maps, so to: delete / download many at once, cf #1430

**Comment by Shohreh** [comment]
I guess hiding it before finding a better way does the job. The issue is that is that is slows down things a lot, while the user simply wants to delete a bunch of maps.

To select maps, I'd rather have them displayed all on one page instead of having to scroll or hit prev/next. For better performance, just displaying their title + date last updated is good enough.

A "delete/download" option would definitely be nice IMHO.

**Comment by davidbgk** [comment]
> while the user simply wants to delete a bunch of maps.

I wonder if that's a popular use-case, adding some friction to such a destructive function might actually be a feature 🤔

**Comment by yohanboniface** [comment]
Closing here, we should be good now!

**Comment by Shohreh** [comment]
I don't see checkboxes on each line.

Is there a way to select several maps, and delete them all in one go?

![image](https://github.com/umap-project/umap/assets/1541861/ef4fea3b-6d28-416e-bb55-3111bfd7eabc)

**Comment by davidbgk** [comment]
This is not a use case we consider to be common and this is a destructive one so we decided to keep the extra step.
