### ISSUE TITLE
Restoring a backup also restores the permissions

### ISSUE THREAD

**Issue by guinbespa** [umap-project/umap#1460]
Hello,
A bug in the "Show/hide a layer" function, which remains in hidden mode by default (only one layer is affected), has shown me that my latest backups are not correct.
Here's what happens when the backup file is imported, depending on the choice of data format (120.0.1 Firefox Release November 30, 2023):

        - Umap: "The data in the file 2023-12-10.umap is not valid as an umap format".
        
        - GeojSON: the data is displayed but the layout does not conform
        
So I gradually went back into my backup files and restored a working map that was about a month old.

Assuming that I hadn't changed anything in my backup methods :

    - what happened so that the last backups were not valid and did you encounter the same problem?
    - Is it safe to recover data from other layers?
    - Have you had this problem with the "Show/hide a layer" function, which remains hidden by default?
    
Thank you in advance for your information

Yves
guinbespa@gmail.com

**Comment by yohanboniface** [comment]
Can you share your backup file so I can have a look ?

**Comment by guinbespa** [comment]
[2023-11-17-ter.umap.txt](https://github.com/umap-project/umap/files/13647662/2023-11-17-ter.umap.txt)
[2023-12-10-bis.umap.txt](https://github.com/umap-project/umap/files/13647663/2023-12-10-bis.umap.txt)


Hello,
Here are two backup files:
invalid : 2023-12-10-bis.umap
valid : 2023-11-17-ter.umap
If you look at the difference between these two files, you can see that the invalid file is missing its entire header.
And I seem to remember that in the path for the backup in "Edit map properties", there used to be "Umap" in the drop-down menu for the choice: "Download data" (which no longer appears???)
Thank you and have a nice day
Yves

**Comment by yohanboniface** [comment]
> Assuming that I hadn't changed anything in my backup methods

You did changed your backup method, as the old one is not more possible ;)

There is a now a dedicated button for the backup:

![image](https://github.com/umap-project/umap/assets/146023/16f473ec-5dbd-4c8f-92f0-a28b9a6b9326)

My supposition is that, by force of habits, you used the first entry of the dropdown, which is now geojson, which flatten all layers in one. Can it be ? :)

**Comment by guinbespa** [comment]
[2023-12-12.backup-umap.txt](https://github.com/umap-project/umap/files/13651600/2023-12-12.backup-umap.txt)
Yohan,
The assumption was correct, the backup file is valid with the complete data.
Now, how to correct the bug in the "Show/hide a layer" function, which remains in hidden mode by default: in the attached file, it's the month of May. 
Thank you in advance and have a good evening
Yves

Ps: I miss the old backup file which was more hierarchical to read and therefore easier to check the indexed content!

**Comment by yohanboniface** [comment]
> Now, how to correct the bug in the "Show/hide a layer" function, which remains in hidden mode by default: in the attached file, it's the month of May.

Technical comment: this happen because:
- permissions are stored in between the options
- datalayer save blindly all the options (while the map has a white list of keys to save)
- when restoring, those permissions are taken into account

As soon as the restored map is saved, those permissions are replaced by the real one, so the issue is minor, but it shows a bad design.

**Comment by guinbespa** [comment]
Yohan,
I've noted that this is a programme design problem.
Specifically, what is the solution for the corrupted May layer?
- clone the layer and rename it in a new layer (risk of duplicating the problem?) 
- download the contents of the layer and copy it to a new layer (risk of duplicating the problem?) 
- edit each element by copying and pasting it into a new layer
Thank you and have a nice day
Yves
Webmaster Latinamap.eu

**Comment by yohanboniface** [comment]
Just save the map and the layer will have correct permissions

**Comment by guinbespa** [comment]
Yohan,
I've noted that you only need to save the map for the layer to have the correct permissions.
So, in the layer properties, I renamed the name and then saved it.
Then, in the browser, clear history data or CTRL + F5.
But the May layer persists in remaining in "hide layer" mode.
Please tell me how to proceed
Best regards
Yves

**Comment by yohanboniface** [comment]
Ah, it seems you've set `maxZoom: -1` somehow:

![image](https://github.com/umap-project/umap/assets/146023/1cb319fb-1b16-4d06-9f07-821a7a73d78b)

**Comment by guinbespa** [comment]
Great! The layer is working again
Thanks a lot!
Y.
