### ISSUE TITLE
Ad a Directory Structure for Layers

### ISSUE THREAD

**Issue by differentieel** [umap-project/umap#1462]
If the developer creates a map with a lot if layers - let's say 60 or more - it would be nice to have a Directory-like Structure that can be sorted by hand (as it is now) AND automatically alphabetical by choice.

The visible Directory Structure should work in the Development mode as well in the View mode in a way that the visitor can sort it in both ways - alphabetically or as the Developer has set the sorting - both under the "Directories" the developer has set the order.

The way it might look like this:

/Section One
.  /Layer One
.  /Layer Two
.  /Layer Three
   […]
/Section Two
.  /Layer One
.   - /Sub layer A
.   - /Sub Layer B
.  /Layer Two
   […]
/Section Three
.  /Layer One
.  /Layer Two
.  /Layer Three
.   - /Sub layer A
.   - /Sub layer B
.   - .  /Third floor layer A
.   - .  /Third floor layer B
         […]
.   - /Sub layer C
.  /Layer Four
.  /Layer Five
   […]
/More sections as much as the developer needs
.  /As much layers as the developer needs

This is ment as a simple addition to structure the developers work with no complex algorithms.

**Comment by yohanboniface** [comment]
cf #1300

**Comment by yohanboniface** [comment]
Closing in favor of #939
