### ISSUE TITLE
Display measure not showing

### ISSUE THREAD

**Issue by Xonnext** [umap-project/umap#1486]
When I right click on a line in a map, the [Display measure] is not showing a distance anymore. It shows: {afstand} km.

BEWARE: As far as I can see only in the NL-version. 

Joyeuses fêtes..!

![NO_Distance_measure](https://github.com/umap-project/umap/assets/7556062/e35cc078-7f3a-43ba-9830-8df7f1cf69b5)

**Comment by yohanboniface** [comment]
Thanks for the report! This comes from a var translated by mistake here: https://app.transifex.com/openstreetmap/umap/translate/#nl/frontend/457406643?q=text%3Akm

I fixed it, it will be released soon! :)
