### ISSUE TITLE
Improving visibility security for "anyone who has the link"

### ISSUE THREAD

**Issue by cayenne17** [umap-project/umap#1494]
**Is your feature request related to a problem? Please describe.**
When I change the numbers at the end of the URL that corresponds to the card identifier, I come across cards. The problem is that by changing the number, I can come across cards where there is slightly sensitive data.

Here's the URL of a card I've created:
- [https://framacarte.org/fr/map/point-deau-osm-france_**133263**](https://framacarte.org/fr/map/point-deau-osm-france_133263)

By changing the number at the end, I'll come across another map even if the visibility parameter for the other map is set to anyone who has the link.
- [https://framacarte.org/fr/map/point-deau-osm-france_**133264**](https://framacarte.org/fr/map/point-deau-osm-france_133264)    

The URL will be rewritten to :
- [https://framacarte.org/fr/map/carte-du-moyen-orient_**133264**](https://framacarte.org/fr/map/carte-du-moyen-orient_133264)
<br>

*Describe the solution you'd like**
- it should lead to a 404 error
- A random link should be generated

**Comment by yohanboniface** [comment]
Thanks! Duplicate of #905.

**Comment by cayenne17** [comment]
> Thanks! Duplicate of #905.

I've just closed it
