### ISSUE TITLE
Satellite base map

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#151]
Originally reported by: **Anonymous**

---

I have been following umap development and it's come a long way over the last couple of year.  Nice work!  

I am using the tool for some participatory mapping and wondering if you can add a satellite base layer?  It will be a helpful reference layer for some of the stakeholders I work with.

Thanks,
Gregg

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/151

**Comment by amenk** [comment]
There is a Bing layer plugin for leaflet...

**Comment by mattbk** [comment]
ESRI maps are free only if you have ArcGIS Server:

> Q:  Can I
use these services for free in a custom web application?

> A:  Yes, the
services are free, however the use of Esri Web mapping APIs may require a
subscription. If you have ArcGIS Server, no subscription is needed. If you do
not have ArcGIS Server and are deploying an application built with these APIs
commercially or internally, then a subscription
is required

**Comment by sylvain-m** [comment]
And what about MapBox Satellite ?
https://www.mapbox.com/satellite/
(I did not seek too far the terms of use ...)

**Comment by legrostdg** [comment]
An aerial layer would be awesome...

**Comment by alpter** [comment]
I have been using mapbox satellite...
http://umap.openstreetmap.fr/en/map/alpi-liguri-open-outdoor_109351#11/44.1370/7.8042
and also personalized tileserver map
http://umap.openstreetmap.fr/en/map/cartografia-1-50000-alpi-liguri_109355#12/44.1527/7.8631

What would be useful would be a sort of overlap of the personalized map on the top of the OSM layers... giving the possibility to chose the map and also the transparency of it....

See here as example of trasparency on the top right on various sources... leaflet and openlayers...
http://tileserver.alpiligurioutdoor.it

**Comment by legrostdg** [comment]
https://github.com/umap-project/umap/issues/71

**Comment by alpter** [comment]
if someone is interested this should be re-open
Support overlay tile layers [#87](https://github.com/umap-project/umap/issues/87)

**Comment by legrostdg** [comment]
@alpter #87 is a duplicate of #71

**Comment by mnoblecourt** [comment]
Hi everyone, I was just wondering about this feature!
@yohanboniface I'm trying to figure out how to add Bing or Mapbox background to a uMap but I don't find how, could you help me if you have a minute?
For Bing I'm trying to base it on the TMS in JOSM (bing[22]:https://www.bing.com/maps/) but just entering `https://www.bing.com/maps/` is not working. Same for Mapbox `https://{switch:a,b,c,d}.tiles.mapbox.com/styles/v1/openstreetmap/cj8gojt0i1eau2rnn7q4mdgu7/tiles/256/{zoom}/{x}/{y}?access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJhNVlHd29ZIn0.ti6wATGDWOmCnCYen-Ip7Q` even when removing the token part of the URL.

More generally speaking it would be great to have the free providers such as Bing, Mapbox or DigitalGlobe (if possible legally speaking) in the tile options for uMap! 😉

**Comment by yohanboniface** [comment]
Try this:

> https://{s}.tiles.mapbox.com/styles/v1/openstreetmap/cj8gojt0i1eau2rnn7q4mdgu7/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJhNVlHd29ZIn0.ti6wATGDWOmCnCYen-Ip7Q

> if possible legally speaking

I don't think it is, but I'd like to be proven I'm wrong :)

**Comment by mnoblecourt** [comment]
The link works, thanks a lot for the super fast answer!
OK, I haven't investigated at all so forget it then. Thanks again!

**Comment by mnoblecourt** [comment]
@yohanboniface me again :)
We have tried to create a new uMap with satellite imagery background. I have tried to base it on MapBox's current URL and tried to adapt to the format you edited last time `https://{s}.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}?access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJjaml5MjVyb3MwMWV0M3hxYmUzdGdwbzE4In0.q548FjhsSJzvXsGlPsFxAQ`, but it doesn't seem to be working... if you can help again that would be most appreciated.

**Comment by yohanboniface** [comment]
Sorry, missed that notification by then it seems. I guess it's way to late, but please reopen if needed/ :)
