### ISSUE TITLE
Import GeoJSON: Can I use tags as description of the overlay layer elements?

### ISSUE THREAD

**Issue by dancesWithCycles** [umap-project/umap#1517]
Hi folks,
Thank you so much for providing and maintaining this repository!

**Is your feature request related to a problem? Please describe.**
Kind of: When I import GeoJSON from overpass the resulting overlay layer elements do have a name but the description ist empty.

**Describe the solution you'd like**
I am importing GeoJSON generated by [overpass-turbo](http://overpass-turbo.eu/) into a umap. The `name` tag from OSM is used as the name of overlay layer elements.

Can I use other OSM tags, e.g. hours, website, phone, aso., as the description of overlay layer elements? How?

**Describe alternatives you've considered**
I have not considered alternatives yet.

**Additional context**
Any additional context needed?

Cheers!

**Comment by yohanboniface** [comment]
Hi @dancesWithCycles 

I see two options if I get you right.

1. You can set a custom template for your popup (on the map properties or on the layer properties), this way:

![image](https://github.com/umap-project/umap/assets/146023/9c54628a-9a23-4410-a2c6-b75ed2e89806)

2. you can use the new "OpenStreetMap" popup template

Which tries to display the most common informations for an OpenStreetMap object:

![image](https://github.com/umap-project/umap/assets/146023/183428e9-a36e-4eba-afbf-1a97edcca2e2)

![image](https://github.com/umap-project/umap/assets/146023/c364cdb0-4fcf-4b8a-9a24-947c48fed58a)

**Comment by yohanboniface** [comment]
Closing, please reopen if you need more help!
