### ISSUE TITLE
Question: ENABLE_ACCOUNT_LOGIN don't work

### ISSUE THREAD

**Issue by geimist** [umap-project/umap#1520]
I want to self-host uMap for a private project with docker. I don't want to use OAuth for this, but only a few local user accounts. Accordingly, I have set the parameter `ENABLE_ACCOUNT_LOGIN=1` in the umap.conf file, as [described here](https://docs.umap-project.org/en/master/config/settings/#enable_account_login). 

Where can I find a way to register or store credentials?
![Bildschirmfoto 2024-01-10 um 15 06 08](https://github.com/umap-project/umap/assets/29315520/bac5f532-4abc-46da-bdae-8705620551f1)

**Comment by yohanboniface** [comment]
From the admin: `/admin` you should be able to create users.

**Comment by yohanboniface** [comment]
> Or do you mean the URL extension (umap.example.com/admin)?
> Even there I only get to a login screen.

Yes, that way.

You need to create first a superuser, on the command line:

    umap createsuperuser

**Comment by geimist** [comment]
Great, it works. I would not have found this way on my own.
Thank you 🤗

**Comment by yohanboniface** [comment]
Would you mind creating a PR on the doc to add this ?
