### ISSUE TITLE
Map version

### ISSUE THREAD

**Issue by ahspence53** [umap-project/umap#1521]
**Describe the bug**
Today (10th January) map has reverted to a version before 7th January.
I completed edits on 8th January 2024 and all was well.
My map is; https://umap.openstreetmap.fr/en/map/golf-courses-in-scotland_1002268#8/55.503/-4.157

**Expected behavior**
I cannot see or find a reason for this behaviour

 

**Smartphone (please complete the following information):**
 - Device: IPAD
 - OS: [e.g. iOS 16
 - Browser Safari
 

**Additional context**

**Comment by yohanboniface** [comment]
>  I cannot see or find a reason for this behaviour

Me neither :(

May be a cache issue or something. Have you tried from another device/network ?

**Comment by ahspence53** [comment]
First thing I tried is cache as this happens often when I use uMap.
I did not try another device, if this happens again I will indeed try this, howver please close this as I resolved it another way.
