### ISSUE TITLE
Allow OGC standard protocols as WMS and WFS

### ISSUE THREAD

**Issue by severinmenard** [umap-project/umap#1522]
**Is your feature request related to a problem? Please describe.**
Watch the SotM FR 2023 presentation ans saw that allowing layers to be shared between maps is in the roadmap, so why not using the existing interoperable OGC protocols?

**Describe the solution you'd like**
Allowing WMS/WFS layers, both for uMap generated layers and external layers

**Comment by yohanboniface** [comment]
Closing in favor of #264
