### ISSUE TITLE
Unable to delete two maps

### ISSUE THREAD

**Issue by ahspence53** [umap-project/umap#1527]
Could an administrator please delete both maps in **umap.openstreetmap.fr **under**** my login called **Scotland Coal Mines**
I am unable to Edit to delete.
My id is Hunter1143
My email address is ahspence@gmail.com

**Comment by yohanboniface** [comment]
Can you be more specific on "I am unable to Edit to delete" ? Thanks! :)

**Comment by ahspence53** [comment]
OK, when I go into my Dashboard, I have two maps named **Scottish Coal Mines** when I click on Edit, the map opens, then within the map when I click Edit to go into the menu to access Edit map properties/Advanced and Delete the map, nothing happens, except for the Edit button disappearing.

**Comment by yohanboniface** [comment]
Do you see the confirm dialog after clicking on Delete ?

![image](https://github.com/umap-project/umap/assets/146023/716d43a5-001f-43a6-88d1-c8cf03bcdf81)

**Comment by ahspence53** [comment]
When I click on the Edit button on the top right hand of the page, the edit button disappears, giving me no way to delete the map.
![7472612B-DFBE-48F8-8A10-AA25C324824A](https://github.com/umap-project/umap/assets/147179766/98ab441c-24b1-4d8a-a622-0ab7b9286f77)

**Comment by yohanboniface** [comment]
Can you open the developer console before testing and making a new screenshot ?

**Comment by ahspence53** [comment]
How do I do that please?
Thanks

Alex

**Comment by ahspence53** [comment]
Wow! The upgrade to **dashboard** works, I was able to delete the maps. Thank you!

**Comment by davidbgk** [comment]
@ahspence53 thank you for your feedback 🙇
