### ISSUE TITLE
disappearance markers

### ISSUE THREAD

**Issue by adminANNAD** [umap-project/umap#1537]
Markers added two days ago disappear as I add new ones so i can't take a screeshot to show you the bug :/ 

Umap version : 1.13.1

**Comment by yohanboniface** [comment]
It's usually a caching issue in the network you are using.

You can:
- test from another browser to see if those points appear
- test from another network (your phone/tablet, your work…)
- go to the layer versions and see if you can restore a version with those points:

![image](https://github.com/umap-project/umap/assets/146023/149f7118-c7e7-48d1-91ae-39cc42338a9a)

We sadly cannot do anything more.
