### ISSUE TITLE
Import GeoJSON via api

### ISSUE THREAD

**Issue by VladDrakul1986** [umap-project/umap#1548]
**Is your feature request related to a problem? Please describe.**
I would like to import geojson to umap. I generate the GeoJSON with an small app and so far i upload them manually to umap.
I use the network analyse function of my broswer but i didn't see something like post call which upload my geoJSON.

**Describe the solution you'd like**
A way to automatically upload a geoJSON from my App to a given map, layer with a description. e.g. with a post Endpoint.

**Comment by yohanboniface** [comment]
An API is somewhere on the road map, but not in the top priorities, see #175 

uMap itself uses json calls internally thought, in the case of a layer, the POST should point to something like `/map/xxxx/datalayer/create/`

I'm closing as there already is an issue to track this need.
