### ISSUE TITLE
Warn about old / not supported browser

### ISSUE THREAD

**Issue by iriman** [umap-project/umap#1557]
**Is your feature request related to a problem? Please describe.**
Some users still use old browsers like IE (Windows) or old versions of Samsung Internet (Android) on their devices and such browsers don't load umap maps.

**Describe the solution you'd like**
An informational alert on map page for user to use a modern browser.

**Comment by davidbgk** [comment]
@iriman did it happen to you?

Which message would be valuable for these users?

**Comment by iriman** [comment]
Not for me, but I tested it with my old android phone to check it. Also tried out on Windows 7 with IE 11. In both I saw a blank page for all maps.
I realized this  when I shared a short url to the map to see some statistics about users and found out a few of them used IE browser.

As an example message:
Your browser isn't supported. Please update it to the latest version or use a modern browser like Firefox, Chrome, Edge.
