### ISSUE TITLE
Elements become unclickable while having an open popup from a disappeared layer [of polygons, probably]

### ISSUE THREAD

**Issue by iriman** [umap-project/umap#1575]
**Describe the bug**
Elements become unclickable with the following steps to reproduce:

**To Reproduce**
1. Go to 'https://umap.openstreetmap.fr/en/map/map_943303#6/35.075/52.339'
2. Click on any division to open popup.
3. Do not close popup.
4. Zoom in (With scroll wheel or keyboard +) so the current layer disappear and another layer appear.
5. Click on any element from new layer. Click doesn't work. **[bug]**
6. Zoom in more to see some icons from another layer. Click on them isn't working too. **[bug]**
7. Zoom out so the layer in step 2 reappear again.
8. Click on any division.
9. Click works!
10. Close the pop up manually before zooming in.
11. Repeat from step 5.
12. No problem.

This also happens while changing zoom from 10 to 11 so that subdivisions disappear. 
This doesn't happen while changing zoom from 11 (only icons visible) to 7 or less (icons aren't visible any more). (pop up from icons)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Firefox]
 - Version [122.0]
 - 
**Additional context**
On step 5 or 6 this error appears in browser console:
```
20:26:39.566 Uncaught Error: Must add layer to map before using getCenter()
    getCenter Polygon.js:69
    extendedProperties umap.features.bb884676d297.js:140
    getDisplayName umap.features.bb884676d297.js:63
    resetTooltip umap.features.bb884676d297.js:119
    _redraw umap.features.bb884676d297.js:186
    fire Events.js:195
    onRemove Popup.js:171
    removeLayer Layer.js:185
    close DivOverlay.js:74
    fire Events.js:195
    _fireDOMEvent Map.js:1452
    _fireDOMEvent Map.js:1416
    _handleDOMEvent Map.js:1401
    handler DomEvent.js:108
Polygon.js:69:9
```

**Comment by yohanboniface** [comment]
Thanks for the detailed bug report and step by step! Should be fixed on next release.
