### ISSUE TITLE
Change project licence for one recognized by OSI

### ISSUE THREAD

**Issue by virgile-dev** [umap-project/umap#1577]
**Is your feature request related to a problem? Please describe.**
Currently the uMap licence is WTFPL.
While applying to grants (ex : NLNet NGI's) we found that not having a [licence recognized by the OSI](https://opensource.org/licenses/) could be a blocker. 
**Describe the solution you'd like**
How about changing to AGPLv3 which is widely used as a strong copyleft licence.

**Describe alternatives you've considered**
We could ask the OSI to recognize the WTFPL. They have a [process on their website](https://opensource.org/licenses/review-process/).
Though I'm concerned it won't do as WTFPL might a bit too minimalistic for them ^^

**Additional context**
Google grants and contribution programs also require a licence from OSI.

**Comment by almet** [comment]
Because the license is WTFPL, we can probably change the license to whatever we want.

+1 for whatever works for you (AGPLv3 would be great)

**Comment by davidbgk** [comment]
Done in https://github.com/umap-project/umap/pull/1605
