### ISSUE TITLE
Update periodicity with remote data

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#160]
Originally reported by: **Sylvain Montagner (BitBucket: [sylvain_montagner](http://bitbucket.org/sylvain_montagner), GitHub: [sylvain_montagner](http://github.com/sylvain_montagner))**

---

The ability to add remote data is very useful.
However, it would be more effective (to reduce the frequency of queries on the servers) proposing an update periodicity (intermediate between dynamic / non-dynamic).
For example, with a query that returns a large amount of data, it would be better to ask that  datas are updated 1 time a day, or even 1 time per week.
Whait do you think about it ?

Sylvain M.

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/160

**Comment by ckhung** [comment]
I echo Sylvain Montagner's request, but from the opposite perspective :-)

For example if the user can specify the update periodicity of 1 minute, or if there is a button for reloading the remote data, then umap could become a universal transportation map for all cities. For city gov's without sufficient technical resources, they won't have to develop their own fanciful transportation apps -- they just have to update their bus data as geojson or kml files. This may also promote the visibility of umap and even attract city gov's to collaboratively contribute to umap.

Or even if the update periodicity cannot be made very small, a 5-min update cycle can still be useful for a group of hikers or street salespersons or OSM mappers to know roughly where everyone else is.

BTW, if I want to change the update periodicity manually for now, which line of which source file should I be looking at? I couldn't find the relevant code by grep.

Many thanks to  yohanboniface for this wonderful OSM app. I am using it in my (college) classes.

**Comment by sylvain-m** [comment]
(je me rends compte avec ce post que j'ai 2 profils sur Github, mais c'est bien le même Sylvain Montagner que précédemment)

Après quelques mois, je me permets de venir aux nouvelles sur l'éventuelle prise en charge de cette fonctionnalité (mis à jour périodique de la donnée distante).
Après avoir bien avancé sur ma prise en main de Umap, c'est vraiment un point clé pour qu'il réponde à nos besoins.
En effet, pour des couches volumineuses issues d'OSM via Overpass, une fois chargées (avec le mode "cluster" notamment), l'affichage est vraiment rapide. Ce qui prends du temps, c'est l'execution de la requête sur les serveurs OSM/Overpass.
Donc, dans les cas qui me concernent, une mise à jour quotidienne de la requête serait idéale !
(programmée à minuit par exemple).
Comme ça, mes données n'ont au plus qu'un jour de retard, ce qui est tout à fait acceptable !
(dans le processus actuel manuel, les données ont plusieurs semaines/mois de retard...)

Y a-t-il un espoir pour que cette fonctionnalité soit implémentée prochainement ?

Merci encore pour ce "génialissime" outil libre !

Sylvain M.


In English (with a proprietary but effective tool) :

> 
> (I realize with this post that i have 2 profiles on Github, but it is the same Sylvain Montagner as before)
> After a few months, let me come to news about the possible support for this feature (periodicity update with remote data).
> With now better understanding of Umap, it's really a key point to respond to our needs.
> Indeed, for bulky layers from OSM via Overpass, once loaded (with the "cluster" method in particular), the display is really fast. What takes time is the execution of the request on the OSM / Overpass servers.
> So in cases that concern me, a daily update of the application would be ideal!
> (Programmed at midnight for example).
> That way my data has at most a day late, which is quite acceptable!
> (In the current manual process, the data have several weeks / months late ...)
> Are there any hope for this feature to be implemented soon?
> thank you again for this "genial" free tool!
> 
> Sylvain M.

**Comment by vinber** [comment]
indeed it would be very useful for both the remote server but also for fun user (no remote data waiting to be loaded).
Thanks for umap and framacarte and others...

**Comment by sylvain-m** [comment]
Is there any update about this point ?

**Comment by sylvain-m** [comment]
2017's update ;-)
> Is there any update about this point ?

This feature would be very useful !

**Comment by ckhung** [comment]
Not sure if it is an allowed practice to promote one's own related project... But since several people have the same need, I will just risk being frowned upon, and apologize in advance :-) For people who only need configurable dynamic data sources and who don't need the editing and other rich features of umap, you can try [potluckmap](https://g0v.github.io/potluckmap/).

**Comment by yohanboniface** [comment]
Closing as implemented (through cache support), see https://github.com/umap-project/umap/commit/81f6b429bc91321e33ad645fe94531604fbd6313
