### ISSUE TITLE
Unable to log in with osm account

### ISSUE THREAD

**Issue by bristow** [umap-project/umap#1611]
It's all in the title, but you get this error after clicking on the OSM logo: 

![image](https://github.com/umap-project/umap/assets/1156507/5a2f8084-3712-4f32-b081-9127f945d0ba)

Thanks :pray:

**Comment by yohanboniface** [comment]
http vs https ?

**Comment by bristow** [comment]
You're right. That's the problem, it used to work because I always noticed that uMap didn't force https.

Is this feasible? On my browser, it always passes me http, so there must be a way to force it via the server, right?

**Comment by yohanboniface** [comment]
> Is this feasible? 

Yes, it's on its way.

Not sure how much trouble will get with #594 but let's move step by step!

**Comment by yohanboniface** [comment]
Redirect is on!

**Comment by bristow** [comment]
Confirmed Yeah !

Thanks
