### ISSUE TITLE
Github login not working

### ISSUE THREAD

**Issue by JustEasternThings** [umap-project/umap#1612]
When I attempt to log in through Github, after entering my account details, page redirects to ww1.fluv.io which redirects to adware/spyware site - on navigating back to uMap still logged out

1. Go to 'https://umap.openstreetmap.fr/en'
2. Click on 'Login', then click Github 
3. Enter account details and sign in to Github

**Expected behavior**
Redirect to umap.openstreetmap.fr and logged in

**Screenshots**
<img width="1439" alt="Screenshot 2024-02-15 at 17 57 49" src="https://github.com/umap-project/umap/assets/69594608/be018fa0-3891-458b-b76e-71c0bd6948d9">
site redirect after github login

 - OS: MacOS
 - Browser: Firefox
 - Version: 122.0.1

**Additional context**
This has made me unable to access my main account "JustEasternThings"
I have an OpenStreetMap account with username "TheBus8" but it is already linked to the uMap account "BryantKokBinYee", I would like to consolidate both logins under the "JustEasternThings" account if it is possible

**Comment by JustEasternThings** [comment]
Thank you!
Is it possible to remove the uMap account associated with my OSM account (username TheBus8) so I can link it to my main uMap?

**Comment by yohanboniface** [comment]
I can't find no user with this username in uMap users

**Comment by JustEasternThings** [comment]
TheBus8 is my OSM username, the uMap username is "BryantKokBinYee".

**Comment by yohanboniface** [comment]
OK! I've deleted the user.
