### ISSUE TITLE
Text formatting > display error for mailto links

### ISSUE THREAD

**Issue by clwacker** [umap-project/umap#1616]
If you add a link to an e-mail address in a text field, for example in Edit map properties  > Credits > Long credits in the form [[mailto:someone@somesite]] or [[mailto:someone@somesite|**someone@somesite**]]
a ? sign enclosed in a small rectangle is displayed in front of the link.
The mail link works, but I guess the ? additionally displayed is a bug.

uMap version 1.13.1

**Comment by davidbgk** [comment]
Thanks for the report.

This is probably [that line](https://github.com/umap-project/umap/blob/8eb2a518f1b8d75fd2eca5cfe2592005867f9aff/umap/static/umap/map.css#L1325) again.

**Comment by clwacker** [comment]
Waouh, so fast fix!
I'm using https://umap.osm.ch
You can have a look to my most extensive map with over 1,700 points and 2D and 3D photos of the historical milestones:
https://umap.osm.ch/fr/map/bornes-historiques-de-neuchatel_3405
Thanks for your great job!

**Comment by yohanboniface** [comment]
Cool!
