### ISSUE TITLE
OEmbed support

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#162]
Originally reported by: **Yohan Boniface (BitBucket: [yohanboniface](http://bitbucket.org/yohanboniface), GitHub: [yohanboniface](http://github.com/yohanboniface))**

---

http://www.oembed.com/

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/162

**Comment by bristow** [comment]
:+1:

**Comment by bristow** [comment]
Hi!

It would be nice to have oEmbed support on uMap. It is already available on the openstreetmap.org website.

Indeed, the digital workspaces used in French colleges and high schools simplify rich integration and implement only OEmbed instead of iframe-based codes, we no longer have accessible source code.

Thanks :)

**Comment by bristow** [comment]
Some news ? Thanks :)

**Comment by yohanboniface** [comment]
I see that there is a [`rich`](https://oembed.com/) type, which allows html, we may dig into this option.

**Comment by bristow** [comment]
Here is an example of a mapping system found on the providers page: https://github.com/iamcal/oembed/blob/master/providers/ucam_map.yml

The json returned by 
https://map.cam.ac.uk/oembed/?url=https://map.cam.ac.uk/#52.203547,0.120560,18 : 

`{"type":"rich","version":"1.0","title":"University Map","author_name":"University of Cambridge","author_url":"https:\/\/www.cam.ac.uk","provider_name":"University of Cambridge: University Information Systems","provider_url":"https:\/\/www.uis.cam.ac.uk\/","width":500,"height":300,"html":"<iframe src='https:\/\/map.cam.ac.uk\/' style='width: 500px; height: 300px;'>iframe required<\/iframe>"}`
