### ISSUE TITLE
Icon symbol appears even if no symbol was selected

### ISSUE THREAD

**Issue by IgnacioHeredia** [umap-project/umap#1622]
**Describe the bug**
When creating icons with no symbols, a black dot still appears in the middle of the marker.

![image](https://github.com/umap-project/umap/assets/16413205/1e750cd8-247f-4ff5-92bb-4372c7452f2d)

If one then selects a dot as symbol, then the dot appears white.

![image](https://github.com/umap-project/umap/assets/16413205/5ad09c8b-d3ab-46fc-a5be-0b4e74274c78)

**To Reproduce**
Simply create a way point.
Optionally: use bright icon color to better see the black dot.

**Expected behavior**
I would expected that if one does not select a symbol, then no black dot would appear.

**Desktop (please complete the following information):**
- Ubuntu 20.04
- Brave 1.62.162
- Firefox 122.0.1 --> same problem (though the initial icon appears white, not black)

**Comment by yohanboniface** [comment]
Thanks for the report, but I cannot reproduce, tested on Firefox, Chrome, Chromium, Brave: when creating a Marker, the got is always white.

Having a white dot by default is the expected behaviour.

Which uMap server are your using ?

**Comment by IgnacioHeredia** [comment]
Then I misunderstood the behaviour. 
I would have expected than if no symbol was selected, to see something like this.

![image](https://github.com/umap-project/umap/assets/16413205/2ba5d2a3-65c2-4bf3-a871-5e7bb9bdda32)

But I understand that having a default symbol looks nicer. Just that it seemed weird to not have a "No symbol" option.
