### ISSUE TITLE
Add tilesets in Spain

### ISSUE THREAD

**Issue by mauriciabad** [umap-project/umap#1638]
Hi, would it be okay to add this two tilelayers? They are from Spain, and I need them to be able to draw precise geometries.

### Topografic Catalunya
- Name: Topografic Catalunya (Spain)
- Author: ICGC
- Url: <http://icgc.cat/>
- Tiles: <https://geoserveis.icgc.cat/icc_mapesmultibase/noutm/wmts/topo/GRID3857/{z}/{x}/{y}.png>

I don't need this 2nd one but it would be nice to have: They also have a satelite view, but it's almost the same as PNOA: <https://geoserveis.icgc.cat/icc_mapesmultibase/noutm/wmts/orto/GRID3857/{z}/{x}/{y}.png>

### PNOA Spain
- Name: PNOA Spain
- Author: IGN
- Url: <http://www.ign.es/>
- Tiles: <https://www.ign.es/wmts/pnoa-ma?service=WMTS&request=GetTile&version=1.0.0&Format=image/png&layer=OI.OrthoimageCoverage&style=default&tilematrixset=GoogleMapsCompatible&TileMatrix={z}&TileRow={y}&TileCol={x}>

I don't need this 2nd one but it would be nice to have: They also have a topografic map, similar to the ICGC's one, but for the whole Spain and way less precission. <https://ign.es/wmts/mapa-raster?service=WMTS&request=GetTile&version=1.0.0&Format=image/jpeg&layer=MTN&style=default&style=default&tilematrixset=GoogleMapsCompatible&TileMatrix={z}&TileRow={y}&TileCol={x}>

### Other
I don't need this one, but it has good quality and covers all the planet. 

It is the Esri Clarity: <https://clarity.maptiles.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}>

**Comment by yohanboniface** [comment]
Hi @mauriciabad sorry for the late answer! The OSM France uMap as already a lot of tilelayers available, and it aims to have worldwide (or France specific) ones only.

Have you considered having a Spanish uMap server ? Like there are for example one in [Switzerland](https://umap.osm.ch/) or in [Germany](https://umap.openstreetmap.de/fr/).

Also, you can still add a custom tilelayer on your map to use those tilelayers.
