### ISSUE TITLE
Question: Did anyone ever see the edit page of a umap turn to HTTP 403 Forbidden Error?

### ISSUE THREAD

**Issue by dancesWithCycles** [umap-project/umap#1640]
**Describe the bug**
An association is using umap happily for a couple of years. Since this month the edit page of the umap shows a white page with the `HTTP 403 Forbidden Error`.

```
Access to umap.openstreetmap.fr was denied
You don't have authorization to view this page.
HTTP ERROR 403
```

**To Reproduce**
This is the public link to the umap of the association.

https://umap.openstreetmap.fr/de/map/der-grune-kompass-braunschweig_93968#12/52.2639/10.5211

To edit this umap you open the edit page. Due to IT security concerns I do not like to share the link to the edit page here.

**Expected behavior**
The edit link shall make people able to get to the edit page to edit the umap.

**Screenshots**
Please find here the screenshot of the `HTTP 403 Forbidden Error`.

![Screenshot_2024-02-20_21-09-42](https://github.com/umap-project/umap/assets/47819327/98682ce1-66bb-4fb3-9af5-36eba4b58b46)

**Desktop (please complete the following information):**
 - Browser: Firefox and Chromium

**Smartphone (please complete the following information):**
 - Device: Android
 - Browser: Firefox

Cheers!

**Comment by yohanboniface** [comment]
Should be good now, sorry!

**Comment by dancesWithCycles** [comment]
I appreciate your prompt help. Cheers!
