### ISSUE TITLE
uMap - Edit Access Required / Can't Edit My uMap

### ISSUE THREAD

**Issue by dilspil** [umap-project/umap#1642]
Hi,

I've mistakenly created a uMap earlier this week prior to logging in with my OSM account. This can no longer be edited; however, I'm now needing access to make some changes.

I have seen previously others have received assistance in linking the map to my OSM account to regain access. Could I please 
get some assistance with this?

Link: https://umap.openstreetmap.fr/en/map/healthcare-australia-active-employees-workforce_1026469#5/
OSM Username: dylan_weston_hca

**Comment by yohanboniface** [comment]
Should be good now, sorry!

**Comment by dilspil** [comment]
Was it possible to have access to a few other older ones too I'd had the same problem with, that would be legendary. Thank you so much for actioning the one I shared earlier, again to dylan_weston_hca:
https://umap.openstreetmap.fr/en/map/healthcare-australia-vacancies-march-2023_877148#4/-27.99/129.55
https://umap.openstreetmap.fr/en/map/healthcare-australia-permanent-vacancies_874475#3/-26.67/139.92
https://umap.openstreetmap.fr/en/map/healthcare-australia-vacancies-110123_855214#4/-26.43/131.92
https://umap.openstreetmap.fr/en/map/healthcare-australia-vacancies-210922_810230#4/-24.33/130.52
