### ISSUE TITLE
Question: Can I use an Overpass query as layer input instead of an import?

### ISSUE THREAD

**Issue by dancesWithCycles** [umap-project/umap#1652]
Hi folks,
Thank you so much for providing and maintaining this repository! Kudos!

**Is your feature request related to a problem? Please describe.**
It is rather a hassle than a problem. I really fancy these [2 map features](https://github.com/umap-project/umap/issues/1517#issuecomment-1884676263)! I am downloading data in GeoJSON format using [overpass](https://overpass-turbo.eu/) and importing that data into a specific existing layer using the umap import feature.

**Describe the solution you'd like**
I was wondering if it is possible to specify a Overpass query like this one

```
[out:json][timeout:60];
relation(62531);
map_to_area;
nwr[bulk_purchase=yes](area)->.bp;
nwr[zero_waste=yes](area)->.zw;
//union block statement
(
.bp;
.zw;
);
out body center qt;
```

instead of an GeoJSON import as data source for a layer?

**Describe alternatives you've considered**
This way I solve my OSM data update issue. Currently I manually update my umap layers by downloading GeoJSON via Overpass and importing into layers via the umap import feature. It is quite a hassle to do that like every week or so to stay up to date with OSM.

**Additional context**
I cannot think of additional context right now. You?

Cheers!

**Comment by yohanboniface** [comment]
Yes, there are a bunch of tutorial out there for this, for example: https://wiki.openstreetmap.org/wiki/UMap/Guide/Import_data_with_Overpass

**Comment by dancesWithCycles** [comment]
@yohanboniface Cheers mate! That works perfectly fine out of the box! Kudos!
