### ISSUE TITLE
Question: geojson Data Import VS. Dynamic Remote Data

### ISSUE THREAD

**Issue by dancesWithCycles** [umap-project/umap#1663]
Hi folks,
Thank you so much for providing and maintaining this repository!

**Is your feature request related to a problem? Please describe.**
I am comparing 2 layers in umap:
1. Manually importing geojson data from OSM with `Popup content style` set to `OpenStreetMap` resulting in this map.

![Screenshot_2024-02-28_21-14-49](https://github.com/umap-project/umap/assets/47819327/1f00d793-e3b2-4d7e-b88d-d143c36f7b2d)

2. Dynamically loading the layer content using the `Remote data` feature with `Popup content style` set to `OpenStreetMap` resulting in this map.

![Screenshot_2024-02-28_21-17-44](https://github.com/umap-project/umap/assets/47819327/8ec8ac7d-861b-4217-849d-94c5d27e9306)

**Describe the solution you'd like**
Please ignore the name tag in the example screenshots. Anyhow, I would have expected to fine the same style and content in the white area below the name/title as I chose `Popup content style` set to `OpenStreetMap` in both cases. Of course, the content in the white area depends on the tags provided in OSM. That is not what I am talking about.  I am talking about 2 observations:

* When I am using the `Import GeoJSON` feature I get a link with the label `See on OpenStreetMap`, but not with the `Remote Data` feature.
* No matter if I am using the `Import GeoJSON` or `Remote Data` feature, I see a website listed in the white area when the website is provided in OSM using the `website` tag but not using the `contact:website` tag. Are you doing this on purpose? Are you omitting the `contact` namespace on purpose or do you have to decide for on?

**Describe alternatives you've considered**
Can I influence what content appears in the white area of the popup?

**Additional context**
I appreciate your support! Cheers!

**Comment by yohanboniface** [comment]
This should indeed be the same. Can you share the URL you are using as remote data ?

**Comment by dancesWithCycles** [comment]
Sure! This is the URL for the purple `public_bookcase` layer

```
https://overpass-api.de/api/interpreter?data=[out:json][timeout:60];relation(62531);map_to_area;(nwr[amenity=public_bookcase](area););out%20body%20center%20qt;
```

und for the pink `second_hand` layer.

```
https://overpass-api.de/api/interpreter?data=[out:json][timeout:60];relation(62531);map_to_area;nwr[shop=second_hand](area)-%3E.shops;nwr[second_hand=yes](area)-%3E.secondHands;(.shops;.secondHands;);out%20body%20center%20qt;
```
I hope this helps!

**Comment by yohanboniface** [comment]
> Sure! This is the URL for the purple public_bookcase layer

There seems to be no tag on those object, so this explains popups are empty. What are you expecting ?

if you compare importing data and using remote data, please do it with the same data.

**Comment by dancesWithCycles** [comment]
> There seems to be no tag on those object, so this explains popups are empty. What are you expecting ?

Agree. I'll  reproduce the situation and compare the data first of all.

Anyhow, what about the 2. observation that I do not get the `See on OpenSteetMap` link in the white area of the popup when I am using the `remote data` feature?

**Comment by yohanboniface** [comment]
> Anyhow, what about the 2. observation that I do not get the See on OpenSteetMap link in the white area of the popup when I am using the remote data feature?

`@id` property seems now to be `id`, I'll fix that!
