### ISSUE TITLE
Change German label key property name

### ISSUE THREAD

**Issue by lukasschnellmann** [umap-project/umap#1676]
**Is your feature request related to a problem? Please describe.**
I was trying to change the content of the label. I found that the option to do this was quite hard to find. In the German version the Label Key option in the layer properties under advanced properties is called "Anzeigeschlüssel". A user looking for this option might not figure out that this is the option he is looking for.

**Describe the solution you'd like**
Either rename the field or add a header telling the user that this field belongs to the label options.

**Describe alternatives you've considered**
Another possibility would be to move this option into the interaction options to the other label options.

**Additional context**
![image](https://github.com/umap-project/umap/assets/141338253/ede0d8b7-3298-4c3f-bd0b-6364038e4c3f)

**Comment by yohanboniface** [comment]
Translations are manager through Transifex:

https://www.transifex.com/openstreetmap/umap/

You can create an account, ask for joining the German team and suggest better translations. :)
