### ISSUE TITLE
Edit button not shown on mobile

### ISSUE THREAD

**Issue by besendorf** [umap-project/umap#1679]
**Describe the bug**
The edit button in the top right corner on desktop is not shown on mobile.

View on desktop:
![image](https://github.com/umap-project/umap/assets/26350155/0da0621f-379f-4e4b-b10f-a06e2edce1ae)
view on mobile:
![image](https://github.com/umap-project/umap/assets/26350155/f79dbe21-4483-470f-a932-445552b3e801)

**To Reproduce**
open umap on mobile

**Expected behavior**
feature parity with desktop version

**Comment by yohanboniface** [comment]
Are you logged in when you open the map on your mobile ?

**Comment by besendorf** [comment]
No, but I am also not logged in on desktop

**Comment by yohanboniface** [comment]
Can you share the map URL ?

**Comment by besendorf** [comment]
Ah sorry I didnt see that I need to enable that
