### ISSUE TITLE
After Update to 2.0.4 anonymous Edit-Links don't work

### ISSUE THREAD

**Issue by lorenzdomb** [umap-project/umap#1686]
**Describe the bug**
After I updated to version 2.0.4, I discovered that the edit links of all the maps that I installed in the old versions did not work. I get a 404 error message.

**To Reproduce**
1. docker-compose down
2. change version in docker-compose.yml
3. docker-compose pull
4. docker-compose up

**Expected behavior**
All old edit links must continue to work.

**Comment by yohanboniface** [comment]
If it's a 404, so maybe `UMAP_ALLOW_ANONYMOUS` is not defined. Are you sure it's on your custom settings ?

**Comment by lorenzdomb** [comment]
It is defined in docker-compose.yml and it works correctly for all new maps I created in the new version. 

Only for the maps created in the older versions it does not work.

**Comment by lorenzdomb** [comment]
<img width="305" alt="Bildschirmfoto 2024-03-12 um 15 13 23" src="https://github.com/umap-project/umap/assets/79528359/d15687ee-b8fd-4870-95a7-0ef38c4da85a">

**Comment by yohanboniface** [comment]
Can you share an URL that goes in 404 (without the key itself) ?

**Comment by yohanboniface** [comment]
Please reopen with more details if you still need help!
