### ISSUE TITLE
Unable to close the "data layers list" when set as open by default in Config

### ISSUE THREAD

**Issue by Binnette** [umap-project/umap#1691]
**Is your feature request related to a problem? Please describe.**
Yes. When setting the "data layer quick access list" as "opened" by default in settings. Then it is impossible to close it when viewing the map. It is OK when you consult the map on PC. But it is KO when you show the map on a phone.

Here is a phone screenshot of a map with the "impossible to close data layer list". As you can see, It take a LOT of place on the screen, so you can barely see the map content behind.

![image](https://github.com/umap-project/umap/assets/6597721/4c919ef2-a0c2-4d6c-9885-09bf2cc9c596)

**Describe the solution you'd like**
Just show the "layer" button. So that way, user can close the layers list.

This button:

![image](https://github.com/umap-project/umap/assets/6597721/43a62b60-9017-41bb-aadc-f6f7eaa86f0b)

**Describe alternatives you've considered**
Workaround is to change the setting to "close".

**Comment by yohanboniface** [comment]
Will be fixed with next release, which start a refactor of panels.

**Comment by yohanboniface** [comment]
Should hopefully now be obsolete :)
