### ISSUE TITLE
Get object data from OSM

### ISSUE THREAD

**Issue by vmartyanov** [umap-project/umap#1693]
Let's say I have a list of POIs (as a list of OSM nodes ID) I would like to see in uMap. Now I have to add them manually on map and manually add names. Or using a script to get coordinates and names from OSM, save as CSV and set it as an external data source

It would be great if uMap will fetch coordinates, names and other tag info from OSM, so giving a POI list I'll have all the info I can display on mouse hover over a point.

**Comment by clwacker** [comment]
I don't think uMap is designed to extract data directly from OSM.
However, it is perfectly possible to extract data from OSM with Overpass turbo (https://overpass-turbo.eu/) and then upload it to uMap.
I do this several times a month with over 1800 OSM points, and it takes a few minutes at most.

**Comment by yohanboniface** [comment]
One can also issue a search, in edit mode, and click on the pencil to add the point from OSM:

![image](https://github.com/umap-project/umap/assets/146023/8ad07e4d-8117-4679-a12a-96b4473b843a)

See #786 for a better integration of Overpass inside uMap. It's on the radar.
