### ISSUE TITLE
"See all" bug

### ISSUE THREAD

**Issue by Cyril5C** [umap-project/umap#1700]
**Describe the bug**
I use the side panel view, when I click on "see all" the side panel disappears.

**To Reproduce**
1. Go to https://umap.openstreetmap.fr/en/map/cafe-comptoir_1014832
2. Click on a POI to open a side panel
3. Click on "See All"
4. The side panel disappears

**Expected behavior**
We should see the data in the side panel

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : all browsers

**Smartphone (please complete the following information):**
 - Device: iPhone

**Comment by clwacker** [comment]
I see the same problem here:
https://umap.osm.ch/m/3405
