### ISSUE TITLE
Can't login with OSM credentials

### ISSUE THREAD

**Issue by Teengamer37** [umap-project/umap#1703]
**Describe the bug**
When I log in with OpenStreetMap credentials, a message shows me: 502 Bad Gateway

**To Reproduce**
I simply use the "Login" button in the main page and log in by clicking on the OpenStreetMap icon

**Desktop (please complete the following information):**
 - OS: Windows 11 64-bit
 - Browser: Brave
 - Version: 1.64.109

**Comment by yohanboniface** [comment]
Hi @Teengamer37 sorry for the late answer! I can't find anything in the logs, can you try again ? Maybe it was an outage somewhere at that moment.
Otherwise, can you give me your OSM nickname, so I can investigate ?

**Comment by Teengamer37** [comment]
@yohanboniface sorry I forgot to close and delete the report: it was only an outage… thanks anyway!
