### ISSUE TITLE
Umap map - How to unify the cities (like Beijing and Shanghai) into "identical" country (China) after import umap files?

### ISSUE THREAD

**Issue by CBRE-TW** [umap-project/umap#1707]
I have 2 city umap files (Shanghai and Beijing) with polygon marked on each. I need to load them together under "identical" China but now they're show "separately" like below :

![image](https://github.com/umap-project/umap/assets/99246319/274ae9aa-a615-4470-b6ff-42aaba033e3f)

- Things I try:
 There's a chinese layer name in Shanghai file, I adjust them in English but still not work
One of alternative was to move the polygon manually from "A" China to "B" China, but I have a lot of polygon, and the "moving" distance is a bit long, it's quite stupid to do that

- Things I expect:
 both cities show in identical China in map

**Comment by yohanboniface** [comment]
Can you share your data ? I suppose one file has longitudes > 180

**Comment by CBRE-TW** [comment]
Hi yohanboniface,

Thanks for the info.
Yes, you're right, Shanghai lat was ~31 while long was ~ -238 in the file but the longitude should be around 121 ....

I try to edit the longitude (replace all numbers with ~238 to 121).  the image was skewed to the right hand side of "Shanghai" and most importantly, the polygon were twist around. I attached the file in below, appreciate for your help.

Thanks.

Regards,
Thomas
[umap_Shanghai_test.txt](https://github.com/umap-project/umap/files/14792840/umap_Shanghai_test.txt)

**Comment by CBRE-TW** [comment]
Hi All,

The issue was the creator chose a "different" China to draw Shanghai and Beijing polygon that cause the issue.

As from above, the image was twist around when I adjust longitude by +360 to 121, but when I adjust that by -360 to -598, the image direction was correct but it place at a further left-hand side China ....

Any suggestion on this and anyone know the reason why the image direction will twist when +360 but not when -360 on longitude ? 

Thanks a lot for yours' help !!

Regards,
Thomas

**Comment by yohanboniface** [comment]
Here is what I see when importing your dataset ([umap_Shanghai_test.txt](https://github.com/umap-project/umap/files/14792840/umap_Shanghai_test.txt)):

![image](https://github.com/umap-project/umap/assets/146023/b9cd2ab6-7d64-486c-8316-137ab5485f8f)

I'm not sure what wrong for you in this, can you give me more details ?
