### ISSUE TITLE
Text formatting in the description field

### ISSUE THREAD

**Issue by Aurelie-Jallut** [umap-project/umap#1710]
**Is your feature request related to a problem? Please describe.**
The text displayed in the help modal gives the impression that it's going to be complicated to create.
the term Iframe, for example, is not understood by non-tech users.

![image](https://github.com/umap-project/umap/assets/131352601/4831607b-3e7d-400d-b0ee-787f46ec5cbf)

**Describe the solution you'd like**
We could add buttons for styling in Markdown

**Describe alternatives you've considered**
We could improve the text in the modal

**Comment by PeskyPotato** [comment]
Related to #813

**Comment by yohanboniface** [comment]
Closing in favor of #1950
