### ISSUE TITLE
About panel disappears

### ISSUE THREAD

**Issue by Cyril5C** [umap-project/umap#1711]
**Describe the bug**
I use the side panel view, when I click on "About" the side panel disappears.

**To Reproduce**

- Go to https://umap.openstreetmap.fr/en/map/cafe-comptoir_1014832
- Click on a POI to open a side panel
- Click on "See All"
- Click on "About"
- The side panel disappears

**Expected behavior**
We should see the "About" Panel
Probably related to :  https://github.com/umap-project/umap/issues/1700

**Comment by yohanboniface** [comment]
Should have been fixed in latest release (and the UI will change in next one anyway).

**Comment by Cyril5C** [comment]
Cool, thanks for the great job you do!When is planified the release with the new UI? Can’t wait! ;)Le 16 avr. 2024 à 15:29, Yohan Boniface ***@***.***> a écrit :﻿
Should have been fixed in latest release (and the UI will change in next one anyway).

**Comment by yohanboniface** [comment]
I'd say around next week :)
