### ISSUE TITLE
Side panel at full height

### ISSUE THREAD

**Issue by Cyril5C** [umap-project/umap#1712]
**Is your feature request related to a problem? Please describe.**
It is not very easy to scroll the side panel on mobile

**Describe the solution you'd like**
Have the option of having the side panel at max. height. This is equivalent to having a list mode. See screenshot above : 

<img width="462" alt="Capture d’écran 2024-03-26 à 11 31 25" src="https://github.com/umap-project/umap/assets/64784806/e87bafca-f072-49b8-99b0-bbbad42e83e8">

**Additional context**
It means that when your in the panel "Browse data" you have to hide the switch "Current Map View"

Thanks you for all the good work !

Cyril.

**Comment by davidbgk** [comment]
We are [actively working](https://github.com/umap-project/umap/pull/1687) on such improvement 👍

**Comment by Cyril5C** [comment]
Top!

**Comment by yohanboniface** [comment]
Should be good now!
