### ISSUE TITLE
datalayers format change broke my maps

### ISSUE THREAD

**Issue by baikiet** [umap-project/umap#1714]
**Describe the bug**
I built a map with a few layers, some combinations of which I embed on a website. The way layers are named in the URL seems to have changed. That broke the website. For example, I am embedding this URL :

https://umap.openstreetmap.fr/en/map/vol-libre-jura_980516?datalayers=3058582#11/47.2767/7.3087

That was working fine until a few days/weeks ago. Now it doesn't show the layer. The new correct URL seems to be this:

https://umap.openstreetmap.fr/en/map/vol-libre-jura_980516?datalayers=159d6396-daf5-48cf-a523-7b6c5c1be3d3#11/47.2767/7.3087

**To Reproduce**
See above.

**Expected behavior**
Valid URL should not change.
https://www.w3.org/Provider/Style/URI

If the change/breakage was inevitable, some sort of notification to users would have been unavoidable.

**Additional context**
I believe this is related to a change from ID to UUID for layers. I found a related commit in https://github.com/umap-project/umap/commit/1b41ff0ddc7e97a592fabaa5da7580bde9f960c9 but there is no explanation of why or whether there was an intention for this to be backwards compatible.

**Comment by baikiet** [comment]
I fixed the URLs linked from https://vollibrejura.ch/spots-vlj/

The following ones are still broken:
https://vollibrejura.ch/?page_id=19200
https://vollibrejura.ch/?page_id=20321
https://vollibrejura.ch/?page_id=20208
https://vollibrejura.ch/?page_id=20273

Can you please confirm whether that's something you plan to fix on your side or should I fix manually on my side?

**Comment by yohanboniface** [comment]
Thanks for the report, and sorry for the inconvenience.
The datalayer id have indeed changed, and this use case seem to be missing from our test cases / radar, and I'm sorry for that.
We'll have a look now. Hopefully we'll have a fix on our side, I'll let you know!
