### ISSUE TITLE
Question about Heatmap

### ISSUE THREAD

**Issue by dancesWithCycles** [umap-project/umap#1715]
**Is your feature request related to a problem? Please describe.**

Hi folks,
Thank you so much for maintaining and providing this repository!

I created this Umap including a heat map layer for public transport stops.

https://umap.openstreetmap.fr/en/map/braunschweig_1045019#12/52.2717/10.5356

I set the heat map radius to 100. I reckon the value 100 means a radius of 100 meters from the origin of a pin, right?

When I zoom in or out I observe that the radius is adjusting along the zoom. In other words, the area around a pin is painted in different colors depending on the zoom level.

**Describe the solution you'd like**

I would have expected a constant radius of 100 meter around pins not matter the zoom level. That means, the area around a pin is always painted in the same color depending on the radius configuration.

Is my expectation wrong?

**Describe alternatives you've considered**

I have no alternatives considered yet.

**Additional context**

I have neither context nor screenshots.

Cheers!

**Comment by yohanboniface** [comment]
> I set the heat map radius to 100. I reckon the value 100 means a radius of 100 meters from the origin of a pin, right?

Nope, it's in pixels. This is the behaviour from the [plugin](https://github.com/Leaflet/Leaflet.heat) we use, and I don't think it's easy to change that.

I'm closing as I think this is the expected behaviour, but please do not hesitate to comment with more use case and feedback to argument!
