### ISSUE TITLE
Zoom issue

### ISSUE THREAD

**Issue by jdo075** [umap-project/umap#1720]
Since yesterday end of the day. When i zoom on any maps. The backgroupd does not refresh so i can'ts seee street name. Only grey backgroung.

I try on several device ans 3 internet connetion. Same issue evrythere

Thanks for your help

Regards

JDO

**Comment by yohanboniface** [comment]
Can you share a map URL please ?

**Comment by jdo075** [comment]
Hello Hohan

Here is the link
https://umap.openstreetmap.fr/fr/map/space-invaders_425001#13/48.8001/2.4199

Regards

**Comment by yohanboniface** [comment]
Ok, so I think it's the background layer having an issue. Try using another until it cames back on life. :)
