### ISSUE TITLE
Gradient for markers within a layer

### ISSUE THREAD

**Issue by el-srabo** [umap-project/umap#1721]
For now, when choosing the color of the markers within one layer, one can only set a single color. Would it be possible to add the option to choose a gradient instead, so that each marker would be a slightly different color? This would be really useful for maps where markers have a chronological order!

Thanks for maintaing this really cool project!

**Comment by yohanboniface** [comment]
Have you tried playing with the choropleth mode for that ? I needs a property with an integer value though.

**Comment by el-srabo** [comment]
I still haven't had the opportunity to look into this, I'll reopen the issue in case I need help when I do!

**Comment by el-srabo** [comment]
Closing the issue
