### ISSUE TITLE
[wishlist] Add markdown support for popups, credits and other text fields.

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#173]
Originally reported by: **Cristian Consonni (BitBucket: [CristianCantoro](http://bitbucket.org/CristianCantoro), GitHub: [CristianCantoro](http://github.com/CristianCantoro))**

----------------------------------------

"Markdown is a markup language with plain text formatting syntax designed so that it can be converted to HTML and many other formats" (from [Wikipedia](https://en.wikipedia.org/wiki/Markdown)).

Here there are the [specifications for Markdown](http://daringfireball.net/projects/markdown/).

From a quick search, the following modules should support Markdown in text fields for Django applications:

* [django-markupfield](https://github.com/jamesturk/django-markupfield)
* [django-markdown](https://pythonhosted.org/django-markdown/)

----------------------------------------
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/173

**Comment by bricewge** [comment]
Why does this issue has been closed? It sound like a good idea to use the most common markup language.

**Comment by Hugo-Trentesaux** [comment]
I do not know, but there is some base wiki-style markup language:

```
Text formatting

    *simple star for italic*
    **double star for bold**
    # one hash for main heading
    ## two hashes for second heading
    ### three hashes for third heading
    Simple link: [[http://example.com]]
    Link with text: [[http://example.com|text of the link]]
    Image: {{http://image.url.com}}
    Image with custom width (in px): {{http://image.url.com|width}}
    Iframe: {{{http://iframe.url.com}}}
    Iframe with custom height (in px): {{{http://iframe.url.com|height}}}
    Iframe with custom height and width (in px): {{{http://iframe.url.com|height*width}}}
    --- for an horizontal rule
```
