### ISSUE TITLE
Data Loss over night

### ISSUE THREAD

**Issue by EmreNator** [umap-project/umap#1730]
Hello!

yesterday i worked on the map, adding more details about the already existing markers, i just editet them and saved.

Now after i came back to work on it again (1day later) everything is gone?? Even the markers that i didnt touch. 

I will need atleast 2 weeks when i have to begin from 0.. I also tried getting the older version, its from 15.01.24 but also there nothing comes up? The map is much older, so it should have atleast some old markers from 15.01.24?

I also tried it on a new browser etc. Is there anyway to get a backup from somewhere?
![Screenshot 2024-04-03 100542](https://github.com/umap-project/umap/assets/165885128/de852890-26f9-4916-bc56-26cd99de0c6e)

Map: https://umap.openstreetmap.de/de/map/karte-volker_21477#12/50.9636/10.8524
![Screenshot 2024-04-03 100542](https://github.com/umap-project/umap/assets/165885128/6f3be66f-068f-4348-bc55-541a7ed44a36)

**Comment by gislars** [comment]
sorry to hear you are having trouble with umap running on the German server. I upgraded yesterday (around 17:45 local time) to the newest version 2.1.3.  (from 2.1.1)
At least one other user had problems saving data to a layer. After the upgrade the user could successfully save the data again. There actually was an issue which is described in this [ticket](https://github.com/umap-project/umap/issues/1714). 

Please try again to edit your layer(s) and/or try revert to a previous version. If the problem still exists please report back.

**Comment by EmreNator** [comment]
thank you for responding. Unfortunately nothing changes, Also the old layer from 25.01.2024 is suspicious small with 0,1 kB, i dont even think that there is anything still saved, please help me to get atleast some old data back, since it was a lot of work to get all the data in. 

Thank you in advance

**Comment by gislars** [comment]
I was able to start up a backup locally. If you recognize this data, I can send you the .umap and .geojson files. Let me know where.
![Bildschirmfoto vom 2024-04-04 09-46-00](https://github.com/umap-project/umap/assets/402166/2767065a-34a7-4741-ba2f-831d9fa5966e)
