### ISSUE TITLE
Le bouton "Enregistrer" ne fonctionne plus

### ISSUE THREAD

**Issue by lameuledefoin** [umap-project/umap#1732]
Présent par défaut à l'ouverture de la carte (ce qui n'était pas le cas auparavant), le bouton "Enregistrer" n'a plus d'effet quand on clique dessus après avoir réalisé des modifications sur la carte (important de trace GPX, modifications de paramètres de couleur ou de forme, changement de fond de carte, de point de centrage...)

**Comment by davidbgk** [comment]
Comme mentionné dans le gabarit d'issue, pas d'aide possible sans lien vers une carte.
