### ISSUE TITLE
Layer appears completely empty, file might be broken

### ISSUE THREAD

**Issue by der-paule** [umap-project/umap#1735]
**Describe the bug**
I have a map on uMap with 20-25 layers. One of them is not displaying it’s data anymore. It is visible in the layers list, but greyed out like I’d made it invisible. Klicking on the button to make it visible does nothing, as do all the other buttons. In the “show data” window, it shows zero data in that layer. Trying to download the whole map from the dashboard gets me an error message: "[Errno 2] No such file or directory: '/srv/umap/data/datalayer/0/8/45080/167dcc2b-5f61-4465-9bfa-5991beafc90d_1711816555939.geojson'". Trying to duplicate the map from the dashboard only gives me a duplicate with three layers.

**To Reproduce**
1. Go to 'https://umap.openstreetmap.de/de/map/schienenbahn_45080'
2. Click on 'view data layers'
3. Scroll down to 'U-Bahn'
4. See layer 'U-Bahn' greyed out
5. Click on 'Show data'
6. See zero data in layer 'U-Bahn'

**Expected behavior**
To have access to my data

**Screenshots**
![Screenshot 2024-04-07 134222](https://github.com/umap-project/umap/assets/166299441/5e139ae1-7a2d-4e09-8e94-5d950e4ead6c)
![Screenshot 2024-04-07 134240](https://github.com/umap-project/umap/assets/166299441/6efed57b-73c4-4784-81da-e2af62fc3212)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 124.0.2

**Additional context**

**Comment by gislars** [comment]
Did you edit your map or the layer with missing data between March 25th and April 2nd? I guess then you are effected by an bug which caused a data loss. The bug is fixed and it was deployed on April 2nd on umap.openstreetmap.de

If it helps I can send you a backup of your U-Bahn layer or your whole map with all layers from end of February this year. Let me know how I can send it to you.

**Comment by der-paule** [comment]
Thank you so much! I think I edited the layer on March 30 but I can recreate it. So if you could send me the layer I'd appreciate it :)
I'll shoot you an email.

**Comment by davidbgk** [comment]
Thank you @gislars (and sorry for that bumpy release…), could you close the issue if the map is now OK?
