### ISSUE TITLE
Can I really delete a map I don't own ?

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#1739]
**Describe the bug**
The list of maps in my dashboard shows the Delete button for maps I don't own and cannot edit.

**To Reproduce**
1. I open my dahsboard (user Carto'Cité)
2. There is a map called 'test2', owned by someone else, only the owner can modify that map.
3. The Delete map button is available and I can press it.
4. A message pops up : "Are you sure you want to delete this map?" (translation missing btw)

**Expected behavior**
Either the Delete button should be deactivated, or the message should say "You cannot delete this map owned by XXX."
I haven't actually tried to delete it, the message may pop up then but that still leaves some doubt on the actual risk of deleting someone else's map.

Instead, I want to be able to remove that map from my dashboard (enhancement request) :)

**Comment by yohanboniface** [comment]
> Either the Delete button should be deactivated

PR for that #1748 :)

>  The list of maps in my dashboard shows the Delete button for maps I don't own and cannot edit.

You are on the list of editors of this map, don't you ?

**Comment by naomap** [comment]
> You are on the list of editors of this map, don't you ?

I am indeed. I happen to be an editor of many maps from people I trained. This makes me think of a couple of features I would like to see: 
- give up being an editor of a map (without asking the owner)
- ability to sort (and filter ?) the maps in the dashboard : by name, date or owner

I can write up a feature request if these have not been requested yet.
