### ISSUE TITLE
Piano and Forte map backgrounds are broken - ANCT instance

### ISSUE THREAD

**Issue by Aurelie-Jallut** [umap-project/umap#1740]
**Describe the bug**
When I create a map on https://umap.incubateur.anct.gouv.fr all I see is a gray background and no map background.
When I open the map background editor, I see that the Piano and Forte map backgrounds are broken.

**To Reproduce**
https://umap.incubateur.anct.gouv.fr
Se connecter
Créer une carte

**Expected behavior**
Displaying a background map

**Comment by Aurelie-Jallut** [comment]
This morning it was broken on an agent's computer. Have you intervened on your side since ?

**Comment by davidbgk** [comment]
No, maybe there was an issue at that moment.

**Comment by Aurelie-Jallut** [comment]
I saw the same problem on another agent's computer last week => I'm going to send an e-mail to both of them to find out if the problem has been resolved since.

**Comment by Aurelie-Jallut** [comment]
I've had 2 replies and the problem is still there: 

"So as it stands, alas, no card is displayed... (whether I log in to my account or not). Gray page.
- Firefox Browser - Extended Support Release - version 115.2.0esr (64 bits)"

"the display problem persists.
I'm using Firefox Browser, version 115.2.0"

**Comment by yohanboniface** [comment]
I know the style has been moved to a new server, is the issue still present ?

**Comment by yohanboniface** [comment]
Should be fixed since then.
