### ISSUE TITLE
Use custom pictures as background map

### ISSUE THREAD

**Issue by tech62** [umap-project/umap#1741]
**Is your feature request related to a problem?
No, i wanted to know if it is possible to develop a possibiity to use png/jpg/ vectorial pictures as background maps

**Comment by davidbgk** [comment]
If you have your own instance, you can setup your own `TileLayer` from the Django admin.

**Comment by yohanboniface** [comment]
You can use https://mapwarper.net/ to transform an image as a tilelayer.
