### ISSUE TITLE
Tried to import two KML files...

### ISSUE THREAD

**Issue by jidanni** [umap-project/umap#1743]
Here nothing happens why trying to upload KML.
![Screenshot 2024-04-15 14 59 55](https://github.com/umap-project/umap/assets/1230959/2e56e3a0-6109-4839-887f-8ec0b50622a3)

Your form doesn't accept KMZ, so I used unar(1) to extract the two KMLs in found in 
[a0andHouses.kmz.gz](https://github.com/umap-project/umap/files/14975351/a0andHouses.kmz.gz)
a .KMZ, which I have zipped, to be able to post it to GitHub.)
I then attempted to import them into Umap, but nothing happened.

**Comment by yohanboniface** [comment]
Works for me:

![image](https://github.com/umap-project/umap/assets/146023/5d1236dc-44ae-4fee-9a53-db94514a47d2)
