### ISSUE TITLE
Pouvoir dupliquer une donnée ?

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#178]
Originally reported by: **Vincent Bergeot (BitBucket: [vinber](http://bitbucket.org/vinber), GitHub: [vinber](http://github.com/vinber))**

----------------------------------------

Bonjour,
la possibilité de dupliquer (cloner) existe au niveau de la carte et des calques, mais pas au niveau des données.

Cela peut-être pratique pour des données "similaires" mais pas localisées au même endroit.

----------------------------------------
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/178

**Comment by yohanboniface** [comment]
Fixed in https://github.com/umap-project/Leaflet.Storage/commit/9eb80d73e8b79b284e03af971b5035ef4229d75e

**Comment by vinber** [comment]
thanks
