### ISSUE TITLE
Release 2.2.2 on Mobile device

### ISSUE THREAD

**Issue by Cyril5C** [umap-project/umap#1788]
Hi, 

Thanks a lot for the 2.2.2 which brings better UI for desktop, but... I am using uMap a lot on my iPhone, i have a couple of feedbacks : 
## When i want to filter a part of the "modal" is hidden : 
![IMG_4650](https://github.com/umap-project/umap/assets/64784806/db817602-c1c8-4802-b9b8-df1f4a95a103)

## I can't expand the modal as I can on desktop, the button doesn't appear. I'd love to see the modal on full screen
![IMG_4649](https://github.com/umap-project/umap/assets/64784806/0c0fd5c7-e7da-4cba-8bd4-40a08845c589)

Again thanks a lot for the great job you're doing!

Cyril.

**Comment by yohanboniface** [comment]
Thanks for your feedback, we'll work on this :)
