### ISSUE TITLE
Allow html dir attribute 

### ISSUE THREAD

**Issue by iriman** [umap-project/umap#1796]
**Is your feature request related to a problem? Please describe.**
I use dir="auto" in pop-ups so direction of text is based on line content. This is especially useful when someone uses browser translate function to machine-translate content. When text is translated to a rtl or ltr language its direction is fixed automatically.
On previous versions of umap it was possible to use dir attribute. With new updates seems it is disabled.

**Describe the solution you'd like**
Please allow using dir attribute in html in pop-ups.

example pop-up that has dir="auto" in its template: [link](https://umap.openstreetmap.fr/en/map/map_943303?feature=%D8%AF%DA%A9%D8%A7%D9%86%20%D9%86%D8%A7%D9%86%D9%88%D8%A7%20%D8%A8%D8%A7%D8%B4%DB%8C#13/35.7889/51.4869)

**Comment by davidbgk** [comment]
We forgot that use-case when we updated the policy on HTML attributes, thanks for reporting this pertinent case!

**Comment by iriman** [comment]
Thanks! Could you allow **title** too? for a tooltip when cursor is over an element. I forgot to mention it.
