### ISSUE TITLE
Localization not working on laptop or mobile not matter 

### ISSUE THREAD

**Issue by dancesWithCycles** [umap-project/umap#1812]
Hi folks,
Thank you so much for providing and maintaining this repository!

I am aware of these issues.

* https://github.com/umap-project/umap/issues/634
* https://github.com/umap-project/umap/issues/623
* https://github.com/umap-project/umap/issues/1352
* https://github.com/umap-project/umap/issues/1006

Still, I am not able to get the localization feature working on either laptop Firefox (115.9.1esr (64-bit)) or Chromium (123) nor mobile Android Chrome or Firefox (125.3.0).

On laptop Chromium (Version 123.0.6312.105 (Official Build) built on Debian 12.5, running on Debian 12.5 (64-bit)) I received this notification, that disappeared after about a second
```
Geolocation error: Failed to query location from network service. Check the DevTools console for more information..
```

From the console I can read the following.
```
gompass_1045554#12/52.2761/10.5131:1 Network location provider at 'https://www.googleapis.com/' : Returned error code 429.
```

On laptop Firefox () I read these logs from the console.
```
Use of the orientation sensor is deprecated. [DomEvent.js:135:7](https://umap.openstreetmap.fr/static/umap/vendors/src/dom/DomEvent.js)
Uncaught TypeError: this._map is null
    _isOutsideMapBounds L.Control.Locate.js:865
    setView L.Control.Locate.js:563
    _onLocationFound L.Control.Locate.js:788
    fire Events.js:195
    _handleGeolocationResponse Map.js:718
    locate Map.js:647
    _activate L.Control.Locate.js:494
    _activate umap.controls.3d30884eabc9.js:232
    start L.Control.Locate.js:443
    _onClick L.Control.Locate.js:431
    onAdd L.Control.Locate.js:379
    handler DomEvent.js:108
[L.Control.Locate.js:865:26](https://umap.openstreetmap.fr/static/umap/vendors/src/L.Control.Locate.js)
```

This log includes this [learn more](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default) link.

I am testing these maps.

* https://umap.openstreetmap.fr/en/map/braunschweig_1045019
* https://umap.openstreetmap.fr/en/map/vbn_1047983
* https://umap.openstreetmap.fr/en/map/gompass_1045554

When I go to either of those maps, I hit the "Current Location" button. I acknowledge, when the browser is asking me for the privilege to use the location feature. The "Current Location" button design is switching to the one with the dot at the center. Anyhow, The map does not move to the center of my current location.

From what I have heard or read about other Umap Instances, I expected to see the map switch to my current geographical location after hitting the localization button.

You can see, that all links are using HTTPS mode.

Any hints what I am doing wrong?

Cheers!

**Comment by yohanboniface** [comment]
Can you test here https://domoritz.github.io/leaflet-locatecontrol/demo/ ?

**Comment by dancesWithCycles** [comment]
> Can you test here https://domoritz.github.io/leaflet-locatecontrol/demo/ ?

The localization on this site works on either laptop or mobile. Can you conclude something from this observation?

Cheers!
