### ISSUE TITLE
Data lists and filters have disappeared

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#1813]
**Describe the bug**
I had a map set up with filters and facets. I can no longer view filters and facets on this map.

**To Reproduce**
1. Go to 'http://u.osmfr.org/m/897554/
2. Click on 'À propos'
3. There is just one tab on the panel, showing the list of layers.

**Expected behavior**
There used to be 2 other tabs, one to view and filter the data, the other one showing facets..

**Screenshots**
![image](https://github.com/umap-project/umap/assets/6516063/b04b1f96-a99f-4db3-9808-231f06bb71f5)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : Firefox

**Comment by naomap** [comment]
Ok, found it : this has moved to the data layers panel. Makes sense to me.

One detail though : the tooltip still says "Voir les calques" whereas the panel title is "Visualiser les données"
![image](https://github.com/umap-project/umap/assets/6516063/ea363574-3fb2-46a6-9da0-4a4196ef4dae)

**Comment by yohanboniface** [comment]
Titles have been updated
