### ISSUE TITLE
Heatmaps appear in 'Manage layers' but not in the 'Browse data' tab.

### ISSUE THREAD

**Issue by rprovilij** [umap-project/umap#1820]
**Describe the bug**
Any type of layer usually appears in the 'Browse data' tab. However, heatmaps are now excluded and can only be viewed in Edit mode via the 'Manage layers' tab. 

**To Reproduce**
1. Go to http://u.osmfr.org/m/1021391/
2. Click on 'See layers' and you'll find them missing as shown in the image below. 

**Screenshots**
![Screenshot 2024-05-13 222750](https://github.com/umap-project/umap/assets/81406457/c981a387-ecff-46e5-8772-38b0797ce710)

**Comment by yohanboniface** [comment]
heatmaps, given their granular data is not interactive, has never appeared in the data browser. But they should appear in the caption (the <i> button) still, but in this case they are not because they are not loaded yet. Fix is coming, thanks for the report!
