### ISSUE TITLE
in editing : the layers panel automatically closes

### ISSUE THREAD

**Issue by Aurelie-Jallut** [umap-project/umap#1831]
**Is your feature request related to a problem? Please describe.**
In editing, when I perform an action in the Layers panel, the panel automatically closes, even though I want to perform several actions.

**Describe the solution you'd like**
I'd like the panel to stay open and close either when I click on another toolbar button, or when I close the panel.

**Comment by yohanboniface** [comment]
It should be automatically closing "only" when hitting save ? Is that the case, or is it closing after some other action ?

For the save case, there already is an issue: https://github.com/umap-project/umap/issues/1139

I can't remember why this is not fixed yet, I'll have another look.

**Comment by Aurelie-Jallut** [comment]
It should be automatically closing "only" : When you press save or click on another toolbar button.

Here it closes when, for example, I click on the garbage to delete a layer.

**Comment by yohanboniface** [comment]
> Here it closes when, for example, I click on the garbage to delete a layer.

I guess you mean when clicking on the garbage in the datalayers list ?

Here ?

![image](https://github.com/umap-project/umap/assets/146023/8d68625b-c94c-48a3-8219-0accd98dba14)

If yes, this one is also known: #498 

I'm working on it now.

> When you press save

So you confirm that when hitting save, the edit panel should close, whatever it is showing ?

**Comment by Aurelie-Jallut** [comment]
no, i think when you click on save, the panel can remain open.

It can be closed by clicking on close or on another toolbar button that opens a panel.
