### ISSUE TITLE
"https:" missing in "Embed the map"

### ISSUE THREAD

**Issue by Cyril5C** [umap-project/umap#1855]
**Describe the bug**

Hello, 
I guess the "https:" is missing in the src of the iFrame

<iframe width="100%" height="300px" frameborder="0" allowfullscreen allow="geolocation" src="//umap.openstreetmap.fr/fr/map/cafe-comptoir_1014832?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&editMode=disabled&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=none&captionBar=false&captionMenus=true"></iframe><p><a href="//umap.openstreetmap.fr/fr/map/cafe-comptoir_1014832?scaleControl=false&miniMap=false&scrollWheelZoom=true&zoomControl=true&editMode=disabled&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=none&captionBar=false&captionMenus=true">Voir en plein écran</a></p>

Thanks !

Cyril.

**Comment by davidbgk** [comment]
This is valid and will avoid mixed-content errors with http vs. https contents.

**Comment by yohanboniface** [comment]
See also https://github.com/umap-project/umap/issues/1397 ;)
