### ISSUE TITLE
list of layers presented by About in reverse order

### ISSUE THREAD

**Issue by clwacker** [umap-project/umap#1874]
My map has just been upgraded to uMap 2.3.1 and I've changed the order of 2 layers after the upgrade. I now notice that when I click on About (À propos), the list of layers is presented in the reverse order to that in the edit panel.

I don't think there's an option to change the display order, could this be a bug?

My map: https://umap.osm.ch/m/3405

**Comment by clwacker** [comment]
I have another map on the same uMap server that I haven't modified for many months and I see that the order of the layers is now also reversed in the list under About (À propos).

**Comment by yohanboniface** [comment]
Thanks for the report! Should be fixed in next release.

**Comment by clwacker** [comment]
thank you and well done for your speed
