### ISSUE TITLE
Direct link to a POI

### ISSUE THREAD

**Issue by Cyril5C** [umap-project/umap#1893]
Hello,
I'd like to have what's called a "share" link for POIs. When this link is clicked, the map loads with the POI panel open.
Thanks a lot!
NB: perhaps this is already possible via a geek trick ;)
Cyril.

**Comment by yohanboniface** [comment]
It's already possible, but will be refactor soon.

For now, you have to set an identifier key (a name of a column):

![image](https://github.com/umap-project/umap/assets/146023/837734e6-508b-4cab-ac0c-f68a2d16d338)

Then right-click on a feature:

![image](https://github.com/umap-project/umap/assets/146023/2948edb2-d970-4dd3-8381-a3cff499ea26)

**Comment by Cyril5C** [comment]
Ok great! It works well except when you have defined a "panel on load". But i guess it's not a priority bug as you are in the middle of a refacto. 
Thanks.

**Comment by Cyril5C** [comment]
arf and it doesn't work on mobile... for exemple : https://umap.openstreetmap.fr/fr/map/cafe-comptoir_1014832?feature=rectC21sHWLMEeBaa (works on my mac but not on my iPhone)

**Comment by yohanboniface** [comment]
> Ok great! It works well except when you have defined a "panel on load"

We could give priority to the feature in that case, I think it makes sense.

> arf and it doesn't work on mobile

Can you be more explicit ?

**Comment by Cyril5C** [comment]
when i open the link on mobile the panel does not open

**Comment by yohanboniface** [comment]
BTW, just having a look at your map, have you tried setting a filter key like this ?

![image](https://github.com/umap-project/umap/assets/146023/591cb1e8-f998-4400-bf36-10277260cb36)

**Comment by Cyril5C** [comment]
ooh ! mais non c'est génial !

**Comment by yohanboniface** [comment]
Avec un filtre sur le prix aussi:

![image](https://github.com/umap-project/umap/assets/146023/bc307b37-864b-4bce-a20e-4618941102e7)

**Comment by Cyril5C** [comment]
Merci pour le petit coup de pouce sur les filtres, par contre les filtre "number" ne marchent par avec des chiffres avec des virgules, j'ai contourné en dupliquant le champ et en remplacant la virgule par un point. Mais pour les français ca serait bien d'accepter les points et les virgule.
C'est top de voir uMap progresser de jour en jour !

**Comment by yohanboniface** [comment]
Numbers formatting depends on the locale (eg. in the US a `,` is a thousand separator: `10,323,234`).

We can display a number according to user locale, but there is not helper in the browser for parsing according to locale, plus we don't know the locale used when the number was typed.

So at this stage the only solution I see is to use "machine ready" numbers in the data, and:

- use a localized version for displaying it, so it's more user friendly
- when (if) we add typing of columns, allow to define an input format, so users can also type the number in their locale

**Comment by yohanboniface** [comment]
(Closing the original issue as it's fixed, and the number related discussion is about typing, which is another story)
