### ISSUE TITLE
Support for Overture maps to be imported within the tiles

### ISSUE THREAD

**Issue by milind-soni** [umap-project/umap#1909]
**Is your feature request related to a problem? Please describe.**
It will be really useful to import Overture maps buildings GeoJson

**Describe the solution you'd like**
Ability to integrate and import the data from the overture maps API easily

**Comment by yohanboniface** [comment]
Thanks for the suggestion.

Can you be more explicit on:
- which API you'd like to be used ?
- what Overture data gives you more dans OpenStreetMap one ?

Thanks!

**Comment by yohanboniface** [comment]
Closing for now. Please reopen if needed, with greeter details / use cases.
