### ISSUE TITLE
Reduce the line spacing of the panel title

### ISSUE THREAD

**Issue by Aurelie-Jallut** [umap-project/umap#1927]
**Is your feature request related to a problem? Please describe.**
When the title is long and spans two lines, the rest of the title is lost because it appears too low. 

**Describe the solution you'd like**
line-height: 1; would be sufficient 
![image](https://github.com/umap-project/umap/assets/131352601/a39a395d-d369-4ae2-a671-07601ecd7eca)

**Additional context**
![image](https://github.com/umap-project/umap/assets/131352601/ef3e45d2-aa74-45f3-a6d1-78bc0b3ecfba)

**Comment by yohanboniface** [comment]
This should already have been fixed in dev, have you tested ?

**Comment by Aurelie-Jallut** [comment]
yes, it's on the dev!

We could take advantage of this to : 
- reduce the h3 
font-size: 1rem; 
we're talking about it here : https://github.com/umap-project/umap/issues/1911

- and put some space between the title and the Credits tab :)

**Comment by yohanboniface** [comment]
can you share a link to the map on dev ?

**Comment by yohanboniface** [comment]
Can you give me the size for h4, h5, h6 too ?

**Comment by Aurelie-Jallut** [comment]
h3 {
  font-size: 1rem;
}

h4 {
  font-size: 0.9rem;
}

h5 {
  font-size: 0.8rem;
}

h6 {
  font-size: 0.7rem;
}

for h5 and h6 I did a little test in the view inspector :
![image](https://github.com/umap-project/umap/assets/131352601/d3d9845b-a7b4-4734-a529-d5c89c2c1452)
