### ISSUE TITLE
uMap Freezes when editing big >2mb OSRM-GPX traces

### ISSUE THREAD

**Issue by skyrl69** [umap-project/umap#1966]
**Describe the bug**
This is maybe more an unresponsiveness behavior than a bug, literaly speaking :
When I try to edit an imported GPX trace >2mb, made with OSRM, uMap will freeze with CPU 100%. After ten seconds or so the browser signals that uMap is not responding, and ask to wait or reload the page. Depending on the size of the GPX trace, the page will recover responsiveness, or will lead to crash of the browser.
+ If I reload the page, all my modifications are lost. Obviously

**To Reproduce**
1. Go to https://umap.openstreetmap.fr/en/map/anonymous-edit/1089775:BrKRjkrNd8G6w-v0AX_7Gy5G8_7TMZhDyWFF-XikqgE (french instance of umap)
     or https://umap.openstreetmap.de/en/map/anonymous-edit/63092:Rhxx1irDhFVpNx-lNetLQo5ibufeyjHXnPuczC1s0M4 (german instance)
2. Click Edit button on top right corner of the view
3. Click on Import Button : It is the last button bottom-down the right edge of the screen (an upload arrow)
4. Choose a GPX trace >2mb, computed and exported by OSRM tool (https://map.project-osrm.org/)
5. The trace is quickly added to a new layer, and shown in uMap
6. Zoom and click on that trace (left mouse button) : two small context buttons will show, a pencil and a trashbin
7. Click on edit context button (the pencil) : Instantly the page is freezing

**Expected behavior**
Either :
- Allow to edit the trace in matter of seconds
- Says it will take too long to make the trace editable
- Forbid point editing since the trace's too complex for edition
- Offers a way to stop entering in edition mode
- At least not freezing, or at least a way to recover unsaved data...

**Desktop : Win10 x64 Brave 1.67.123 Chromium 126 x64**

**Screenshots of normal behavior**
🆗 1) 56 nodes 2489bytes GPX
![image](https://github.com/umap-project/umap/assets/45392236/581eda79-5632-49b5-9156-1f6a15da6d09)

🆗 2) 1716 nodes, 62kb GPX trace from Namur to Liege
![image](https://github.com/umap-project/umap/assets/45392236/e9f835a7-b1b8-45c2-a838-a0f6d31c6680)

**Screenshots of enhancable behavior**

⚠3) 29878 nodes, 1.05mb GPX trace from Paris to Berlin
Took 70sec CPU 100% to compute ! Thread reached 1.7gb in memory heap. After that, Chrome is keeping is responsiveness
![image](https://github.com/umap-project/umap/assets/45392236/9d5096e2-60d1-4a33-a1f4-04080559932c)

❌4) 59869 nodes, 2.00mb GPX trace from Paris to Riga, Moscow, Venise

Took 11 minutes to process, thread reached 3.5gb in memory heap
After what, UI is stalling, not responsive, objects are not shown correctly, and nothing can be done anymore until the tab is closed

a) ![image](https://github.com/umap-project/umap/assets/45392236/2e7db00c-3a00-4da2-9d64-118c65a4be88)
b) ![image](https://github.com/umap-project/umap/assets/45392236/92cf2f18-f2ec-47dc-a780-538f6d6a909f)
c) ![image](https://github.com/umap-project/umap/assets/45392236/ab9e1c7b-2606-4e28-8a0c-43203831fc20)
d) ![image](https://github.com/umap-project/umap/assets/45392236/2ccb9cd7-a003-43b4-b730-c78f17d08195)
ProcessExplorer :
![image](https://github.com/umap-project/umap/assets/45392236/ad6635fa-0f30-42e9-b728-ed7dd058997d)

**Desktop : Win10 x64 Firefox 113 x64**

❌4) Same but on Firefox (59869 nodes, 2.00mb GPX trace)

Took 16 minutes to process, thread reached 3go in memory heap
After what, Firefox is a little more responsive than Chromium, but it takes always two to five minutes for any action

a) ![image](https://github.com/umap-project/umap/assets/45392236/084ecd33-90c8-4126-9da2-34de827c3743)
b) ![image](https://github.com/umap-project/umap/assets/45392236/b523c7de-ff09-4620-a92d-9c4e013468ae)
c) ![image](https://github.com/umap-project/umap/assets/45392236/dcce98e6-01a4-419d-b5b4-24ebe8adcb29)
d) ![image](https://github.com/umap-project/umap/assets/45392236/8ff2e973-21da-4325-96c4-67dc62964d7d)
ProcessExplorer :
![image](https://github.com/umap-project/umap/assets/45392236/b8bca86f-4a9b-445d-b106-f6ade69884d7)

**Additional context**
You'll find the GPX traces in example here in a zip file :
[bug umap GPX.zip](https://github.com/user-attachments/files/16072290/bug.umap.GPX.zip)

**Comment by davidbgk** [comment]
Trying to display 30k+ nodes on a potentially moving map in a browser is probably a bad idea and even if it works for your configuration it might not be on another user's setup 🤷

**Comment by skyrl69** [comment]
> Trying to display (and edit!) 30k+ nodes on a potentially moving map in a browser is probably a bad idea and even if it works for your configuration it might not be on another user's setup 🤷

You're right but yet, Google Maps is doing it perfectly fine ^^
And I think the examples are classic holidays / road trip itinaries...

Not handling 30k+ nodes is a thing I can understand. Freezing / crashing is another matter

As a workaround, I found the idea to disable interaction for the whole layer. But neverless, one cannot edit those traces, even to change their properties, since editing the trace goes to crash. The only workaround to change aspect of the trace is to set the default settings for the layer encapsulating the trace...

Regards

**Comment by davidbgk** [comment]
There are a lot of tools to simplify tracks, for instance https://opengeo.tech/gpx-simplify-optimizer/

**Comment by yohanboniface** [comment]
A few ideas:
- differentiate editing the geometry and editing the properties
- do not display that much nodes at this zoom level (no sure what kind of algo could be used here), as it's simply useless (even if the browser could handle the points, there is no way to edit a path with that much nodes close one to each other)
- split the line in multilines (if it's not yet the case), and only edit one geometry line at a time
- use canvas for vertex as low zoom levels
- do not show nodes outside of bbox (so one may zoom in and then edit)

**Comment by yohanboniface** [comment]
Should be fixed with latest release: when there are many points in the geometry, only the properties will be editable, and a message will invite the user to zoom in for editing the geometry.
