### ISSUE TITLE
Popups are not displayed at URLs provided by permalink

### ISSUE THREAD

**Issue by rikutaromanabe** [umap-project/umap#1970]
**Describe the bug**
Popups are not displayed at URLs provided by permalinks.
When a URL provided by permalink is opened in a different browser, the popup may or may not be displayed.

**To Reproduce**
1. click on any permalink and copy the URL provided
2. open the copied URL in another browser
3. no pop-up appears

**Expected behavior**
The popup should appear.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Safari, Firefox

**Comment by yohanboniface** [comment]
Can you please share an URL as asked in the issue template ?

**Comment by rikutaromanabe** [comment]
For example,
https://umap.openstreetmap.fr/ja/map/carte-historique-de-lanaudiere-quebec_643883?feature=John%20Rowan#12/45.9823/-73.7543
https://umap.openstreetmap.fr/ja/map/cartographie-des-moulins-du-quercy_1017444?feature=moulin%20de%20Saint-G%C3%A9raud#12/44.2553 /1.3548
Often works well when carried out in a browser that has acquired permalink.

**Comment by yohanboniface** [comment]
I cannot reproduce, I see the popup when I:

- click on your link above
- copy the link on another tab
- copy the link in another browser

Maybe it's on a specific browser / version ? Or can you try to be more specific on process you use to reproduce the bug ?

I'm curious if anyone else can reproduce, so we may find the common denominator (cc @davidbgk if you can try on your side)

**Comment by rikutaromanabe** [comment]
Thanks for the verification.
The permalinks on this site rarely pop up in my environment.
Please try it.
https://umap.openstreetmap.fr/ja/map/map_672698?feature=20025#16/35.7034/139.8189
https://umap.openstreetmap.fr/ja/map/map_672698?feature=3036#17/35.7054/139.8080

**Comment by davidbgk** [comment]
I confirm that it works for me too.

**Comment by rikutaromanabe** [comment]
Thanks.
Does the permalink on map_672698 work ?

**Comment by rikutaromanabe** [comment]
In my environment, the position and zoom are displayed correctly but do not pop up.
Is this an environment-dependent problem?
OMG

**Comment by davidbgk** [comment]
This is probably a race condition given the amount of data, we're investigating ATM.

**Comment by yohanboniface** [comment]
There is certainly a race condition somewhere, but as stated by David, the amount of data/layers does not help.

Do you need that much layers shown at load ? You may display only some of those and users display the other when they need ?

**Comment by rikutaromanabe** [comment]
I see.
So the large amount of data has increased the burden on the umap server.
The concept of this map is to enjoy the city entertainment by combining mass layers and mass data, but if there is a system burden, then we should reconsidered the method.

**Comment by davidbgk** [comment]
<img width="285" alt="Capture d’écran, le 2024-07-05 à 13 26 04" src="https://github.com/umap-project/umap/assets/3556/1e9be3fd-f388-4997-a6c9-858af05164e7">

This is definitely a lot for each and every users' browser to handle.

**Comment by rikutaromanabe** [comment]
I should consider ways to thin out the display according to scale.

**Comment by rikutaromanabe** [comment]
I have found that this is not a bug.
We are very grateful for your consideration.
I am glad we had a useful discussion.
