### ISSUE TITLE
Impossible to use superuser at /admin

### ISSUE THREAD

**Issue by jerem001** [umap-project/umap#1990]
I install Umap with Docker image and i try to access /admin after use commande umap createsuper but when I test I can't access...

**Comment by yohanboniface** [comment]
Can you give more details ? Are you logged in when you try to access the admin ?

**Comment by jerem001** [comment]
Thanks to answer my question but I worked around the problem by using a user who was able to connect and assigning him the role of superuser...
Thank you so much
I close the ticket

Kind regards

Jerem
