### ISSUE TITLE
styling labels

### ISSUE THREAD

**Issue by drzraf** [umap-project/umap#1996]
**Is your feature request related to a problem? Please describe.**
Some layers' labels are very important. Some other aren't. I'd like to tweak color, font-size, background-color and background-opacity for the labels belonging to one specific layer

**Describe the solution you'd like**
UI ? Or a textarea to input free-form CSS.

**Additional context**
Currently, all labels are leaflet tooltips, as a flat list of `<div>` with no information about the layer they belong to. Having a `data-layer` attribute would be nice for per-layer label styling.

**Comment by yohanboniface** [comment]
Closing in favor of #1884
