### ISSUE TITLE
Import Helper: Overpass help below import helper window

### ISSUE THREAD

**Issue by gislars** [umap-project/umap#1997]
**Describe the bug**
The import Helper has a help function which can be opened by clicking on the question mark in the import helper dialog. The help window is below the import helper dialog and can't be seen. When you close the import helper dialog, you can see the help dialog.

**To Reproduce**
1. visit https://umap.openstreetmap.fr
2. create a new map
3. open the data import
4. choose the overpass importer
5. click on the question mark

**Expected behavior**
the help should be visible to the user and not hidden.

**Screenshots**
let me know if you need screenshots

**Comment by davidbgk** [comment]
I confirm, thanks for reporting the issue! (rel. #1942)
