### ISSUE TITLE
add hosting/contact about this instance in the about tag

### ISSUE THREAD

**Issue by Marc-marc-marc** [umap-project/umap#2004]
**Is your feature request related to a problem?**
when a user lost it's edit link, he doesn't know who to send his request to.

**Describe the solution you'd like**
add a setting to allow an instance owner to add a name and a email for contact about this instance
the tab "about" may also have a sentence to redirect generic requesto to the help tab

**Comment by yohanboniface** [comment]
cc @Aurelie-Jallut can we take this opportunity to rework the "about" page, adding instance contact information ? I'm talking about this page https://umap.openstreetmap.fr/fr/about/ (which is close to useless at this stage)

**Comment by Aurelie-Jallut** [comment]
![image](https://github.com/user-attachments/assets/24aecea5-9ca9-4aa7-9e74-6239bf7f6854)

**Comment by yohanboniface** [comment]
Here is a proposal that "simply" adds contact info in the footer: #2080

**Comment by yohanboniface** [comment]
Host infos are now in the footer. Does that work for you @Marc-marc-marc ? :)
