### ISSUE TITLE
Icon sets for marker icons

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#201]
Originally reported by: **Michael Glanznig (BitBucket: [nebulon42](http://bitbucket.org/nebulon42), GitHub: [nebulon42](http://github.com/nebulon42))**

---

I have seen a selection of Maki icons available for marker icons on umap.openstreetmap.fr. Since I have not found those in the code I wondered if they are part of uMap or instance specific?

If they are part of uMap maybe you would be interested to include other icon sets as well?
For example Osmic (https://github.com/nebulon42/osmic), which is largely used by the OSM standard tile layer.

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/201

**Comment by yohanboniface** [comment]
> Since I have not found those in the code I wondered if they are part of uMap or instance specific?

@nebulon42 those are instance specific. One can for example run a uMap dedicated to humanitarian context and have icons specific to this fields.

> For example Osmic

We need a script to have all icons on the format expected (PNG, size, grey or white colour with transparency, tiny border…), not to do that by hand.

**Comment by nebulon42** [comment]
For Osmic a script does already exist (for further explanations see https://github.com/gmgeo/osmic/blob/master/tools/export.md). Or see for example how overpass-turbo handles it: https://github.com/tyrasd/overpass-turbo/commit/2140c6670ccd9562bff3cd5e4ec7966400ba0b48.

We would need to work out the concrete parameters how the icons should look like and the rest could be done automatically.

**Comment by yohanboniface** [comment]
Very nice!

One question: is there a way to generate two versions of the same icon? In uMap we have one grey (for light backgrounds) and one white (for dark background).

**Comment by yohanboniface** [comment]
Another question for you @nebulon42: I see that I can add a padding around the icon, but then the final width depends on the icon shape width. What if I want all icons to be of a given width? (For now, to be aligned, I need them to have a fixed width.)

**Comment by yohanboniface** [comment]
> What if I want all icons to be of a given width? 

Ah, now I see, the ones that are in 20px are also in 24px (with padding: 4), just need to filter them out later.

**Comment by nebulon42** [comment]
> is there a way to generate two versions of the same icon?

You would need to run the export twice with two separate configuration files. You could export without subdirectories, but set two different destination directories like light and dark or something like that.

> I see that I can add a padding around the icon, but then the final width depends on the icon shape width. What if I want all icons to be of a given width?

I think you are referring to the different size versions that exist for some icons, because otherwise all icons would have the same width. As you said you could filter them out later on. I have implemented a `size_filter` option for font and sprite generation. This could be adapted to all output methods, I didn't think it would be useful for SVG or PNG export. I have added an issue for that: https://github.com/gmgeo/osmic/issues/47.

**Comment by yohanboniface** [comment]
Thanks :)
No hurry though, it's easy for me to filter the sizes I don't want.

One more remark: I think we need a way to pass the `input` value from command line. Use case is: I want to keep my `osmic.yaml` config file in the uMap directory, and keep the output path relative to uMap root (because the script may run from other computers); and I don't want to have `input` absolute in the config file for same reason.

Naive approach:

```python
diff --git a/tools/export.py b/tools/export.py
index 9315915..ffd5f1c 100755
--- a/tools/export.py
+++ b/tools/export.py
@@ -9,6 +9,7 @@ def main():
        parser = argparse.ArgumentParser(description='Exports Osmic (OSM Icons).')
        parser.add_argument('configfile', metavar='config-file', help='the configuration file for the export')
        parser.add_argument('--basedir', dest='basedir', metavar='base-directory', help='specify the working directory of the script', required=False, default=None)
+       parser.add_argument('--input', dest='input', help='specify the input root', required=False, default=None)
        args = parser.parse_args()
 
        try:
@@ -25,6 +26,9 @@ def main():
        if args.basedir:
                config['basedir'] = args.basedir
 
+       if args.input:
+               config['input'] = args.input
+
        # set basedir (elvaluation from cwd, if not specified always cwd)
        if 'basedir' in config:
                os.chdir(os.path.dirname(config['basedir']))
```

Side note: you should pep8 your python ;)

**Comment by nebulon42** [comment]
I see the use case. So you want to have the input completely independent from the working directory, which can only be set at runtime. I did not think about that so far, but it is easy to add some additional parameter. Issue is here: https://github.com/gmgeo/osmic/issues/48

**Comment by yohanboniface** [comment]
Thanks!

One more question :)
I see how to define the padding of the icon, but not the shape size itself.
See the difference between this two icons (from my own command line, years ago; and from the script run just now):

![](https://umap.openstreetmap.fr/uploads/pictogram/airport-24.png)  ![airport-24](https://cloud.githubusercontent.com/assets/146023/10416723/e3150a2a-7021-11e5-9f2a-d82765c31c3a.png)

Both files images are 24px large, but you can see that the shape of the first is bigger than the one of the second. Is there any way to say something like "shape must scale until 20px" + 2px padding?

**Comment by nebulon42** [comment]
As far as the PNG export is concerned you can modify the `dpi` setting, which defaults to 90. Setting it to 120 would produce the size you want I think. But since not all icons are exactly the same width and height and the padding is always calculated from the bounding box, there might still be differences in icon size. It would work for the plane as it uses the full height and width, but e.g. the bus stop icon would be 2px less wide, so effectively there would be 4px from the shape to the boundary.

**Comment by nebulon42** [comment]
Just for reference, I have now implemented the things mentioned above (filters for all export methods, support of input location as parameter) and also a more fine-grained control over what will be exported. In fact you can now specify exactly which icons should be included or being excluded from the export.

**Comment by KaiRo-at** [comment]
I guess this is related to #648 ;-)
I definitely would like the car and attraction icons for my own maps, as a car rental place and "something interesting to see" are things I often have in my vacation planning, for which I like using uMap.
