### ISSUE TITLE
Export `map` and `L` to the global scope to allow live plugin addition

### ISSUE THREAD

**Issue by drzraf** [umap-project/umap#2016]
**Is your feature request related to a problem? Please describe.**

I can't really touch my map. I wanted to export high-definition of an area. It couldn't be more cumbersome:
- zoom at the requested level of detail
- resize to window to 4000 x 4000 px
- hope all the tiles were loaded / try to center correctly
- attempt to use a screenshot / FF screenshot tool
- realize it either doesn't work or that that leaflet render blurred tiles when screen-size exceeds 4k

**Describe the solution you'd like**

Let me use the console, `L` and `map` so I can load `screenshoter` , `BigImage`, `Print` plugins and anything that could likely help me workaround this issue (and most others which may come up later)

**Describe alternatives you've considered**

Main code is encapsulated inside a module, there is no clear way to hook / load custom plugins.

Regarding HQ-screenshot, I may have to turn to manual assembly: an absurd waste of time when it comes to just print a map.

See also : https://github.com/umap-project/umap/issues/88#issuecomment-917593767

**Comment by davidbgk** [comment]
`U` and `U.MAP` are probably what you are looking for 🤗

**Comment by drzraf** [comment]
Oh, great hint, thank you!

What about `L` (which contains `control`, for https://github.com/pasichnykvasyl/Leaflet.BigImage)?

**Comment by davidbgk** [comment]
`L` is already exposed too.
