### ISSUE TITLE
[Bug] Popup badly set in slideshow

### ISSUE THREAD

**Issue by C-Sophie** [umap-project/umap#2018]
Popups protrude from card frame when slideshow scrolls

![Image](https://github.com/user-attachments/assets/22d81274-7ba2-4002-8aeb-70cf4604e769)

The background map should move sufficiently to align the popups with the other three blocks (two toolbars and legend).

Example : https://umap.openstreetmap.fr/fr/map/calais-interactif-la-memoire-de-calais-cartographi_865765#14/50.9527/1.8408 (same pb uMap OSM (https://umap.openstreetmap.fr/pl/map/calais-interactif-la-memoire-de-calais-cartographi_865765#13/50.9565/1.8508

![Image](https://github.com/user-attachments/assets/318ec730-6034-436e-9eed-5cfcd4e07bb5)

**Comment by C-Sophie** [comment]
Not only slideshow : 

![Image](https://github.com/user-attachments/assets/205f0326-eeff-49f0-a25f-cb6c8835647e)
https://umap.openstreetmap.fr/nl/map/les-subventions-europeennes-dans-lherault-2021-202_942160#10/43.5326/3.4854
Unable to move the background map and thus display the top of the popup

**Comment by yohanboniface** [comment]
This is because the map has fixed bounds.

![image](https://github.com/user-attachments/assets/200d7227-ab1e-4b18-abc1-6719937e92fa)

I think in this situation, with long popup content, the only option is to use panels instead of popups.
