### ISSUE TITLE
What's the order of a remote layer CSV

### ISSUE THREAD

**Issue by aborruso** [umap-project/umap#202]
Hi,
I have made this map http://umap.openstreetmap.fr/it/map/instatrapani_49274 using this CSV source:
http://spreadsheets.google.com/tq?tqx=out:csv&tq=select%20A%2CB%2CC%2CD%2CE%2CF%2CG%2CH%2CI%2CJ%2CK%2CL%2CM%20where%20H%20%3E%200%20order%20by%20M%20desc&key=1bjswEWHJmWRx0ENlsb3o0hDhRdI89uJkYbx8qImhcCk&gid=1153026712

If you look at the same source as [HTML](http://spreadsheets.google.com/tq?tqx=out:html&tq=select%20A%2CB%2CC%2CD%2CE%2CF%2CG%2CH%2CI%2CJ%2CK%2CL%2CM%20where%20H%20%3E%200%20order%20by%20M%20desc&key=1bjswEWHJmWRx0ENlsb3o0hDhRdI89uJkYbx8qImhcCk&gid=1153026712) these are first and second record:
![image](https://cloud.githubusercontent.com/assets/30607/9151464/85490f9a-3e03-11e5-907e-e39ac2e98014.png)

But if you stard the slide on the map, the first record is the same, but not the second. It seems tha umap does not use the original records sort of the CSV source. What's the column that umap use for slide sorting?

Thank you

**Comment by yohanboniface** [comment]
For now, it's alphabetical only on the name :(
Because it's the simplest way for the user to take control over the order (out of using a csv where you can).
One option for you is to have a "name" column with "1. xxx", "2. xxxx". I know it's not ideal.
This is something I want to make better.

**Comment by aborruso** [comment]
Hi @yohanboniface thank you.

Than if I create a new columnn "name" with a simple progressive counter, the order will be "1,10,100,101, 102, ecc." and not "1,2,3,4,5, ecc.". Is it right?

**Comment by yohanboniface** [comment]
humm, I'm not sure I understand :/
You want to use "1, 10, 100" instead of "1, 2, 3" ?
Given that it's alphabetical, it's possible that "100" will come before "2". :/ Maybe you'll need to use "1.0.0, 1.0.1", but that's a bit ugly :(

**Comment by yohanboniface** [comment]
Ah, I remember now that you can use another column if you prefer:

![screenshot from 2015-08-09 09 56 02](https://cloud.githubusercontent.com/assets/146023/9154006/e9a4552a-3e7c-11e5-8cdb-ff11e0bfcb4c.png)

**Comment by aborruso** [comment]
Thank you, I have solved.

I had a name column with:
1
2
...
10
11

And the sorting was
1
10
11
...

I have used function TEXT in my spreadsheet `TEXT(mycell;"00000")` and now my name column is
00001
00002
00003
...
00010
00011

And now the sorting works.

And also your last email about umap setting is a solution. Thank you

**Comment by aborruso** [comment]
Hi @yohanboniface,
there is something strange.

This is my [source](http://spreadsheets.google.com/tq?tqx=out:csv&tq=select%20A%2CB%2CC%2CD%2CE%2CH%2CI%2CO&key=1bjswEWHJmWRx0ENlsb3o0hDhRdI89uJkYbx8qImhcCk&gid=1798959119) in CSV.
If you look at it in [html](http://spreadsheets.google.com/tq?tqx=out:html&tq=select%20A%2CB%2CC%2CD%2CE%2CH%2CI%2CO&key=1bjswEWHJmWRx0ENlsb3o0hDhRdI89uJkYbx8qImhcCk&gid=1798959119) you can see that I have a name column (the last one).
But the slider of my [map](http://umap.openstreetmap.fr/it/map/instatrapani_49274) does not start from the first record of my source. What's wrong in my source?

Thank you

**Comment by yohanboniface** [comment]
Scusa Andrea, ero offline faciando vela.

Looking at the source file, it seems to me that the first rows are the ones without value in the name column, do you confirm?

**Comment by aborruso** [comment]
Scusa @yohanboniface , it works, it was an error of mine.

Thank you very much

**Comment by yohanboniface** [comment]
:)
