### ISSUE TITLE
Add an export button in the admin panel

### ISSUE THREAD

**Issue by virgile-dev** [umap-project/umap#2020]
**Is your feature request related to a problem? Please describe.**
Currently it's tedious for non technical admins to export the list of users / list of maps. 
Same for maps.

**Describe the solution you'd like**
It'd be great to have an export button that downloads a csv when clicked.
In order to avoid downloading the full db, being able to aply filters and export the selection would be interesting to have but not mandatory.

**Describe alternatives you've considered**
I've been copy pasting a paginated list into a table but I'm missing info.
Having a queryable api would be an interesting approach as it would open the data to non admins. 

**Additional context**
I've been doing this for a small instance.

**Comment by yohanboniface** [comment]
https://makina-corpus.com/django/comment-facilement-exporter-csv-depuis-admin-django
