### ISSUE TITLE
New Jawg Maps styles available for uMap

### ISSUE THREAD

**Issue by Joxit** [umap-project/umap#2022]
Hi there,

We ([Jawg Maps](https://jawg.io/)) are providing free tiles to the umap's project [since 2016](https://blog.jawg.io/les-cartes-de-jawg-sur-umap/).

We created some new map styles since then and they can be added in uMap. 
The missing styles are [`jawg-lagoon`](https://www.jawg.io/docs/apidocs/maps/dynamic-maps/#jawg-lagoon) and [`jawg-terrain`](https://www.jawg.io/docs/apidocs/maps/dynamic-maps/#jawg-lagoon).

You can add them whenever you want.

FYI, we also rename old layers:
From ` ` or `street` to `jawg-street`, `sunny` to `jawg-sunny`, `light` to `jawg-light` and `dark` to `jawg-dark`.

**Comment by yohanboniface** [comment]
Thanks @Joxit ! For your information, the tilelayers available are not defined in the uMap code, but it's a per instance configuration.

You certainly have in mind the OSM instance, which already have a lot of tilelayers available (but if we have 39 we could have 41…), not sure what's the policy (hint: there isn't :p). 


Ping @cquest @Jocelynj thoughts ? :)

**Comment by jocelynj** [comment]
It seems a good idea to add these tilelayers to umap.openstreetmap.fr, thanks!

@yohanboniface: can you add them yourself?

**Comment by yohanboniface** [comment]
Done!
