### ISSUE TITLE
Misalignment of map icons with right-to-left user interface of umap

### ISSUE THREAD

**Issue by iriman** [umap-project/umap#2038]
**Describe the bug**
In RTL environment map icons and tooltips are out of correct position. I found 3 issues with this map:

![image](https://github.com/user-attachments/assets/f4d1f76a-b7b0-4da5-a184-d6f11819d456)

**To Reproduce**
1. Go to 'https://umap.openstreetmap.fr/fa-ir/map/map_943303#8/33.891/51.117' 

**Desktop:**
 - OS: Windows 11
 - Browser Firefox
 - Version 128

**Comment by fim100** [comment]
Label placement also has problem in RTL mode that I couldn't fix:

![image](https://github.com/user-attachments/assets/f3371343-0f07-4d85-967c-34e759e48d79)

https://umap.openstreetmap.fr/fa-ir/map/test-map_1100282
https://umap.openstreetmap.fr/en/map/test-map_1100282

**Comment by fim100** [comment]
issues here:
- [x] misalignment in cluster icon 
- [x] misalignment in parts of icon shapes: default, drop and ball icons 
- [ ] 'edit tooltip' out of the position 
- [ ] label out of the position

**Comment by fim100** [comment]
All should be solved by #2046

**Comment by yohanboniface** [comment]
This is now deployed in umap.openstreetmap.fr, should all be good. Thanks a lot @iriman for spotting the issues, and @fim100 for actually fixing them! :+1:
