### ISSUE TITLE
Legend rendering

### ISSUE THREAD

**Issue by thibdrev** [umap-project/umap#204]
Hi Yohan,

Is it normal that the legend initially shows the colours of only the layers for which the option "displayed at loading" was activated?

Because once we click on "show/hide" these very layers, then their respective colour appears in the legend, which is a bit weird.

The map where you can probably reproduce is located here : http://umap.openstreetmap.fr/fr/map/vive-la-france-2015_51034

Hope this will help. In my opinion, the legend should show the colours of all the layers, displayed by default at startup or not.

Best regards,
Thibault

**Comment by yohanboniface** [comment]
Yes, it's "normal", because, until the layer is loaded we don't know its default colour ;)

**Comment by thibdrev** [comment]
Hum hum... I understand the reason why now. Still, strange behaviour :)

However, beautiful app, many thanks for it !
