### ISSUE TITLE
[Question] Stylesheets of umap project

### ISSUE THREAD

**Issue by fim100** [umap-project/umap#2040]
I looked into live stylesheets of umap website to work around some rtl issues (like #2038).

I wonder is it correct way to directly modify stylesheets from "[umap/static/umap/css"](https://github.com/umap-project/umap/tree/5a0b75fd3322cf18b41e3c70fb743a3c6a1e4747/umap/static/umap/css) or "[umap/static/umap](https://github.com/umap-project/umap/tree/5a0b75fd3322cf18b41e3c70fb743a3c6a1e4747/umap/static/umap)" and send PR or are they come from some external projects that we should fix issues there?

**Comment by davidbgk** [comment]
@fim100 this is the right place to initiate your PR, thank you!
