### ISSUE TITLE
https/http 

### ISSUE THREAD

**Issue by skillz-xx** [umap-project/umap#205]
hello

Thanks for your great service! We love to use openstreetmal and your project helps a lot!

I have a question though: My site is standard https in the browser and if I embed the code:

<iframe width="100%" height="300px" frameBorder="0" src="https://umap.openstreetmap.fr/en/map/sexy-vegan_49979?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&datalayersControl=true&onLoadPanel=undefined&captionBar=false"></iframe><p><a href="https://umap.openstreetmap.fr/en/map/sexy-vegan_49979">See full screen</a></p>

The map tiles seem still to be loaded from a "http" only server. It would be great if everything could go through https, so I dont get an error of "insecure elements loaded" on my site..

would be greatly appreciated if that could work!

many thanks
dan

**Comment by yohanboniface** [comment]
Problem here is that no everything relies on umap instance maintainers: tiles, icons, and also user images, can come from any source which may or may not support https.

If you want to use https only, you can still add a custom tile source with https and then have your embed call uMap through https.

But (and I know that's sad), for the reasons given above, I don't think we can force https only uMap at this time. :(

**Comment by skillz-xx** [comment]
do you know any tilesource that supports https=?

**Comment by yohanboniface** [comment]
I think osm.org does, and Thunderforest ones too, and Mapbox ones. Certainly others :)

**Comment by skillz-xx** [comment]
do you have a link and can you tell me how i configure it in my umap?

many thanks for your help!!!

**Comment by yohanboniface** [comment]
http://www.thunderforest.com/ gives some.

For example: https://{s}.tile.thunderforest.com/cycle/{z}/{x}/{y}.png should work.

Then in your map goes to the map settings (the gear), then custom background, then add at least the url and attribution, and save, and that should be ok.

**Comment by skillz-xx** [comment]
hm, dont see any map now
https://umap.openstreetmap.fr/en/map/sexy-vegan_49979#16/47.0668/15.4379

what did i do wrong?

**Comment by yohanboniface** [comment]
I don't know because I see the map ;)

**Comment by skillz-xx** [comment]
me too now, sorry, I didnt realize my Request Policy in firefox was preventing cross site requests :)

chees and thx, will get it to work then!
dan
