### ISSUE TITLE
Problem importing geojson file (and any other type)

### ISSUE THREAD

**Issue by Cristian-wp** [umap-project/umap#2050]
Hello, I have load a dxf file in QGIS, then I exported it as geojson.
I can import the file in my umap project, but after a reload I get all the line ruined by simplify. I have already disable it, but I always get the same result.
How can I solve this problem?

Afrer import:
<img width="466" alt="image" src="https://github.com/user-attachments/assets/2146ee35-50a7-466c-885f-ccbdaff32535">

After reload:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/6600de04-976f-4a05-b6e0-b9b43f216714">

**Comment by davidbgk** [comment]
The issue template is here for a good reason, we need a map or at least the uploaded file to be able to reproduce 🤷
