### ISSUE TITLE
Draw Line following Road or Railway

### ISSUE THREAD

**Issue by jmaris** [umap-project/umap#2052]
**Is your feature request related to a problem? Please describe.**
It can be difficult to draw lines along roadways, especially ones that curve. 

**Describe the solution you'd like**
It would be amazing if there was a setting for the line tool that would make it snap to and follow existing roadways, so you can quickly and accurately draw lines that follow roads

**Describe alternatives you've considered**
Drawing these roads in by hand

**Comment by yohanboniface** [comment]
Thanks for the suggestion. Though there is already an issue to track this need: #297 

Agreed that this would be very useful, but it's not easy. This would basically means:
- a router server able to serve the requests coming from uMap (can be quite a lot)
- a bit of work on the frontend level to implement a new drawing tool

(Closing in favor of #297)

**Comment by yohanboniface** [comment]
As a workaround, one can compute the route in a service like [this](https://maps.openrouteservice.org/), and then export to geojson/gpx and import in uMap.
