### ISSUE TITLE
recovery of my own map

### ISSUE THREAD

**Issue by amirnada1** [umap-project/umap#206]
i have created map on umap and suddenly i couldn't find the data created, how can i recover the map or restore it for previous date

**Comment by yohanboniface** [comment]
> how can i recover the map or restore it for previous date

That's not possible on this version sadly, but will be in the [next one](https://github.com/umap-project/Leaflet.Storage/commit/9a301831bd1ae9203e9ecbde4693a6167c8a9410).

> suddenly i couldn't find the data created

Data doesn't disappear as if by magic; so generally it's either a user mistake, or a cache problem. Have you tried from another browser/computer/Internet access (it may be linked to some zealous proxy)?
