### ISSUE TITLE
Modifications non enregistrées

### ISSUE THREAD

**Issue by Bescu** [umap-project/umap#207]
Bonjour,

Je ne comprends pas pourquoi les marqueurs créés ou supprimés sur cette carte uMap avec une permission d'édition accordée à tout le monde ne s'enregistre pas : 

http://umap.openstreetmap.fr/fr/map/stationnements-gig-gic_51627#16/50.3661/3.5432.

J'ai également posté un message sur le forum OSM consacré à uMap : http://forum.openstreetmap.fr/viewtopic.php?f=19&t=2225

**Comment by yohanboniface** [comment]
Works for me.
Tu es derrière un proxy?

**Comment by Bescu** [comment]
Au boulot oui, mais j'avais le même problème de chez moi sans proxy. Je ne comprends pas bien ce qui pourrait provoquer ce soucis du coup

**Comment by Bescu** [comment]
Pour info voici une capture vidéo du problème : https://youtu.be/tyUHIZRGYi8
J'ai le même problème que je sois au boulot (IE 11 derrière un proxy) ou chez moi (Firefox à jour, sans proxy)

**Comment by yohanboniface** [comment]
Oui, ça ressemble à un problème de cache:

![screenshot from 2015-09-08 10 40 30](https://cloud.githubusercontent.com/assets/146023/9730328/13b62784-5616-11e5-8c95-1ef060c9666e.png)

En chargeant depuis un autre navigateur, ça dit quoi?

**Comment by Bescu** [comment]
Merci Yohan! Effectivement ça ressemble à ça, depuis mon téléphone j'ai bien les marqueurs ajoutés! Y-a-t-il une solution pour que les enregistrements apparaissent tout de suite ou rapidement dans le navigateur d'origine?

**Comment by yohanboniface** [comment]
Je sais pas, un réglage quelque part qui fout le ouaille je dirais. Ça marche pour 99,9% de gens (ou bien personne ne s'est plaint, et ça marche chez moi).
T'as pas un plugin qui pourrait faire du zèle?
Sinon essaie de regarder dans les outils développeurs, et dis-moi les headers reçus sur les URLs en /datalayer/xxx.

**Comment by Bescu** [comment]
Merci pour tes éléments de réponses!
Quand je rafraichi la page il trouve bien les marqueurs ajoutés ou supprimés mais pas que je quitte la page et que j'y retourne.
Quand je quitte la page et que j'y retourne, dans les outils développeurs il n'y a aucun URLs en /datalayer/xxx par contre que je rafraichis je les retrouve : 
http://i.imgur.com/IE63ufI.jpg

**Comment by yohanboniface** [comment]
Je veux bien les en-têtes de réponse aussi :)

**Comment by Bescu** [comment]
Voilà ;)

http://i.imgur.com/eAVgkKj.jpg

**Comment by yohanboniface** [comment]
Tu as un squid qui tourne en local et qui met le bins, apparemment.

**Comment by Bescu** [comment]
Ok merci pour toutes ces infos, je regarderai ce soir de chez moi qu'est-ce qui peut clocher parce qu'il n'y a pas de squid ;-)

**Comment by yohanboniface** [comment]
> il n'y a pas de squid

Si, si :)
Peut-être qu'il est au boulot, qu'il change les headers agressivement, si bien que quand tu rentres chez toi ton navigateur a encore les pages avec des mauvais headers en cache.

**Comment by Bescu** [comment]
Aham, ça expliquerait donc pourquoi ça fait cela aussi de chez moi!
