### ISSUE TITLE
Login page broken

### ISSUE THREAD

**Issue by stevage** [umap-project/umap#209]
In Firefox (which I don't normally use), I just received the following page when clicking the `login` button:

```
{"html": "\n\n
Please choose a provider
\n\n
\n

    \n \n
    \n \n
    \n \n
    \n \n
    \n \n
    \n \n
    \n \n
    \n \n
    \n \n 

\n
\n"}
```

I gather that that's the actual contents of `http://umap.openstreetmap.fr/en/login/`, so something failed to intercept that click and make it ajaxy I guess.

**Comment by yohanboniface** [comment]
Are you on a slow internet connection?

**Comment by stevage** [comment]
Not exactly - but anyway I'll keep an eye out to see if it recurs. It hasn't so far.
