### ISSUE TITLE
Map permissions page super slow to load

### ISSUE THREAD

**Issue by stevage** [umap-project/umap#210]
For me (Chrome OSX Mavericks), clicking on the key symbol (Map permissions) consistently takes 26 seconds to load the permissions page. During that time, the browser page is non-responsive.

Most of the time seems to be taken up by a "parse HTML" within an XHR Ready State Change.

![screenshot 2015-09-11 10 46 16](https://cloud.githubusercontent.com/assets/678344/9804549/62a09754-5872-11e5-8178-174afe6f5409.png)

**Comment by yohanboniface** [comment]
Quite extreme! It may be that the editor list is becoming too big.
Can you try to load the URL on a separate window (i.e. out of javascript time) and see how much it takes?
BTW, I'm curious why you have jquery around.

**Comment by stevage** [comment]
Sorry, what do you mean "out of javascript time"? Happy to do further experiments, I'm just not clear what you're asking?

I imagine the jquery is related to an extension. I run quite a few extensions. Disabling them all, the page loads within about 5 seconds - maybe I can find out which one is interacting to make it so slow.

**Comment by yohanboniface** [comment]
I meant loading this URL in a separate window: https://umap.openstreetmap.fr/en/map/1/update/permissions/

Try changing 1 by the id of a map you have full control of. And check how long it takes.

For what I see, the hard coded list of users is becoming too big. But that explains something like 1 or 2 seconds to load, but not 5, and not 26 either.

**Comment by stevage** [comment]
Took around 1 second before [that page](https://umap.openstreetmap.fr/en/map/55998/update/permissions/) started building, and maybe 3 seconds to complete.

Whereas the "Map permissions" page still took 17 seconds to load. (I recently got rid of a few extensions and switched from AdBlock to UBlock, maybe explains the decrease compared to before...)

**Comment by amenk** [comment]
Did you try disabling all extensions for testing?

**Comment by sabas** [comment]
There are more than 22.000 possible editors, all loaded into the select #id_editors 
Couldn't that be loaded via ajax only when the user starts typing? See https://github.com/select2/select2
Otherwise it's impossible to change permissions

**Comment by yohanboniface** [comment]
> Couldn't that be loaded via ajax only when the user starts typing?

Yes, someone needs to do that ;)

I've an unfinished branch somewhere with https://github.com/novafloss/django-agnocomplete I'll try to push it

**Comment by yohanboniface** [comment]
Finally done and merged in 1.0.0-rc.1 out today.
