### ISSUE TITLE
Minimap and credits above pannels

### ISSUE THREAD

**Issue by el-srabo** [umap-project/umap#2103]
**Describe the bug**
Since very recently on the Framacarte instance the minimap and credits appear above the panels (e.g. settings or captions), which make the interface difficult to use!
Also there use to be a linebreak in my credits which is now ignored.

(This is potentially the same issue as the one described [here](https://github.com/umap-project/umap/issues/2070))

**To Reproduce**
1. Go to "https://framacarte.org/m/148987/"
2. Click on a feature to open a caption.
3. See minimap and credits appear above the panel.

**Expected behavior**
The minimap and credits should stay below the panels, otherwise they hide text and features.

**Screenshots**

![Screenshot_20240904-144111_Firefox](https://github.com/user-attachments/assets/e41172c6-d0ab-4a4c-b4ea-474d500ee433)

**Smartphone**
- Device: Fairphone 2
- OS: LineageOS 18.1 (Android 11)
- Browser: Firefox
- Version: 123.0

**Comment by Tkyzxim** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
