### ISSUE TITLE
I have a project I can't edit

### ISSUE THREAD

**Issue by stevage** [umap-project/umap#211]
I invited a friend to uMap and ended up in a weird situation: [a map](http://umap.openstreetmap.fr/en/map/aawt-bike2_52441) was listed in "Stevage's maps", but I couldn't edit it. Apparently he:
- added me as an editor
- but didn't change the "edit status"

From a UX point of view, I think either:
- maps that I'm invited to view but not edit should be listed as "[username]'s maps". (Could be "maps shared with you"); or
- the status of being added as an editor to a public map, but not given edit permissions, should not exist.

**Comment by yohanboniface** [comment]
Good point.

> maps that I'm invited to view but not edit should be listed as "[username]'s maps". (Could be 
> "maps shared with you"); or

Yes. Or maybe just not appearing at all, given that they are not shared with you until the status is changed too.

>  the status of being added as an editor to a public map, but not given edit permissions, should not 
> exist.

Well, I'm not sure about this one: one may want to keep the list of editors while changing the status, or setting the list while not yet changing the status; that may be a wrong scenario (I mean one that in reality never appear) though, but that was the rationale behind the way it works now: separate those two infos that are different, i.e. "who" in one hand, "how" in another.

At this time I'm in favour of removing from your maps the ones you are in the list of editors but are not really shared with you.

**Comment by stevage** [comment]
>At this time I'm in favour of removing from your maps the ones you are in the list of editors but are not really shared with you.

Yeah, that probably makes more sense actually.

**Comment by grandbic** [comment]
Bonjour,
Only half agree with 'stevage'
'My maps' gives owned, or editable, or shared as editor but not editable; when I read 'owned by me'
I suggest : 'Maps'
and when in editable mode (not owner) to put into 'permissions', a grayed section with the owner named; for this is where I got muddled.
.............for stevage:   maps that I'm invited to view but not edit should be listed as "[username]'s maps". 
maps are named as[name of map][owner's name]
P.S.I'd like a longer 'my maps' page, so not having to tap 'more' to scroll.

**Comment by yohanboniface** [comment]
@grandbic can you elaborate a bit your point, I'm not sure to follow

**Comment by Binnette** [comment]
Hi, does this problem still exist? This issue is very old, please make a new test and reopen this bug is the issue still exist. Thanks a lot, have a nice day.
