### ISSUE TITLE
Edit header in small screens

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#2113]
![image](https://github.com/user-attachments/assets/2570821d-a52c-4ac2-a60b-f547963f5c54)

@Aurelie-Jallut what do you think about using an icon for the dashboard in this case (I'd suggest something like a profile icon https://thenounproject.com/icon/profile-4334341/) ? And maybe cutting the title shorter ? And what about the visibility text ? :)

**Comment by Aurelie-Jallut** [comment]
It's a bit strange to put a link to the profile in the middle of the page, as we usually look for it on the right.
If you just display the first name and surname, you'd expect to come across a profile page or a drop-down menu with various possible actions: View my cards / Create a team / etc. I'll get a word that best represents what you'd expect to find behind it.

I'll go for a word that best represents what you expect to find behind it.

![image](https://github.com/user-attachments/assets/f1c8ad80-2348-4f14-b604-7000d01580c9)

**Comment by Aurelie-Jallut** [comment]
Maybe this will works ?

![image](https://github.com/user-attachments/assets/063e5945-cec0-450f-b02b-ecf186834ca3)

**Comment by yohanboniface** [comment]
> Maybe this will works ?

Sounds perfect to me :)

**Comment by yohanboniface** [comment]
Could it be also the opportunity to have a drop-down menu on click on the icon ? With entries:

- my profile
- my maps
- my teams

wdyt ? :)

**Comment by Aurelie-Jallut** [comment]
yes, a few months ago I designed something like this :
![image](https://github.com/user-attachments/assets/eeb23491-a318-41db-b761-ef8cfecf2659)

**Comment by yohanboniface** [comment]
Something like this ?

Normal screens:

![image](https://github.com/user-attachments/assets/39425b67-25e5-4ab7-99a9-237ab2d1bdd7)

Small screens:

![image](https://github.com/user-attachments/assets/95b5e489-460e-4bd5-bd06-d58c72a303fc)

**Comment by yohanboniface** [comment]
Small screen without the menu:

![image](https://github.com/user-attachments/assets/d5e1c609-00eb-41fe-90aa-49958ff9a71d)

**Comment by Aurelie-Jallut** [comment]
with menu : 
- I would align the menu on the right-hand edge

without menu : 
- can you leave the little vertical bar in front Help on small screen ?

**Comment by Aurelie-Jallut** [comment]
right-hand edge of what the button : 

![image](https://github.com/user-attachments/assets/330329ae-3585-4051-ba0b-9150adf78cd5)

**Comment by yohanboniface** [comment]
> right-hand edge of what the button

Ok! I've had a look, but it quite code expensive. Can we keep it left aligned for now ? :)

**Comment by Aurelie-Jallut** [comment]
hum... of course ;)
