### ISSUE TITLE
Sizing Circles

### ISSUE THREAD

**Issue by XioNoX** [umap-project/umap#2114]
**Is your feature request related to a problem? Please describe.**
A bit similar to conditional formatting, there seems to be no good way to compare features between each others based on one of their properties if they can have a wide range of such property value.
For example I'd like to be able to show all stairs of a given area, but also easily visualize which ones have more steps than others.

**Describe the solution you'd like**
Something like this: https://infonewt.com/circles/
Given a feature's property (eg. OSM's `step_count`) to be able to display a circle (or icon size) that changes size proportionally (or following multiple possible algorithms).

**Describe alternatives you've considered**
So other non-OSS tools support such feature, but nothing in Umap afaik. And I couldn't think of any workaround.

**Additional context**
Thanks!

**Comment by davidbgk** [comment]
It will be part of the next release, you can already try it out here: https://dev.umap-project.org/en/

Refs #1399 and #2053.
