### ISSUE TITLE
"Delete this shape" no longer working

### ISSUE THREAD

**Issue by Player701** [umap-project/umap#2124]
**Describe the bug**
Attempting to delete a shape from a feature containing multiple shapes results in an error.

**To Reproduce**
1. Go to https://umap.openstreetmap.fr/
2. Create a new map
3. Draw a line
4. Right-click on any point along the line, choose "Split line"
5. Left-click on the line, then choose "Delete this shape" (3rd button from the left)
6. Observe error: "TypeError: this.feature.enableEdit is not a function"

**Expected behavior**
The selected part of the line gets deleted.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 11 x64
 - Firefox 130.0 / Chrome 128.0.6613.138

**Smartphone (please complete the following information):**
N/A

**Additional context**
Used to work just a few days ago.

**Comment by yohanboniface** [comment]
Thanks for the report! We'll release a fix soon. In the meantime, you can use right click for same operation.

**Comment by Player701** [comment]
Thanks for the hint - the context menu operation ("Remove shape from the multi") does work indeed. But please also check out #2125.
