### ISSUE TITLE
"Merge lines" no longer working

### ISSUE THREAD

**Issue by Player701** [umap-project/umap#2125]
**Describe the bug**
Attempting to merge two lines results in an error.

**To Reproduce**
1. Go to https://umap.openstreetmap.fr/
2. Create a new map
3. Draw a line
4. Draw another line, starting close to where the line drawn in p.3 ends
5. Drag the line drawn in p.4 so that its starting point overlaps with the ending point of the line drawn in p.3
6. Right-click on the line drawn in p.3, choose "Transfer shape to edited feature"
7. Right-click on the overlapping points, choose "Merge lines"
8. Observe error: "TypeError: this.getLatLngs is not a function"

**Expected behavior**
The lines get merged.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 11 x64
 - Firefox 130.0 / Chrome 128.0.6613.138

**Smartphone (please complete the following information):**
N/A

**Additional context**
Used to work just a few days ago.

**Comment by yohanboniface** [comment]
Thanks again! I'm having a look :)

> Draw another line, starting close to where the line drawn in p.3 ends
> Drag the line drawn in p.4 so that its starting point overlaps with the ending point of the line drawn in p.3
> Right-click on the line drawn in p.3, choose "Transfer shape to edited feature"

For the same result, you could directly draw a multi line using this icon:

![image](https://github.com/user-attachments/assets/e5b35a98-59cc-4327-8016-f61a57f131b4)
