### ISSUE TITLE
Side panel doesn't show up when using the data browser

### ISSUE THREAD

**Issue by valenceromansagglo** [umap-project/umap#2127]
**Describe the bug**
When using the data browser, a side panel doesn't show up when clicking on any data.

**To Reproduce**
1. Go to https://umap.openstreetmap.fr/fr/map/fete-de-la-science-2024_1110035
2. When the data browser displays, click on any label to expand it, then click on any displayed data.
3. Nothing happens.

**Expected behavior**
When clicking on a data, a side panel appears with details about the specific data.
(The details do show up when directly clicking the pin on the map)

**Screenshots**
See attached video
[Fête-de-la-Science-2024---uMap.webm](https://github.com/user-attachments/assets/301df6d7-a956-4efe-a569-cdddb9ed49ee)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave (Brave shields & addons disabled)
 - Version: v1.69.162 (Sep 3, 2024) / Chromium 128.0.6613.120

**Smartphone (please complete the following information):**
N/A

**Comment by yohanboniface** [comment]
Thanks for the report, and sorry for that. I'll have a look today. In the meantime, you can remove the cluster mode to workaround this trouble…
