### ISSUE TITLE
Search fails - invalid mapquest AppKey

### ISSUE THREAD

**Issue by cweiske** [umap-project/umap#213]
Trying to search a location fails. The browser's console shows:

> XMLHttpRequest cannot load
> http://open.mapquestapi.com/nominatim/v1/search.php?format=json&q=london%20…4501953125%2C51.87140380383993%2C2.04345703125%2C50.90996067566234&limit=1.
> No 'Access-Control-Allow-Origin' header is present on the requested resource.
> Origin 'http://umap.openstreetmap.fr' is therefore not allowed access.
> The response had HTTP status code 403.

Fetching the open.mapquestapi.com page itself tells me:

> The AppKey submitted with this request is invalid.

The mapquest docs say now:

> http://open.mapquestapi.com/nominatim/
> All Nominatim and Xapi requests require a key starting September 15, 2015.
> Please visit the MapQuest Developer Network to sign up for an AppKey if you do not have one.

**Comment by yohanboniface** [comment]
Ah http://devblog.mapquest.com/2015/08/17/mapquest-free-open-license-updates-and-changes/

Thanks for the report!

**Comment by yohanboniface** [comment]
Sorry for the delay, I was travelling, and thus offline. I'm pushed an hot fix on prod servers, and will issue a proper fix for the next release (maybe switching to Photon btw…)
