### ISSUE TITLE
Impossible to drop a point on firefox

### ISSUE THREAD

**Issue by MathiasVadot** [umap-project/umap#2135]
**Describe the bug**

On firefox, when i when to make a new point on my layer, impossible to drop this point. But it is possible to draw a line or a surface.

**To Reproduce**
1. Go to firefox
2. Go to umap.openstreetmap.fr
3. Click on Editer
4. Click on Make a new marker
5. Try to drop the marker

**Expected behavior**
When i drop the marker, this one should be on the map.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 130.0 (64 bits)

**Comment by davidbgk** [comment]
@MathiasVadot can you try again? There was a server issue at that moment.

**Comment by MathiasVadot** [comment]
Hello, now it works, I guess it was related to the server problem
