### ISSUE TITLE
Unable to edit an object on Firefox

### ISSUE THREAD

**Issue by MathiasVadot** [umap-project/umap#2136]
**Describe the bug**

On firefox, when i want to edit an objet already on the map, it impossible to click on the pencil for a point, a line or a surface.

**To Reproduce**
1. Go to firefox
2. Go to umap.openstreetmap.fr
3. Click on Editer
4. Click on object like a point, line or surface already on the map 
5. Try click on the pencil to edit the object.

**Expected behavior**
When i click on the object already on the map, i can click to the pencil and then edit the object with a new name, a new form etc...

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 130.0 (64 bits)

**Comment by davidbgk** [comment]
@MathiasVadot can you try again? There was a server issue at that moment.

**Comment by yohanboniface** [comment]
The server was full, sorry for that, fixed!
