### ISSUE TITLE
Cannot clone or save content to maps, get "Oops, Server error…" or "Problem in the response" errors, respectively. 

### ISSUE THREAD

**Issue by rprovilij** [umap-project/umap#2137]
**Describe the bug**
When cloning a map, I get an "Oops, Server error…". In refreshing the My Maps page, I get an empty map with the cloned name. Probably related is that I can no longer save content within maps either as I then get a "Problem in the response" error. 

**To Reproduce**
1. >Go to 'http://u.osmfr.org/m/1058398/' (for example)
2. >Map advanced properties / Settings
3. >Advanced actions
4. >Clone this map

**Expected behavior**
That I can both clone existing maps and save content in new maps. 

**Screenshots**
![Screenshot 2024-09-13 130438](https://github.com/user-attachments/assets/f4dc02c0-5b4a-4023-a3f2-7e08b34d7018)
![Screenshot 2024-09-13 130424](https://github.com/user-attachments/assets/5288f084-682b-4278-a77a-b6d2ab49f8be)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Chrome (same issue on Firefox)

**Comment by lmartorell** [comment]
I have the same problem, but not only clonning. 
I clonned a map and have the same issue. 
Later I tried to create a new map (not clonning from existing one). 
- uMap creates it. 
- I'll change some map properties and uMap save them.
- I added a data layer (without marker in layer, only create layer), When I try to save uMap return the same error is "Problem in the response". 

Its easy to reproduce.

**Comment by ddrap14** [comment]
I'm having the same issue as well with adding any data to a map. I suspect it might be application-wide. Hopefully it's solved quickly, because it renders uMap pretty unusable for now, especially on web

**Comment by ddrap14** [comment]
I suspected it might be a server issue if it was universal. It's working for me right now (although I can't confirm that for the others experiencing the issue)

**Comment by yohanboniface** [comment]
The server was full, sorry for that, fixed!
