### ISSUE TITLE
`Data browser`: allow filtering by description content 

### ISSUE THREAD

**Issue by IgnacioHeredia** [umap-project/umap#2138]
**Is your feature request related to a problem? Please describe.**
I would like to search features by the content of the description.

**Describe the solution you'd like**
Currently, one can only filter by feature title:
![image](https://github.com/user-attachments/assets/9e3c3bd9-6507-44d3-b9cf-e1bba3242685)

I would like to be able to filter features also by description content.
Maybe show those ones last, because they are less relevant that features matching in the title.

**Describe alternatives you've considered**
I'm currently using tags in the feature title, for things I think I might look for in the future.
For example, I would have a feature named `XYZ trail #trek #summer #lake #steep #risky`.
This can work fine, but I see two mains cons:
* When I create the feature, my present self needs to know what my future self might be looking for
* feature titles end up looking ugly

Instead, if descriptions could be searched, I could have:
```
title: XYZ trail
description: This is mainly a trek for summer. Nice lake on top. It is steep, so if conditions are bad it can be risky.
```
Anyway, I hope it made sense! I'm doing fine right now with my current tag system, but if more people find this interesting, maybe this can be implemented.

Thanks!

**Comment by yohanboniface** [comment]
Define "Search keys" in the map advanced properties:

![image](https://github.com/user-attachments/assets/76f36db0-002e-4757-8f9f-777b44f0b5a1)

**Comment by IgnacioHeredia** [comment]
Excellent! Sorry I missed that. Many thanks @yohanboniface !! 🚀
