### ISSUE TITLE
unable to save map

### ISSUE THREAD

**Issue by govvin** [umap-project/umap#215]
For a few days now, I've been working on a map but is unable to save the edits using Firefox (40.0.3) and Chromium (Version 44.0.2403.89) on Ubuntu 14.04 (64-bit). 

I already exported my data, just in case this fails completely, so I don't lose all my work. Are there existing issues about this?

**Comment by yohanboniface** [comment]
Is the map attached to an account or is it "anonymous"? If the latter, you may have lost the auth cookie.

**Comment by gitGOwin** [comment]
Yes, I used my OSM account to log in. On the top of the page, I see a never-ending attempt to save the map.

**Comment by yohanboniface** [comment]
Can you give the URL of the map?

**Comment by gitGOwin** [comment]
Try this, please: http://u.osmfr.org/m/50912/

However, what's visible is not what in the version I'm editing (and couldn't be saved.)

**Comment by yohanboniface** [comment]
Never seen this before. Can you clone this map and give me permissions on the clone so I can do some checks?

**Comment by gitGOwin** [comment]
Thanks for taking a stab at this Yohan. I just added you, but already lost the edits because I had to reboot my computer. :(

**Comment by yohanboniface** [comment]
Sorry, time files. Do you still have the issue?

**Comment by gitGOwin** [comment]
Hello Yohan. I'm sorry, but I have been unable to test it since losing the data after the reboot.

**Comment by vivideo** [comment]
I have exactly the same issue as described by govvin. It looks like a time-out error or a connection failure. In my case I'm about to lose lots of markup data :(

**Comment by yohanboniface** [comment]
@vivideo without more details, I'm unable to be of any help :/

**Comment by vivideo** [comment]
I understand. Is there a way to see log-files etc? Or a debug-mode?

**Comment by yohanboniface** [comment]
Some things you can try to narrow the issue:

- try with another map in another tab of the same browser
- try with another browser (with another map indeed)
- try with another computer (and with another map indeed)
- try with the same computer but from another network

**Comment by vivideo** [comment]
Ok, I will. 
* another map in another tab of the same browser: I tried that. Saving succeeded.
* another browser (with another map indeed): did not try, but I expect it would save the changes.
* another computer (and with another map indeed): did not try, but I expect it would save the changes as well.
* same computer but from another network: idem
* I also tried to reopen the map in the same browser using another tab. This only showed that the changes weren't saved.
Thanks!

**Comment by yohanboniface** [comment]
> I also tried to reopen the map in the same browser using another tab. This only showed that the changes weren't saved. Thanks!

And if you save the map from this tab (I know it's missing your changes, but to see if it's linked to the map itself or to the session or whatever)?
Are you logged in on umap?
What's the map URL?

**Comment by vivideo** [comment]
That did't work. I had to cancel the saving proces (that took already 30 minutes). I could have gone further editing though, but I knew it would save that work.. At this moment, after doing the markup job again, the map is saved correctly. The map isn't public (for now, it isn't finished yet), but I can send you the url. (I'll send you a message!)

**Comment by yohanboniface** [comment]
> edit: Is your username also yohanboniface? Then I include you as editor ;)

No, it's "ybon", but if the map is saving now, I'm not sure it's needed.
What exactly have you done? Reloaded the page?

**Comment by vivideo** [comment]
Ok :)
I just canceled saving. And without refreshing the map returned to its last saved state (so I could do everything all over again ;)

**Comment by yohanboniface** [comment]
Can you remember the last actions (with as details as possible) you made before trying to save without success?

**Comment by vivideo** [comment]
I was busy importing Google kml-files as new and in current layers. Then I made markup changes: custom symbol icons (external links), color of polygons. The not-saving-issue could have started during the import of the kml-files, but also during the formatting of the content.

**Comment by yohanboniface** [comment]
Try to save regularly now, and if you fall into the same issue give me all the actions you made before last save, so I have a chance to reproduce, and then to fix it. Thanks :)

**Comment by vivideo** [comment]
I will! Thanks for your time :)

**Comment by govvin** [comment]
Hello. I'd like to report that I'm experiencing this same issue again.

Again, I'm currently editing the map, and the perpetual attempt to save. I managed to save a few edits before the current operation which appears to have triggered it: fetching data remotely using an Overpass Turbo query.

For reference, the map is at http://u.osmfr.org/m/84417/

However, what's visible is the version I saved before adding a layer that's supposed to query data via Overpass Turbo.

**Comment by yohanboniface** [comment]
Do you see anything in your javascript console?

**Comment by govvin** [comment]
Thanks for asking that @yohanboniface . The solution is to request for an https URL, and that fixed the problem.

Below is the error from the console.

> Mixed Content: The page at 'https://umap.openstreetmap.fr/en/map/demo-fire-hydrant-map-manila-fire-district_84417#14/14.6146/120.9917' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://overpass-api.de/api/interpreter?data=[out:json][timeout:25];area(360…y%22=%22fire_station%22](area.searchArea););out%20body;%3E;out%20skel%20qt;'. This request has been blocked; the content must be served over HTTPS.

**Comment by govvin** [comment]
Querying the results through https resolved this issue. Thanks
