### ISSUE TITLE
Marker search

### ISSUE THREAD

**Issue by Cristian-wp** [umap-project/umap#2150]
**Is your feature request related to a problem? Please describe.**
I am creating a map with a lot of different marker types, and its a little bit difficult to find exacly the one I am looking for.

**Describe the solution you'd like**
I would like there is a search feature in order to find the marker I need. For example I write "pizza" in a text box and a list of marker regarding "pizza" shows up in a list, and if I click on a voice it redirect me directly on that marker.

**Comment by yohanboniface** [comment]
Have you tried the browser search ? If yes, can you explain why it does not work for you ?

**Comment by Cristian-wp** [comment]
No I havent try it. 
What do you mean with browser search? Is the standard Ctrl+F?

**Comment by yohanboniface** [comment]
No, Ctrl-F will do a search in all OSM data (roughly), while the browser will allow to search among the map features. You can find it on the left toolbar, then "filters".

**Comment by Cristian-wp** [comment]
@yohanboniface Thanks for the advice, but that search shuts down all the other elements. In my case I have load a building plan in a layer and all the device in another.
<img width="958" alt="2024-09-19 10_49_58-" src="https://github.com/user-attachments/assets/3d70674c-6698-48ef-a123-1bcbe38d011c">
If I search the "Printer" all the other elements will not be displayed. In my case that is ok for the devce layer, but I wish that the building mup stay visible.
<img width="958" alt="2024-09-19 10_50_25-Posta in arrivo - cristian trazzi@wpweb com - Outlook" src="https://github.com/user-attachments/assets/523f6ef5-0dd6-46c5-a539-fe7b82bbb413">
Is this already possible with some filter option?

**Comment by yohanboniface** [comment]
Try setting the building layer as "browsable=false"

**Comment by Cristian-wp** [comment]
It works! Thank you!

> Try setting the building layer as "browsable=false"
