### ISSUE TITLE
Loading CSV from URL -- problem with response, but works as a file

### ISSUE THREAD

**Issue by jflamy** [umap-project/umap#2161]
**Describe the bug**
I have a URL with valid CSV data -- downloading the file and loading it into umap works.
When I try to use the exact same URL to load the data, it fails with "error in response"

There is no way to see what the error is.  The csv does contain UTF-8 characters, which are not a problem when reading as a file.

**To Reproduce**
- download the data from https://getusage.jflamy.dev/all.csv
- load this data as a file, things work
- use this URL to import data, fails.

**Expected behavior**
using the URL should work.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 129

**Additional context**

**Comment by yohanboniface** [comment]
Sounds like a CORS problem (the remote server does not allow browser access from another domain). Sadly in this case the requests fails as any network error, so we cannot say it's due to CORS restriction and display a specific message :(

**Comment by jflamy** [comment]
Thanks! Nailed it.

The site that exposes my data is a trivial Caddy site.  The relevant snippet of the Caddyfile is
```
getusage.jflamy.dev {
        root * /var/log/usage
        file_server

        header {
                # Disable all CORS checks
                Access-Control-Allow-Origin *
                Access-Control-Allow-Methods *
                Access-Control-Allow-Headers *
        }

        @csvFile {
                path /all.csv
        }

        header @csvFile {
                Content-Type "text/csv; charset=utf-8"
        }
}
```

**Comment by jflamy** [comment]
If you can tell me what the origins header should be, and perhaps add this to the documentation.
Currently the documentation in French only discusses CSV files, not reading from URLs..
