### ISSUE TITLE
Explorateur de données : masquer les calques sans données

### ISSUE THREAD

**Issue by valenceromansagglo** [umap-project/umap#2170]
_Post en français par souci de clarté._

**Is your feature request related to a problem? Please describe.**
Une proposition que nous formulons suite à un de nos travaux en cours sur cette carte : 
https://umap.openstreetmap.fr/fr/map/toque-du-local_1108280

L'idée de cette carte est de permettre aux usagers de rechercher des producteurs locaux en fonction de la commune à laquelle ils appartiennent. Nous sommes une Agglomération de 54 communes, ce qui a nécessité de créer 54 calques différents. Les intégrations sont en cours, cependant la plupart des communes n'auront pas de donnée, du moins pas dans l'immédiat. Les calques restent cependant affichés, ce qui peut compliquer la recherche pour les usagers.

![Screenshot 2024-09-24 123618](https://github.com/user-attachments/assets/ce99c177-f10d-44fa-989e-72aabcd01770)

**Describe the solution you'd like**
Nous appuyons une demande faite ici auparavant (#1181) : nous souhaiterions que les calques ne contenant pas de données n'apparaissent pas dans l'explorateur de données.

**Describe alternatives you've considered**
Bouton "Lister seulement les éléments visibles" : ne répond pas à notre demande, même si certaines communes ne sont pas visibles, leurs calques restent affichés dans l'explorateur.

**Comment by yohanboniface** [comment]
Y a une raison particulière pour utiliser un calque par commune ? Une autre option serait d'avoir un seul calque et une colonne "commune" dans les données, puis un filtre sur cette colonne.  Dans ce cas, seules les valeurs existantes apparaîtraient.

**Comment by yohanboniface** [comment]
Duplicate of #1181
