### ISSUE TITLE
Marker label always displayed

### ISSUE THREAD

**Issue by Baliverbes** [umap-project/umap#218]
Hi,

would it be possible to have a choice whether to display a marker's name on top of it at any time ? Or starting at a certain zoom level/distance from other markers ? (so that they don't overlap)
May be a complex request, not sure how much work that represents.
The reason for that is sometimes a wide view of a map is not very explanatory, displaying labels would help scan things in a flash.

Merci pour votre travail,

Hadrien

(I don't seem to figure out how to label this as enhancement, maybe I don't have this privilege)

**Comment by yohanboniface** [comment]
This kind of label doesn't fit: http://umap.openstreetmap.fr/en/map/raspail_1#19/48.69578/6.18070 ?

**Comment by Baliverbes** [comment]
It does. I could not find it. Thanks for pointing me to it and apologies for this waste of time...

Hadrien

**Comment by yohanboniface** [comment]
No pb ;)
