### ISSUE TITLE
Add publiccode.yml

### ISSUE THREAD

**Issue by bzg** [umap-project/umap#2186]
I believe umap past developments have been funded by public money from the French administration: please correct me if I'm wrong or if this is an oversimplification.

`publiccode.yml` is a standard for describing software projects, particularily suitable for Free Software backed by public money.

I suggest adding a `publiccode.yml` at the root of umap's repository so that we can include umap in https://code.gouv.fr/fr/awesome/, a shortlist of "Awesome" open source project by the French administration. Of course, a project can be mostly funded by public money while having a governance and a roadmap that does not depend on French administration: if this is the case for umap, then the "Awesome code.gouv.fr" shortlist is not relevant.

Also, I suggest adding more information on how to contribute to the project and its governance - this could help attract more contributors.

Let me know how I can help with these suggestions!

**Comment by davidbgk** [comment]
@bzg where is the specification for `publiccode.yml`?

**Comment by bzg** [comment]
You can see an example here: https://github.com/codegouvfr/react-dsfr/blob/main/publiccode.yml

**Comment by bzg** [comment]
I see it has been added then removed from the roadmap.  If this does not seem useful, can I close this issue?

**Comment by yohanboniface** [comment]
As far as I understand, uMap is not concerned by this project, as it has not been created by the public sector. Corrige me if I'm wrong though!

**Comment by bzg** [comment]
My understanding was that umap was _mostly_ funded by public money, so that it could be conceived as "made by the administration".  Is that fully wrong?  Do we have public figures on where umap funding comes from?

**Comment by yohanboniface** [comment]
uMap exists since 2012, and has been mainly funded by volunteer time, apart from (from the top of my head) a feature (remote data) funded by the RATP years ago.

Since one year and a half, the ANCT and the DINUM/AIC are paying a team to work on uMap (two devs at two days a week each, one UX designer and one bizdev at one day a week each). Plus uMap have been granted by the NLNet to work on a "real time collaborative editing" feature on uMap (which is close to be finished), and has a new grant from them to come to integrate vector tiles.

**Comment by bzg** [comment]
Great, thanks for those details.  From these facts, I conclude that umap can be better considered as a volunteer-led project, with some support from public bodies and NLnet grants, but with the roadmap still in the hands of volunteers.  That's enough to make adding a `publiccode.yml` and joining the code.gouv.fr Awesome list irrelevant.

Thanks! Closing this issue.
