### ISSUE TITLE
"Route from here" does not work

### ISSUE THREAD

**Issue by cweiske** [umap-project/umap#219]
Right-clicking a point and selecting "route from here" opens map.project-osrm.org/ with the coordinates. Unfortunately, it does not seem to accept this parameters.

Example: http://map.project-osrm.org/?loc=51.52740913661656,-0.08299827575683594&hl=de

**Comment by yohanboniface** [comment]
ah, thanks for the report, API may have changed. I'll look at that quickly.

**Comment by laraque** [comment]
Can yours help me to publish an OSM URL directions with the OSRM routing engine into UMap ?

I have the next URL: 
https://www.openstreetmap.org/directions?engine=osrm_car&route=5.71817%2C-72.93340%3B5.71195%2C-72.92650#map=18/5.71619/-72.93029

According to the issue : [6960299](https://github.com/umap-project/umap/commit/6960299d213dd404975e6d846bfda745de65aa5d) 

The structure of the URL must be :
`http://www.openstreetmap.org/directions?engine=osrm_car&route={lat},{lng}&locale={locale}#map={zoom}/{lat}/{lng}`


So, if, i modify the source URL to the expected format

> https://www.openstreetmap.org/directions?engine=osrm_car&route={5.71817},{-72.93340}{5.71195},{-72.92650}#map=18/5.71619/-72.93029

**Looks like is missing the ending point**  in the formt URL to work inside UMap.

Thanks for your attention,

**Comment by yohanboniface** [comment]
You should use the `{` only to use a variable, so `{lat}`, but if you use the actual value, you should just put the raw value:

https://www.openstreetmap.org/directions?engine=osrm_car&route=5.71817,-72.93340&locale=5.71195,-72.92650#map=18/5.71619/-72.93029

**Comment by laraque** [comment]
Well , i tried the URL suggested with the fixed options .. and again nothing is showed .

I tried in two UMap instances, to see if there are differences in the UMap versions:
-- https://umap.openstreetmap.fr
--  http://umap.openstreetmap.co/es/

Im using the external data option, and OSM type to work inside the UMap layer.

Maybe i missing something else ??
