### ISSUE TITLE
[Request] Give me ownership of maps that I created without being connected to uMap

### ISSUE THREAD

**Issue by Binnette** [umap-project/umap#2190]
Hi, just a request: can you give me the ownership of those maps:

- https://umap.openstreetmap.fr/en/map/public-bookcases_362282
- https://umap.openstreetmap.fr/en/map/2019-05-27-public-bookcases_362245

OSM account: Binnette

I created those maps in 2019 but forgot to connect with my OSM account on uMap before creating it.

Thank you.

**Comment by yohanboniface** [comment]
Hey @Binnette, can you send me an email instead, I'll give you the secret edit link there :)
