### ISSUE TITLE
Duplicate in the Serps

### ISSUE THREAD

**Issue by Latinamap** [umap-project/umap#2201]
Hello,
How can I delete a test map (/dev.umap-project.org/) that appears as a duplicate in the Serps?
Merci par avance
Yves
contact@latinamap.eu

Top latino festival France et Europe : Salsa & Bachata - uMap
umap-project.org
https://dev.umap-project.org/fr/map/top-latino-festival-france-et-europe-salsa-bachata_6540#5/48.720/2.197

![Image](https://github.com/user-attachments/assets/db819e9f-78c9-422e-bfc8-ed2af6c3e8bd)

**Comment by davidbgk** [comment]
Good catch, we'll add the proper noindex/robots.txt directives to avoid that!

**Comment by Latinamap** [comment]
Thanks !

**Comment by yohanboniface** [comment]
Workaround in the meantime, pass the map in non public (private or users with link only).

**Comment by Latinamap** [comment]
yes, but you need access rights to do this!
