### ISSUE TITLE
Turn layer on/off via Marker

### ISSUE THREAD

**Issue by ahspence53** [umap-project/umap#2208]
**Is your feature request related to a problem? Please describe.**
This is not an issue, but a request for an enhancement.

**Describe the solution you'd like**
I use uMap for recording walks and hikes.
Each starting location for a walk/hike is highlighted using a marker, I use a drop icon.
Each Marker has properties which I load in using a CSV file, the interaction I use is Side Panel pop-up shape with Table pop-up context to display walk/hike information.
I would like to be able to have the GPX track, which I can load also using a CSV file, to be displayed when I click on the marker, so that the GPX track (which will be on a separate layer) will display at the same time as the pop-up table is displayed.

**Describe alternatives you've considered**
Can't see any other way of doing this.

**Additional context**
None.

**Comment by jschleic** [comment]
Regarding alternatives / workaround: In [this map ](https://umap.openstreetmap.fr/de/map/adfc-sternfahrt-2023_866879) I use links in marker text with parameter `datalayers=` to hide everything but the selected layer (I'm not sure, if the map is reloaded on every click?). How many layers are on your map? Could something similar be a feasible workaround?

**Comment by ahspence53** [comment]
Thank you! That does look ideal. I'll need to look into how I use **datalayers=** 
I appreciate your advice. 😀

**Comment by ahspence53** [comment]
> Regarding alternatives / workaround: In [this map ](https://umap.openstreetmap.fr/de/map/adfc-sternfahrt-2023_866879) I use links in marker text with parameter `datalayers=` to hide everything but the selected layer (I'm not sure, if the map is reloaded on every click?). How many layers are on your map? Could something similar be a feasible workaround?



> Regarding alternatives / workaround: In [this map ](https://umap.openstreetmap.fr/de/map/adfc-sternfahrt-2023_866879) I use links in marker text with parameter `datalayers=` to hide everything but the selected layer (I'm not sure, if the map is reloaded on every click?). How many layers are on your map? Could something similar be a feasible workaround?

**Comment by ahspence53** [comment]
Hi, I discovered using Layer Permalink gives me exactly what I require
