### ISSUE TITLE
Failed with GitHub Log-in on the current https://umap.openstreetmap.fr/en/

### ISSUE THREAD

**Issue by easz** [umap-project/umap#221]
it comes out 404 page.

http://umap.openstreetmap.fr/complete/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=aTt3cmAPnOz1fc1x8MpMUcBzfFYWSYgV

**Comment by yohanboniface** [comment]
Ah, http vs https. Try with http for now, I'll see how I can enable both.

**Comment by yohanboniface** [comment]
cf #502
