### ISSUE TITLE
Caption not being displayed on map load if any datalayers are set to off, or turned off.

### ISSUE THREAD

**Issue by ahspence53** [umap-project/umap#2232]
**Describe the bug**
On a map, if I have any layers with the property **Datalayers=OFF**
The Caption does not display when I have set **Do you want to display a panel on load** to **Caption**
When set **Datalayers=ON** and refresh the map, the Caption appears.
**To Reproduce**
1. Go to 'https://umap.openstreetmap.fr/en/map/walk-details_1078445#10/55.6342/-4.3176'
2. Click on 'Open Caption'
3. The Caption does not appear, unless you browse the Datalayers and either temporarily set the layer Tracks to Visible, or set the property to Datalayers=ON, then if you click Open Caption it appears.

**Expected behavior**
I would expect the caption to appear even if I have certain datalayers turned off, or set to off

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser
 - Version 
 - 

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: IOS 18.1
 - Browser Chrome, Firefox and Safari
 - Version 

**Additional context**
None

**Comment by yohanboniface** [comment]
Thanks for the report, we'll have a look.
