### ISSUE TITLE
"Confirm Reload: true" when refreshing page

### ISSUE THREAD

**Issue by stevage** [umap-project/umap#224]
When reloading or leaving a page with unsaved changes, Chrome shows:

![screenshot 2015-10-11 19 24 14](https://cloud.githubusercontent.com/assets/678344/10415986/ead608e6-704d-11e5-9977-9073f429bce1.png)

Passing an incorrect argument, perhaps?

**Comment by yohanboniface** [comment]
Fixed in code but not released.
