### ISSUE TITLE
Add Positron and Dark Matter base maps

### ISSUE THREAD

**Issue by stevage** [umap-project/umap#225]
These two general purpose maps from CartoDB are [free to use](https://cartodb.com/basemaps/), based on OpenStreetMap data, quick to load, and excellent for overlaying data. 

* `http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png`
* `http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png`

If the list is too long, maybe cull some of the really obscure ones like "OpenRiverboatMap" :)

(Yes, I know you can add your own custom map individually to each map - this is a suggestion for the default list.)

**Comment by yohanboniface** [comment]
Done :)
