### ISSUE TITLE
Fetching variables through Iframe in popup

### ISSUE THREAD

**Issue by yanisperron** [umap-project/umap#2269]
Hello,

I'd like to be able to create a dynamic iframe to display in my popups, interacting with the variables.
I spent all day trying to figure this out and I found a pretty good way of doing it but it seems I'm blocked by uMap limitations.

My iframe link is as follow : 

`{{{https://yanisperron.github.io/infocard.html?name={name}&description={description}}}}`

Quick glance at the code, it seems we're prevented from adding any brackets to the link, but my knowledge in coding is too small to understand why this could be an issue.

I would be grateful if this could be a feature. Sorry if its not the place for such things I just made a github account for this.
Thank you.

**Comment by yohanboniface** [comment]
Thanks! Seems to be related to having spaces in the query string (the values of "name" or "description"). Should be fixed in next release (I've not ETA yet).
