### ISSUE TITLE
Layer properties page needs a title

### ISSUE THREAD

**Issue by stevage** [umap-project/umap#227]
Editing properties of layers would be less confusing IMHO if the page had a title, "Layer properties". At the moment, it's not at all clear *what* you're editing.

![screenshot 2015-10-11 23 42 22](https://cloud.githubusercontent.com/assets/678344/10416813/c6e2772a-7071-11e5-8081-1416c53b5c81.png)

**Comment by yohanboniface** [comment]
Missing for so long! Thanks for the ribbing :)
