### ISSUE TITLE
Improved English labels

### ISSUE THREAD

**Issue by stevage** [umap-project/umap#228]
Not sure whether I did this right or not, but I've added quite a few improved "translations" in Transifex: https://www.transifex.com/yohanboniface/umap/translate/#en_US/frontend/19079942

These are mostly to use more idiomatic English, and sometimes improved UX or better consistency.

(Takes me back a bit - in 2005 I was working at a software company in Lyon, translating the French developers' "English" UI labels into actual English. :) )

**Comment by yohanboniface** [comment]
> (Takes me back a bit - in 2005 I was working at a software company in Lyon, translating the French 
> developers' "English" UI labels into actual English. :) )

Yeah, we are still there ;)

On Transifex, you requested also "en_AU" and "en_GB", was that a mistake or are you willing to translate them too?

**Comment by yohanboniface** [comment]
Also, for chatting, instead of opening an issue, you can raise up at https://gitter.im/umap-project/umap or on #umap@Freenode servers. ;)

(Closing here as there is no action needed.)
