### ISSUE TITLE
Default map position

### ISSUE THREAD

**Issue by stevage** [umap-project/umap#229]
It seems that every map defaults to a view over western Europe until you explicitly set it. This is, um, sub-optimal for 95% of the world :)

Suggestions:
- set a default extent the first time you import any data
- set a default extent the first time you press Save

**Comment by yohanboniface** [comment]
You know you can change it, right?

**Comment by stevage** [comment]
Yes. (Weird, I thought I added a line to the description saying, "Yes, I know you can change it". Heh.)

It may not seem so bad to you because the default is kind of reasonable for European users. But if the default was, say, Argentina, you'd see it's pretty bizarre.

**Comment by yohanboniface** [comment]
There are two things here.
Firstly, the default center depends of the uMap instance, so as you can see the French instance defaults to somewhere in Europe, but the Swiss one defaults to Switzerland (http://umap.osm.ch/en/map/new/) and the Colombian one defaults to Colombia (http://umap.openstreetmap.co/en/map/new/) ;)

Secondly, that's true that any of those instance can be used by users from anywhere in the world. And true that no default center can match all users needs. So there is room for improvement here.

I don't really like the idea of saving the center while the use doesn't exactly means that.

Here are two other suggestions:
- retrieve user geolocation when creating a map (but that mean a dialog saying "do you want to share your position" each time one creates a map)
- save a cookie each time a user save map position and use this position next time as default center

**Comment by stevage** [comment]
>save a cookie each time a user save map position and use this position next time as default center

Yeah, but you'd have to track whether or not they had set an *explicit* position, which would override this.

Incidentally, this is the approach CartoDB takes, but not with no explicit positions. End users always see wherever you last panned to, which I find really poor UX.

Another approach: if no explicit position, set the initial view to the extent of all layers, zoomed out slightly.

**Comment by yohanboniface** [comment]
Work in progress cf #841

**Comment by yohanboniface** [comment]
Should have been done since then!
