### ISSUE TITLE
Display length of feature

### ISSUE THREAD

**Issue by mattbk** [umap-project/umap#230]
I swear that last year when I was making a map of a race course, I could click on a polyline and the length/distance of the feature would pop up.  Has something changed, or I have I forgotten how to enable this functionality?

**Comment by yohanboniface** [comment]
You need to click on "More" button, then last control on the bottom.

**Comment by mattbk** [comment]
> You need to click on "More" button, then last control on the bottom.

That's to measure an arbitrary distance, not an existing feature..  Is there no way to click on a polyline and get the length of that feature?

**Comment by yohanboniface** [comment]
That should display measure of all drawn feature.

**Comment by yohanboniface** [comment]
Something like that:
![screenshot from 2015-10-12 17 19 26](https://cloud.githubusercontent.com/assets/146023/10431449/6b4998b4-7105-11e5-98e2-774a70c3af7e.png)

If it's not, it's a bug ;)

**Comment by mattbk** [comment]
Thank you, you are right.  I wasn't looking at a wide enough area.

**Comment by yohanboniface** [comment]
OK :)

**Comment by miksen** [comment]
I'm looking for this feature, and I cannot find it. Is it now hidden behind some setting I need to enable?

**Comment by mattbk** [comment]
Now I am seeing the measurement show up in the top center of the screen when I mouseover a polyline. This seems less intuitive. You still need to have clicked on the measure button.

![image](https://user-images.githubusercontent.com/3729038/100364274-8582c480-2fc3-11eb-9770-9306d05e832e.png)

**Comment by RemiCardona** [comment]
Every few months or so, when I use umap to keep track of hikes, I keep forgetting how to find the length of the lines I've drawn and I keep coming back here. I'd say there's some room for a little improvement. Cheers
