### ISSUE TITLE
Support file drag-and-drop 

### ISSUE THREAD

**Issue by stevage** [umap-project/umap#231]
It's become fairly common to allow users to drag and drop files from the desktop into web applications. For instance, MapBox, CartoDB and [TerriaJS](http://terria.io) all support this. It's especially useful if you can drag-drop multiple files at once. (CartoDB doesn't support that).

More info: http://www.htmlgoodies.com/html5/javascript/drag-files-into-the-browser-from-the-desktop-HTML5.html

**Comment by yohanboniface** [comment]
https://github.com/placemark/flat-drop-files may help
