### ISSUE TITLE
Text formating doesn't work on layers

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#232]
Formating the description of a layer doesn't work. A description such as :[[http://hiking.waymarkedtrails.org/fr/routebrowser/5540239/gpx|Télécharger le fichier GPX]]
is nicely formatter on the map description and on an item description, but appears as such on layer description.
See this map for instance : http://umap.openstreetmap.fr/fr/map/randonnees-a-chemere_56422#

**Comment by yohanboniface** [comment]
Good catch! Will be fixed in next release (soon, now that Leaflet beta2 is out http://leafletjs.com/2015/10/14/leaflet-1.0-beta2-released.html :) ).
