### ISSUE TITLE
bring up the label key in the layer panel

### ISSUE THREAD

**Issue by Aurelie-Jallut** [umap-project/umap#2331]
**Is your feature request related to a problem? Please describe.**
Tests with uMap users show that it is difficult to find where change the content of the label, and that this is a priority need.

**Describe the solution you'd like**
In the layer panel, could we leave the ‘Advanced properties’ panel and bring up the function that lets you define the label key?

**Comment by yohanboniface** [comment]
> could we leave the ‘Advanced properties’ panel 

I'm not sure what you mean here 🤔

**Comment by yohanboniface** [comment]
See also #2291 and #2281

**Comment by Aurelie-Jallut** [comment]
I mean moving this field up under the layer type selection

![Image](https://github.com/user-attachments/assets/d9e65024-e538-483e-9ae3-1a8715c8a663)

**Comment by yohanboniface** [comment]
Like this ?

![Image](https://github.com/user-attachments/assets/beb1b12a-8b33-46a7-a7cd-c08347041e29)
