### ISSUE TITLE
Be able to assign multiple tags

### ISSUE THREAD

**Issue by Aelyth** [umap-project/umap#2336]
**Is your feature request related to a problem? Please describe.**
I have a map when I want to identify my locations not only by categories but also by month**s** recommanded to visit the location, and to be able to filter on this information.

**Describe the solution you'd like**
It would be great if I could create only one "Month" column and add several information which can be seperated in the filters. For example, it put both "January" and "March", seperated by a comma, and umap treat each one as separated infos instead of "January, March"

**Describe alternatives you've considered**
For now, if I want to do that, I need to create one column for each month, and put "Yes" or "No" in it, for the information to be separeted. It works, but I have to create a lot of differents properties and it make the properties board really heavy.

**Additional context**
Of course, my example is by month, but by theme work also, or even categories.

**Comment by yohanboniface** [comment]
Thanks for the suggestion and the use case, I think it is the same as #1570, so I'm closing here, but let's track the need there.
