### ISSUE TITLE
Website: URL still pointing to bitbucket

### ISSUE THREAD

**Issue by htgoebel** [umap-project/umap#234]
On the website, the ULR behind "And it's open source!" is still pointing to bitbucket. At least for English and German.

**Comment by yohanboniface** [comment]
Yes, see #214 :)

Fixed but not yet released (but you can test new version on the demo site though: http://umap.fluv.io/en/ ).

**Comment by htgoebel** [comment]
Sorry for the duplicate. I searched the issues for "website" while "bitbucket" would have been the better search-term.
