### ISSUE TITLE
In some situations, features are deleted even after the user selected "cancel" in the deletion confirmation message box

### ISSUE THREAD

**Issue by slasherfun** [umap-project/umap#2355]
**Describe the bug**
In some situations, features are deleted even after the user selected "cancel" in the deletion confirmation message box.

**To Reproduce**
1. Download the file jsons.zip attached to this bug report [jsons.zip](https://github.com/user-attachments/files/18068619/jsons.zip)
, and extract the two .json files it contains.
2. Go to either instance of uMap (reproduced on FR/DE/CH)
3. Create a new map
4. On the right menu, click "import data"
5. Import one of the two json files, its content (a polyline) is added to the map
6. Import the second of the two json files (doesn't matter if on a different layer or on the same layer), its content (another polyline) is added to the map
7. Click on one of the two polylines added, and click on the "trash" icon
8. A message box appears to ask the user to confirm the deletion of the feature, click "cancel" --> the polyline is still there, which is expected
9. Again, click on one of the two polylines added, and click on the "trash" icon
10. Again, a message box appears to ask the user to confirm the deletion of the feature, this time click "OK" --> the polyline is deleted, which is expected
11. Click on the remaining polyline, and on the "trash" icon
12. Once more, a message box appears to ask the user to confirm the deletion of the feature, click "cancel" --> the polyline is deleted, while the user wished to cancel the operation

**Expected behavior**
The polyline shouldn't be deleted

**Screenshots**
Short video: https://dubz.co/c/79c41f (couldn't attach it to the bug report)

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2
 - Browser Mozilla Firefox
 - Version 134.0b8

**Additional context**
This bug report describes a way that I found to reproduce the issue, but I'm sure there at least another way to reproduce it, since I never pressed the "trash" button before first encoutering this bug.

**Comment by davidbgk** [comment]
I confirm the bug both in production and on the `master` branch.

**Comment by davidbgk** [comment]
@slasherfun thanks a lot for taking your time to investigate and document so thoroughly that nasty bug! Really appreciated 👏 🙇
