### ISSUE TITLE
Support opacity on markers

### ISSUE THREAD

**Issue by stevage** [umap-project/umap#236]
There doesn't seem to be a way to make an individual marker more transparent (less opaque). Even using a warkaround color description like `hsla(120,50%,50%,30%)` didn't work.

**Comment by VladimirSlavik** [comment]
You have the css color code wrong, I think. When I pasted what you wrote here I got a blue-something. It was the same when I deleted random bits of that code. Let me share my own "solution"...

rgba(255,0,0,1) - red markers
rgba(255,0,0,0) - fully transparent red
![umap-transparency](https://cloud.githubusercontent.com/assets/15903878/11236859/940d6228-8ddc-11e5-8a21-7750a5d7f7d8.jpg)

**Comment by stevage** [comment]
Ah, yeah, thanks - the correct CSS format is `hsla(0, 50%,50%,0.1)`.

As noted, it only changes the background colour - the icon is still 100% opaque.

**Comment by VladimirSlavik** [comment]
...use a custom fully transparent pic for the icon, then? That leaves only the shadow and offset inherent to the pin-like style.

**Comment by stevage** [comment]
Oh, yes :) Ok, so there is a workaround.
