### ISSUE TITLE
[wishlist] Proportionnate representation (color, size)

### ISSUE THREAD

**Issue by adrien-r** [umap-project/umap#237]
Hi,

It would be great to be able to use a table value as parameter in the representation.
For example : population per city/region (variation of color or size of the marker represents the population).

Thanks for your amazing work anyway !

**Comment by yohanboniface** [comment]
cf #1136

**Comment by yohanboniface** [comment]
Should be handled by choropleth layer type. Do not hesitate to reopen/comment if you test and have cases not covered.
