### ISSUE TITLE
Python locking geojson file so geometry can't be stored

### ISSUE THREAD

**Issue by jdmount** [umap-project/umap#238]
Everyone,
I just started playing with umap and I am really impressed with the system.  We are going to use it in a research project so I installed it on a Windows 7 machine and everything works fine except for saving layers to the database storage.  The problem seems to be that python locks the geojson file so it can't be uploaded - following is an example of the error:

WindowsError at /en/map/7/datalayer/create/
[Error 32] The process cannot access the file because it is being used by another process: u'F:\NARRATIVE_GEOGRAPHIES
\Envs\umap\umap\var\uploads\datalayer\7\7\layer-1.geojson'

Python is locking the file and not closing it - or at least that's what it seems.  Checking this in Windows - i.e. trying to delete the file shows that it's locked as long as the umap instance is running.

The host machine is running Windows 7, database, virtualenv, etc are all set up and working.  I could use Linux to host it if needed but I will have to set up a virtual machine so I tried it on my workstation as an experiment.    

Has anyone seen this before?
Thanks for any information,
Jerry

ps. I apologize if this isn't the correct place to put the issue.

**Comment by yohanboniface** [comment]
@jdmount never seen uMap running on Windows before myself, so I've no experience.

Are you running on latest django-leaflet-storage master?

**Comment by jdmount** [comment]
Yohan, thanks for the quick reply.

As for the storage module I installed it through the requirements.txt file – the version is django-leaflet-storage==0.8.0b0.  It seems like when it saves it locally as a geojson that python doesn’t close the file.  I was going to dig through the code but thought I’d ask first.  It sounds like most people use linux.

Thanks again,
Jerry

**Comment by yohanboniface** [comment]
>  It sounds like most people use linux.

Yeah :) If you have the option to use Linux, just do that. Otherwise this will need a bit of investigation. That sounds weird anyway, so even if this does not seems to be a visible in Linux, it may be something wrong anyway.

**Comment by jdmount** [comment]
I can try it with Linux – I have a CentOS vm somewhere so I’ll try that.  I can try to dig at the issue and see if I can come up with anything.  I saw this once a long time ago on a different application and somehow fixed that – seems like it was a simple file.close() that fixed it.

I’ll try to track it through the wsgi calls to find where it writes out the file to local filesystem and go from there.

Ok – sorry to bug you with windows issues…
