### ISSUE TITLE
Add a "Non authorized" page

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#2390]
When someone loads a map they cannot access to, they have a blank page, without any explanation.

Now that draft is default mode, this situation will happen more often, so I think we need a message in this page. Something like "This map is private" or "You are not authorized to see this map".

@Aurelie-Jallut what do you think ? :)

**Comment by Aurelie-Jallut** [comment]
"This map is private" or "You are not authorized to see this map" sounds good

We can add : 
Are you the map's editor? Find out here how to manage the map's permissions. (link to documentation)

and below,  a link to the home page of the map instance

I can also create a small visual : )

**Comment by Aurelie-Jallut** [comment]
👀 [figma link](https://www.figma.com/proto/7ytmJizPCtdncPBD7BeRlj/UI-uMap?page-id=1305%3A3983&node-id=2849-13840&viewport=-4061%2C1433%2C0.7&t=bnD42zXTNqfavbI6-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2849%3A13840) 
<img width="600" alt="Image" src="https://github.com/user-attachments/assets/6c8b0e7b-4832-40e8-b02f-7e186b7fb619" />

**Comment by davidbgk** [comment]
I was thinking maybe `This map is not publicly available` would be a better message (if the owner forgot to change the status from Draft to Public for instance).
