### ISSUE TITLE
"Zoom to layer extent" not working on layers

### ISSUE THREAD

**Issue by sfaraut** [umap-project/umap#2391]
"Zoom to layer extent" functionnality not working on layers

It seems that clicking on the icon allowing to "Zoom to layer extent" not currently working on any standard layers as intended (no action).

**To Reproduce**
1. Go to any Umap. For example: https://umap.openstreetmap.fr/en/map/umap-zoom-test_1155149
2. Scroll anywhere on the map
3. In the "Data browser", click on 'Zoom to layer extent' icon
4. Problem: No action - The map layer's frame doesn't update to show all the features contained in the layer.

**Expected behavior**
Clicking on the icon "Zoom to layer extent" of a layer should zoom to show all the features contained in this layer.
By the way, I found that clicking on the icon "Zoom to data extent" (first item in Data browser") works. But is not a workaround when having several layers on the map.

**Screenshots**
![Image](https://github.com/user-attachments/assets/3f3609b1-2364-4414-bcdd-e3dc4fa2b4c6)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by davidbgk** [comment]
Fixed in https://github.com/umap-project/umap/pull/2394
