### ISSUE TITLE
Can't create a Marker (this._leafletMap.startMarker is not a function)

### ISSUE THREAD

**Issue by DasFranck** [umap-project/umap#2392]
**Describe the bug**
Can't create a marker on umap, nothing happens on the UI but I get an error in the dev console.
Tried on both uMap FR and dev instances, on three different OS with different browsers plus my phone.

**To Reproduce**
- Go on any umap on following instance on which you have edit rights:
  - https://dev.umap-project.org/
  - https://umap.openstreetmap.fr/
- Click on edit button
- Try to create a marker
- Nothing happens, error in the dev console appears, screenshot in the dedicated section below

**Expected behavior**
Marker to be created and no error in the console.

**Screenshots**
![Image](https://github.com/user-attachments/assets/30676ef1-e641-4960-8530-37bd49d312e2)

**Desktop:**
- OS: Windows 11
- Browser: Firefox 133.0.3
- OS: ArchLinux
- Browser: Firefox 133.0.3

**Smartphone:**
 - Device: One Plus 13
 - OS: Android 14
 - Browser: Firefox Mobile
 - Version: 133.0
 - Browser: Chrome
 - Version: 128.0.6613.88

**Additional context**
It seems to have appeared since new UMap version rollout (2.8.0) as it was working perfectly fine one week ago and stopped working around 2 days ago.

**Comment by yohanboniface** [comment]
Thanks for the report!
Sadly I cannot reproduce, so this needs more context.
Let's try a bit random: can you add a line ? have you tried from another network (in case it's a cache issue) ? Do you have any error in the network tab of the console ?

**Comment by yohanboniface** [comment]
I'd say the CORS is unrelated, but it's still may be a hint. Maybe some browser addon blocking some request ?

I've seen you already tested in three Firefox and one Chrome on mobile, but can you make some other tries ? Do you have a Chrome/Chromium on your Arch to test ?

We have to find what's specific on your setup. And the error seems to come from nowhere, so my only guess at this time is that one library needed by uMap (Leaflet.Editable) is not loaded, but I've no idea why (if it's the case, I may also be on the wrong track).

Just in case, can you load this URL ?

https://umap.openstreetmap.fr/static/umap/vendors/editable/Leaflet.Editable.717772131828.js

**Comment by DasFranck** [comment]
Hello,

Unfortunatly it doesn't seems to work either on Chromium 131.0.6778.204 on ArchLinux.
Also, your link is accessible on all my devices and is correctly loaded when I access a map.

Kind Regards,

**Comment by yohanboniface** [comment]
Anyone else having this issue to help narrowing down which context creates it ?

**Comment by denizkurt** [comment]
The "save location as a new feature" button in search results no longer works on https://umap.openstreetmap.fr. Nothing happens on the UI but I get errors in the dev console:

![Image](https://github.com/user-attachments/assets/af9af1cd-e2a6-43fa-b525-5c0857f4134c)

Tested wifi and mobile connections with no extensions on Debian 12: Firefox 133.0.3 and ungoogled-chromium 131.0.6778.204

I also get the CORS error described by DasFranck.

Selecting "draw a marker" from the right toolbar works fine.

**Comment by DasFranck** [comment]
Hello,
Thank you for the message Deniz, this is indeed working while using the option on the right toolbar I was so used to to it via the right click that I forgot it could also be done this way, I will use it as a workaround until resolution of the issue!

The comportement I described was also when selecting the option after a right click and while trying to add a location as marker in the search menu.

Have a merry christmas!

**Comment by yohanboniface** [comment]
thanks @denizkurt for the report, I'll fix this.

@DasFranck only now I understand that you tried to create the marker with right-click and not the toolbar… So now I can reproduce and then I'll be able to fix too!

**Comment by DasFranck** [comment]
Yeah, I've probably not been accurate enough in the bug report, sorry for that.
However, I'm glad that the fix in the source code turns out to be quite simple!

**Comment by yohanboniface** [comment]
Fixed and deployed!

Now I'm wondering why when right-clicking and select "Add a marker" it does not create a marker where the user clicked. Wouldn't this make more sense ? Otherwise it's just the same as clicking on the toolbar.
