### ISSUE TITLE
How can I set the initial zoom and location?

### ISSUE THREAD

**Issue by amenk** [umap-project/umap#245]
I want to use a specific location on my instance. How can I configure that?

**Comment by yohanboniface** [comment]
In your settings: LEAFLET_LATITUDE, LEAFLET_LONGITUDE and LEAFLET_ZOOM

(Writting that, I see that having one setting for latitude and one for longitude doesn't make sense. I'll change that (keeping compat ;) ).)

**Comment by amenk** [comment]
Thanks
