### ISSUE TITLE
When setting Debug = False, static content is no longer loaded

### ISSUE THREAD

**Issue by amenk** [umap-project/umap#248]
When I set `DEBUG = False` URLs like http://example.com/static/storage/reqs/leaflet/leaflet.css throw a 404 error. Is this expected behaviour?

**Comment by yohanboniface** [comment]
Yes. Python should not serve statics. So when in production, you need to setup nginx (or whatever HTTP server you are using) to do that. See: https://docs.djangoproject.com/en/dev/howto/deployment/

**Comment by amenk** [comment]
thanks once again. I've put an `Alias /static /static/folder` now
