### ISSUE TITLE
Tiles from GI-Science Heidleberg problem --> Solution inside

### ISSUE THREAD

**Issue by FlorianBoegner** [umap-project/umap#251]
Hi Guys,

I just phoned the University as their tiles are not working anymore. 
They changed their IP-Adress...and recommend to use DNS.
Could you please change this, so the tiles are visible again on my umap? :)
Thanks a lot in advance!
Florian

Copied from their page (http://korona.geog.uni-heidelberg.de/contact.html):

 Web Map Tile Service Links
OSM Roads layer:
URL: http://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}
or http://129.206.66.245:8001/tms_r.ashx?x={x}&y={y}&z={z}
OSM Semitransparent layer:
URL: http://korona.geog.uni-heidelberg.de/tiles/hybrid/x={x}&y={y}&z={z}
or http://129.206.66.245:8003/tms_h.ashx?x={x}&y={y}&z={z}
ASTER GDEM & SRTM Hillshade layer:
URL: http://korona.geog.uni-heidelberg.de/tiles/asterh/
or http://129.206.66.245:8004/tms_hs.ashx?x={x}&y={y}&z={z}
ASTER GDEM contour lines layer:
URL: http://korona.geog.uni-heidelberg.de/tiles/asterc/
or http://129.206.66.245:8006/tms_il.ashx?x={x}&y={y}&z={z}
OSM Administrative Boundaries layer:
URL: http://korona.geog.uni-heidelberg.de/tiles/adminb/
or http://129.206.66.245:8007/tms_b.ashx?x={x}&y={y}&z={z}
OSM Roads Grayscale Layer:
URL: http://korona.geog.uni-heidelberg.de/tiles/roadsg/
or http://129.206.66.245:8008/tms_rg.ashx?x={x}&y={y}&z={z}

**Comment by yohanboniface** [comment]
Thanks!

>  URL: http://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}

Does not seem to be working. See http://korona.geog.uni-heidelberg.de/tiles/roads/x=0&y=0&z=0 for example.

**Comment by FlorianBoegner** [comment]
This map (http://korona.geog.uni-heidelberg.de/) works for me on firefox but not on chrome...mhm..

Ai strange...This was the number of the guy: +49 6221545505. He speaks English, maybe he can clarify...I am to noobish ,-)

**Comment by yohanboniface** [comment]
Seems ok now. Thanks for the ping :)
