### ISSUE TITLE
Add documentation, where to file issues for which part of umap

### ISSUE THREAD

**Issue by thoka** [umap-project/umap#253]
As I understand umap consists of at least three different parts (maintained by umap-project or yohan)
- django backend: [django-leaflet-storage](https://github.com/umap-project/django-leaflet-storage)
- js frontend: [Leaflet.Storage](https://github.com/umap-project/Leaflet.Storage)
- part of frontend gui: [Leaflet.FormBuilder](https://github.com/yohanboniface/Leaflet.FormBuilder)

Which is the right place to  collect wanted features, user and dev documentation requests ?

**Comment by yohanboniface** [comment]
> Which is the right place to collect wanted features, user and dev documentation requests ?

The first you find is good ;)
A developer will certainly create the issue on the library, while a user will create the issue in umap itself as it's the main entry point.
I think that's OK :)
