### ISSUE TITLE
URL scheme too short for WMTS in tile layer administration...

### ISSUE THREAD

**Issue by cquest** [umap-project/umap#255]
Example...

http://wxs.ign.fr/73op4emhz6dyqwgcbuvr162x/wmts/?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&FORMAT=image%2Fjpeg

it is limited to

http://wxs.ign.fr/73op4emhz6dyqwgcbuvr162x/wmts/?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&FORMAT=i

**Comment by smallf00t** [comment]
Same issue
changing size postgres did not solve ...
