### ISSUE TITLE
Anonymous Editing Link in umap doesn't work anymore

### ISSUE THREAD

**Issue by buddyholgi** [umap-project/umap#256]
Hello,
I created a map without being logged in an received an anonymous link in order to edit it. But this link doesn't work.
Can you please help me?
Thanks

**Comment by yohanboniface** [comment]
What's the map public URL (no the edit link!) ?

**Comment by buddyholgi** [comment]
It's
http://umap.openstreetmap.fr/de/map/nisthilfen_nauheim_60756#14/49.9508/8.4650

**Comment by buddyholgi** [comment]
Hello,

any news?

I urgently need to get this map deleted from the public "map of maps"

Cheers

 

-----Original-Nachricht-----

Betreff: Re: [umap] Anonymous Editing Link in umap doesn't work anymore 
(#256)

Datum: 2015-11-27T07:34:13+0100

Von: "Yohan Boniface" <notifications@github.com>

An: "umap-project/umap" <umap@noreply.github.com>

 

 

 

What's the map public URL (no the edit link!) ?

—
Reply to this email directly or view it on GitHub
<https://github.com/umap-project/umap/issues/256#issuecomment-160052616> .

**Comment by yohanboniface** [comment]
Send me an email at ybon at openstreetmap dot fr I will send you a new edit link.

**Comment by buddyholgi** [comment]
You were going to provide a new link. I emailed you twice as you asked without any reaction from your side.
