### ISSUE TITLE
url parameter onLoadPanel doesn't work

### ISSUE THREAD

**Issue by r4fx** [umap-project/umap#258]
Hello,
it seems that "onLoadPanel" parameter doesn't work,

my test map: http://umap.openstreetmap.co/en/map/zmid-test_443?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=false&datalayersControl=true&onLoadPanel=caption#15/52.3248/20.9466

**Comment by yohanboniface** [comment]
Seems fixed on the master: http://umap.fluv.io/en/map/korongmenyala_204?onLoadPanel=databrowser#17/-27.57372/153.06393 vs http://umap.fluv.io/en/map/korongmenyala_204?onLoadPanel=caption#17/-27.57372/153.06393 (demo site)

Should be good next time this instance will be updated :)

**Comment by r4fx** [comment]
cool, when do you plan to update live version ?
