### ISSUE TITLE
datalayer shows by url parameter

### ISSUE THREAD

**Issue by r4fx** [umap-project/umap#259]
Is there possible to show data layer through URL param?

for example by adding `&datalayer=865` to the url

**Comment by yohanboniface** [comment]
Yes, use the iframe exporter where you can choose to "show only current visible layers" that will add the current visible layers in the URL, and take the URL from there. I'll add an URL export too to make this easier.

**Comment by r4fx** [comment]
Unfortunately, I do not see "show only current visible layers" option in iframe exporter

![iframe-export](https://cloud.githubusercontent.com/assets/4216415/11608853/ea17b6fe-9b75-11e5-94e1-4e33a89c7c73.png)

**Comment by Agamitsudo** [comment]
@r4fx hi :)
Did you get an answer to your question. I'd like to do exactly the same...

Thanks.

**Comment by Agamitsudo** [comment]
Actually seems &datalayers=layer_id works. But I don't see how to know every layer_id...

**Comment by r4fx** [comment]
Nope, I don't get any feedback..

**Comment by yohanboniface** [comment]
Which umap instance are you using? On http://umap.openstreetmap.fr, it's there:

![screenshot from 2016-02-21 08-03-30](https://cloud.githubusercontent.com/assets/146023/13201430/b3eec840-d871-11e5-90d5-7c0d5b574496.png)
