### ISSUE TITLE
Generated map doesn't load anymore

### ISSUE THREAD

**Issue by UniKTHeidelberg** [umap-project/umap#261]
I have generated the following map:
http://umap.openstreetmap.fr/de/map/first-stars-v-restaurant-guide-2016_49273#17/49.41149/8.70230

The map background doesn't load anymore and for some reason I have no access to this map via my account (UniKTHeidelberg) anymore. Is there a way to fix the map and make it available to my account again? I've tried to export the data and import it to a new map but a lot of the information of the old map is missing.

**Comment by grandbic** [comment]
Bonjour,
If it can help, your map dosn't stop charging, but I can see it if I clic on "change the map base option".
I can also see blue icones on your map with UniKTHeidelberg .

**Comment by UniKTHeidelberg** [comment]
The problem is that this map is supposed to be published for many users to use on their smartphones on the road. So it would be necessary that the map background appears automatically. 
The other map with the blue icons is a new version I recreated from exported date - but it's not helpful since the main information cannot be exported to the new version. 

I need to make the old version function again.

**Comment by yohanboniface** [comment]
I guess we can close since then. Sorry for not answering at that time!
