### ISSUE TITLE
Search location on map

### ISSUE THREAD

**Issue by orschiro** [umap-project/umap#262]
Dear all, 

I might have overlooked something but I miss the feature to search for a location on a custom umap. 

Example use case: 

I want to add a pointer on my map that matches the location `Strotzbüscher Mühle 54552 Strotzbüsch`. Since it is a very small place, it's very difficult to find it manually by scrolling and zooming the map. 

How could I improve my workflow? 

Would searching by location be an option that could be added to umap?

Thankfully

~ Robert

**Comment by yohanboniface** [comment]
Will be available in next version. Live soon.

**Comment by orschiro** [comment]
Thank you! :-)

**Comment by githubuser0535** [comment]
Was the search for a custom location feature released? 
Many thanks.
