### ISSUE TITLE
Loss of anonymous link

### ISSUE THREAD

**Issue by didnight** [umap-project/umap#263]
Hello,

Briefly, i work for a NGO and we had ask to our intern to create a map with Umap. But just before he finish his internship, he has cleaned the browers history. I discovered he didn't use account, only cookie.
Apparently he add some personal data on the map, and the map is public.

So now, we dont have the link, no cookie, i cant edit the map and personals data are on the web.

How i can proceed for recovered rights for editing the map?

**Comment by yohanboniface** [comment]
Send me an email ybon at openstreetmap dot fr with map URL, I'll see if I can do something.
