### ISSUE TITLE
Can't apply full opacity to a vector polygon

### ISSUE THREAD

**Issue by JeremyG** [umap-project/umap#266]
Hi,
I'm trying to apply full opacity to a vector polygon drawn into umap (opacity=1.0), but the polygon remains a little transparent. Any hint?
Thanks!
Jeremy

**Comment by yohanboniface** [comment]
What's the map URL?

**Comment by JeremyG** [comment]
umap.openstreetmap.fr/it/map/mc3-urban-projects_64062

**Comment by yohanboniface** [comment]
Seems like the italian translation have messed up the "opacity" thing: you have twice "opacità", while should should have "opacità" and "opacità del riempimento" or something like that. So either switch to English or just fill in both "opacità" and it will work as expected.

**Comment by JeremyG** [comment]
You get it, thanks. Might be good considering a clear labelling and division of the stroke and fill attributes in the panel? Hope it helps!
Best
Jeremy
