### ISSUE TITLE
Installing umap - how to logon to admin?

### ISSUE THREAD

**Issue by plepe** [umap-project/umap#267]
In the README there's written that I need to go to the admin-page during the install process. How to create an admin account? Are there any default credentials? I would be good to include this in the installation instructions ...

**Comment by yohanboniface** [comment]
Good catch, fixed, thanks :)

**Comment by plepe** [comment]
Thanks!

**Comment by ChildApple** [comment]
The docs still dont show the default password when creating a docker instance. How do you figure out what the password is?

**Comment by davidbgk** [comment]
@ChildApple there is still no default password, that's when [you run the `createsuperuser` command](https://umap-project.readthedocs.io/en/master/docker/#create-superuser) that you'll be prompted.
