### ISSUE TITLE
Limit/control account creation

### ISSUE THREAD

**Issue by plepe** [umap-project/umap#268]
I'm looking into using umap as tool for an organization (a local bicycle activist group) and I'm not really happy with the current authentication system:
- Is there a way to restrict new user registration, e.g. moderator needs to create account or moderator approval? I found the account management page in the admin area ...
- Is there a possibility to log on to local accounts? (like on the /admin page)

I guess I'll look into Django documentation in the upcoming days :-) (Never used it before)

**Comment by yohanboniface** [comment]
Keep in mind that uMap is "just" a Django project wrapper around django-leaflet-storage and leaflet.storage.
Basically, it adds home page, search, authentication, a bit of CSS. So, depending on the balance between what you want to keep as is and what you want to customize, you may just want to create new django project. You'd not have that much to code, as you can see looking at the uMap code.

Also, have a look at python-social-auth, to see if some settings can help you keeping social login while deactivating account creation.

**Comment by yohanboniface** [comment]
@plepe did you finally manage to control registration ? I guess since then I can close. Please reopen if you need!
