### ISSUE TITLE
List of public maps

### ISSUE THREAD

**Issue by plepe** [umap-project/umap#269]
Is it possible to list all public maps on the front page? Would it be possible to filter this list by certain criteria?

**Comment by yohanboniface** [comment]
> Is it possible to list all public maps on the front page?

Humm, isn't what the home page is already doing? :)

> Would it be possible to filter this list by certain criteria?

You want like an advanced search?

**Comment by plepe** [comment]
Apparently it does, the problem was that I haven't updated the center position of my map. Therefore the following query excluded the map:
```python
qs = qs.filter(center__distance_gt=(DEFAULT_CENTER, D(km=1)))
```

Is there a special reason for this query? I guess the reason is to exclude unused maps?

**Comment by yohanboniface** [comment]
Ah, yeah, sorry, forgot to warn you about this.

>  I guess the reason is to exclude unused maps?

Yes, that was the easiest trick to exclude from the home page all the "default map" from people only creating it, without doing any thing more. The idea is to have a set of "nice" maps on the home, not all the maps without distinction.
This check could be made configurable without issue, though, if you prefer to have all the maps.

**Comment by plepe** [comment]
I see. As you might have noticed I already introduced a configuration setting (#270), I hope it suits you (if not, I can update it).

As far as I understand Postgis, the above query is not performant though, as indexes can not be used for function results (like ST_Distance). Why not compare the values as they are? I don't think that you should have any problems with floats ...

**Comment by yohanboniface** [comment]
Closing as now uMap sets the center and zoom at first map save, so there is no more real needs for this filter.
