### ISSUE TITLE
introduce a way to switch easely between a subset of map background

### ISSUE THREAD

**Issue by niconil** [umap-project/umap#272]
recently in umap.openstreetmap.fr the IGN aerial view (aka GeoPortail) was added
it's a GREAT NEWS !! ans thanks a lot for that !!

Now in the map, i would like to let the user to switch between a subset of map background
by exemple switch between 'osm-fr' and 'IGN'
with a button directly visible on the interface

today is possible
but
- you cannot select which map background subset 
- the button is not directly visible on the map (you have to click three times or more)

**Comment by yohanboniface** [comment]
Closing in favor of #1814, which is more up to date.
