### ISSUE TITLE
Import data from Wikipedia table?

### ISSUE THREAD

**Issue by orschiro** [umap-project/umap#275]
Dear all, 

Is it possible to import data into a map from a Wikipedia table?

Thankfully,

~Robert

**Comment by yohanboniface** [comment]
I don't know this format, can you point me to some description and example about it?

**Comment by orschiro** [comment]
Dear @yohanboniface,

Thanks for your quick reply!

I would like to import [this](https://en.wikipedia.org/wiki/User:Orschiro/SCORAI/Sustainable_Consumption_Teaching) table into [this](http://umap.openstreetmap.fr/de/map/scorai-sustainable-consumption-teaching-map_60282#6/47.525/18.995) map. 

Any ideas?

~Robert

**Comment by yohanboniface** [comment]
Humm, but this table is missing geographical information. You need to geocode this data first in some way.

**Comment by orschiro** [comment]
Dear @yohanboniface,

Thank you! Let's assume I have added the geographical information to the table. 

Is there then a way to transfer this table to uMap?

~Robert

**Comment by yohanboniface** [comment]
Yes, copy-paste it in a spreadsheet editor (it should respect the table formatting) and save it as CSV, then import it as CSV from uMap.

**Comment by orschiro** [comment]
Great, thank you!

So, the solution is handling file transfers as `.csv`. :+1:
