### ISSUE TITLE
Some noob questions

### ISSUE THREAD

**Issue by hoeschstahl** [umap-project/umap#276]
I use umap for some weeks now for a large project. All major industrial sites of the Ruhr area in 1952. That will be around 1500 areas and another 1500 pois.
Questions
1: Is there a limit (data volume or number of pois)?
2: Each time I log in my map is focussed on the far right corner, how do I get an overview as a start ?
3: The zoom function ain't clear to me, how does it work ?
4: How do I choose a license ? It always says "no license chosen" but gives no choice.
5: The filter/search function does not work, if I type in a term in the data overview it only returns to the layer overview. Do I have too many areras and pois already ?
6: Can I store a custom icon design in the icon list ?

Thank you very much for any answers.

Uwe

**Comment by yohanboniface** [comment]
> 1: Is there a limit (data volume or number of pois)?

Fair use limit, depending on who hosts the uMap instance you are using. Plus browsers limit (thousands of points will hurt some browsers).

> 2: Each time I log in my map is focussed on the far right corner, how do I get an overview as a start ?

Don't the question, sorry.

> 3: The zoom function ain't clear to me, how does it work ?

Humm, click on "plus" button, it zooms in; click on "minus" button, it zooms out?

> 4: How do I choose a license ? It always says "no license chosen" but gives no choice.

Edit the map properties (gear icon).

> 5: The filter/search function does not work, if I type in a term in the data overview it only returns to the layer overview. Do I have too many areras and pois already ?

Don't get it. May be a bug. Can you open a dedicated issue with more details (how to reproduce, browser used, map URL, etc.)?

> 6: Can I store a custom icon design in the icon list ?

Not yet, but planned, see #125 for example.

**Comment by hoeschstahl** [comment]
Hi, thanks for the fast reaction.
This is  the map, its about half finished:
http://umap.openstreetmap.fr/de/map/industrie-ruhrgebiet-1952_62895#13/51.5162/7.2596
runs well on my browser

I have attached some screen shots to explain my problems (german version).
