### ISSUE TITLE
[wishlist] Search also in description field

### ISSUE THREAD

**Issue by mikejpr** [umap-project/umap#278]
I would like that the "Filter"-Box not only search in the name field but also in the description field.

For exemple we can solved them with a check box and a text like "search also in the description" so that if the user wants he can search including the description field of the marker.

**Comment by mikejpr** [comment]
Maybe the feature is not enought clear what I mean.
I put into the description field historical name of place. 
For example "Quenvel" is the actually used name of a place. But if I search for "Kenvel" or "Kervel" I don't have a result because umap don't search this information from description field.
Thx.
https://umap.openstreetmap.fr/fr/map/carte-historique-de-la-presquile-de-crozon_57712

**Comment by yohanboniface** [comment]
You can add how many properties in the "filters" advanced setting (through the gear symbol).

For example:

`name,description,otherfield`
