### ISSUE TITLE
more graceful error handling for dynamic remote data source, including error messages

### ISSUE THREAD

**Issue by ckhung** [umap-project/umap#280]
It's quite difficult to figure out what's wrong with a layer that's connected to a remote data source. Can we have more detailed error messages when umap fails to parse the remote url? BTW, this map with remote url seems to stuck in an infinite loop and therefore does not even produce an error message:  https://umap.openstreetmap.fr/zh-tw/map/map_68900 When the browser opens this map, the cyan line on the top keeps running and I cannot even edit it to change its remote url data source. Presently its data source is actually a static geojson generate by a php script: http://v.im.cyut.edu.tw/~ckhung/z/exp/osmtwed.php

Thank you for your great work, @yohanboniface!

**Comment by ckhung** [comment]
I am not sure whether I should open a new ticket. I have removed the data source file but this map (68900) still fails to open. Even simply deleting the map or deleting the layer seems impossible. I hope it's not eating up too much CPU cycles of umap.openstreetmap.fr .

**Comment by yohanboniface** [comment]
Seems fixed on the given map, closing. Please reopen if needed.
