### ISSUE TITLE
"Invalid JSON file: Syntax error: Unexpected token <"

### ISSUE THREAD

**Issue by govvin** [umap-project/umap#281]
I'm trying to load data by remote URL from Github (tried it with repo and gist, same results):
`http://umap.openstreetmap.fr/en/map/new/?dataUrl=https://github.com/OSMPH/events/blob/master/calendar.geojson&dataFormat=geojson
`

but get the following error:
`"Invalid JSON file: Syntax error: Unexpected token <"` 

Curiously, github and geojson.io renders the geojson file correctly.

**Comment by yohanboniface** [comment]
Not sure you can use the github front URL like this, have you tried with raw? But afaik they force content-type to text, so not even sure it will work.

**Comment by govvin** [comment]
@yohanboniface 

Raw. That's it. Feeding it the the raw file works. Thanks.
