### ISSUE TITLE
CSV import could be more permissive on invalid rows

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#285]
Importing a CSV file where only a few rows have an invalid lat/lon currently refuses to load any data at all. It would be helpful to let it load those rows that are valid, and just show a warning that the file import is incomplete.

Attached is an example file (renamed to .txt to allow attachment), where the 5th row has no lat or lon.
[file_import.txt](https://github.com/umap-project/umap/files/134325/file_import.txt)

Cheers,
Antoine.

**Comment by yohanboniface** [comment]
True! :)
