### ISSUE TITLE
broken github connection

### ISSUE THREAD

**Issue by zpartakov** [umap-project/umap#287]
hello

trouble: when I try to connect to https://umap.openstreetmap.fr/fr/ with my github account (zpartakov) I get a 404... 

any idea? 

it's a problem because I wan't to edit asap the map http://umap.openstreetmap.fr/fr/map/acpch_6509#9/46.6098/6.8939 which is usefull - no, vital - to participative website http://acpch.ch/; if I try to connect with my openstreetmap account umap says to me that I have... no map!

thank you in advance & a big "bravo" for your excellent software

fred radeff aka zpartakov (https://github.com/zpartakov)

**Comment by yohanboniface** [comment]
Try with http instead of https.

**Comment by zpartakov** [comment]
thank you so much... I'm such a dummy not finding it!
works perfectly
