### ISSUE TITLE
Allow editing of layers, but not maps

### ISSUE THREAD

**Issue by sylvain-m** [umap-project/umap#288]
In a logic of participatory mapping, contributors are able to add data to a layer, but only the administrator should be able to change the interface (map title, legend, explanations ...).
Also, I suggest the distinction of managing the editing rights on the layers (or even for each layer, but this has already been proposed), that on editing maps rights.

Thank you if this feature can be added.

(And congratulations for this wonderful tool!)

Sylvain M.

**Comment by yohanboniface** [comment]
I'll work on this. See #584 for a recent discussion on the topic.
