### ISSUE TITLE
map becomes uneditable when using placeholers in symbol url and adding a new pointer

### ISSUE THREAD

**Issue by squiddle** [umap-project/umap#292]
If a symbol url is defined in layer settings or whole map settings which uses placeholder you cannot add new points anymore.

Looks like it trips over the fact, that the newly added point does not have value for the placeholder yet.

**Comment by yohanboniface** [comment]
Should have been fixed by https://github.com/umap-project/Leaflet.Storage/commit/e915d445143c461f18d1588f50dc6209e37260e8 (which is not yet in http://umap.openstreetmap.fr but soon).
