### ISSUE TITLE
Text formating in description field from about don't work

### ISSUE THREAD

**Issue by mikejpr** [umap-project/umap#293]
The text formating like
`Link with text: [[http://example.com|text of the link]]`
doesn't work in the description field from the "about" part.

You can see them here for the moment:
http://umap.openstreetmap.fr/en/map/carte-historique-de-la-presquile-de-crozon_57712#13/48.2574/-4.5085

**Comment by yohanboniface** [comment]
Sorry, missed that issue :(
You mean on each layer description?

**Comment by mikejpr** [comment]
Sorry I not sure that this is the layer description. I mean the part from "About" ("Légende"). When I try to use the link with text it doesn't work but show only the code. It would be very nice if this bug can be resolved :smile:

**Comment by yohanboniface** [comment]
It's fixed in master yet, and will be live in next release (soon!).
See an example in the demo site (up to date): http://umap.fluv.io/en/map/untitled-map_3360
