### ISSUE TITLE
Unique marker url

### ISSUE THREAD

**Issue by Cyrille37** [umap-project/umap#294]
Hi
Is there a way to get unique POI (marker, trace) URL ?

I had a look in slideshow mode but did not see unique url, but only datalayer url like "/en/datalayer/{pk}/"
It should be nice to have direct link on one POI (to retrieve one POI data).

Cheers

**Comment by sebastianludwig** [comment]
Any updates on this?

**Comment by TZornG** [comment]
I'd like to second this request. Please provide a link with with I can zoom the map to a specific object and open the respective popup.

**Comment by kasanova123** [comment]
Is there any alternative mapping possibility to solve the prob with unique marker URL?

**Comment by Binnette** [comment]
@kasanova123, no i don't think so. Until now, the best think you can do is to set the zoom/latitude/longitude in URL like so :

- https://umap.openstreetmap.fr/en/map/la-dorne_391480#16/44.8675/4.3617
- https://umap.openstreetmap.fr/en/map/la-dorne_391480#16/44.9675/4.4617

As you can see, those links open the same uMap but in differents places.

**Comment by gislars** [comment]
If I have multiple POI at one location at a clustered layer, I can open the permalink, but the popup doesn't open. Would this be a bug, should I file an issue?

For example you can have a look at http://umap.openstreetmap.fr/de/map/glutenfree_6373
