### ISSUE TITLE
Restore to a previous saved state of the map (history system)

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#299]
Hi

This is a feature request : maps should have a *minimal* history system. You should be able to save a the state of a map, make changes, and restore the previous saved state of the map.

For now, if you get your map just right, then mess it up accidentally, you can't revert it. You have re-do all the work. Same thing if someone else vandalize your map.

This could be done like in Etherpad : every change isn't revertable and isn't saved in a proper history, but users can create "saved revision" of their work and revert back to it when needed.

Cheers

**Comment by yohanboniface** [comment]
That's already the case in the future release (see https://framacarte.org which runs the beta): you can restore previous layer versions :)
