### ISSUE TITLE
when you change your name (aka) in OSM settings, there's no change in umap

### ISSUE THREAD

**Issue by vinber** [umap-project/umap#302]
Example for the same account :
- umap : vinber-inli
- OSM : vinber-num&lib

**Comment by yohanboniface** [comment]
Yes, we need a way for a user to resync with an auth provider. See also #7

**Comment by vinber** [comment]
Thanks, I haven't seen this issue (#7) and I didn't know it was "same" kind of issue :(

**Comment by datendelphin** [comment]
Ah I see this is already reported. Just got a similar question from a user.
For the changing osm user names, I think from OSM the user Id should be saved, because that one is stable.

**Comment by siSSSou** [comment]
This feature (sync uMap account name with OSM account name) would be valuable.
Our corporate structure has changed its name (a ministry) and our maps can't be updated !

**Comment by Binnette** [comment]
Fixed by #754
