### ISSUE TITLE
Fullscreen option for embedded Map

### ISSUE THREAD

**Issue by SultanMaz** [umap-project/umap#303]
Hi,

I'm looking for a way to let the users enlarge the embedded Map (iframe) into Fullscreen within the iframe. 
I only have an url under the map directing to the main umap website to show the fullscreen map, but I would like to let my users stay on my website.

Is that somehow possible?

This is my website, so you can understand my question better:

[http://syriancivilwarmap.com/](url)

Thanks for any help.

Regards,
Sultan

**Comment by yohanboniface** [comment]
No, that's not possible right now. But I'll will add that button.

**Comment by SultanMaz** [comment]
Thanks! That would be awesome.

**Comment by yohanboniface** [comment]
Fixed with https://github.com/umap-project/Leaflet.Storage/commit/db58ea56e562b7662345a052637240f03f9384a4
