### ISSUE TITLE
Optimize way to exclude default maps in home page

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#310]
Try to do an exclude without the need of reprojecting.

Here is the current SQL:

```sql
SELECT
    *
FROM
    "leaflet_storage_map"
WHERE
    ("leaflet_storage_map"."share_status" = 1
    AND ST_Distance("leaflet_storage_map"."center", ST_GeomFromEWKB('\001\001\000\000 \346\020\000\000\000\000\000\000\000\000\000@\000\000\000\000\000\200I@'::bytea)) > 1000.0) 
ORDER BY
    "leaflet_storage_map"."modified_at"
DESC LIMIT 50
```

**Comment by cquest** [comment]
You can add the following specialized index to speed up that request and its sister with count(*):

`create index leaflet_storage_map_optim on leaflet_storage_map (modified_at) WHERE ("leaflet_storage_map"."share_status" = 1  AND ST_Distance("leaflet_storage_map"."center", ST_GeomFromEWKT('SRID=4326;POINT(2 51)')) > 1000.0);`

On a 80000+ maps umap instance it is 200x faster (less than 1ms). Home page rendering time got divided by 2.
The index is set on modified_at to allow the ORDER BY / LIMIT to take advantage of it too.
