### ISSUE TITLE
gdrive csv remote layer: in this moment it does not work

### ISSUE THREAD

**Issue by aborruso** [umap-project/umap#312]
Hi,
I have a lot of maps that use gdrive csv as source, and in this moment they not work.

This is the map:
[http://umap.openstreetmap.fr/it/map/referendum-popolare-sulla-durata-delle-trivellazio_81115](http://umap.openstreetmap.fr/it/map/referendum-popolare-sulla-durata-delle-trivellazio_81115)

This is the CSV URL:
[http://spreadsheets.google.com/tq?tqx=out:csv&tq=select%20A%2CB%2CC%2CD%2CE%2CF&key=12xt8Z_zZji2nu9v275hHdbRF9HcaDQjRTqd-hADnWFw](http://spreadsheets.google.com/tq?tqx=out:csv&tq=select%20A%2CB%2CC%2CD%2CE%2CF&key=12xt8Z_zZji2nu9v275hHdbRF9HcaDQjRTqd-hADnWFw)

Is there something that does not work in this moment?

Thank you

**Comment by yohanboniface** [comment]
We have made some updates on the server. I'm having a look right now.

**Comment by cirospat** [comment]
yes I'm having same problems using gdrive csv as source for uMap

this is the Map:
http://umap.openstreetmap.fr/it/map/sicilia-sicily-cluster-bio-mediterraneum-sme_44048

This is CSV URL:
https://docs.google.com/spreadsheets/d/14s-p6NbbSLDJQYk-X9IyWLcTFuBZZ1wXe1gRlwdwi7g

**Comment by aborruso** [comment]
Thank you @yohanboniface

**Comment by cirospat** [comment]
thanks you @yohanboniface for the prompt service
so many maps on uMap with data coming from csv on GDrive
thanks very much

**Comment by yohanboniface** [comment]
Should be back working, even if not proxied through Nginx right now, so we will certainly make some new tries in the incoming days/weeks.
You know where to find me if we break it again without noticing it :p

**Comment by yohanboniface** [comment]
@aborruso quand'è che facciamo umap.openstreetmap.it? ;)

**Comment by aborruso** [comment]
Caro @yohanboniface facciamolo!

Please tell me what can we do to achieve this goal and I think we well find the way and the people to do it

**Comment by yohanboniface** [comment]
> Please tell me what can we do to achieve this goal and I think we well find the way and the people to do it

A server to run a debian/ubuntu on it, and either someone to install the soft on it, or an access so I can do it :)

Ideally, you'd want a server that is backuped, in case of failure somewhere, it's better to have a backup (as we have in umap.openstreetmap.fr or framacarte.org)

**Comment by stevevance** [comment]
It seems like if you try to call Google Docs directly, they fail to load on the map. This happens in Safari, and not Chrome. 

This is happening on the [Shareable Chicago map](http://umap.openstreetmap.fr/en/map/shareable-chicago_80079#15/41.9446/-87.6738). Open that in Safari and open the inspector and you'll see this error:
````
XMLHttpRequest cannot load https://docs.google.com/spreadsheets/d/18Pu4o9tamgTDQHpjkOma7hzBiOMpiXz0yGw-AM0eK04/gviz/tq?tqx=out:csv&tq=SELECT+A,+B,+F,+C,+H,+J,+X,+Y+WHERE+I+CONTAINS+'yes'+AND+(H+CONTAINS+'Housing+Coop'+OR+H+CONTAINS+'Group+Home')&gid=0. Cannot make any requests from null.
````

**Comment by cirospat** [comment]
I'm having the same problem now, please can you have a test (try)?

**Comment by yohanboniface** [comment]
Are you loading the map in http or https?

**Comment by cirospat** [comment]
Sorry it was a my problem now solved.... Thanks

ciro spataro
cirospat@gmail.com
umap.openstreetmap.fr/it/user/cirospat
petrusino.opendatasicilia.it
twitter.com/cirospat

Il 04/ago/2016 05:45 PM, "Yohan Boniface" <notifications@github.com> ha
scritto:
