### ISSUE TITLE
Change Tilelayers broken

### ISSUE THREAD

**Issue by nordbit** [umap-project/umap#319]
In newest version from repository "Change Tilelayers" do not work anymore, after clicking on icon nothing happens, panel with tilelayers do not slide from right

**Comment by yohanboniface** [comment]
Can you try with that commit: https://github.com/umap-project/Leaflet.Storage/commit/9f6adc176603485da9faf419a6b3ba5fa83703c7 ?

**Comment by nordbit** [comment]
It working now .Thank You.
