### ISSUE TITLE
django 1.9 and changes in ETag

### ISSUE THREAD

**Issue by nordbit** [umap-project/umap#320]
![error](https://cloud.githubusercontent.com/assets/1248229/14861459/9fc34632-0cad-11e6-8cf9-55a61844e9e9.png)
Sometimes, after update map i got this error.
If I remember correctly, there are changes in code from django 1.8 -> 1.9 about checking ETag

**Comment by yohanboniface** [comment]
Yes.
I've hack locally for that. I need to find a proper solution.
The Django behaviour is weird to me.
Basically, in https://github.com/django/django/blob/master/django/middleware/http.py#L24 Django take the **response** ETag, and later in https://github.com/django/django/blob/master/django/utils/cache.py#L133 it compares it with the **request** `If-Match`.
But given that the request was a POST, the response ETag has changed (the resource changed), and thus does not match anymore. That's expected. What's weird to me is Django comparing the response new ETag with the request If-Match **after** the response has been processed.
Plus, returning a **pre*condition failed **after** the response is processed sounds not very logical to me.
Anyway, I'll see how to prevent this cleanly.

**Comment by yohanboniface** [comment]
Removing `django.middleware.http.ConditionalGetMiddleware` from the middlewares "fixes" the issue, but I'd like to understand a bit better what's going on before committing that.
I don't think we are using it anyway at this point.

**Comment by yohanboniface** [comment]
I wonder why there is not check about the request verb in there https://github.com/django/django/blob/master/django/middleware/http.py, as I understand it, it should be called only for GET requests.

**Comment by nordbit** [comment]
Talk to guys who changed code in django. Can it be a bug?

**Comment by yohanboniface** [comment]
We are now close to Django 3.0 and I've seen no new complaints about this, so let's assume it's an issue from the past. ;)
