### ISSUE TITLE
All kinds of issues with javascript variables set to Null

### ISSUE THREAD

**Issue by vectorien** [umap-project/umap#322]
Hi I have installed umap and many things (django admin ) work, but in the main map view, the right hand editing panel is totally unreactive. 
A quick firebug look gave all kinds of errors like

`storage.ui.default.js:13 Uncaught TypeError: Cannot set property 'className' of null
storage.ui.default.js:126 Uncaught TypeError: Cannot read property 'clientWidth' of null
storage.ui.default.js:13 Uncaught TypeError: Cannot set property 'className' of null
storage.ui.default.js:126 Uncaught TypeError: Cannot read property 'clientWidth' of null
storage.ui.default.js:13 Uncaught TypeError: Cannot set property 'className' of null
storage.ui.default.js:126 Uncaught TypeError: Cannot read property 'clientWidth' of null`

Any pointers? (I am not a web dev ..;-))

**Comment by yohanboniface** [comment]
How have you installed umap?

**Comment by vectorien** [comment]
cloned from github. Deployed with gunicorn on Centos

**Comment by yohanboniface** [comment]
Have you installed latest statics Leaflet.Storage and requirements, or are you just running the ones coming with django-leaflet-storage?

**Comment by vectorien** [comment]
just the django-leaflet-storage

which ones are recommended?

**Comment by yohanboniface** [comment]
Given you say you "are not a webdev", I'd suggest using the 0.7.6 tag of umap, running again `pip install .` to have the proper django-leaflet-storage version too.

The other option is to install all master versions (including Leaflet.Storage and requirements), but that's sort of the north face if you are not used to that.
