### ISSUE TITLE
Option to open links in "_parent" target instead of "_blank" for easier iframe integration

### ISSUE THREAD

**Issue by nouser2013** [umap-project/umap#323]
Dear dev's,

for easier iFrame integration I'd like to be able to set the target property of outgoing URLs. On my webpage, I currently have an interactive map with several areas. Upon clicking, a link such as `www.mydomain.com/deep-link#area_1` is opened; the browser scrolls down to the respective anchor.

Unfortunately, it always opens in a new window. I'd like to open in "_parent" to hint to the browser to simply scroll instead of loading the whole page again, even over cross-origin.

Thanks.

**Comment by yohanboniface** [comment]
Would allow anchor values only in the link be an option? In other words:
- if the link starts with http:// => open in a new window
- if the link starts with '#' => open in the same window

It would be a bit implicit, but we already have a bunch of options in uMap, and I'm not sure this needs a new one.

**Comment by yohanboniface** [comment]
Of maybe `link domain == current domain` => same window?

**Comment by nouser2013** [comment]
> Would allow anchor values only in the link be an option? In other words: [...]

Well, functionality-wise, yes, of course. You could also directly parse the `target=""` value from the textbox like so:

* _parent:http(s)://...
* _blank:http(s)://
* _self:http(s)://

> Or maybe link domain == current domain => same window?

Nope, due to x-origin restriction you have no way of determining where the map is viewed: you cannot say if it's stand-alone in a separate tab/window or within an iframe on a parent page. Your condition would likely never match since you probably don't want to link to uMap in most cases.

**Comment by yohanboniface** [comment]
> Nope, due to x-origin restriction you have no way of determining where the map is viewed

Good point!

> You could also directly parse the target="" value from the textbox

I'll think about that option.

**Comment by nouser2013** [comment]
Alright, thanks. I'd be very nice to have it, here's the (German) web page I'd like to use it in: http://www.pro-fuerstenried.de/2016/05/oekologie-im-viertel-ein-gastbeitrag/

Click on a green area on the map and jump down to the appropriate detailed description...

**Comment by tourenfex** [comment]
Is there an solution for this problem?

**Comment by nouser2013** [comment]
@yohanboniface with regard to your other comment in #349 (bottom):

> There is not way to change that behaviour for now sadly. I've looked at it, and it's not that easy given the action is made in javascript (it's not a real HTML link), and thus there are restriction for an iframe to communicate with parent.

As I don't know how exactly the links are created or what happens when you click on the overlay elements, here are the two ways that seem to work according to community:

### Redirect iFrame parent by clicking anchor link inside:

http://stackoverflow.com/questions/1037839/how-to-force-link-from-iframe-to-be-opened-in-the-parent-window

1. add ```<base target="_parent" />``` to top of the page within the iFrame; this changes all links within the iframe to load in the parent window, *or*
2. add ```target="_parent"``` to a single anchor tag. This changes just the respective link.

### Redirect iFrame parent by javascript call:

http://stackoverflow.com/questions/580669/redirect-parent-window-from-an-iframe-action

1. exchange the  ```window.location = ...```-call with ```window.top.location.href = ...```. This will load the URL in the iFrame's parent window. No restriction.

### Determine when to load content in parent window

Well, see https://github.com/umap-project/umap/issues/323#issuecomment-216112555 for the suggestions already given...

**Comment by yohanboniface** [comment]
> exchange the window.location = ...-call with window.top.location.href = .... This will load the URL in the iFrame's parent window. No restriction.

Is http://jsfiddle.net/ppkzS/ working for you?

**Comment by yohanboniface** [comment]
It's actually working if I try it in uMap:

http://umap.openstreetmap.fr/en/map/demo_1#12/53.2397/9.0308

I'll investigate a bit more and have a try. Need to find the right format syntax though.

**Comment by tourenfex** [comment]
Yes, this would solve my problem!


This is my map: http://umap.openstreetmap.fr/de/map/webcams_98826#10/46.8405/12.6755


The links should open in the same (_parent) window.


________________________________
Von: Yohan Boniface <notifications@github.com>
Gesendet: Samstag, 20. August 2016 09:09
An: umap-project/umap
Cc: tourenfex; Comment
Betreff: Re: [umap-project/umap] Option to open links in "_parent" target instead of "_blank" for easier iframe integration (#323)


It's actually working if I try it in uMap:

http://umap.openstreetmap.fr/en/map/demo_1#12/53.2397/9.0308

I'll investigate a bit more and have a try. Need to find the right format syntax though.

-

**Comment by yohanboniface** [comment]
Will be in next release only.
Looks like this:
![screenshot from 2016-08-20 11-12-35](https://cloud.githubusercontent.com/assets/146023/17830263/4e43f86e-66c7-11e6-8b86-3ae66bc01f47.png)

**Comment by tourenfex** [comment]
Perfect! Thank you for your great job! When will be the next release approximately?

**Comment by nouser2013** [comment]
Thanks. Looks perfect. Can't wait to try it out...

**Comment by tourenfex** [comment]
hey guys, when will be the next release? i would need this option as soon as possible.

**Comment by ne0guille** [comment]
any news on this?

**Comment by tourenfex** [comment]
the above option is still missing in the new release. what is the reason?

**Comment by yohanboniface** [comment]
> the above option is still missing in the new release.

You meant "I can thing this option in the new version, am I not looking at the right place?".
So when you edit a polygon (only polygons have outlink), you should have both the outlink property and the way to define how the link should behave.

**Comment by tourenfex** [comment]
Is it possible to get this option for markers too?

Thank you for your help!



Von: Yohan Boniface [mailto:notifications@github.com]
Gesendet: Sonntag, 2. Oktober 2016 22:02
An: umap-project/umap
Cc: tourenfex; Comment
Betreff: Re: [umap-project/umap] Option to open links in "_parent" target instead of "_blank" for easier iframe integration (#323)


the above option is still missing in the new release.

You meant "I can thing this option in the new version, am I not looking at the right place?".
So when you edit a polygon (only polygons have outlink), you should have both the outlink property and the way to define how the link should behave.

**Comment by tourenfex** [comment]
Will this option be implemented for markers too in one of the next updates?

**Comment by servizislovenia** [comment]
hello, any news for this release? thank you!
