### ISSUE TITLE
if locale  {{locale}} not parsed?

### ISSUE THREAD

**Issue by nordbit** [umap-project/umap#324]
```
{% if locale %}
    <script src="{{ STATIC_URL }}storage/src/locale/{{ locale }}.js"></script>
{% endif %}
```
Always generate:
```
 "GET /static/storage/src/locale/%7B%7B%20locale%20%7D%7D.js HTTP/1.1" 404
```
not 
```
"GET /static/storage/src/locale/de.js HTTP/1.1" 200
```

**Comment by yohanboniface** [comment]
That's very weird: STATIC_URL seems parsed.

I'm not reproducing on my side, so hard to investigate.

Which Django and python versions are you on?

**Comment by nordbit** [comment]
Ugh.... my fault.
I replaced {{ STATIC_URL }} with {% static %} tag
Indeed, with {{ STATIC_URL }} it works.
Is there a reason to using {{ STATIC_URL }}? I see it over all templates.

**Comment by yohanboniface** [comment]
>  Is there a reason to using {{ STATIC_URL }}? I see it over all templates.

Old way of doing, before 'staticfiles' get merged into Django. Not sure how to deal with variables in the path when using `static` though, but that should be doable.
