### ISSUE TITLE
feature request - one more template for popup

### ISSUE THREAD

**Issue by nordbit** [umap-project/umap#325]
For now popup have few templates:
1. Name + description
2. Name + description (big)
3. Table
etc...
i miss option:
6. Description (only)
What the point?
Now, if i have no name,  templates 'Name + description/(big)" generate empty tag ```<h3></h3>``` with ```<br>```
and it produce white margin at popup top. If first element of description is image i get unnecessary ugly margin at top.
New template should not generate ```<h3>``` with ```<br>```. I know, my wish is not important, You are busy, but if You can to consider.....

**Comment by yohanboniface** [comment]
You can change the popup content template to include only the description:
```
{{description}}
```

**Comment by yohanboniface** [comment]
Closing as I think changing the popup template is the way to go, please reopen if needed.
