### ISSUE TITLE
Layer button not working with Smartphone

### ISSUE THREAD

**Issue by Dirk71** [umap-project/umap#328]
I can hide and unhide the layers by using a PC or MacBook - no problem. But the Layer-Button is not working in Smartphone Browsers. The button simply has no functionality. Nothing happens when I touch it.

**Comment by yohanboniface** [comment]
Yes, I'll fix that in the incoming version.

**Comment by Dirk71** [comment]
Good to hear! Thank you for your contribution! 👍

**Comment by Dirk71** [comment]
There is a workaround to show layers also on Smartphones! If it doesn't work by touching the Layer-Icon one can touch "About" (in German: "Über") on the right hand buttom corner. Then the menu will show up.

**Comment by Dirk71** [comment]
Hi,
why is it closed? The issue still exists.
Regards, Dirk


Am 22. August 2016 20:54:34 schrieb Yohan Boniface <notifications@github.com>:

**Comment by yohanboniface** [comment]
> why is it closed? The issue still exists.

Closed from a commit, see just above your comment. But not yet released.

**Comment by Dirk71** [comment]
Okay, thank you.


Am 22. August 2016 21:02:24 schrieb Yohan Boniface <notifications@github.com>:

**Comment by Dirk71** [comment]
Hi,

I know that in a former version of umap the distances of the particular routes have been displayed. This is gone and I don’t know when. It would be great if the distances could be displayed without measuring it. Thank you in advance.

Cheers, Dirk

**Comment by Dirk71** [comment]
Hi Yohan,
can you please implement a feature to show the distances of the routes. I 
miss this quite a lot.
Thank you.
Dirk


Am 18. Mai 2016 21:49:16 schrieb Yohan Boniface <notifications@github.com>:
