### ISSUE TITLE
Sidepanel infos not displayed in IE11

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#331]
Hi,

Popup infos won't display under Internet Explorer 11 when using the sidepanel popup template. 

Sidepanel appears, but empty. 

Popup infos do appear when using another popup template.

**Comment by yohanboniface** [comment]
Can you please check on the demo site: http://umap.fluv.io and if there is any error report the console output here?

**Comment by druxstr** [comment]
Still not working. But console doesn't show any error by default (using "Edge" mode).

The debugger stops on this, as an unhandled exception :

> _globalPointerMove [Ligne : 487, col : 716], 53ec23f71b63.js

If I use the "10" mode, the console displays the following errors :

> SCRIPT5007: Impossible de définir la propriété « id » d’une référence null ou non définie
> Fichier : 0d5b0b71ef52.js, ligne : 124, colonne : 362
> SCRIPT5007: Impossible d’obtenir la propriété  « ui » d’une référence null ou non définie
> Fichier : ie-11-testing_3806, ligne : 317, colonne : 9

Then the debugger stops on this :

> Global code [Ligne : 317, col : 9], ie-11-testing_3806

Hope this can help, but I'm pretty close to my technical limits (as I'm no developper).

**Comment by Timbuktu82** [comment]
Hello,

I currently have the same error in IE11. Is this bug possibly still eliminated, or has the support of the IE11 been discontinued? The IE11 is currently still used by many users and thus I have a big problem with the bug.

Thank you in advance

**Comment by yohanboniface** [comment]
Sorry for the veeeeeery late answer, but is that still an issue ?

**Comment by druxstr** [comment]
@yohanboniface I guess this issue can be closed, as IE11 has [mostly](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549) reached end of life. 

Many major applications already dropped support for IE11 back in 2021.

Plus, I don't have any machine running IE11 anymore, so I'm not able to confirm it's still an issue in uMap.

**Comment by yohanboniface** [comment]
:+1:
