### ISSUE TITLE
Contribution financière au projet

### ISSUE THREAD

**Issue by RomainLalande** [umap-project/umap#333]
Bonjour,

Je ne vois nulle part de possibilité de contribution financière au projet Umap. Comme nous commençons à nous en servir dans le cadre d'accompagnement ou de formations que nous facturons, il serait intéressant de pouvoir rétribuer les communautés qui créent les ressources que nous utilisons.

Serait-il envisageable de créer un espace de don HelloAsso ? Une team sur [Liberapay](https://github.com/RomainLalande/Cre-sol/blob/master/utiliser_liberapay_pour_retribuer_des_communs.md) afin de pouvoir faire des dons récurrents ?

A l'écoute de ce que vous en pensez, peu importe l'outil, pourvu qu'il y ai l'IBAN :-) 

Romain

**Comment by yohanboniface** [comment]
Bonjour Romain,

Merci de poser cette question, mais c'est pas si facile d'y répondre. ;) Je vais y réfléchir. :)
Dans tous les cas, il y a un moyen d'aider uMap, c'est de soutenir [Framasoft](https://soutenir.framasoft.org/) ou [OpenStreetMap.fr](https://www.helloasso.com/don/associations/openstreetmap-france) qui gèrent des instances de uMap mises à disposition du public.

Liberapay semble un projet intéressant, libre, basé sur une asso, je vais regarder.

Yohan

**Comment by RomainLalande** [comment]
Hello,

Désoler du délais j'ai raté la notification de réponse. Dans ce cas je passe par OpenStreetMap.fr alors ! 
Merci et au plaisir,

Romain

**Comment by yohanboniface** [comment]
Hop, une team sur Liberapay https://liberapay.com/uMap/

Vieux motard que j'aimais! ;)

**Comment by yohanboniface** [comment]
On a créé une orga dessus, mais à ma connaissance il est encore en modération (depuis 10 jours je dirais). cc @davidbgk qui est peut-être plus à jour vu qu'il était aux manettes ?

**Comment by davidbgk** [comment]
<img width="956" alt="Capture d’écran, le 2023-06-12 à 13 22 39" src="https://github.com/umap-project/umap/assets/3556/ddfc0dad-0b69-4636-80c5-b91c9ebe96d1">

Still waiting…

**Comment by virgile-dev** [comment]
@davidbgk je vous conseille de vous mettre en fiscal hosting chez Open Collective Europe. Je connais bien son directeur, je vous garantit une approbation rapide https://opencollective.com/europe

**Comment by virgile-dev** [comment]
Je peux appuyer votre candidature d'un petit mail :)

**Comment by yohanboniface** [comment]
Sous-entendu la demande qu'on a faite est pour les US ?

**Comment by virgile-dev** [comment]
<img width="368" alt="Capture d’écran 2023-06-14 à 09 21 18" src="https://github.com/umap-project/umap/assets/11473995/b5bfbc83-f1f5-4f2c-8105-31fca261a48a">
https://opencollective.com/opensource#category-ABOUT
C'est fiscal host qui est basé aux US oui. 
Ils peuvent prendre en charge n'importe qui. L'inconvénient c'est que c'est pas pas pratique pour tous les sous qui viendront de l'Europe et de ses Etats membre et qu'ils sont tellement fat que du coup ils sont pas super réactifs.

**Comment by yohanboniface** [comment]
![image](https://github.com/umap-project/umap/assets/146023/2f7e66a9-8c0d-4a35-bf77-afa98ce98a7a)

![image](https://github.com/umap-project/umap/assets/146023/ecd511ee-c58d-404f-baf6-a920a824f20b)

:euro:

**Comment by davidbgk** [comment]
> To receive donations you must connect at least one account from a supported payment processor.

Indeed, thanks for pointing out the issue, we'll configure that 🙇

**Comment by davidbgk** [comment]
@scaidermern it should be “fixed” by now. Thanks!

**Comment by yohanboniface** [comment]
Closed in favor of #1850 and #2002
