### ISSUE TITLE
[wishlist] highlight active marker / polygon 

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#334]
If your map has a lot of markers or polygons, highlighting the selected one could be helpful.
When using the sidepanel, you can't visually get which one is currently selected.

If your map has also multipoints or multipolygons, highlighting seems anoivable : 
otherwise you won't see if a specific element is part of a multi or not.

This could be done by adding a colored border to the element for instance.

**Comment by MIAnalytics** [comment]
This is a really good idea, is this something that could be easily added?

**Comment by yohanboniface** [comment]
Fixed in #1359
