### ISSUE TITLE
Sign-in using github doesn't work

### ISSUE THREAD

**Issue by billboule** [umap-project/umap#337]
- Go to https://umap.openstreetmap.fr/en/
- log-in, choose github, connect to github
- redirect URL after successfull log-in to github send me to an 404-error-page
with this url :
https://umap.openstreetmap.fr/complete/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=JqoDsgBOBjwfAGk1HsBuMXGqZbeX6nCG

**Comment by yohanboniface** [comment]
Issue with 'https'. Try with http.
And see #287 and #221

**Comment by billboule** [comment]
Merci, désolé, j'avais pas vu que le pb était déjà reporté...

**Comment by yohanboniface** [comment]
cf #502
