### ISSUE TITLE
Openstreetmap caps when logging in

### ISSUE THREAD

**Issue by pnorman** [umap-project/umap#338]
umap offers the ability to log in via "Openstreetmap", not "OpenStreetMap"

**Comment by davidbgk** [comment]
This is a configuration from OSM administrators, there is no hard-coded strings of login providers in uMap.

**Comment by davidbgk** [comment]
To be exhaustive, this is indeed in [our code](https://github.com/umap-project/umap/blob/master/umap/templates/registration/login.html#L32), inherited from python-social-auth:

https://github.com/python-social-auth/social-core/blob/master/social_core/backends/openstreetmap.py#L19

Still too much work for an edge case.
