### ISSUE TITLE
export options for embed not working properly after export

### ISSUE THREAD

**Issue by servizislovenia** [umap-project/umap#341]
hello,
when i get the embed to set the map on my website, not all the functions are working, just width and height are been exported, all other functions with "true/false" are not exported after i personalize them, expecially the function for setting the actual zoom of the map. hope you can fix it soon.

thank you!

**Comment by yohanboniface** [comment]
Can you share the iframe code you are using?

**Comment by servizislovenia** [comment]
sure, here you have:

<iframe width="100%" height="545px" frameBorder="0" src="http://umap.openstreetmap.fr/it/map/mangiare-in-slovenia_93304?scaleControl=true&miniMap=false&scrollWheelZoom=true&zoomControl=true&allowEdit=false&moreControl=true&datalayersControl=true&onLoadPanel=none&captionBar=false#10/46.0041/14.0529"></iframe><p><a href="http://umap.openstreetmap.fr/it/map/mangiare-in-slovenia_93304">Visualliza schermo intero</a></p>

**Comment by servizislovenia** [comment]
i actually found out that is missing actually the code "#(level)" for setting the zoom level. so if i write after the url http://umap......... _93304**#8**  it is fixed the level zoom

**Comment by yohanboniface** [comment]
The hash should be added automatically. Which browser and OS (and versions) are you using?

**Comment by servizislovenia** [comment]
i am using mozilla firefox 47.0 on windows 10

**Comment by yohanboniface** [comment]
Is "Current view instead of default map view" checked?

**Comment by servizislovenia** [comment]
I already tried with both solutions, no effect

**Comment by yohanboniface** [comment]
Can you check on the new version? Demo here: http://umap.fluv.io/

**Comment by servizislovenia** [comment]
going to check and answer asap

**Comment by servizislovenia** [comment]
the new version it is offline...

**Comment by yohanboniface** [comment]
Sorry, restarted, should be OK now.

**Comment by yohanboniface** [comment]
I guess I can  close since then. Please reopen if needed.
