### ISSUE TITLE
Inheritance : point popup can't override layer popup

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#342]
Hi. Layer popup still shows when a point popup isn't set on "inherit".

You can't override the layer popup and change popup content for a specific point.

Problem occurs with standard popup and sidepanel.

[See this map for an exemple](https://framacarte.org/fr/map/bug-test_4056#6/47.018/2.549)

**Comment by yohanboniface** [comment]
I'm not sure to understand what you are trying to achieve.
You have set the popup template on the layer level, and this popup template does not load any field (like {description} or {name}).
Can you explain what you are trying to do?

**Comment by druxstr** [comment]
J'essaie d'afficher du contenu dans le popup. Disons par exemple que j'ai 10 marqueurs dans un calque. Pour 9 marqueurs, je veux afficher le même contenu (champs). Pour le 10e marqueur, je veux afficher un contenu différent.

J'ai essayé de faire ça en configurant le popup au niveau du calque (pour les 9 marqueurs avec le même contenu), puis en utilisant le champ description du 10e marqueur. Je m'attendais à ce que la config au niveau du marqueur prime sur celle au niveau du calque.

Mais maintenant je vois pourquoi ça marche pas. Ce qui m'a induit en erreur, c'est le menu "Options du popup". Il permet de changer un élément d'apparence au niveau du marqueur (choisir un popup "bulle" pour ce marqueur, même si le calque est configuré sur popup "panneau latéral"). 

Je m'attendais à pouvoir faire le même genre de manip au niveau du contenu. Pouvoir dire au calque "affiche les champs {description} et {champ_perso1} " et dire à un marqueur "affiche juste le champ {champ_perso2}".

Mais en fait le menu "Options du popup" n'a pas exactement les mêmes options au niveau du calque et au niveau du marqueur. Au niveau du calque il y a un menu déroulant (apparence du popup en gros) + formulaire de texte libre, alors qu'au niveau du marqueur il n'y a que le menu déroulant.

Bref, c'est pas un bug. C'est moi qui ai mal compris le fonctionnement de l'appli.

**Comment by yohanboniface** [comment]
OK, merci, je ferme alors :)
