### ISSUE TITLE
Data disappearing from fluv.io umap

### ISSUE THREAD

**Issue by cgiovando** [umap-project/umap#343]
Hi @yohanboniface - not sure if this is a problem with the particular fluv.io instance or a general umap bug, but I had a layer with ~10 points in this [map](http://umap.fluv.io/en/map/pacdid-kickoff-map_3604#14/-18.1383/178.4405) which now fails to load:

`GET http://umap.fluv.io/en/datalayer/6341/ net::ERR_CONTENT_DECODING_FAILED`

Any clue why this may be happening?

**Comment by yohanboniface** [comment]
Seems to load for me http://umap.fluv.io/en/datalayer/6341/
Any more info to help reproducing?

**Comment by cgiovando** [comment]
Thanks for the quick reply @yohanboniface !

Now I'm suspecting that it may have to do with my current 3G provider here in Fiji. In fact it was working before I left last Friday. I'm not sure though why it would let me view the map, but then block the data source...

Anyway, here's a screenshot of what I'm seeing in Chrome:

<img width="796" alt="screen shot 2016-08-02 at 08 57 57" src="https://cloud.githubusercontent.com/assets/10201533/17308853/1d2deb08-5890-11e6-8bac-37d228d673d9.png">

**Comment by yohanboniface** [comment]
> Now I'm suspecting that it may have to do with my current 3G provider here in Fiji.

Sounds like it is :/
The content is gzipped, so it may be because of that. But that all standard HTTP here, so the 3G provider is to blame certainly (as more or less all 3G provider in the world, France included…).
