### ISSUE TITLE
"Jump to location" button

### ISSUE THREAD

**Issue by YvonAutret** [umap-project/umap#346]
The "Jump to location" button has a strange behavior from my point of view.
The current zoom is modified and that is annoying for me.
For example, when I press then "Jump to location" button
on a Galaxy J1 smartphone, I always get the zoom level #19 
and I must press 5 times the "Zoom out" button if I want to return
to the zoom level #14

**Comment by yohanboniface** [comment]
It's removed on master, and thus will be on next release.
It has been replaced by a proper search box.
