### ISSUE TITLE
Protocol hardcoded in search requests.

### ISSUE THREAD

**Issue by StyXman** [umap-project/umap#348]
I'm accessing umap via HTTPS. When I try to search, I get no results. Looking at my browser's console, I see this:

    Blocked loading mixed active content "http://open.mapquestapi.com/nominatim/v1/search.php?...

I can't find in the app where the search URL is defined, but most probably by removing the `http` part should solve the problem.

**Comment by yohanboniface** [comment]
True!
However the search has been fully refactored in new version (not yet released), and uses Photon now.
URL will be up to the server configuration.

Thanks for the report anyway :)
