### ISSUE TITLE
Open links in _parent instead of _blank

### ISSUE THREAD

**Issue by tourenfex** [umap-project/umap#349]
In Umap I am using [[http://beispiel.com|Text für den Link]] for links. But the problem is that all links are opened in a new blank window. But I want that they are opened in the same (_parent) window. Is there a possibility to change this?

**Comment by yohanboniface** [comment]
Duplicate of #323

**Comment by yohanboniface** [comment]
There is not way to change that behaviour for now sadly.
I've looked at it, and it's not that easy given the action is made in javascript (it's not a real HTML link), and thus there are restriction for an iframe to communicate with parent.
