### ISSUE TITLE
Correct format for URL OSRM layer into Umap

### ISSUE THREAD

**Issue by laraque** [umap-project/umap#352]
Can yours help me to publish an OSM URL directions with the OSRM routing engine into UMap ?

I have the next URL: 
https://www.openstreetmap.org/directions?engine=osrm_car&route=5.71817%2C-72.93340%3B5.71195%2C-72.92650#map=18/5.71619/-72.93029

According to the issue : 6960299

The structure format of the URL must be :
http://www.openstreetmap.org/directions?engine=osrm_car&route={lat},{lng}&locale={locale}#map={zoom}/{lat}/{lng}

So, if, i modify the source URL to the expected format

https://www.openstreetmap.org/directions?engine=osrm_car&route={5.71817},{-72.93340}&locale={5.71195,-72.92650}#map={18}/{5.71619}/{-72.93029}
Looks like is missing the format ending point of the route in the format URL to work inside UMap.

Currently, nothing is showed into the UMap layer using the expected format.

Thanks for your attention,

**Comment by yohanboniface** [comment]
Answered here https://github.com/umap-project/umap/issues/219#issuecomment-242175541

**Comment by laraque** [comment]
Well , i tried the URL suggested with the fixed options .. and again nothing is showed .

I tried in two UMap instances, to see if there are differences in the UMap versions:
-- https://umap.openstreetmap.fr
--  http://umap.openstreetmap.co/es/

Im using the external data option, and OSM type to work inside the UMap layer.

Maybe i missing something else ??
