### ISSUE TITLE
[wishlist] better sorting 

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#353]
Data browser and Caption are sorting elements in a poor way. For instance, elements named :

1
9
10
11
100

are actually sorted :

100
10
11
1
9

I know it seems easy to overcome by adding zeroes. But it can be a pain when dealing with large numbers or remote data you may not have full control on. This would be a nice improvement of the default behavior.

**Comment by SultanMaz** [comment]
Yeah that would be nice. It's really time cunsuming to sort the data
