### ISSUE TITLE
missing storage/reqs/fullscreen/leaflet.fullscreen.css

### ISSUE THREAD

**Issue by datendelphin** [umap-project/umap#355]
I have issues upgrading to the most recent umap version. When I run
`python manage.py compress`
I get an error: `An error occurred during rendering /.../umap/umap/templates/auth/user_detail.html: 'storage/reqs/fullscreen/leaflet.fullscreen.css' could not be found in the COMPRESS_ROOT '/.../umap/static' or with staticfiles.`
How or where should I get leaflet-fullscreen ? Should it come with pip install?

**Comment by datendelphin** [comment]
it looks like static/storage/reqs is not properly populated by `python manage.py collectstatic`

**Comment by yohanboniface** [comment]
Those are only provided when using a packaged version of django-leaflet-storage, which is not yet the case for the latest master, but in its way.
The other way is to have declare Leaflet.Storage as a separate statics directory to Django, and then use the `make vendors` command from there, but that's a bit of North face. Unless you are in a hurry or very motivated to do things by hand I suggest to wait for a packaged version.
Anyway, if needed I can provide you with more detailed info on how to do it by hand.

**Comment by datendelphin** [comment]
I do have leaflet.storage in the umap/remote_static folder currently. Which version of umap and which version of leaflet.storge do you suggest to use? I would like to get rid of the bug with the search (search not panning to the right location)
