### ISSUE TITLE
Embeded Map on Website - Gzip problem

### ISSUE THREAD

**Issue by SultanMaz** [umap-project/umap#356]
Hey,

i'm using a map on my website. There is one problem and i'm not sure whether its a problem on my part or not.

Pages with the embeded map are "slow". Google PageSpeed Insights says: 

Enable compression for the following resources to reduce their transfer size by 454.2KiB (75% reduction)

Compressing http://umap.openstreetmap.fr/static/CACHE/js/28e5f8d7eaae.js could save 267.3KiB (75% reduction).
Compressing http://umap.openstreetmap.fr/static/CACHE/js/27f2d290e8f9.js could save 112KiB (75% reduction).
Compressing http://umap.openstreetmap.fr/static/CACHE/css/d236cff7811e.css could save 44.7KiB (83% reduction).
Compressing http://umap.openstreetmap.fr/static/CACHE/css/17a522b54f8a.css could save 14.6KiB (77% reduction).
Compressing http://umap.openstreetmap.fr/static/storage/src/locale/de.js could save 11KiB (63% reduction).
Compressing http://umap.openstreetmap.fr/static/CACHE/js/bfc211acb65e.js could save 4.6KiB (71% reduction).

Is there any way to compress this ressources which are loaded in the iframe?

Thanks for any help!

**Comment by yohanboniface** [comment]
@cquest seems to be missing in Nginx conf, worth adding it :)
Thanks for the report @SultanMaz :)

**Comment by cquest** [comment]
gzip added for css, js and svg static files...

**Comment by yohanboniface** [comment]
Thanks! :)

**Comment by SultanMaz** [comment]
Little question. GTMetrix and Google are showing me this notification lately:

"There are 18 static components without a far-future expiration date:"

http://umap.openstreetmap.fr/static/CACHE/css/1a36913492ee.css
http://umap.openstreetmap.fr/static/CACHE/css/085f10e3fefe.css
http://umap.openstreetmap.fr/static/CACHE/js/829988441b5a.js
http://umap.openstreetmap.fr/static/storage/src/locale/de.js
http://umap.openstreetmap.fr/static/CACHE/js/4b5850889f7f.js
http://umap.openstreetmap.fr/static/CACHE/js/34fa51a3dab4.js
http://openstreetmap.fr/piwik/piwik.js
http://umap.openstreetmap.fr/static/storage/src/img/16-white.png?ef2d7e303253
http://umap.openstreetmap.fr/static/storage/src/img/24.png?ef2d7e303253
http://umap.openstreetmap.fr/static/storage/src/img/16.png?ef2d7e303253
http://umap.openstreetmap.fr/static/storage/src/img/marker.png

Any way to fix it on my end or can you do anything for that issue?

Thanks!
