### ISSUE TITLE
cannot transfer ownership or add editors with less than 3 chars

### ISSUE THREAD

**Issue by bagage** [umap-project/umap#357]
A friend of mine has an account with name "XX" (2 letters only). But when I try to add her as map owner and/or map editor, after 2 characters umap automatically suggests names (but not XX) and I am stuck:
* if I type `enter`, umap select the current name in the list
* if I type `escape`, umap clear the textfield
* if I type `XX ` (with a space), I cannot hit `enter` then.
Is there a way to add a 2-letters user in umap?

**Comment by bagage** [comment]
Awesome, thanks @yohanboniface for the quick fix.

**Comment by yohanboniface** [comment]
Not yet deployed though.
