### ISSUE TITLE
erreur attribution fond de carte (osm_fr vs MapQuest)

### ISSUE THREAD

**Issue by Cyrille37** [umap-project/umap#358]
En mode édition je mets le fonds de carte osm_fr et l'attribution en bas à droit est juste.
En mode vue, le fond est bien osm_fr mais l'attribution pour MapQuest ...

La carte: http://umap.openstreetmap.fr/fr/map/opl-montreuil-en-touraine_101871#17/47.48682/0.94963
![capture du 2016-09-10 10-35-47](https://cloud.githubusercontent.com/assets/368965/18409212/5c66479a-7742-11e6-80bd-08b39a2faa74.png)

**Comment by yohanboniface** [comment]
C'est des restes du vieux fond MapQuest, remplacé à l'arrache pas le fond OSM-fr. Je vais faire du ménage avec la bascule vers la nouvelle version :)

**Comment by yohanboniface** [comment]
MapQuest a été supprimé.
