### ISSUE TITLE
Install issue: umap not found after succesful pip install

### ISSUE THREAD

**Issue by SABR-13** [umap-project/umap#362]
Hi,

we are trying to install umap to our Ubuntu 16 server and manage to get to this part of the install documentation: https://umap-project.readthedocs.io/en/latest/ubuntu/#create-the-tables

umap migrate 

but then we get "umap not found".

Could you please help us identify what's going wrong?

**Comment by yohanboniface** [comment]
Yes https://github.com/koorukuroo/umap/issues/1

Please do `pip install git+https://github.com/umap-project/umap` for now.
I'll push on pypi with another name asap.

**Comment by QJKX** [comment]
ea7ecbfc6d81cf64a1c79906e6f3f58a7d86944e corrects the pypi name.

**Comment by yohanboniface** [comment]
Good point!
