### ISSUE TITLE
Is it possible to insert in pop-up  image with hyperlink?

### ISSUE THREAD

**Issue by aborruso** [umap-project/umap#364]
Something like this in markdown:

    [![Foo](http://www.google.com.au/images/nav_logo7.png)](http://google.com.au/)

[![Foo](http://www.google.com.au/images/nav_logo7.png)](http://google.com.au/)

In uMap it could be somethink like:

    [![Foo]({imgUrlSrcField})]({imgUrlHrefField})

But it's a wrong syntax.

Thank you

**Comment by yohanboniface** [comment]
Should be:

    [[http://osm.org|{{https://camo.githubusercontent.com/dcef59392dafe5f8a60486c5a3d99e8ae752524e/687474703a2f2f7777772e676f6f676c652e636f6d2e61752f696d616765732f6e61765f6c6f676f372e706e67}}]]

Cioè:

    [[link_url|{{image_url}}]]

**Comment by aborruso** [comment]
@yohanboniface My URL link is inside a CSV field.

I have used:

    [[{link_url}|{{image_url}}]]

And it does not work

Grazie

**Comment by yohanboniface** [comment]
Ah, allora you need one more curly brace around the image link:

    [[{link_url}|{{{image_url}}}]]

**Comment by aborruso** [comment]
@yohanboniface wow, it works!!

This is the map http://umap.openstreetmap.fr/it/map/le-foto-di-internazionaleit_103554

**Comment by yohanboniface** [comment]
Andrea, se hai un minuto per provare la nuova versione di umap, mi fai un favore:

    http://dev.umap.openstreetmap.fr/

E une copia dei dati del umap di qualche giorni fa, quindi dovresti trovare le tue mappe.

**Comment by aborruso** [comment]
@yohanboniface I have made the login, and it works.

I have a lot of this error, that I do not have in the stable version

![image](https://cloud.githubusercontent.com/assets/30607/18729282/8060b636-8051-11e6-9a7a-c8059606668c.png)

**Comment by yohanboniface** [comment]
Ah ok, I think we do not have activated the proxy feature yet. I'll have a look asap, thanks :)

**Comment by aborruso** [comment]
@yohanboniface you are always very kind.

And what's new in the new version of uMap? Is there some wiki page that I can read?

**Comment by yohanboniface** [comment]
I'll do a workshop during SotM this week-end on this topic, and put online all the changes :)
Some of them:
- multipolygon/multipolyline support
- layer versioning
- layer reordering by drag'n'drop
- labels also on polygon/polyline
- export/import of full map data for better backup/restore
- new search
…

**Comment by yohanboniface** [comment]
> I have a lot of this error, that I do not have in the stable version

Should be fixed :)
