### ISSUE TITLE
GPX export not working with 0.8.0.rc.3

### ISSUE THREAD

**Issue by gottferdom** [umap-project/umap#366]
When trying to export data from a map in GPX format, it is not working:

- if I select GPX format in the combo box first then click on the download data link, nothing happens (javascript error: togpx is not defined)
- if I select another format first and export the data, then select GPX format and export, the proposed file is with the previous selected format

To reproduce : create a new map with a simple segment, then click on share icon on the left, choose GPX format and click download data link

**Comment by yohanboniface** [comment]
Thanks, fixed!
(But not yet released.)
