### ISSUE TITLE
Paths rendered above markers

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#368]
![screenshot from 2016-09-24 00-01-46](https://cloud.githubusercontent.com/assets/146023/18802615/2e41f7b2-81ea-11e6-8f06-eebdcda19e02.png)

Only paths should be reordered in specific layer panes, but markers should always be on top, in the markers pane.

**Comment by SultanMaz** [comment]
Same problem here. Markers are rendered below the polygons. Will this get fixed soon? 

![map](https://cloud.githubusercontent.com/assets/18287501/18803310/3ce20cbc-81ef-11e6-9781-eb37c1d70ae7.png)

**Comment by yohanboniface** [comment]
> Same problem here. Markers are rendered below the polygons. Will this get fixed soon?

It's fixed on the code, and will be deployed tomorrow.
You should be able to reorder layers to keep markers on top for now, as a workaround.
