### ISSUE TITLE
Layer items disappear randomly in edit mode

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#371]
This can be reproduced on http://umap.openstreetmap.fr/fr/map/cartopartie-velo-1992015_51492. Get to edit mode, edit the layer "Zones terminées", select "Afficher une étiquette" then "Etiquette cliquable" : a random polygon disappears, click again, another polygon or two disappear. The show/hide layer action also undraws a few polygons randomly. 
Looks like an interesting feature ;-)

**Comment by yohanboniface** [comment]
Fixed with Leaflet 1.0.0 release.
