### ISSUE TITLE
French based background layer still missing boundaries france/germany

### ISSUE THREAD

**Issue by wambacher** [umap-project/umap#374]
read https://lists.openstreetmap.org/pipermail/umap/2016-September/000140.html

problem is still open.

**Comment by yohanboniface** [comment]
This is not a uMap issue.
Please open an issue on the OSM-fr rendering: https://github.com/cquest/osmfr-cartocss

**Comment by wambacher** [comment]
yes, will do it. 

btw: that is the first time during the last 3 month somebody told me, who is really responsible for that problem. thank's
