### ISSUE TITLE
Separated default value for label displaying for points and lines

### ISSUE THREAD

**Issue by MiroJanosik** [umap-project/umap#378]
Hi, I noticed a big change in my map after recent update (23/9/2016).
Before I had there paths (with hidden labels) and points (with labels displayed).
After update I can't have that anymore, as there is only one default switch for that - Default interaction / display label.
Please bring an option to set these options per geometry type.

**Comment by yohanboniface** [comment]
You can either put them in separate layers (and control the label differently from those layers) or go by each feature and change it there.
Also only displaying the label on over may be to consider.

I think it does not worth an option, that would make the UI even more fussy, for very few usages.
