### ISSUE TITLE
Layer order and rendering order

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#379]
The rendering order apparently follows the rendering order : the first layer in the list is rendered first, then the second and so on. This results in the last layer being rendered on top of the others. I would argue this should be the opposite, so that the first layer in the list is rendered on top of the other layers. The argument is that one typically puts the "important" layer at the top of the list, and users expect it to be rendered on top of the others.

**Comment by vinber** [comment]
:+1:

**Comment by yohanboniface** [comment]
Released!
Thanks in advance for testing and feedback :)

**Comment by naomap** [comment]
Looks good to me, on this map anyway : http://u.osmfr.org/m/96443/
Thanks for fixing this from where you are :-)
