### ISSUE TITLE
Umap not saving edits anymore

### ISSUE THREAD

**Issue by GordonOfSeattle** [umap-project/umap#384]
UMap is no longer saving any edits I make to a map, even after I click save and disable editing. I come back later and they haven't been saved.

I also frequently (but not always) get the following error now:

![screen shot 2016-09-30 at 12 43 36 pm](https://cloud.githubusercontent.com/assets/22550821/19004747/219bde7a-870c-11e6-8d45-57364107d7eb.png)

Thanks to everyone who works on this. It's been really helpful for our non-profit up until now.

**Comment by GordonOfSeattle** [comment]
This has been especially problematic in conjunction with the fact that all my maps now have their labels turned on (and because of the error above I can't turn them off). 

thanks

**Comment by yohanboniface** [comment]
Adding the URL of the map can help understand what's going on, thanks.

**Comment by severinmenard** [comment]
I have the same issue, eg with this map, trying to sort the layers with the new (great) dragging functionality so that they are ordered by their initial number (0, 1, 2...)  : https://umap.openstreetmap.fr/fr/map, /carteinnov-suivi-de-la-cartographie-des-lieux-dinn_101662

**Comment by yohanboniface** [comment]
Tried to reproduce with (a clone of) your map, but it works for me.
Can you save in other situations (i.e. if you don't try to reorder but do any other change)?
Also do you have the same issue with the others of your maps?
Can you try with another browser?
Can you open the developer console before clicking save then do a screenshot of the full page (including the console) when you feel the map is not updating anymore?

**Comment by augustindo** [comment]
Hi,

I have trouble reordering layers by drag&drop too.
My config : Firefox ESR 45.4.0 Debian Jessie

- I have this problem on this two maps
https://umap.openstreetmap.fr/en/map/reseau-de-bus-sotraco-ouagadougou-burkina-faso_58808
https://umap.openstreetmap.fr/en/map/carteinnov-suivi-de-la-cartographie-des-lieux-dinn_101662

- But it's working on
https://umap.openstreetmap.fr/en/map/projet-ieda-cartographie-des-districts-sanitaires-_59363#9/13.2413/-2.3730

- Description of actions/reactions when it's not working
   - open the map in edition mode
   - drag&drop layers to reorder them
   - hit "Save"
   - right layer panel is leaving the screen smoothly on the right
   - but "Save" and "Cancel" buttons stay active/clickable
   - 2min later, nothing happen. I press F5 to refresh and I've a warning message
![capture du 2016-10-06 10 18 12](https://cloud.githubusercontent.com/assets/20402274/19174550/0ca09a0c-8c1f-11e6-99b9-73701e470088.png)
   - I choose "Stay on page"
   - Some time later I have the message "Vos modifications ont bien été sauvegardées". "Save" and "Cancel" button are not clickable anymore.
   - Refresh by F5, no warning,
   - My reordering is lost and I still have a bad order.

- Note
   - I can save other kind of modifications : edit a layer title, create a new marker, edit a marker name
   - About you @yohanboniface  asking " Can you open the developer console before clicking save then do a screenshot of the full page (including the console) when you feel the map is not updating anymore?", here it is (hope it is what you want) :
   ![selection_004](https://cloud.githubusercontent.com/assets/20402274/19174419/308d88f4-8c1e-11e6-8921-721fb4310b57.png)
   - Can't test with another browser for now (missing time and a good internet connection). I think @severinmenard could try this with his computer

Thanks for all :) can give precisions if needed

**Comment by GordonOfSeattle** [comment]
I haven't been able to successfully save any maps, but not being able to update this map in particular is causing our organization trouble: http://umap.openstreetmap.fr/en/map/seattle-neighborhood-greenway-groups_11792#13/47.5289/-122.3216

Thanks!

**Comment by yohanboniface** [comment]
@GordonOfSeattle have you tried with and other browser and/or from another network?
