### ISSUE TITLE
freeze upon launch

### ISSUE THREAD

**Issue by GordonOfSeattle** [umap-project/umap#385]
Just recently I've started getting the following error when launching (most of the time):

![screen shot 2016-09-30 at 12 42 44 pm](https://cloud.githubusercontent.com/assets/22550821/19004787/570ab69e-870c-11e6-94e6-f362d5fed0ba.png)

Thanks to everyone who works on this. It's been really helpful for our non-profit up until now.

**Comment by yohanboniface** [comment]
Adding the URL of the page you have opened when getting this message would help, thanks.

**Comment by GordonOfSeattle** [comment]
http://umap.openstreetmap.fr/en/user/GordonOfSeattl0f6854a36c9345b9/

It's just the opening screen for me. Thanks
