### ISSUE TITLE
"Note" feature

### ISSUE THREAD

**Issue by NicolasDumoulin** [umap-project/umap#387]
It could be nice if the visitor of an umap can leave a "note" as on the main website osm.org.
By "note", I mean the tool that allow the visitor to leave a suggestion for editing data on a place.

Thanks

**Comment by sfkeller** [comment]
Similar to letting users suggest new objects #768, #471 and #52?

**Comment by yohanboniface** [comment]
Yep, let's close in favor of #52 or #768, which are two ways to answer that.
