### ISSUE TITLE
Unable to add an editor to the map : the OSM userID suggestion is hidden by the "Map permissions" panel + edit not saved

### ISSUE THREAD

**Issue by augustindo** [umap-project/umap#389]
Hi,

On this map : https://umap.openstreetmap.fr/en/map/reseau-de-bus-sotraco-ouagadougou-burkina-faso_58808#12/12.3509/-1.4612
When I open "Map permissions" and type the 1st letters of an OSM userID, there is no autocompletion. So I type all the userID by my own (exemple : "DibloniInnocent") and click on "Save" (settings : "Only editors can edit"). 
The right panel close and I've a confirmation message at the top to tell me that my edits had been saved + the autocompletion name visible behind the right panel : 
![capture d ecran de 2016-10-09 12 34 54](https://cloud.githubusercontent.com/assets/20402274/19220592/6eace43c-8e20-11e6-9f00-082fd826f9d1.png)
![capture d ecran de 2016-10-09 12 37 46](https://cloud.githubusercontent.com/assets/20402274/19220593/6ebb1692-8e20-11e6-91e1-694baefc4b15.png)
If I open again the "Map permissions" : my edit had not been saved and I'm still the only editor of the map (and owner).

It has been reproduced by 2 other people on other computers and other maps (they are on Ubuntu, I'm one Debian, we use FF browser).

Sorry to not give more details but internet connection is too slow to do more tests.

Thanks in advance !

**Comment by augustindo** [comment]
But on the same map I've been able to edit and save the "Edit status" from "Only owner can edit" to "Only editors can edit"

**Comment by yohanboniface** [comment]
Thanks for the report!
Will be fixed on the next release :)
