### ISSUE TITLE
[wishlist] Better "See full screen" for embedded map

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#390]
Embedding a map allows you to select multiples options (layers shown, interface preferences, etc.), but the "See full screen" link doesn't reflect the choices made.

Iframe with many parameters :
`<iframe width="100%" height="300px" frameBorder="0" src="https://umap.openstreetmap.fr/en/map/carte-des-burgers-vegetariens-a-paris_19632?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=databrowser&captionBar=false&datalayers=120411"></iframe>`

"See full screen" with none :
`<p><a href="https://umap.openstreetmap.fr/en/map/carte-des-burgers-vegetariens-a-paris_19632">See full screen</a></p>`

It would be nice if the "See full screen" link reflected at least some of the choices made. Like the layers shown, if "Keep current visible layers" has been chosen by the mapper. Example :

`<p><a href="https://umap.openstreetmap.fr/en/map/carte-des-burgers-vegetariens-a-paris_19632?&datalayers=12041">See full screen</a></p>`

**Comment by yohanboniface** [comment]
Makes sense!
