### ISSUE TITLE
Markers movable when edition is off

### ISSUE THREAD

**Issue by severinmenard** [umap-project/umap#392]
Weird markers behaviour that I caught yesterday on Kazam: https://vimeo.com/186248367/dc3fca8732
Actually just after the video, when I disabled the edition, the red markers did not move anymore, but the yellow ones could then be moved.
Today after rebooting the computer, everything seems normal again.

System: Ubuntu Xenial
Firefox 49.0
umap #105470 (orginally created by cloning another one)

**Comment by yohanboniface** [comment]
Any new information to help me reproducing?
