### ISSUE TITLE
Better "add an editor" message

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#396]
The "Start typing" placeholder in "Map permissions > Editors" isn't clear anymore.

Typing in "Editors" used to launch the autosuggest with a list of editors. 

What to do next was easy to guess : pick one in the list.

Now autosuggest is gone, so what to do is unclear.

The placeholder should be something like "Type a username, and press Enter".

**Comment by yohanboniface** [comment]
Will be fixed in next deployment. See https://github.com/umap-project/umap/issues/389
