### ISSUE TITLE
Cannot add authorized editors with new version

### ISSUE THREAD

**Issue by jgc31** [umap-project/umap#397]
When trying to add authorized editors to a uMap (the new version hosted on osm.fr), no completion appears when one starts to type an identifier, and thus it is not possible to add other editors. I observed this with Firefox and Chromium browsers on Linux, and someone else had the same problem, likely on another platform.

Thus the only way for the owner not to remain the only editor was to open edition to all. Or to move to framacarte.org that is still using the previous version.

**Comment by yohanboniface** [comment]
See https://github.com/umap-project/umap/issues/389
It will be fixed with next deployment, hopefully today.

**Comment by jgc31** [comment]
Thank you very much, Yohan.
