### ISSUE TITLE
Casse non homogène dans l'interface

### ISSUE THREAD

**Issue by C138** [umap-project/umap#399]
La casse des titres des options n'est pas homogène.
E.g. 
_C_ouleur   mais _o_pacité  et _é_paisseur (au lieu de Opacité  Épaisseur)

idem dans Propriétés avancées
_S_implifier mais _t_raitillé

Probablement d'autres...

**Comment by yohanboniface** [comment]
https://www.transifex.com/yohanboniface/umap/dashboard/
