### ISSUE TITLE
[wishlist] Augmenter le seuil de détection/sélection des objets  

### ISSUE THREAD

**Issue by C138** [umap-project/umap#401]
Apparemment, le seuil de détection "accroche" d'un objet est très faible (1 pixel ?)
Certains utilisateurs peuvent avoir des dfficultés énormes à sélectionner un objet (trait)

Passer à 2 ou 3 pixels serait plus confortable.

Merci pour eux

**Comment by yohanboniface** [comment]
Indeed! cf #673
