### ISSUE TITLE
Dépendances inadaptée dans tutorial installation (Ubuntu)

### ISSUE THREAD

**Issue by C138** [umap-project/umap#404]
(Détail)
Dans le tutorial il est indiqué : 
apt install python3.5 python3.5-dev python-virtualenv

Si on est dans le contexte python3.5, alors les dépendances devraient être : 
python3-virtualenv virtualenv

Non ?

**Comment by yohanboniface** [comment]
Non, pas nécessairement.
L'executable utilisé pour créer le venv n'est pas celui qui sera installé dans le venv (cf `--python`).

**Comment by C138** [comment]
Sorry but do not assume that (any) "contributors" is able to PR ;-)
May be one day,  but for now I'm too busy by installing/testing an instance of umap... 
Seems to work until now, will confirm in a few minutes ;-)
