### ISSUE TITLE
local.py not correct for Ubuntu install tutorial

### ISSUE THREAD

**Issue by C138** [umap-project/umap#406]
Have to correct local.py by removing '/home' in the following lines (l. 103&106): 

# For static deployment
STATIC_ROOT = '/srv/umap/var/static'
# For users' statics (geojson mainly)
MEDIA_ROOT = '/srv/umap/var/data'

Unless, the script fails on dealing with '/home/srv', which does not exists.

BTW :  Reach the end of the installation process (without configuring web server), and ... it works ! ;-)

**Comment by yohanboniface** [comment]
Thanks, I think it has been fixed since then.
