### ISSUE TITLE
useradd -N umap -m -d /srv/umap/ is better

### ISSUE THREAD

**Issue by C138** [umap-project/umap#407]
Creating user **and** home directory (-m) is better than the two following lines 

```
sudo mkdir -p /srv/umap  (warning ! /srv/umap belongs to root.root and not umap user)
sudo useradd -N umap -d /srv/umap/
```
useradd -N umap -m -d /srv/umap/ ensures that /srv/umap/ is created with the right permissions.

**Comment by yohanboniface** [comment]
Fixed :p
