### ISSUE TITLE
Overpass: Image is not showing, wikipedia keytag

### ISSUE THREAD

**Issue by AllroadsNL** [umap-project/umap#409]
Data via overpass.

In the popup content template of the layer.
If you use de osm keytag inscription 
{inscription} you get the osm value text shown in the popup. okay!
Also  [[{website}|Website]] works well. You get the osm value url page in the browser.

But if you use the keytag image
{{image}} you get the image url with a extra } this is clickable, browser opened but does not show the image because of the extra } in the string , what I expected was, the image to be shown in the popup.
|100  width in the string gives a square but not a image or a url to a image.

The layer is set, but not every poi have this osm inscription keytag or a image or else.
Then when there is not a value found in the overpass process, the {} should not be shown in the popup. This does not look good. And should be avoided.

wikipedia
[[{wikipedia}|Wikipedia]] in the template, the value in osm is for example en:Eiffel Tower then you see a clickable Wikipedia in the popup, but in the browser the url is not found, logic, but it should make a right url.

There maybe more osm keytags that need a overpass solution.

**Comment by yohanboniface** [comment]
Closing in favor of #884
