### ISSUE TITLE
Not rendering on not-host PC

### ISSUE THREAD

**Issue by hevilp** [umap-project/umap#410]
Hi,

I got ubuntu 16.04.
Installed mod_tile and renderd after the tutorial: 
The http://MYLOCALIP/osm_tiles/0/0/0.png shows the world map.
The rendering is working fine with render_list.

The debug server with umap runserver 0.0.0.0:8000 (or MYLOCALIP:8000)  shows the start page.
Then I go to the button create new map and the map doesnt show up. The menus are there, but the map not.

I got the same issue in a virtual box.
Inside the box I was able to use umap correctly. But If I connected from another PC to the site, the map was not shown, too. But why?

**Comment by yohanboniface** [comment]
> The http://MYLOCALIP/osm_tiles/0/0/0.png shows the world map.

If it's a local IP, I guess it's expected that it's not accessible from outside.
This does not seem related to uMap, and I'm not sure how I can help.
