### ISSUE TITLE
lots of problems with new version

### ISSUE THREAD

**Issue by grandbic** [umap-project/umap#412]
Bonjour,
I made an up to date map this evening and had lots of problems.
https://umap.openstreetmap.fr/fr/map/amis-de-la-nature-2017-1er-semestre_114420#13/45.8211/4.9472
 The  slide show wouldn't restart once stopped.
The slide show starts at the bottom of the list.
The sites can be moved, even if not in edit mode.
On hover-over I get a second label 'dates à determiner Séjour.......' everywhere
The search places button charged without stopping, and I had to reload the page.
Perhaps the problem is my side? I'm having to use neighbours 4G connection.

**Comment by yohanboniface** [comment]
No idea.
Please take more time to investigate and open one Github issue per issue with details on how to reproduce.

**Comment by yohanboniface** [comment]
I can reproduce none of the listed issues.

**Comment by yohanboniface** [comment]
Look at your JS console, try in an other browser, try with another network, try with another map…

**Comment by grandbic** [comment]
can't understand, everything is now fine!
Before making the issue, I did check many times. Perhaps something to do with 'cache'.
Sorry for wasting your time.
