### ISSUE TITLE
How to add Proj4Leaflet to uMap?

### ISSUE THREAD

**Issue by SABR-13** [umap-project/umap#416]
Hi,

how would I go about adding Proj4Leaflet to uMap?

Adding it to plain Leaflet is simple:

```
<script src="proj4.js"></script>
<script src="proj4leaflet.js"></script>
```

`// RT90 with map's pixel origin at RT90 coordinate (0, 0)
`var crs = new L.Proj.CRS('EPSG:2400',
`  '+lon_0=15.808277777799999 +lat_0=0.0 +k=1.0 +x_0=1500000.0 ' +
`  '+y_0=0.0 +proj=tmerc +ellps=bessel +units=m ' +
`  '+towgs84=414.1,41.3,603.1,-0.855,2.141,-7.023,0 +no_defs',
`  {
`    resolutions: [8192, 4096, 2048] // 3 example zoom level resolutions
`  }
`);

`var map = L.map('map', {
`  crs: crs,
`  continuousWorld: true,
`  worldCopyJump: false
`});`

I've tried adding it to map_init.html as follows:

`var MAP = new L.Storage.Map("map", { crs: crs,{ map_settings|notag|safe }});`

and into leaflet_storage.js on the L.Map.mergeOptions, but I can't get either to work. Can anyone help?

Thanks!

**Comment by yohanboniface** [comment]
> I can't get either to work

map_init.html should be the right place. I guess you also added the proj4 statics?
Then what do you tried and what error message did you get or what where you expecting that was not working?

**Comment by SABR-13** [comment]
SyntaxError: invalid property id at: 

`        var MAP = new L.Storage.Map("map", {crs: crs, { map_settings|notag|safe }});`

And yes I have added the files to the js.html and uploaded the files to the server.

I assume that uMap has a different way of handling the L.Storage.Map() than default Leaflet?

**Comment by SABR-13** [comment]
And to be specific, my problem is when I insert the parameter "crs: crs" into the L.Strorage.Map() function in the map_init.html. I don't know how to combine it with the {map_settings|notag|safe} parameter.

**Comment by yohanboniface** [comment]
Closing in favor of #789
