### ISSUE TITLE
Saving current center/zoom creates mistakable success message

### ISSUE THREAD

**Issue by ltog** [umap-project/umap#420]
When saving the current center and zoom level using the icon

![umap_icon_save_center_and_zoom](https://cloud.githubusercontent.com/assets/4726277/21129867/03b91412-c105-11e6-8aae-47c6ea95a2d5.png)

, uMap reports with a mistakable error message:

In english:

> The zoom and center have been setted.

In french:

> Le zoom et le centre ont été enregistrés.

For some readers this might imply that the changed settings are already in effect, but my tests show that this is only the case after the settings have been saved using the save button:
 
![umap_buttons_abbrechen_speichern](https://cloud.githubusercontent.com/assets/4726277/21129905/42160a30-c105-11e6-9c2e-83234a7cdcc6.png)

I propose to update the text to say something like:

> The zoom and center have been registered. Use the "Save" button to apply this change to your map.

**Comment by yohanboniface** [comment]
What about just `The zoom and center as been modified` ?
