### ISSUE TITLE
layer buttons

### ISSUE THREAD

**Issue by grandbic** [umap-project/umap#421]
Bonjour,
I was a long time making out layer buttons (perhaps they are new), finishing by finding them of no use to me, so others might have same problem.
'display on load' OK now, avoids an overcharged map and data panel.
'data is browsable' could be useful eg for having hidden data ready to load - but why are the markers  put on the map in that case, and perhaps that's why  the left side layer button shows them. 
Trying to help.

**Comment by yohanboniface** [comment]
> 'data is browsable' could be useful eg for having hidden data ready to load - but why are the markers put on the map in that case, and perhaps that's why the left side layer button shows them.

Sometime it could make sense to add context data in the map (like the city districts in a map showing trash boxes), that should not appear in the "data browser panel".

With the districts:

![image](https://github.com/umap-project/umap/assets/146023/3803b7dc-8e4f-4ded-8775-6235c4e74688)


Without the districts:

![image](https://github.com/umap-project/umap/assets/146023/0d7fc133-e56e-4315-9dd2-513f71ae601e)
