### ISSUE TITLE
Disparition de la mesure automatique des distances et des surfaces

### ISSUE THREAD

**Issue by Bruitdufrigo** [umap-project/umap#423]
Bonjour, dans la nouvelle version de uMap, l'outils "mesurer les distances" ne permet plus d'afficher automatiquement les distances des tracés (ainsi que les surfaces des polygones). J'utilise umap pour créer des circuits de randonnée et je suis désormais obligé de retracer entièrement chaque parcours avec l'outils "distance" pour les mesurer. L'autre solution consiste à envoyé le fichier kml ou gpx dans googlemap qui lui les affichent, un comble !
Autre problème : au delà  de 10km, la mesure arrondi au kilomètre prés ce qui n'est pas très précis (avant 10km, le précision est au mètre prés)
Savez-vous si la fonctionnalité affichage des distances et surfaces sera rétablie, comme sur la version précédente ?
Merci d'avance.

**Comment by traildpdpdo** [comment]
Je plussoie.
En fait, ce serait bien d'avoir dorénavant les deux outils.
L'ancien qui faisait un calcul précis automatiquement quand on cliquait dessus (il calculait aussi les aires des polynomes).
Et le nouveau comme il est (et peut s'avérer pratique et complémentaire).
Merci.

**Comment by Bruitdufrigo** [comment]
bonjour
je ne sais pas si quelque pourra lire ce mail...
N’étant pas du tout spécialiste, je me demande ce que signifie le mail reçu ci-dessous. Est-ce que cela veut dire que le problème que j’ai soulevé a été résolu ? (je n’ai remarqué aucun changement sur umap).
merci

Yvan Detraz, architecte, directeur
contact@bruitdufrigo.com
06 64 39 68 15

**Comment by yohanboniface** [comment]
Oui, ça veut dire que c'est corrigé.
Et pour moi ça marche ;)
I.e.: quand l'outil de mesure est activé et que je survole une ligne ou un polygone sa longueur ou aire s'affiche via un message.
Si c'est pas le cas pour vous, je veux bien un peu plus de détails.

**Comment by Bruitdufrigo** [comment]
merci pour votre réponse, ça marche aussi pour moi, je n’avais pas remarqué le message qui s’affiche en haut
concernant le précision au delà des 10km (l’unité passe du m au km), pouvez vous faire quelque chose ?
encore merci !

Yvan Detraz, architecte, directeur
contact@bruitdufrigo.com
06 64 39 68 15

**Comment by traildpdpdo** [comment]
Merci pour l'information :)
Par contre pareil que Bruitdufrigo ; une valeur avec deux chiffres après la virgule (comme c'était "avant") c'est mieux qu' un grossier arrondi supérieur...
Merci !
