### ISSUE TITLE
Full stop in the name of a property

### ISSUE THREAD

**Issue by PRBS35** [umap-project/umap#426]
When you go to "Edit properties in a table", then "add a new property". 

If you put some special character in the name of a property, a lot of characters will not cause any trouble (for instance "&é~"#'{([@=$;"). 

But, if you add a new property with a full stop (for instance "C.P."), you will not be able to edit the features anymore. You get the same problem when you import a file (csv, geojson), where headers have a full stop in it. Deleting this property or rename it without a full stop solves the problem.

**Comment by yohanboniface** [comment]
Sorry, I'm not sure what you call a "full stop". Is there a map where I can see the issue?

**Comment by VladimirSlavik** [comment]
@yohanboniface Full stop is another name for dot, like at the end of a sentence. A string literal with full stop: "."
