### ISSUE TITLE
I can't move POI

### ISSUE THREAD

**Issue by vinber** [umap-project/umap#428]
On this map, in edit mode, i can't move any POI ?
http://umap.openstreetmap.fr/fr/map/les-tiers-lieux-en-nouvelle-aquitaine_93940#10/44.9765/0.6434

**Comment by yohanboniface** [comment]
Reproduced. Thanks for the report!

Seems to be linked to clusters. I'll try to fix this during the week-end.

**Comment by vinber** [comment]
Thanks :)

**Comment by vinber** [comment]
Do you succeed ?

**Comment by vinber** [comment]
Thanks :)
