### ISSUE TITLE
Data have been doubled

### ISSUE THREAD

**Issue by vinber** [umap-project/umap#429]
I don't understand, all data are doubled.
It happened after I add a property in table to add "logo" and url

http://umap.openstreetmap.fr/fr/map/les-supermarches-cooperatifs_121041#6/46.950/1.571

**Comment by yohanboniface** [comment]
Scary.
But remember that a bug report without a way to reproduce is just a rant ;)

**Comment by vinber** [comment]
Sorry it's not a rant. In fact i can't reproduce it :(
I import data, open table, add property "logo" and several values (logo url) to this property.
I save it and "refresh F5 or ctrl+R" and in table i have data in double, a line with value for new property "logo" and a line without value for new property "logo".
But if i try to reproduce it, nothing :(

**Comment by druxstr** [comment]
I run into something oddly similar. 

All my layers got duplicated after I added a custom marker using an URL.

I didn't manage to reproduce either unfortunately.

**Comment by yohanboniface** [comment]
Too bad. That one looks really scary, I'd love to catch it soon!

**Comment by yohanboniface** [comment]
Isn't that the same than #442?

**Comment by druxstr** [comment]
I'd say it is. I guess I've been using an unsaved cloned map, saving it only after I chose a custom marker. That would have cloned my layers, and be consistent with #442.

**Comment by yohanboniface** [comment]
OK, let's close, then.
