### ISSUE TITLE
Import KML

### ISSUE THREAD

**Issue by harobaua** [umap-project/umap#431]
Hi, i working in the Umap, i import file KML, but no recognized all elements, It looks incomplete.

View in Umap: 
![kmlumaperror](https://cloud.githubusercontent.com/assets/21368523/22185332/a90fa9f0-e0b1-11e6-881e-1f23331de28a.png)

View in Google My Maps: 
![kmlgooglemaps](https://cloud.githubusercontent.com/assets/21368523/22185349/ee45bda2-e0b1-11e6-903c-bba320d10c9e.png)

File KML: 
[LocalidadUPZ.zip](https://github.com/umap-project/umap/files/722208/LocalidadUPZ.zip)

Thanks, for helpme.!

Harobaua

**Comment by yohanboniface** [comment]
Should be fixed on next release.
Thanks for the report!
