### ISSUE TITLE
Heatmap doesn't working with way?

### ISSUE THREAD

**Issue by NicolasDumoulin** [umap-project/umap#432]
Hi, it seems that the heatmap feature doesn't work with way data.
I've build a layer (layer "parkings à vélos" on this [umap](https://www.openstreetmap.org/way/217766964)) that displays heatmap for bicycle_parking, and a [parking maped as an area (closed way)](https://www.openstreetmap.org/way/217766964) isn't displayed.
Is it a bug or a feature?
Thanks

**Comment by yohanboniface** [comment]
The plugin used only works with points: https://github.com/Leaflet/Leaflet.heat
You can force Overpass to give you only points with `center` option, AFAIK :)

**Comment by NicolasDumoulin** [comment]
Yes, it works!
My request becomes:
`http://overpass-api.de/api/interpreter?data=[timeout:120];area(3600007406)->.searchArea;(node["amenity"="bicycle_parking"](area.searchArea);way["amenity"="bicycle_parking"](area.searchArea););out center body;>;out skel qt;`
