### ISSUE TITLE
Layer versions show the wrong date

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#433]
Layer versions display silly dates such s "mercredi 10 février **48945** 11:18:33"
For a map I've created about a month ago, definitely not in February of any year.
This map for instance : http://u.osmfr.org/m/118024/
Though they all seem to suffer from the same time space trap hole...

**Comment by yohanboniface** [comment]
Yes, [fixed](https://github.com/umap-project/Leaflet.Storage/commit/e8db3b542849d8c9a57b5dc8a40c6a0eed7bdcf5) but not yet released :(
On its way!
