### ISSUE TITLE
OpenTopoMap : voir la distance totale / to see all the distance...

### ISSUE THREAD

**Issue by traildpdpdo** [umap-project/umap#435]
Bonjour.

Aux contributeurs d' OpenTopoMap :

Cela serait bien d'améliorer "la marge à droite du profil" à l'insertion d'un .gpx.
Pour rendre possible la lecture complète des valeurs, à l'extrémité.
En l'état, la distance et l'altitude totale se voient "rognés" dès que les valeurs commencent à être un peu élevées.
c.f. ma capture d'écran en lien ci dessous :
[http://img11.hostingpics.net/pics/713229OTM.jpg](http://img11.hostingpics.net/pics/713229OTM.jpg)
Merci !

Hello.

To the contributors of OpenTopoMap:

We can't read well the total distance for a "long" .gpx.
Thank you for improve that !
Here my screen shot :
[http://img11.hostingpics.net/pics/713229OTM.jpg](http://img11.hostingpics.net/pics/713229OTM.jpg)

**Comment by krisanselmo** [comment]
Bonjour,
Cela ne semble pas être en lien avec [OpenTopoMap](https://github.com/der-stefan/OpenTopoMap) mais plutôt avec le plugin [Leaflet Elevation](https://github.com/MrMufflon/Leaflet.Elevation) non?
Sur quel site web avez vous fait votre capture d'écran?

**Comment by traildpdpdo** [comment]
Bonjour, merci pour cette réponse.
La capture d'écran avait été faite depuis OpenTopoMap [https://opentopomap.org](https://opentopomap.org)
Hier, j'ai aussi laissé un courriel à chacune des trois adresses de leur page crédits quant à mon "problème". Mais en effet, peut-être est-ce dû au plugin Leaflet Elevation, ou à un bug avec mon naviguateur, comme ce que je pense avoir pu traduire du lien renvoyant à son sujet.

Une nouvelle capture d'écran :
[http://img11.hostingpics.net/pics/340852ScreenOTM.png](http://img11.hostingpics.net/pics/340852ScreenOTM.png)
Les valeurs sont coupées et hors champ de lecture au delà d'un certain nombre de chiffres.

**Comment by yohanboniface** [comment]
OpenTopoMap, c'est par [là](https://github.com/der-stefan/OpenTopoMap/issues) ;)
