### ISSUE TITLE
onLoadPanel seams to not work on new version

### ISSUE THREAD

**Issue by fjg** [umap-project/umap#436]
It does not load the **databrowser** since last [https://framacarte.org](https://framacarte.org) update.

**Comment by yohanboniface** [comment]
Seems to be working for me:

![screenshot from 2017-02-02 18-56-31](https://cloud.githubusercontent.com/assets/146023/22561625/49d13168-e979-11e6-835e-7e8f6d02f12b.png)

Do you have a bit more details?

**Comment by fjg** [comment]
cf. https://framacarte.org/m/6392

et sinon intégrée sur https://supermarchés-cooperatifs.fr avec l'option "&onLoadPanel=databrowser". Ca fonctionnait très bien avant cette mise à jour.

Je ne vois pas qui aurait pu changer...

**Comment by yohanboniface** [comment]
Ah, au chargement, j'avais compris.
Je regarde.

**Comment by yohanboniface** [comment]
Corrigé, mais cela demande une nouvelle mise en prod. J'essaie de faire ça au plus vite.

**Comment by yohanboniface** [comment]
Voilà, mis à jour sur framacarte.org.
Merci pour le signalement!

**Comment by fjg** [comment]
super merci pour la réactivité
