### ISSUE TITLE
Difficlut to edit polygons

### ISSUE THREAD

**Issue by nour72sy** [umap-project/umap#441]
OS: Windows 7 Pro
Browser: Chrome Version 56.0.2924.87 (64-bit) or IE 11, the same problem.

In all my maps, the polygon editing points (squares), suddenly got bigger and now it's difficult to handle or edit the polygons with these big squares!

I logged out and in, and created a new map, but the problem remain!

Please advise.

**Comment by yohanboniface** [comment]
Humm, is your computer touch enable?

**Comment by nour72sy** [comment]
Hi, 
No, it's a Lenovo laptop "ThinkPad" with the standard keyboard and mouse combination!

**Comment by yohanboniface** [comment]
Can you try on Firefox?

**Comment by nour72sy** [comment]
thank you very much, it worked on Firefox!
But can I know what is the cause of this issue? 
I've tried IE and even used a different computer but it didn't work!
Much appreciated.

**Comment by yohanboniface** [comment]
When edge markers are big, it means Leaflet.Editable is thinking the map is in touch mode. Which is because Leaflet since to consider the touch as enabled. So certainly the issue is there. I'll try to have a look soon.

**Comment by nour72sy** [comment]
Just forgot to mention that it happend with two of my friends also..
Thanks again for your support.

**Comment by yohanboniface** [comment]
@nour72sy sorry for the delay, but do you still have an issue ? I' can't reproduce myself neither in Chrome nor FF (Linux).
