### ISSUE TITLE
Data duplication on save

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#442]
I run into an issue where data layer duplicates itself on save.

I've created a [fresh new map](http://u.osmfr.org/m/124431/) and added a marker to in it. Everything seems fine. But when I click "Save", data duplicates and another marker appears in my Layer 1.

I managed to reproduce it. It seems to only happen when you create simultaneously a layer and it's data.  I encountered the issue in these 3 cases \:

- creating the first marker on a map
- importing data (geoJSON) to a new layer with the import tool
- cloning an existing layer

But if I create a layer then add data to it, nothings goes wrong.

**Comment by yohanboniface** [comment]
Should be fixed by https://github.com/umap-project/Leaflet.Storage/commit/47671750a22985d705b60d90a5e155ef35b51ea9
Can you confirm?

**Comment by druxstr** [comment]
It's fixed. Thanks !

**Comment by yohanboniface** [comment]
Thanks you for the detailed report! :)
