### ISSUE TITLE
Précision de la mesure de la distance avec uMap

### ISSUE THREAD

**Issue by traildpdpdo** [umap-project/umap#446]
Bonjour.

L' outil mesure uMap permet dorénavant à nouveau le calcul d'une aire d'un polynôme et de de la distance d'une trace .gpx : merci.
(Il faut activer l'outil mesure, et "pointer" (sans cliquer) sur l'aire ou le .gpx pour voir s'afficher l'estimation.)

Hélas, la précision (de l'estimation du calcu) à disparue pour un .gpx : en effet, au delà de 10,00 km, on à seulement dorénavant un chiffre rond.
En deçà la précision est de deux chiffres après la virgule.

Il n'y a pas ce "problème" pour les volumes, à ma connaissance.

Est-ce que cela pourrait-être corrigé ?

Merci !

**Comment by yohanboniface** [comment]
https://github.com/umap-project/Leaflet.Measurable/commit/cb32f0dd6b9fd92316aec5c64f2a980a9aa80199
