### ISSUE TITLE
Polygon repository

### ISSUE THREAD

**Issue by AlfonsoAlejandre** [umap-project/umap#447]
Thanks for this magnificent work.
Is there a  Polygon repository of country borders?
I want to make polygons with countries, and I suppose that this work is done for other people. Isn't It?
Thank you in advance for the response. 
Alfonso

**Comment by yohanboniface** [comment]
A lot around, just search Internet, you'll find some. :)
Here is one example: https://gist.github.com/brandonblack/a947443b8c1fa507d358
