### ISSUE TITLE
Import data by URL doesn't work

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#448]
Importing data by providing an URL doesn't seem to work

![import-data-url](https://cloud.githubusercontent.com/assets/17235663/22780046/7c4adc54-eebd-11e6-86ee-585bc73e8a85.JPG)

I tried \:
* importing different format (CSV, geoJSON, KML, GPX)
* importing via Firefox & Chrome
* importing from a different webserver

[See this map](http://u.osmfr.org/m/125848/) : each layer should display 2 markers in Ireland. But instead it shows nothing.

Importing does create a new layer, but it's empty.

**Comment by yohanboniface** [comment]
The URL must enable CORS.
What is the URL your are trying?

**Comment by druxstr** [comment]
I tried with : 

* https://whoz.me/map/brouillon.geoJSON (simple file on a webserver)
* https://webcloud.zaclys.com/index.php/s/2PGtfUiogKD5qBH/download (file shared via OwnCloud)

**Comment by yohanboniface** [comment]
None of those uses CORS.
When using "remote data" you can click "proxy" so the URL will be proxied on the uMap server to work around CROS issues.
But when importing, given it's a one time action, there is no need. Just copy-paste the URL content by yourself.
