### ISSUE TITLE
add opensnowmap.org as background

### ISSUE THREAD

**Issue by juliencarnot** [umap-project/umap#449]
There are already some outdoors/sport renderings available, but it would be great to be able to use www.opensnowmap.org rendering as background in umap, to be able to sketch and share proposed routes for example.

**Comment by yohanboniface** [comment]
From the "about" section of opensnowmap:

>  The base topo map or the piste+relief overlay are too demanding in server ressources to be shared easily.

Sadly :/

(And sorry for the lag!)
