### ISSUE TITLE
[wishlist] Add polygon interaction options to layer options

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#451]
It would be nice to have the ability to define polygon interaction options in the layer interaction options. Amongst those options (Enable interaction, Link to [URL] and Open the link in...), it would be super-great to let the second option allow the URL to be defined with an attribute coming from an imported file - in a similar way this can be done for marker icons (i.e. http://myserver.org/images/{name}.png) : this would enable us to "automate" creating a "navigation map" such as http://umap.openstreetmap.fr/fr/map/quartiers-de-nantes_126581

(Ok ok this is not so crucial, you can leave it as low priority ;-)
Cheers,
Antoine.

**Comment by yohanboniface** [comment]
Done in #1162 :tada:
