### ISSUE TITLE
handle tms layer attribute on tilelayer/add/ 

### ISSUE THREAD

**Issue by brunob** [umap-project/umap#453]
Hey @yohanboniface what do you think about adding a checkbox in order to set tms attribute on layers when editing one from `admin/leaflet_storage/tilelayer/add/` ?

I couldn't find a way to add a tms layer from admin page, and i've seen it's possible to set this attribute on custom background in public area :\

**Comment by brunob** [comment]
After a quick lookup, this seems to be possible by adding an option fort that in https://github.com/umap-project/django-leaflet-storage/blob/master/leaflet_storage/models.py#L64 (and maybe it would need another modification in leaflet.storage ?).

**Comment by yohanboniface** [comment]
Yo @brunob !

Do you have an example of TMS tilelayer service I can test out?

Sorry for the lag :(

**Comment by brunob** [comment]
sure, have a look at these one http://tiles.kupaia.fr/demos/sync.html

no hurry :)

**Comment by brunob** [comment]
\o/ merci mignon :)

**Comment by brunob** [comment]
@yohanboniface can you confirm that the commit add a checkbox to admin/leaflet_storage/tilelayer/add/ page ?

**Comment by yohanboniface** [comment]
It does, but it's not yet part of a uMap release :(
I'll try to make that up this week.

**Comment by brunob** [comment]
Ha ok, no hurry, again ;)
