### ISSUE TITLE
Example for local.py for using sqlite 

### ISSUE THREAD

**Issue by hevilp** [umap-project/umap#458]
How to use sqlite as backend? How to define the sqlite-db-file?

**Comment by siiky** [comment]
Assuming that they don't use any special Postgresql features, I think it should be as simple as changing this line to use SpatiaLite ([`django.contrib.gis.db.backends.spatialite`](https://docs.djangoproject.com/en/4.1/ref/contrib/gis/db-api/)):

https://github.com/umap-project/umap/blob/9b0986c16b8175af37df3a1001d15f0306d42197/umap/settings/local.py.sample#L27

**Comment by davidbgk** [comment]
@hevilp you should [get your database running](https://docs.djangoproject.com/en/4.2/topics/install/#database-installation) and then [adapt your settings for DATABASES](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-DATABASES).

This is an untested territory though.
