### ISSUE TITLE
tabindex - responsive web - safari 

### ISSUE THREAD

**Issue by JohnDevC** [umap-project/umap#464]
I included the map in my webpage and if I touch the map on mobile devices (e.g. safari) the webpage scrolls automatically to the bottom.

It is possible that the tabindex scrolls the main page if someone interact with the map?
If i remove the tabindex programmatically from the id=map, there are no troubles for responsive websites. For instance the bug exists for safari.
I include the map with iFrames or object data descriptions (<object data="http...").
There are some other experience with this issue?

The bug always exists.

**Comment by yohanboniface** [comment]
Sorry that this issue has been out of our radar! I guess it's not needed anymore  since then, so closing. Please reopen if needed.
