### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'deny'

### ISSUE THREAD

**Issue by r4fx** [umap-project/umap#469]
Hi,

I realised that embedding map is not possible because of X-Frame-Options sending as "deny",
Is that ok ? How can we use now embedding option ?

**Comment by nblock** [comment]
The webinterface still shows the 'Embed the map' option via IFrame. Could this just be a misconfiguration on the webserver?

**Comment by r4fx** [comment]
don't use https://umap.openstreetmap.co, 
instead use http://umap.openstreetmap.fr

**Comment by nblock** [comment]
@r4fx Oh, thx a lot!
