### ISSUE TITLE
tiles loading over http and not https causing mixed content errors

### ISSUE THREAD

**Issue by canaldumidi** [umap-project/umap#470]
Mixed Content: The page at 'https://www.xxxxx.xxxx/accommodations.html' was loaded over HTTPS, but requested an insecure image 'http://a.tile.opencyclemap.org/cycle/9/257/187.png'. This content should also be served over HTTPS.

If I remember correctly, this was not causing any problems last week.  But now I am getting mixed content warnings.  Did you all do some recent updates?  Could you please fix this?  Thanks!

**Comment by svalo** [comment]
Trying to visit  'https://a.tile.opencyclemap.org/cycle/9/257/187.png' I receive an ssl error about certificat being valid only for tile.opencyclemap.org, this may be the issue. Otherwise you can check if in the admin section or in the map configuration if the tile layer is configured to use `https://` instead of `http://`

**Comment by canaldumidi** [comment]
Mixed Content: The page at 'https://xxxx.xxx/accommodations.html' was loaded over HTTPS, but requested an insecure image 'http://a.tile.opencyclemap.org/cycle/9/261/186.png'. This content should also be served over HTTPS.
umap.openstreetmap.fr/en/map/free-canal-du-midi-france-cycling-map_113068?s…76889%2C276894%2C275874%2C276837&editinosmControl=false#9/43.3851/2.4609:1

I tried using the meta tag <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> but it did not fix the problem.  Instead of getting a mixed content warning, I got a large grey square (the map tiles were not loading, as they do not exist in https version).  The meta tag did resolve another similar issue on a geoportail map, so the meta tag is good.

**Comment by fallen** [comment]
We also get the same issue at https://antipub.org , what would be the solution?
Thanks!

**Comment by yohanboniface** [comment]
> We also get the same issue at https://antipub.org , what would be the solution?

Switch to a background using https ;)

**Comment by fallen** [comment]
Fixed. Thanks! :)
