### ISSUE TITLE
Attribution templates escape HTML instead of rendering it.

### ISSUE THREAD

**Issue by almereyda** [umap-project/umap#472]
When adding a map overview to https://hack.allmende.io/s/intermapping-report I've found that the attribution footer is incorrectly rendered. This also happens in non-embedded maps like https://umap.openstreetmap.fr/map/intermapping-2017-firenze_131835.

**Comment by yohanboniface** [comment]
You can use "uMap flavored templating":

```
 [[http://example.com|text of the link]]
```

**Comment by almereyda** [comment]
This looks like a Wiki link. Merci, it works!
