### ISSUE TITLE
Remote data with URL for geojson does not work

### ISSUE THREAD

**Issue by severinmenard** [umap-project/umap#474]
the data from https://gist.github.com/anonymous/02c9721420577fe6efb381251215aa06 shows up on the gist map but not on umap (example: https://umap.openstreetmap.fr/fr/map/carteinnov-tests_136434)

Same issue with other geojson data sources (example: https://healthsites.io/api/v1/healthsites/search?search_type=placename&format=geojson&name=senegal)

**Comment by yohanboniface** [comment]
> the data from https://gist.github.com/anonymous/02c9721420577fe6efb381251215aa06 shows up on the gist map but not on umap

You need to use the raw URL (see "Raw" button), which is https://gist.githubusercontent.com/anonymous/02c9721420577fe6efb381251215aa06/raw/e6550e92969e33bf4deffa09a0ca74552867fbfc/test.geojson in this case.

See http://umap.openstreetmap.fr/en/map/untitled-map_147031#7/14.153/-13.535 with a working example.

> Same issue with other geojson data sources (example: https://healthsites.io/api/v1/healthsites/search?search_type=placename&format=geojson&name=senegal)

Just had a deeper look on this case, and it seems an SSL issue.

@Jocelynj @cquest I feel like we are in this trap: http://stackoverflow.com/questions/34513784/urlopen-error-errno-1-ssl-c510-error14077417ssl and it seems fix it to upgrade python to python >= 2.7.9.
Time for Python3 and server migration?

**Comment by berteh** [comment]
fyi I refer to my github hosted geojson via the free CDN at https://gitcdn.xyz/.
Works flawlessly so far.

**Comment by davidbgk** [comment]
Please reopen if the problem persist.
