### ISSUE TITLE
Backup data to local disk

### ISSUE THREAD

**Issue by canaldumidi** [umap-project/umap#475]
Is there a way to backup data to local disk?  I am starting a very big project with Umap, and am concerned about future data loss.  I have duplicated my map, but for extra security off-site storage of data is recommended.  So I would like to store my data on my server at home (RAID).  How can this be done?

**Comment by VladimirSlavik** [comment]
Hi, you can always download all the contents: On the left, select sharing, then at the bottom of that you get download options. You can see for yourself which formats can be exported...

![umap-export](https://cloud.githubusercontent.com/assets/15903878/24854359/798ea3ec-1dde-11e7-9a6c-e1ef198786e2.png)

**Comment by yohanboniface** [comment]
Downloading full umap data as explained by @VladimirSlavik is the way to go.
