### ISSUE TITLE
disappearing data

### ISSUE THREAD

**Issue by grinapo** [umap-project/umap#476]
It seems this map only contain one object:
https://umap.openstreetmap.fr/en/map/magyar-kilatok-look-out-towers-in-hungary_140128
Browse data show one.

But in fact it does plenty, which is visible in the editor. When I edit the name of the data the entry changes to another, but still not all visible.

**Comment by yohanboniface** [comment]
Thanks for the report, and sorry for the lag :(
Should be fixed in the next release, hopefully next week.
