### ISSUE TITLE
Cancelling a marker's shape don't use the layer default

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#480]
1. Create a marker and set its shape
2. Change the layer default options to use the 'drop' shape for markers
3. Delete the marker's shape in order to use the layer default shape
It doesn't ! The "default default" shape (square-ish) is used instead.

**Comment by yohanboniface** [comment]
Had a quick look, this seems to be the case for all select, because by FormBuilder.Select.toJS have a fallback to return the default value when no valid value is found:

https://github.com/yohanboniface/Leaflet.FormBuilder/blob/master/Leaflet.FormBuilder.js#L432

**Comment by yohanboniface** [comment]
Should be fixed by https://github.com/umap-project/umap/commit/fded9d62018d1a8d85676389d8dba251aa4565c4#diff-4b3d9c0f6294b60225bb8334f8c68fac
