### ISSUE TITLE
Possible to have 10 layers with dynamic remote data ?

### ISSUE THREAD

**Issue by pdfext** [umap-project/umap#486]
Hello 
 I built an umap with 10 layers of dynamic remote data. And It does not work well. I have a red banner which gets displayed with 'Problem in the response', and this banner is displayed multiples times. 
 If I test each on these layers one by one, then I get no issue, and remote data are properly displayed.
 If I test with 5 layers, it works as well, but it seems to be the limit, not sure of that, but I for sure get the banner with 'Problem in the response' when I reach 10 layers, likely before !
 My umap is [http://umap.openstreetmap.fr/en/map/equipements-cyclables_141536 | equipements_cyclables], if someone could try and tell me if this is a umap limit or if this is something else.  Is there any way to workaround this issue ?
Thank you in advance !

**Comment by yohanboniface** [comment]
You are getting a "429 Too Many Requests" from Overpass API.
Try another [Overpass instance](https://wiki.openstreetmap.org/wiki/Overpass_API#Introduction).
