### ISSUE TITLE
Changing umap account name 

### ISSUE THREAD

**Issue by aftocext** [umap-project/umap#491]
Hello
 I associated my Umap account with an OpenStreetMap account thru OAuth, but afterwards I changed the displayname of my account in OpenStreetMap and I really wish that this change is reflected into my Umap account (which is not the case, i still see my previous name on Umap). Is there a way this can be changed at least manually  by somebody, as I didn't see any thing related to account management on the Umap side ? Thank you very much if this can be done !  (I ll provide account details when necessary).
Cheers !

**Comment by pdfext** [comment]
No answer on this one ?

**Comment by grandbic** [comment]
Bonjour,
If i've understood:
open account 1
permissions/editers/name of 2nd account
close 1st account /open 2nd account
edit/advanced actions /clone

**Comment by tomhughes** [comment]
Can we please, please fix this! I'm fed up with people closing their OSM accounts and creating new ones just so they can change their name on uMap!

Well that and complaining that they can't contact anybody at uMap and hence come to OSM support instead with their uMap issues.

**Comment by vinber** [comment]
I think it's a duplicate : https://github.com/umap-project/umap/issues/7

**Comment by Binnette** [comment]
Fixed by #754
