### ISSUE TITLE
uMap iframe not working in Firefox?

### ISSUE THREAD

**Issue by Ocirne94** [umap-project/umap#492]
Hi,
I'm trying to display an uMap iframe on a webpage (https://aulastudio-lodi.neocities.org, tab "Dove siamo"), with mixed sucess. Everything works with Chromium browser, but with Firefox (53) the map is not shown.
Debugging with Firebug I think I've found a possible cause: there is a GET request for https://openstreetmap.fr/piwik/piwik.js which is never completed.
Could you please help me?
Thank you very much!

**Comment by yohanboniface** [comment]
If you site is using `https`, you need to include only `https` elements.

**Comment by Ocirne94** [comment]
Do you mean changing the iframe code to <iframe id="mappa" frameBorder="0" src="https://umap.openstreetmap.fr[..]"></iframe> ? That doesn't work.

**Comment by Ocirne94** [comment]
Further research shows that the map iframe with firefox is actually displayed around 20% of the times...?!

**Comment by nylnook** [comment]
Same issue for me on this webpage: http://campinglalize.fr/
We recently moved to another host, it was previously working, and now it's not. 
No errors in the console, the iframe is only showing a blank page... 

Any guidance please ?

Thanks in advance !

**Comment by yohanboniface** [comment]
Humm, I see a map in http://campinglalize.fr/
Are you using some browser extension to force https?

**Comment by nylnook** [comment]
Thanks Yohanboniface !
I'm sorry to have waste your time...  I found the bug: It's Privacybadger Extension who was blocking umap.openstreetmap.fr...
I'll report that to PrivacyBadger...
