### ISSUE TITLE
No error when fetching data from URL returns 40X error code

### ISSUE THREAD

**Issue by bagage** [umap-project/umap#493]
See #489 for the whole context:

When the XHR request fails with `404` or `403`, we should reach the error-handling statement from [there](https://github.com/umap-project/Leaflet.Storage/blob/master/src/js/leaflet.storage.xhr.js#L83). But when I test on umap.openstreetmap.fr, no popup appears for dropbox, seafile or any invalid link that respond 403 or 404. 
However if I type `teadt>/*"` in URL, I get ["error in the response" popup](https://github.com/umap-project/Leaflet.Storage/blob/master/src/js/leaflet.storage.xhr.js#L128), as expected. 
Do you know the reason why these alerts are not shown?

**Comment by yohanboniface** [comment]
> But when I test on umap.openstreetmap.fr

It may be a Nginx thing, do you see the same behavior when running umap locally?

**Comment by bagage** [comment]
Err, I cannot run it locally since I don't have the backend installed and it seems a bit heavy to setup - the issue also happens on http://umap.fluv.io, and actually the reason is in the developer console:

> Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://www.dropbox.com/s/l2g8kit4felnznv/26-statistics.geojson?dl=0. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.  (source inconnue)

The browser is actually "killing" the request before it's actually sent, so you never reach the callback... I don't know [if it's even possible to catch it](http://stackoverflow.com/questions/29042794/how-to-catch-a-browser-blocked-xmlhttprequest)?

**Comment by yohanboniface** [comment]
> if it's even possible to catch it

AFAIK, it's not, and this why it's done in Leaflet.Storage :(

**Comment by bagage** [comment]
Oops, see my edit: on fiddle it seems that the callback *is* invoked, with `xhr.readyState == 4 && xhr.status == 0`. 
But I cannot confirm for sure if it's the same thing on Umap since I cannot run it locally yet.

**Comment by yohanboniface** [comment]
This should have been fixe by #1175
