### ISSUE TITLE
import marker color from kml or geojson

### ISSUE THREAD

**Issue by simonLouvet** [umap-project/umap#494]
Hello,

I try to specify color of marker during an import but that don't seem effectiv.
```
<Document>
        <Placemark>
            <Point>
                <coordinates>1.8457031250000002,47.45780853075031</coordinates>
            </Point>
            <styleUrl>#Style00</styleUrl>
        </Placemark>
        <Style id="Style00">
            <LineStyle>
                <color>ff6e6e6e</color>
            </LineStyle>
            <IconStyle>
                <color>ff6e6e6e</color>
            </IconStyle>
        </Style>
    </Document>
```
I ever try other color format (kml, Umap Color..).

**Comment by M-Rick** [comment]
Hi
You already can do it.
In your GeoJSON, just add a new column _**_umap_options**_ and in your datas values add this **_{ "color": "green" }_**
You can edit your GeoJSON file in QGIS and apply a dynamic calculation from the color column over the new _**_umap_options**_ just like this **_{ "color": "my_colors" }_**. And then when you will import your datas in uMap, you won't have to set the colors, all will be ready. It works for any of the settings, such as transparency, dashes, weight, labels, icons etc.
You can even prepare all your data directly if your create a **_name_** a **_description_** columns and fill them with the texts dedicated to them including the CSS style to format the rendering.

**Comment by wikimas** [comment]
I'm trying to get my head around to setting the pin-style in my csv, but whenever i try to import a _umap_options field, it dissappears, or at least, it doesn't style my pin?

**Comment by skramm** [comment]
ok, finally got that. For others that follow the same path as me, here is a sample of something that works.
I think that the issue can be closed now.
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "Collège Bidule","_umap_options": { "color": "yellow" }
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          2.332706,
          48.86614
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Ecole maternelle Truc","_umap_options": { "color": "green" }
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          2.290811,
          48.842157
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Ecole primaire Machin", "_umap_options": {"color": "red"}
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          2.405807,
          48.875666
        ]
      }
    }
  ]
}
```

**Comment by simonLouvet** [comment]
thanks a lot @skramm

**Comment by dawansv** [comment]
> I'm trying to get my head around to setting the pin-style in my csv, but whenever i try to import a _umap_options field, it dissappears, or at least, it doesn't style my pin?

_map_options is removed from the table view by design. The problem is not that, but the fact that in a CSV _umap_options is processed as a quoted string, so instead of { "color": "red" } it is processed as "{ \"color\": \"red\" }" and it ends up looking like a series of single characters after processing.
```
"_umap_options": {
          "0": "{",
          "1": "\"",
          "2": "c",
          "3": "o",
          "4": "l",
          "5": "o",
          "6": "r",
          "7": "\"",
          "8": " ",
          "9": ":",
          "10": " ",
          "11": "\"",
          "12": "r",
          "13": "e",
          "14": "d",
          "15": "\"",
          "16": "}"
        }
```
I don't really think there is a way around it without converting your csv to GeoJSON first. Which is too bad because I was trying to use this from a remove google spreadsheet csv but indeed although I can pass the regular fields that way, no luck with passing per-record _umap_options.

**Comment by albjeremias** [comment]
hi! 
i made this script to convert kml to geojson, importable by umaps! :)

https://gist.github.com/albjeremias/0d591bbd703ac2b9bd835b40118cd14f

but I'm still trying to understand how the geojson should be formatted so that the polygon has a filling color. anyone knowns?

**Comment by yohanboniface** [comment]
Try adding something like this:

```
"type": "Feature",
…
"properties": {
    …
    "_umap_options": {
        "color": "yellow"
    }
}
```

But please note that this property is not official, and it is going to change in the incoming weeks.
