### ISSUE TITLE
"Routing mode" for drawing lines

### ISSUE THREAD

**Issue by joostschouppe** [umap-project/umap#495]
Hi,
This must have been asked before, but I could not find an old or new issue.

Is it possible or on the agenda to draw lines based on OSM features such as roads? To make it possible to (for example) click on a point, then a next, where the line is generated based on the road network?

**Comment by gappleto97** [comment]
It would be very nice to have this. At the moment I have to do it in Google Maps and export the path. This is both inaccurate, and kind of a pain.

**Comment by o314** [comment]
Hello there. No news about this feature request, 5 years later ?

**Comment by o314** [comment]
FWIW gpx studio provides a nice editing experience. Their github mentions that

> Each time you add or move a track point, we make a request to <a href="https://docs.graphhopper.com/#tag/Routing-API" target="_blank">GraphHopper Routing API</a> to retrieve a route on the road network.

So consulting https://github.com/gpxstudio/gpxstudio.github.io and https://github.com/graphhopper/graphhopper may be useful ...

**Comment by yohanboniface** [comment]
Closing, but following the feature in #297
