### ISSUE TITLE
Popup shown by default

### ISSUE THREAD

**Issue by tourenfex** [umap-project/umap#496]
Is it possible that a pop-up, as shown in the picture, is already open when the map is displayed and not only after clicking on the marker?

![popup](https://cloud.githubusercontent.com/assets/21131233/26783461/8d9b7d74-49f8-11e7-8bd5-3a26af0583bd.jpg)

**Comment by yohanboniface** [comment]
Nope. But it's must have, indeed.

I'd close here, but keep https://github.com/umap-project/umap/issues/294 as reference for this feature request.
