### ISSUE TITLE
UMAP - External call (iframe) &datalayers parameters: is it possible to specify a marker name/id to focus the map on it

### ISSUE THREAD

**Issue by naonedv** [umap-project/umap#497]
Hello
I'm calling the iframe text generated by umap to call the map from a website: that's super cool.
The map has for instance 50 markers.
But i'd like for my 50 websites pages to call for the map but the map must be "centered" to a specific marker (the one we talk about on the specific page).
I see there is &datalayers parameters, that if we choose option "show as current view", the outcome is like this: &datalayers=370676#7/35.747/35.145
It's cool but i'd like to easy  my job and i don't want to go to each marker to get their coordinates so to call the map focused on the marker from outside.
Is there a way, via parameter to do so?
Of course you might tell me to import map data to my website and build whatsoever php, but please try answer my question. Any suggestion is welcomed :)

**Comment by druxstr** [comment]
>  i don't want to go to each marker to get their coordinates

I guess there is no other way. A basic marker is a geoJSON point with a 2 properties (name, description) and coordinates. It has no ID that would be independant from its coordinates and that you could fetch.
