### ISSUE TITLE
Request to the Umap developer community to get in touch

### ISSUE THREAD

**Issue by brandrg** [umap-project/umap#499]
I work for the EU-funded CIVITAS initiative (www.civitas.eu), which supports cities in their pursuit of sustainable mobility. We are creating an online repository of tools that can be of practical use for cities. Umap should obviously be featured in this database. If you would like to have Umap included please submit related information before July 14 2017 on https://qeurope.eu.qualtrics.com/jfe/form/SV_5BbWweceP1LOwkJ. It only takes 10-15 minutes and is free of charge. You can also contact me at r.brand@rupprecht-consult.eu

**Comment by yohanboniface** [comment]
Thanks for the info, I'll have a look :)

**Comment by yohanboniface** [comment]
Oops, missed that :(
