### ISSUE TITLE
georss flickr 

### ISSUE THREAD

**Issue by pdfext** [umap-project/umap#500]
As an attempt, I tagged one flickr picture and verified it could be get thru its tag : 
[my georss with tag, (you can test it)](http://api.flickr.com/services/feeds/photos_public.gne?tags=ruebarginetgrenoble&format=rss_200_enc)

Then I created a umap and wanted to see if umap can display it : 
[my umap with one remote contents](https://umap.openstreetmap.fr/fr/map/essaiflickrgeorsstag_154934#15/45.1878/5.6976), but it does not work as expected.

I verified that, my umap config was correct : 
 - I set url to 'http://api.flickr.com/services/feeds/photos_public.gne?tags=ruebarginetgrenoble&format=rss_200_enc'
 - I set format to 'georss' 
 - I set 'dynamic contents'
 - I set 'with proxy'

I verified as that that my picture is displayed thru this url which covers the same geographic zone : [https://www.flickr.com/map/?fLat=45.184456&fLon=5.740399&zl=14](https://www.flickr.com/map/?fLat=45.184456&fLon=5.740399&zl=14)

Can you pleas tell me if I did something wrong, or missed one step ?
Thank you !!

**Comment by yohanboniface** [comment]
You sure you pictures are geotagged? I see not geo information from within the feed:

view-source:http://api.flickr.com/services/feeds/photos_public.gne?tags=ruebarginetgrenoble&format=rss_200_enc

**Comment by pdfext** [comment]
Yes, [the picture which is displayed through this link]( http://api.flickr.com/services/feeds/photos_public.gne?tags=ruebarginetgrenoble&format=rss_200_enc) is geotagged

When I look at the [picture itself](https://www.flickr.com/photos/156017218@N06/34679633524/)
and when I do **'See EXIF**', I can see the following (see part in **bold**)


Date and Time (Modified) - 2017:06:25 11:38:35
Image Width - 4656
YCbCr Positioning - Centered
Image Height - 2620
Y-Resolution - 72 dpi
X-Resolution - 72 dpi
Make - asus
**GPS Date Stamp - 2017:06:25
GPS Altitude Ref - Unknown (2)
GPS Longitude Ref - East
GPS Longitude - 5 deg 42' 22.90"
GPS Processing Method - ASCII
GPS Latitude Ref - North
GPS Time Stamp - 09:38:31
GPS Altitude - 0 m
GPS Latitude - 45 deg 11' 10.17"
Color Space - sRGB**
Date and Time (Digitized) - 2017:06:25 11:38:35
Exposure Mode - Auto
Sub Sec Time Digitized - 770261
Scene Capture Type - Standard
Scene Type - Directly photographed
Sub Sec Time Original - 770261
Exposure Index - 0
White Balance - Auto
Sub Sec Time - 770261
Metering Mode - Center-weighted average
Date and Time (Original) - 2017:06:25 11:38:35
Components Configuration - Y, Cb, Cr, -
Exif Version - 0220
Exposure Bias - 0 EV
Brightness Value - 0
ISO Speed - 50
Sensing Method - One-chip color area
Flashpix Version - 0100
Interop Index - R98 - DCF basic file (sRGB)
Interop Version - 0100
Thumbnail Length - 12490
Thumbnail Offset - 23180


I had verified this point previously
Thank you in advance for any clue

**Comment by pdfext** [comment]
You were right, the picture contained no geotag
So it was my fault !
Thank you !
