### ISSUE TITLE
Data from OpenStreetMap (CSV / GeoJson) with @ in fields

### ISSUE THREAD

**Issue by sylvain-m** [umap-project/umap#503]
Hi,
Umap is really great, but I have a small recurring difficulty with data from OpenStreetMap* (GeoJson, CSV, ...).
If I want to use the fields "@id", "@lat" and "@lon" (in the popup), I am obliged to manually rename these fields by manually removing the at sign (@).
Is there a way to use these fields in the popup? (without renaming)

Sylvain M.

(*) generated from Overpass Turbo for example

**Comment by sylvain-m** [comment]
After a few years, I'm bringing this subject up again.
I would like to make the link between the objects on my map and the OSM database, but it doesn't seem possible at the moment.

The URLs are the following:
https://www.openstreetmap.org/way/614811615
which corresponds to :
https://www.openstreetmap.org/{@id}
Since the @id field is present in base, with values in "way/614811615" format (geojson from Overpass)

But the popup does not convert the {@id} field.

Do you have a solution?

**Comment by carlbacker** [comment]
I have sort of the same problem, but more inconsistent.

When I look at `@id` value references in the wiki and guide, they are shown and meant to work without the `@` as `{id}` : [example](https://wiki.openstreetmap.org/wiki/UMap/Tips). This works well in my dynamic overpass layers for `{id}` but not for other keys that have the same character (in my case `{@geometry}` ), and still not for static json layers imported from overpass.

A workaround for regular imported layers is to rename the table header, which I only have to do once and it makes every reference work, but I haven't been able to do that for dynamic layers.

At the same time `{lat}` and `{lon}` without `@` works flawlessly in all kinds of layers, I never have to change those. So there seems to me to be some kind of bug making this not always behave as expected?

**Comment by yohanboniface** [comment]
Should have been fixed by #1217
