### ISSUE TITLE
Empty sidepanel on load when using URL parameters

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#504]
Some iframes with parameters display neither caption nor databrowser on load. 

E.g this code : 

    <iframe src="https://umap.openstreetmap.fr/fr/map/implantation-de-linserm_96589?datalayers=229164%2C229163%2C229158%2C229156%2C236803%2C229157" width="1000" height="800"></iframe> 

Will render like that on load : 
![umapiframeissue-2017-08-07-15-39-03](https://user-images.githubusercontent.com/17235663/29030535-a42541b4-7b8b-11e7-8e09-3bba8fa81b5a.png)

Instead of looking like this :
![umapiframeissue2-2017-08-07-15-39-03](https://user-images.githubusercontent.com/17235663/29030400-1d946990-7b8b-11e7-95f0-2ecb0aa028e8.png)

Normal rendering resumes after clicking "About" or "Browse data". F5 doesn't change anything.

Issue encountered on FF & Chrome (desktop + mobile), on multiple devices and uMaps.

**Comment by yohanboniface** [comment]
I see the caption:

![screen shot 2017-08-09 at 18 30 15-fullpage](https://user-images.githubusercontent.com/146023/29132544-d1d00bca-7d30-11e7-8d2e-a65901b5a113.png)

What should I see instead?

**Comment by druxstr** [comment]
I was expecting the visible layer name and description to showup (the red square part). I always thought it was a part of the caption, as the URL parameter `onLoadPanel=caption` usually ends up displaying the general map caption *and* each layer infos.

![umapmissinglayercaption-2017-08-10-08-18-17](https://user-images.githubusercontent.com/17235663/29157280-7b25a818-7da6-11e7-83e0-574c9f95b35e.png)

**Comment by yohanboniface** [comment]
Oh, right, missed that point, now it's clear, thanks!
