### ISSUE TITLE
How to put the same marker in differents layers with umap?

### ISSUE THREAD

**Issue by AdrianG19** [umap-project/umap#505]
Hello,
I'm totally new with code... I have created a map with umap which contains many markers. Now I want to place them into layers. The problem is that you can only put them in one layer. Is it a way to put a marker in different layers?
thanks

**Comment by yohanboniface** [comment]
Nope, there is no way to do that :(
Marker inherit many things from the layer (color and co), so it would change a lot of thing to have multiple inheritance.
Closing as I don't think it may happen soon.

**Comment by AdrianG19** [comment]
Ok thank you,
By the way I have another question: when I use the gps position to find my own position, why there is no dot? The position is good but no dot?
