### ISSUE TITLE
Versions missing

### ISSUE THREAD

**Issue by timoto** [umap-project/umap#507]
If I click save whilst drawing a path, the data for the path is overwritten with no data.

When I attempt to retrieve a previous version of the layer, nothing is listed under the layer's versions, please help !!!

Thanks

**Comment by yohanboniface** [comment]
This generally is a cache issue when working behind a bad configured proxy.
So, for debugging, trying from another network (your phone for example) and another browser and another computer may give some hints about the guilty bit.
Also, an URL may help me to help you…

**Comment by timoto** [comment]
I had no choice for network (phone only where I am), but changed OS and thus browser. Now I can see the other versions.

Thanks for the support :)
