### ISSUE TITLE
Improvement: fixing the annoying "Problem with server response" red flag

### ISSUE THREAD

**Issue by severinmenard** [umap-project/umap#510]
This red flag (see below) shows up due to, I guess, a time-out for remote data (overpass in this case, from zoom 14: https://umap.openstreetmap.fr/fr/map/carteinnov-suivi-d-ynamique-de-la-cartographie-open_110969#16/14.7514/-17.4568). It does spoil the map though it is not useful, because actually the data from Overpass does show up a few seconds later. Is there not a way, either to increase the time-out duration, either allowing to deactivate this flag, or put this info in the admin console and not in the middle of the map?

![selection_177](https://user-images.githubusercontent.com/1291055/29635115-5f9219b6-8822-11e7-97eb-988977b9911d.png)

**Comment by yohanboniface** [comment]
This should be fixed by the commit above, allowing to cache remote URLs locally.
