### ISSUE TITLE
Error: OSM-layer in self-created maps does no longer show

### ISSUE THREAD

**Issue by webmeist** [umap-project/umap#511]
Since a few days, the maps I created are no longer visible with the underlying OSM data, only the POI´s I created are displayed. This occurs in my umap account, but also in all websites in which I embedded the data via iframe. This has occurred after working for a long time and I did not make any changes to the maps recently.

Hope you can resolve this problem, as my projects are dependent on these maps.

username: tb17

**Comment by yohanboniface** [comment]
Having a link to a map showing the issue may help ;)

It may be because of an overpass rate limit.

**Comment by webmeist** [comment]
After more than a week, the map display is back to normal now. My feeling is that this was caused by server performance problems, as also the umap services were very slow at this time. I am very happy that everything seems to work again.
Umap is great and I really love it!
