### ISSUE TITLE
Umap / Bing aerial background

### ISSUE THREAD

**Issue by ThierryPayet974** [umap-project/umap#514]
I want to create a map with Umap using Bing aerial image as the background. The map will display the places and related stories of the migrants who are now in Paris, France, but no geographical information. As I only intend to use the background image with no additional information (no names, no place, nothing) there shouldn't be any copyright problem with Bing. Does someone know what URL I should write for Bing in the related box in Umap ? Or does someone have an alternative solution / tool to create such a map ?

**Comment by yohanboniface** [comment]
AFAIK, there is no XYZ URL (scheme used by uMap) for Bing, you'd need a proxy. Or you can create an account on Mapbox to use their satellite image.
