### ISSUE TITLE
Embedded fullscreen: `allowfullscreen`

### ISSUE THREAD

**Issue by kousu** [umap-project/umap#516]
On Firefox 55 (and presumably lots of other modern browsers), an `<iframe>` needs to be written `<iframe allowfullscreen="allowfullscreen" ...>` for its content to be allowed to fullscreen itself. The current embed-code generator in uMap (or what I assume is current; I found this while using https://framacarte.org) does _not_ know to add this attribute when `fullscreenControl=true`, but without it the fullscreen control is neutered and useless.

Adding this tag manually to my uMap embeds makes fullscreening work beautifully. It's actually rather impressive to have a little map on my website pop out in full glory.

**Comment by yohanboniface** [comment]
>  It's actually rather impressive to have a little map on my website pop out in full glory.

:)

Right, I'll add it! (But PRs are also welcome ;) ).
