### ISSUE TITLE
Demo linked from homepage goes into re-render loop

### ISSUE THREAD

**Issue by tomfitzhenry** [umap-project/umap#517]
http://umap.openstreetmap.fr/en/map/fjklfjalkfj_1 repeatedly re-renders/re-directs the map. It looks like a point on the map is repeatedly being selected/de-selected.

Reproduced with Chrome 57.0.2987.133 on OSX 10.12 and Firefox 55.0.2 on Android 7.0.

**Comment by yohanboniface** [comment]
I can't reproduce, but it may be because of the limit bounds and rounding issues with your browser/screen resolution/….
Try removing the limit bounds and see if it fix it.

**Comment by tomfitzhenry** [comment]
It has miraculously fixed itself on both devices. Woo!
