### ISSUE TITLE
Bad recommendation in install.md

### ISSUE THREAD

**Issue by anayrat** [umap-project/umap#519]
Hello,

I notice you recommends to change definition of unaccent(text) and to_tsvector(text) from STABLE to IMMUTABLE : [install.md](https://github.com/umap-project/umap/blob/master/docs/install.md#search)

Generally, it is a bad idea to change system's function definition. If your user had other applications in the same database (they share same function), theses changes could lead to logical index corruption.

See this thread for [unaccent](https://www.postgresql.org/message-id/flat/201012021544.oB2FiTn1041521%40wwwmaster.postgresql.org#201012021544.oB2FiTn1041521@wwwmaster.postgresql.org)

Or this explanation on stackoverflow : [unaccent() only STABLE not IMMUTABLE](https://stackoverflow.com/questions/11005036/does-postgresql-support-accent-insensitive-collations/11007216#11007216)

And this one for [to_tsvector](https://www.postgresql.org/message-id/flat/200805230830.m4N8Uble097183%40wwwmaster.postgresql.org#200805230830.m4N8Uble097183@wwwmaster.postgresql.org)

If you really want to create an index with theses functions, you need to use those that are immutables:

  * For `to_tsvector` you can use `to_tsvector('english', body)` (or other language, it depends of your configuration). [Explanation](https://www.postgresql.org/docs/current/static/textsearch-tables.html#TEXTSEARCH-TABLES-INDEX)
  * For `unaccent`, there is no "easy" solution. However we can use a workaround to prevent users changing unaccent function for the whole database:

You can create a wrapper based on unaccent and mark it as IMMUTABLE. **This function must only be used by umap**:
```sql
CREATE OR REPLACE FUNCTION umap_unaccent(text)
RETURNS text AS
$func$
SELECT public.unaccent('public.unaccent', $1)
$func$  LANGUAGE sql IMMUTABLE;
```
(From stackoverflow as mentionned above)

And then you should be able to create functionnal index:
```sql
CREATE INDEX search_idx ON leaflet_storage_map USING gin(to_tsvector('english',umap_unaccent(name)), share_status);
```

Of course, you will have to change your queries to call rights functions.

Regards,

**Comment by anayrat** [comment]
Oh, I looked at : https://github.com/umap-project/umap/blob/c854c98e493154a9474b2f4b60e4ed6cb6dab049/umap/views.py#L158

You can also create specific full text search configuration for umap and apply unaccent directly inside configuration : 

```sql
CREATE TEXT SEARCH CONFIGURATION umap_fts ( COPY = english );
ALTER TEXT SEARCH CONFIGURATION umap_fts ALTER MAPPING FOR hword, hword_part, word WITH unaccent,english_stem;
select to_tsvector('umap_fts','Fooééô');
 to_tsvector 
-------------
 'fooeeo':1
(1 row)
```

**Comment by yohanboniface** [comment]
Pull requests welcome ;)

**Comment by yohanboniface** [comment]
Should be good on master!
