### ISSUE TITLE
UMap planté pour les projets HOT

### ISSUE THREAD

**Issue by verdy-p** [umap-project/umap#520]
signalé sur https://hotosm.slack.com/messages/C042TUWCV/convo/C4MMB6PD4-1507161772.000085/

UMap semble planté pour la mise à jour des cartes de projets HOT.

Signalé aussi sur la mailing list francophone

**Comment by AdrianG19** [comment]
Umap ne fonctionne toujours pas..

**Comment by yohanboniface** [comment]
Restarted, thanks for the ping!
