### ISSUE TITLE
Host UMap on URL with prefix (e.g. example.com/umap)

### ISSUE THREAD

**Issue by knowname** [umap-project/umap#522]
i couldn't find much information on placing umap not at the root, but at a URL with prefix like http://example.com/umap. 
Currently i am using apache as webserver and wsgi as python interface.

To get this working i had to configure the webserver accordingly, but i also had to fiddle with the umap code.

The django documentation tells you to put `FORCE_SCRIPT_NAME = '/umap'` in the `umap.conf` file in order to get the prefix working.  The problem is that the buttons ("Save", "Cancel", ...) aren't working. 

The essential parts of `umap.conf`:
```
STATIC_ROOT = '/srv/umap/var/static'
STATIC_URL = '/umap/static/'
FORCE_SCRIPT_NAME = '/umap'
SITE_BASE_URL = "http://example.com/"
SITE_URL = "http://example.com/umap/"
```

To fix the buttons i modified the function 
 `_urls_for_js` at [line 51](https://github.com/umap-project/django-leaflet-storage/blob/c81972e524b1e09ffca355bfb7edfdede42dcc59/leaflet_storage/views.py#L51) by adding FORCE_SCRIPT_NAME as prefix parameter.
```
leaflet_storage/views.py:43
def _urls_for_js(urls=None): 
    # [...]
    urls = dict(zip(urls, [get_uri_template(url, prefix=settings.FORCE_SCRIPT_NAME) for url in urls]))
    # [...]
```
Finally i had to fix the `full_secret_link` located in [`leaflet_storage/forms.py` at line 42](https://github.com/umap-project/django-leaflet-storage/blob/master/leaflet_storage/forms.py#L42) by introducing and using the SITE_BASE_URL instead of the SITE_URL and clearing extra slashes.
```
full_secret_link = "%s%s" % (settings.SITE_BASE_URL, self.instance.get_anonymous_edit_url().strip("/"))
```

hope i could be of some help for anybody :)  cheers

**Comment by rory** [comment]
Has there been any work on supporting this feature?

**Comment by yohanboniface** [comment]
@knowname would you mind putting all that in PR ? :)
