### ISSUE TITLE
howto recover map access

### ISSUE THREAD

**Issue by C138** [umap-project/umap#525]
Hi
Seems to be (too!) easy to lost the write access to a map ... :-(

While switching from public to private editing, I clicked too quickly on "send" button...
Now I have no more access to edit button and didn't know (note) the private key!
  
How can I recover access to a map ? ... When there is no "factual" link to an account or a mail address or...

Thanks for any hint/help
Switching to private edition should'nt be allowed before defining a way (mail / account) to restore grant access.
[Unless I missed something]
Cheers

**Comment by yohanboniface** [comment]
Which map?

**Comment by vinber** [comment]
closed :)  https://framasphere.org/posts/4035460

**Comment by yohanboniface** [comment]
ok thanks :)
