### ISSUE TITLE
Enable editing button on right-side not appearing

### ISSUE THREAD

**Issue by neomodern** [umap-project/umap#526]
First edit of a map is fine, however when trying to use the link to a previously created map I usually find the enable editing button is missing.

I've tried reusing the link generated when a map is first saved, as well as the link in the 'Map permissions' area. With both types of links I've found that the 'enable editing' button/all buttons on the right-side menu don't appear.

**Comment by yohanboniface** [comment]
Can you give the map URL so I'll have a look?

**Comment by yohanboniface** [comment]
Closing as inactive.
