### ISSUE TITLE
umap problem with internet explorer v 11

### ISSUE THREAD

**Issue by mauropreda** [umap-project/umap#528]
The web site at this address: 
http://sistra.cittametropolitana.mi.it:8000/it/
work perfectly  with the browser Firefox, Chrome, Opera.  Only Internet Explorer (v. 11)  not work! :((

Thank you!

**Comment by yohanboniface** [comment]
Sorry!
Can you elaborate a bit: what action are you trying to do (view map, edit something…), and what error do you have in the console?
