### ISSUE TITLE
user created maps can make the main page inaccessible

### ISSUE THREAD

**Issue by datendelphin** [umap-project/umap#530]
We just had that issue on umap.osm.ch

Someone created a map with a lot of data, which took more than 10 seconds to load, and even after loading the page remained largely unresponsive. This was unintentional, but one could easily use this loop hole to make the main page inaccessible to users with a large enough map. There should be some time limit for those maps to load and limits on the amount of data which is drawn to prevent an unusable main page.

**Comment by Binnette** [comment]
Yes, I also experiment the same lag issue on main page.

**Comment by yohanboniface** [comment]
This can be now handled by the `UMAP_HOME_FEED` new option: https://docs.umap-project.org/en/master/config/settings/#umap_home_feed
