### ISSUE TITLE
Import KML / Différencier folder

### ISSUE THREAD

**Issue by RomainLalande** [umap-project/umap#531]
Hello,

Lors d'un import KML qui sépare à la base différents calques dans différents folder avec  @Cyrille37 , l'import met tout sur le même calque : est-ce voulu ? Est-ce un bug ? Serait-ce cohérent que chaque folder soit plutôt importé dans un calque différent ? 
Belle journée ! 
Romain :)

**Comment by yohanboniface** [comment]
Suis pas sûr d'avoir compris :/
C'est quoi un "folder" dans ce contexte?

**Comment by Cyrille37** [comment]
Bonjour
Dans un fichier KML des ensembles de `PlaceMarker` sont regroupés en `Folder` ce qui correspond à des calques de données.
```
kml.Document.Folder
kml.Document.Folder.Placemark
```

Cheers.

**Comment by yohanboniface** [comment]
OK.
Malheureusement, uMap utilise la librairie [togeojson](https://github.com/mapbox/togeojson), qui ne semble pas parser cette information, voir https://github.com/mapbox/togeojson/issues/64

**Comment by Cyrille37** [comment]
J'ai compris que c'est parce que le format GeoJSON ne défini pas le concept de calques (folders) que cette distinction n'est pas implémentée. Quel dommage.

Donc pour les utilisateurs, le mode d'emploi serait à l'aide d'un éditeur de texte d'extraire les différents "folder" dans différents fichiers KML.

et Merci encore pour ce fabuleux uMap !

**Comment by RomainLalande** [comment]
Oh oui, merci <3
Et grâce à @Cyrille37 on sait comment faire avec le KML à la main à #Tours :p
