### ISSUE TITLE
502 bad gateway error

### ISSUE THREAD

**Issue by christrillium** [umap-project/umap#532]
http://umap.openstreetmap.fr/ 
Umap sites are returning a 502 error. We are working on a community mapping project that relies (desperately) on our umap being up and running tomorrow morning. Can this be addressed?

Many thanks,
Chris

**Comment by phi-gamma** [comment]
Confirmed, the nginx 502 page for me as well.

**Comment by yohanboniface** [comment]
Ooops, sorry, seems up now.
