### ISSUE TITLE
Feature-Request: Export/Backup

### ISSUE THREAD

**Issue by flaschenpost** [umap-project/umap#533]
It would be great to have an export or backup functionality. Maybe it's there and I can't find it, but if it is missing and not too complicated, it would be good to have.

Just the json you probably use internally is good.

**Comment by yohanboniface** [comment]
The `umap` format download is made for that.
You need to open the "share" box, and then choose "umap" as download format (instead of json or kml for example).

**Comment by flaschenpost** [comment]
Ah, under "Share" - many thanks for quick response - my fault!
