### ISSUE TITLE
Can not save edited map.

### ISSUE THREAD

**Issue by Shourov7** [umap-project/umap#536]
I have installed the local instance Umap in my computer OS is Ubuntu 16.04. While I want to save the edited map in my computer then it shows "problem in the response". What should I do?

**Comment by yohanboniface** [comment]
Can you paste the response?

**Comment by Duvel** [comment]
I think I had the same problem, could you check the logs of uwsgi? It showed me an error about wrong folders.

**Comment by Duvel** [comment]
This is how I fixed my problem:

https://github.com/umap-project/umap/pull/544/commits/1d4fe98e2855b538ad0424748d73eed8618ded32

**Comment by yohanboniface** [comment]
Closing as inactive.
