### ISSUE TITLE
Map Changes not Saving

### ISSUE THREAD

**Issue by bmonson32** [umap-project/umap#537]
Every time I try to edit my map, the changes don't stay. I'll hit save, and it will tell me the save was successful, but when I reload the map the changes I made are no longer there.  Other times, when I try to save it will give me the error message:
![screen shot 2017-12-31 at 13 03 38](https://user-images.githubusercontent.com/34988576/34463759-da3bbb58-ee2b-11e7-90d4-d1b9e3d08d5d.jpg)

I am the only user and only editor of my map. It is currently embedded on an external website as well.  Here is the link to my map:
https://umap.openstreetmap.fr/en/map/pavement-hunters_176648#6/46.301/-95.054

**Comment by yohanboniface** [comment]
This looks like your are working behing a proxy, which does aggressive caching.
Can you try from another network (your phone connection for example) / another browser / another device? And report here the differences. Thanks.

**Comment by yohanboniface** [comment]
Closing as inactive.
