### ISSUE TITLE
speed up loading of umap layer data

### ISSUE THREAD

**Issue by ajRiverav** [umap-project/umap#540]
If the data to be displayed in a layer is large in size (e.g. a 100Mb geojson), it may take a while for the data to be loaded up on the client web browser, especially in low-bandwidth situations, because uMap sends the whole file to the client at least once. 

I propose a solution that should work at least when using the remote data setting: allow for the compression/decompression of the data.

For example, in my application I use the remote data setting. I would specify the URL that points to the compressed file. uMap would then send this compressed file to the client and decompression would occur on the client. I have seen geojson files of about 100Mb in size be reduced to 30Mb after compression.

**Comment by yohanboniface** [comment]
This should already be the case:

```
$ http --headers https://umap.openstreetmap.fr/en/datalayer/364321/                                                                                                                                                                1ms
HTTP/1.1 200 OK
Cache-Control: must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Language: en
Content-Length: 1563
Content-Type: application/json
Date: Tue, 09 Jan 2018 10:00:07 GMT
ETag: c3c10876824b3b06b6dbe0d728a750b6
Last-Modified: Thu, 05 Oct 2017 08:07:26 GMT
Server: nginx
```

See `Content-Encoding: gzip`.
