### ISSUE TITLE
Aberrant result in search

### ISSUE THREAD

**Issue by lamixorp** [umap-project/umap#541]
Following issue #539

Search in now ok, but result is aberrant. Seems to be searching on other field than location.

**Comment by yohanboniface** [comment]
Thanks for the report, but there is little uMap can do about this.
Try your search on [Photon demo page](http://photon.komoot.de/) and open an issue on Photon repository instead, **with more details**: "result is aberrant" is not really helpful. At bare minimum, give an example search, the result you expect, and the actual result you have.
Thanks!
