### ISSUE TITLE
Insert HTML into popup / Sidebar

### ISSUE THREAD

**Issue by simogeo** [umap-project/umap#542]
Hi, 
First of all, thanks for umap - great tool !

I'd like to know if there is a way to insert pure html as _description_. Not sure I can since I've read that : 

>     *simple astérisque pour italique*
>     **double astérisque pour gras**
>     # un dièse pour titre 1
>     ## deux dièses pour titre 2
>     ### trois dièses pour titre 3
>     Lien simple: [[https://exemple.fr]]
>     Lien avec texte: [[http://exemple.fr|texte du lien]]
>     Image: {{http://image.url.com}}
>     Image avec largeur (en pixels) : {{http://image.url.com|largeur}}
>     Iframe: {{{http://iframe.url.com}}}
>     Iframe avec hauteur (en pixels): {{{http://iframe.url.com|hauteur}}}
>     Iframe avec hauteur et largeur (en px): {{{http://iframe.url.com|height*width}}}
>     --- pour un séparateur horizontal

The only way would be to use an iframe as container ?
Thanks for support

**Comment by yohanboniface** [comment]
Sorry, no, this is not possible.
Allowing arbitrary HTML can have a bunch of subtle issues (security, stability, design, hard to debug situations…) I preferred to stay out for now.

Using a custom iframe is indeed a workaround.

See also #414

**Comment by simogeo** [comment]
I was waiting for that kind of reply ... ;-) 

Will try iframe as workaround ! Thanks for your fast answer.
