### ISSUE TITLE
Ubuntu Server

### ISSUE THREAD

**Issue by flaviomx14** [umap-project/umap#545]
Hello All! I have installed a uMap in Ubuntu 16.04. How can i edit the default website page?
I have changed the dir /srv/umap/venv/lib/python3.5/site-packages/umap/template but then changes have no effect.
Whats the way to do this?

**Comment by yohanboniface** [comment]
See https://github.com/etalab/cartes.data.gouv.fr as an example of templating uMap.

**Comment by flaviomx14** [comment]
Thank you for the fast answer! Sorry but i dont understood your answer. Can you explain me where i can make changes to edit my html page, logo, etc. Thank my friend!
