### ISSUE TITLE
Secret Key

### ISSUE THREAD

**Issue by flaviomx14** [umap-project/umap#546]
Hi All!

I have installed a Umap in my Ubuntu Server 16.04. On tutorial, i need Add a real SECRET_KEY
In your local.py file, add a real secret and unique SECRET_KEY, and do not share it.
What key is this? Do I have to create one?

When I change inside the page / admin some parameter, as for example:
The owner of some map, the system returns me error and does not write this change.

Was it because of this key?

Thanks

**Comment by yohanboniface** [comment]
See https://stackoverflow.com/questions/7382149/purpose-of-django-setting-secret-key

> Was it because of this key?

No idea. What error message do you have? Have you turned DEBUG on?

**Comment by flaviomx14** [comment]
Yes, i am in Debug mode. Without debug mode, the system return a page “ops, server error”

This is the answer:

JSONDecodeError at /admin/leaflet_storage/map/3/change/

Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Request Method: POST
Request URL:    http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/
Django Version: 1.11
Exception Type: JSONDecodeError
Exception Value:

Expecting property name enclosed in double quotes: line 1 column 2 (char 1)


Exception Location:     /usr/lib/python3.5/json/decoder.py in raw_decode, line 355
Python Executable:      /usr/bin/uwsgi-core
Python Version: 3.5.2
Python Path:

['.',
 '',
 '/srv/umap/venv/lib/python35.zip',
 '/srv/umap/venv/lib/python3.5',
 '/srv/umap/venv/lib/python3.5/plat-x86_64-linux-gnu',
 '/srv/umap/venv/lib/python3.5/lib-dynload',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/srv/umap/venv/lib/python3.5/site-packages']


Server time:    Ter, 23 Jan 2018 19:07:11 +0000
Traceback Switch to copy-and-paste view<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>

  *   /srv/umap/venv/lib/python3.5/site-packages/django/core/handlers/exception.py in inner
     *

            response = get_response(request)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/core/handlers/base.py in _legacy_get_response
     *

            response = self._get_response(request)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response
     *

                response = self.process_exception_by_middleware(e, request)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response
     *

                response = wrapped_callback(request, *callback_args, **callback_kwargs)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/contrib/admin/options.py in wrapper
     *

                return self.admin_site.admin_view(view)(*args, **kwargs)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/utils/decorators.py in _wrapped_view
     *

                    response = view_func(request, *args, **kwargs)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/views/decorators/cache.py in _wrapped_view_func
     *

        response = view_func(request, *args, **kwargs)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/contrib/admin/sites.py in inner
     *

            return view(request, *args, **kwargs)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/contrib/admin/options.py in change_view
     *

        return self.changeform_view(request, object_id, form_url, extra_context)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/utils/decorators.py in _wrapper
     *

            return bound_func(*args, **kwargs)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/utils/decorators.py in _wrapped_view
     *

                    response = view_func(request, *args, **kwargs)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/utils/decorators.py in bound_func
     *

                return func.__get__(self, type(self))(*args2, **kwargs2)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/contrib/admin/options.py in changeform_view
     *

            return self._changeform_view(request, object_id, form_url, extra_context)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/contrib/admin/options.py in _changeform_view
     *

            if form.is_valid():

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/forms/forms.py in is_valid
     *

        return self.is_bound and not self.errors

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/forms/forms.py in errors
     *

            self.full_clean()

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/forms/forms.py in full_clean
     *

        self._post_clean()

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/forms/models.py in _post_clean
     *

            self.instance.full_clean(exclude=exclude, validate_unique=False)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/db/models/base.py in full_clean
     *

            self.clean_fields(exclude=exclude)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/db/models/base.py in clean_fields
     *

                setattr(self, f.attname, f.clean(raw_value, self))

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/django/db/models/fields/__init__.py in clean
     *

        value = self.to_python(value)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /srv/umap/venv/lib/python3.5/site-packages/leaflet_storage/fields.py in to_python
     *

            return json.loads(value)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /usr/lib/python3.5/json/__init__.py in loads
     *

        return _default_decoder.decode(s)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /usr/lib/python3.5/json/decoder.py in decode
     *

        obj, end = self.raw_decode(s, idx=_w(s, 0).end())

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>
  *   /usr/lib/python3.5/json/decoder.py in raw_decode
     *

            obj, end = self.scan_once(s, idx)

...
▶ Local vars<http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/#>

Request information
USER
umap
GET
No GET data
POST
Variable        Value
owner

'2'


slug

'four-rastreamento-ltda'


center

'SRID=3857;POINT(-45.999999998968704 -20.999999999810154)'


name

'Four Rastreamento Ltda'


zoom

'7'


csrfmiddlewaretoken

'BBcXiPF3xBb17p09bhVcRHnPA2gzpV6us9PPKh2QVbD47eysq7aNXfKehCr3IAwq'


edit_status

'2'


tilelayer

''


OpenLayers_Control_LayerSwitcher_65_baseLayers

'OpenStreetMap (Mapnik)'


initial-licence

'2'


settings

("{'properties': {'moreControl': True, 'scrollWheelZoom': True, 'zoomControl': "
 "True, 'zoom': 7, 'name': 'Four Rastreamento Ltda', 'color': 'Brown', "
 "'captionBar': False, 'miniMap': False, 'searchControl': True, "
 "'displayPopupFooter': False, 'limitBounds': {}, 'embedControl': True, "
 "'slideshow': {}, 'iconClass': 'Drop', 'datalayersControl': True, "
 "'fullscreenControl': True, 'description': 'Machado,MG', 'licence': '', "
 "'scaleControl': True, 'tilelayer': {}, 'easing': True}, 'geometry': "
 "{'coordinates': [-46, -21], 'type': 'Point'}, 'type': 'Feature'}")


description

''


_save

'Gravar'


licence

'2'


share_status

'1'


FILES
No FILES data
COOKIES
Variable        Value
csrftoken

'G864LScWJP8PUsTEoOcp7TThHaW3JftHxGJWdkzJ7pASUhrXDEr0drgGoK7x2UTD'


messages

('097bed570e6571508a7e408cc56f24766808b40a$[["__json_message",1,25,"The '
 'utilizador \\"<a href=\\"/admin/auth/user/2/change/\\">flavio</a>\\" was '
 'changed successfully."],["__json_message",1,25,"The utilizador \\"<a '
 'href=\\"/admin/auth/user/1/change/\\">umap</a>\\" was changed '
 'successfully."]]')


sessionid

'hcieq4086qv8avkay2f1awqrdhl7wsuc'


META
Variable        Value
CONTENT_LENGTH

'2360'


CONTENT_TYPE

'multipart/form-data; boundary=----WebKitFormBoundaryzVg8kIYgB2ay03Vd'


CSRF_COOKIE

'G864LScWJP8PUsTEoOcp7TThHaW3JftHxGJWdkzJ7pASUhrXDEr0drgGoK7x2UTD'


DOCUMENT_ROOT

'/usr/share/nginx/html'


HTTP_ACCEPT

'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'


HTTP_ACCEPT_ENCODING

'gzip, deflate'


HTTP_ACCEPT_LANGUAGE

'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7'


HTTP_CACHE_CONTROL

'max-age=0'


HTTP_CONNECTION

'keep-alive'


HTTP_CONTENT_LENGTH

'2360'


HTTP_CONTENT_TYPE

'multipart/form-data; boundary=----WebKitFormBoundaryzVg8kIYgB2ay03Vd'


HTTP_COOKIE

('messages="097bed570e6571508a7e408cc56f24766808b40a$[[\\"__json_message\\"\\0541\\05425\\054\\"The '
 'utilizador \\\\\\"<a '
 'href=\\\\\\"/admin/auth/user/2/change/\\\\\\">flavio</a>\\\\\\" was changed '
 'successfully.\\"]\\054[\\"__json_message\\"\\0541\\05425\\054\\"The '
 'utilizador \\\\\\"<a '
 'href=\\\\\\"/admin/auth/user/1/change/\\\\\\">umap</a>\\\\\\" was changed '
 'successfully.\\"]]"; sessionid=hcieq4086qv8avkay2f1awqrdhl7wsuc; '
 'csrftoken=G864LScWJP8PUsTEoOcp7TThHaW3JftHxGJWdkzJ7pASUhrXDEr0drgGoK7x2UTD')


HTTP_HOST

'emap.4tracking.com.br<http://emap.4tracking.com.br>'


HTTP_ORIGIN

'http://emap.4tracking.com.br'


HTTP_REFERER

'http://emap.4tracking.com.br/admin/leaflet_storage/map/3/change/'


HTTP_UPGRADE_INSECURE_REQUESTS

'1'


HTTP_USER_AGENT

('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, '
 'like Gecko) Chrome/63.0.3239.132 Safari/537.36')


PATH_INFO

'/admin/leaflet_storage/map/3/change/'


QUERY_STRING

''


REMOTE_ADDR

'187.73.165.249'


REMOTE_PORT

'64391'


REQUEST_METHOD

'POST'


REQUEST_SCHEME

'http'


REQUEST_URI

'/admin/leaflet_storage/map/3/change/'


SCRIPT_NAME

''


SERVER_NAME

'emap.4tracking.com.br<http://emap.4tracking.com.br>'


SERVER_PORT

'80'


SERVER_PROTOCOL

'HTTP/1.1'


uwsgi.node

b'eMap'


uwsgi.version

b'2.0.12-debian'


wsgi.errors

<_io.TextIOWrapper name=2 mode='w' encoding='UTF-8'>


wsgi.file_wrapper

''


wsgi.input

<uwsgi._Input object at 0x7fdecbe99420>


wsgi.multiprocess

True


wsgi.multithread

False


wsgi.run_once

False


wsgi.url_scheme

'http'


wsgi.version

(1, 0)


Settings
Using settings module umap.settings
Setting Value
ABSOLUTE_URL_OVERRIDES

{}


ADMINS

(('flavio', 'flavio@4rastreamento.com.br<mailto:flavio@4rastreamento.com.br>'),)


ALLOWED_HOSTS

['*']


APPEND_SLASH

True


AUTHENTICATION_BACKENDS

('social_core.backends.github.GithubOAuth2',
 'social_core.backends.bitbucket.BitbucketOAuth',
 'social_core.backends.twitter.TwitterOAuth',
 'social_core.backends.openstreetmap.OpenStreetMapOAuth',
 'django.contrib.auth.backends.ModelBackend')


AUTH_PASSWORD_VALIDATORS

'********************'


AUTH_USER_MODEL

'auth.User'


CACHES

{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}


CACHE_MIDDLEWARE_ALIAS

'default'


CACHE_MIDDLEWARE_KEY_PREFIX

'********************'


CACHE_MIDDLEWARE_SECONDS

600


COMPRESS_CACHEABLE_PRECOMPILERS

()


COMPRESS_CACHE_BACKEND

'default'


COMPRESS_CACHE_KEY_FUNCTION

'********************'


COMPRESS_CLEAN_CSS_ARGUMENTS

''


COMPRESS_CLEAN_CSS_BINARY

'cleancss'


COMPRESS_CLOSURE_COMPILER_ARGUMENTS

''


COMPRESS_CLOSURE_COMPILER_BINARY

'java -jar compiler.jar'


COMPRESS_CSS_COMPRESSOR

'compressor.css.CssCompressor'


COMPRESS_CSS_FILTERS

['compressor.filters.css_default.CssAbsoluteFilter']


COMPRESS_CSS_HASHING_METHOD

'mtime'


COMPRESS_DATA_URI_MAX_SIZE

1024


COMPRESS_DEBUG_TOGGLE

None


COMPRESS_ENABLED

False


COMPRESS_JINJA2_GET_ENVIRONMENT

<function CompressorConf.JINJA2_GET_ENVIRONMENT at 0x7fdecbe0e1e0>


COMPRESS_JS_COMPRESSOR

'compressor.js.JsCompressor'


COMPRESS_JS_FILTERS

['compressor.filters.jsmin.JSMinFilter']


COMPRESS_MINT_DELAY

30


COMPRESS_MTIME_DELAY

10


COMPRESS_OFFLINE

True


COMPRESS_OFFLINE_CONTEXT

{'STATIC_URL': '/static/'}


COMPRESS_OFFLINE_MANIFEST

'manifest.json'


COMPRESS_OFFLINE_TIMEOUT

31536000


COMPRESS_OUTPUT_DIR

'CACHE'


COMPRESS_PARSER

'compressor.parser.AutoSelectParser'


COMPRESS_PRECOMPILERS

()


COMPRESS_REBUILD_TIMEOUT

2592000


COMPRESS_ROOT

'/home/srv/var/static'


COMPRESS_STORAGE

'compressor.storage.CompressorFileStorage'


COMPRESS_TEMPLATE_FILTER_CONTEXT

{'STATIC_URL': '/static/'}


COMPRESS_URL

'/static/'


COMPRESS_VERBOSE

False


COMPRESS_YUGLIFY_BINARY

'yuglify'


COMPRESS_YUGLIFY_CSS_ARGUMENTS

'--terminal'


COMPRESS_YUGLIFY_JS_ARGUMENTS

'--terminal'


COMPRESS_YUI_BINARY

'java -jar yuicompressor.jar'


COMPRESS_YUI_CSS_ARGUMENTS

''


COMPRESS_YUI_JS_ARGUMENTS

''


CSRF_COOKIE_AGE

31449600


CSRF_COOKIE_DOMAIN

None


CSRF_COOKIE_HTTPONLY

False


CSRF_COOKIE_NAME

'csrftoken'


CSRF_COOKIE_PATH

'/'


CSRF_COOKIE_SECURE

False


CSRF_FAILURE_VIEW

'django.views.csrf.csrf_failure'


CSRF_HEADER_NAME

'HTTP_X_CSRFTOKEN'


CSRF_TRUSTED_ORIGINS

[]


CSRF_USE_SESSIONS

False


DATABASES

{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.contrib.gis.db.backends.postgis',
             'HOST': '',
             'NAME': 'umap',
             'OPTIONS': {},
             'PASSWORD': '********************',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': None,
             'USER': ''}}


DATABASE_ROUTERS

[]


DATA_UPLOAD_MAX_MEMORY_SIZE

2621440


DATA_UPLOAD_MAX_NUMBER_FIELDS

1000


DATETIME_FORMAT

'N j, Y, P'


DATETIME_INPUT_FORMATS

['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y']


DATE_FORMAT

'N j, Y'


DATE_INPUT_FORMATS

['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']


DEBUG

True


DEBUG_PROPAGATE_EXCEPTIONS

False


DECIMAL_SEPARATOR

'.'


DEFAULT_CHARSET

'utf-8'


DEFAULT_CONTENT_TYPE

'text/html'


DEFAULT_EXCEPTION_REPORTER_FILTER

'django.views.debug.SafeExceptionReporterFilter'


DEFAULT_FILE_STORAGE

'django.core.files.storage.FileSystemStorage'


DEFAULT_FROM_EMAIL

'webmaster@localhost'


DEFAULT_INDEX_TABLESPACE

''


DEFAULT_TABLESPACE

''


DISALLOWED_USER_AGENTS

[]


EMAIL_BACKEND

'django.core.mail.backends.console.EmailBackend'


EMAIL_HOST

'localhost'


EMAIL_HOST_PASSWORD

'********************'


EMAIL_HOST_USER

''


EMAIL_PORT

25


EMAIL_SSL_CERTFILE

None


EMAIL_SSL_KEYFILE

'********************'


EMAIL_SUBJECT_PREFIX

'[Django] '


EMAIL_TIMEOUT

None


EMAIL_USE_LOCALTIME

False


EMAIL_USE_SSL

False


EMAIL_USE_TLS

False


ENABLE_ACCOUNT_LOGIN

True


FILE_CHARSET

'utf-8'


FILE_UPLOAD_DIRECTORY_PERMISSIONS

None


FILE_UPLOAD_HANDLERS

['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']


FILE_UPLOAD_MAX_MEMORY_SIZE

2621440


FILE_UPLOAD_PERMISSIONS

None


FILE_UPLOAD_TEMP_DIR

None


FIRST_DAY_OF_WEEK

0


FIXTURE_DIRS

[]


FORCE_SCRIPT_NAME

None


FORMAT_MODULE_PATH

None


FORM_RENDERER

'django.forms.renderers.DjangoTemplates'


IGNORABLE_404_URLS

[]


INSTALLED_APPS

('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.gis',
 'leaflet_storage',
 'umap',
 'compressor',
 'social_django')


INTERNAL_IPS

('127.0.0.1',)


LANGUAGES

(('en', 'English'),
 ('fr', 'Francais'),
 ('it', 'Italiano'),
 ('pt', 'Portuguese'),
 ('nl', 'Dutch'),
 ('es', 'Español'),
 ('fi', 'Finnish'),
 ('de', 'Deutsch'),
 ('da', 'Danish'),
 ('ja', 'Japanese'),
 ('lt', 'Lithuanian'),
 ('cs-cz', 'Czech'),
 ('ca', 'Catalan'),
 ('zh', 'Chinese'),
 ('zh-tw', 'Chinese'),
 ('ru', 'Russian'),
 ('bg', 'Bulgarian'),
 ('vi', 'Vietnamese'),
 ('uk-ua', 'Ukrainian'),
 ('am-et', 'Amharic'),
 ('sk-sk', 'Slovak'))


LANGUAGES_BIDI

['he', 'ar', 'fa', 'ur']


LANGUAGE_CODE

'en'


LANGUAGE_COOKIE_AGE

None


LANGUAGE_COOKIE_DOMAIN

None


LANGUAGE_COOKIE_NAME

'django_language'


LANGUAGE_COOKIE_PATH

'/'


LEAFLET_LATITUDE

-21


LEAFLET_LONGITUDE

-46


LEAFLET_STORAGE_ALLOW_ANONYMOUS

True


LEAFLET_STORAGE_EXTRA_URLS

{'ajax_proxy': '/ajax-proxy/?url={url}',
 'routing': 'http://www.openstreetmap.org/directions?engine=osrm_car&route={lat},{lng}&locale={locale}#map={zoom}/{lat}/{lng}'}


LEAFLET_STORAGE_KEEP_VERSIONS

10


LEAFLET_ZOOM

7


LOCALE_PATHS

[]


LOGGING

{}


LOGGING_CONFIG

'logging.config.dictConfig'


LOGIN_REDIRECT_URL

'/'


LOGIN_URL

'login'


LOGOUT_REDIRECT_URL

None


LOGOUT_URL

'/logout/'


MANAGERS

(('flavio', 'flavio@4rastreamento.com.br<mailto:flavio@4rastreamento.com.br>'),)


MAP_SHORT_URL_NAME

'umap_short_url'


MEDIA_ROOT

'/home/srv/umap/var/data'


MEDIA_URL

'/uploads/'


MESSAGE_STORAGE

'django.contrib.messages.storage.fallback.FallbackStorage'


MIDDLEWARE

None


MIDDLEWARE_CLASSES

('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware')


MIGRATION_MODULES

{}


MONTH_DAY_FORMAT

'F j'


NUMBER_GROUPING

0


PASSWORD_HASHERS

'********************'


PASSWORD_RESET_TIMEOUT_DAYS

'********************'


PREPEND_WWW

False


PROJECT_DIR

'/srv/umap/venv/lib/python3.5/site-packages/umap'


ROOT_URLCONF

'umap.urls'


SECRET_KEY

'********************'


SECURE_BROWSER_XSS_FILTER

False


SECURE_CONTENT_TYPE_NOSNIFF

False


SECURE_HSTS_INCLUDE_SUBDOMAINS

False


SECURE_HSTS_PRELOAD

False


SECURE_HSTS_SECONDS

0


SECURE_PROXY_SSL_HEADER

None


SECURE_REDIRECT_EXEMPT

[]


SECURE_SSL_HOST

None


SECURE_SSL_REDIRECT

False


SERVER_EMAIL

'root@localhost'


SESSION_CACHE_ALIAS

'default'


SESSION_COOKIE_AGE

1209600


SESSION_COOKIE_DOMAIN

None


SESSION_COOKIE_HTTPONLY

True


SESSION_COOKIE_NAME

'sessionid'


SESSION_COOKIE_PATH

'/'


SESSION_COOKIE_SECURE

False


SESSION_ENGINE

'django.contrib.sessions.backends.db'


SESSION_EXPIRE_AT_BROWSER_CLOSE

False


SESSION_FILE_PATH

None


SESSION_SAVE_EVERY_REQUEST

False


SESSION_SERIALIZER

'django.contrib.sessions.serializers.JSONSerializer'


SETTINGS_MODULE

'umap.settings'


SHORT_DATETIME_FORMAT

'm/d/Y P'


SHORT_DATE_FORMAT

'm/d/Y'


SHORT_SITE_URL

'http://emap.four'


SIGNING_BACKEND

'django.core.signing.TimestampSigner'


SILENCED_SYSTEM_CHECKS

[]


SITE_ID

1


SITE_NAME

'uMap'


SITE_URL

'http://emap.4tracking.com.br'


SOCIAL_AUTH_ASSOCIATE_BY_EMAIL

True


SOCIAL_AUTH_BACKEND_ERROR_URL

'/'


SOCIAL_AUTH_BITBUCKET_KEY

'********************'


SOCIAL_AUTH_BITBUCKET_SECRET

'********************'


SOCIAL_AUTH_DEFAULT_USERNAME

<function <lambda> at 0x7fdedf298730>


SOCIAL_AUTH_GITHUB_KEY

'********************'


SOCIAL_AUTH_GITHUB_SCOPE

['user:email']


SOCIAL_AUTH_GITHUB_SECRET

'********************'


SOCIAL_AUTH_LOGIN_REDIRECT_URL

'/login/popup/end/'


SOCIAL_AUTH_OPENSTREETMAP_KEY

'********************'


SOCIAL_AUTH_OPENSTREETMAP_SECRET

'********************'


SOCIAL_AUTH_PIPELINE

('social_core.pipeline.social_auth.social_details',
 'social_core.pipeline.social_auth.social_uid',
 'social_core.pipeline.social_auth.auth_allowed',
 'social_core.pipeline.social_auth.social_user',
 'social_core.pipeline.social_auth.associate_by_email',
 'social_core.pipeline.user.get_username',
 'social_core.pipeline.user.create_user',
 'social_core.pipeline.social_auth.associate_user',
 'social_core.pipeline.social_auth.load_extra_data',
 'social_core.pipeline.user.user_details')


SOCIAL_AUTH_RAISE_EXCEPTIONS

False


SOCIAL_AUTH_TWITTER_KEY

'********************'


SOCIAL_AUTH_TWITTER_SECRET

'********************'


STATICFILES_DIRS

('/srv/umap/venv/lib/python3.5/site-packages/umap/static',)


STATICFILES_FINDERS

['compressor.finders.CompressorFinder',
 'django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']


STATICFILES_STORAGE

'django.contrib.staticfiles.storage.StaticFilesStorage'


STATIC_ROOT

'/home/srv/var/static'


STATIC_URL

'/static/'


TEMPLATES

[{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': ['/srv/umap/venv/lib/python3.5/site-packages/umap/templates'],
  'OPTIONS': {'context_processors': ('django.contrib.auth.context_processors.auth',
                                     'django.template.context_processors.debug',
                                     'django.template.context_processors.i18n',
                                     'django.template.context_processors.request',
                                     'django.template.context_processors.media',
                                     'django.template.context_processors.static',
                                     'django.template.context_processors.tz',
                                     'social_django.context_processors.backends',
                                     'social_django.context_processors.login_redirect',
                                     'umap.context_processors.settings',
                                     'umap.context_processors.version')}}]


TEST_NON_SERIALIZED_APPS

[]


TEST_RUNNER

'django.test.runner.DiscoverRunner'


THOUSAND_SEPARATOR

','


TIME_FORMAT

'P'


TIME_INPUT_FORMATS

['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']


TIME_ZONE

'UTC'


UMAP_DEMO_SITE

False


UMAP_EXCLUDE_DEFAULT_MAPS

False


UMAP_FEEDBACK_LINK

'https://wiki.openstreetmap.org/wiki/UMap#Feedback_and_help'


UMAP_MAPS_PER_PAGE

1


UMAP_MAPS_PER_PAGE_OWNER

10


UMAP_USE_UNACCENT

False


USER_MAPS_URL

'user_maps'


USE_ETAGS

False


USE_I18N

True


USE_L10N

True


USE_THOUSAND_SEPARATOR

False


USE_TZ

True


USE_X_FORWARDED_HOST

False


USE_X_FORWARDED_PORT

False


WSGI_APPLICATION

'umap.wsgi.application'


X_FRAME_OPTIONS

'SAMEORIGIN'


YEAR_MONTH_FORMAT

'F Y'


You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.



FLAVIO F NOGUEIRA
ENG TELECOMUNICACOES






Em 23 de jan de 2018, à(s) 17:04, Yohan Boniface <notifications@github.com<mailto:notifications@github.com>> escreveu:


See https://stackoverflow.com/questions/7382149/purpose-of-django-setting-secret-key

Was it because of this key?

No idea. What error message do you have? Have you turned DEBUG on?

**Comment by yohanboniface** [comment]
> When I change inside the page / admin some parameter, as for example:
The owner of some map, the system returns me error and does not write this change.

I've never used the admin for changing the owner of a map, this is to be done front the front-end.

(Copy-pasting a whole error log without any formatting is not very useful, you'd better put it in a pastebin and link to it, or at least format it ;) )

**Comment by flaviomx14** [comment]
Sorry!

Try now please.


I've never used the admin for changing the owner of a map, this is to be done front the front-end.

Yes, is on front end page admin, just for test.

[cid:cf961477-3655-455b-b93f-35265dff076d@LAMP152.PROD.OUTLOOK.COM]


FLAVIO F NOGUEIRA
ENG TELECOMUNICACOES






Em 23 de jan de 2018, à(s) 17:09, Yohan Boniface <notifications@github.com<mailto:notifications@github.com>> escreveu:


When I change inside the page / admin some parameter, as for example:
The owner of some map, the system returns me error and does not write this change.

I've never used the admin for changing the owner of a map, this is to be done front the front-end.

(Copy-pasting a whole error log without any formatting is not very useful, you'd better put it in a pastebin and link to it, or at least format it ;) )

**Comment by yohanboniface** [comment]
> JSONDecodeError at /admin/leaflet_storage/map/3/change/

Should be fixed with last release.
