### ISSUE TITLE
Cluster numbers are black on Chrome

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#547]
The number displayed in clusters are in black over blue on Chromium, making them unreadable.
See for instance http://umap.openstreetmap.fr/fr/map/devdu-accueil_193233 and this screenshot:
![image](https://user-images.githubusercontent.com/6516063/35380593-057e01bc-01ba-11e8-991e-c3d2598eb266.png)

**Comment by yohanboniface** [comment]
I'll have a look, thanks!

**Comment by dbitouze** [comment]
The same happens with Opera, Midori, Gnome Web, etc. (Firefox is okay).

**Comment by yohanboniface** [comment]
I'm afraid we've fallen into https://bugs.chromium.org/p/chromium/issues/detail?id=558165

**Comment by dbitouze** [comment]
OK. As a workaround, the default colour can be changed for e.g. DodgerBlue in (approximative translation from French): Manage the layers → Edit →Property of the layout → Colour.
