### ISSUE TITLE
Don't say "Disable editing". Say instead "View map"

### ISSUE THREAD

**Issue by jidanni** [umap-project/umap#556]
In the upper right corner (of e.g,. https://umap.openstreetmap.fr/en/map/testmapa_200038#6/25.265/120.630 which I am editing)
please don't say "Disable editing".
That looks like a permission change command.

I would say one of
View / Preview / View mode / View map or eyeball icon
And toggle 
Edit / Edit mode / pencil icon

With mouseover: Switch back to Edit / View mode.

**Comment by VladimirSlavik** [comment]
This is actually a pair of strings "Enable editing" + "Disable editing".

Curiously enough, translation contains "Start editing" and "Stop editing" which sounds like a better fit.
