### ISSUE TITLE
"Only visible features will be downloaded" ambiguous

### ISSUE THREAD

**Issue by jidanni** [umap-project/umap#559]
"Only visible features will be downloaded" found throughout the interface, could have several meanings.
1. Only features that appear in the current part of the map that is visible. E.g., only the western part of the United States.
2. Only items that have their visibility attribute checkbox etc. checked.
3. All points but only their popups that are currently opened. 

Therefore please reword it.

**Comment by VladimirSlavik** [comment]
Seconded - this confused me a lot, too. Perhaps: _"Download will not include layers with visibility toggled off"_...? (It seems that's what it does)

**Comment by yohanboniface** [comment]
Changed recently through https://github.com/umap-project/umap/pull/1454
