### ISSUE TITLE
No way back to the home page

### ISSUE THREAD

**Issue by jidanni** [umap-project/umap#565]
User is here,
![sdd](https://user-images.githubusercontent.com/1230959/36843366-b0f28c3a-1d89-11e8-9ebf-2a0b57750146.jpg)
There are no links there that will lead him back to the homepage,
where he can learn more about the project.

**Comment by druxstr** [comment]
There used to have a "Home button", but it was misleading (see #300). 

Many users reported (at least to me) they expected the "Home sign" to get them back to "Default zoom".

If the user access a map directly, "Home" is where he started browsing, within the app.

It can be confusing to be brought out of the app, to a website you never seen before.

Still I agree not having a clear way to learn more about the project is a bummer.

**Comment by yohanboniface** [comment]
> Still I agree not having a clear way to learn more about the project is a bummer.

You should have a "home" link in the caption (bottom-right)

![screenshot-20180404113022-567x279](https://user-images.githubusercontent.com/146023/38299863-96216bba-37fb-11e8-8f33-312ad595a16f.png)

**Comment by unpack5** [comment]
That "Home" link is super low key. It's in the right bottom corner, with a small font, and with "OSM" before it I assumed it leads to the home page of the OSM project.

I agree there should be an easy way to navigate from a map to uMap home. It can be as easy as placing an uMap logo in the left side of the top bar and making it a link to the home page (similar to how Github's desktop page looks like).
