### ISSUE TITLE
Overlay layer on base map

### ISSUE THREAD

**Issue by xaid2** [umap-project/umap#566]
Good afternoon. I know that such appeals have already been made, but is it possible to add overlays to the map? I have some pictures that I made with the drones, I cut them into tiles, and it would be nice to put them on top of the map, and not make a separate map on which they will only be. If there is such an opportunity, write where and what to replace in the config. Thank you.

**Comment by gelmio** [comment]
@yohanboniface this would be a very useful feature! Is there any chance of this feature?

**Comment by mary-loulou** [comment]
It would be amazing to have image overlays.

**Comment by yohanboniface** [comment]
cf #315
