### ISSUE TITLE
tiles issue on http to https 

### ISSUE THREAD

**Issue by Morten11** [umap-project/umap#567]
Dear people,

currently I move my website to https. On my website I embedded an iframe for my umap to show it on the website. Now, as I want to move to https there is an issue reported because the tile source is http but needs to be https.
Can you please change the tiles to https or let me know if I can fix that issue.

Regards
Morten

**Comment by VladimirSlavik** [comment]
You can do it yourself - edit map, go to map settings (pencil next to map name in top left), custom backgrounds, and enter an URL template string that does what you want.

The following may help you understand what should go there:
http://leafletjs.com/reference-1.3.0.html#tilelayer
https://github.com/Leaflet/Leaflet/issues/3186

**Comment by Morten11** [comment]
Thanks a lot for your reply concerning the https-issue. Your advice helped
a bit, but not fully. After editing the URL template string from http to
https the embeded code of my umap does not cause any further issues. My
website is secure by https. But unfortunately while changing to https the
template string don`t load the map anymore. Now I can only see the drawing
line of my route on a fully grey background. (see:
http://umap.openstreetmap.fr/en/map/morten-rochssare_180360#1/34/51). That
is not what I want. I need the map to be https and actually show when
embeded.
How can the issue be solved?

Kind regards
Morten

2018-03-13 22:40 GMT+07:00 Vladimír Slávik <notifications@github.com>:

**Comment by Morten11** [comment]
Sure, please note the following URL

https://mortenundrochssare.de

Regards

Yohan Boniface <notifications@github.com> schrieb am Mi., 2. Mai 2018,
13:23:

**Comment by yohanboniface** [comment]
> https://mortenundrochssare.de

I don't see any map on this page. Can you point me to page with the uMap iframe?

**Comment by Morten11** [comment]
Hey,
The map is located on the right hand side within the side bar. There is a
heading saying "Asien seit 2014 - aktuell 51.371 km". Below that is the map.

Yohan Boniface <notifications@github.com> schrieb am Mi., 2. Mai 2018,
14:41:

**Comment by yohanboniface** [comment]
Ah. It's blank because it's an http iframe while the site is https.

So let's me summarize the basics when you want to embed uMap in https:

- the iframe URL needs to be https://
- the background layer needs to be in https://, for this you can either choose one from the list already in https or use the "Custom background" panel to define a custom one in https
- each image or remote data layer needs to use https:// too

Once this checklist is all good, your map should work as expected. If not, ping me back.

**Comment by Morten11** [comment]
Hey
unfortunately it is not working for me. I changed the iframe URL to https://
and I am using your background layer OSM-monochrome. Anyway while embeding
the map there is still an issue with https:// as my website is not verified
with a green lock. Checking the browsers Console the issue is connected to
the background layer of umap. (note atachement).
Realizing this I went back to my umap to change the costum background (http
to https) but than be background goes blank, leaving nothing but grey space.

Hope you can help.
Regards.

2018-05-02 16:40 GMT+07:00 Yohan Boniface <notifications@github.com>:

**Comment by yohanboniface** [comment]
> I am using your background layer OSM-monochrome. 

It's not an https one.
If you want a light one, use Positron, it's https.

**Comment by VladimirSlavik** [comment]
There's a list of tile servers / layers on the OSM wiki, which includes some info about https availability: https://wiki.openstreetmap.org/wiki/Tiles

Indicating whether a "umap background" supports https would help, too - perhaps adding a green shield icon to the preview image in the background picker. Not sure if that is technically feasible, though.

**Comment by yohanboniface** [comment]
> Indicating  whether a "umap background" supports https would help, too - perhaps  adding a green shield icon to the preview image in the background  picker.

Good suggestion! :)

**Comment by peppemath** [comment]
Even if the post is closed, I have a similar problem (with my test site) but not with the tiles but with the points of interest; I switched to https, I see the tiles but I don't see the then.
My map is this http://umap.openstreetmap.fr/it/map/macellerie-e-rosticcerie_44760
and I use the map with iframe here
https://peppemath.altervista.org/macellerie.html.

OSS:
I have the same problem if I directly access my map with https://umap.openstreetmap.fr/it/map/macellerie-e-rosticcerie_44760

What could be the problem?

**Comment by peppemath** [comment]
I solved!!
I changed in the layer properties, the remote data url!
