### ISSUE TITLE
Search by coordinates

### ISSUE THREAD

**Issue by blauloke** [umap-project/umap#570]
Hello!

I have a list with many coordinates that I want to add to my map. Is it possible to search the database by coordinates, not just by names, like it can be done in OSM?

For example, can I search for N54°49.538' E009°24.334' or do I need to search by name? Coordinates are a lot easier, if you have them.

If it's not already possible, can it be please added as a feature?

**Comment by vinber** [comment]
if it's possible, it's easier to import yours datas, with a csv file containing your coordinate

**Comment by blauloke** [comment]
Thanks for the answer but I don't even know what a csv file is.

Is it really not possible to just search for coordinates?

**Comment by blauloke** [comment]
Thanks, I tried it and it worked!
