### ISSUE TITLE
login with github not work

### ISSUE THREAD

**Issue by stefanocudini** [umap-project/umap#571]
login with github redirect to a page not found 404

**Comment by yohanboniface** [comment]
Are you in https?

**Comment by stefanocudini** [comment]
yes, and redirect me top here:
http://umap.openstreetmap.fr/complete/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=vsPtvizqJmYmDR5CDP3Nkn76to7B3irv

**Comment by n0vember** [comment]
I have the same issue. I deactivated httpseverywhere plugin and forced http URL and finally managed to log in.

**Comment by stefanocudini** [comment]
I haven't httpseverywhere plugin

**Comment by yohanboniface** [comment]
@stefanocudini have you tried with http://umap.openstreetmap.fr ?

**Comment by stefanocudini** [comment]
yes without https it work!
