### ISSUE TITLE
https cert expired

### ISSUE THREAD

**Issue by DaCor1** [umap-project/umap#572]
Getting this error when I navigate to umap in my browser (chrome)

NET::ERR_CERT_DATE_INVALID
`
**Subject:** osm102.openstreetmap.fr

**Issuer:** Let's Encrypt Authority X3

**Expires on:** Apr 8, 2018

**Current date:** Apr 8, 2018

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIGQTCCBSmgAwIBAgISA2ZpWCzGZf+/1M/aEpPSZQyYMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xODAxMDgwMTEzMTlaFw0x
ODA0MDgwMTEzMTlaMCIxIDAeBgNVBAMTF29zbTEwMi5vcGVuc3RyZWV0bWFwLmZy
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA04PCVDi6zRab+ElshZ05
1isRv6od0xGU0SIim2p2W+XanbkH8CJ+SWWWNViploo0hu/8MMJrYYJ9FvnVlMFf
NATLolVLuIEycYeW+CsV+X/mnVIRC2kGRO0bB2KR/92uAt5AFMXi4ydOWoOE1ZdJ
qiw+/JeanHnEichEpy2o+lQ+GLdOHEeagnPrsyr79XR2419vLz+Y3lAFyPZCv5n/
V3XYqgpJ+ojhxSxDKNX/i/gTeuWcO7ksH9j2fOESmiGLWmRM4tLVnPhIz42UpLU9
g+l+zHY3FeGONJksUNgHEWO9gcj9U0KRp71l0iesNVgXjUXTaMmnOG+zdiB2R+r0
wNdN95qKIAZjwywNV5xsM/UvvXxltP7EcwCCh3+0XdF81PpmgWkJMbfsqCydQcn/
Dou2zq0dHbdEe/UX3HTcbeuu9+Hla0O9DGn0j8B8gOc+0ZmNLLAJoL4e10AyAKlt
cn4LDEFb2k+TDCMgR49Z/8GKrWYGG//r0ALYh136vq7BNkNrONDRobDb6fpw0T0m
z5iKYkaGewTQjVjJPW3BKZHgVHNLfaKqLJpd9X5v1/wHpTE79rzl3XDj3PpBz5U8
tYnDVpQ785+gKHddGu0YTvqKkGKpK4oXkO3tNbhCz+8hZwmgjbgdoottk+bBWFTG
qGGHd8x7abz5OWEsm+FMS/sCAwEAAaOCAkcwggJDMA4GA1UdDwEB/wQEAwIFoDAd
BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNV
HQ4EFgQUtwMevr1MyZQKsDJFOfukXi8WaNIwHwYDVR0jBBgwFoAUqEpqYwR93brm
0Tm3pkVl7/Oo7KEwbwYIKwYBBQUHAQEEYzBhMC4GCCsGAQUFBzABhiJodHRwOi8v
b2NzcC5pbnQteDMubGV0c2VuY3J5cHQub3JnMC8GCCsGAQUFBzAChiNodHRwOi8v
Y2VydC5pbnQteDMubGV0c2VuY3J5cHQub3JnLzBSBgNVHREESzBJghdub21pbm8u
b3BlbnN0cmVldG1hcC5mcoIXb3NtMTAyLm9wZW5zdHJlZXRtYXAuZnKCFXVtYXAu
b3BlbnN0cmVldG1hcC5mcjCB/gYDVR0gBIH2MIHzMAgGBmeBDAECATCB5gYLKwYB
BAGC3xMBAQEwgdYwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQu
b3JnMIGrBggrBgEFBQcCAjCBngyBm1RoaXMgQ2VydGlmaWNhdGUgbWF5IG9ubHkg
YmUgcmVsaWVkIHVwb24gYnkgUmVseWluZyBQYXJ0aWVzIGFuZCBvbmx5IGluIGFj
Y29yZGFuY2Ugd2l0aCB0aGUgQ2VydGlmaWNhdGUgUG9saWN5IGZvdW5kIGF0IGh0
dHBzOi8vbGV0c2VuY3J5cHQub3JnL3JlcG9zaXRvcnkvMA0GCSqGSIb3DQEBCwUA
A4IBAQCK5VG9OZZV6t3Z2bAe3IPrbj7aZ8dltnJ7aC1BSvVQDp9XaDgrheSACNQl
R4xJlLSAkBH6MWyK9VkGFvfhv0hLgPrykr2UmkrdIFlP3j57y04shiym5dshFtcr
Y/8sUNMa4lJZSd3pFvFiFkFn77RjNeulagcAyZoNdxIuJL+j1gp3yTowwef5mqxv
r+evSM5yJdmlXwJXoTyS9+3V4KyyqgOvPSrKg0fQrWV8Sbwh1Y09RIAeR9fKmaXh
259/8s202S2WLEs9QPkZx/GNfiYdR6/JTTB5Xy2LlpHaHSBLE15DQ886283f4oeV
zlrS57EG/kkCYjZmd9KRhMncDp74
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
/PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDSjCCAjKgAwIBAgIQRK+wgNajJ7qJMDmGLvhAazANBgkqhkiG9w0BAQUFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTAwMDkzMDIxMTIxOVoXDTIxMDkzMDE0MDExNVow
PzEkMCIGA1UEChMbRGlnaXRhbCBTaWduYXR1cmUgVHJ1c3QgQ28uMRcwFQYDVQQD
Ew5EU1QgUm9vdCBDQSBYMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AN+v6ZdQCINXtMxiZfaQguzH0yxrMMpb7NnDfcdAwRgUi+DoM3ZJKuM/IUmTrE4O
rz5Iy2Xu/NMhD2XSKtkyj4zl93ewEnu1lcCJo6m67XMuegwGMoOifooUMM0RoOEq
OLl5CjH9UL2AZd+3UWODyOKIYepLYYHsUmu5ouJLGiifSKOeDNoJjj4XLh7dIN9b
xiqKqy69cK3FCxolkHRyxXtqqzTWMIn/5WgTe1QLyNau7Fqckh49ZLOMxt+/yUFw
7BZy1SbsOFU5Q9D8/RhcQPGX69Wam40dutolucbY38EVAjqr2m7xPi71XAicPNaD
aeQQmxkqtilX4+U9m5/wAl0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFMSnsaR7LHH62+FLkHX/xBVghYkQMA0GCSqG
SIb3DQEBBQUAA4IBAQCjGiybFwBcqR7uKGY3Or+Dxz9LwwmglSBd49lZRNI+DT69
ikugdB/OEIKcdBodfpga3csTS7MgROSR6cz8faXbauX+5v3gTt23ADq1cEmv8uXr
AvHRAosZy5Q6XkjEGB5YGV8eAlrwDPGxrancWYaLbumR9YbK+rlmM6pZW87ipxZz
R8srzJmwN0jP41ZL9c8PDHIyh8bwRLtTcm1D9SZImlJnt1ir/md2cXjbDaJWFBM5
JDGFoqgCWjBH4d1QB7wCCZAA62RjYJsWvIjJEubSfZGL+T0yjWW06XyxV3bqxbYo
Ob8VZRzI9neWagqNdwvYkQsEjgfbKbYK7p2CNTUQ
-----END CERTIFICATE-----

 `

**Comment by jo2012** [comment]
same problem
it is irritating many user

**Comment by yohanboniface** [comment]
cc @jocelynj @cquest one of you have the process at hand to renew the certificate?

**Comment by jocelynj** [comment]
The process is the following on the server:
`
sudo -u letsencrypt -s
cd ~/keys/
./launch-acme-tiny.sh
`

**Comment by yohanboniface** [comment]
Should be OK, thanks for the report, and thanks @cquest and @jocelynj :)

**Comment by jo2012** [comment]
thank you very much!!!
