### ISSUE TITLE
Impossible to edit my map

### ISSUE THREAD

**Issue by beamaria** [umap-project/umap#579]
I've created a map and now I need to edit it and add some markers. Even if I can login to uMap site I can only view the map and not edit it. I've set the permission to edit to the owner of the map (that's me and ONLY me) and there aren't any other owners/editors. What can I do to retrieve my map and edit it?

**Comment by beamaria** [comment]
Hi Yohan, thanks for your reply.
Here the  link <https://umap.openstreetmap.fr/it/map/where-to-buy_219013>.
I think you should add some more documentation about creating a Map with uMap: a lot of people (like me) are trying to find systems to draw maps other than that damned Google Maps, especially since Google requires your credit card data to have an API Key.
I’m still struggling to realise how to cluster many markers, even using a layer with “clustered” option ticked….

Elisabetta

**Comment by yohanboniface** [comment]
> Here the  link <https://umap.openstreetmap.fr/it/map/where-to-buy_219013>.

This map is owned by `giacomaccio`, does that make sense for you?

> I think you should add some more documentation about creating a Map with uMap

Thanks for the suggestion.
uMap is a volunteer and community project. It's sustainable only if everyone do a little effort to make it better, not if I do everything myself.
So you are welcome to make the documentation better :)
You can find link to tutorials and documentation here: https://wiki.openstreetmap.org/wiki/UMap
The English documentation is here (not up to data as far as I can tell): https://wiki.openstreetmap.org/wiki/UMap/Guide

**Comment by beamaria** [comment]
Yes, the owner it’s me!
I didn’t realise I have to copy the url in my browser to edit the map; actually I thought to log in and find a list of my maps to be edited…
I would be happy to contribute to the documentation, but I must solve my problem first (that is how to cluster many markers). I searched the links you sent me and couldn’ t find anything on the subject
Thanks anyway!

Elisabetta

**Comment by yohanboniface** [comment]
> I thought to log in and find a list of my maps to be edited…

That should be the case.

> I must solve my problem first (that is how to cluster many markers). I searched the links you sent me and couldn’ t find anything on the subject

You shouldn't have to do anything more than use a "Clustered" layer.
Note that of course the markers are clustered only if they are close enough.
