### ISSUE TITLE
Fullscreen button has styling issues

### ISSUE THREAD

**Issue by akien-mga** [umap-project/umap#586]
On both Firefox Nightly 62.0a1 (2018-05-30) and Chromium 62.0.3202.94 on Linux (Mageia 6 x86_64), the Fullscreen button in the left dock seems to be wrongly styled, as it appears smaller than other buttons in the dock, and then expands to be slightly bigger than the other buttons when hovered:
![image](https://user-images.githubusercontent.com/4701338/40835738-912dd852-6594-11e8-812c-231e5fe110a3.png) ![image](https://user-images.githubusercontent.com/4701338/40835746-9d88f1a4-6594-11e8-8605-affe0f98df57.png) ![screenshot_20180601_121005](https://user-images.githubusercontent.com/4701338/40835787-bb63f64c-6594-11e8-95b4-710579e1e03a.png)

It would look better if it was styled like the other buttons.

The zoom buttons (`+` and `-`) also seem to have the same issue, though it's less of an issue.

**Comment by yohanboniface** [comment]
Is you display touch able?

**Comment by akien-mga** [comment]
My hardware isn't (regular non touch laptop), but the software might be
(recent Xorg with Xinput and KWin as window manager).

Le samedi 2 juin 2018, Yohan Boniface <notifications@github.com> a écrit :
> Is you display touch able?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/JfJ75yyDrXpcdEIncJDiknSYpGkZ695Y_Zyy9UrG3MmfPpqUtNgXWxDZkZDvliZLmjWTmnFO6EOeXwZJxAJkUKmNs1LsSUpYDvKmr0P6YjRlcXZ39LAKk4uyr-dOECRilRXWAE4VFhfV1uHkM9iW6Zck5W-VZQ=s0-d-e1-ft#https://github.com/notifications/beacon/AEe8mhhDAr_UXZ9XpKDdVGvZFyQwn4qLks5t4j5NgaJpZM4UWcYg.gif>

**Comment by frchretien** [comment]
Hello / bonjour,
Thanks for this great software. I use current version of umap.openstreetmap.fr. I'd like to bounce on this issue : can you check the styling of these icons ? As we see in the image above, zoom +/- and fullscreen icons are smaller and with white background by default; they become larger and grey background on hover. Other icons (eg search) are displayed the same way (large; grey) by default and on hover. I suspect a bug in displaying other icons. Reproduced in FF and Chrome, current versions. 
btw : don't you think it would be nicer to have only the background changed on hover and not the size, as in regular OSM button bar ?
Thanks

**Comment by frchretien** [comment]
Hm; in the demo site above you fixed the size but not the background (still incorrect for search icon for example). Right ?

**Comment by yohanboniface** [comment]
Ah, right! I'll fix that :)
