### ISSUE TITLE
Unable to log into the Demo instance with Openstreetmap login

### ISSUE THREAD

**Issue by MIAnalytics** [umap-project/umap#588]
I was creating a map in the demo instance (http://umap.fluv.io/en/user/) And for the past few days when I try to log in with my "OpenStreetMap" credentials, I get a 502 Bad Gateway error message. I want to either move or recreate that map in the main instance (http://umap.openstreetmap.fr/user) but cannot do that without being able to check my settings on the original map

**Comment by yohanboniface** [comment]
Should be OK now.

Ref: https://github.com/umap-project/umap/pull/580 (not released yet because #583 )
