### ISSUE TITLE
UMAP OLD access using OpenStreetMAP API

### ISSUE THREAD

**Issue by kleper** [umap-project/umap#593]
I have an old instance of UMAP https://umapold.openstreetmap.co
that recently started to fail and does not allow users to log in using OpenStreetMap since I have tried several things regarding the API correction but I can not fix it, I have looked at the documentation on the subject but I have not found anything that I'm heading to fix this problem.

**Comment by yohanboniface** [comment]
See https://github.com/umap-project/umap/pull/580
Should work with 0.8.3 and latest social-auth package.
