### ISSUE TITLE
Label Keys 

### ISSUE THREAD

**Issue by Bogibog** [umap-project/umap#595]
When tweaking the lable keys, I'm able to get some results but after clicking on the Save button, the Lable key I've chosed disappear.

Working under Firefox 60.0.2 (64 bits)

Example of the map here : https://umap.openstreetmap.fr/fr/map/formations-faasb-2018_217863#6/46.081/2.813

:)

**Comment by vinber** [comment]
it seem to work with label key on layers but not when it's only on map parameters.

https://umap.openstreetmap.fr/fr/map/cartographie-des-activites-asb_232569#6/46.081/2.802

**Comment by Bogibog** [comment]
Sry No. Just tried it fex minutes ago, stil the same problem. Working as you enter the label key at first but after disconnecting the Label key is missing, so the informations selected at first.

**Comment by yohanboniface** [comment]
Sry nt rlsd yet.
