### ISSUE TITLE
umap vs google maps - misplaced vertices of a 'circle'

### ISSUE THREAD

**Issue by aillusions** [umap-project/umap#597]
Same coordinates are rendered differently in the two systems:

![image](https://user-images.githubusercontent.com/273321/42248562-e0033ffe-7f2e-11e8-9fca-62a3fde00ccf.png)

![image](https://user-images.githubusercontent.com/273321/42248565-e5346c3c-7f2e-11e8-93a2-4cac7776b869.png)

[
[
8.5151,
47.16530837158007
],
[
8.515275261046382,
47.16529091747498
],
[
8.515443786909037,
47.165239225910796
],
[
8.515599101233576,
47.16515528336549
],
[
8.51573523537761,
47.16504231570411
],
[
8.515846957782324,
47.16490466421044
],
[
8.515929975018363,
47.16474761875418
],
[
8.515981096779901,
47.16457721450411
],
[
8.515998358486314,
47.1644
],
[
8.515981096779901,
47.164222785495895
],
[
8.515929975018363,
47.164052381245824
],
[
8.515846957782324,
47.16389533578956
],
[
8.51573523537761,
47.16375768429589
],
[
8.515599101233576,
47.16364471663451
],
[
8.515443786909037,
47.163560774089206
],
[
8.515275261046382,
47.163509082525024
],
[
8.5151,
47.16349162841993
],
[
8.514924738953619,
47.163509082525024
],
[
8.514756213090964,
47.163560774089206
],
[
8.514600898766425,
47.16364471663451
],
[
8.51446476462239,
47.16375768429589
],
[
8.514353042217676,
47.16389533578956
],
[
8.514270024981638,
47.164052381245824
],
[
8.5142189032201,
47.164222785495895
],
[
8.514201641513687,
47.1644
],
[
8.5142189032201,
47.16457721450411
],
[
8.514270024981638,
47.16474761875418
],
[
8.514353042217676,
47.16490466421044
],
[
8.51446476462239,
47.16504231570411
],
[
8.514600898766425,
47.16515528336549
],
[
8.514756213090964,
47.165239225910796
],
[
8.514924738953619,
47.16529091747498
],
[
8.5151,
47.16530837158007
]
]

Is this map configuration issue?

thanks

**Comment by yohanboniface** [comment]
Seems like a projection issue.
How did you get those coordinates?

**Comment by aillusions** [comment]
I've computed them by using two approaches (with identical results): 

1. JS implementation inspired by this article: http://pietschsoft.com/post/2008/02/09/Virtual-Earth-Draw-a-Circle-Radius-Around-a-LatLong-Point

![image](https://user-images.githubusercontent.com/273321/42270362-5589ea0c-7f89-11e8-8a57-a5ef72ccf62a.png)

2. Google maps API, inspired by this jsfiddle http://jsfiddle.net/z4om3x6s/7/
![image](https://user-images.githubusercontent.com/273321/42270664-18fb6d6c-7f8a-11e8-800f-5469255e297d.png)
