### ISSUE TITLE
uMap integration in Wix not working, X-Frame Option Problem?

### ISSUE THREAD

**Issue by RodrigueRF** [umap-project/umap#598]
Hi everyone,

I tried to embed my uMap map in the Wix website I created using the Wix HTML toolAnd it does display anything. I tried various options (from uMap & from Wix) but it didn't change anything... Where did I miss something?

`<iframe width="100%" height="300px" frameBorder="0" src="http://umap.openstreetmap.fr/fr/map/eudaimon-path_231868?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false"></iframe><p><a href="http://umap.openstreetmap.fr/fr/map/eudaimon-path_231868">Voir en plein écran</a></p>`

Link of the map : http://u.osmfr.org/m/231868/

Is it an X-Frame Option problem? If yes how should I do to solve it?

Thank you in advance for your help :)

**Comment by deuzeffe** [comment]
Maybe an issue with http/https ? In the iframe code, try to replace both occurrence of http by https. 
HTH

**Comment by yohanboniface** [comment]
> Maybe an issue with http/https ?

+1 If the site is https, that may be the reason.

Otherwise, can you share a link where the iframe is embedded so we can investigate?

**Comment by RodrigueRF** [comment]
Yes it was exactly this problem :) Thank you guys!
