### ISSUE TITLE
Integration of OpenAgenda feeds

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#600]
ENHANCEMENT

OpenAgenda is working on producing event data in GeoJSON. This contains a lot of data which is structured as objects in objects, for instance : 

```
{
      "type": "Feature",
      "properties": {
        "title": "Samedi 30 juin et dimanche 1er juillet à BEAUPREAU",
        "url": "https://openagenda.com/ou-retrouvez-mes-produits-au-safran-bienvenue-a-la-ferme/events/samedi-30-juin-et-dimanche-1er-juillet-a-beaupreau",
        "description": {
          "fr": "« Parc en fête », sur le thème « l'art dans la nature »"
        },
        "nextTiming" : {
          "start" : "2018-06-30T16:00:00+02:00",
          "end" : "2018-06-30T21:30:00+02:00"
        }
      },
      "geometry": {
        "type": "Point",
        "coordinates": [-0.991652, 47.206477]
      }
}
```

In order to use this data, it would be nice to extend uMap's variable injection syntax {var} to point to objects in objects, for instance {description.fr} or {nextTiming.start} for the example above. Perhaps allow for deeper structures, i.e. {var1.var2.var3} ...

**Comment by kaore** [comment]
Hi! Any progress on this? Many of our users would find this useful. Something following the synthax as described by the [lodash get](https://lodash.com/docs/4.17.10#get) function would be handy.

**Comment by yohanboniface** [comment]
Is there any URL I can play with to test?

**Comment by kaore** [comment]
So there is this one, which lists events with a location sub-key: https://openagenda.com/agendas/38728897/events.v2.json?key=dcff3038e7460e5b762034f2118c5cd7&monolingual=fr&geojson=1&detailed=1

The monolingual key ensures that only content in french is return in multilingual fields, detailed sends detailed information, the geojson query param tweaks the sub-structure of the location key of each listed event to provide data in a geojson format.

Ideally, it would be practical for users to be able to specify a subkey where to find location data in a feed and be able to access parent data. In our case, the parent data is the event details and the location detail is given in an .location subkey. This would be useful not only for event lists but also any other type of data that are linked to locations.

Here is a list of verified ( official ) agendas last updated on openagenda: https://openagenda.com/agendas?official=1

**Comment by yohanboniface** [comment]
> So there is this one, which lists events with a location sub-key: https://openagenda.com/agendas/38728897/events.v2.json?key=dcff3038e7460e5b762034f2118c5cd7&monolingual=fr&geojson=1&detailed=1

Humm, this does not look like geojson. Am I missing something? :)

**Comment by yohanboniface** [comment]
So a basic version of nested variable is now support, but just to make it clear: the URL provided is not [GeoJSON](http://geojson.org/) and is not any format known by uMap so it cannot be used as data source at this stage.

Options are:
- openagenda provides a geojson stream (or any other known formats: csv, gpx, kml, georss, osm)
- umap add a way to import openagenda custom json

**Comment by kaore** [comment]
Hi, sorry for the delay.

We will implement option 1.

What I was suggesting was not necessarily doing something specific for openagenda, but rather for any list of data with a nested geojson component. In the link provided previously, the event data is not geojson, but the nested location in each event item are.

**Comment by kaore** [comment]
So here is what the event json would look like now. I tested it with http://geojson.io
[events.geojson.json.zip](https://github.com/umap-project/umap/files/2260114/events.geojson.json.zip)

**Comment by yohanboniface** [comment]
Sounds good :)

Example of template:
```
# {title} ({dateRange})
{contributor.organization}
{{{image.base}{image.filename}}}
```

(But I've 'access denied' on the image…)

![screenshot from 2018-08-05 13-06-02](https://user-images.githubusercontent.com/146023/43685305-c9094686-98b0-11e8-8af4-bd2da8c48ae4.png)

Is there any "default template" that could work for any event? We may add a "OpenAgenda" popup style, so users don't need to deal with variables for common cases?

**Comment by kaore** [comment]
Yes I can advise something, I'll get back to you shortly with a json with fully valid data and a template which  could work. Any conditionals possible on the template synthax? like for example:

    {contibutor.organization || 'no organization'}

Or conditional blocks? The image is not always available.

**Comment by yohanboniface** [comment]
Custom template will be full JS, so we can do whatever we want :)
But this should be quite stable if possible because it will need a new release to be updated ;)

**Comment by yohanboniface** [comment]
BTW: regarding the `properties` structure, is there any "calendar" related json standard we could rely upon?

**Comment by kaore** [comment]
Hi,

So here is the updated json link: https://openagenda.com/agendas/38728897/events.v2.json?key=dcff3038e7460e5b762034f2118c5cd7&monolingual=fr&geojson=1&detailed=1

Concerning the template, you are using a specific template engine ( handlebarsjs or the like )?

The most widespread standard is ical( so the json standard would be this: [JSCalendar](https://tools.ietf.org/id/draft-jenkins-jscalendar-01.html), but it is better suited for personal scheduling calendars. Events on OA tend to be more detailed.

Maybe we should open separate issues to cover these topics more specifically :)

**Comment by yohanboniface** [comment]
> Concerning the template, you are using a specific template engine ( handlebarsjs or the like )?

Nope, just search and replace.
I may upgrade to a template engine at some point, but for now the idea is to keep it basic, so my "it does not work" issues list does not grow too much.

> The most widespread standard is ical( so the json standard would be this: JSCalendar, but it is better suited for personal scheduling calendars. Events on OA tend to be more detailed.

From uMap point of view, adding a "popup content style" makes sense mostly if it's a standard.
Maybe JSCalendar is enough in our use case? Which is I guess something like name + description + dates + picture ?
Of course, one can still use variable to make its own template when needed, I'm just talking about a ready-to-use choice in the select box for common users.

**Comment by yohanboniface** [comment]
> The most widespread standard is ical( so the json standard would be this: JSCalendar

What about https://tools.ietf.org/html/rfc7265 (jCal) ?

**Comment by yohanboniface** [comment]
Other option, have a "flat summary" mode, like in https://www.agendadulibre.org/regions?region=all (geojson) ?

**Comment by yohanboniface** [comment]
Hello! Is this still a needed feature and is there still missing pieces in uMap ?

**Comment by kaore** [comment]
Hi @yohanboniface I haven't had any requests recently for umap specifically but I'll find some time to experiment and advertise what can be done on our documentation as displaying events on a map easily is a recurring topic. Any changes on templating possibilities? Placing a  name + description + dates + picture AND link to an external site would probably suffice in most cases.

**Comment by yohanboniface** [comment]
Customizing the template is already possible, but this as to be done by hand (`{name} / {description}…`).

In an ideal world, but my be in a second step, we could have a built-in template, like we have one for GeoRSS. And it seems this is something we already discussed a bit above :)

Maybe next time to have a request from somebody to put events on a map we could explore that together ?

**Comment by kaore** [comment]
Sure, we'll document what is possible today and leave the door open for a discussion to whomever might be interested

**Comment by naomap** [comment]
> Hello! Is this still a needed feature and is there still missing pieces in uMap ?

As far as I'm concerned this feature is no longer needed, however this could be a cool feature.

**Comment by yohanboniface** [comment]
Need seems to have disappeared, let's reopen if it comes again!
