### ISSUE TITLE
Background map selection does not work on instance on openstreetmap.fr

### ISSUE THREAD

**Issue by gormo-osm** [umap-project/umap#601]
When trying to select a different background map on the umap instance at http://umap.openstreetmap.fr/de/ the click on the background map icon in the right panel does nothing. The other icons open the side panel when clicked, only the background map is affected.

Javascript console says `Error: No value provided for variable {r}` 

The instance at http://umap.fluv.io/de/ is not affected (it works there).

**Comment by yohanboniface** [comment]
> The instance at http://umap.fluv.io/de/ is not affected (it works there).

Because this instance is running the 1.0.0-rc.1, which contains a patch for this.

I've patched the osm.fr instance, should be ok now. Thanks for the alert! :)
