### ISSUE TITLE
permissions editing efficiency problem

### ISSUE THREAD

**Issue by jgastonraoul** [umap-project/umap#603]
I think there is an efficiency problem in the way editing permissions is managed (at least on http://umap.openstreetmap.fr)...
When I click on the "key" icon, a big file of 2,45MB is downloaded before to open the sidebar.
Then, when I start to enter some letters to find a user, the process of autocompletion is very slow (I think this is due to the size of the file).
Would there be a way to improve this by making autocompletion requests at the time letters are entered instead of parsing this big file ?

**Comment by yohanboniface** [comment]
Fixed in 1.0.0-rc.1.
See https://github.com/umap-project/umap/issues/210
And testable in http://umap.fluv.io (not released yet in openstreetmap.fr instance).

**Comment by jgastonraoul** [comment]
Thank you ! Sorry for the duplicate !

I'll just wait for the update on openstreetmap server, then ! cc @cquest @jocelynj
