### ISSUE TITLE
[enhancement] Append "(clone)" to cloned map name 

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#605]
When you clone a map you're redirected to another map pretty identical to the first one.

It's hard to guess if you're still browsing the original map or if you're now on the clone.

You have to check the URL and notice the map id has changed.

It would be simpler if the clone was automatically named "original map name (clone)"

**Comment by yohanboniface** [comment]
This should already be the case. The clone name should start with "clone of" (or "clone de") depending on the language.

See: https://umap.openstreetmap.fr/en/search/?q=clone

**Comment by druxstr** [comment]
I was thinking about the name that displays here \:

![capture d ecran_2018-08-01_15-29-41](https://user-images.githubusercontent.com/17235663/43524737-4846824c-95a0-11e8-98d6-977fc8ce9080.png)

I feel it's a bit unintuitive that it stays the same after moving to the cloned map

**Comment by yohanboniface** [comment]
Ah, right!
DRY alert. I'll fix it for 1.0 :)
