### ISSUE TITLE
[enhancement] download data as CSV

### ISSUE THREAD

**Issue by druxstr** [umap-project/umap#608]
It would be useful to have CSV as an option when you download map data

Right now there's :\

* geoJSON
* kml
* gpx
* umap

**Comment by yohanboniface** [comment]
See https://github.com/umap-project/umap/issues/123#issuecomment-127049922

**Comment by druxstr** [comment]
OK, valid point. 

A solution could be to make CSV download available only for maps which use Points and no other geometry. 

But I don't think it's a good idea at all.
