### ISSUE TITLE
[Amélioration] Lien vers "Mes cartes" en mode édition

### ISSUE THREAD

**Issue by deuzeffe** [umap-project/umap#609]
Hello,
(Je l'ouvre en français, c'est plus simple pour moi, ça sera plus clair pour toi ^^).

Pas trouvé de moyen simple (sinon lien Accueil en bas de carte -> User(Mes Cartes) -> Clic sur la carte de son choix pour l'éditer) pour shifter d'une carte à l'autre en mode édition. Peut-être un lien/bouton à la fin de la barre de menu verticale droite pourrait être une bonne solution (sauf si trop lourd à coder, sinon, la v1 ne va jamais sortir :P)

Thx.

**Comment by yohanboniface** [comment]
Il y a maintenant un lien vers "mes cartes" dans le header:

![image](https://github.com/umap-project/umap/assets/146023/163af20f-1443-4c13-8e28-aca80e9892a1)

Mais quoi qu'il en soit @Aurelie-Jallut va revoir ce header (en mieux! :) ).

**Comment by Aurelie-Jallut** [comment]
Top menu Iteration suggestion :
- Add Umap logo on left to return to homepage
- Delete Edit in progress, which I find confusing
- Change text colors to respect accessibility
- Add info after map on status (public / instance)
- Move Account Access to the right (conventional location)
- Allow access to My cards via a drop-down menu

I'm a bit lacking in the "Preview" or "Share" functionalities here, but we'll see about that later ;)



![top-menu](https://github.com/umap-project/umap/assets/131352601/b55fcb5d-6bcc-4fef-9830-03b074b2902a)

**Comment by yohanboniface** [comment]
I'm fine with all that suggestions, my only concert is about the uMap logo to go back to the home page: given that this header is only displayed in edit mode, this means that map readers will not have it. Is it what we want ?

Also, the map may be in "anonymous mode", so we don't have a user authenticated, and thus no name to display. Should we keep the space blank or display something / an icon ?

**Comment by Aurelie-Jallut** [comment]
On the 1st point:
When I access a map via my town's website to consult "chantiers" in my town, I don't need to have a highly identifiable access to the uMap homepage.
On the other hand, when I'm an editor, it can be useful for finding a tutorial or inspiration, for example.
Can we differentiate between these 2 cases? If so: could we keep a light gray banner with reduced opacity for the edit button, and display the logo + the map name?

On the 2nd point: 
One solution might be to place the first-name field to the left of the Cancel and Save buttons: this is less usual, but I see 2 advantages: leaving the Save button in the same place and making it the main element for the user.

![image](https://github.com/umap-project/umap/assets/131352601/9fe6a59f-dc4a-4d60-81c9-99d7a056e0d6)

**Comment by Aurelie-Jallut** [comment]
![Image](https://github.com/umap-project/umap/assets/131352601/4c4b5fbb-58ad-476a-ba34-8bb91495b3c8)



![Image](https://github.com/umap-project/umap/assets/131352601/24beb7c9-c6c5-4eeb-89f0-687fc4b3fe77)



![Image](https://github.com/umap-project/umap/assets/131352601/0f3dd9a0-a942-44a3-918e-fee373870080)

**Comment by yohanboniface** [comment]
Nice!

Quelques questions/remarques:

- Les deux derniers écrans, c'est au choix ? :)
- si on met le statut au long ("carte publique"), ça risque de faire long pour le cas où c'est "Quiconque a le lien" ("carte accessible à quiconque a le lien"…), donc peut-être qu'il faut combiner un picto et un texte court (genre: "privé", "public", "lien direct")
- "instance github", c'est pour quoi ?
- Tu me fais l'icon uMap qui va bien ou je m'en débrouille ?
- Faut aussi penser à une déclinaison pour les petits écrans
- "Mes cartes", il flotte pas un peu ? :)
- est-ce qu'on garde le fait qu'en cliquant sur le titre (et sur les permissions du coup) on permet de le modifier ? Et si oui, est-ce qu'on garde le petit stylo au survol ?
- on vire le "?" et le texte d'aide (il ne me manquera pas) ?

**Comment by yohanboniface** [comment]
> si on met le statut au long ("carte publique"), ça risque de faire long pour le cas où c'est "Quiconque a le lien" ("carte accessible à quiconque a le lien"…), donc peut-être qu'il faut combiner un picto et un texte court (genre: "privé", "public", "lien direct")

D'ailleurs, pour pimenter un peu y a deux statuts:
- le statut en lecture (qui peut voir):
    - tout le monde
    - seuls les éditeurs
    - ceux qui ont le lien
- le statut en écriture (qui peut modifier):
    - quand il y a un propriétaire
        - tout le monde peut éditer
        - seulement les éditeurs
        - seulement le propriétaire
    - en mode anonyme
        - tout le monde
        - seulement le créateur

**Comment by davidbgk** [comment]
On a un moyen de détecter si on est dans une iframe pour n'enlever la barre que dans ces cas là ?

**Comment by yohanboniface** [comment]
> On a un moyen de détecter si on est dans une iframe pour n'enlever la barre que dans ces cas là ?

J'imaginais ne l'afficher dans tous les cas que si la personne a les droits d'édition sur la carte (mode "gestion" vs consultation pure), wdyt ?

**Comment by yohanboniface** [comment]
I'd say it's done!
