### ISSUE TITLE
[Feature] Group overlapping markers

### ISSUE THREAD

**Issue by tzeumer** [umap-project/umap#611]
Putting many markers (especially with icons) closely nearby makes the map look very cluttered when zooming out. Personally I like how Wikidata does it: things that are at the exact same coordinate get grouped and expand on click. Example:  http://tinyurl.com/yar863c9 (most dots expand, not all - I'm too bad at querying the right way). 

Maybe something similar could be implemented for uMap? 

I guess there are many other possible approaches to overcome the cluttering. While the one above seems to me to be the easiest (not meaning easy ;)), some other ideas
* Use a group property to manually define such groups (instead of exact same coordinate)
* Try to calculate when markers overlap and put them automatically in a group (and use some icon that indicates this nicely)
* Put markers in a radius into a group in accordance with a zoom level (settings) for the layer

Btw. this is what I'm trying to do https://umap.openstreetmap.fr/de/map/tuhh_238303. Maybe I just have a misconception and it would be better to do multiple linked maps or something like that. Anyway, thanks for reading up to here :)

**Comment by yohanboniface** [comment]
Have you tried to use a `Cluster` layer?

**Comment by tzeumer** [comment]
Oh, I completely missed that. This is pretty much what I wanted. Thank you!

I just wonder, if it is intentionally that you have to click twice in the data browser to see the popup (or sidebar) for grouped items. Or am I missing another option again? :)

**Comment by yohanboniface** [comment]
> I just wonder, if it is intentionally that you have to click twice in the data browser to see the popup (or sidebar) for grouped items. Or am I missing another option again? :)

Seems not.
Can you share the link of the map?

**Comment by tzeumer** [comment]
The link is https://umap.openstreetmap.fr/de/map/tuhh_238303. If you click on e.g. any entry in "TUHH: Institute" it expands the grouped items on first click, but shows the popup only when clicking again.

**Comment by yohanboniface** [comment]
Thanks for the report, it's fixed, but not yet released/deployed.
