### ISSUE TITLE
Impossible to edit polygons

### ISSUE THREAD

**Issue by thibdeh** [umap-project/umap#612]
Hi,

I've imported json data from OSM Boundaries in order to map countries at risk (and districts within)

But as soon as I try to edit these polygons (countries or regions) the site does not respond anymore and I have to quit and reload the page to access the map again (I could only edit Jamaica). 

I'm a new user of uMap so I have no idea of why it does not work (maybe i've input to much data in the map)

You will find the map below:
https://umap.openstreetmap.fr/fr/map/country-risk-map-2_238970#3/12.55/-1.58

Thanks in advance for your feedback

**Comment by yohanboniface** [comment]
> maybe i've input to much data in the map

Yep, i'm afraid it is the reason.
Do you have a dataset with simpler shapes? If not you can first use http://mapshaper.org/ to simplify it before importing in uMap.

**Comment by thibdeh** [comment]
Bonjour Yohan et merci pour votre retour (si je ne me trompe pas, je présume que vous parlez français :)

Qu'entendez-vous par simplifier ? Etant donné que je débute dans la cartographie je suis un peu perdu...

Merci beaucoup,

--------

Hi Yohan and thanks a lot for your feedback (if I'm not wrong, I presume that you speak French :)

What do you mean by simplify ? Given the fact that I'm a beginner regarding cartography, I'm a little bit lost....

Thanks a lot

**Comment by yohanboniface** [comment]
> Qu'entendez-vous par simplifier ? Etant donné que je débute dans la cartographie je suis un peu perdu...

Avoir une polygone avec moins de détails (tu n'as pas nécessairement besoin d'avoir tous les méandres d'une frontières qui suit un cours d'eau par exemple), donc moins de points, donc plus de facilité à l'éditer en ligne.

**Comment by yohanboniface** [comment]
j'aurais dit 10%, mais le mieux c'est d'essayer ;)
