### ISSUE TITLE
Map Caption Edit

### ISSUE THREAD

**Issue by thibdeh** [umap-project/umap#613]
Hi everyone,

I'd like to edit the map caption of my work like this one i've found online:

![edit example](https://user-images.githubusercontent.com/42180625/43949357-91eb65ae-9c8d-11e8-91a5-c96815923d62.PNG)

The problem is that I don't know how to put colours into a label like in the example.

Could someone please explain me how to do so ?

Many thanks !!!!

**Comment by yohanboniface** [comment]
It's hand made with a screenshots, here what the popup description looks like:

```
{{http://domaine.org/path/to/caption.jpg|300}}
```
