### ISSUE TITLE
pip install umap-project =>  Error: could not determine PostgreSQL version from '10.3'

### ISSUE THREAD

**Issue by Langlais115** [umap-project/umap#614]
Hy There,

When I follow the installation doc from https://umap-project.readthedocs.io/en/latest/ubuntu/ on a fresh install of Ubuntu 18.04 server I get the following error when I run the command **pip install umap-project**
`   Error: could not determine PostgreSQL version from '10.3'`

Any Idea what is wrong?

Please note that on ubuntu 18.04 few version are diffent from the doc:

- PostgresSQL is in version 10.3
- Python is in version 3.6.5
- psycopg2 is in version 2.7.5

**Comment by yohanboniface** [comment]
humm, weird, seems like an old version of psycopg2 is around.
Grml, I'm afraid this will need to wait until the next stable release (ongoing).

**Comment by Langlais115** [comment]
Thanks for your fast reply.
Any idea when this will be? (The release of the next stable release)

**Comment by yohanboniface** [comment]
I hope within the current month.

**Comment by Langlais115** [comment]
Awesome, thanks again.
