### ISSUE TITLE
[Enhancement] To clone marker

### ISSUE THREAD

**Issue by deuzeffe** [umap-project/umap#616]
Hello,

Should you add a feature to clone a marker (point/node in prior) in the (very) next future release ?

Thx (even is the answer is "No!" ^^)

**Comment by yohanboniface** [comment]
https://github.com/umap-project/umap/commit/f96f08fc360cfd29ec579261d93c9862041dd3b9 :)

**Comment by deuzeffe** [comment]
Gnagnagna :P
