### ISSUE TITLE
"Center map on your location" doesn't work

### ISSUE THREAD

**Issue by eehpcm** [umap-project/umap#623]
I turned on the GPS on my Android phone.  Waited for a position lock.  Then went to one of my maps and touched "Center map on your location."  The button flashed, but nothing else happened.  I tried it with both Chrome and Firefox.

I then tried the same thing on my desktop computer with Firefox.  Firefox ought to have popped up a dialogue box asking if I wanted to reveal my location.  It didn't.

Either uMap is broken or I am. :)

**Comment by yohanboniface** [comment]
Where you in https ?

**Comment by eehpcm** [comment]
@yohanboniface 

I wasn't.  At around the time you posted this I was looking into this myself.  I read that in most browsers geolocation only works with https, so gave it a go and it worked.  I was just about to answer my own question here (for the benefit of anyone else) but checked my mail and saw you'd already answered.

Two things, though.

1) Your geolocation doesn't have the dot and disc of openstreetmap.  I kinda miss that.  The dot for where GPS thinks I am, the disc for the uncertainty.  The dot is better than trying to gauge the centre of the map by eye.  The disc is very useful if you're out and about and trying to figure out if you're on a path or not: knowing the uncertainty in your position may prevent misinterpreting where you are.

2) I now understand other issues here about https redirects.  Currently u.osmfr.org/m/nnnnn doesn't support https. :(

**Comment by Dirk71** [comment]
Oh yes indeed.... with https it's working! THANK YOU!!!

**Comment by GreggSq** [comment]
@Dirk71 
How do you enable https on the umap pages?
