### ISSUE TITLE
Unable to modify the map I created

### ISSUE THREAD

**Issue by zarmal** [umap-project/umap#624]
Hello,
I created the following map https://framacarte.org/fr/map/videosurveillance-a-gaillac_28438#13/43.9123/1.9320 after signing in with my account. Now I can not even edit it. Did I make something wrong?
Thanks for helping newbies,
*Z*

**Comment by eehpcm** [comment]
I know they have some problems with https redirects.  Try [this](http://u.osmfr.org/m/28438) (which will  always work even if you change the name of the map).  Once you're in, lock the map to the zoom and location you want (eighth button down in the edit buttons, the one above the key) and that URL will always take you straight there.

**Comment by vinber** [comment]
You don't have a "pen" in the up right corner ?
Are you sure you signed in, then you click on your map ?

**Comment by Binnette** [comment]
Hi @zarmal, please read my FAQ here: https://wiki.openstreetmap.org/wiki/UMap/FAQ#Why_can.27t_I_edit_my_map.3F

I"m closing your ticket. Feel free to reopen it if needed.
