### ISSUE TITLE
umap.openstreetmap.fr results in nginx welcome page

### ISSUE THREAD

**Issue by eehpcm** [umap-project/umap#632]
I noticed, after the recent server maintenance, that [http://umap.openstreetmap.fr](http://umap.openstreetmap.fr) gives an nginx welcome page.  I could be misremembering, but didn't it do a browser language detect in the past and redirect to the appropriate place?  If it didn't, then it should at least list available languages rather than just saying "Welcome to nginx on Debian!"

**Comment by yohanboniface** [comment]
Weird.
Seems to work for me:

```
$ http http://umap.openstreetmap.fr                                                                                                                                      100ms
HTTP/1.1 302 Found
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Mon, 10 Sep 2018 15:53:40 GMT
Location: /en/
Server: nginx/1.10.3
Transfer-Encoding: chunked
Vary: Cookie
```

**Comment by eehpcm** [comment]
I get the same thing when I use telnet to talk http to it.

I fired up my crappy computer to try it.  Exact same version of firefox.  Exact same add-ons.  That worked.  Grrrrrrrrr.  Sorry to have bothered you.

There are days when I hate computers.  It's the days with a "y" in them.
