### ISSUE TITLE
Labels' way of display is locked

### ISSUE THREAD

**Issue by Al-Hun** [umap-project/umap#633]
Hello !
Default way of displaying labels in my map was "on hover" and I wanted to define for some icons only "never" and "always". It seems that was the beginning of my problem : now the default is "never" and if I change it, save, and immediatly verify, it's still "never"...
I tried to export (umap format) and re-import in a newly created map : it's the same. Maybe manually changing something in the umap file before re-importing ?

We have a important event next week-end and I had used it to promote osm/umap in my townhill, so I'm very despited. 
Any suggestions ?

Alain.

**Comment by yohanboniface** [comment]
@Al-Hun fix is released, can you check on your side?
And if it's not ok, please share the map URL.

**Comment by Al-Hun** [comment]
Merci pour la réactivité !Le fix a fait son oeuvre mais, niveau affichage, on a toujours l'impression quand on change le comportement par défaut et que l'on revient dessus après enregistrement que ça n'a pas été pris en compte. 

Par ailleurs bravo pour la nouvelle possibilité d'indiquer une lettre en guise de pictogramme. J'ai vu que ça fonctionnait aussi avec des nombres même sur plusieurs digits, c'est carrément parfait pour indiquer des balises, d'autant que c'est compatible avec l'utilisation d'un champ de donnée (mais ce n'est pas mentionné dans la petite aide).Je me rends compte qu'il y a eu récemment de nombreuses évolutions alors encore merci. uMap est non seulement très utile en soi, mais aussi un formidable outil pour "évangéliser" à l'usage d'osm !
Alain.
   Le lundi 10 septembre 2018 à 22:50:51 UTC+2, Yohan Boniface <notifications@github.com> a écrit :  
 
 
@Al-Hun fix is released, can you check on your side?
And if it's not ok, please share the map URL.

**Comment by yohanboniface** [comment]
> Merci pour la réactivité !Le fix a fait son oeuvre mais, niveau affichage, on a toujours l'impression quand on change le comportement par défaut et que l'on revient dessus après enregistrement que ça n'a pas été pris en compte.

Tu peux être un peu plus précis sur le pas à pas pour reproduire? :)
Et partager l'URL de la carte, que je vois si je reproduis quelque chose.

**Comment by yohanboniface** [comment]
OK, compris, je regarde ça!

**Comment by yohanboniface** [comment]
Voilà, ça devrait aller mieux :)

**Comment by Al-Hun** [comment]
Désolé pour le temps de retard : hier soir c'était la réunion mensuelle osm des lyonnais...Je viens de vérifier, tout est ok, merci !Alain.
Pour info, la carte concernée : https://frama.link/50ansbelair 


    Le mardi 11 septembre 2018 à 20:19:02 UTC+2, Yohan Boniface <notifications@github.com> a écrit :  
 
 
Voilà, ça devrait aller mieux :)
