### ISSUE TITLE
Error Saving Changes

### ISSUE THREAD

**Issue by Morten11** [umap-project/umap#636]
Dear people,

I have a problem saving changes in my map. Whenever I try to save any changes I`ll receive a message saying

> Someone else seems to have edited the data. You can save anyway, but this will erase the changes made by others. (see atachement)

It does not matter how often I save my changes afterwards. Once I close and re-open uMap, my map will always fall back to the stage it was before I did the last session of changes. Maybe there is a bug or something. 

Please help!

Kind regards
Morten
![saving error umap](https://user-images.githubusercontent.com/37325151/45370069-98db2c80-b611-11e8-9205-6e4ca687bb21.jpg)

**Comment by yohanboniface** [comment]
This usually is the symptom of a "bad tuned" proxy.
So basically, the proxy would cache the request too much, and thus when you load the map, you load the map from the proxy and not from uMap, but when you save, you do save to uMap.
To investigate a bit, could you try:
- same computer but another browser
- same browser, but another network (eg using your phone connection if you are on wifi, or using your home connection if you are at work, etc.)

**Comment by Morten11** [comment]
Dear Yohan,

thanks for your help. I did the requested investigation.
The mentioned issue happened in firefox and it continues happening in
firefox, even when I use another network.
Using Chrome the latest changes are shown as I saved them (good news).

Question: What can I do to solve the problem with firefox, as it is my
standard browser?





Am Di., 11. Sep. 2018 um 23:47 Uhr schrieb Yohan Boniface <
notifications@github.com>:

**Comment by yohanboniface** [comment]
> The mentioned issue happened in firefox and it continues happening in firefox, even when I use another network. 

Can you open the "Web developer" network panel, and click on the URL that looks like the URL of your map (the URL displayed in your browser URL bar), and then copy-paste or screenshot the request and response headers?

**Comment by Morten11** [comment]
Dear Yohan,

I followed your instruction and ended up with reloading the website once I
opened the Web Developer Network Panel. After reloading the issue was
solved. Now all my latest changes appear in the map.
Thanks for the successful support!

Morten

Yohan Boniface <notifications@github.com> schrieb am Mi., 12. Sep. 2018,
16:15:
