### ISSUE TITLE
Géolocalisation umap KO 

### ISSUE THREAD

**Issue by odelbucc** [umap-project/umap#637]
Bonjour,

Sur une carte personnalisée, le bouton de géolocalisation est inactif (sur iOS / Safari). Les services de localisation sur l'app "Sites Safari" est à "App active" dans mes réglages.

Dans la même idée, quand je fais des recherches de lieu sur la carte, elle ne sont pas du tout géolocalisées (il me sort des restaurant aux états unis par exemple).

Merci de votre retour

Olivier

**Comment by yohanboniface** [comment]
> Sur une carte personnalisée, le bouton de géolocalisation est inactif (sur iOS / Safari). Les services de localisation sur l'app "Sites Safari" est à "App active" dans mes réglages.

https ou http?

**Comment by odelbucc** [comment]
http. j'ai essayé avec https : la l'url est KO

**Comment by odelbucc** [comment]
J'obtiens la page "Safari ne peut pas ouvrir la page car la connexion au serveur est impossible".
en http, ca marche bien.
=> Je viens de comprendre : En fait c'est avec l'url courte que ca ne marche pas, avec l'url complète, ca fonctionne bien

**Comment by odelbucc** [comment]
OK, c'est KO sur Gandi. Pour info, ca fonctionne avec bitly.

Merci de votre réactivité !

Olivier

**Comment by yohanboniface** [comment]
> Par contre, en suggestion d'amélioration, ce serait pas mal que la recherche de lieux tienne compte de la géolocatlisation,e t qu'on propose en priorité des lieux près de notre position

C'est le cas: la position du centre de la carte est envoyée au moteur de recherche (Photon), qui les utilise dans sa pondération.
