### ISSUE TITLE
Can no longer retrieve tag values from Overpass data in OSM format

### ISSUE THREAD

**Issue by naomap** [umap-project/umap#641]
There seems to be a regression in the ability to retrieve tag values from an Overpass request producing data in the OSM format. 

This map http://u.osmfr.org/m/189194/, when you zoom in to level 16, uses an Overpass request to retrieve bicycle locations (blue markers). The popup template is: 
`# {name}
{capacity} emplacements
Carte bancaire : {payment:credit_cards}
{note}`

However no tat value get injected into this template. The request produces data in the OSM format:
`http://overpass-api.de/api/interpreter?data=%5Bout%3Axml%5D%5Btimeout%3A25%5D%3Barea%283600059874%29%2D%3E%2EsearchArea%3B%28node%5B%22amenity%22%3D%22bicycle%5Frental%22%5D%28area%2EsearchArea%29%3Bway%5B%22amenity%22%3D%22bicycle%5Frental%22%5D%28area%2EsearchArea%29%3Brelation%5B%22amenity%22%3D%22bicycle%5Frental%22%5D%28area%2EsearchArea%29%3B%29%3Bout%3B%3E%3Bout%20skel%20qt%3B%0A`

The same applies when you zoom in further to see individual bicycle parkings.

**Comment by yohanboniface** [comment]
Should be fixed and deployed :)
Thanks for the report!

**Comment by naomap** [comment]
It works perfectly.
Thanks for the fix :o)
