### ISSUE TITLE
Save button says "OK" but doesn't save

### ISSUE THREAD

**Issue by pertile** [umap-project/umap#642]
Hi, sometimes it fails to save my map. My workaround is to export the map and then import it to a new map. The worst thing about it is to realize that a lot of changes you saved aren't there; this could be something that makes people to leave this platform.

I had the same issue at least 4 times.

This map has the issue now: https://umap.openstreetmap.fr/es/map/clasificacion-rutas_206486#7/-30.732/-62.238. If I delete any line, save and then enter again line is still there. I no longer use this map (I have a copy) so edit it as you need.

**Comment by yohanboniface** [comment]
Sounds like a proxy issue: the map is saved, but when you reload it, a proxy before uMap is serving you an old copy.
Next time you see the problem try to load the map from another network and another browser, for example checking with your phone if you have a "smart" one.

**Comment by Binnette** [comment]
No response from user. Feel free to reopen issue.
