### ISSUE TITLE
How to adjust the side panel design

### ISSUE THREAD

**Issue by playoff001** [umap-project/umap#644]
I try to create a multi-layer map project. Where can I modify the look so that the layout with the objects opens or closes when clicked as a harmonica? Sample here: 
![list](https://user-images.githubusercontent.com/18735027/46093866-c949cb80-c1b8-11e8-9a60-6c1f6f6e9b8f.jpg)

And the second question: How do I default to set a specific map section instead of a whole Western Europe map when refresh the page? Thank you
https://umap.openstreetmap.fr/cs-cz/map/lanskroun_250918#17/49.91276/16.61329

**Comment by yohanboniface** [comment]
Toggling layers list has been done in 2.2.
