### ISSUE TITLE
Update Maki marker icon collection

### ISSUE THREAD

**Issue by robinmetral** [umap-project/umap#648]
I've noticed uMap is using some of Mapbox's [Maki marker icons](https://www.mapbox.com/maki-icons/) (CC0 and [on Github](https://github.com/mapbox/maki)).

There are many other icons in the Maki collection that are not natively offered on uMap. Is there a reason for this?

For my personal use the uMap marker icon selection is pretty restrictive, and since Maki icons are originally SVGs, I can't use a custom icon link straight from their Github repo ([example](https://raw.githubusercontent.com/mapbox/maki/master/icons/aerialway-15.svg))

Is there a plan to update the uMap marker icons according to the current Maki icon collection?

**Comment by Binnette** [comment]
Hi, I wrote a doc in order to update icon markers: 128358a

Which instance do you use? https://umap.openstreetmap.fr? https://umap.openstreetmap.de? Because icons are related to uMap configuration (not to uMap source code). So we need to know which instance you are using.

**Comment by robinmetral** [comment]
Hi @Binnette, thanks for the doc and thanks your reply! I'm using the hosted https://umap.openstreetmap.fr/, I don't have my own instance.

FYI, this was reported over a year ago and I don't really need this feature anymore - but I'll leave it open in case others are interested. Feel free to close.

**Comment by Binnette** [comment]
@jocelynj can I suggest you to add following icons in https://umap.openstreetmap.fr ?

1. ![attraction-24](https://user-images.githubusercontent.com/6597721/75292247-1c97d180-5824-11ea-8ed2-ba735d2b729c.png) attraction
1. ![car-24](https://user-images.githubusercontent.com/6597721/75292250-1d306800-5824-11ea-8b68-fae94fd2e5f3.png) car
1. ![castle-24](https://user-images.githubusercontent.com/6597721/75292251-1dc8fe80-5824-11ea-84c9-0e6ab08ef08b.png) castle
1. ![clothing-store-24](https://user-images.githubusercontent.com/6597721/75292252-1dc8fe80-5824-11ea-9810-9b3ffbd42af3.png) clothing-store
1. ![communications-tower-24](https://user-images.githubusercontent.com/6597721/75292253-1e619500-5824-11ea-90d4-53892a792490.png) communications-tower
1. ![convenience-24](https://user-images.githubusercontent.com/6597721/75292254-1e619500-5824-11ea-9755-6ca5636342bb.png) convenience
1. ![drinking-water-24](https://user-images.githubusercontent.com/6597721/75292255-1efa2b80-5824-11ea-8b69-384ffffd076f.png) drinking-water
1. ![home-24](https://user-images.githubusercontent.com/6597721/75292258-1efa2b80-5824-11ea-8ca0-f79bc1ab71ec.png) home
1. ![industry-24](https://user-images.githubusercontent.com/6597721/75292262-1f92c200-5824-11ea-98f2-50c1423ae3b2.png) industry
1. ![information-24](https://user-images.githubusercontent.com/6597721/75292265-1f92c200-5824-11ea-96db-91b8dfd18b8b.png) information
1. ![mobile-phone-24](https://user-images.githubusercontent.com/6597721/75292266-202b5880-5824-11ea-97a5-dea77e177be8.png) mobile-phone
1. ![music-24](https://user-images.githubusercontent.com/6597721/75292267-202b5880-5824-11ea-8a9e-b839fd145146.png) music
1. ![picnic-site-24](https://user-images.githubusercontent.com/6597721/75292268-20c3ef00-5824-11ea-80b7-7e4d4667155d.png) picnic-site
1. ![recycling-24](https://user-images.githubusercontent.com/6597721/75292270-20c3ef00-5824-11ea-9dab-cadbbef92a5c.png) recycling
1. ![waste-basket-24](https://user-images.githubusercontent.com/6597721/75292272-215c8580-5824-11ea-95ed-df71d376277a.png) waste-basket
1. ![water-24](https://user-images.githubusercontent.com/6597721/75292274-215c8580-5824-11ea-9173-0337ba209b39.png) water
1. ![zoo-24](https://user-images.githubusercontent.com/6597721/75292278-215c8580-5824-11ea-8e8c-e87099ad6d1a.png) zoo

Currently, we have 54 black icons and the same 54 icons in white on https://umap.openstreetmap.fr

Maki icon set have a total of 187 unique icons. So I selected the most interesting ones.

© https://labs.mapbox.com/maki-icons/

**Comment by yohanboniface** [comment]
There two [config](https://github.com/umap-project/umap/blob/master/osmic.yaml) [files](https://github.com/umap-project/umap/blob/master/osmic-white.yaml) in uMap root to work with https://gitlab.com/gmgeo/osmic so it will generate the icons with correct dimensions and borders and such.
Then those can be imported with "import_pictograms".
One more thing I need to document :/

**Comment by Binnette** [comment]
Cool. I was not aware of those files. I will try to use them and document how if I succed. I already started documenting on how to import Maki icon set.

**Comment by yohanboniface** [comment]
Closing in favor of #1194
