### ISSUE TITLE
stamen watercolor missing from list of tiles

### ISSUE THREAD

**Issue by timoto** [umap-project/umap#650]
Err, have the watercolor tiles been removed from umap ?

![image](https://user-images.githubusercontent.com/1268358/48332217-021d0180-e68e-11e8-9b6a-73242c66b304.png)

**Comment by yohanboniface** [comment]
Nice paint!
AFAIK, there is not https version of wetercolor.

**Comment by timoto** [comment]
Also did you try this:
https://stamen-tiles.a.ssl.fastly.net/watercolor/1/1/1.jpg

Because that is what I'm using on another site.

**Comment by yohanboniface** [comment]
> Also did you try this:
https://stamen-tiles.a.ssl.fastly.net/watercolor/1/1/1.jpg

Thanks, I've updated the link, it should appear now in https :)

**Comment by timoto** [comment]
Thanks  @yohanboniface the selection is now available.

However the result is not as expected. Tiles are systematically not being rendered:
![image](https://user-images.githubusercontent.com/1268358/48337078-eb31db80-e69c-11e8-8c44-961e57589b5e.png)
