### ISSUE TITLE
How do I view more than 50 of my own maps

### ISSUE THREAD

**Issue by thewebkit** [umap-project/umap#651]
Hello there ! 

First of all great work with umap, it's awesome.

I've a project on umap for which I created more than 50 maps, but the "My maps" page only allows me to view the last 50 maps I've created (by clicking 4 times on the 'more' button). I've tried using the ?p=6 query, but past ?p=5 the result is always the same.

@yohanboniface This issue was already adressed to you on osm forums more in 2017, but I guess the hard coded limit is still on. Have you any plan on raising this limit anytime soon ?

If not, one solution might be for me to host my own umap server. 
**Can you confirm me that I would be able to change that limitation if I host my own umap ?**

Thanks for your time !

Related topic on OSM : https://help.openstreetmap.org/questions/57549/how-do-i-view-more-than-50-of-my-own-maps-in-umap

**Comment by yohanboniface** [comment]
> @yohanboniface This issue was already adressed to you on osm forums more then a year ago, but I guess the hard coded limit is still on. Have you any plan on raising this limit anytime soon ?

Was out of my radar, sorry. I'll update it on next rc release.

> If not, one solution might be for me to host my own umap server.
Can you confirm me that I would be able to change that limitation if I host my own umap ?

Yes!

**Comment by thewebkit** [comment]
> 
> Was out of my radar, sorry. I'll update it on next rc release.
> 

Thanks for your superfast response !
Is there any way to have an indication to when this next release will come out ? 

In the meantime I'll look into creating my own umap server - never worked with geoDjango before but it will be good experience !

**Comment by yohanboniface** [comment]
>  Is there any way to have an indication to when this next release will come out ?

More or less once rc release a month ultimately: https://github.com/umap-project/umap/releases

Closer and closer to get a proper 1.0 release too, I guess before end of year.

**Comment by Player701** [comment]
Sorry if this is not the right place to write about this. It seems that the limit that was discussed here is unfortunately still in place on https://umap.openstreetmap.fr/ - I can only see 50 of my last maps. Am I by chance doing something wrong?... Tried logging out and back in, clearing cache, cookies, the usual stuff... it doesn't seem to get better :(

**Comment by brunellop** [comment]
Hello there !
About three years later I reopen the question, the limit is currently 100 maps, so in my case where I have many more maps the problem remains.
Why was it never considered to include the 'Search maps' button also on proprietary maps and not only on public maps?

Thank you.
