### ISSUE TITLE
Unable to save layer changes

### ISSUE THREAD

**Issue by FrViPofm** [umap-project/umap#653]
When changing and saving layer properties (e.g. choosing the cluster type) , I get the message (in French) **"Aïe! Quelqu'un d'autre semble avoir modifié la carte. Vous pouvez continuer l'enregistrement, mais ses données seront perdues"**. *Hum, I doubt that someone else is changing my map just now...* I click on **"continuer"** and then I get the message saying that the changes are saved. But not at all ! When reloading the map, nothing has been changed.

Have a look at : https://umap.openstreetmap.fr/fr/map/conversion-ecologique_5642

Some days ago it append to work, sometimes. Some layers are now as clusters.

But, nevertheless, a very good tooL Many thanks.

**Comment by yohanboniface** [comment]
Can you try from another network by chance ?
Eg. 4G network sharing if you are on your home/work wifi, or vice-versa.

**Comment by Binnette** [comment]
No response from user. Feel free to reopen the issue if needed.

**Comment by oupala** [comment]
I'm having the same problem on the umap instance of [Framasoft](https://framasoft.org/): [Framacarte](https://framacarte.org/). I think it would be great if you can reopen the issue.

If I can help you debugging the problem if needed.
