### ISSUE TITLE
Watercolor tiles not rendering as expected

### ISSUE THREAD

**Issue by timoto** [umap-project/umap#655]
Tiles are systematically not being rendered:
![image](https://user-images.githubusercontent.com/1268358/48337078-eb31db80-e69c-11e8-8c44-961e57589b5e.png)

_Originally posted by @timoto in https://github.com/umap-project/umap/issues/650#issuecomment-437805689_

**Comment by momu** [comment]
Problem seems to be, that the servers  https://stamen-tiles.b.ssl.fastly.net and https://stamen-tiles.c.ssl.fastly.net  are giving error 500 when requesting a tile.

Check the same tile on all servers: 
* https://stamen-tiles.a.ssl.fastly.net/watercolor/15/17622/10763.jpg (working)
* https://stamen-tiles.b.ssl.fastly.net/watercolor/15/17622/10763.jpg  (not working)
* https://stamen-tiles.c.ssl.fastly.net/watercolor/15/17622/10763.jpg (not working)

Error is:

```
Fastly error: unknown domain: stamen-tiles.b.ssl.fastly.net. Please check that this domain has been added to a service.

Details: cache-fra19140-FRA
```

**Comment by timoto** [comment]
Well spotted. @yohanboniface Can you just use the 1 subdomain instead ?

**Comment by yohanboniface** [comment]
Maybe this should be instead reported to Stamen people for a proper fix.

cc @almccon anything doable on your side? Thanks :)

**Comment by gelmio** [comment]
I'm still having this same issue, and it makes the tiles unusable.
This is clearly a problem that Stamen is having (and I've reported it to them), but would it be possible to change the umap code so that we only pull the tiles from the one subdomain that works? That subdomain being `https://stamen-tiles.a.ssl.fastly.net/watercolor/`

**Comment by gelmio** [comment]
I've found the fix for this:
In umap in the editor, head to settings and then under custom background change this `https://stamen-tiles.{s}.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg` to this `https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg`
Thrilled I can use this set of tiles

**Comment by almccon** [comment]
Hi there from Stamen. Sorry it's a bit weird, but you don't replace the `.a.` part. If you want to access multiple subdomains, you instead add `-{S}` after `stamen-tiles`. 

So the full template would be this: 

`https://stamen-tiles-{S}.a.ssl.fastly.net`

NOT this:

`https://stamen-tiles.{S}.ssl.fastly.net`

See the documentation here: http://maps.stamen.com

**Comment by gelmio** [comment]
> Hi there from Stamen. Sorry it's a bit weird, but you don't replace the `.a.` part. If you want to access multiple subdomains, you instead add `-{S}` after `stamen-tiles`.
> 
> So the full template would be this:
> 
> `https://stamen-tiles-{S}.a.ssl.fastly.net`
> 
> NOT this:
> 
> `https://stamen-tiles.{S}.ssl.fastly.net`
> 
> See the documentation here: http://maps.stamen.com

Works perfectly. Would be good to change the code in UMap so that the workaround doesn't have to be done manually for the tiles to be downloaded.

**Comment by yohanboniface** [comment]
Done on umap.openstreetmap.fr!

Sorry for the lag.
