### ISSUE TITLE
Share iframe code: use https instead of http 

### ISSUE THREAD

**Issue by bagage** [umap-project/umap#657]
When you hit the share Iframe button on http://umap.openstreetmap.fr/fr/map/al-romainville-2019_278896#14/48.8809/2.4475, the generated code is:

```html
<iframe width="100%" height="300px" frameBorder="0" allowfullscreen src="http://umap.openstreetmap.fr/fr/map/al-romainville-2019_278896?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false"></iframe><p><a href="http://umap.openstreetmap.fr/fr/map/al-romainville-2019_278896">Voir en plein écran</a></p>
```

To make it work also on https website, it would be good to use https scheme instead, eg `src="https://umap.openstreetmap.fr`.

**Comment by yohanboniface** [comment]
It uses whatever the protocol you are using at the moment. :)

**Comment by bagage** [comment]
Oh indeed :). Not sure why it does not default to https automatically but make sense, my bad. Thanks @yohanboniface!
