### ISSUE TITLE
GPS localisation does not work

### ISSUE THREAD

**Issue by Dirk71** [umap-project/umap#658]
I tried all kind of browsers on my smartphone (Android 8.0) but localisation by GPS does not work at all.

**Comment by yohanboniface** [comment]
Where you in https ?

cf https://github.com/umap-project/umap/issues/623

**Comment by Dirk71** [comment]
Dear Yohan,

I am a huge fan of umap and I am very thankful you share your great work with others.

I am currently developing an Excel Tool on Visual Basic. Imagine each route has an ID (own defined tag). One just has to put in the ID’s of the routes he want to generate as GPX-File. Then he has just to push a button and the GPX-File will be downloaded containing the geo-information. This gpx-file can be used with GPS-Apps like Oruxmaps to navigate.

The tool will be finished soon and I will share it with you.

The biggest challenge was, to sort the geo-data in order to obtain one route containing the geo-data in the correct order. I found an algorithm to get this done. Now that I have the most difficult part finished, I think, I will be ready soon.

I think, this is a huge benefit for umap-users.

I will get back to you as soon I have the first beta-version available.

Best regards,

Dirk

**Comment by Dirk71** [comment]
Hello Yohan,

I have developed an Excel-Tool (VBA) to generate GPX-Data based on umap.

You will find more information and a download link in the following document:

https://docs.google.com/document/d/1xLzCD1kvu5rB9XwG0_hbXAK1lRf_gIU6BtbAnK0GGU4/edit?usp=sharing

I hope you will enjoy.

Best regards,
Dirk

https://dzhome.de

**Comment by Dirk71** [comment]
Hello Yohan,

there is a new release of Geo-Tool, completely rewritten with a lot of solved bugs and new features.

If you are interested to test it, you’ll find it here….

Tutorial

https://1drv.ms/w/s!ArhiczfRMumOj1Z4nnUePRX4WPvD?e=PONqtB <https://1drv.ms/w/s!ArhiczfRMumOj1Z4nnUePRX4WPvD?e=PONqtB>

UGT

https://drive.google.com/open?id=1JDzE3gm6E2BuR86r5IC6f47xml-hr3wP <https://drive.google.com/open?id=1JDzE3gm6E2BuR86r5IC6f47xml-hr3wP>

Regards,
Dirk



> Am 25.08.2019 um 15:09 schrieb Dirk Ziegler <dzonline71@gmail.com>:
> 
> Hello Yohan,
> 
> I have developed an Excel-Tool (VBA) to generate GPX-Data based on umap.
> 
> You will find more information and a download link in the following document:
> 
> https://docs.google.com/document/d/1xLzCD1kvu5rB9XwG0_hbXAK1lRf_gIU6BtbAnK0GGU4/edit?usp=sharing
> 
> I hope you will enjoy.
> 
> Best regards,
> Dirk
> 
> https://dzhome.de
