### ISSUE TITLE
can't edit my Umap

### ISSUE THREAD

**Issue by jeromeobear** [umap-project/umap#660]
Hi

I created a map a few months ago, before I signed up to Github, and at first I could just edit and add using the url, but now when I put the url in my browser, the edit function is gone from the top right corner of the map. Would someone know why, and how I can resume editing my map?

Best and thanks for your help,
J

**Comment by Binnette** [comment]
Hi, please read the following article.
https://wiki.openstreetmap.org/wiki/UMap/FAQ#Why_can.27t_I_edit_my_map.3F

Feel free to reopen this ticket if needed.
