### ISSUE TITLE
Dynamic properties in Popup template 'wikimedia-commons', 'intro-from-wikipedia', 'wikipedia-from-wikidata'

### ISSUE THREAD

**Issue by sfkeller** [umap-project/umap#661]
My idea is to extend the popup (i.e. the popup template) so that pictures of Wikimedia Commons and Wikipedia texts are displayed as soon as the user clicks on the popup. Related to #185 with the difference that text is fetched ad-hoc. Probably also related to #183.

Suggestion: Extension of the "Popup content template" with "Dynamic properties" which return an image and text (not just the Wikipedia link) based on what is in Wikidata and Wikipedia.

1. Property "wikimedia-commons-from-wikidata" returns the URL of the first Wikimedia Commons image (input Wikidata-Id and the number of returned URLs). 
2. Property "wikipedia-from-wikidata" returns the title (e.g. "fr:Château_de_Chillon") of the Wikipedia page (input: Wikidata id, e.g. Q372647 and language preference list). 
3. Property "intro-from-wikipedia" would return the text of the first paragraph (input: Wikipedia title, e.g. "fr:Château_de_Chillon").

The content of a popup template could look like this for Château de Chillon (Q372647):
```
Image (if available as Wikimedia Commons from Wikidata):
{{ {{wikimedia-commons|Q372647|1}} }}
Caption: {{intro-from-wikipedia|{{wikipedia-from-wikidata|Q372647|fr,en}} }}
```
The syntax proposed here is not quite definitive yet.

Implementation hints:
- Wikipedia query of "Chillon Castle" with JSON respone:  https://en.wikipedia.org/w/api.php?format=json&action=query&prop=extracts&exintro&explaintext&redirects=1&titles=Chillon_Castle
- Wikidata query of "Q60322693" with JSON response: https://www.wikidata.org/wiki/Special:EntityData/Q60322693.json

**Comment by sfkeller** [comment]
After some discussion with @yohanboniface we think a new, separate fixed template is perhaps easier to maintain and more robust.

This template would accept "Wikidata" as parameter, would read the "Wikidata" property, get the Wikimedia Commons and Wikipedia intro text, then it would display the image, the caption and whatever is needed.

**Comment by sfkeller** [comment]
Of course. One is about castles, another about electric power stations, etc. Give me some hours...

**Comment by sfkeller** [comment]
[top100_castles_switzerland_plus_surroundings.zip](https://github.com/umap-project/umap/files/3200085/top100_castles_switzerland_plus_surroundings.zip)
I'm unsure what you expect but I've uploaded finally a GeoJSON containing 100 castles from OSM which alle have tags for Wikidata and Wikipedia.

**Comment by osmvermesser** [comment]
hi !

my english is not very well but it could be an addition ...

i found it could be very helpful to integrate a possibility to show the image of the image tag, when define to wiki-Server like the historic map (http://gk.historic.place/historische_objekte/l/de/index.html)

![2020-09-08_10h12_41](https://user-images.githubusercontent.com/6803899/92450727-106dd300-f1bc-11ea-9090-d969acc48c53.png)

regards Jan

**Comment by yohanboniface** [comment]
I'd suggest to support wiki* tags in the OSM popup template
