### ISSUE TITLE
Embed only gives a blank area + link

### ISSUE THREAD

**Issue by forteller** [umap-project/umap#662]
Hi. Thank you for a great service, which is exactly what I've been looking for! Except that I can't get embeding to work. When I try I only get the full screen link bellow a totally empty area:
![screenshot from 2019-01-22 23-39-21](https://user-images.githubusercontent.com/343561/51570452-58cd6580-1e9f-11e9-85cd-a753f2e458f8.png)

I tried turning off all blocking extension before taking this screenshot. Also no VPN.

I tried a couple of different embed options, with the same result.

Here's the code I used:

`<iframe width="100%" height="300px" frameBorder="0" allowfullscreen src="http://umap.openstreetmap.fr/en/map/untitled-map_285394?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=false&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=caption&captionBar=false&datalayers=748987"></iframe><p><a href="http://umap.openstreetmap.fr/en/map/untitled-map_285394">See full screen</a></p>`

Hope you can help me. Thank you very much!

**Comment by yohanboniface** [comment]
Try using the https URL instead.

**Comment by forteller** [comment]
Thank you! That worked! But I can't find a way to have the Draw a marker function in the embed. Is this possible? Or should I open a new issue for this?

**Comment by Binnette** [comment]
I think we should change the generated "Embed the map" code from:
`<iframe [...] src="http://umap.openstreetmap.fr/[...]"></iframe><p><a href="http://umap.openstreetmap.fr/[...]">See full screen</a></p>`

To:
`<iframe [...] src="//umap.openstreetmap.fr/[...]"></iframe><p><a href="//umap.openstreetmap.fr/[...]">See full screen</a></p>`
