### ISSUE TITLE
OSM SSO user omits non-ASCII character

### ISSUE THREAD

**Issue by TZornG** [umap-project/umap#663]
I have used an OSM account called 'Dhünn' to log into umap.openstreetmap.fr. There my user gets abbreviated to 'Dhnn'. The 'ü' gets skipped. This happens  in the page url: http://umap.openstreetmap.fr/en/user/Dhnn/ as well as in the page text. 

OSM user: https://www.openstreetmap.org/user/Dhünn

**Comment by TZornG** [comment]
Note that the same user name works all right on the German instance umap.openstreetmap.de.

**Comment by yohanboniface** [comment]
@TZornG could you try login in again ? Seems this has been fixed with recent version of python-social-auth.

**Comment by yohanboniface** [comment]
Should be fixed. Please reopen if it's not!

**Comment by TZornG** [comment]
I can confirm it is working as expected now. Thanks!
