### ISSUE TITLE
Sign up with GitHub fails some days

### ISSUE THREAD

**Issue by LesLibresGeographes** [umap-project/umap#666]
On last Sunday February 3, I tried many times to connect on with this GitHub account but it failed every time, getting this 404 message :
![selection_015](https://user-images.githubusercontent.com/34093668/52272208-d9bb4100-2924-11e9-97b0-38059f52ddb4.png)

It happens regularly for me. 

Today sign works perfectly fine. 
![selection_016](https://user-images.githubusercontent.com/34093668/52272235-e344a900-2924-11e9-9f15-4d312a8699e2.png)

Is there something in the log files that would provide an explanation?

**Comment by yohanboniface** [comment]
#450 ? ;)

**Comment by LesLibresGeographes** [comment]
ah, I had searched on "sign up', not "login"
