### ISSUE TITLE
Default zoom not stable with Firefox

### ISSUE THREAD

**Issue by Rpnpif** [umap-project/umap#667]
Hello,
I set a default zoom on my maps embedding all the icons that I had set.
When I reopen a map, the page is refreshing permanently indefinitely. This is annoying and do an image of the map unstable. The CPU activity is high.

If I changed the actual zoom, this issue disappears.

All values of default zoom are affected.

Regards.

The same in French language, perhaps for a better explanation.

En général, je règle un zoom par défaut pour l'ouverture de mes cartes;
Mon problème : quand j'ouvre mes cartes, elles sont instables et sont rafraîchies en permanence, indéfiniment, avec une activité du CPU élevée.
Il n'est pas facile de faire cesser l'effet sauf en changeant le zoom actuel. Ceci me semble être un bogue.

**Comment by Rpnpif** [comment]
This issue was observed on all my systems.

**Comment by yohanboniface** [comment]
Which map?

**Comment by Rpnpif** [comment]
I am frustrated because I cannot reproduce this issue today.

This concerned this map and others on the Framacarte.org instance.
https://umap.openstreetmap.fr/fr/map/associations-adherentes-a-la-sauvegarde-de-lanjou_290111

Perhaps, it is depending of the Firefox window size. I do not know.

With the next occurrence, I will try to record a video.

**Comment by Binnette** [comment]
I close this issue for now, Feel free to reopen it if needed.
