### ISSUE TITLE
remove openmapsurfer tile layer

### ISSUE THREAD

**Issue by tyrasd** [umap-project/umap#668]
The korona.geog.uni-heidelberg.de server was shut down. ~~OpenMapSurfer tiles are now available from a new URL. Normally, one would need an API key for this, but for umap you can use `https://maps.heigit.org/openmapsurfer/tiles/roads/webmercator/{z}/{x}/{y}.png` for now (//cc @TimMcCauley). See https://ask.openrouteservice.org/t/openmapsurfer-api/233 for more information.~~

**Comment by joker234** [comment]
The mapsurfer tiles are not available anymore and should be removed permanently. See also:
* https://github.com/leaflet-extras/leaflet-providers/pull/354#issuecomment-627505860
* https://ask.openrouteservice.org/t/mapsurfer-discontinued/1873

**Comment by tyrasd** [comment]
This was solved on the "main" umap instance via https://github.com/osm-fr/infrastructure/issues/319
