### ISSUE TITLE
Access some geojson properties and handle accent in properties 

### ISSUE THREAD

**Issue by jdlom** [umap-project/umap#676]
Hi,
I think there is a problem with properties with some special characters (accent é for example). 
And it seems not possible to access some properties of the geojson.

## Results
Variable in template | Is working ? | 
------------ | -------------
{Nom} | ok
{Accessibiilité} | **ko**
{Adresse.Ligne} | ok
{CoordonnéesNum.Téléphone} | **ko**
{CoordonnéesNum['Téléphone']} | **ko**
{CoordonnéesNum.Email} | **ko**
{Ouverture.PlageJ[0].début} | **ko**
{Ouverture.PlageJ[0].fin} | **ko**
({Ouverture.PlageJ[0].PlageH.début} | **ko**
{Ouverture.PlageJ[0].PlageH.fin} | **ko**

## Sample data for testing
Based on this api : 
* https://api.gouv.fr/api/api_etablissements_publics.html

I have a geojson from this source :
* https://etablissements-publics.api.gouv.fr/v1/organismes/27/mairie

My umap url (everybody can edit)  : 
* http://umap.openstreetmap.fr/fr/map/clone-de-service-public-dans-leure_303846

Thank you for your amazing work !
Best regards,

**Comment by davidbgk** [comment]
@jdlom the geojson from the API is now deprecated. The closest I found is https://etablissements-publics.api.gouv.fr/v3/departements/27/mairie and it doesn't have any special character (which is probably a good idea :)).

Do you still have the issue? Can you share a map+source of data if that's the case?

**Comment by jdlom** [comment]
@davidbgk I come to you if I find an other example. If I don't, you could close this issue.
