### ISSUE TITLE
Map units, alternative to lat/lon for POI coordinates

### ISSUE THREAD

**Issue by rawdr** [umap-project/umap#677]
I'm attempting to use uMap for a non-earth (video game) map with simple xyz coordinates for POI's. I've managed to get the custom background working by using QGIS to georeference a jpeg image, export as GeoTIFF, convert to tiles with gdal2tiles.py, and host the resulting tiles. The uMap measuring tool gives correct distances in meters when compared to the game, so this is good.

I can begin adding POI's visually now, but they are stored with latitude/longitude coordinates which have no real relevance to the data source (x-y coordinates as 'meters' roughly up to 10000, thus lat/lon very near 0). This is problematic if I want to add POI's from in-game coordinates or from an existing database. 

I tried changing to different CRS settings but with no change in this regard. Is there any way to change the map units so it uses meters instead of latitude and longitude?

Thanks.

**Comment by Binnette** [comment]
Hi @rawdr, i think you should consider implement your own map based on Leaflet. You will have way more control for your use case. I close this issue for now, feel free to reopen if needed.
