### ISSUE TITLE
Correction of street name 

### ISSUE THREAD

**Issue by RoosPM65** [umap-project/umap#678]
Latitude:     -34,080486594406665  
Longitude:  22,14977324008942
The name of the street is spelled .    The name is NOT Implala Road.  The correct spelling is **Impala** Road.
![image](https://user-images.githubusercontent.com/10368910/54800827-a03c5c00-4c6c-11e9-8985-7dbe0b2f1a6c.png)

**Comment by vinber** [comment]
I created a note in OpenStreetMap (https://www.openstreetmap.org/note/1718877) because correction must occur in OpenStreetMap, not in Umap.
