### ISSUE TITLE
Setting default zoom level for search results

### ISSUE THREAD

**Issue by Aureuum** [umap-project/umap#679]
Hello,
I'm setting the Default Zoom level for the map to 10, but when searching, the result still appears at a zoom level of 16. I would like to set default zoom level for search results individually for each map. 
Is this possible?
Thank you!

**Comment by Binnette** [comment]
Hi, i don't think it is possible yet.

**Comment by yohanboniface** [comment]
Yes, zoom when clicking on a search result is now hard coded: https://github.com/umap-project/umap/blob/master/umap/static/umap/js/umap.controls.js#L882

I guess to fix this, we'd also need to fix #419
