### ISSUE TITLE
umap https certificate expired

### ISSUE THREAD

**Issue by TajinValorian** [umap-project/umap#686]
![grafik](https://user-images.githubusercontent.com/657341/56272099-5410fa00-60fa-11e9-99f4-956636315501.png)

**Comment by yohanboniface** [comment]
Seems to be taginfo not umap?

**Comment by yannicka** [comment]
Yes, the certificate has expired ("mardi 16 avril 2019 à 23:17:23"): 

![image](https://user-images.githubusercontent.com/22885898/56274639-65103a00-60ff-11e9-994a-3d186f20de13.png)

**Comment by Marc-marc-marc** [comment]
regen done https://github.com/osm-fr/infrastructure/issues/105

**Comment by yohanboniface** [comment]
Thanks @Marc-marc-marc ! :)
