### ISSUE TITLE
Changing Username in Openstreetmap doesn't reflect on umap

### ISSUE THREAD

**Issue by imagoiq** [umap-project/umap#695]
Hello,

I've changed my username a couple months ago and I see that even after reconnecting to my umap.openstreetmap.fr account, the change isn't reflected in umap.

Thanks in advance

**Comment by Binnette** [comment]
I think we should overwrite the local uMap username each time an user connect with his OSM account.

**Comment by Binnette** [comment]
Fixed by #754
