### ISSUE TITLE
Import of geojson is unstable

### ISSUE THREAD

**Issue by Rpnpif** [umap-project/umap#697]
When I tried to import about 250 simple nodes on a map from a geojson file, all works fine, but I have often an error that said that someone had modified the map and his data will be lost.

My data was well displayed on the map. If I do other editing, all works fine.

But when I disconnect and I reconnect, the imported data are all lost.

Sometimes (rarely from a while), with the same file, all works fine and the data are not lost.

Regards.

**Comment by Rpnpif** [comment]
I think that adding some few nodes to a layer with yet about one hundred of nodes is the cause of this issue.

**Comment by yohanboniface** [comment]
That's a cache issue related to some zealous proxy or something. This should have been worked around in 1.3.0.
