### ISSUE TITLE
Add a process to associate auth provider to an already logged in user

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#7]
Originally reported by: **Yohan Boniface (BitBucket: [yohanboniface](http://bitbucket.org/yohanboniface), GitHub: [yohanboniface](http://github.com/yohanboniface))**

---

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/7

**Comment by AZWCI** [comment]
Always no soluce for non developper and just uMap average user ?

**Comment by yohanboniface** [comment]
Done with #1269
