### ISSUE TITLE
Can't edit my maps

### ISSUE THREAD

**Issue by Xonnext** [umap-project/umap#703]
I don't know where to put my question, so I place it on several places hoping to get an answer:
Can anyone help me with this matter please? I created some maps for the first time but when I want to change them now I cannot edit the data anymore. See https://umap.openstreetmap.fr/nl/map/de-oude-dorpskern-noordwijk_321214 for the map I mean. I had an account before I made these map, but it does not show in My Maps (anymore).

Same question as: can't edit my Umap, but there is no answer.

**Comment by mvanwijnendaele** [comment]
Hello, I have the same issue. Can't access my Umap anymore? Did you find a solution?

**Comment by Binnette** [comment]
Hi @Xonnext, @mvanwijnendaele here is a possible resolution:
https://wiki.openstreetmap.org/wiki/UMap/FAQ#Why_can.27t_I_edit_my_map.3F

Feel free to reopen this ticket if you do not recover your maps
