### ISSUE TITLE
private maps 

### ISSUE THREAD

**Issue by DSIOCCITANIE** [umap-project/umap#704]
Bonjour, 

Je souhaiterais créer une cartographie avec des informations privées de l'entreprise, je ne sais pas comment m'y prendre. J'ai déjà créer une cartographie se nommant "nawale plan de mobilité". Je voudrais juste la mettre en privé. Est-il possible de remédier à ce problème ? 

En vous remerciant par avance. 

Nawale AZAHAF

**Comment by Binnette** [comment]
Hi @DSIOCCITANIE, yes it is possible to make a "private" uMap. Here is how to do so:
https://wiki.openstreetmap.org/wiki/UMap/FAQ#How_to_make_a_.22private.22_uMap.3F
