### ISSUE TITLE
New language available

### ISSUE THREAD

**Issue by kingserbi** [umap-project/umap#706]
I have added and translated uMap to new lenguage: Serbian
Can you please upload it?
Thanks.

**Comment by Binnette** [comment]
Hi @kingserbi, thanks for your work on serbian translation.
![image](https://user-images.githubusercontent.com/6597721/74688008-67876880-51d6-11ea-8dab-13e2f96213cf.png)
There is still some work to accomplish. Can you please try to translate strings a bit more?

2020-02-17 status:
- 51% translated
- 232 strings translated
- 217 strings untranslated

Have a nice day. I hope you will find some time to work on those translation.

**Comment by yohanboniface** [comment]
Serbian is in the available languages.
