### ISSUE TITLE
Crédit "Gravitystorm" (Transport-Outdoors-Landscape) uMap

### ISSUE THREAD

**Issue by AZWCI** [umap-project/umap#709]
Bonjour.

Je signale que les 3 fonds de cartes (nommés dans uMap) "OSM Transport (Thunderforest)", "OSM Outdoors (Thunderforest)" et "OSM Landscape (Thunderforest)" affichent toutes le crédit "Tiles © Gravitystorm" qui renvoit à la page https://www.thunderforest.com/maps/outdoors/

Est-ce (encore) pertinent ? 

La page :
https://www.thunderforest.com/maps/transport/ (de thunderforest/Gravitystorm) (c'est "le même" c'est juste que son "appellation" a changé il y a quelques années si je ne me trompe)
crédite dorénavant "Thunderforest" (avec un T majuscule) et renvoi à https://www.thunderforest.com/ (j'ai regardé tous les fonds de cartes proposés, c'est dorénavant ainsi pour tous. "Gravitystorm" semble avoir dorénavant "disparu"...
(On trouve en fait (sur son site seulement) la mention "Thunderforest is a project by Gravitystorm Limited" avec un lien renvoyant à la page de contact https://www.thunderforest.com/contact/.

En cherchant sur Google, on peut retrouver la trace de "Gravitystorm" ici : https://www.gravitystorm.co.uk/

Sa page de "conditions" sur thunderforest.com mentionne d'ailleurs ici :

https://www.thunderforest.com/terms/

Attribution must be given to both “Thunderforest” and “OpenStreetMap contributors”.
Users of your site/application must have a working links to www.thunderforest.com and www.openstreetmap.org/copyright, for example:

Maps © Thunderforest, Data © OpenStreetMap contributors

For media that doesn’t support links, such as posters, books and other printed media, then you can provide attribution as follows:

Maps © www.thunderforest.com, Data © www.osm.org/copyright

uMap ne devrait-il pas faire une mise à jour du crédit dédié pour ces trois fonds de cartes ou quelque chose m'échappe ?

Merci (pour lui) !

https://www.casimages.com/i/190828041557414006.png.html
[img] https://nsa40.casimages.com/img/2019/08/28//190828041557414006.png [/img]

**Comment by AZWCI** [comment]
Hello (i try my same request in english)

The tiles credit for "OSM Transport (Thunderforest)", "OSM Outdoors (Thunderforest)" et "OSM Landscape (Thunderforest)" are currently credit "Tiles © Gravitystorm" and the hyperlink is : https://www.thunderforest.com/maps/outdoors/

Is that still relevant ?

The page :
https://www.thunderforest.com/maps/transport/ (by thunderforest/Gravitystorm) (it’s "the same guy" he’s just changed his "name" a few years ago if I’m not mistaken)
crédit now "Thunderforest" (with a big T) and send by hyperlink to https://www.thunderforest.com/ (like all of he's other maps tiles. "Gravitystorm" doesn't exist anymore...
On he's website, we just can found "Thunderforest is a project by Gravitystorm Limited" with a hyperlink who send to he's contact page https://www.thunderforest.com/contact/.

On Google search, we can found "Gravitystorm" here : https://www.gravitystorm.co.uk/

Its ("news") "conditions" page in thunderforest.com request :

https://www.thunderforest.com/terms/

Attribution must be given to both “Thunderforest” and “OpenStreetMap contributors”.
Users of your site/application must have a working links to www.thunderforest.com and www.openstreetmap.org/copyright, for example:

Maps © Thunderforest, Data © OpenStreetMap contributors

For media that doesn’t support links, such as posters, books and other printed media, then you can provide attribution as follows:

Maps © www.thunderforest.com, Data © www.osm.org/copyright

So, I think uMap should be update the credits !

Thank you (for him)!

https://www.casimages.com/i/190828041557414006.png.html
[img] https://nsa40.casimages.com/img/2019/08/28//190828041557414006.png [/img]

**Comment by AZWCI** [comment]
Par exemple, Openrunner affiche le bon crédit...

**Comment by cquest** [comment]
Fixed !

**Comment by Binnette** [comment]
Since this is fixed, i close this issue.
