### ISSUE TITLE
Enhancement: Allow clicking on a map feature to add a marker connected to it

### ISSUE THREAD

**Issue by KaiRo-at** [umap-project/umap#710]
This is a very work-intense proposal but it would be really awesome in terms of usability - and make uMap to be more on par with other services.
Google's MyMaps allows you to click on POIs on the underlying map and add a marker for it (IIRC just copying the name and location over). In uMap it would be cool to enable the same and also keep some connection with the OSM object to look up further properties.
I know you usually do not have the POI info in the bitmap tiles, so because of that (and probably other details), this is not really easy - but it would help a ton for making custom maps like for vacation or event planning.

**Comment by Binnette** [comment]
Hi @KaiRo-at, i think this kind of feature will be available only when "vecor" tiles will be implemented and available for apps like uMap and so on.

Please fill a bug maybe to Tile Servers? In order to ask vor vector tiles? Then add a link to your issue here.

Have a nice day.

**Comment by yohanboniface** [comment]
Closing in favour of #968
