### ISSUE TITLE
allow setting the colour of marker symbols

### ISSUE THREAD

**Issue by richlv** [umap-project/umap#711]
Ability to set marker label to any character was added in 563839b9a6d3f67fcabaf048b234c97edad53a88 , but the character always seems to be white.
Would be great to allow setting character colour so that lighter marker colours could be used.

**Comment by richlv** [comment]
The characters seem to be pretty small when displayed on the marker - perhaps they can be bigger compared to the overall marker size?

**Comment by Binnette** [comment]
Hi @richlv, are you talking about this king of label?

![image](https://user-images.githubusercontent.com/6597721/78884670-a231b280-7a5b-11ea-82b3-f985dcbc06b5.png)

**Comment by guaspito** [comment]
I think that @richlv means that chars used as symbols results too small into markers (I had the same problem)

As can be seen in figure, nevertheless single upper-case letters is readable (and single small words can be written as icon symbols), when we try to use more interesting symbols available in unicode charset (I've tried with stars, scissors and other), they are usually too small to obtain good results. The skull on the left is unrecognisable.

![umap_iconsymbol_chart](https://user-images.githubusercontent.com/5469846/101436536-a70e7500-390e-11eb-8770-d1a83ac8df03.png)

When I try to use unicode chars as symbol in marker (stars, skulls and other symbols)

**Comment by richlv** [comment]
Sorry I missed the previous question - the small size for single characters inside of a marker is exactly what I had in mind.

**Comment by yohanboniface** [comment]
This is now handled automatically with a WCAG algorithm to set text white or black in order to get the better contrast. cf #1593
