### ISSUE TITLE
Icon symbols disappeared

### ISSUE THREAD

**Issue by Travel01Alex** [umap-project/umap#714]
the icon symbols that I chose from the list on the side panel disappeared about a couple of weeks ago. Is there a way to make them reappear on the side panel and on my map? Thank you

**Comment by Binnette** [comment]
Hi @Travel01Alex, sorry i do not understand your issue. Can you add some screenshot, a link to your map or be more accurate in your description?

**Comment by Travel01Alex** [comment]
Dear Binnette, 

 

Thanx for getting back to me after the time that has passed. 

 

The error of the non appearing default symbols lasted only a few days and got resolved a day after I had written my post. I thought it might have been linked to it or maybe only coincidence.

 

Thank you and thanks to your team for the great mapping service you offer.

 

Best regards,

Alex

**Comment by Binnette** [comment]
Great, so i can close this issue :+1:
