### ISSUE TITLE
umap.fluv.io disappeared?

### ISSUE THREAD

**Issue by fritz3721** [umap-project/umap#716]
Hello!
I had a collection of  maps on umap.fluv.io, but the site has disappeared for weeks.
Does anybody know what's going on?
Thanks a lot!!

**Comment by Binnette** [comment]
Hi, umap.fluv.io is not an "official" uMap server. If you know the owner, please contact him directly.

See known instances here: https://wiki.openstreetmap.org/wiki/UMap#Instances

Since this is not an uMap issue, please consider closing your issue.

**Comment by Binnette** [comment]
I close your issue.

**Comment by yohanboniface** [comment]
> . If you know the owner,

I know him, and it's me :p
I forgot to renew the domain in time, and it's now wayyyy to expensive.
The umap instance in there was supposed to be a test instance only. I'll try to reactivate it under another domain.

**Comment by Binnette** [comment]
@yohanboniface, great ! I will love to have a "public" sandbox for uMap.

@fritz3721 if you really want your uMap project back, may be you can ask @yohanboniface, to export your project to an ".umap" file.

@fritz3721 please fell free to contact us if you need this ".umap" file

**Comment by yohanboniface** [comment]
Provisional: http://umap.yohanboniface.me/

**Comment by Binnette** [comment]
@yohanboniface: Will @fritz3721 be able to recover his maps on this server?

@fritz3721: Feel free to reopen it, if you can not recover your map by connecting on @yohanboniface URL. Also i encourage you to "clone" all your maps from this URL to an "official" uMap server. Instructions about cloning [here](https://wiki.openstreetmap.org/wiki/UMap/FAQ#How_to_clone_an_uMap_project.3F).

**Comment by fritz3721** [comment]
thank you all so much!!
