### ISSUE TITLE
When I search a street, it doesn't indicate it

### ISSUE THREAD

**Issue by NicoBdxLaLibre** [umap-project/umap#717]
Hey !
I create a Openstreetmap with Umap, and I have a problem with the search control.
When I'm searching a street, it finds it and I zoom to it. But there is no "location point" or "marker" on the street I was looking for. So, in a city like Brussels, it's quite complicated to know exactly which street I was looking for because there is no point on it...
Do you know how to add a marker on a the street I was looking for ?

Thank you !

Nicolas

**Comment by Binnette** [comment]
Hi, I don't think this is possible with uMap for now. Will label your issue with "feature request" then.

**Comment by yohanboniface** [comment]
Duplicate of #419
