### ISSUE TITLE
Can't edit my umap 

### ISSUE THREAD

**Issue by Marine25** [umap-project/umap#718]
Hi ! 

So I created two umap in august, and now I can't edit them anymore... Is there a way to re-install the editing feature ? 

Here are the links: 
http://umap.openstreetmap.fr/fr/map/securite-noso_363761#8/5.791/10.195
http://umap.openstreetmap.fr/fr/map/security-noso_363510#8/5.616/10.195

Thanks for your help !

**Comment by Marc-marc-marc** [comment]
to which osm account should they be connected?

**Comment by Marine25** [comment]
> to which osm account should they be connected?

I do have an osm account but I created those maps before creating my account...

**Comment by Marc-marc-marc** [comment]
if wou want I connect those maps to our osm account, tell me witch osm account :)
I you want to keep an anonymous map, I need a contact (for exemple send an email to umapmailing)

**Comment by Marine25** [comment]
Sorry for my late response; I think I want to keep the map anonymous. You can use the email : marineguillou25@gmail.com

**Comment by Walkovsky** [comment]
Hello!

I've got the same problem. I created map without my OSM account. Now I can't edit my map, so I'd like to connect it. 

link to map:
https://umap.openstreetmap.fr/pl/map/koninska-mapa-rowerowa-komar_386955#15/52.2292/18.2425

my email address:
fil.walkowiak@gmail.com


Thanks for help!

**Comment by adatkabel** [comment]
Hi!

I have the same issue. I signed in with my Openstreetmap account, but it shows I don't have any map. That's not true, I did that map: https://umap.openstreetmap.fr/hu/map/magyarorszag-legjobb-bringas-helyei-by-flowcycle_383964#8/47.324/19.336

My e-mail address: janos@flowcycle.hu or valvetronic1@gmail.com

Thanks for your help in advance!

**Comment by funique** [comment]
@Marc-marc-marc Me too. Thank you for helping me get edit access back
http://umap.openstreetmap.fr/fr/map/francophonie-au-canada_361531
mgt@funique.ca

**Comment by Binnette** [comment]
Hi, if your issue is solved, can you please consider closing it?

FYI, I created an FAQ with a possible solution for this kind of issues here:
https://wiki.openstreetmap.org/wiki/UMap/FAQ

**Comment by Binnette** [comment]
I close this issue, feel free to re-open it if needed

**Comment by adatkabel** [comment]
> Hi, if your issue is solved, can you please consider closing it?
> 
> FYI, I created an FAQ with a possible solution for this kind of issues here:
> https://wiki.openstreetmap.org/wiki/UMap/FAQ

Hi!

Thanks for your help, but on my map, there isn't any sharing button, so I cannot use the clone method. Do you have any clu, how to enable it?

Thanks:
J

**Comment by domdak** [comment]
Hi, I've got this issue with this map, the edit icon I've previously used has just vanished: https://umap.openstreetmap.fr/en/map/syo-mapruns_468145. Could it possibly be linked to my account, dominic(dot)dakin(at)gmail(dot)com
Thanks very much!

**Comment by OdiloPinder** [comment]
@Marc-marc-marc Sorry to bother you, but I do have the same issue. Would you mind to connect my so far anonymous map on https://umap.openstreetmap.fr/de/map/grundherrschaft-mariazell_582119#17/48.01653/15.99746 to my Account on t.aigner@mariazell-wienerwald.at

Thank you so much and all the best,
Thomas

**Comment by Marc-marc-marc** [comment]
link send by email

**Comment by OdiloPinder** [comment]
Thank you so much!

Von: Marc-marc-marc ***@***.***>
Gesendet: Sonntag, 16. Mai 2021 11:00
An: umap-project/umap ***@***.***>
Cc: Thomas Aigner ***@***.***>; Comment ***@***.***>
Betreff: Re: [umap-project/umap] Can't edit my umap (#718)


link send by email

**Comment by Basta911** [comment]
Hi there - unfortunately I also have the issue that I created the map w/o any account @Marc-marc-marc 
Would you be so kind and link the map https://umap.openstreetmap.fr/de/map/jga-timo-krieg_626123
with my mailadress / OSM account tocoolforhell@web.de??
Thanks a lot in advance and have a good start into the new week!

**Comment by Marc-marc-marc** [comment]
@Basta911 link send by email

**Comment by jaewoo5830** [comment]
@Marc-marc-marc Unfortunately, I do have the same issue. I created the map without using my OSM account. Would you be able to link the map to my OSM account?
Link: https://umap.openstreetmap.fr/en/map/roadeye_589949#15
OSM account/ email address: kjae@umich.edu
Thank you so much!

**Comment by Marc-marc-marc** [comment]
@jaewoo5830 link send by email

**Comment by fseyd** [comment]
I've got the same problem and would need to modify urgently my map since pupils will rely on it by beginning of next week (and already have the link) Thanks a lot in advance for help!
http://umap.openstreetmap.fr/de/map/lokale-ausbildungsmeile-wandsbek_664266#13/53.6162/10.1381

email: seyd@bwh-sh.de

**Comment by Marc-marc-marc** [comment]
@fseyd link send by email

**Comment by fseyd** [comment]
Great! Thanks so much!

**Comment by MBrou-sketch** [comment]
Hi guys, sorry I have the same problem as the people above...
Here the map I was working on:
[http://umap.openstreetmap.fr/fr/map/epd_703663#6/46.551/0.461]
And here is the email address I'd like it to be linked to:
maximbrouss@hotmail.fr

Is it possible to know why I can't edit the map anymore, even by using an ld link that used to work?

Thanks so much for the help

**Comment by MBrou-sketch** [comment]
Just in case someone stubles upon this : I guess my link doesn't work anymore because I deleted the cookies in-between two uses.

**Comment by autresrhumbs** [comment]
Hello,

I have the same problem!
Is it possible to get this one attached to my account?

umap.openstreetmap.fr/fr/map/antikeo_769294

Many thanks!

Bruno

email: brunomorazzoni@hotmail.com

**Comment by jlmxyz** [comment]
ok, I've the same issue.... I forgot to login to OSM before creating the map, and seems that the cookies got corrupted...
https://umap.openstreetmap.fr/en/map/greek_882501#12/37.4845/21.9438
dev.3xm0f@8alias.com

**Comment by jlmxyz** [comment]
for people having the same issue, one way is to export the data of the map (database icon on the left) then recreate a map using your account, import the data (import icon on the right) 
best regards

**Comment by przem0022** [comment]
Edit issue
https://umap.openstreetmap.fr/pl/map/testnet_889496
Please email link przem00@outlook.com

**Comment by Marc-marc-marc** [comment]
as the ticket is closed, it's not easy so catch pending issue
please open a new ticket per issue

**Comment by guilleguez** [comment]
Hello!

I've got the same problem. I created map without my OSM account. Now I can't edit my map, so I'd like to connect it.

link to map:
http://umap.openstreetmap.fr/es/map/caballito_941030#15/-34.6110/-58.4340

my email address:
guilleguez@hotmail.com

Thanks for help!

**Comment by Marc-marc-marc** [comment]
@guilleguez https://github.com/umap-project/umap/issues/718#issuecomment-1538841019
