### ISSUE TITLE
Bug :  after enter a wrong coordinate format " 35.6867,51.4176 "  the map background is gone

### ISSUE THREAD

**Issue by joe-pirat** [umap-project/umap#719]
Bug :  after enter a wrong coordinate format " 35.6867,51.4176 "  the map background is gone
If I check with a nother browser, the background map of https://umap.openstreetmap.fr/en/map/joes-map_372758#11/35.6867/51.4176  is there. 
But in my main Browser the map stays blank. 
Shod I tray to delete all the last edits ? 
![Screenshot from 2019-10-22 09-54-04](https://user-images.githubusercontent.com/37078939/67267102-ef23cb80-f4b1-11e9-9878-b8ec8b61b22e.png)

**Comment by Binnette** [comment]
Hi @joe-pirat, sorry i do not understand your issue. Where did you try to enter those cordinate in wrong format? In the url bar?

Please give us a detailed scenario to help us reproduce your bug.

**Comment by joe-pirat** [comment]
I have entert in one ( ! )  celll :   " 35.6867,51.4176 " 
the result of the wrong entry was that my map is broken 
If I open  https://umap.openstreetmap.fr/en/map/joes-map_372758#11/35.6867/51.4176  in Chrome browser I dont the the map any more.
more cleare ?

**Comment by Binnette** [comment]
Hi @joe-pirat, sorry I can not reproduce your issue.

When i open https://umap.openstreetmap.fr/en/map/joes-map_372758#11/35.6867/51.4176 in Chrome or Firefox, everything is fine:
![image](https://user-images.githubusercontent.com/6597721/74756216-82101f00-5274-11ea-8099-50ba67de1d96.png)

Can you help me reproduce it please? Maybe there is something wrong with your web browser? Try on a different computer. Or consider cleaning your web brower, or restart it without extensions/plugins. Also, in Chrome, you can press F12 on your keyboard, then open your map and see if some errors are displayed.

Have a nice day.

**Comment by yohanboniface** [comment]
cf #1168
