### ISSUE TITLE
Importing geojson from link doesn't render geojson

### ISSUE THREAD

**Issue by brunetton** [umap-project/umap#720]
Hi,

I wanted to import this geojson onto a map: https://gitlab.com/brunetton/forets-publiques/raw/master/forets-publiques-autour-maubeuge.json

But the map doesn't display my data. Here's the link to the map: http://umap.openstreetmap.fr/en/map/untitled-map_379707#13/50.2078/4.1415
(I changed the color of geojson rendering to a super visible color to be sure not to miss it on the map)

What did I miss ? Maybe this geojson file have too much points ? 

Thanks !

**Comment by vinber** [comment]
it's working : http://umap.openstreetmap.fr/fr/map/carte-sans-nom_380165#10/50.1505/4.1212

see parameters :

![Capture d’écran de 2019-10-24 09-34-55](https://user-images.githubusercontent.com/890869/67463378-9d11b000-f641-11e9-97c9-0c9a84e942b3.png)

**Comment by brunetton** [comment]
Thanks. 
For future reference: I had to enable `proxy` option.
