### ISSUE TITLE
Insert a medium (sound, video) in the description

### ISSUE THREAD

**Issue by FrViPofm** [umap-project/umap#721]
There is a way to insert pictures in descriptions of an object.
I created a [map](https://umap.openstreetmap.fr/fr/map/pouce-vert_361854) showing interviews of people and their place. I can put a photo but I can't insert a audio reader for [that](https://cloud.imagine-asso.fr/index.php/s/DKzd9anpEfw7RLH) or [that](http://www.imagine-asso.fr/wp-content/uploads/2019/10/20191016-Claire-TdV-final.mp3)
Is it a way to add a reader, even very small, in the description with the video or audio element from html5 ?

**Comment by FrViPofm** [comment]
Sorry for the disturbance. I've found the "{{{iframe}}}" syntax.

**Comment by Binnette** [comment]
Great, I will add it to the Tips section here: https://wiki.openstreetmap.org/wiki/UMap/Tips

**Comment by hueldoeu** [comment]
> Sorry for the disturbance. I've found the "{{{iframe}}}" syntax.

thx. i was trying to find how to insert a video in umap. so 3 (curly) braces for a video/audio according to everything a modern browser with support for HTML5 can offer and 2 braces for pictures.
