### ISSUE TITLE
IGN aerial and OSM forte Fr are no longer displayed

### ISSUE THREAD

**Issue by Bruitdufrigo** [umap-project/umap#722]
Hello
I'm using these two maps (IGN aerial + OSM forte Fr) but they dont display anymore on my umap. Is there a problem ? 
Thank you !

**Comment by Sebourg** [comment]
Similar issue today, can't use IGN Aerial map. 
Getting HTTP 403 error when loading the tiles.

HTTP response for every tile request :

```
<ExceptionReport>
	<Exception exceptionCode="MissingParameter">Key does not exist or has expired</Exception>
</ExceptionReport>
```

Looks like an expired api key.

**Comment by deuzeffe** [comment]
Mmmhh. Collateral damage from the recent update of IGN services hosting, I guess.

**Comment by Bruitdufrigo** [comment]
any solution to fix it ??

Yvan Detraz, architecte, directeur
contact@bruitdufrigo.com
06 64 39 68 15
bruitdufrigo.com <http://www.bruitdufrigo.com/>
randonnéespériurbaines.fr <https://xn--randonnespriurbaines-h2bd.fr/>
facebook <https://www.facebook.com/Bruitdufrigo/>
instagram <https://www.instagram.com/bruitdufrigo_/>

**Comment by deuzeffe** [comment]
Fixed. Thx to @cquest

**Comment by Sebourg** [comment]
It works. Thanks.

**Comment by Bruitdufrigo** [comment]
great !

Yvan Detraz, architecte, directeur
contact@bruitdufrigo.com
06 64 39 68 15
bruitdufrigo.com <http://www.bruitdufrigo.com/>
randonnéespériurbaines.fr <https://xn--randonnespriurbaines-h2bd.fr/>
facebook <https://www.facebook.com/Bruitdufrigo/>
instagram <https://www.instagram.com/bruitdufrigo_/>

**Comment by deuzeffe** [comment]
@Bruitdufrigo Can you close the issue, please?
