### ISSUE TITLE
can't edit OSM map

### ISSUE THREAD

**Issue by LeaDenieul** [umap-project/umap#725]
HI I made a ma on OSM that I can't seem to edit anymore although I'm the only contributor. 
Could you explain to  me how to edit it ? here is the url http://u.osmfr.org/m/382789/

thanks!

**Comment by Binnette** [comment]
Hi @LeaDenieul. This is not an uMap issue. This map is not linked to any uMap account. You probably created this map without connecting to uMap first. So this map is linked to your web browser's cookies.

You have 2 way for solving this issue:
-  Use the exact same browser on the same computer used when you created this map (note that if you clear your web browser history/cookies, the "edit link" for this map is lost)
- Export data from your old map then create a copy by importing data, here is how to do so:

Clone a uMap:
1. Open a uMap
2. On the left, click on the "share" buton
3. On the right in "Download data", select "Full map data"
4. Click on Download data. You will obtain an "your_data.umap" file
5. Connect to uMap with your account
6. Create a new map
7. Import the "your_data.umap"
8. Done

Please, consider closing this issue if problem is solved.

**Comment by Binnette** [comment]
FYI: I created an FAQ containing a solution for this issue here:

https://wiki.openstreetmap.org/wiki/UMap/FAQ

**Comment by Binnette** [comment]
I close this "issue", fell free to reopen it, if you can not clone/recover your uMap project.
