### ISSUE TITLE
Unable to add some editors

### ISSUE THREAD

**Issue by F1oron** [umap-project/umap#726]
On https://umap.openstreetmap.fr, the autocomplete search to add new editor doesn't find the user account "Tbennegen".
Does Umap have conditions to add editors on a map?

**Comment by Binnette** [comment]
Hi @F1oron, user Tbennegen have to log in to https://umap.openstreetmap.fr with his OSM account first in order to be displayed in the "Map's editor" autocomplete field.

Since this is not an uMap issue. Please consider closing this bug.

**Comment by F1oron** [comment]
Thank you, it works after following your instructions.
