### ISSUE TITLE
No thumbnail when share map

### ISSUE THREAD

**Issue by redb** [umap-project/umap#727]
Hi all
I don't know if its really an issue, but there is no thumbnail when we share a map on Twitter or Facebook. It could be a very good idea. Many thanks for your job

**Comment by Binnette** [comment]
Hi, I think this is not an uMap issue. I think this is a Twitter/Facebook issue. They are not configured to make a preview for uMap website. Please consider, submitting the issue to them.

**Comment by yohanboniface** [comment]
I guess we are missing OpenGraph tags ?

**Comment by Binnette** [comment]
@yohanboniface, i never heard about this "Open Graph Protocol". It is exactly what we need to fix this issue.

**Comment by yohanboniface** [comment]
Closing in favor of #162
