### ISSUE TITLE
Issue with uMap import file

### ISSUE THREAD

**Issue by u247712** [umap-project/umap#729]
Hello all,

I'd like to create an interactive map with openstreetmap and share it with my colleagues: uMap seems to be the most simple way to succeed. Unfortunately, I spent last week 2 hours to add markers and attached information when a red banner said that I loose anything, or something like this.
So, I downloaded in a umap file all remaining information, opened and edited it with a txt tools from Windows. I'm able now to upload and save this file in a new map but, and it is my issue, when I want to modify/share it, there is only 1 marker per layer displayed: all others are erased!!!
Have you ever seen this issue? Do you know how to overcome it?
Please, help me !

**Comment by Binnette** [comment]
Hi @u247712, are all your data  inside your uMap file?
Can you add a link to your uMap project?
