### ISSUE TITLE
No IGN orthoPhoto available 

### ISSUE THREAD

**Issue by Lecaethomas** [umap-project/umap#731]
Hi,
I'm trying to use othophotos on my project but it seems that there's no longer access to imagery emitted from IGN (whereas it works fine on géoportail). 
Do you think that you know how to solve it ?

**Comment by deuzeffe** [comment]
Cf https://github.com/umap-project/umap/issues/722#issuecomment-563474202

**Comment by Lecaethomas** [comment]
I see, thanks !

**Comment by deuzeffe** [comment]
@Lecaethomas see https://github.com/umap-project/umap/issues/722#issuecomment-565739172

**Comment by deuzeffe** [comment]
@Lecaethomas Can you close the issue, please?
(red button at the bottom of the page)
