### ISSUE TITLE
AMP compatibility 

### ISSUE THREAD

**Issue by Luen** [umap-project/umap#732]
I've been embedding umaps into my ghost blog posts but Google Search Console is telling me that it has issues with "Linked AMP version is invalid. It won't appear in Google Search results." because "AMP HTML Tag has an invalid layout specified by its attributes."

This happen with all of the pages with embedded maps. 

Here's the code it tells me it has issues with:
`<amp-iframe allowfullscreen frameborder=0 height=450px layout=responsive sandbox="allow-scripts allow-same-origin" src="https://umap.openstreetmap.fr/en/map/smith-creek-falls-track_397929?scaleControl=false&amp;miniMap=false&amp;scrollWheelZoom=true&amp;zoomControl=true&amp;allowEdit=false&amp;moreControl=false&amp;searchControl=false&amp;tilelayersControl=false&amp;embedControl=false&amp;datalayersControl=false&amp;onLoadPanel=undefined&amp;captionBar=false&amp;editinosmControl=false" width=100%></amp-iframe>`

How do I fix this?

**Comment by Binnette** [comment]
Hi @Luen, do you have more info about the error? Can you add a link here to your blog post?

**Comment by Luen** [comment]
![image](https://user-images.githubusercontent.com/1161837/74614088-a11d8c80-5160-11ea-9be5-acc920fc5030.png)

Here's a link to one of the articles with umap which Google Search Console has an issue with. 
https://wanderstories.space/mt-tyson/amp

If I embed Google My Maps, the code is as follows and Google Search Console has no issues with it
`<iframe src="https://www.google.com/maps/d/u/0/embed?mid=1KyyF77sDgRirDwXyToy9DI2AImo" width="640" height="480"></iframe>`

**Comment by Luen** [comment]
Using the amp validator, it said that it had a problem with the width="100%"
I just changed it to width="640" and it works. Thanks

https://validator.ampproject.org/
