### ISSUE TITLE
Unable to edit the map

### ISSUE THREAD

**Issue by Blade71** [umap-project/umap#733]
I created a map by loading a GeoJeson with 1700 entries, now the map is no longer editable, I can't delete it and it freezes everything, even when I scroll through the list of created maps, what can I do? how can I delete the created map or remove the data entered via file? thank you so much I have been stuck for days.

here the map
https://umap.openstreetmap.fr/it/map/pedoni-morti-2018_401524#12/41.9951/12.7709

**Comment by Binnette** [comment]
Since I'm not an uMap admin, i can not fix your map myself. If you really want to recover your map, here is what you can do.

Example with Firefox:
1. Open your map
2. Show dev tools by pressing F12
3. Go to network tab
4. Right click on each queries starting with "/it/datalayer"
5. Click on block query for each
6. Reload the whole page
7. It will prevent data to be loaded
8. So you will be able to edit your map, to solve your problem either: delete your data, or set your layer to be "clustered"

![image](https://user-images.githubusercontent.com/6597721/74603001-df5a7380-50ae-11ea-9fd2-c09d98beeb3f.png)

**Comment by Binnette** [comment]
#bug: we should suggest users to use clustered markers when POI number is greater than 200 or 500? (we will need to define a limit).

**Comment by Binnette** [comment]
Related to #618 and #557

**Comment by Blade71** [comment]
thanks, even if this procedure fails, because I can't even get to the dev tools, the map is blocked immediately .... surely a limit is necessary!

**Comment by Binnette** [comment]
I agree. In Firefox open a new tab, press F12 to open devtools, and then change tab url.

**Comment by Blade71** [comment]
Thanks I did it ....

**Comment by Binnette** [comment]
Hi @jocelynj, can you please send me by mail the "admin url" for the following public uMap please?
https://umap.openstreetmap.fr/it/map/pedoni-morti-2018_401524#12/41.9951/12.7709

I will try to fix it by applying cluster to all data layers.

**Comment by jocelynj** [comment]
I cannot find the admin url for the above map. But I could add your login as a "creator" to make to possible to modify the map yourseulf.

**Comment by jocelynj** [comment]
@Binnette: do you have an account on umap? If so, what is its name?

**Comment by Binnette** [comment]
My username is "Binnette". See: https://umap.openstreetmap.fr/fr/user/Binnette/

**Comment by jocelynj** [comment]
@Binnette and @Blade71 can now both modify the map.

**Comment by Binnette** [comment]
@Blade71, it seems that you uploaded the same geojson file multiple time:
![image](https://user-images.githubusercontent.com/6597721/74883117-8faacf00-5370-11ea-8348-513233f1383e.png)

I will remove clones.

**Comment by Binnette** [comment]
A lots of your data seems buggy. It seems your geojson is corrupted. There are a lot of data in the sea/ocean:
![image](https://user-images.githubusercontent.com/6597721/74884686-085f5a80-5374-11ea-93f5-4dee6a4a6105.png)

**Comment by Binnette** [comment]
Done :+1: 
Everything is working fine now. There were three king of dataset:

- one dataset of 37 KB
- one dataset of 1 MB
- one dataset of 21 MB

I was obliged to remove the 21MB dataset. uMap can handle it, but web browsers hardly can manage it...

Here are all your dataset: [pedoni.zip](https://github.com/umap-project/umap/files/4228112/pedoni.zip)

I'm closing this issue. Feel free to reopen it if needed.
