### ISSUE TITLE
Try to read property _zoom of undefined object

### ISSUE THREAD

**Issue by sjarrossay** [umap-project/umap#734]
On Google Chrome
Version 79.0.3945.88 (Build officiel) (64 bits)

When we use layer cluster property and you embed the map, we got an error in script
TypeError: Cannot read property '_zoom' of undefined
As result we just have a marker on map when you expected cluster marker
Result :
<img width="195" alt="Capture d’écran 2019-12-26 à 19 17 45" src="https://user-images.githubusercontent.com/43173739/71487438-9824d480-281b-11ea-8114-762263df5435.png">

Expected :
<img width="301" alt="Capture d’écran 2019-12-26 à 19 19 48" src="https://user-images.githubusercontent.com/43173739/71487451-a246d300-281b-11ea-820c-ea6e5ecde75f.png">

It's appear in a method `addLayer` :
<img width="1207" alt="Capture d’écran 2019-12-26 à 19 10 30" src="https://user-images.githubusercontent.com/43173739/71487470-bab6ed80-281b-11ea-8f1b-685898fb0adb.png">

![image](https://user-images.githubusercontent.com/43173739/71488227-bc82b000-281f-11ea-8f5d-e97b6e12c81e.png)

**Comment by Binnette** [comment]
Hi @sjarrossay, can you please, share a link to your map here indor to help me reproduce the bug?
