### ISSUE TITLE
How to stop google indexing the Umap website and user pages with the maps=

### ISSUE THREAD

**Issue by JamesN89** [umap-project/umap#735]
Is there a possibility to add "noindex" to the umap homepage and the user pages with created maps?

**Comment by Binnette** [comment]
I can't tell if we should or should not avoid robot index for uMap projects.

**Comment by yohanboniface** [comment]
When a map sharing status is set as "anyone with link" then it's not referenced in the home or user's pages

**Comment by Binnette** [comment]
@yohanboniface, it seems fine to me let robots index "public" uMap. Do you know, if we need to add some code to force deny indexing for "private" project?

@JamesN89, is your uMap project private or public?

**Comment by yohanboniface** [comment]
Only public maps are indexable, when status is "private" or "anyone witih link" maps do have `<meta name="robots" content="noindex">`.
