### ISSUE TITLE
error al cargar la página demo umap.fluv.io

### ISSUE THREAD

**Issue by pepeysusmapas** [umap-project/umap#740]
Al pulsar sobre el enlace sale te lleva a una de esas páginas de publicidad engañosa y span

**Comment by Binnette** [comment]
Please use english. Can you please provide a screenshot of your web browser when you encounter this ad page? Can you please tell us how to reproduce this? (for example: 1. go to umap.openstreetmap.de 2. click on button create 3. and so on)

I don't think this is a uMap issue. You may have a malware on your web browser that open ad pages?

**Comment by Binnette** [comment]
Feel free to reopen this ticket if needed.
