### ISSUE TITLE
[nice top have] Calculations in placeholders

### ISSUE THREAD

**Issue by cascafico** [umap-project/umap#742]
I'd like to link in pop-ups a command to run JOSM (via JOSM remote control), for instance:
http://127.0.0.1:8111/load_and_zoom?left=8.19&right=8.20&top=48.605&bottom=48.590
As you can see, it needs 4 coordinates, but with umap I can fetch just two.

Is there a chance to do simple calculations inside umap to build such coordinates? 
Ie: {lat}+0.003

**Comment by Binnette** [comment]
Hi @cascafico, what you want is not supported yet.

If your popups are binded on OSM objects, here is a workaround (I tested it right now, it is working fine). Add the following code in the content of your popups.
`[[http://127.0.0.1:8111/load_object?new_layer=true&objects={id}|Edit in JOSM]]`

It will add in your popup a link "Edit in JOSM" that will load the OSM object in JOSM.
![image](https://user-images.githubusercontent.com/6597721/74596824-c45b1580-5054-11ea-81c2-8eeecc81e373.png)


More details about JOSM load_object commande [here](https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#load_object).

**Comment by yohanboniface** [comment]
Have you tried with `east`/`west`/`north`/`south` ?

**Comment by cascafico** [comment]
> Hi @cascafico, what you want is not supported yet.
> If your popups are binded on OSM objects, here is a workaround (I tested it right now, it is working fine). Add the following code in the content of your popups.
> `[[http://127.0.0.1:8111/load_object?new_layer=true&objects={id}|Edit in JOSM]]`

Thanls, I was aware of it. In my case I don't have an object ID, because I want umap to download  OSM data in a small bbox to build a new object.
I think I will build a bbox in input table.

**Comment by Binnette** [comment]
@cascafico do you know that you can add an "edit button" in the left panel?
![image](https://user-images.githubusercontent.com/6597721/74765281-8c85e500-5283-11ea-9f96-5139b9ce91fd.png)
See https://wiki.openstreetmap.org/wiki/UMap/Guide/Edit_map_properties

**Comment by Binnette** [comment]
Success! @cascafico, add the following code in your popup:
`**Edit:** [[http://127.0.0.1:8111/load_and_zoom?left={west}&right={east}&top={north}&bottom={south}&select={id}|JOSM]]`
Is that what you want? If yes, please close this ticket then :+1: 

I just wrote a "tips" here: https://wiki.openstreetmap.org/wiki/UMap/Tips#Add_a_link_.22Edit_in_JOSM.22_in_a_popup

**Comment by cascafico** [comment]
Thanks Yohan and Binnette: cardinal points solution is perfect!
Here is my [landfill umap](http://umap.openstreetmap.fr/en/map/discariche_419682)

**Comment by Binnette** [comment]
@cascafico I looked to your uMap, it seems that you want to recreate your own "MapRoulette" with uMap. Do you know [MapRoulette](https://maproulette.org/)? Please have a look to MapRoulette, i think it may suit you best.

**Comment by cascafico** [comment]
> @cascafico I looked to your uMap, it seems that you want to recreate your own "MapRoulette" with uMap. Do you know [MapRoulette](https://maproulette.org/)? Please have a look to MapRoulette, i think it may suit you best.

I took a look at Maproulette some time ago, but (as far as I understand), I cannot load other data layers. My goal was to display a map with OSM data and external dataset(s), in order to start a visual conflation.

**Comment by yohanboniface** [comment]
Maybe https://www.mapcontrib.xyz/ ?

**Comment by Binnette** [comment]
> My goal was to display a map with OSM data and external dataset(s), in order to start a visual conflation

This is exactly what i do for public bookcase in my map: 
https://umap.openstreetmap.fr/en/map/osm-bookcases-and-boite-a-lire_394538#15/45.1737/5.7436
(In my case, external data are not from a "trustred" source, so users need to check IRL before adding bookcase in OSM).

Also, the best way to do "conflation" is to use JOSM with conflation plugin: https://wiki.openstreetmap.org/wiki/JOSM/Plugins/Conflation

Please consider looking to other solutions here: https://wiki.openstreetmap.org/wiki/Conflation
