### ISSUE TITLE
Umap does not load maps

### ISSUE THREAD

**Issue by mayschje** [umap-project/umap#743]
Since two days umap does not load maps anymore when using the search function. When entering the map url everything seems fine, but when I try to add a new location to my map by using the search function the whole map changes to the grey background without loading the images. This appears on several browsers on a linux system as also on a android system.

![blank_screen](https://user-images.githubusercontent.com/32663815/74592507-6281b800-5022-11ea-9849-099d27c56b0a.png)

https://umap.openstreetmap.de/de/map/februar-2020_2323 (works fine)
https://umap.openstreetmap.de/de/map/februar-2020_2323#16/47.7811/9.6125 (freezing)

**Comment by Binnette** [comment]
Hi @mayschje, i think this it is not an uMap issue. You are using "Wikimedia OSM-International" as background. And they may have some issues right now:

Screenshot of queries made when i open your uMap in my web brower:
![image](https://user-images.githubusercontent.com/6597721/74596176-f3b95480-504b-11ea-9e9a-6f36484b7015.png)

![image](https://user-images.githubusercontent.com/6597721/74596235-abe6fd00-504c-11ea-821e-7a4e7e72703f.png)

Error given by Wikimedia is: "Error: 429, Too Many Request".

Can you please consider "report this error to the Wikimedia System Adminstrators" instead ? (as asked in the screenshot).

For now, to solve this error in your uMap, please consider using an other background.

Have a nice day.

**Comment by mayschje** [comment]
Hi Binnette, ah ok, thank you very much.

I'll do that.

**Comment by Binnette** [comment]
Since this is not an uMap issue, i am closing it. Feel free to reopen it if needed.
