### ISSUE TITLE
Make uMap RTL compliant (right-to-left writing)

### ISSUE THREAD

**Issue by Binnette** [umap-project/umap#752]
Make uMap capable to display languagues wroten from [right-to-left](https://en.wikipedia.org/wiki/Right-to-left).

This wiil need a lot of work.

**Comment by yohanboniface** [comment]
Added dir="rtl" when appropriate. More work is needed to adapt the CSS:

![Screenshot_2020-03-23 uMap](https://user-images.githubusercontent.com/146023/77307659-f3227680-6cf9-11ea-87e2-267584d80d54.jpg)
![Screenshot_2020-03-23 Haute randonnée pyrénéenne - uMap](https://user-images.githubusercontent.com/146023/77307672-f9185780-6cf9-11ea-8589-4be5897148a7.jpg)

**Comment by yarons** [comment]
Yup, mostly in terms of icon alignment.

There's this CSS method to add `[dir=rtl]` to directives and this way we can tackle only the RTL issues.

**Comment by yohanboniface** [comment]
Done in #2078
