### ISSUE TITLE
Conventions for keyboard shortcuts

### ISSUE THREAD

**Issue by sveinki** [umap-project/umap#753]
Hi, recently started to translate uMap, found some occurrences in umap_frontend where keyboard shortcuts are presented as (shift-click), (Alt-click), and (Ctrl-click). First of all; in most FOSS-projects I'm aware of, convention dictates that modifiers should always be capitalized: Shift, Alt, Ctrl, etc. But also that a combination of keys should take a plus sign for a simultaneous sequence; e.g. Shift+click, Alt+click, and Ctrl+click.
Ctrl+Alt+Del looks familiar, right?
Sorry for the nitpicking, but I think this kind of inconsistency may affect the "UX-experience" for some people ;-)

**Comment by Binnette** [comment]
Hi @sveinki,

You are totally rigth! Thank you for creating this ticket. When my PR #744 will be merged. I will "mass edit" our translations file to fix this issues. I will also merge my mass changes to Transifex to stay synchronized.

**Comment by Binnette** [comment]
Issue fixed by #778
