### ISSUE TITLE
How to batch upload .gpx (or .geojson) data ?

### ISSUE THREAD

**Issue by galuel** [umap-project/umap#757]
I can't find a way to develop a program that could be able to generate directly his map. I only found information about using the "import" data manual button on umap.

I'd like to run a server that update a map with frequent changes (geolocalisation of events), that could send a .gpx or .geojson file without any manual interaction.

Any information about that feature would help me a lot, thanks for reading.

**Comment by yohanboniface** [comment]
Instead of pushing, you should be putting the data online somewhere uMap can pull it, using remote data

**Comment by galuel** [comment]
Thanks for your answer. Where do I find documentation / example of how using "remote data" ?

**Comment by yohanboniface** [comment]
http://www.mappa-mercia.org/2014/09/creating-an-always-up-to-date-map.html should help

**Comment by galuel** [comment]
I don't understand how it works... I cannot use that "overpass api", since I have my own data, that are not online anywhere on any map or website. I created a GEOJSON file (with help of overpass website for the format) with the information in it (same format that overpass api), and I put it in my own website : https://diagonaletv.com/map/chess.geojson

But then if I use the "import data from URL" with that URL, use "geojson" format, then after clicking on "importer les données" nothing happens...

**Comment by yohanboniface** [comment]
Skip the overpass part, and concentrate on the "Remote data" one, but using your own remote URL

**Comment by Binnette** [comment]
Hi @galuel, here is the way to do so:

(click on following image to zoom)
![remotedata256](https://user-images.githubusercontent.com/6597721/75715317-7fc6af80-5ccd-11ea-8772-93cbcf429ced.gif)

**Comment by galuel** [comment]
Thank you @Binnette I was able to reproduce it, it is exactly what I needed, great explanation ! :) Problem solved :)
