### ISSUE TITLE
popup shape: popup

### ISSUE THREAD

**Issue by maro-21** [umap-project/umap#759]
In `Settings` -> `Default interaction options` there is a setting "Popup shape" which has options to choose:
- "popup"
- "popup (large)"
- "side panel"
It doesn't make sense, these are not the names of shapes, it should be rewritten.

**Comment by Binnette** [comment]
Hi @maro-21, what do you suggest for thoses strings? Thanks for you help

**Comment by maro-21** [comment]
Unfortunately I don't have any suggestions. And I don't know what this setting is used for.
