### ISSUE TITLE
GeoJSON unkown geometry types on Import

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#76]
Originally reported by: **BitBucket: [borgo](http://bitbucket.org/borgo), GitHub: [borgo](http://github.com/borgo)**

----------------------------------------

I wasn't able to import more complex Geometry Objects such as MultiPoint, MultiLineString, MultiPolygon and GeometryCollection to uMap.

Trying to paste this [json](http://geojson.org/geojson-spec.html#id7):

```
#!json

{ "type": "MultiPolygon",
    "coordinates": [
      [[[102.0, 2.0], [103.0, 2.0], [103.0, 3.0], [102.0, 3.0], [102.0, 2.0]]],
      [[[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]],
       [[100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2]]]
      ]
}
```

I get "Skipping unkown geometry.type: MultiPolygon" error.

What would be a suggested way, to import polygon such as this http://nominatim.openstreetmap.org/details.php?place_id=98238624 to uMap?

----------------------------------------
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/76

**Comment by yohanboniface** [comment]
Multi are now supported.

**Comment by druxstr** [comment]
I'm still getting "Skipping geometry unknown" for MultiPoint on http://umap.fluv.io/

Other Mutli are working fine.

**Comment by yohanboniface** [comment]
Yeah, I'm not sure we will support MultiPoint at all.
Should we then split a MultiPoing in many Point during import?

**Comment by druxstr** [comment]
Oh no, MultiPoint solves SO much problems. It would be a shame.

- Many points means many lines in the data browser. And it adds clutter

If you're representing an single entity that has multiples locations (like a partnership between cities), you got identical lines cluttering the data browser. The entity _has_ to keep the same name, cause there is only one, but you get to repeat that name in the data browser, as it's a represented by bunch of different Points.

- Many points also mean repeating the same code all over

Take a Feature using MultiPoint and having a lot of properties. If we split it to many Features using a Point, we'll have many Points, with the same properties repeated. It not just heavier, it's a pain to maintain. Any change will have to be made in every Point.

I do get that MultiPoint is less used, but it's really powerful and it _solves_ problems. MultiPoint support would make Umap a full featured solution for almost every need.

Please consider supporting it.

**Comment by yohanboniface** [comment]
OK, can you open a fresh issue with that? I'll have a try on it?
