### ISSUE TITLE
Center map on your localisation doesn't keep zoom level

### ISSUE THREAD

**Issue by NicolasGrosjean** [umap-project/umap#763]
Hi,

When I use the button "Center map on your localisation", the map is unzoomed. I have tested it both on mobile and desktop.

Like in addition the localisation is not displayed (see #339 ), it is very difficult to use the localisation feature.

Thank you for reading me.

**Comment by yohanboniface** [comment]
>  localisation is not displayed

This one is fixed :)

About the zoom, I'm not sure what would be the correct behaviour, given that when the localisation is active the user position is watched.
So, when asking for localisation, the map does three things:
- display a dot to show the position (and a circle to show the accuracy)
- move the view to this position
- zoom to this position

@NicolasGrosjean @Dirk71 What zoom behaviour are you expecting ? Keeping in mind that when locate is active, if your position changes, the map will relocate you (eg. on smartphone).

**Comment by NicolasGrosjean** [comment]
> @NicolasGrosjean @Dirk71 What zoom behaviour are you expecting ? Keeping in mind that when locate is active, if your position changes, the map will relocate you (eg. on smartphone).

I expect keeping the same zoom level. OsmAnd did it and it avoid issues when your position change.

Currently when I unzoom or zoom with a localisation, the zoom is reset in 1 second.

Last month when I tested, I zoomed in on a map with data in only 1km². When I used localisation, the map was unzoomed to 10 000km² ... Like in addition the localisation was not displayed, even by zooming in it was impossible to compare my position with map data.

**Comment by Dirk71** [comment]
Yes, @NicolasGrosjean did explain it. I also would like to keep the zoom-level when localisation is enabled.

**Comment by Dirk71** [comment]
Are there any news on this?

**Comment by yohanboniface** [comment]
I've made that zoom does not change any more on locate.

**Comment by Dirk71** [comment]
Thank you Yohan for your contribution. But there is another issue now....when the localisation is active the zoom-level is LOCKED. I only can change it, when I set localisation OFF.
The behaviour should be same as other GPS apps....keep the zoom-level but allow to change it manually (even when localisation is active).

**Comment by ddejalle** [comment]
Hi guys,
This issue still there, this is a little bit bad if you want to use the lock GPS button on a mobile device in order to follow a specific path. I mean, for user that are no familar with using devices and playing around ;-)

me, as a "clever" user, I know that I have to turn off the lock GPS button to be able to zoom/unzoom, then turn on again, but "standard" user could have problem with that.

we use Umap service to share touristic path and let people to "navigate" on them with just this easy lock gps button this is fantastic (no other application needed !)

thanks

**Comment by Dirk71** [comment]
@ddejalle Absolutely agree with you. But I doubt that this issue will be fixed some day. I am waiting for this for a long time.
