### ISSUE TITLE
502 Bad Gateway when username contains a space

### ISSUE THREAD

**Issue by DominikBeeBop** [umap-project/umap#774]
Hey all
Great project.

I have the following problem. 
After logging in via OSM, https://umap.openstreetmap.fr/de/ loads for a very long time and then hangs at 502 Bad Gateway.

However, if I go to the website and don't log in, I can look at the public maps.
Hope with my account and the maps created everything is fine. I'm grateful for any help.
Best regards
Dominik

**Comment by yohanboniface** [comment]
hi @DominikBeeBop 

Can it be the issue described here #773 ?

**Comment by DominikBeeBop** [comment]
Thank you for your reply.
It appears to be so. Unfortunately, I don't know where I could still be registered with it.
I don't have an account on Twitter, nor Bitbucket. I have an account with Github, but neither the username nor my password is the same
Have another old account for Umap that works.
How could I get my cards back?

**Comment by yohanboniface** [comment]
Short term solution: can you give me your current username ?

**Comment by DominikBeeBop** [comment]
VIA eG 
on OSM

**Comment by yohanboniface** [comment]
Not sure it's the same issue then, I don't see any conflicting username.

Did you by case changed your OSM name recently ?

You talked about an old account, what was the username ?

**Comment by DominikBeeBop** [comment]
Old Account is
PlanungsbüroVIAeG 
this works, but didn´t have the maps 

The OSM name (VIA eG) has not been changed.
This account was still working this morning. Only around noon came 502 Bad Gateway.

**Comment by yohanboniface** [comment]
Can you try again and tell me if you have an error message instead of the 502 page ?

Also, can you copy paste the final URL (the one giving you a 502) ?

**Comment by DominikBeeBop** [comment]
Hi
It is not a specific map, it happens during the registration process. After I log in via OSM and have granted Umap access to my OSM account, I return to Umap. Then the page loads a long time and ends with 502

**Comment by yohanboniface** [comment]
still, what the final URL ?

**Comment by DominikBeeBop** [comment]
I tried to log in (in Chrome browser - incognito mode). The 502 Bad Gateway still appears

I didnt understand "final URL"
https://umap.openstreetmap.fr/de/

eg this is a Map of my Account
https://umap.openstreetmap.fr/de/map/radverkehrskonzept-stadt-goch_399399

**Comment by yohanboniface** [comment]
I'm clueless :/

Can you try to login on this QA site http://umap.yohanboniface.me/ ?

**Comment by DominikBeeBop** [comment]
simple with my OSM Account?

**Comment by yohanboniface** [comment]
yes.

And then retry on umap.openstreetmap.fr, I've changed a setting just in case

**Comment by DominikBeeBop** [comment]
under
http://umap.yohanboniface.me/
Oops, Server error…

under 
umap.openstreetmap.fr
502 Bad Gateway

**Comment by yohanboniface** [comment]
Okay, once again on http://umap.yohanboniface.me/ ? And copy-paste the error page, thanks

**Comment by DominikBeeBop** [comment]
Anforderungsmethode: | BEKOMMEN
-- | --
http://umap.yohanboniface.me/de/
2.2.11
NoReverseMatch
Umkehrung für 'user_maps' mit Argumenten '(' VIA eG ',)' nicht gefunden. 1 Muster versucht: ['de / user / (? P <Benutzername> [-_ \\ w @] +) / $']
/srv/umap/venv/lib/python3.5/site-packages/django/urls/resolvers.py in _reverse_with_prefix, Zeile 673
/ usr / bin / uwsgi-core
3.5.2
['.',  '',  '/srv/umap/venv/lib/python35.zip',  '/srv/umap/venv/lib/python3.5',  '/srv/umap/venv/lib/python3.5/plat-x86_64-linux-gnu',  '/srv/umap/venv/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/srv/umap/venv/lib/python3.5/site-packages']
Mi, 25 Mär 2020 14:00:41 +0000

**Comment by DominikBeeBop** [comment]
[UmapDominik.txt](https://github.com/umap-project/umap/files/4381320/UmapDominik.txt)

**Comment by yohanboniface** [comment]
OK, now we have the clue! Thanks, I'll work on a fix

**Comment by DominikBeeBop** [comment]
Many thousend thanks to you

**Comment by yohanboniface** [comment]
@DominikBeeBop can you try again on http://umap.yohanboniface.me/ ?

**Comment by DominikBeeBop** [comment]
Hi
I can log in on your demoserver , great

**Comment by yohanboniface** [comment]
OK, try in umap.openstreetmap.fr now, should be good

**Comment by DominikBeeBop** [comment]
Thats it.
Great and again many, many thanks to you
