### ISSUE TITLE
My map data has been deleted

### ISSUE THREAD

**Issue by komlosn** [umap-project/umap#775]
Dear Address.

I made a bike tour map for private use.
( http://umap.openstreetmap.fr/ )
I saved the map to the web yesterday.
Today, all data is gone. (I worked with him for at least 10 hours)

What could have happened?
How do I restore it?
Thank you.

**Comment by Binnette** [comment]
Hi @komlosn,

- do you have a link to your map?
- or at least do you know the name of your map?
- were you connected to uMap when creating the map?

I think you created your map without connecting to uMap with (Osm, GitHub, ...). So your map is lnot linked to any account. Instead your map is linked with a specific web brwoser on a specific compuret. If so, try to edit this map on this specific computer and web browse.

Otherwise, may be today you connect with an account, so your map is not linked with your account.

Please have a look to the FAQ, it may help you :
https://wiki.openstreetmap.org/wiki/UMap/FAQ

**Comment by komlosn** [comment]
> Szia @komlosn ,
> 
> * van linke a térképen?
> * vagy legalább tudja a térkép nevét?
> * csatlakozott az uMap-hez a térkép létrehozásakor?
> 
> Azt hiszem, úgy készítette el a térképét, hogy nem csatlakozott az uMap-hez (Osm, GitHub, ...). Tehát a térképet nem kapcsoljuk össze semmilyen fiókkal. Ehelyett a térképet egy adott webes brwoser-hez kapcsolják egy adott kompresszoron. Ha igen, próbálja meg szerkeszteni ezt a térképet ezen a számítógépen és a webböngészésben.
> 
> Ellenkező esetben előfordulhat, hogy ma kapcsolatba lép egy fiókkal, így a térképe nincs összekapcsolva a fiókjával.
> 
> Nézd meg a GYIK-t, ez segíthet:
> https://wiki.openstreetmap.org/wiki/UMap/FAQ
> 
> SZERKESZTÉS: Talán más térképen is létrehozta a térképet? Itt található a szerverek listája:
> https://wiki.openstreetmap.org/wiki/UMap#Instances


Hello.

http://umap.openstreetmap.fr/hu/map/city2020_435089#13/47.5047/19.0811

**Comment by Binnette** [comment]
Great. So you can get your map back by applying the cloning procedure here: https://wiki.openstreetmap.org/wiki/UMap/FAQ

**Comment by Binnette** [comment]
Please close this bug, when you have cloned your map.

**Comment by komlosn** [comment]
> Great. So you can get your map back by applying the cloning procedure here: https://wiki.openstreetmap.org/wiki/UMap/FAQ

Thanks

Unfortunately, the data made yesterday were gone.

A blank map was loaded today.
Even though I cloned, I still see only a blank map.

How do you restore yesterday's data?
Why does the data disappear if I saved it?

Is there an offline program / map that I can edit like this?

**Comment by yohanboniface** [comment]
Have you checked the old versions of your datalayers ?

Edit datalayers => Versions, and you should have a list of previous saves.

**Comment by komlosn** [comment]
> Have you checked the old versions of your datalayers ?
> 
> Edit datalayers => Versions, and you should have a list of previous saves.

This too is empty. :(

**Comment by yohanboniface** [comment]
I'm sorry, but even looking at the server, I can see not other data than the one listed in the versions.

Are you sure you don't created two maps ? Are you sure you saved the data after your work ? Did you recall any action that occurred last time you saved/edited/viewed the map ?

I've never seen data disappearing like that.
