### ISSUE TITLE
Unwanted return line with text, link, image : format (recent) problem (window/flap display)

### ISSUE THREAD

**Issue by AZWCI** [umap-project/umap#776]
Hello. Please, imagine ++ is ** on this exemple

If I type this ++text++ to display as 

If I type this **text** to display as              (appears)

now, the browsers or uMap (?) presents like that:

If I hit this
**text**
to display as

And this put a big "mess" on the neatness well worked of my uMaps.

I can almost get around the problem by typing this:

[[If I type this ++text++ to display as]]

But I get link text (with link error 404) so it’s not okay either...

[If I type this **text** to display as](https://umap.openstreetmap.fr/fr/map/Si%20je%20tape%20ce%20%3Cstrong%3Etexte%3C/strong%3E%20pour%20qu'il%20s'affiche%20ainsi)

"Where" is the problem please ?
Is it a "bug" ?
Is there a new "code" for format text ?

Thank you.

Edit by Binnette. Following is not formated; `This **text** ++is++ not [formated](osm.org) by GitHub markdown syntac`

**Comment by Binnette** [comment]
Note about GitHub markdown syntax, you can use [inline code block](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) to write non formated stuff in your message.

Exemple: `Non **formated** ++text++ in this grey bloc`

**Comment by AZWCI** [comment]
My english is awfull...

Perhaps it can be more easy to see/understand the problems :

https://umap.openstreetmap.fr/fr/map/umap-text-and-images-format-problems_436512#6/49.916/1.846

Browsers bad reading ?

**Comment by AZWCI** [comment]
the problems just appears on the "shape informations".
if i put the same code on the "map properties" (see  with right click "about") the code appears with good format.

**Comment by AZWCI** [comment]
**Resume :**

> `If I type this **text** to display as` (on the uMap **and** Markdown/Shape proprieties)

Markdown/Shape windows result is : 

  If I type this
  **text**
  to display as
:-1:  (bad format : **not online** : unwanted line return !) `(problem valable with **fat_text**, [[link]], {{image_ without_size}} ...)`

uMap properties" (see with right click "about") result is :

  If I type this **text** to display as
:+1: (good format : online !)

Please, look [this uMap exemple](https://umap.openstreetmap.fr/fr/map/umap-text-and-images-format-problems_436512) for see/understand the Markdown/shape proprietes format problems.

The problem in [french forum osm](https://forum.openstreetmap.fr/viewtopic.php?f=19&p=19530#p19530) uMap

**Comment by yohanboniface** [comment]
@Binnette seems to be related to https://github.com/umap-project/umap/commit/345283782c45e3f565132f1ad0c2fa5c4b7d4043#diff-356b8a43ccc66b9d36fe49f87ba77ad0R1285-R1287

I need to be offline for work for a few more hours and I'll have a look, but if you can do it before that would be great :)

**Comment by yohanboniface** [comment]
See also https://forum.openstreetmap.fr/viewtopic.php?f=19&t=7374

**Comment by Binnette** [comment]
Hi, sorry about that. I made a PR #777. I am gonna test it more.

Here is what i get now:
![image](https://user-images.githubusercontent.com/6597721/77820092-0cec0100-70e0-11ea-9f97-4c2648e68748.png)

Bad line break are fixed. Everything seems good to me. I will test it more.

**Comment by Binnette** [comment]
Just to be sure, i added a line break in my umap data (in the description of my umap marker)
Here is what I get:

![umap-line-break-iframe](https://user-images.githubusercontent.com/6597721/77820702-6a824c80-70e4-11ea-9ede-896dca476ad8.png)


As said before, my fix still imrove iframe width :wink:

**Comment by AZWCI** [comment]
Lots of thanks guys ! :+1: 
:1st_place_medal:
