### ISSUE TITLE
add an api for automatic export

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#78]
Originally reported by: **BitBucket: [guillaumeallegre](http://bitbucket.org/guillaumeallegre), GitHub: [guillaumeallegre](http://github.com/guillaumeallegre)**

---

I would like to automatically download the geojson export of a map,
eg. on a daily basis.
This is to track locally the editions of an open map (and perhaps manually revert to a previous version in case of vandalism).
A very simple API would be useful for this.

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/78

**Comment by almereyda** [comment]
Please note we just ran into #174 trying to export as much raw data from uMap as possible. It also appeared the `mime-type` for the `geojson/` endpoint is not properly set; a browser tries to download a `geojson.html` instead of `map#.geojson`.

**Comment by Wikinaut** [comment]
Has anyone a working script for doing the steps programatically?

I my humble opion, the download "all" link should be a static perma link on the umap.
![grafik](https://user-images.githubusercontent.com/1151915/149239457-f2bb3f17-ca18-4bb4-803f-3f8dd57c3467.png)

**Comment by Wikinaut** [comment]
nodejs-code is here: https://github.com/Wikinaut/getumap

**Comment by yohanboniface** [comment]
There is now a direct link to download full map data, eg.: https://umap.openstreetmap.fr/map/1/download/ where `1` is the id of the map.

**Comment by hriebl** [comment]
This is not yet implemented on the German server, right? Or am I using the wrong URL?

- https://umap.openstreetmap.de/de/map/entsorgungsbetriebe-lubeck_49064 ➡️ works
- https://umap.openstreetmap.de/map/49064/download/ ➡️ doesn't work

**Comment by hholzgra** [comment]
The maintainer (not me) of the openstreetmap.de instance hosted by FOSSGIS e.V. is working on getting the site updated, but it is still work in progress right now ...

**Comment by prin-underlandscape** [comment]
uMap is a fantastic project, but I lack an API that enables me to upload either a layer or the entire map. Is there any chance of it being implemented?

**Comment by almereyda** [comment]
As a side-note, FOSSGIS have updated the umap.openstreetmap.de instance to v2.

![grafik](https://github.com/umap-project/umap/assets/1645308/14b9b197-8c56-43e7-a721-eec01050b320)

1. It now offers the download button and with that a "download API" to retrieve maps with permissions set to *Everyone (Public)* and *Everyone with the link*.
2. Requests to a map set to *Editors only* will yield a 403.
3. Additionally it is possible to craft a request to download multiple (public) maps at once:  
   https://umap.openstreetmap.de/de/me/download?map_id=1706&map_id=49064

Automation of cases (2.) and (3.), an "automatic export API", would probably be possible with authorising the requests with a valid authentication cookie.
