### ISSUE TITLE
cant change ownership of current map

### ISSUE THREAD

**Issue by Caidezel** [umap-project/umap#780]
Hey, my map is linked to my account, but i want to give the ownsership to another user. I got a red error message after trying to switch permissions... Any idea how to change ownership ?

**Comment by Binnette** [comment]
Hi @Caidezel, can you please post a link to your map here? Also can you please give us the error message? Since you are a web designer, I think you can also post here the complete response sent by the server 😉 Thank you and have a nice day.

**Comment by Caidezel** [comment]
Hi @Binnette my current map : https://umap.openstreetmap.fr/fr/map/points-de-vente-produits-locaux_435582#8/46.088/4.724 (linked to my account atm, i just need to switch ownership to another user)

I've tried to prompt something in web console, but it's empty, i got a simple red box "An error occured" when i tried to save a new owner. Got no idea of what to do there...

**Comment by yohanboniface** [comment]
@Caidezel can you try again? I'm monitoring the logs to see some error

**Comment by Caidezel** [comment]
Just tried it a this moment.

**Comment by yohanboniface** [comment]
Grml, nothing in the logs.

Able to do a quick screen sharing, eg. using https://meet.jit.si/umap ?

**Comment by yohanboniface** [comment]
Ah, I see you are dev, you may just paste me the HTTP response error message :)

**Comment by yohanboniface** [comment]
OK, I've reproduced the error.

I'll fix it, but in the meantime, can you give me the account you want to transfer the map to ? I'll do it from the command line.

**Comment by Caidezel** [comment]
Seems its a permission problem right ?

`{errors: {edit_status: ["Ce champ est obligatoire."], share_status: ["Ce champ est obligatoire."]},…}
errors: {edit_status: ["Ce champ est obligatoire."], share_status: ["Ce champ est obligatoire."]}
edit_status: ["Ce champ est obligatoire."]
0: "Ce champ est obligatoire."
share_status: ["Ce champ est obligatoire."]
0: "Ce champ est obligatoire."
error: "<ul class="errorlist"><li>edit_status<ul class="errorlist"><li>Ce champ est obligatoire.</li></ul></li><li>share_status<ul class="errorlist"><li>Ce champ est obligatoire.</li></ul></li></ul>"`

yep, just need to switch ownership to 'BB_ZDL' (currently recorded as a modifyer in this map ;)

TY !

**Comment by yohanboniface** [comment]
Should be good!

**Comment by Caidezel** [comment]
@yohanboniface Perfect ! TY !

**Comment by Binnette** [comment]
Fixed ? so i close it ?

**Comment by yohanboniface** [comment]
Nope, I've just changed the ownership in the DB for now, and now I'm able to reproduce the issue. But this still needs a proper fix :)

**Comment by chrisgastebois** [comment]
Hi @yohanboniface i have the same problem, this issue has been solved ? Thanks for your response

**Comment by yohanboniface** [comment]
Should be fixed. Please test again and give feedback :)

**Comment by chrisgastebois** [comment]
> Should be fixed. Please test again and give feedback :)

Perfect this worked for me. Thanks
