### ISSUE TITLE
Responsive images in side panel

### ISSUE THREAD

**Issue by ebakogianni** [umap-project/umap#781]
Hi,

I am working on this public map:
[https://umap.openstreetmap.fr/en/map/paris-au-cinema_282405](https://umap.openstreetmap.fr/en/map/paris-au-cinema_282405)

Since last week, the display of iframes in the side panel seems to have
been improved (full width) but images are not responsive anymore. On
large and small screens, my images are larger than the side panel,
and, on medium screens, they are smaller.

It looks like the images were blocked at ```400px```, which is the max-width
applied. When I uncheck the line corresponding to this max-width through
the developer tools, everything seems to work correctly (its the
```max-width: 99% !important``` mentioned elsewhere in the css that applies
then).

Is there a way to solve this? How can I make my map's images on the side
panel responsive again.

**Comment by yohanboniface** [comment]
cc @Binnette any time to have a look ? :)

cf #765

**Comment by Binnette** [comment]
Already fixed in  #777 :)

**Comment by Binnette** [comment]
It was a side effect of my not so good solution...

**Comment by Binnette** [comment]
@ebakogianni Can you send to us a screenshot if you can still reproduce the bug please :)

**Comment by ebakogianni** [comment]
Hi, the bug can be seen in the screenshot you provided. If you take a look at the text in the Description paragraph you can see that its right part is cut, same thing happens to the image.

Here is a screenshot of the same side panel displayed correctly:

![Screen Shot 2020-04-08 at 12 35 05](https://user-images.githubusercontent.com/59390462/78777650-39363600-799a-11ea-8359-48899d0f5161.png)

To get this result I have commented the line ```max-width: 400px !important```.

**Comment by Binnette** [comment]
Ohhhhh ok ! I will give a look to the source code then :)

**Comment by Binnette** [comment]
Ok now it seems way more better. See below before/after my fix.
- i reduce the padding (in yellow in following picture) to get more space
- i justify the text, it's prettier like that

![umap-img](https://user-images.githubusercontent.com/6597721/78782992-35f37800-79a3-11ea-90e3-dd0b7422fd40.png)

What do you think @ebakogianni?

**Comment by Binnette** [comment]
Ok so here is what I managed to do: (before/after)
- You can see in yellow what spacing i changed.
- I also "justified" the text, so it looks better

![umap-img](https://user-images.githubusercontent.com/6597721/78838405-66183680-79f6-11ea-9915-31fc73195f4a.png)

**Comment by ebakogianni** [comment]
Looks great, thank you !
