### ISSUE TITLE
Maps deleted

### ISSUE THREAD

**Issue by TjaPhiMey** [umap-project/umap#784]
Hi,

I've just logged in and all my maps are deleted!
I have no backups, no data!
(User: Ruffnex)

**Comment by yohanboniface** [comment]
I see maps http://umap.openstreetmap.fr/fr/user/Ruffnex/ here

**Comment by TjaPhiMey** [comment]
That's quite interesting...
![image](https://user-images.githubusercontent.com/64006765/79738009-77b5e400-82fc-11ea-97e6-99a29c762410.png)

**Comment by yohanboniface** [comment]
openstreetmap.de vs openstreetmap.fr ;)

**Comment by TjaPhiMey** [comment]
But it worked fine in german. Never used the french layer... And as I could login/work with both languages should the maps also be available in both languages?

**Comment by TjaPhiMey** [comment]
German site, german layer, no data
French site, german layer... seems to work.
https://umap.openstreetmap.fr/de/
Okay, little bit confusing.
Let my ask it this way:
Why can I loggin with my account in french AND german but I'm not able to see the same things. Account seems to be the same, but data is splitted? Does it make sense? Perhaps there is a reason, just want to understand it. Otherwise it's a featurerequest :-)

**Comment by yohanboniface** [comment]
> Perhaps there is a reason, just want to understand it. 

The reason is that those are two distinct servers, managed by different people. I'm sorry that this confusing, maybe because both URLs start with "umap.openstreetmap.", but at this stage there is nothing we can do easily.

I'm closing here as imho there is no action needed, but the conversation is not closed.

**Comment by TjaPhiMey** [comment]
Okay, thanks for info and for quick response!
