### ISSUE TITLE
Customization of uMap theme or layout doesn't work ?

### ISSUE THREAD

**Issue by Interested-in-opensource** [umap-project/umap#785]
Hi,

I wanted to do some customization on the layout / theme following this documentation :
https://umap-project.readthedocs.io/en/latest/custom/

I use v1.2.2

for some reason it doesn't work, tried to clear cache, restarted uwsgi, nginx etc ...
 this simple exemple 
```
" .umap-nav {
    background-color: red;
}" 
```
never worked on my main page. 

I also looked for umap/navigation.html  in the original static folder but does'nt exist.

I added into _/etc/umap.umap.conf_

```
    UMAP_CUSTOM_TEMPLATES = '/srv/umap/path/to/templates/'
    UMAP_CUSTOM_STATICS = '/srv/umap/path/to/static/'
```

doesn't seems to load anything ..

I even tried to change in the original static folder the theme.css file and it doesn't work either.

What is the purpose of the CACHE folder which contain js and css ? could it be related to my issue ?
Any idea would be great.

Thanks

**Comment by yohanboniface** [comment]
Some hints:

- make sure to switch to `DEBUG=True` to ease investigation
- have a look at the CSS loaded by the page: is your change there ?
- make sure to run `umap collectstatic` and `umap compress` when in `DEBUG=False`

**Comment by Interested-in-opensource** [comment]
Hi Yohan,

Thank you for the tips,
I tried :
desactivate DEBUG : 

> DEBUG = false

Then modify the theme.css
Then run **umap collectstatic** and **umap compress** then put back

> DEBUG= true

it now takes the **theme.css** color but still nothing about the **navigation.html**  and the test logo 

i get a 404 

```
Not Found: /srv/umap/custom/static/umap/img/wiki_logo.png
GET /srv/umap/custom/static/umap/img/wiki_logo.png HTTP/1.1" 404 4067
GET /favicon.ico HTTP/1.1" 404 3965
```
The file exist and is readable 

```
ls -al /srv/umap/custom/static/umap/img/
drwxr-xr-x 2 umap umap  4096 Apr 21 08:15 .
drwxr-xr-x 3 umap umap  4096 Apr 21 08:55 ..
-rw-rw-r-- 1 umap umap 90284 Apr 20 09:13 wiki_logo.png
```

And nothing in the logs about navigation.html ...
In the basic static installation i have also no file named "navigation.html" maybe it's my first issue   ?
How is generated the main webpage at / ?

now i also get  304 errors ... 

```
[21/Apr/2020 10:12:04] "GET /static/CACHE/js/output.100e48f39fe9.js HTTP/1.1" 304 0
[21/Apr/2020 10:12:04] "GET /static/CACHE/js/output.400583288e77.js HTTP/1.1" 304 0
[21/Apr/2020 10:12:04] "GET /static/CACHE/css/output.5217aba07350.css HTTP/1.1" 304 0
[21/Apr/2020 10:12:04] "GET /static/umap/img/osm.svg HTTP/1.1" 304 0
[21/Apr/2020 10:12:04] "GET /static/umap/img/logo_filigree.png?625e752bedc8 HTTP/1.1" 304 0
[21/Apr/2020 10:12:04] "GET /static/umap/img/edit.svg HTTP/1.1" 304 0
[21/Apr/2020 10:12:04] "GET /static/umap/img/opensource.svg HTTP/1.1" 304 0
```

**Comment by yohanboniface** [comment]
> desactivate DEBUG :

Please keep `DEBUG=True` until everything works as expected

> now i also get 304 errors ...

Those are not errors, they are HTTP code saying that the server file has not changed since last time the browser requested them.


Can you share you local config file ?

**Comment by Interested-in-opensource** [comment]
Quick update from my side.
i had a typo in **umap.conf** ...  :-/ 

> UMAP_CUSTOM_TEMPLATE

 instead of  

> UMAP_CUSTOM_TEMPLATES

I get no warning when i do **umap collectstatic** and **compress** ... after hundred of tests i didn't pay attention to the variable name ... so it wasn't working for that reason...

But i still don't see how the main page is built, for exemple the footer  ? the navigation.html is ok but i don't see other parts, do i have to check in .js files how everything is structured ?

**Comment by yohanboniface** [comment]
Hi @Interested-in-opensource I guess you've moved forward since then, but in case you still need help, please reopen!
