### ISSUE TITLE
Running umap server on Windows

### ISSUE THREAD

**Issue by brentfraser** [umap-project/umap#787]
Not really a request for help, just a list of steps to show others how to get uMap running on Windows.

The **good news** is that it is possible to run uMap server on Windows.  That said, I'd recommend using uMap on a Linux distribution as I expect it will be easier to install, modify, and deploy.  My goal was just to experiment with uMap to get some insight into its abilities, protocols, etc. so I can't guarantee all functions work on Windows.

My set up:
- Windows 7 64-bit
- Postgresql 9.6, with PostGIS 2.5.3
- Python 3.8.2 64-bit, with pip and virtualenv installed
- uMap v1.2.2

An outline of the steps:

**1. Prepare the database** 
This assumes you've installed Postgresql.
- Create a database called "umap"
- Install PostGIS extension in it

**2. Create a directory and a Python virtual environment** 
Open a Windows command window, cd to a directory of your choice and do:
```
mkdir test
cd test
virtualenv venv
venv\Scripts\activate.bat
```

**3. Install GDAL for Python**
It is really difficult to install GDAL the "standard" way since it requires compiling GDAL.  Instead download an already compiled pip-compatible wheel package file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal .  Note that cp38 refers to the Python version you are using, so make sure you select the one that matches your Python version for download.

In the command window, install the downloaded wheel package:
`pip install GDAL-3.0.4-cp38-cp38-win_amd64.whl`

You can test the install from the Python command line.  From the Windows command window invoke Python:
```
python
```
then enter some Python commands:
```python
>>> import gdal
>>> print(int(gdal.VersionInfo('VERSION_NUM')))
>>> exit()
```
**4. Install uMap**
In the Windows command window:
```
mkdir static
mkdir data
pip install umap-project
```
**Windows Work-Around 1**
I couldn't get setting the UMAP_SETTINGS environment variable to work, so I put the file in umap's fall-back location of \etc\umap\umap/conf (not very Windows friendly, but good enough for testing):
```
mkdir \etc\umap
wget https://raw.githubusercontent.com/umap-project/umap/master/umap/settings/local.py.sample -O \etc\umap\umap.conf
```
Edit the umap.conf:

**Windows Work-Around 2**
It might be possible to modify django's libgdal.py (umap installed django) to detect the installed GDAL, but until then you can explicitly give the paths.

Add the GDAL paths somewhere near the top of the umap.conf file (make sure the last part, "gdal300", is the name of the GDAL DLL in its package dir):
```python
GDAL_LIBRARY_PATH = r'C:\temp\test\venv\Lib\site-packages\osgeo\gdal300'
GEOS_LIBRARY_PATH = r'C:\temp\test\venv\Lib\site-packages\osgeo\geos_c'
PROJ_LIB =          r'C:\temp\test\venv\Lib\site-packages\osgeo\data\proj'
```
And while you're editing umap.conf, add the needed parameters to the DATABASES default object :
```python
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'umap',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432'
```
And set umap's paths to where you've created the directories:
```python
STATIC_ROOT = '/temp/test/static'
MEDIA_ROOT  = '/temp/test/data'
```
Now that the minimal configuration is done, you can do the django-ish portion of the umap install.  In the Windows command window:
```
umap migrate
umap collectstatic
umap createsuperuser
```
**Windows Work-Around 3**
Strangely, having umap.exe is not enough.   Some script tries to execute "umap" without the ".exe" extension, so here's the hack to make that work:
```
copy venv\scripts\umap.exe venv\scripts\umap
```
**5. Run umap server**
In the Windows command window:
```
umap runserver 127.0.0.1:8000
```
You should now be able to open a browser and go to http://127.0.0.1:8000

If  you add some features to a new map and try to save them, you will likely see an error in the Windows command window running the umap server.   This error is a Python error related to doing 
`os.remove(name)` on Windows (see #238):
```
  File "c:\temp\test\venv\lib\site-packages\django\core\files\storage.py", line 303, in delete
    os.remove(name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\temp\\test\\data\\datalayer\\1\\1\\layer-1.geojson'
```

**Windows Work-Around 4**
Edit `test\venv\lib\site-packages\django\core\files\storage.py`, and comment out lines 302 and 303:
```python
#            else:
#                os.remove(name)
```
Now adding features and saving should work.  _Now here's the weird part._   Edit `storage.py` to restore it to it's original state by removing the comment characters you put in.  Save the changes, do some more feature editing and saving in your browser.  It still works!  This may be due to file/directory locking by Windows, I don't know.

That's all!  Have fun!

**Comment by Binnette** [comment]
Hi @brentfraser, this is great. Can you please consider make a pull request to the documentation inside our repo?

**Comment by brentfraser** [comment]
Hi @Binnette, Will do!

**Comment by davidbgk** [comment]
Done in https://github.com/umap-project/umap/pull/790
