### ISSUE TITLE
Limitations on objects count & perf issues

### ISSUE THREAD

**Issue by Binnette** [umap-project/umap#788]
Hi @yohanboniface,

I just received some questions about umap. Question were asked by Maria Popova on my journal: https://www.openstreetmap.org/user/Binnette/diary/392302#comment47028 

I would like to have your point of view on those questions:
- Does uMap have any limitations on objects number?
- Which number of polygons could degrade the map performance noticeable ( 1K, 1M, 1B )?
- Is it ok to add millions of polygons in uMap?

Here is Maria's map : http://umap.openstreetmap.fr/ru/map/map_424586#6/57.636/38.511

**Comment by Binnette** [comment]
So here are some answers from my point of view.

- uMap does not have limitation on the number of displayed elements. But if you add many elements, your web browser will not support it. There are some performance issues maybe in the libraries we are using?

@yohanboniface I can **well** remember this Italian map with about **15k elements**. The map was terribly slow and the user can't open it. I was obliged to remove a bunch of duplicated element to make it work again in a web browet. BTW the issue was that 15k element is way too much for our librairies and/or web browser.

**Comment by MariaP0p0va** [comment]
Hello. Thank you for response!

10K polygons would be enough for a first time I think, but we'll exceed the limit after a couple of seasons...
Is it possible to show objects only for large scale and hide all polygons for small scale somehow? In the case browser will not need to render a lot of objects in the window.

**Comment by Binnette** [comment]
Hi @MariaP0p0va,

I advice you to store your objects on geojson files on your web server (or on GitHub, or any file host). That way, your data are safe in case your uMap projetct crash (Sometime we can not recover data). But I think you maybe already do that.

Here is a way to do so. Note that you can choose the min & max zoom level in which your remote data will be displayed. Also you should consider making one geojson file by region in you plan to have many elements. Also you should consider creating one uMap project by region?

![remotedata256](https://user-images.githubusercontent.com/6597721/80371134-b403ba00-8891-11ea-810a-b8302c78b860.gif)

**Comment by brentfraser** [comment]
For web mapping in general,  there are a few strategies:

1. Filter the features by scale and/or view bounds (could use WFS protocol with Geoserver on the server)

2. Render them on the server to an image (using Mapserver for example)
  - if you want to edit them it would required some additional client and server coding.

3. Use Vector tiles (you would need to investigate a tile server, or at least a Leaflet plugin)

**Comment by MariaP0p0va** [comment]
Hi, @Binnette !  Certainly, I backup map data regularly. :)  I don't whant to create one uMap project by region, because we need to demonstrate several regions at the same time occasionally.  Also people sometimes do not know administrative edges, it may be in forest or field without any landmark. But if we reach the perfomance limit, we'll need to do so.

**Comment by JanLukasGithub** [comment]
Does uMap implement [Viewing Frustum Culling](https://en.wikipedia.org/wiki/Hidden-surface_determination#Viewing-frustum_culling) or the 2D version of the technique?

Does uMap show all objects when there are many and you are zoomed out far? Is [Occlusion Culling](https://en.wikipedia.org/wiki/Hidden-surface_determination#Occlusion_culling) implemented, if that even improves performance?

**Comment by yohanboniface** [comment]
uMap does not implement such algorithms itself. It is based on Leaflet, but AFAIK it's not implemented. But maybe a plugin exist (I don't know) that could be used here.

That could be a nice contribution, tough.

See also #1061 and https://github.com/Leaflet/Leaflet/issues/6314
