### ISSUE TITLE
Satellite view background disappears for a large scale 

### ISSUE THREAD

**Issue by MariaP0p0va** [umap-project/umap#791]
If we select satellite view instead of OpenStreetMap plan as background, it is hided on scale 13 and larger (background on scale 12 and smaller is visible). For large scale we see clear white area :(.
Is it possible to show interpolated photo view or OpenStreetMap plan for such large scale?

**Comment by brentfraser** [comment]
There is a Leaflet plugin to do this https://github.com/ghybs/Leaflet.TileLayer.Fallback. But I don't know how to add this plugin to uMap.

**Comment by MariaP0p0va** [comment]
Thank you for recommendation! I don't know it too, but will try to digg in this direction...
