### ISSUE TITLE
Poligons gouping 

### ISSUE THREAD

**Issue by MariaP0p0va** [umap-project/umap#792]
As I understand, UMap doesn't allow select some polygons (for export purpose for example), am I right? It will allow to export and save locally only part of polygons (not whole map or layer) and demonstrate them offline or backup a part of the map. The selection would be useful for many other applications I guess...

Thank you and best regards!

**Comment by brentfraser** [comment]
There is a Leaflet plugin to do this https://github.com/ghybs/Leaflet.TileLayer.Fallback.  But I don't know how to add this plugin to uMap.

**Comment by Binnette** [comment]
Hi @MariaP0p0va, you can export your data from umap by using the "share" button on the left.
I encourage you to export as geojson. This is a well known format. You can open it with tons of webapp and desktop app: QGis and so on. :+1:

**Comment by brentfraser** [comment]
Geez my comment was for a different issue #791.  sorry about that.

**Comment by MariaP0p0va** [comment]
"export your data from umap by using the "share" button on the left."

I see only "download" button on the right in map properties: [screenshot](http://antiborschevik.ucoz.net/Photos/KARTA/ForUmap/knopka_skachat_kartu.jpg)
Do you mean this button?

**Comment by Duvel** [comment]
@MariaP0p0va she meant a button on the left, see 1 in https://wiki.openstreetmap.org/wiki/UMap/Guide/Using_the_map
