### ISSUE TITLE
Allow public editing only for one layer

### ISSUE THREAD

**Issue by vizsim** [umap-project/umap#793]
Hello,
is it possible to allow editing on one layer only? 
lets say I created 5 layers as a basemap and now want to encourage a community to add icons to a new layer, however, I want to make sure that my 5 basemap layers remain untouched.

**Comment by yohanboniface** [comment]
Not yet. :(
Planned, see #584 for more context.

Closing as duplicate, but the feature is in the radar.

**Comment by yohanboniface** [comment]
Side note, one possible hack:

- create two maps, one open for public edition and one with only private edits
- put all valid data on private map
- on public map, load layers from the private map as "remote layers", and keep a layer for editing
- from time to time, import the new data from public map to private one, on dedicated layers

**Comment by vizsim** [comment]
thank you for your feedback!
by 'load layers from the private map as "remote layers"' you mean export it as .umap and import in the new map?
I did that, however, all layers (imported and newly created) behaved as before

**Comment by yohanboniface** [comment]
> by 'load layers from the private map as "remote layers"' you mean export it as .umap and import in the new map?

Nope.
In your private map, for each layer, copy the "Download" link (Edit layer => Advanced action => Download) and use it in the public map as "remote data" URL (Edit layer => remote data => URL)

**Comment by ormesulmondo** [comment]
> Side note, one possible hack:
> 
> * create two maps, one open for public edition and one with only private edits
> * put all valid data on private map
> * on public map, load layers from the private map as "remote layers", and keep a layer for editing
> * from time to time, import the new data from public map to private one, on dedicated layers

Seems to me  the same thing. Just one map edited just by owner and one layer assigned to editors
It's fondamental to have each layer assigned to different editors !
Please implement this feature that is essential to a collaborative map
