### ISSUE TITLE
how to check users views in umap?

### ISSUE THREAD

**Issue by saragaudio** [umap-project/umap#794]
Hi guys! Is it possible to check how many (daily) views has my map created in umap? Thanks in advance!

**Comment by Lukas458** [comment]
At the moment it is not, unfortunately :(

**Comment by Binnette** [comment]
Hi, I don't think we will implement this.

**Comment by yohanboniface** [comment]
We may have a matomo integration (setting per instance), to use their API also to display counters in "My Maps".
