### ISSUE TITLE
transifex incorrectly shows Dutch translated 100%

### ISSUE THREAD

**Issue by joostschouppe** [umap-project/umap#796]
Hi,
The transifex tool thinks Dutch is done, however there's lots of work left to do! It might be useful to run a tool there to mark identical versions as untranslated. Maybe the same happened in other languages too!
See https://community.transifex.com/t/filter-when-source-text-is-same-as-translated/1113

EDIT (June 10th): everything in Dutch is translated now

**Comment by Binnette** [comment]
Thank you :+1:
