### ISSUE TITLE
General uMap UI Critisism

### ISSUE THREAD

**Issue by Ethan777100** [umap-project/umap#797]
After 1 week of using uMap, i would like to comment how user unfriendly this platform is. There are so many lacking things and bugs here n there that make map tracing very ardous.

1. The UI options and dropdown choices are smth very irritating to work with:

-Only 1 editing feature can be present at any time. Like for eg, ruler distance must be lost in order to edit any line vertex. Why so unproductive?? Can't there be more resilience in allowing multiple editing tools be present on the map at the smae time? 

The map shld be treated more like a canvas whr u are deep in work to edit smth! Not some simplistic browser piece where only 1 thing at one go ... this makes the experience very hard to edit / fine tune map tracing to precision!
**-Cannot distinguish between when u wanna move a line vs editing a line vertex. When u wanna do either/or, you get the other action! This is very atrocious.**

-No UNDO/REDO??! HOW CAN? Do u know how many times i accidentally got my entire line segment deleted when the map accidentally group selects them together?? Do u see how USER UNFRIENDLY IT IS?

2. My Polygon objects disappearing upon closer zoom. 

They r still in my map...but somehow when i zoom closer, they dont render! Then i have to reload just to "Get it back"

3. Inaccessiblity to robustly edit layers and layer characteristics.
The layers feature is pretty underdeveloped. I have to click thru so many client layers just to get to the specific layer element i wanna edit for characteristics...and in fact, the UI design is in such a way where u can only go deeper but not shallower - ie when u finish editing layer characteristics for one element, u cannot return to the Layer Pane where all ur objects are listed at.

4. Merging of lines feature is not working/non-existent.

Its atrocious that if u wanna make a contnious line, u must draw it out fully. Its not easy to keep extending the same line every time and then risk that coz of ur lousy UI, u accidentally click wrongly and do unintended edits/moving/deletion of the entire line segment! **The insecurity that u have to ensure that whilst ur line gets longer n longer....u dont anyhow alter ur earlier precise placements of ur line further up the route.**

Modelling certain line curves is more suitable that u draw a seperate line...then merge it to ur original line. But in uMaps, i can't work backwards in this manner...i can't snap-to and merge 2 lines together at their vertex. 

Your guide says there is such a function...but its not working at all.

5. Sponatenous red banner msg that someone is editing my work.
No! thats not the case, i alr set my privacy setting to my ownself as editor! This red banner popup makes it very misleading and that it has given me some problems jn where i didn't save my work in reality...even though i did!

OVERALL

My UI experience with uMaps has been pretty horrible. It would be gr8 if some of these changes/improvements be made inisde the UI to improve uMaps.

![uMap1](https://user-images.githubusercontent.com/49090166/81550752-42f4f400-93b3-11ea-85a4-66a3c5bb3e1c.gif)

**Comment by Spielmops** [comment]
Do you have a link to your map?
Spielmops

**Comment by yohanboniface** [comment]
Thanks for this feedback. Each single point will be tracked in separate issues.
