### ISSUE TITLE
Adding a marker - cooridnate validation - webpage freeze

### ISSUE THREAD

**Issue by DanielXYZ2000** [umap-project/umap#799]
If a new marker is added and the coordinates are entered the wrong way (. instead of "," or letter by accident) the webpage freezes - a reload is needed (this can include a loss of data)

Browser: Chrome
Steps to reproduce:
1) place a marker on the map
2) edit coordinates 
2a) write a . instead of , e.g. 48.99
2b) add a letter to the coordinate e.g. 48,23xx
in both cased the map disappears and the webpage needs to be reloaded

**Comment by yohanboniface** [comment]
I've made a quick fix to prevent the freeze, and display an alert. It may broke later if the user continue editing and save and so on, but at least the user can fix them selves.
