### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#80]
Originally reported by: **BitBucket: [almereyda](http://bitbucket.org/almereyda), GitHub: [almereyda](http://github.com/almereyda)**

---

As I would love to see uMap spreading across the world, let's start talking about a Dockerfile here.
- Which prequisites do we need?
- Which succsessful (Geo)Django Dockerfiles are known, what can we build upon?
  - https://registry.hub.docker.com/search?q=django
  - https://github.com/dockerfile?tab=repositories

It is to mention, that Docker setups prefer stateless apps, i.e. decoupled logic and persistence. http://12factor.net/ gives an introduction to that thought.

---

Once I've got that working, I'd like to provide a GeoCouch adapter for Django and even further seperate the UI from the backend, so it could run as a CouchApp.

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/80

**Comment by thoka** [comment]
Uff.  There is much info in this thread, not only related to a dockerized umap.

Do I understand correctly, that main questions in creating a docker setup for umap would be, how to keep data integrity on  software updates ?

**Comment by almereyda** [comment]
As far as I understand uMap until now, it's state lives mostly in the file system.
Apparently, from the comments above, PostgreSQL is only used for basic Django capabilities and the GeoDjango part for the centre of maps.

Filesystem storage and the database can be nicely abstracted within a `docker-compose` setup, for example.

Knowing CouchDB [is soon to have an official Dockerfile](https://github.com/docker-library/official-images/pull/1288#issuecomment-178916570) and [GeoCouch seems to work](https://github.com/14mmm/docker-geocouch/issues/1#issuecomment-158085017) dockerized, too, we could think of realigning these discussions:

@thoka also once mentionned there would be a working, containerized uMap setup, but I cannot find it.

* Creating a working `docker-compose` example for uMap

How hard would be a migration path of Django as a mere API layer for a - then - Single Page JS Frontend?
I know now **uMap** encompasses `django-leaflet-storage` and `Leaflet.Storage`, but how can or should we generalize them for different environments? Talking to a number of initiatives associated with @TransforMap we know most of them use Leaflet already, always building new backends for their respective stack (Rust/Neo4j, PHP/MongoDB, JS/MongoDB, etc.)
If I understand it correctly, `couch-leaflet-storage` could be a first step into such a `Leaflet.Storage` ecosystem.

**Comment by jezdez** [comment]
Just a quick heads-up that in case anyone is interested, I've created a [Dokku](http://dokku.viewdocs.io/dokku/) setup for uMap: https://github.com/jezdez/umap-dokku

**Comment by almereyda** [comment]
This is very impressive @jezdez . From my dockerisation experiments I remember there remained issues with some PostGIS development libraries not available in the main container during `pip install` of certain dependencies which would need those to compile. I think this concerned compilation of some GDAL/OGR libraries for Python, which were in use back then. Did you run into any of this, after Dokku's git receive hook had been fired?

**Comment by jezdez** [comment]
@almereyda Nope, didn't hit that, I'm running an uMap instance right now with that and so far it seems to work as intended.

**Comment by jezdez** [comment]
There is now a PR here to add this to the main repo: #456

**Comment by jezdez** [comment]
If you want to try it up, get the docker branch from my fork, install Docker for your platform and run `make docker-up`.

**Comment by LucianoSilvaSantos** [comment]
@jezdez what a marvel I am looking for and I will test I will make a fork of your git and lift the docker to test.

> If you want to try it out, get the docker branch from my fork, install Docker for your platform and run `make docker-up`.

**Comment by jezdez** [comment]
@LucianoSilvaSantos Hey, no problem, I deleted my fork last year, but just reforked and pushed the docker branch again to it. Let me know if you want to pick it up and finish #456. Cheers!

**Comment by LucianoSilvaSantos** [comment]
> @LucianoSilvaSantos Ei, não há problema, eu deletei meu garfo no ano passado, mas apenas reforked e empurrei o ramo docker novamente para ele. Deixe-me saber se você quer pegá-lo e terminar [# 456](https://github.com/umap-project/umap/pull/456) . Felicidades!

Yes, I really want to, and I'm very grateful if you can help me. I have a project that I want to use to support a community here in Brazil. I am very grateful! Through Docker it's easy to get up and manage and replicate the environment.

**Comment by yohanboniface** [comment]
It finally landed! https://hub.docker.com/repository/docker/umap/umap/general

**Comment by almereyda** [comment]
🎉 Many thanks for the long-term maintenance.

**Comment by almereyda** [comment]
_Addendum:_

That's the internal repository settings page, which asks me to login.

The public link is https://hub.docker.com/r/umap/umap

You could replace the link in your comment above, and hide/delete mine.

**Comment by davidbgk** [comment]
Thanks @almereyda :)
