### ISSUE TITLE
Live Remote Data from csv

### ISSUE THREAD

**Issue by nicky-macs** [umap-project/umap#800]
Hi all!
I have an urgent issue new to umap and working on a COVID 19 mapping system to track the distribution of masks. We have live data being submitted and loaded into the map. I cannot see any attributes the points come through x/y lat long but there is no attributable data.

I could not find a solution, 

Second issue is i have loaded a static csv file with the attributes if the opp is a table it all comes through but when i use place holders {} it does not.

Sorry to reach out to the community for this i guess simple get round/ solution.

**Comment by davidbgk** [comment]
Please reopen and share a map link if it is still an issue.
