### ISSUE TITLE
How to upgrade version of uMap

### ISSUE THREAD

**Issue by tech62** [umap-project/umap#804]
Hi !

I want to upgrade my uMap version, but can't find information about that.
Anyone can update the wiki with a process to follow ?

Thanks !

**Comment by Lukas458** [comment]
Maybe a oslution would be to download the data from your uMap and then creating with this dataset a new map? When I see it right, this new map would have the newest version then.

Or do you mean something else?

**Comment by tech62** [comment]
No, i search how to upgrade my Umap version with the entire data of my database + umap application, there is nothing wrote about this case.

**Comment by ovruni** [comment]
I did the following to update my umap instance:

```
sudo -u umap -i
virtualenv /srv/umap/venv --python=/usr/bin/python3.7
source /srv/umap/venv/bin/activate
pip install umap-project --upgrade
umap migrate
umap collectstatic
umap compress
sudo systemctl restart uwsgi nginx
```

**Comment by yohanboniface** [comment]
Yes, indication of @ovruni are correct!

I've just mentioned this in the documentation: https://umap-project.readthedocs.io/en/latest/install/#upgrading

Curious, @ovruni, @tech62 are you still running uMap instances ? If yes, are those public ?

**Comment by tech62** [comment]
We only use it internally for the moment
