### ISSUE TITLE
Permission lite

### ISSUE THREAD

**Issue by DTVIA** [umap-project/umap#806]
![Screenshot_20200531_082344](https://user-images.githubusercontent.com/66194360/83345884-1da33800-a318-11ea-95d7-b1a1fc2b2c49.jpg)
Dear Developer 
At the moment you can choose between read only and full access, so that with the latter, all options such as data upload, editing of all layers, etc. are always available to the user.

Would it be possible for the further development that there would be another user level in umap?  

For example, a simplified user interface could be created for citizen participation.  Processing would be reduced and only the markers (point, line and polygon) would be visible and usable.  All buttons below the polygon button won't be shown in this scenario. 
It could be organized in such a way that the top layer, like today, is the standard input layer, so you can enter further information there about the marker set

**Comment by yohanboniface** [comment]
This is something planned, see #584 :)

I'm closing here, as duplicate, but the needs is clear and in the radar. Just need time or PR ;)
