### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#81]
Originally reported by: **BitBucket: [almereyda](http://bitbucket.org/almereyda), GitHub: [almereyda](http://github.com/almereyda)**

---

The documentation of uMap is rather poor or nonexisting.
Which clusters need to be covered?

So far I can identify:
- API (via GeoDjango)
- Installation (Development / Bare Metal)
- Deployment (Docker, Ansible, Cloud examples?)
- Contribution Guide
- End-user/Frontend help

Sources of information currently are:
- http://wiki.openstreetmap.org/wiki/UMap
- Readme.rst

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/81

**Comment by thoka** [comment]
How about moving the install docs to the wiki and let the crowd improve it ?
