### ISSUE TITLE
Embed does not work with Firefox

### ISSUE THREAD

**Issue by debyos** [umap-project/umap#814]
Dear All,

if I embed a map, it can be viewed woth both Google Chrome and MS Edge, however, it does not work with Firefox.

E.g. if you have a look [on the website of this journey](https://www.pannonpilgrim.hu/trip/egyeni-gyalogos-zarandoklat-szent-erzsebet-ut-zemplen/) by clicking the "Térkép" tab below, you can/cannot see an embedded [Umap map](https://umap.openstreetmap.fr/hu/map/szent-erzsebet-ut_293425), depending on the browser you use.

Do you have some idea what could be done to let it work also with Firefox?
Thanks

Gábor

**Comment by Binnette** [comment]
Hi @debyos,

Ok i got it, there is an encoding error in the "src" tag of your iframe:

![image](https://user-images.githubusercontent.com/6597721/86212065-ac091480-bb77-11ea-8d89-dff2a27dbdea.png)

Each `&amp;` must be replaced by a standard `&`.

BTW when I edit the `src` tag with Firefox debugger (and add some whitespace at the end of the url). Firefox kindly replace  `&amp;` by `&` and then your map in working nicely.

![image](https://user-images.githubusercontent.com/6597721/86212262-fdb19f00-bb77-11ea-8020-8a508e0c3a95.png)

**Comment by debyos** [comment]
Dear @Binnette,

it's great, thank you. However, how could I convince Firefox not to convert `&` to `&amp;`. 
When I code it, they are all OK, and also other browsers do not convert them.
So, what should I do?

Thanks

Gábor

**Comment by davidbgk** [comment]
This is not anymore an issue related to umap.
