### ISSUE TITLE
Install on Ubuntu 18.04 LTS from scratch is not working

### ISSUE THREAD

**Issue by Paris999** [umap-project/umap#816]
Dear Developer,

I tried to install umap on a Ubuntu Server 18.04 LTS from scratch.
First the System dependency or packets not available, thal all will be installed this command would be work:
`sudo apt install build-essential autoconf python3.8 python3.8-dev python-virtualenv wget nginx uwsgi uwsgi-plugin-python3 postgresql-10 postgresql-server-dev-10 postgresql-10-postgis-2.4 git libxml2-dev libxslt1-dev zlib1g-dev`

But than I stuck on another Part I am not able to activate the virtualenv with this command:
`source /srv/umap/venv/bin/activate`

I always get the Error: `-sh: 2: source: not found`

Is it possible you check the Installation routine on the documentation, that it is working with the actual versions.

Thanks
Paris

**Comment by H-LK** [comment]
Installed today with 20.04 LTS - Python 3.8.2 is already installed - (check with: `python3` )

Changes:
`sudo apt install postgresql-all postgresql-12-postgis-3 virtualenv`

`virtualenv /srv/umap/venv --python=/usr/bin/python3.8`
`. /srv/umap/venv/bin/activate`

**Comment by yohanboniface** [comment]
Closing as old, please reopen if help is still needed.
