### ISSUE TITLE
Add coalesce function in Popup content template

### ISSUE THREAD

**Issue by sfkeller** [umap-project/umap#820]
Often attributes can be NULL but for display purposes one wants to show "0" or another value (like "-").

Proposal: Add a coalesce function in "Popup content template" which returns the first non-NULL value from the parameter list, similar to QGIS or PostgreSQL.

**Comment by sfkeller** [comment]
Here's a use case of a template, where the attribute/value of ele isn't always set:

    # {name} ({ele} m ü. M.)

=> shows: Piz Signina ( m ü. M.)

This is the proposal:

    # {name} (coalesce({ele},'-') m ü. M.)

=> shows: Piz Signina (- m ü. M.)

**Comment by das-g** [comment]
I think the syntax should be more like

    # {name} ({coalesce(ele,'-')} m ü. M.)

or maybe something more compact like

    # {name} ({ele|'-'} m ü. M.)

**Comment by Binnette** [comment]
Sorry, i don't get it. Can you add a screenshot of the issue?

**Comment by yohanboniface** [comment]
As I understand it, the need is to display a fallback value when a template variable points to an empty value.

The uMap templating system (to say a big word) is very minimal (because uMap is targetted as users without tech skills), and I'm not sure it's feasable without adding a lot of complexity, but I'll have a look.

**Comment by das-g** [comment]
> As I understand it, the need is to display a fallback value when a template variable points to an empty value.

Exactly. For a quick grasp of SQL's `COALESCE` feature that @sfkeller referred to, see [this tweet](https://twitter.com/b0rk/status/1181201631557357568) by @jvns. To quote from that tweet:

> `COALESCE` is a SQL function that returns the first argument you give it that isn't `NULL`
> 
> `COALESCE(NULL, 1, 2)` &rarr; `1`
> `COALESCE(NULL, 'hi')` &rarr; `'hi'`
> `COALESCE(4, NULL, 2)` &rarr; `4`

Importantly, it allows specifying not only hard-coded fallback values, but also fallback columns (or more generally, fallback expressions). This is something we might want for a corresponding feature in the uMap "templating system", too, e.g.

* if `ele` is `NULL`, use `0` instead
* if `ele` is `NULL`, use `'-'` instead

(hard-coded fallback value)

but also

* if `addr_street` is `NULL`, use `addr_place` instead

(lookup in an alternative fallback column)

**Comment by yohanboniface** [comment]
I've made a proposal in this direction:

`{key|fallbackkey|"fallbackstring"}`

It's not released yet. And I've not documented it yet, so we can do some tests before.

**Comment by yohanboniface** [comment]
Released. Please test and give feedback :)

**Comment by tportier** [comment]
Hi,

I tried to use this feature but it seems that it doesn't work. Can you confirm ?

Thank you

**Comment by tportier** [comment]
In this map : https://umap.openstreetmap.fr/fr/map/zones-humides_1021804#15/42.6706/2.1895
For the layer "Zones humides disposant d'un plan de gestion"
The template of the popup is set up as : 
```
# Zones humides disposant d'un plan de gestion
# {nom_zh|n_compx|""}
{nom_zh}
{n_compx}
Code : {id_zh}
Plan de gestion : {pgl}
```
I thought it will display the value of n_compx when nom_zh was null an nothing when both are null but it's not the case.

Thank you
