### ISSUE TITLE
Imposibilité de modifier ma carte

### ISSUE THREAD

**Issue by guys92** [umap-project/umap#822]
Bonjour
Depuis 2 jours, je ne peux plus modifier ma carte, le bouton avec le crayon pour modifier ne s'affiche plus. Est ce que vous auriez une solution pour moi?
Merci

**Comment by VigneSuisse** [comment]
Bonjour,

Même problème pour moi aujourd'hui. Avez-vous trouvé une solution depuis ? Merci

**Comment by VigneSuisse** [comment]
Du coup voici la "solution" que je viens de trouver : 
* Cliquez sur le bouton "Partager" 
Télécharger en tant que "Données cartographiques complètes". 
Cela vous donne un fichier .umap. 
Créez un nouvel umap, (cette fois ci je l'ai fait avec un compte enregistré) et avant de faire quoi que ce soit d'autre, cliquez sur "télécharger des données" et choisissez votre fichier umap.

**Comment by guys92** [comment]
Ca marche merci beaucoup!
