### ISSUE TITLE
Cannot access uMap through github login provider 

### ISSUE THREAD

**Issue by dlepenven** [umap-project/umap#823]
Hi,

When I want to login using the github provider, it returns a 404 error with the following link : 
http://umap.openstreetmap.fr/complete/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=nA6k0JBlEzjzmhajX1wmzJfS377WzaP4
![image](https://user-images.githubusercontent.com/1785409/92108310-771f7500-ede7-11ea-9bff-c75495330576.png)

I tried with Edge and Chrome.

Regards,

**Comment by dlepenven** [comment]
In fact it works when I choose "Openstreetmap" provider and then github :/

**Comment by yohanboniface** [comment]
I think you must use https to use Github provider, see #287
