### ISSUE TITLE
Scroll bar cuts off text

### ISSUE THREAD

**Issue by aborruso** [umap-project/umap#824]
Hi,
if you open this map and click on a point, the scroll bar cuts off text:
http://umap.openstreetmap.fr/it/map/mappa-degli-insediamenti-culturali-dell-agro-di-bi_471958

See in example the image below:

![image](https://user-images.githubusercontent.com/30607/92990305-9e5afe00-f4db-11ea-8f4a-a39a947d8831.png)

I think it's related to class "umap-popup-content",  and to "overflow-y: auto" and "overflow-x: hidden" properties.

Is there a way to solve it?

Thank you

**Comment by a-cartographer** [comment]
Hi there,
I just want to confirm that I am having the same issue as mentioned above, for multiple map pages I maintain, including:
https://umap.openstreetmap.fr/en/map/green-flag-award_382275#8

See attached image - this must affect all users?
Thanks you in advance!

![Cropped_Text1](https://user-images.githubusercontent.com/71816033/94122136-131e2880-fe4a-11ea-9f6d-feb59984f952.png)

**Comment by aborruso** [comment]
@a-cartographer I think it's in all maps, it seems a bug

**Comment by yohanboniface** [comment]
@Binnette any time slot to have a look at this by chance ? :)

With a quick look, it may just be that the width of the panel (#map-ui-container) of 400px is not enough to contain the img max-width 400px + the various margin/padding.

**Comment by a-cartographer** [comment]
Hi @yohanboniface and @Binnette, thanks for reply!
At the moment I bring in the images using a Flickr URL, that pulls the image into the panel/description.  Currently my code is simply this, which i think is just the 'simple link'-style text formatting:
[[{link_url}|{{{PICTURE}}}]]

Do you think it's better if I go with an option where i strictly define the custom px width, as in?:
Image with custom width (in px): {{http://image.url.com|width}}
?

Other than that, I assume it's not possible to directly alter the width of the panel, to make it wider?  Not sure that would solve the inherent issue anyway as all the photos i pull from Flickr are of wildly different widths/heights.
Thanks again in advance!

**Comment by yohanboniface** [comment]
Ah, gasp, this seems to be fixed by @Binnette since https://github.com/umap-project/umap/commit/8b28536bbb88cbb7b9f80965d73aa3449ef4dd58 which is not released yet!

I'll try to do a release these days.

**Comment by yohanboniface** [comment]
Fix has been released. Sorry for the delay!

**Comment by aborruso** [comment]
Thank you very much @yohanboniface
