### ISSUE TITLE
saving current center/zoom doesn't work on high frames/windows

### ISSUE THREAD

**Issue by gsilber56** [umap-project/umap#825]
Hello,
i use uMap on https://framacarte.org
I try to display my map with a saved center and zoom (https://framacarte.org/fr/map/aco-france_81627#5/29.707/47.021)
all works fine if the window or the iframe in which the map is displayed has height of about 500px
Each time i try to have a bigger height (about 900px), the saved center is lost and the map displays with #5/4.193/50.625

**Comment by Binnette** [comment]
Hi @gsilber56, can you please try to reproduce your issue on https://umap.openstreetmap.fr/en/

Have a nice day.

**Comment by gsilber56** [comment]
Hi @Binnette, i tried my umap on https://umap.openstreetmap.fr/en/ (https://umap.openstreetmap.fr/en/map/aco-france_509480) but cannot reproduce this issue. Issue is only on framacarte.

**Comment by yohanboniface** [comment]
Time has passed, sorry! @gsilber56 do you still have the issue ?
