### ISSUE TITLE
Problem with the server response when saving map

### ISSUE THREAD

**Issue by TanguyJvt** [umap-project/umap#827]
Hello,

I keep having the same issue when I try to edit then save my map.
I import new data to my map, and then every time I try to save it, it waits a few seconds and then displays the message "problem with the server response".

Could it be because there are a lot of data on my map ? (probably several hundreds of gps tracks).

Thank you for your help.

![image](https://user-images.githubusercontent.com/72264404/94933709-0ee9af00-04cb-11eb-8610-9e860d53cffa.png)

**Comment by Binnette** [comment]
I have the same issues with big data files.

**Comment by yohanboniface** [comment]
@TanguyJvt I guess yes, it may be related to the size of the data.

Can you share your map URL/id so I can have a look ?

**Comment by TanguyJvt** [comment]
@yohanboniface Thank you, this is the map url if you want to have a look : 
https://umap.openstreetmap.fr/fr/map/tanguys-sport-and-travel-map_389863#5/44.934/10.129

**Comment by pfbreton-perso** [comment]
I do have similar problems.  I have been able to reproduce it with different layers returning data from overpassAPI.

Here is the map:

http://umap.openstreetmap.fr/en/map/adv-gravel-roads_701978

Let me know if I need to change permission levels for you to inspect the remotedataquery.

**Comment by Shohreh** [comment]
Two and a half years later, not fixed.

When saving a map, Umap sometimes redisplays all the layers that were previously hidden, and fails with that error message.

**Comment by yohanboniface** [comment]
> Two and a half years later, not fixed.

What did you do yourself to help fixing this ? :)

**Comment by Shohreh** [comment]
I would if I had the skills.

**Comment by yohanboniface** [comment]
> I would if I had the skills.

Same for me :)

**Comment by Shohreh** [comment]
Who wrote Umap?

**Comment by yohanboniface** [comment]
Mainly me ;)

**Comment by yohanboniface** [comment]
The initial issue was about error **when saving the map**. I guess this was because of the number of layers. @TanguyJvt please reopen if this issue is still a problem for you.

Others: please open another issue with your specific case if you have one.

**Comment by IgnacioHeredia** [comment]
In case this helps someone, [simplifying the tracks](https://gis.stackexchange.com/a/194435) helped me.
```bash
sudo apt install gdal-bin
ogr2ogr -f KML -simplify 0.0001 outfile.kml infile.kml
```
After the simplification files went from 50MB to 5 MB, and after importing the new data, I could successfully save the map.
