### ISSUE TITLE
Demande d'améliorations

### ISSUE THREAD

**Issue by LeGhe59** [umap-project/umap#828]
Bonjour,

je découvre umap et aimerai poser quelques questions après de longues et vaines recherches, pour améliorer ma carte et la conformer à mes besoins (https://umap.openstreetmap.fr/fr/map/no ... .000/2.000) :

- Possibilité de "figer" le volet de droite ?
- D'y inclure en permanence la "loupe" de recherche dans mes données ?
- De modifier les textes, genre "visualiser mes données" ?
- De modifier les marqueurs type "gouttes" par ceux que je désire (pas l’icône dans le marqueur, mais le marqueur lui-même ?
- De modifier le CSS (ou des balises) pour jouer sur les couleurs, opacités, justifier les textes, etc... ?
- De nommer les clusters, en plus du nombre de "points" représentés ?
- D'afficher un itinéraire ou un polygone au survol ou au clic de certains marqueurs ?
- D'importer plusieurs calques à la fois ?

Beaucoup de questions, je sais... Mais cet outil me plaît par sa facilité d'utilisation.

Merci de votre attention en tous les cas ;-)

Gérard

**Comment by Binnette** [comment]
Hi, can you please have a look to the documentation?
- https://wiki.openstreetmap.org/wiki/UMap
- https://wiki.openstreetmap.org/wiki/UMap/Guide

Have a nice day

**Comment by LeGhe59** [comment]
I read ALL the documentation, but, unfortunately, nothing answers to my questions…

 

 

Librairie Autour du Monde

65 rue Pierre Mauroy

59800 LILLE

03.20.78.19.33

 <https://www.facebook.com/autourdumonde.lille> 

 

De : Binnette [mailto:notifications@github.com] 
Envoyé : samedi 10 octobre 2020 17:27
À : umap-project/umap <umap@noreply.github.com>
Cc : LeGhe59 <gerard@autourdumonde.biz>; Author <author@noreply.github.com>
Objet : Re: [umap-project/umap] Demande d'améliorations (#828)

 

Hi, can you please have a look to the documentation?

*	https://wiki.openstreetmap.org/wiki/UMap
*	https://wiki.openstreetmap.org/wiki/UMap/Guide

Have a nice day
