### ISSUE TITLE
map language

### ISSUE THREAD

**Issue by francescosoave** [umap-project/umap#829]
Hi, why the location names are in french even when accessing the website through other languages?
For example at [this link](https://umap.openstreetmap.fr/en/map/new/#7/50.212/1.450) I'd expect the places and locations to be named in English or when creating a map from [this link](https://umap.openstreetmap.fr/it/ ) in italian, not in french as it seems to be now

**Comment by Binnette** [comment]
Hi @francescosoave , it depends on the selected layer :)

![image](https://user-images.githubusercontent.com/6597721/95658626-24d71f80-0b1c-11eb-9d63-9ce5c202e67f.png)

**Comment by Binnette** [comment]
Close this bug when appropriate :+1:
