### ISSUE TITLE
Hide layer at the start 

### ISSUE THREAD

**Issue by robibrazze** [umap-project/umap#831]
Hi,
is it possible hide layer in this config? 
"Do you want to display a panel on load? Caption"
When i open the map i would like to see the layer Frana hidden

Thanks 
Roberto
![image](https://user-images.githubusercontent.com/28442671/96604584-91f56c80-12f5-11eb-8fc8-24117099e967.png)

**Comment by yohanboniface** [comment]
When editing a layer, you should see a checkbox "Display on load" or something like that depending on the language :)

**Comment by robibrazze** [comment]
Hi,
i know this checkbox but i would like see the layer (the text) when i open the map at the start. If i check "Display on load" > off when i open the map the layer disappared.
Perhaps by installing umap on your own server this option is feasible

**Comment by theraser** [comment]
You can show the layer again if you enable the datalayers control (use "&datalayersControl=true" in your map address) and then click on the database symbol and the strikethrough eye for your layer.

**Comment by yohanboniface** [comment]
You can unclick "Data is browsable":

![image](https://user-images.githubusercontent.com/146023/98461956-da939d80-21b0-11eb-929a-032e89cc068f.png)

This will make the layer disappear from every listing.
