### ISSUE TITLE
disable link at the owner of the map

### ISSUE THREAD

**Issue by robibrazze** [umap-project/umap#832]
Hi,
when installing umap on my server 1) is it possible disable the link at the owner of the map by ........ , or erase this element?
thanks

Roberto

1) https://umap-project.readthedocs.io/en/latest/install/

![image](https://user-images.githubusercontent.com/28442671/97452500-19199480-1935-11eb-9b75-07b98220c567.png)

**Comment by yohanboniface** [comment]
It's not possible from configuration, but given you own the server, you can add a [custom style](https://umap-project.readthedocs.io/en/latest/custom/) with this rule:

```css
.umap-map-owner {
    display: none;
}
```
