### ISSUE TITLE
map editors

### ISSUE THREAD

**Issue by tanguytomes** [umap-project/umap#833]
Hello! 

On uMap I am the owner of a map called Beaver Database v0.10. I am looking to make another user (kernowbeaver) an editor of this map but when I type it into the "map's editors" box no results come up... Any ideas on how I can allow that user editing access but not the general public?

Thanks, 

Tanguy

**Comment by yohanboniface** [comment]
Hi, I don't see any user with name "kernowbeaver". Are you sure of the typing ?

**Comment by tanguytomes** [comment]
yes i've double-checked with the person who made it and they are sure. I believe they created the account on 30 Oct.

**Comment by yohanboniface** [comment]
I really think there is some mistake somewhere, see for example the page of my public maps:

https://umap.openstreetmap.fr/fr/user/ybon/

But there is not such page for the user `kernowbeaver` as is does not seem to exist:

https://umap.openstreetmap.fr/fr/user/kernowbeaver/

Can you double double triple check ? :)

**Comment by tanguytomes** [comment]
Ahah, thank you for that idea of searching usernames by way of URL! Turns out the person has made an openstreetmap account but not a umap account. Hopefully should be able to proceed from ehre on out. Thank you for your help :)

**Comment by yohanboniface** [comment]
Cool :)
