### ISSUE TITLE
Display distance while drawing lines

### ISSUE THREAD

**Issue by Cyrille37** [umap-project/umap#834]
Hello
Thanks for that so great tool !

It should be nice to display length (aka distance) of lines while drawing them. Like there is a "distance" tool and a "line" drawing tool it should be not so hard to implements ?

Regards & Cheers

**Comment by yohanboniface** [comment]
Nice suggestion. I'll keep open, but I've no time to work on this now.

**Comment by oli44** [comment]
Would be much appreciated: how can I go for a daily walk inside a 1km radius around my house?

**Comment by woodpeck** [comment]
@yohanboniface I would like to build this feature into umap and make a pull request for it. Is umap.openstreetmap.fr running the current Github version of umap so that the change would then end up there at some point, or are you running a fork of some kind?

**Comment by yohanboniface** [comment]
Hi @woodpeck :)

It's running the latest release, not the current master, but new release is in process. 

The new release in this case depends on a server upgrade to have a newer python, so it's not as simple as "pip install", so I'm unable to give an idea of when it will occur, but let's say "soon", cc @cquest :)

**Comment by yohanboniface** [comment]
Sounds like a good step forward to me, thanks!

About the translation, one other option would have been to keep the variable out of the translated string: `L._("blaba bla") + "(" + distance + ")"` (that does not allow for translators to move the variable in the sentence, but may be enough as a first step).

Anyway, given you have already make the effort to update each string, we could also proceed as is :)

So, yeah, let's put that in a PR! :+1:
