### ISSUE TITLE
Popup content template: "id"-value has additional content, "type" is empty

### ISSUE THREAD

**Issue by theraser** [umap-project/umap#837]
I'm not sure if this is a bug or feature:

I'm using remote data from Overpass Turbo (which works perfectly fine) and I'm using it for popup content. This works for most of the available fields, but not all: {id} also includes a "node/"-part in front of the real id (i.e. {id} is resolved as "node/7639975011"). The field "type" is available from Overpass Turbo, but empty when accessed using {type}.

All other fields (i.e. "lat", "lon", "source", "inscription") are working fine.

Is there a way to get **only** the id of the current item without the "node/"-part?

[Example data query](https://overpass-api.de/api/interpreter?data=[out:json][timeout:25];area(3600062400)-%3E.searchArea;(node[%22memorial%22=%22ghost_bike%22](area.searchArea););out%20body;%3E;out%20skel%20qt;)

**Comment by yohanboniface** [comment]
Overpass data is converted to geojson by [osmtogeojson](https://github.com/tyrasd/osmtogeojson/issues/2) plugin.

The `id` value is made from `type` and `id` values, to make sure it's a *unique* identifier, given in OSM node and way does not share the same ids.

That said, I don't think there is a (simple) way to work around this.

Closing as I don't think there is any action possible on uMap side, but please feel free to continue the discussion and to reopen if you think I'm wrong.
