### ISSUE TITLE
Pillow and python3.9

### ISSUE THREAD

**Issue by mmeinert** [umap-project/umap#840]
Current version of Ubuntu (20.04) LTS ships with Python3.9

`pip install umap-project` tries to compile Pillow-6.2.2.tar.gz which is [not compatible with 3.9](https://pillow.readthedocs.io/en/latest/installation.html)
Is it possible to use Pillow >= 8.0 ?

[Gist's log](https://gist.github.com/mmeinert/ba9b230203182d79862e49a9a34a7476)

Made PR #839

**Comment by yohanboniface** [comment]
Merged, thanks!
