### ISSUE TITLE
All roads lead to Rome …

### ISSUE THREAD

**Issue by vonneudeck** [umap-project/umap#841]
… or in this case to Paris.

If one creates a map on https://umap.openstreetmap.fr and loads it without giving explicit coordinates, it will always centre Paris.
Even if that means that the actual self created content is not visible.

Here are examples:
https://umap.openstreetmap.fr/en/map/test_520174 (Data is drawn on Svalbard)
https://umap.openstreetmap.fr/en/map/test_520178 (Data is drawn on Singapore)

Hence one has to add values, which is a) cumbersome and b) error-prone considering that many people embed iframes on websites with responsive design. So it becomes not just a usability but also an accessibility issue for people with devices who differ from the map creator’s.

It would be more useful if the software by default would pick the position and and zoom level so that the content added by the map creator would be visible. Paris is lovely, but most people use maps to show what *they* drew on it.

**Comment by yohanboniface** [comment]
Hey, thanks for this feedback.

Have you tried changing the default center when editing the map, by clicking on the "center map" button ? 

![image](https://user-images.githubusercontent.com/146023/98460363-0f4d2800-21a4-11eb-9099-b4025bc82217.png)

**Comment by vonneudeck** [comment]
No, thank you. I didn’t know it existed. Must have overlooked it in the documentation. Sorry about that.
I still think it would be a good default behaviour to centre on the content added by the map author.

**Comment by yohanboniface** [comment]
> I still think it would be a good default behaviour to centre on the content added by the map author and set the zoom dynamically so it will fit the content on every device

It's not that easy. I agree that keeping default map extent if user does not explicitly change it is a poor default, but:

- we don't want to change the default extent of the map if it has been set by the user
- we only can try to act at save time to set a better default, and thus only at first map save ever
- at this moment, we have no idea if the current map extent makes sense or not, and we cannot be sure all the map data is loaded to compute the data extent

So until now I've considered better not to try instead of setting a meaningless extent on behalf of the user. But as an experiment I've changed it: starting next release, we'll keep the current extent of the map at first save, if user hasn't changed it yet.

Let's see out it goes. And thanks any way for challenging the status quo :)

**Comment by vonneudeck** [comment]
> It's not that easy. I agree that keeping default map extent if user does not explicitly change it is a poor default, but:

I know. It rarely is.
 
>     * we don't want to change the default extent of the map if it has been set by the user

*If* it has been set. There can be a button to unset it.
 
>     * we only can try to act at save time to set a better default, and thus only at first map save ever

Why? We can recalculate everytime the map is saved. That does not sound like a big deal.

>     * at this moment, we have no idea if the current map extent makes sense or not, and we cannot be sure all the map data is loaded to compute the data extent

We know it when people save the map. And we definitely know it when the map is loaded from elsewhere in an iframe.

> So until now I've considered better not to try instead of setting a meaningless extent on behalf of the user. But as an experiment I've changed it: starting next release, we'll keep the current extent of the map at first save, if user hasn't changed it yet.

An edit view is not the same as a consumption view. Hence I would calculate the extent of the map when the data elements are known. I would not try to guess so much from map creator behaviour. Map creators who want that fine grained control will set everything themselves anyway.
 
> Let's see out it goes. And thanks any way for challenging the status quo :)

You are very welcome. And as you can read I am not yet done challenging : )
