### ISSUE TITLE
address search does not work anymore...

### ISSUE THREAD

**Issue by cquest** [umap-project/umap#842]
photon leaflet plugin uses an outdated URL for the geocoding API

https://photon.komoot.de/api/?

It should be replaced by:

https://photon.komoot.io/api/?

A 301 redirect is sent, but does not seem to work.

**Comment by yohanboniface** [comment]
> A 301 redirect is sent, but does not seem to work.

CORS headers seems to be missing.

@lonvia any idea who to ping to add those by chance ? :)

I'll fix the URL anyway, but it's controlled by [leaflet-photon](https://github.com/komoot/leaflet.photon/blob/master/leaflet.photon.js#L56) plugin, not by uMap itself (it's configurable, but uMap does not control it atm, I'll fix that).

**Comment by lonvia** [comment]
> CORS headers seems to be missing.

This needs fixing on Komoot's side. I've pinged them.

In any case, switching to photon.komoot.io is definitely the way to go.

**Comment by yohanboniface** [comment]
> This needs fixing on Komoot's side. I've pinged them.

Thanks :)

> In any case, switching to photon.komoot.io is definitely the way to go.

Done. Release on its way :)

**Comment by yohanboniface** [comment]
Released :)
