### ISSUE TITLE
Map or layer update time

### ISSUE THREAD

**Issue by cascafico** [umap-project/umap#843]
Hello,

I wonder if there is a variable I can get in a "mustaches" placeholder which defines time/date of map/layer last update.

**Comment by yohanboniface** [comment]
Nope.
Usually, "mustaches" variables are contextual to a map feature (i.e. a point, a line…).
Maybe this information should be displayed on the caption and/or caption bar ?

**Comment by cascafico** [comment]
> Maybe this information should be displayed on the caption and/or caption bar?

Sorry, I badly explained my case.

[My umap](http://umap.openstreetmap.fr/en/map/covid-nelle-scuole-fvg_509775) is feeded by   remote csv files; each map feature has an update date field, which I can display in pop-ups.

Is it possible to access one of the map features update date and display it in map and/or layer caption?

**Comment by davidbgk** [comment]
Sorry, but this very specific feature is not a priority given the time we have.
