### ISSUE TITLE
Adjust the Attribution leaflet

### ISSUE THREAD

**Issue by SinimRocky** [umap-project/umap#844]
On an iPhone7 in Safari, the little box in the bottom right corner "Data © OpenStreetMap Contributors, map style provided by FOSSGIS e.V..." is way too large and obtrudes the view. (It's even worse on Opera)

I'd propose shortening the text and maybe downsize the font a bit.

**Comment by yohanboniface** [comment]
Can you share a screenshot ?

The displayed text may be constrained by legal issues (eg. https://www.openstreetmap.org/copyright/en), but maybe at some screen size we may hide the box and only display a "copyright" link that toggle the visibility of this box.

**Comment by SinimRocky** [comment]
Yes of course 
![IMG_8586](https://user-images.githubusercontent.com/57175557/98694193-74a24400-2371-11eb-9e9d-c81ba26af6a8.PNG)
![IMG_8587](https://user-images.githubusercontent.com/57175557/98694197-75d37100-2371-11eb-839a-0eaa8853a744.PNG)
![IMG_8585](https://user-images.githubusercontent.com/57175557/98694200-766c0780-2371-11eb-887d-8f47e6b7b792.PNG)

**Comment by davidbgk** [comment]
A small phone in landscape mode does need a responsive adaptation.

**Comment by davidbgk** [comment]
It happens because some maps have very long attribution strings:

<img width="582" alt="Capture d’écran, le 2023-05-18 à 13 22 42" src="https://github.com/umap-project/umap/assets/3556/5f16c17f-4112-4225-ab62-805e8b250548">

You can hardly fit that into a single line on a small screen 🤷

**Comment by yohanboniface** [comment]
Maybe in a small screen display only a small <i> clickable that would then extend the full attribution text ?
