### ISSUE TITLE
Log-In via GitHub fails with 404 because the redirect URI does not match the registered callback URL

### ISSUE THREAD

**Issue by vonneudeck** [umap-project/umap#846]
When I try to log in via Github I get a 404 with this beautiful speaking URI

http://umap.openstreetmap.fr/complete/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=uV2F28VIreaQnh51EpkB8Dxmj7wlyf3Z

It works if I visit umap without TLS.
How about enforcing https? It is anyway what should be done.

**Comment by donalhunt** [comment]
I just got bitten by this too. I had created some maps using my github account and couldn't figure out how to login to it.

I suspect the config for github auth is broken (assumes http and fails for https).

This is the URL I get sent to:

`http://umap.openstreetmap.fr/complete/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=igYXxodyWeEvbpiYB3pqtG0nCX6eXBIP`

**Comment by donalhunt** [comment]
This is probably a misconfiguration on the github side (only supports redirects to the http url) and needs to be resolved by the service owner.

flow is:

1. https://umap.openstreetmap.fr/login/github/
1. https://github.com/login/oauth/authorize?client_id=XXXXXX&redirect_uri=https://umap.openstreetmap.fr/complete/github/&state=XXXX&response_type=code&scope=user:email
1. http://umap.openstreetmap.fr/complete/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=XXXXXXX

**Comment by donalhunt** [comment]
https://github.com/omab/django-social-auth/issues/600 seems to be a very similar issue but is over 8 years old.

**Comment by Wikinaut** [comment]
Stupid bug. I cannot login into my account.

**Comment by TheTechRobo** [comment]
Still got this problem. I can no longer loginto my account.

**Comment by davidbgk** [comment]
We have modified the app on the Github side to handle the HTTPS. 🎉

**Comment by Wikinaut** [comment]
Finally it works.

**Comment by donalhunt** [comment]
There are different issues now. I will file new issues since they are different to this one. 😥

**Comment by yohanboniface** [comment]
For what I can see, we have the opposite issue: it only work when umap is https now, and does not work when it's http. Certainly time to force https everywhere, but [#205 and #594](https://github.com/umap-project/umap/issues/594#issuecomment-420625781) …
