### ISSUE TITLE
Images don't load with chrome

### ISSUE THREAD

**Issue by marcbertholet** [umap-project/umap#848]
Hi!

I work on a an interactive medieval map of my town. The project is here : https://umap.osm.ch/fr/map/vevey-au-moyen-age_2787#17/46.45952/6.84725

Unfortunately, it appears that the images of the project (icons, images in popup windows, ...) doesn't load when using the chrome navigator. It works with firefox...

I don't have the knowledge to understand the problem.... 

Have you any advises?

Thank you very much!!!

**Comment by yohanboniface** [comment]
Seems like the links are in "http" (unsecure) while you load the page in "https" (secure), so the solution would be to load the links in https

**Comment by robibrazze** [comment]
Hi, i'm not sure but probabli your link at the photo is not correct 
https://www.reclus.org/cartes/moyenage/icones/718905_horror_512x512.png

**Comment by marcbertholet** [comment]
Thank you! For most of my images, the links are correct. I will look for the https / http issue... I think the problem must be with the site www.reclus.org where I stock my images. Because with images located elswhere, it works!

**Comment by Lukas458** [comment]
Hello, i have a maybe similar problem, namely, some of my photos often load blurry. Even if I emptied the image cache in the browser. Both umap and image link are https. Maybe someone knows what could be the reason?

Example: On https://umap.openstreetmap.fr/de/map/telefonzellen-in-essen-auch-ehemalige-offentliches_372368#19/51.45369/6.97987 click on the square icon with the blue background. On the embedded image (maybe you need to scroll down a bit to see it), the writing should actually be **sharp** with the text "Am Westbahnhof 1". I see them in the browser but often **blurred**. Only slightly, but still. It semems that my brwoser doesn't load the image in its complete quality? The zoom is always set to normal at 100%.

The problem occurs with Chrome, in MS edge the images often do not load at all.

Maybe someone can give me a tip about this problem? that would be great. Thanks very much!
