### ISSUE TITLE
castom text in the bottom "About"

### ISSUE THREAD

**Issue by robibrazze** [umap-project/umap#849]
Hi,
i have installing umap in local on ubunto whit this guide https://umap-project.readthedocs.io/en/latest/ubuntu/ and it work fine.

I would like customize my umap style and in particular i would like change the test and the color at botton " About".
When find the code for this element?

Thanks 

Roberto

**Comment by davidbgk** [comment]
Hi @robibrazze 

You'll have to target `.leaflet-control-attribution.leaflet-control a` in your theme CSS as [documented here](https://umap-project.readthedocs.io/en/latest/custom/).

Hope it helps!
