### ISSUE TITLE
Wish: versions shown with timestamp

### ISSUE THREAD

**Issue by Spielmops** [umap-project/umap#852]
I wish, I could see, at what time a version has been stored and I could see the different version as "date-time (kByte)". 
Normally I create several versions within a session, so the versions have all the same date and a different time, but I can not tell them apart, because the time is not shown.

Spielmops

**Comment by yohanboniface** [comment]
Makes sense, I'll do!

**Comment by Spielmops** [comment]
Perhaps it helps, if I tell the problem more clearly:

If I change the storage-path of the app into

`/data/user/0/com.nextcloud.client/files `

as offered from the app, I should find the files here (if I’m the only user)

`/internal_storage/com.netxtcloud.client/files`

but instead the files are here:

`/data/data/com.nextcloud.client/files`

and a) this is not the offered location and b) you have no access to this location at least up to Android 9. Any advice, what to do?

Spielmops

Additional info:
the real problem ist, that normal users do not locate their files, because they are in
`/internal_storage/Android/data/com.nextcloud.client/files/`
They do not normally use the "Android"-folder. It would be better, if the nextcloud-folder would be in the root of "internal_storage" or "sd-card" or similar, that is
`/internal_storage/com.nextcloud.client/files/
Best would be:
`internal_storage/Nextcloud/`

`

**Comment by Spielmops** [comment]
Sad ...

**Comment by yohanboniface** [comment]
Seems to be the case

![image](https://github.com/umap-project/umap/assets/146023/8650aa57-2f43-4a78-a358-096482275ece)

**Comment by yohanboniface** [comment]
Ah no, sorry, you meant to have the time too, sorry.

**Comment by Spielmops** [comment]
Thank you all for this wish to come true. 

Spielmops
