### ISSUE TITLE
Assing pin color through table parameter (column)

### ISSUE THREAD

**Issue by guaspito** [umap-project/umap#858]
When using tables and remote csv sources, in umap it is possible to define name, description and pin icon selecting the table column/field: {name}, {description}, {icon_url}. 

It would be nice if were possibile to select the color of pins of a layer defining an appropriate table field (containing color names or codes) ad recalling it in the map configuration as we do for name, description and pin_icon (see image)

![umap_color_field](https://user-images.githubusercontent.com/5469846/101434536-023e6880-390b-11eb-9315-a6fac1d762e4.png)

This feature allows to have pins of different colors belonging to the same layer, as requested here #818

**Comment by yohanboniface** [comment]
Will be in next release.
