### ISSUE TITLE
certificate on umap.openstreetmap.co is expired

### ISSUE THREAD

**Issue by tbuijsro** [umap-project/umap#864]
I can't open the site because the certificate expired on january 2, 2021.
Who can fix this?

**Comment by carlbacker** [comment]
#### Hi @tbuijsro and welcome to uMap and GitHub! :open_hands: :world_map: 

This repo is only for the application source code, that in turn can be installed by anyone on their own server. (More info on different instances can be found [here](https://wiki.openstreetmap.org/wiki/uMap#Instances))

The domain you refer to is maintained by _OSM Colombia_ including the certificate. I suggest you contact them directly:
[Webpage](https://fosm.openstreetmap.co) (with the same cert warning) - [FB](https://www.facebook.com/groups/OsmCol/) - [Twitter](https://twitter.com/OpenStreetMapCo) - [Email](mailto:info@openstreetmap.co)

**UNSAFE OPTION**: Many browsers also allow to bypass the warning about an invalid certificate, something like clicking `Advanced` and then `Continue to ...` will get you there. But remember this may be unsafe and should only be done very carefully.

**Comment by tbuijsro** [comment]
Hi @carlbacker,
Thankx. I used the unsafe option to access my map and transferred it to the french instance.
