### ISSUE TITLE
Efficient browser caching

### ISSUE THREAD

**Issue by radex02** [umap-project/umap#867]
I have an embed of an umap on my website and I noticed there is no Cache-Control header on any of those requests:

- https://umap.openstreetmap.fr/static/CACHE/js/output.100e48f39fe9.js
- https://umap.openstreetmap.fr/static/CACHE/js/output.759f75ec46f7.js
- https://umap.openstreetmap.fr/static/CACHE/css/output.cf8c34d27c07.css
- https://umap.openstreetmap.fr/static/umap/font/FiraSans-LightItalic.woff2?ec55a7807348
- https://umap.openstreetmap.fr/static/umap/font/FiraSans-Light.woff2?ec55a7807348
- https://umap.openstreetmap.fr/static/umap/locale/fr.js
- https://umap.openstreetmap.fr/static/umap/img/16-white.png?ec55a7807348
- https://umap.openstreetmap.fr/static/umap/vendors/fullscreen/fullscreen.png?ec55a7807348

Why is this and can it be changed ?

**Comment by radex02** [comment]
I also just noticed none of those requests are compressed either with gzip or brotli

**Comment by davidbgk** [comment]
Thanks to @jocelynj it's now done on the OSMfr instance 🎉 

https://www.webpagetest.org/video/compare.php?tests=230628_AiDcHA_C6B,230627_AiDcKF_9A4
