### ISSUE TITLE
Support overlay tile layers

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#87]
Originally reported by: **Anonymous**

---

Currently it seems as if it is not possible to overlay a (transparent) tile layer over the base layer. Example at hand: overlay a separate label language specific layer over a language neutral base layer.

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/87

**Comment by krisanselmo** [comment]
Hi,
I was looking on how to add a transparent tile layer over my umap and I found this discussion. 
Maybe it's still not on your priorities but this new feature could be interesting by overlying maps with strava heatmap: http://wiki.openstreetmap.org/wiki/Strava

Cheers,
Kris
