### ISSUE TITLE
Installation problem: my server try to reach several IP addresses

### ISSUE THREAD

**Issue by robibrazze** [umap-project/umap#871]
Hi,
i installed umap on my server cloud Hetzner and it work but fine  when i start the demo, but my server try to reach several IP addresses on different ports.
I have received numerous abuse messages from hetzner confirming calls from my server to different ip addresses.
Has this happened to anyone? How can it be solved? I think it's a uwsgi problem but I don't know which one.

thanks a lot
Roberto
![image](https://user-images.githubusercontent.com/28442671/105053383-23998500-5a71-11eb-9986-91033daf2b04.png)

**Comment by yohanboniface** [comment]
Sorry @robibrazze to not answer before. Did you finally find the guilty ? Do you still need help ?
