### ISSUE TITLE
Anonymous edit link cannot be access afterwards

### ISSUE THREAD

**Issue by debuglevel** [umap-project/umap#872]
I recently created a map without an account, which worked fine! :-) But the only time I saw the "hey, here is the anonymous edit link: http://..." was in a short popup. After that, I did not find any possibility to retrieve this link again.

On the other hand, the "key" button does not do anything when I click it:
![image](https://user-images.githubusercontent.com/2401265/105226443-48b8f100-5b60-11eb-96f6-cc2717b7db06.png)
Based on its tooltip, I had guessed to find the functionality described aboved there :)

**Comment by debuglevel** [comment]
I just tried to click this button with an account; it seems not to work right now :)
![image](https://user-images.githubusercontent.com/2401265/105319904-cd8a2600-5bc5-11eb-94e6-09e60b6ab2f4.png)

**Comment by yohanboniface** [comment]
Yes, that's a clear UX issue. We'll work on this soon. Closing this, as we'll follow this on this other issue #713
