### ISSUE TITLE
Umap background image repeated problem .

### ISSUE THREAD

**Issue by manosmagar** [umap-project/umap#875]
hi ,

i have a background images repeated problem in umap
this is my background images url (http://localhost:81/umap\images.png)
if you know how to solve this problem please tall me.

Thanks you!

**Comment by guaspito** [comment]
Hello, if you need to set a specific background you have to upload the image on a tileserver. 
This is an explanation on how to do: https://forum.openstreetmap.org/viewtopic.php?id=65480

**Comment by yohanboniface** [comment]
Closing as I think it's not related to uMap. Please reopen if you think I'm wrong and you still need help! :)
