### ISSUE TITLE
Error 502 Bad gateway when trying to log in via osm account

### ISSUE THREAD

**Issue by alexanderzatko** [umap-project/umap#876]
When trying to log into umap via my osm account, I see error 502 Bad gateway. Logging in with github works.

**Comment by lakkes-ra** [comment]
Same Problem here. Can't log in with OSM Account since yesterday. 502 Bay Gateway

**Comment by Cyrille37** [comment]
Error is on url http://umap.openstreetmap.fr/login/openstreetmap/

**Comment by irgendlink** [comment]
I have the same problem with http://umap.openstreetmap.fr. Gitlogin was possible this morning. Now I get an error 404. Bitbucket and openstreetmap logins produce error 502. Only Twitter still works. But you can only get your data by using the login that you used to use. Each login method produces a new account for you. Is there a possibility to connect from twitter login to osm login?

**Comment by vivideo** [comment]
Same here. Logging in via Twitter is possible, but (of course) the french server recognizes it as an other account.

**Comment by cquest** [comment]
This is linked to an IPv6 connectivity problem on our server cluster: https://github.com/osm-fr/infrastructure/issues/262

**Comment by jocelynj** [comment]
The ipv6 connectivity to umap is now repaired, and you should be able to connect via your OSM account.

**Comment by alexanderzatko** [comment]
Yeah, I can log in now. Thank you.

It seems I can close this issue and will do so tomorrow if nobody objects.

**Comment by jocelynj** [comment]
Yes, it would be nice to close the issue: I don't have the rights to close it.

**Comment by alexanderzatko** [comment]
thanks again.
