### ISSUE TITLE
Zoom - after entering city name

### ISSUE THREAD

**Issue by agasad** [umap-project/umap#878]
Hi All!

Is it possible to make lower level of zoom after entering for example city name? Now after enetring it shows the centre of city (it looks like it is 16 level of zoom) and it would be nice to see only a outline of whole city (7 level of zoom) **and then make higher zoom to see more details.**

**Comment by agasad** [comment]
Ok, I found this: https://github.com/umap-project/umap/issues/679

Bad that this is still not solved :(

**Comment by davidbgk** [comment]
Fixed in https://github.com/umap-project/umap/commit/25ab9f943c59c15eee0eb3551008dfbd692a3479
