### ISSUE TITLE
Error message "Problem in the response" after trying to save my map 

### ISSUE THREAD

**Issue by drfrangipane** [umap-project/umap#879]
Good afternoon, Hi, Hello
I've got an error message "Problem in the response" after trying to save my map containig several layers.
Could you help me please?
Is it possible to laod several choropleth maps by town of France regions  (former and new regions) in the same project?
http://umap.openstreetmap.fr/en/map/health_2020_oct20_505487
<img width="960" alt="error_message_save" src="https://user-images.githubusercontent.com/5529454/107641896-77fce280-6c74-11eb-84ba-e53359fe078a.png">

Thank you a lot for your help.
Drfrangipane

**Comment by drfrangipane** [comment]
I ve found the problem: uMap imposes limit'size! so I used mapsharper to reduce the file' size. The new question is: what is the limit 'size by file to import in uMap?

**Comment by MigraMundo** [comment]
Hi drfrangipane! 

And how did you do to solve the issue, what file are you reducing size?

**Comment by davidbgk** [comment]
> The new question is: what is the limit 'size by file to import in uMap?

It will depend on the instance/server configuration. Glad you found a way to reduce the file size!
