### ISSUE TITLE
Possible to retrieve data from KoBoToolbox API?

### ISSUE THREAD

**Issue by severinmenard** [umap-project/umap#881]
Seems it works only within a CURL command and not through a URL like Overpass: [https://support.kobotoolbox.org/api.html](https://support.kobotoolbox.org/api.html)

**Comment by yohanboniface** [comment]
Hello @severinmenard ! Hopes you're well, amigo :) 
Sorry for the very late answer, that ticket end up in a black hole! Do you still have this need ?
(And ping me next time you are in Paris :) )
