### ISSUE TITLE
Umap doesnt load my map

### ISSUE THREAD

**Issue by rhanouki** [umap-project/umap#882]
I can't access my map, even with the URL. It keeps loading but never shows the map (grey background), and I can't click on anything (like my username or "About - Browse data" at the bottom).
When I log in my umap account (through openstreetmap) I can't access my maps either. Same issue : it keeps loading and I can't click on anything. 
I usually work on Chrome but I have the same issue on Safari. And I have deleted all browser's data but nothing changed.

Thank you for your help

**Comment by yohanboniface** [comment]
hi @rhanouki sorry for the very late answer! Do you still face this issue ?
