### ISSUE TITLE
Enhancement: Define editing permissions for each layer

### ISSUE THREAD

**Issue by blef00fr** [umap-project/umap#885]
It is possible to choose _**Who can edit myUmap**_ with  **Update permissions and editors** (Key icon).
Permissions are given for the whole map.

It would be nice to be able to choose for each layer whether or not it follows the general rule.

For example, in the layer's properties, add:
- a toggle button **Permissions: Default/Owner only**
or
- a list box: **Default/Every one/Editors only**

This feature could make it possible to create a contributory map without the risk of data loss.
Furthermore it could resolves issues #52 , #387 and #471

**Comment by RalpH-himself** [comment]
Ideally also an option "owners only" in case of a list box

**Comment by RalpH-himself** [comment]
> I share the interest of this feature.
> But there is a solution by loading the layers that should not be modified from another map (remote data), on which only some editors have the write permission.

Hm, that's an idea I haven't had so far. But I guess in that case it's not possible anymore to turn on and off those layers?

**Comment by yohanboniface** [comment]
cf also #584
