### ISSUE TITLE
Install umap-error nginx

### ISSUE THREAD

**Issue by robibrazze** [umap-project/umap#888]
Hi,
i had install umap on my server and, at the end of install, when I restart whit
sudo systemctl restart uwsgi nginx
i receive this error:
See "systemctl status nginx.service" and "journalctl -xe" for details.

In addition if i see the log errorr of nginx i find thi error:
no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/sites-enabled/umap:8

I think that the problem is the config of nginx.conf; in my set up nginx is the following:
`#` the upstream component nginx needs to connect to
upstream umap {
    server unix:///srv/umap/uwsgi.sock;
}

`#` configuration of the server
server {
    `#` the port your site will be served on
    listen      80;
    listen   [::]:80;
    listen      443 ssl;
    listen   [::]:443 ssl;
    `#` the domain name it will serve for
    `#` server_name (my ip);
	    charset     utf-8;

    `#` max upload size
    client_max_body_size 5M;   # adjust to taste

    `#` Finally, send all non-media requests to the Django server.
    location / {
        uwsgi_pass  umap;
        include     /srv/umap/uwsgi_params;
    }
}

How can the problem be fixed?
thanks 

Roberto

**Comment by Paris999** [comment]
Same Problem, did you find a fix for it?
Thx Paris

**Comment by davidbgk** [comment]
@robibrazze do you still have the issue?
