### ISSUE TITLE
Umap custom-add tile layer visible only on some map

### ISSUE THREAD

**Issue by robibrazze** [umap-project/umap#892]
Hi,
It's possible modify theme.css for don't show a specific tile layer insert in the panel admin > tile layer.
For example:
I create 2 maps (maps1 and maps2);
In panel admin i insert 2 tile layer A and B;
In a maps1 i would show only the tile layer A.

If whit theme.css is not possible where find in the code the custom background whit add when edit the map on the web?

Thank

Roberto

**Comment by yohanboniface** [comment]
Hi @robibrazze not sure to fully understand your point. If you still have the need, could you give more details ? Thanks!
