### ISSUE TITLE
FR: Mapmatching gpx files

### ISSUE THREAD

**Issue by thibaultmol** [umap-project/umap#895]
I have a use case right now for this feature. The idea would be to upload the gpx to umap as you can do now, but then you can click a checkbox and it basically matches the gpx file with the nearest road segments; as shown in the image below:
![image](https://user-images.githubusercontent.com/1010226/112843490-ebcb4100-90a2-11eb-95ff-f347041bb72d.png)
(image source wikipedia https://en.wikipedia.org/wiki/Map_matching )

This is already built into the major routing engines like Graphopper etc.

(for my use case I would like to have it be a certain distance offset from the road (in the direction of the gpx file's coordinates. But that would just be a nice addition)

**Comment by yohanboniface** [comment]
No exactly the same but related to #297

**Comment by yohanboniface** [comment]
Closing here, let's track the need in #297
