### ISSUE TITLE
GPS doesn't work in iframe element

### ISSUE THREAD

**Issue by panosalevropoulos** [umap-project/umap#898]
GPS works fine on umap instances but has no effect when the map is embedded in a website with iframe.

**Comment by hugomymaps** [comment]
Hi, I have the same problem, GPS works fine on map but when the map is embedded in a website with iframe, the button doesn't work. Please, help us to fix it 😄

**Comment by yohanboniface** [comment]
Could you share a link where to reproduce the issue ?

**Comment by panosalevropoulos** [comment]
@yohanboniface https://saloni.ca/

**Comment by panosalevropoulos** [comment]
@davidbgk I added `allow="geolocation"` but it doesn't seem to work.

**Comment by davidbgk** [comment]
@panosalevropoulos did you do it on https://saloni.ca/ because I cannot see the modification?
