### ISSUE TITLE
New points in a track have no elevation

### ISSUE THREAD

**Issue by andre92160** [umap-project/umap#900]
After importation of a gpx file, I add some points to the track, then upload the new gpx file.
The new generated points have no elevation: the \<ele\> element doesn't exist for these points.
Thus the elevation' gain and loss are wrong, and also the global distance of the track (for example, when libraries like leaflet-gpx are used).

**Comment by yohanboniface** [comment]
@andre92160 how would you expect to fill the elevation for each point ? Would having an "elevation" property when editing the form work ?

Can you share a gpx example file so we can reproduce.
