### ISSUE TITLE
Merge close pins

### ISSUE THREAD

**Issue by lalejand** [umap-project/umap#901]
Depending on the zoom level, you can have several pins one above the other, and so you can't click on the one that is under another, or you even can't see it exists.
I would be nice to do a pin merge effect like in some other cartographic services where you see like a circle with a number inside showing the number of "superposed" pins. And when you click on the circle, the circle opens and shows the different merged pins.

**Comment by spaetz** [comment]
This exists when using "clustered" Layers and merges pins just fine. I suggest closing this one as fixed.
