### ISSUE TITLE
Edit old umap without account

### ISSUE THREAD

**Issue by Oliveoil74** [umap-project/umap#902]
Hi,

I can't find a way to modify a map i did without account few month ago.

http://umap.openstreetmap.fr/fr/map/nos-ateliers-et-partenaires_545984#4/18.44/55.02

I did create an account this morning and i would like to connect that map to my account.

Any idea of how i could do that if possible ?

Thank !

**Comment by yohanboniface** [comment]
Hi @Oliveoil74 , sorry for the very late answer (I've not been around for a while plus missing Github notifs). Do you still need help for this map ?
