### ISSUE TITLE
Problem opening a UMAP map

### ISSUE THREAD

**Issue by zaffo80** [umap-project/umap#904]
Good afternoon,
I'm Matteo Zaffonato, OpenStreetmap Regional Coordinator from Wikimedia Italia. After a webinar related to Umap and OpenStreetMap, an attendant made a couple of umap maps and one of them is stucked. The person told me he tried to upload some GPX tracks and probably the GPX tracks are too heavy for the umap server. Is it possible to unblock these maps?

The user page is:
https://umap.openstreetmap.fr/user/ermeskir

Thanks in advance, best regards
Matteo

**Comment by yohanboniface** [comment]
Hi Matteo, sorry for the very late answer (I've not been around for a while plus missing Github notifs). Do you still need help for those maps ?
