### ISSUE TITLE
Problem opening edit mode umap

### ISSUE THREAD

**Issue by OdiloPinder** [umap-project/umap#907]
Hi all,

I´ve created a map without an account. Now suddenly the button for editing the map has disappeared? 

https://umap.openstreetmap.fr/de/map/grundherrschaft-mariazell_582119#17/48.01653/15.99746 

Do you have an idea how to fix it

Thanks in advance,
Thomas

**Comment by davidbgk** [comment]
Hello,

As maintainers of an open-source project deployed in many locations/servers, we do not have access to the data of the instance where you created your map.

Please contact the support of your instance specifying the URL of the map, the time and the browser you used to create it, they might be able to help you. See for example the [documentation of framacarte](https://contact.framasoft.org/en/faq/#carte-lost-edit) on that topic (which might not be _your_ instance).
