### ISSUE TITLE
Login with Gmail / facebook

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#91]
Originally reported by: **Badita Florin (BitBucket: [baditaflorin](http://bitbucket.org/baditaflorin), GitHub: [baditaflorin](http://github.com/baditaflorin))**

---

Not everybody have twitter or osm account, at least in the way that i use uMap, for enabling  teams of hundred of people to share geographic information ( where they live, where they work, etc )

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/91

**Comment by amenk** [comment]
@baditaflorin Did you succeed adding facebook on your local server? If yes, can you post instructions?

**Comment by yohanboniface** [comment]
http://python-social-auth.readthedocs.org/en/latest/backends/facebook.html?highlight=facebook should help.

**Comment by amenk** [comment]
Is it enough to add those settings to the local.py it do I have to patch umap, for example to provide a Facebook logo, Db tables and such?
