### ISSUE TITLE
How to upgrade

### ISSUE THREAD

**Issue by kleper** [umap-project/umap#911]
I have this installation: https://umap.openstreetmap.co/en/ I want upgrade to the last versión, how can i do that?

Thanks.

**Comment by kleper** [comment]
Is fixed I only run this command:

pip3 install umap-project --upgrade

On my venv and is done :)

**Comment by yohanboniface** [comment]
I'd suggest to also run those two commands:

```
# For updating the db structure
umap migrate
# For updating the frontend files
umap collecstatic
```
