### ISSUE TITLE
umap import geoJSON - {"color":"Green","iconClass":"Circle"} fail

### ISSUE THREAD

**Issue by CresbyDotCom** [umap-project/umap#912]
import from a file, the color and iconClass do not over-ride the default settings of the layer. Can't see why. Any ideas anyone?
Solution is to create yet another layer for the particular data set. Not ideal but works.

     "type": "Feature",
      "properties": {
"_umap_options":{"color":"Green","iconClass":"Circle"},
        "name": "(eg) Milestone Society ID: BRE_GWRFRY01em",
        "description": "blah blah ",
        "_umap_options": {
          "iconUrl": ""
        }
      },

see http://umap.openstreetmap.fr/en/map/canal-ms_524305#10/51.7819/-3.2162

**Comment by yohanboniface** [comment]
@CresbyDotCom sorry for the late answer. I'm closing as time as passed, but please comment or reopen if you still need help!
