### ISSUE TITLE
502 Bad Gateway nginx/1.14.2 (umap.fr)

### ISSUE THREAD

**Issue by kasanova123** [umap-project/umap#921]
Hello there, since yesterday evening I can't access https://umap.openstreetmap.fr/ to move all my maps to umap.de because of the issue 502 Bad Gateway nginx/1.14.2

This error is shown by entering the url into 2 different browsers also after cleaning the cashe and website cookies. Can you access  https://umap.openstreetmap.fr/  properly?

Thank you for the great project of umap by the way, it is really a beautifull tool with endless possibilities.

**Comment by hamlet** [comment]
See https://github.com/osm-fr/infrastructure/issues/307 for technical information and follow-up.

**Comment by kasanova123** [comment]
Thank you! Now it is working well!
