### ISSUE TITLE
Adding Markers in WebApplication (PHP)

### ISSUE THREAD

**Issue by RescueAppv1** [umap-project/umap#922]
Hello everyone,
i am developing a Web Application for our local fire brigade. 
Therefore i need to add a new marker to the map in case of an emergency. 

I tried to edit the JSON File and send it via HTTP back to the Server. As i recognized, the page is saved by a Cookie.

_**Is it possible to add a Marker another Way or is it possible to get a Cookie for editing?**_

**Comment by yohanboniface** [comment]
I'm not sure uMap is a good choice for this kind of sensitive application (at least not a public instance).

If you are able to create a PHP backend, you certainly should have your own Leaflet map.

Other option is to host your own instance of uMap, and thus take control over the auth.
