### ISSUE TITLE
Ich brauche einen neuen Bearbeitungslink

### ISSUE THREAD

**Issue by KonniWe** [umap-project/umap#925]
Der Bleistift zum Bearbeiten wird mir nicht mehr angezeigt. Ich brauche einen neuen Bearbeitungslink, wurde mir gesagt.

**Comment by Dirk71** [comment]
Du kannst folgendes machen....klicke links auf das "Teilen"-Icon und exportiere die Karte komplett "Vollständige Kartendaten" und klicke dann auf "Daten herunterladen". Lege Dir eine neue Karte an und importiere die Daten. Dann hast Du Deine Karte wieder und kannst sie bearbeiten.
Generell empfehle ich unbedingt, sich einen Account anzulegen. Dann kann sowas nicht mehr passieren.

**Comment by KonniWe** [comment]
Hi,das mit dem Account habe ich gemacht. Komme aber nicht damit klar. Danke für die Info.Liebe Grüße Konni --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 11.07.21, 09:23 schrieb Dirk ***@***.***>:

   
  Du kannst folgendes machen....klicke links auf das "Teilen"-Icon und exportiere die Karte komplett "Vollständige Kartendaten" und klicke dann auf "Daten herunterladen". Lege Dir eine neue Karte an und importiere die Daten. Dann hast Du Deine Karte wieder und kannst sie bearbeiten. Generell empfehle ich unbedingt, sich einen Account anzulegen. Dann kann sowas nicht mehr passieren.

**Comment by davidbgk** [comment]
Sorry, but we cannot provide support in this language.
