### ISSUE TITLE
UMAP Sorting - Reverse Alphabetical Order

### ISSUE THREAD

**Issue by JustEasternThings** [umap-project/umap#927]
Hello,

When assigning property to "Sort Key" (ex. type), alphabetical order of other property is reversed in some layers (not in others). When assigning two properties to "Sort Key" (ex. type, name), alphabetical order of "name" is reversed in all layers. I think this might be a bug - can it be fixed?

Example: http://u.osmfr.org/m/615067/

**Comment by yohanboniface** [comment]
Seems to be OK on my latest Firefox and Chromium:

![Screenshot-20210806095605-740x1616](https://user-images.githubusercontent.com/146023/128476903-e31ae01e-a497-4456-aad8-64c871f0b1f7.png)

Or am I missing something ?

Which browser are you using ?

**Comment by JustEasternThings** [comment]
I have reproduced the issue here: http://u.osmfr.org/m/644263/
Apologies for the OK link, I filled in the type property with the names of the stations as a quick fix

I am using Chrome desktop

**Comment by yohanboniface** [comment]
ah, fun, it's still good in Firefox, but reversed in Chromium!

Let's have a look.

**Comment by yohanboniface** [comment]
Seems you are using `type` as `sortKey`:

![Screenshot-20210806122221-724x544](https://user-images.githubusercontent.com/146023/128496534-bb3a3291-1ef7-43c2-a820-1b7e4ca94e0a.png)


But the features of the first layer ("Rail Stations") do not have a `type` property, so the order is up to the browser.

**Comment by JustEasternThings** [comment]
I can confirm that when I insert a `type` property, the properties organize themselves in the right order. Thank you, I will consider this issue settled.
