### ISSUE TITLE
feature request: add option to hide more from user interface

### ISSUE THREAD

**Issue by maphouse** [umap-project/umap#930]
Under "update permissions and editors", map creators are given the ability to choose how they want their map to be modified by collaborators or the public. However, the options available to any anonymous public user are too powerful for most use-cases: most map creators who make their maps public may want the public's contributions (i.e. creating new map markers), but don't want the public to be able to remove existing markers, modify data, edit a map's user interface or even to update user permissions. To resolve this, it would be ideal if within the "user interface options", a map creator was able to hide all tabs on the right except for the geometry creation tabs (see highlighted in img below).
![image](https://user-images.githubusercontent.com/4475249/126718733-13c5df9d-8653-4c3f-b120-647b3d446e29.png)

Looking forward to feedback on this!

**Comment by yohanboniface** [comment]
Makes sense!

See also #584

**Comment by yohanboniface** [comment]
This should be a side effet of new permissions at datalayer level: if one user has write permissions on a datalayer but not on the map itself, they will not see those advanced buttons (in yellow in your screenshot).

So I'm closing as I think it answers the needs. Please reopen or comment if you think I'm missing something! :)
