### ISSUE TITLE
Request: password on layers

### ISSUE THREAD

**Issue by kimkochrasmussen** [umap-project/umap#931]
It would be a very nice feature if you could set a password for each layers on a map.

Using umap for treasure hunts, it would be really nice to provide participants with just one map/link, but then during the hike allow them to open up new layers...

So kindly take a "password on layers"-feaute into consideration for further updates.

Thanks in advance

**Comment by yohanboniface** [comment]
I'm closing in favour of #584 for all layer related permissions.
