### ISSUE TITLE
is there an API available?

### ISSUE THREAD

**Issue by Loki-Afro** [umap-project/umap#933]
I have hundreds of gpx tracks that i want to display on a map in a single layer, is there some easier official way to insert those other than doing it manually? :)

thanks for provided umap by the way!

**Comment by yohanboniface** [comment]
No official API, nope.
But when you add a layer, you should be able to select all your files at once, have you tried ?

**Comment by Loki-Afro** [comment]
oh, didn't knew that, yes that is enough for me, thanks for letting me know!
