### ISSUE TITLE
GeoJSON strange data parsing add an extra symbol

### ISSUE THREAD

**Issue by alex-roc** [umap-project/umap#934]
I uploaded a valid GeoJSON with a url for an image:

```
"properties": {
        "Postulante": "Alex Ojeda",
        "Tema": "Contaminación por residuos de industria zapatera de la Laguna Alalay",
        "img": "https://upload.wikimedia.org/wikipedia/commons/8/88/Laguna_Alalay_y_la_Ciudad_de_Cochabamba_Bolivia.jpg",
        "name": "Laguna Alalay"
      }
```
And then apply the following default template:

```
{{img}}
{Tema}
**Nombre:** {Postulante}
```

And uMap doesn't display correctly the image attribute:

![Captura de Pantalla 2021-07-28 a la(s) 22 10 55](https://user-images.githubusercontent.com/10243925/127420718-f1d28fc6-b2a3-4ed1-a8ab-2127418bb73f.png)

The issue seems to be that uMap add at the end of the URL an extra symbol "}', which cause an error of displaying the image, as you can see in the HTML inspector:

```
<div class="umap-popup">
    <div class="umap-popup-content">
        <div class="umap-popup-container">{<a target="_blank"
                href="https://www.opinion.com.bo/media/opinion/images/2019/12/06/2019120615034034149.jpg}">https://www.opinion.com.bo/media/opinion/images/2019/12/06/2019120615034034149.jpg}</a><br>
            Contaminación por residuos de industria zapatera de la Laguna Alalay<br>
            <strong>Nombre:</strong> Alex Ojeda<br>

        </div>
    </div>
</div>
```
You can see the error for yourself here: [https://umap.openstreetmap.fr/es/map/image-error_641990#14/-17.4086/-66.1178](https://umap.openstreetmap.fr/es/map/image-error_641990#14/-17.4086/-66.1178)

**Comment by yohanboniface** [comment]
In your template, try `{{{img}}}` instead of `{{img}}` => you need three, one for reading the variable itself, and two for making an image from the value out of the variable.
