### ISSUE TITLE
Could not join the uMap's Transifex team for Malay (Arabic)

### ISSUE THREAD

**Issue by mnh48** [umap-project/umap#935]
I'm trying to join the Malay (Arabic) team to start translating, but it is not listed under "join team"
![2021-08-01_19-19-06_vivaldi](https://user-images.githubusercontent.com/12217018/127769122-8a0ca8ed-55e4-4cb7-81db-76b6e9d53031.png)
![image](https://user-images.githubusercontent.com/12217018/127769048-88adcfa5-ab31-4a86-84c4-d8e428665181.png)

It says to create request for the language if it doesn't exist, but it is already added so I can't request it
![2021-08-01_19-18-42_vivaldi](https://user-images.githubusercontent.com/12217018/127769078-f12b801e-639d-4509-848d-32e710ffe95c.png)

"Malay (Arabic)" is Malay language written in Arabic-based script known as [Jawi script](https://en.wikipedia.org/wiki/Jawi_alphabet), Jawi script has co-official status alongside Latin script in Brunei and a few states in Malaysia, it is taught in school and used in daily life.

(note that my keyboard got stuck and I hit 'enter' before finishing sentence early on)

**Comment by yohanboniface** [comment]
Seems to be ok now, please ping me if not.

Note that I'm not sure uMap will handle correctly an RTL language yet :(
