### ISSUE TITLE
ERROR 403 - Could not add object on map for iframe - x-csrf-token cookies

### ISSUE THREAD

**Issue by alexandreK34** [umap-project/umap#936]
Hello, First of all, thx for your great work.

I have an issue on UMAP frame on our website. 
It seems that some cookies are not sended, then UMAP lock the update mode on the frame.  
When i use the same map without the frame on our website, directly on the umap website, there is no problem for update or create geometric object.

The error message drop in french langage because i am french : 

**Interdit (403)
La vérification CSRF a échoué. La requête a été interrompue.
Vous voyez ce message parce que ce site exige la présence d'un cookie CSRF lors de l'envoi de formulaires. Ce cookie est nécessaire pour des raisons de sécurité, afin de s'assurer que le navigateur n'ait pas été piraté par un intervenant externe.
Si vous avez désactivé l'envoi des cookies par votre navigateur, veuillez les réactiver au moins pour ce site ou pour les requêtes de même origine (« same-origin »).
Des informations plus détaillées sont affichées lorsque la variable DEBUG vaut True.**

When i'm looking why, it's seem to be about the x-csrf-token cookie for security.
We used umap quiet often and we never had this error.
Someone can help me to fix it or give me some clue to solve the problem ?

Thx

**Comment by alexgitENI** [comment]
Hello,

I currently have the same problem, has anyone found a solution?

Thank you very much for your help.

**Comment by yohanboniface** [comment]
If you still have the issue, can you provide a way to reproduce ? Thanks!

**Comment by yohanboniface** [comment]
Please reopen if you still need help.
