### ISSUE TITLE
Remote Data is not displayed

### ISSUE THREAD

**Issue by IeP4nieF** [umap-project/umap#937]
Hi,

I'm trying to use remote Data in an umap map. The remote data is for example [here](https://www.sailing-snootyfox.de/snooty_fox_linestrings.json). But when I put this url into the Remote Data->Url field, nothing happens. Really nothing. Also there is no error message, if I use an incorrect Url.

So why doesn't umap use the remote data? Why fails it silent?

BTW: I can paste the same data in the "Pate your data here"-field in the Import Data tab and everything works.

Let me know, if you need more information.

**Comment by davidbgk** [comment]
Hi @IeP4nieF the remote data now leads to a 404 so I cannot reproduce, feel free to reopen the issue if you still have the problem.
