### ISSUE TITLE
Feature request: Add search to make adding node markers easier

### ISSUE THREAD

**Issue by antgel** [umap-project/umap#938]
Typical use case, say I'm planning a holiday. I'm reading blogs and I have tens of places I want to mark on the map. 

With another map provider who shall remain nameless, I type the place name in the search box, then I'm two clicks away from adding it to a collection of markers.

With Umap, if I understand correctly, I have to scroll to the right place on the map, click exactly on said place, then I have to type the place name in the Draw a Marker box. It's so much work, and worse, prone to human error.

It would be nice to have a search like on openstreetmap.org, then when the place is found, a simple click to add the marker.

**Comment by yohanboniface** [comment]
When you are in edit mode, there is a pen icon near each search result that will add a marker.
