### ISSUE TITLE
Suppression du tracé après scission

### ISSUE THREAD

**Issue by AZWCI** [umap-project/umap#940]
Bonsoir.

En éditant un tracé avec l'outil ligne d'uMap, si je ne quitte pas l'outil avant de cliquer sur le bouton "Enregistrer", je perds la totalité du tracé que j'éditais... Je ne pense pas que ça a toujours été le cas.

**Comment by yohanboniface** [comment]
Fort ennuyeux!
Quel navigateur et version ?

**Comment by AZWCI** [comment]
:) En effet. Ce problème n'avait été que temporaire (et ne c'était pas reproduit depuis bien longtemps) J'ai moi-même dû oublier de "fermer".
