### ISSUE TITLE
markers names are not show while printing a map with MyOSMatic

### ISSUE THREAD

**Issue by claude1000** [umap-project/umap#941]
Hello 
markers (waypoints) names are not show while printing a map with MyOSMatic

I import the file : *.umap into MyOSMatic and print

thanks for helping

**Comment by davidbgk** [comment]
We need to have access to the umap file to be able to debug that one. Please drop it in the comment section.

**Comment by yohanboniface** [comment]
I'd say this is something that should be handled on MapOSMatic side. AFAIK, they import data from umap files, not style (but certainly uMap should have a documented format or use a standard such geojsoncss for this to work better).

But for this given issue (showing the names), I guess we can't do anything on our side. Feel free to reopen if I'm wrong!
