### ISSUE TITLE
Add satellite ¨flanders¨ to the background map list

### ISSUE THREAD

**Issue by timtilburgs** [umap-project/umap#942]
Can you please add the flemish satellite background to the default background map list?

http://tile.informatievlaanderen.be/ws/raadpleegdiensten/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=omwrgbmrvl&STYLE=&FORMAT=image/png&tileMatrixSet=GoogleMapsVL&tileMatrix={z}&TILEROW={y}&TILECOL={x}

kind regards

Tim

**Comment by yohanboniface** [comment]
Hi @timtilburgs and sorry for the late answer.
uMap itself does not come with any tilelayer, but those are selected by each instance.

The OSM France instance (https://umap.openstreetmap.fr) may add it (ping @cquest), but it may also make sense to have a local umap instance. If you have an OSM chapter we may assist you in installing a uMap with more accurate settings for your needs.

Also, you  can still have a custom background layer in your map:

![image](https://github.com/umap-project/umap/assets/146023/eca4e7d2-0186-4ad5-8783-c1dfb48962fe)
