### ISSUE TITLE
Lost key to map, please link to account

### ISSUE THREAD

**Issue by jazmichaelking** [umap-project/umap#943]
Hi, I have a map at http://u.osmfr.org/m/550053/ that I have somehow lost access to. Several searches pointed me here to request the map be linked to my account (via Github) jazmichaelking - I understand I can download all the data and make a new one but this map has pretty decent coverage on Mastodon and I'd very much like to preserve the URL if possible.

Thanks in advance,

Jaz

**Comment by jazmichaelking** [comment]
Update, I've re-created the map at https://umap.openstreetmap.fr/en/map/mastodon-near-me_828094 - can you please remove http://umap.openstreetmap.fr/en/map/mastodon-near-me_550053 as it is coming up in Google searches, much appreciated/merci bien.

**Comment by yohanboniface** [comment]
Done! Sorry for the huuuuge lag!
