### ISSUE TITLE
Question or FeatureRequest: WFS support

### ISSUE THREAD

**Issue by goback136** [umap-project/umap#944]
Umap makes it very easy to create data layers which I love.

You can download and export all the created data for example as a geojson 
http://umap.openstreetmap.fr/nl/datalayer/1879566/

This is great for one-time downloads, but are there possibilities to download the data through WFS (Web Feature Service)

With this format I can ask data managers to maintain their data on Umap and show or centralize their data layers on other platforms.

**Comment by yohanboniface** [comment]
Closing in favor of #1522
