### ISSUE TITLE
All data gone from map

### ISSUE THREAD

**Issue by AhmedoSemsuri** [umap-project/umap#954]
Hi guys, so I've spent a lot of hours on [this](https://umap.openstreetmap.fr/da/map/bakur_652977) map plotting hundreds of layers into the map. This morning I continued the work, and then suddenly everything disappeared. I've been using UMAP since 2015 and I have never experienced this before. I've tried recreating older versions under layer setting but still no data shows up. I'm also pretty sure I didn't delete anything myself by mistake. So my question is how can I retrieve all (or some) of my data? It's so frustrating having used so much time on this map and then everything is gone in one second.

**Comment by AhmedoSemsuri** [comment]
![image](https://user-images.githubusercontent.com/51060987/133926555-86ef973c-12fa-4769-a701-acb5d3075b76.png)

There seem to be some data saved (the 416.xxx kb) but when I save those versions, nothing happens)

**Comment by niklasliebig** [comment]
Today I discovered that the same thing happened to my maps. All data seem to be lost. It simply says: "niklasliebig has no maps."

**Comment by niklasliebig** [comment]
Yay, today all maps came back again. Anyone knows whats behind this?

**Comment by yohanboniface** [comment]
Hey @AhmedoSemsuri sorry to hear that! I guess since then you have moved out, but if you still need help, please reopen, we'll be more reactive this time.
