### ISSUE TITLE
Zoom To Coordinates 

### ISSUE THREAD

**Issue by ThePieMonster** [umap-project/umap#956]
I see there is no option to paste in a set of coordinates in the search bar or some other field and have the map zoom to that location. 

Basically we need a feature that accomplishes what this plugin does for the QGIS software.
https://plugins.qgis.org/plugins/latlontools/

**Comment by googie0815** [comment]
Yes, just like google maps. for example, enter 48.0543, 10.0362 and a pin will be placed at the corresponding location.
