### ISSUE TITLE
Add Google TileLayers

### ISSUE THREAD

**Issue by ThePieMonster** [umap-project/umap#957]
The below are the URLs for the Google Tile Layers that are not present in the tile layers list in UMap currently. It would be great to see these added, especially a satellite view as there are currently no proper satellite view options.

![image](https://user-images.githubusercontent.com/11359134/136846058-3cdbbf3e-ce04-4188-99e4-0750ee77b19c.png)

**List**

Roadmap
http://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z} 

Terrain
http://mt0.google.com/vt/lyrs=p&hl=en&x={x}&y={y}&z={z}

Altered roadmap
http://mt0.google.com/vt/lyrs=r&hl=en&x={x}&y={y}&z={z}

Satellite only
http://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}

Terrain only
http://mt0.google.com/vt/lyrs=t&hl=en&x={x}&y={y}&z={z}

Hybrid
http://mt0.google.com/vt/lyrs=y&hl=en&x={x}&y={y}&z={z}

**Comment by yohanboniface** [comment]
Hi @ThePieMonster and sorry for my late answer.

uMap itself does not come with any tilelayer, but those are selected by people running a given instance. I don't think the OSM France instance will add those layers (ping @cquest ?), but you may decide to host an instance by yourself or with your local OSM chapter/collective.

Also, remember you can still have a custom background layer in a map:

![image](https://github.com/umap-project/umap/assets/146023/bac88ba1-871f-4f1e-b3b3-cda16721124f)
