### ISSUE TITLE
Request for input on uMap academic article

### ISSUE THREAD

**Issue by maphouse** [umap-project/umap#960]
Hello umap community,

Some colleagues and I are writing an academic paper on uMap and we are wondering how uMap is funded / what funding the project has received in the past (if any). **Any information on this would be very welcome!**

In addition, **we would really appreciate any comments, clarifications or critiques** (in French or English) from the developer community on the article more generally. If you are interested in reading the paper, please leave a comment here or send an email to the lead author at `sepideh.shahamati@gmail.com` so that we can send you a copy of the latest draft!

Merci!

**Comment by yohanboniface** [comment]
hi @maphouse 

> Some colleagues and I are writing an academic paper on uMap and we are wondering how uMap is funded / what funding the project has received in the past (if any). Any information on this would be very welcome!

The development of uMap is 99% volunteering. As far as I can remember, only one feature (remote data) has been funded (by Ixxy Mobility, RATP group).

https://umap.openstreetmap.fr is supported by the OSM France chapter.

> In addition, we would really appreciate any comments, clarifications or critiques (in French or English) from the developer community on the article more generally. 

I'll try to have a look!
