### ISSUE TITLE
Search for location not reliable

### ISSUE THREAD

**Issue by Dirk71** [umap-project/umap#961]
Searching for locations (cities) does often not work. Even big cities are often missing in the search results.

**Comment by yohanboniface** [comment]
Can you be a bit more explicit ? Some example would help.
Note that uMap is using Photon under the hood, with location bias (closer results have more weight).

**Comment by Dirk71** [comment]
Example: I am searching for the city "Soest"....no results appear. If I search for "Bad Sassendorf" which is close to Soest, I get results. Or I try to find the city "Fulda"...and I don't get any results for this city. Instead I get streets with this name but not the city as search result.

**Comment by Dirk71** [comment]
...by the way....good you have an eye on uMap....looking forward for some enhancements. Thank you, Yohan for this!

**Comment by googie0815** [comment]
i can confirm this. The search often does not find the city you are looking for, regardless of the size of the city. I am also not entirely clear about the presentation of the results. when I search for a city, it shows me all sorts of things, the city I am looking for appears somewhere in the list or not at all.

**Comment by davidbgk** [comment]
You might want to report issues about Photon here: https://github.com/komoot/photon
