### ISSUE TITLE
Django version in requirements

### ISSUE THREAD

**Issue by kkuczkowska** [umap-project/umap#963]
Hello, 
Is there a way you could replace hardcoded Django version in requirements.txt with a little more flexible condition, for instance `Django>=3.2`? 
It would make upgrading larger applications using umap a lot easier.

Thanks!

**Comment by yohanboniface** [comment]
@kkuczkowska could describe a bit more your usage of uMap ? What's the larger application you're talking about ? We are in the process of migrating to Django 5.x, and I remember your request, so I'm asking for my understanding, so we could better decide which version of Django to support or not. Thanks! :)
