### ISSUE TITLE
Icône "gérer les calques"

### ISSUE THREAD

**Issue by AntoninCurtit** [umap-project/umap#966]
Salut !
Je suis peut-être le seul confronté à ce souci : **Confondre les icônes pour changer le fond de carte, et gérer les calques**.
Mais dans le doute (et car ce souci perdure pour moi), j'ai essayé avec une autre icône.

Bonne idée ?

![image](https://user-images.githubusercontent.com/30950182/142038777-fc6e1b1d-5414-4746-8ab7-f1b61225a837.png)

**Comment by yohanboniface** [comment]
Hello @AntoninCurtit Désolé de n'avoir pas répondu plus tôt.
Je partage le fait que les icônes sont très proches et pas très parlantes en elles-mêmes.
Maintenant je suis pas sûr que ta proposition résolve complètement le problème.
Pour avancer, je pense que le mieux serait de voir un peu ce que font les autres logiciels équivalents, et s'appuyer sur des icônes qui semblent entrées dans les habitudes.
