### ISSUE TITLE
Default images are small and have big difference in sizes. Custom width doesn't work.

### ISSUE THREAD

**Issue by forteller** [umap-project/umap#967]
Hi. Thanks for an amazing product! It is extremely useful and much needed.

I'm trying to embed images in different places around my map of where there should be more flowers around my city. Some of the images I embed with just {{http://image.url.com}} shows up small, while others show up very, very small:

![Screenshot from 2021-11-23 19-21-49](https://user-images.githubusercontent.com/343561/143082393-bebb06b4-5465-4271-b185-5df885dbfc04.png)

All are embedded in the same way from originals that are the same size, hosted on imgur. It seems like they should have the same size when embedded, and larger than they are now.

I tried making them larger with {{http://image.url.com|width}}, but nothing changed. I tried putting in {{http://image.url.com|500}} and 600, 700 and 800, all of which are much larger than default, but nothing happened. 

Here's my map, if that's useful: https://umap.openstreetmap.fr/no/map/blomster-og-bier_607275

If there's any more info I can give to help, let me know.

Thank you again!

**Comment by HostEis** [comment]
A year ago I had the same problem as described.
In the meantime, I have created a new test map in my account "hoeis" (Openstreetmap), where entering {{http://bild.url.com}} causes a decent, large image to appear on the screen. So I was initially satisfied that the image size, which could not be changed at the time, was again of an acceptable size (uMap software update?).
Then I reduced a new pup-up image to 200 pixels with {{http://bild.url.com|200}}, which worked the first time. Unfortunately, however, a very small PupUp picture.
Now came the big disappointment. No matter what I did, all new images stayed that small (200 pixels) no matter if I used {{http://image.url.com}} or {{http://image.url.com|width}}. This was the same with new test maps, even after logging out and in with new test maps, after deleting all cookies in my Thunderbird browser, and after creating a new map in "anonymous-edit" mode.

**Comment by forteller** [comment]
Thanks!

For me they are also now bigger than they where, and also more consistently the same size. Still, I do feel like they should be a little bigger than they are?

![image](https://github.com/umap-project/umap/assets/343561/9b946b24-2fb5-482a-bae1-f9a59d6453ff)

**Comment by davidbgk** [comment]
> For me they are also now bigger than they where, and also more consistently the same size. Still, I do feel like they should be a little bigger than they are?

What is the resolution/size of your screen? Because on a 27" (5120 × 2880) it does look quite adapted:

![Capture d’écran, le 2023-06-27 à 14 43 54](https://github.com/umap-project/umap/assets/3556/904daa73-1d76-4097-8385-120fc3d1aa25)

**Comment by yohanboniface** [comment]
Closing, please reopen or comment if you have more info to provide! :)
