### ISSUE TITLE
Feature Request: Select building/area pre-existing in OSM

### ISSUE THREAD

**Issue by tiziodcaio** [umap-project/umap#968]
Hello. It would be possible to select some areas already defined in OSM? Maybe it's a dumb question... maybe it could be implemented... I let you the issue so you can judge it

**Comment by yohanboniface** [comment]
Not sure to get the point. Can you give an example ?

**Comment by tiziodcaio** [comment]
If there is a park, can you color it blue and adding a label on my map?

**Comment by tiziodcaio** [comment]
It is clear? Or not? If not I can explain better.
I meant that it would be nice to create areas (lakes, parks, ...) based on the areas on OSM, without track them manually with polygon function.

**Comment by yohanboniface** [comment]
OK, now I understand!
The only way I see now is through overpass-turbo, either an URL or a json copy-paste.
From the search (when in edit mode), you can create point from a result, but this will not work for complex geometries.
Would be great to query overpass directly from uMap, but that means an overpass server that allow much more requests than what we can now.

**Comment by IgorEliezer** [comment]
> Would be great to query overpass directly from uMap, but that means an overpass server that allow much more requests than what we can now.

Perhaps, as an intermediary measure, a layer capable of storing a overpass query in a text field which can be executed only when the user needs to load or update the data. Something like: "Write Overpass Query" -> Execute -> "Save result as layer" or "Replace existing".

**Comment by yohanboniface** [comment]
We may use something like http://yohanboniface.github.io/Leaflet.RevealOSM/ to import object from OSM when clicking on the background. It's a bit magical, but it could help.
Also, when as search result is complex geometry, we could retrieve it instead of a single point.

**Comment by KaiRo-at** [comment]
Would be great if this isn't just for areas but for any feature as stated in #710 - I'm pretty sure that points/nodes would be the most common thing to be put on custom maps if you could click them and make a marker for them.

**Comment by yohanboniface** [comment]
Sure! Note that at the moment, when in edit mode, search results can be added to the map. It will be only nodes, and only features with name can be searched:

![image](https://github.com/umap-project/umap/assets/146023/f5dcc339-7fb3-43c0-adde-bf100e2e12c2)
