### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by coooperrr** [umap-project/umap#969]
Hi, It's a basic on drawing tools but it seems missing : "duplicate a layer" (with all its objects)
so you can easily illustrate diferent stages in a town planing project just deleting or giving diferent colours to objects.

With a great thank you to developpers

**Comment by yohanboniface** [comment]
This should be available through the "Clone" button:

![gnome-shell-screenshot-M05YE1](https://user-images.githubusercontent.com/146023/147581235-2a921b55-ffb3-4d75-8b23-adc688ef5785.png)
