### ISSUE TITLE
 OpenStreetMap.de basemap, wrong link in attribution

### ISSUE THREAD

**Issue by hamlet** [umap-project/umap#975]
Hi,
as can be seen in this [umap](https://umap.openstreetmap.fr/de/map/spielplatze-samtgemeinde-fredenbeck_681338#12/53.5302/9.3844), the basemap is "OSM Deutschland (OSM-DE)", the attribution text is correct ("Courtesy of OpenStreetMap.de") but it points to https://www.openstreetmap.fr/.
Probably not a big deal, but a bit awkward.
Regards

**Comment by Bibi56** [comment]
Please give the correct URL or even better make a PR ;-).

**Comment by hamlet** [comment]
I guess https://www.openstreetmap.de/ would be fine. 
I wanted to make a PR, but I couldn't find the tile layers' list in the code.

**Comment by davidbgk** [comment]
As far as I know, this is not part of uMap's codebase. You have to contact administrators of openstreetmap.de because it's a setting of the deployed instance and we have no control over it.

**Comment by hamlet** [comment]
> As far as I know, this is not part of uMap's codebase. You have to contact administrators of openstreetmap.de because it's a setting of the deployed instance and we have no control over it.

Actually this bug report is about a [map](https://umap.openstreetmap.fr/de/map/spielplatze-samtgemeinde-fredenbeck_681338#12/53.5302/9.3844) on the french instance. Is the umap mailing-list a better place than here ?

You mean the administrators of umap instances have to fill all the tile layers information including attribution ? I thought there was some kind of default list...

Best regards.

**Comment by yohanboniface** [comment]
Yes, tile layers are a per instance configuration (through the admin). I've fixed the link! Thanks for the report.
