### ISSUE TITLE
[Feature suggestion] Enable umap to embed more than one dynamic (tiled) background map

### ISSUE THREAD

**Issue by Wikinaut** [umap-project/umap#976]
### Situation:
I use ```umap``` with a self-defined, tiled background map for a certain area, and of course several annotation layers.

### User needs:
I wish to overlay (or underlay) this first background map (my own tiles from my server) with a certain opacity (let's say, 50%) with a second background map like public OSM-DE.

Currently, I do not see a mechanism or method how this could be achieved directly, and live, using ```umap```.

See also https://twitter.com/Wikinaut/status/1480307131177918467?s=20

### Circumvention, ad-hoc solution:
An ad-hoc solution would be to define a kind of "proxy map server", another server, who merges tiles from the first and the second background maps, however this is not target of my issue report.

### Feature suggestion/request:
Enable umap to embed, to render more than one dynamic background map.

**Comment by davidbgk** [comment]
Closing the issue since a fix has been provided two months ago.
