### ISSUE TITLE
imprécision aide contextuelle

### ISSUE THREAD

**Issue by collectionappareils** [umap-project/umap#981]
Bonjour, 

dans les propriétés d'un calque / options d'interaction/ gabarit du contenu de la popup, l'aide contextuelle (le point d'interrogation) indique  Image : **{{http://image.url.com}}**. En fait il faut une paire d'accolade {} dans le gabarit lui-même et une double paire {{ }} dans le fichier .csv, ce qui revient à avoir trois paires d'accolade et non deux. Serait-il possible d'avoir une explication plus précise dans l'aide contextuelle pour éviter toute ambiguité ?  Merci

A part cette remarque, c'est super, j'ai obtenu exactement ce que je cherchais  :http://www.collection-appareils.fr/carte_interactive/html/carte_interactive_bis.php  (certaines épingles ont un logo)

**Comment by Bibi56** [comment]
> certaines épingles ont un logo
Par exemple ici : http://umap.openstreetmap.fr/fr/map/marques_699575#11/43.7309/7.3389

**Comment by yohanboniface** [comment]
Ça pourrait être documenté en effet, mais c'est un cas assez avancé et on n'est pas sûr qu'il faille surcharger cette box d'aide avec ça.
Par ailleurs, c'est normal que la documentation ne parle que de deux accolades. En effet, il faut utiliser deux accolades pour afficher **une image à partir d'une URL**. Dans le cas où cette URL n'est pas écrite directement entre les accolades mais vient d'une variable, alors il faut une paire d'accolades de plus pour lire cette variable.
Donc:
    {{https://vers.exemple.com/image.png}}
Ou:
    {{{variable_contenant_url}}}

Au passage, dans ta carte, je vois que tu as mis les accolades directement dans le champ `url`, c'est à mon avis pas la bonne façon de faire: il faut laisser l'URL telle quelle dans le champ, et bien mettre trois accolades dans le template.

Merci néanmoins pour le retour! :)
