### ISSUE TITLE
Wrong url on embed code

### ISSUE THREAD

**Issue by luferra** [umap-project/umap#983]
Hi, 
on the `src` attribute on the embed code the prefix _https_ is missing. As you can see from this short code `<iframe width="100%" height="300px" frameborder="0" allowfullscreen src="//umap.openstreetmap.fr/it/map/....`.

I've tried to embed it on a custom html block on a Wordpress website but I've encountered some issues (maybe the issues where taken by the cerberus plugin).

Is it possible to kindly fix it?.
Thanks
Cheers
LF

**Comment by Marc-marc-marc** [comment]
a url without hardcoded protocol allow to have it working no matter the site use http or https
as you are using the osm-fr instance, try to add https: before the //

**Comment by davidbgk** [comment]
I'm closing it since a solution has been provided, feel free to reopen this issue if the problem persists.
