### ISSUE TITLE
Create a new pip release

### ISSUE THREAD

**Issue by tordans** [umap-project/umap#984]
For umap.openstreetmap.de we are using the pip release of umap.

The last release there is from Nov 2020 https://pypi.org/project/umap-project/#history.

Would it be possible to create a new release? I would appreciate having the changes from https://github.com/umap-project/umap/pull/971 live for my project.

---

A few related questions:

- Should we add a headline on the README about the pip process?

<details><summary>Here is a quick text suggestion to comment on…</summary>

> ## Release & installation
> You can install umap via pip
> ```
> pip install umap-project
> ```
> Releases are done from time to time by _UserName_.

</details>

- I found it a bit confusing to have the Release and Packages section active in the Repos-Sidebar. I suggest deactivating them, since they are not used AFAIK.

<details><summary>Here is a screenshot of where to deactivate them…</summary>

<img width="990" alt="image" src="https://user-images.githubusercontent.com/111561/156604877-676b7b6f-ab99-44a4-838c-cb07df8e1bb8.png">

</details>

**Comment by tordans** [comment]
@yohanboniface the last (PIP) release is 17 month old. Do you still plan to use this release process? Or should we switch to using master for umap.openstreetmap.de? – It would be great to get the new features online there…

**Comment by ldidry** [comment]
Ping @yohanboniface

**Comment by ldidry** [comment]
Note that you can clone the repository, checkout the right tag and do `pip install /tmp/umap` (change the directory to where you cloned the repository, of course).

**Comment by ldidry** [comment]
Well, in fact, we got the new release on Pypi! https://pypi.org/project/umap-project/1.2.4/

Thank you, @yohanboniface 😘
