### ISSUE TITLE
Add more than one custom background?

### ISSUE THREAD

**Issue by easz** [umap-project/umap#986]
is it possible to add more than one custom background (i.e. base map layer)?

**Comment by rugk** [comment]
This would be great for [OpenRailwayMap](https://wiki.openstreetmap.org/wiki/OpenRailwayMap), as the default site https://openrailwaymap.org uses the default (OSM) tiles as a background and then their [own tiles](https://wiki.openstreetmap.org/wiki/OpenRailwayMap/API) on top of them.

So if you want to use that background on uMap, you kinda get railways without any country data or so, which is… problematic I'd say…

**Comment by yohanboniface** [comment]
Done in [1.3.0](https://umap-project.readthedocs.io/en/latest/changelog/) release
