### ISSUE TITLE
deleting a map created without an account

### ISSUE THREAD

**Issue by wikihousing** [umap-project/umap#988]
Hello,
I am new to umap. So I didnt know that I will publish the map and wont be able to edit it anymore. I created 2 maps called "WikiHousing Barcelona" with and without an account. Is there any way to delete the one created without an account?

Please help
Thanks 
Merve

**Comment by TLC78-gif** [comment]
Hi , Wikihousing. I have the same pb. Do you found a solution 
? Best, Tanguy

**Comment by davidbgk** [comment]
Hello,

As maintainers of an open-source project deployed in many locations/servers, we do not have access to the data of the instance where you created your map.

Please contact the support of your instance specifying your request.
