### ISSUE TITLE
Usernames with special characters not found

### ISSUE THREAD

**Issue by Hedaja** [umap-project/umap#989]
Hi
I recently created a new OSM account. It had a **:** as special character in it. I than tried to add this account as an editor to my umap but it could not be found in the list, when I typed it it. 
Logging in with it and using umap on its own worked fine though.

So I deleted the account and created a new one without the : 
The new account was found in the editor list immediately.

It therefore seem that umap has an issue finding users when they have certain special characters (- seems to work fine).

**Comment by davidbgk** [comment]
Hi @Hedaja,

We are relying on the [django-agnocomplete](https://github.com/peopledoc/django-agnocomplete) Python package for that, this is a bug to report upstream.

And honestly I'm not sure if it's a bug or a feature to keep the `:`  character out of the search terms to be able to implement [more advanced search filters](https://danlamanna.com/posts/building-search-dsls-with-django/).
