### ISSUE TITLE
Deletion Umap Edition link

### ISSUE THREAD

**Issue by TLC78-gif** [umap-project/umap#991]
Hello,

I accidently lost the edition link of a Umap created without an account.
Is their a way to recover it ?

Thank you,
Tanguy

**Comment by davidbgk** [comment]
Hello,

As maintainers of an open-source project deployed in many locations/servers, we do not have access to the data of the instance where you created your map.

Please contact the support of your instance specifying the URL of the map, the time and the browser you used to create it, they might be able to help you. See for example the [documentation of framacarte](https://contact.framasoft.org/en/faq/#carte-lost-edit) on that topic (which might not be _your_ instance).
