### ISSUE TITLE
By deleting layers, anonymous users can destroy the map history

### ISSUE THREAD

**Issue by mlell** [umap-project/umap#996]
Hi, 

I use umap for a map that a limited number of people will use to enter points of interest for our specific group. This is great, especially the anonymous access, which makes contributing very low-barrier! I have only one fear: The history system, which can be reached when clicking on the edit button of a layer, allows to recover from user error or vandalism. However, when deleting a layer, all its history is irretrievably lost. I think this is dangerous, as that can happen easily by mistake for unexperienced users. 

The remedy currently is to download and save the map data in regular intervals, however, this basically defeats the whole purpose of the history system as this is basically an offline history now. 

For us, a system like for etherpad lite would be optimal, where there is only one history for the whole map:

![image](https://user-images.githubusercontent.com/16210594/169842082-c17017b7-0940-4cae-9fe9-3a61e22b16b2.png)

**Comment by yohanboniface** [comment]
cf #584

**Comment by yohanboniface** [comment]
This should be fixed since 1.8.0, now it's possible to only allow editing one layer, without giving permissions to delete it nor change the map, etc.

See https://www.openstreetmap.org/user/David%20Larlet/diary/402475
