### ISSUE TITLE
Installation Error on Ubuntu 22.04 Server

### ISSUE THREAD

**Issue by Paris999** [umap-project/umap#999]
Hi People,
I installed a fresh ubuntu server 22.04 with all updates. than I installed all the pakets from the installtion manuell. I changed only the versions, because the old one are not available for 22.04.
`build-essential
autoconf
python3.10.4
python3.10-dev
sudo apt-get -y install python3-virtualenv
wget
nginx
uwsgi
uwsgi-plugin-python3
postgresql postgresql-client
postgresql-server-dev-14
postgresql-14-postgis-3
git
libxml2-dev
libxslt1-dev
zlib1g-dev`

when I come to the point from the installation manuall
`pip install umap-project`

it is starting, but it is failing with this message:
.....
     [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow
......

I think it could be that the software versions are to new for the umap installtion.
Is it possible to fix the problem or
I have to change to another Server with another software versions? Is it possible to tell me which software Versions are working?

Thx
Paris

**Comment by davidbgk** [comment]
Hi @Paris999,

We need more informations (like the complete log from pip) to be able to understand the underlying error, do you still have the issue?

**Comment by davidbgk** [comment]
Please reopen if the problem persist.
